### ISSUE TITLE
Crash While In Programmer GUI

### ISSUE THREAD

**Issue by Darkosto** [TeamPneumatic/pnc-repressurized#100]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
2587
### Mod Version
0.2.0-88
### Describe your problem, including steps to reproduce it
While working with a "block" condition puzzle piece and I clicked on the "search for air block" checkbox. The game froze up for a few seconds and crashed out with the following report:

https://pastebin.com/vqSU9qZ2

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Fixed - builds 117+ should work for you.

http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/117/
