### ISSUE TITLE
Upgrade crash 3.2.2-79

### ISSUE THREAD

**Issue by border999** [TeamPneumatic/pnc-repressurized#1003]
### Describe the bug

Crash on startup

### How to reproduce the bug

Pneumaticraft, create?, compressed creativity

### Expected behavior

no crash

### Which Minecraft version are you using?

1.18

### Crash log

https://gist.github.com/border999/c0d49afbdf901a01215c0463ea196da1

**Comment by border999** [comment]
https://crashy.net/3zbSoOyteRxLXaiTwDqJ

**Comment by Nyuraa** [comment]
I do have the same crash, seems to be a problem with CompressedCreativity, probably on their end?
When deactivated the world loads again.
Crash Report https://gist.github.com/Nyuraa/7cdfea83d856fb5b1e9378252bc11fbc
latest.log seems to be to big for gisthub
part of it with the Error: https://gist.github.com/Nyuraa/db018f029413d976e8f77dd4d6f0f7c4

**Comment by desht** [comment]
Yes, CompressedCreativity is accessing a non-API method which has been renamed.

I should probably expose that method via API...

**Comment by Lgmrszd** [comment]
I confirm that this is a problem on my end (https://github.com/Lgmrszd/CompressedCreativity/issues/3), released hotfix for now, but I should stick with API methods from now on :D
