### ISSUE TITLE
Drone's path seems to be overwrite by it's passenger (Zoglin)

### ISSUE THREAD

**Issue by EeveeTC** [TeamPneumatic/pnc-repressurized#1004]
### Describe the bug

Zoglin seems to be able to control the drone it's on.
Without additional puzzle pieces that trys to make it control the drone.
and it would interrupt any process the next puzzle pieces is trying to do.
[https://youtu.be/5t1X8Do6irM](url)

### How to reproduce the bug

![image](https://user-images.githubusercontent.com/105270751/167571037-0259f23e-bd8a-45d8-8c2e-318635eb3133.png)
Program a drone that import Zoglin, and let it chase you, it doesn't do the "Wait 5s" puzzle pieces.

### Expected behavior

The drone aren't supposes to be controlled by mob.

### Which Minecraft version are you using?

1.16

**Comment by desht** [comment]
Build 322 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ should fix this problem.  If you can do some testing on that, that would be helpful...

**Comment by EeveeTC** [comment]
Thank you for replying to the issue! 
But I found out the solution of using NoAI to limit mob control on drone might cause other issue, 
like Hoglin now no longer convert to Zoglin in overworld and mob has their head lock in a position.
The drone that was carrying mob from previous version seems to be able to control the drone now, because i believe the NoAI treatment is done during the importing entity process?
I don't think the head locking would be a huge issue, but the Zoglin conversion might be a bit inconsistence on a gameplay perspective?.

**Comment by desht** [comment]
That is true, conversion won't happen, but is that really a problem?  As soon as the drone drops off the mob again, the AI is re-enabled.

And yes, noAI is applied during the import process.  But wrenching and re-deploying the drone should fix that...

**Comment by EeveeTC** [comment]
Well... I guess it's fine. 
Just considering that some people may use drones to store their mob though.
But there shouldn't be too many people doing it anyway i guess?
Thanks for solving the issue.

**Comment by desht** [comment]
Fixed in 2.15.8 & 3.2.3 releases
