### ISSUE TITLE
Drone getting stuck on amethyst buds

### ISSUE THREAD

**Issue by Aazh** [TeamPneumatic/pnc-repressurized#1005]
### Describe the bug

Drone eventually gets stuck when programmed to mine and collect amethyst in an amethyst geode.
![2022-05-12_11 46 25](https://user-images.githubusercontent.com/32171775/168035586-12ef2a3c-1722-4191-a824-b79932a49dc4.png)

### How to reproduce the bug

![2022-05-12_11 55 31](https://user-images.githubusercontent.com/32171775/168034303-0e89fc55-aac4-4751-962b-b821266aab07.png)
Place budding amethyst and amethyst bud on the budding amethyst in creative.
Program drone to go to location to above budding amethyst and below black concrete.
Place drone on white concrete.

### Expected behavior

Drone avoids getting stuck on the amethyst bud.

### Additional details

Test setup seems to (not) work with all sizes of amethyst bud.

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
Actually a bug in vanilla: Amethyst Buds have a non-full block shape but are not marked as non-pathfindable (i.e. don't override the `isPathfindable()` method to return false).  ~~I created a Mojang bug for it: https://bugs.mojang.com/browse/MC-251636~~

https://bugs.mojang.com/browse/MC-181565

In the meantime I can probably add a workaround to force drones to avoid them...

**Comment by desht** [comment]
Fixed in 3.2.3 release
