### ISSUE TITLE
Security Upgrade fails when used with 8+ Speed Upgrades

### ISSUE THREAD

**Issue by snydej** [TeamPneumatic/pnc-repressurized#1006]
### Describe the bug

The Security Upgrade fails to prevent dangerous pressures in an Air Compressor when used with 8 or more Speed Upgrades.

### How to reproduce the bug

1. Place an Air Compressor and add a closed loop of pipe on it's output to contain the air.
2. Add 1 Security Upgrade and 10 Speed Upgrades to the Air Compressor.
3. Put fuel in the compressor.
4. Wait for things to explode.

### Expected behavior

The Security Upgrade should vent any excess air above 5 bars of pressure.

### Which Minecraft version are you using?

1.16

**Comment by desht** [comment]
Not really a bug, no.  A Security Upgrade vents air when over-pressure, and prevents the machine it's installed in from exploding.  It doesn't mean that excess pressure won't be fed to neighbouring blocks.

If you really want to run your compressors with 8+ Speed Upgrades:
* Get some good redstone control in place.
* Use liquid compressors, not air compressors.  They are much more controllable.
* Have a Security Upgrade in place in case of problems with redstone, and also in neighbouring blocks (Safety Modules for adjacent tubes, Security Upgrades for adjacent machines).

Security Upgrades make machines safer, but when you're running with that many Speed Upgrades, extra precautions need to be taken.

**Comment by snydej** [comment]
Telling me I should move my speed upgrades into an entirely different machine (the liquid compressor) really isn't helpful. What would be nice is if this "intended behavior" was mentioned somewhere. After my stuff blew up I tried to see if there was any way I could have seen this coming but according to the in-game descriptions of the upgrades it should not have happened.

Everybody's going to try 10 upgrades just because it's the max. It really just seems like you want the explosions to happen.

**Comment by desht** [comment]
I didn't say you should move your upgrades to a different machine.  I said if you're intent on using that many speed upgrades, you need to take extra care.

The GUI tab for security upgrades says:

> Adds a built-in safety valve to the machine, automatically releasing some air if the pressure would rise into the danger zone

It doesn't say that it prevents all explosions forever, but I guess I can make that more explicit in the GUI info if it makes you happy.
