### ISSUE TITLE
Heat Frame Error

### ISSUE THREAD

**Issue by bcrotty** [TeamPneumatic/pnc-repressurized#1007]
### Describe the bug

![image](https://user-images.githubusercontent.com/6155964/168331952-5ff58d51-4353-44df-a2f5-3528dc74ba8d.png)
When I use a Heat Frame, WAILA shows that there's an error. As I move the view around, a normal view of the chest showing the temperature and heating/cooling percentages will flash briefly, but it never says anything but the ambient temperature and 0%. Nothing happens inside the chest to the contents that should be heated or cooled.

### How to reproduce the bug

1. Create new MultiMC instance with Forge and Jade, JEI, Patchouli, PC:R
2. Give yourself a chest and a heat frame (optionally something to heat or cool and a hot or cold block)
3. Look at the chest and see an error
4. Wait and nothing happens

### Expected behavior

Heat Frame should heat or cool items as intended and status should show on WAILA

### Additional details

Versions:
Minecraft: 1.16.5
Forge: 36.2.31
LWJGL 3: 3.3.2 (automatically included with base installation through MultiMC)

Mod Versions:
Jade: 2.8.1
JEI: 7.7.1.152
Patchouli: 1.16.4-53.2
PC:R: 1.16.5-2.15.7-320

See attached file or linked log below. This is the only error log produced.
[WailaErrorOutput.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/8689613/WailaErrorOutput.txt)

### Which Minecraft version are you using?

1.16

### Crash log

https://pastebin.com/5M5NvYaT

**Comment by desht** [comment]
Looks like Jade does something that Hwyla (which I originally built against) doesn't, or vice versa.  Not necessarily a problem with Jade though.

I will build against Jade (which is a lot more up to date) and track this down.  Shouldn't be too hard to fix.

**Comment by bcrotty** [comment]
@desht Should blocks placed directly next to the chest with the heat frame affect the temperature? I tried blue ice and magma next to it, but nothing happened. It does work with a vortex pump though.

**Comment by desht** [comment]
No, non tile-entity blocks next to a heat frame won't do anything (the block needs ticking TE logic to transfer heat).  You can connect ice/magma/etc. to a heat frame with a heat pipe, though.

**Comment by desht** [comment]
Fixed in 2.15.8 release
