### ISSUE TITLE
Network node doesn't work

### ISSUE THREAD

**Issue by MrFesliYT** [TeamPneumatic/pnc-repressurized#1008]
### Describe the bug

When i try to put network node into the security station it doesn't allow me

### How to reproduce the bug

try to put network node into the security station

### Expected behavior

It allows

### Which Minecraft version are you using?

1.16

**Comment by MrFesliYT** [comment]
nice

**Comment by MrFesliYT** [comment]
Just tested now works!

**Comment by desht** [comment]
Fixed in 2.15.9 (1.16.5) and 3.2.4 (1.18.2) releases
