### ISSUE TITLE
Vortex Tube keeps face connected after rotating with Pneumatic Wrench

### ISSUE THREAD

**Issue by Lgmrszd** [TeamPneumatic/pnc-repressurized#1009]
### Describe the bug

When rotating Vortex Tube so that connected tube face becomes one of the heat faces, connected part stays rendered and does not disconnect after removing previously connected tube or placing other blocks.
Rotating block further doesn't update it either.

### How to reproduce the bug

Place Vortex Tube and any Pressure Tube next to it.
Rotate Vortex Tube with Pneumatic wrench so that one of the heat faces ends up in the tube face.

https://user-images.githubusercontent.com/16291541/169412375-f0a845e8-0b4f-446e-921a-1a2b0d62575f.mp4

### Expected behavior

Block State updates accordingly.

### Additional details

Seems like the problem is withing `updateShape` in `AbstractPneumaticCraftBlock`

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
Fixed in 3.2.4 release
