### ISSUE TITLE
Breaking a chest while import arm is reaching for something will crash your game (Server crash)

### ISSUE THREAD

**Issue by MrFesliYT** [TeamPneumatic/pnc-repressurized#1010]
### Describe the bug

The moment i try to break the chest/ barrel while import arm is reaching for it will crash your game

### How to reproduce the bug

Step 1) Make an assembly line
Step 2) Start any recipe
Step 3) Break the inventory while arm is reaching for it

### Expected behavior

It stops

### Additional details

Its a major bug as it crashes Server which can be a really bad for the host

### Which Minecraft version are you using?

1.16

### Crash log

https://pastebin.com/J8RHhD1Q

**Comment by MrFesliYT** [comment]
dude your fast

**Comment by desht** [comment]
Fixed in 2.15.9 (1.16.5) and 3.2.4 (1.18.2) releases
