### ISSUE TITLE
Logistics drones get stuck in scaffolding 

### ISSUE THREAD

**Issue by MuradAkh** [TeamPneumatic/pnc-repressurized#1011]
### Describe the bug

Logistic drones seem to get stuck when trying to go down scaffolding 
![2022-05-20_16 44 43](https://user-images.githubusercontent.com/31002977/169608257-fea71739-4ecc-483b-9b59-51f3fada9af6.png)

### How to reproduce the bug

make the logistics drone carry stuff between floors connected by scaffolding 

### Expected behavior

Drones should not pathfind through scaffolding or they should be able to go down

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
Guess they don't know that they need to be sneaking to go down...  anyway should be fixable one way or the other.  I'd prefer to make them able to descend, but just blacklisting scaffolding from pathing is a viable fallback option.

**Comment by desht** [comment]
Fixed in 2.15.9 (1.16.5) and 3.2.4 (1.18.2) releases
