### ISSUE TITLE
Using Give command to give unassembled and empty pcb causes ghost item to drop as well. 

### ISSUE THREAD

**Issue by DelviousCrafts** [TeamPneumatic/pnc-repressurized#1012]
### Describe the bug

When using the give command to give a player an unassembled or empty PCB it will give the item to the player with no problem, however, there will also be a ghost item that appears alongside it. This item never despawns and cannot be picked up. it just sits in the world forever.

### How to reproduce the bug

use the give command to give the player an unassembled or empty PCB. 

### Expected behavior

Just the item being given to a player when using the give command. 

### Which Minecraft version are you using?

1.16

**Comment by desht** [comment]
Confirmed

**Comment by desht** [comment]
Fixed in 3.2.4 release for 1.18.2 & in 2.15.9 release for 1.16.5
