### ISSUE TITLE
Drone "dig" action not executing properly in lua code

### ISSUE THREAD

**Issue by SkylarFernandez** [TeamPneumatic/pnc-repressurized#1015]
### Describe the bug

When using ComputerCraft to write lua code for drones the dig functionality does not seem to behave properly. When executing a goto command and then a dig command the drone will mine the one block under it but using the dig command with an addArea causes the drone to not execute or skip the dig command and remain in place doing nothing. 

### How to reproduce the bug

You can use the test program for digging an area written in the manual for how to use lua with drones located in this repo at the below path
src/main/resources/assets/pneumaticcraft/patchouli_books/book/en_us/entries/machines/drone_interface.json

### Expected behavior

The program referenced by the above link should behave as the description says it should by clearing out a large area specified by the addArea command instead of skipping straight to the standby phase at the end of the program.

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
I think there's a mistake in the book example, looks like it's missing a line (there should be a `m.setAction("dig")` in there too, after the area is set). I'll do some tests later and verify that.

**Comment by desht** [comment]
Yeah the example is bad, I will update the manual with a better one (and some more discussion about how it works)

**Comment by desht** [comment]
Fixed in 3.2.4 release
