### ISSUE TITLE
shift clicking network node causes crash

### ISSUE THREAD

**Issue by scottycool64** [TeamPneumatic/pnc-repressurized#1018]
### Describe the bug

if i shift click a network node into a terminal, the game crashes

### How to reproduce the bug

get a network node, and a security terminal with the 3 requirements and attempt to shift click it into the menu

### Expected behavior

it fails / places it in the menu

### Additional details

the game freezes and never recovers

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
Not seeing this problem.  Can you paste a screenshot of your security station GUI please, so I can see the layout when you try to shift-click?

Also I need to know the exact version of PNC you're using (name of the PNC JAR file in your mods folder is fine)

**Comment by desht** [comment]
Closed due to lack of response
