### ISSUE TITLE
Crude oil destroying blocks

### ISSUE THREAD

**Issue by VirtualGaming1** [TeamPneumatic/pnc-repressurized#1021]
### Describe the bug

oil been destroying stone like block. this have been killing some dungeons.

### How to reproduce the bug

just have the crude oil spawn and let it destroy the blocks.

### Expected behavior

oil should not destroy block and make endless fall of death.

### Additional details

MC version 1.18.2

### Which Minecraft version are you using?

1.18

### Crash log

N/A

**Comment by VirtualGaming1** [comment]
![image](https://user-images.githubusercontent.com/20447403/172068798-72ebd15e-8c2d-4777-939c-ba340f06daa0.png)

**Comment by VirtualGaming1** [comment]
![image](https://user-images.githubusercontent.com/20447403/172068811-75241ffa-0285-4068-8a51-d754b8c0f66e.png)

**Comment by desht** [comment]
Crude oil does not destroy blocks in any way, at all. Some other mod is causing this behaviour.

**Comment by VirtualGaming1** [comment]
well for some odd reason if it is effecting only this fluid

**Comment by VirtualGaming1** [comment]
well just heard from a friend of mine and well found out the pollution of the realm have a little feature that Most of the users did not even know. I will get to there issue and will link it to this. @desht any chance can you change this from completed to the other closed option till the issue is fully fixed.

**Comment by VirtualGaming1** [comment]
https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms/issues/191

**Comment by desht** [comment]
Interesting, I'd heard pother turned dirt/grass into coarse dirt when in contact with crude oil (which is fine), but I didn't realise it was actually destroying blocks (which is not fine IMO). If that's the case and it's not configurable, that is definitely something they need to fix asap.

**Comment by VirtualGaming1** [comment]
> Interesting, I'd heard pother turned dirt/grass into coarse dirt, but I didn't realise it was actually destroying blocks. If that's the case and it's not configurable, that is definitely something they need to fix asap.

I highly agree on that

**Comment by desht** [comment]
PoTR author has just released 6.0.2.1 of the mod which fixes this (rooted dirt - found in 1.17+ - was the block that was being destroyed).
