### ISSUE TITLE
Bug Report/Suggestion A/C Upgrade not working and cross-mod feature suggestion

### ISSUE THREAD

**Issue by Shibva** [TeamPneumatic/pnc-repressurized#1024]
### Describe the bug

It appears that due to the changes that were made with TAN that a number of things have happened

1: The upgrade recipe is now broken due to the removal of both the heat and cooling coil
2. Base functions seem to no longer be working and fail to maintain the temperature as it was said.

 

### How to reproduce the bug

Should be as smiple as testing the features with TAN. though this was testing in 1.18.2

### Expected behavior

Id expected for it to be able to work. I thought I was doing something wrong but after going back to an older version to see what I needed to do I found that its just broken

### Additional details

it should be noted that this may be the same case in 1.16 and other 1.18 versions though I cannot confirm; at the most the recipe still being broken

ADDONAL SUGGESTION:

It seems another mod "Cold Sweat" has means of player temperature mechanic in its own way yet still works like TAN. It might not be a bad idea to have the module also work for the mod as well

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
There's no support for TAN in 1.18, at all.  TAN went completely closed-source, and changed their API, and for both of those reasons, I don't really feel like adding support again.

Although the Air Conditioning Upgrade is still an item, there's no recipe, for obvious reasons.

I am considering Cold Sweat integration.
