### ISSUE TITLE
Fluid Dupe

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#1028]
### Describe the bug

Just relaying from here as requested: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4988

### How to reproduce the bug

N/A

### Expected behavior

N/A

### Additional details

>Just happened to notice this so I'll save you some time by stating this one's on PNC.

>Any PNC fuel in any container item is admissible as furnace fuel, which is intended behaviour. However there are a couple of bugs right now:

>The container is always considered to have 1 bucket of fuel for determining burn time, regardless of the actual amount.
Not all container items actually support being used as a smelting input like this (specifically item.hasContainer() must be true). Mekanism tanks are an example of such a container item (not a Mekanism bug, I should stress). Such items should be disallowed from being placed in the Furnace fuel slot.
I do not see the behaviour mentioned above (always returning an empty bucket); that might be down to the item in particular, but PNC tank items always return themselves with (up to) 1000mB of fuel removed.

>I will be remedying this in the next PNC release; if you want to forward me on an issue as a reminder, that would be fine :)

### Which Minecraft version are you using?

1.16

**Comment by desht** [comment]
Fixed in 2.15.10 & 3.3.1
