### ISSUE TITLE
Allow Gas Lift to be used as a geothermal well

### ISSUE THREAD

**Issue by EnderiumSmith** [TeamPneumatic/pnc-repressurized#1029]
### Describe the feature

Currently the Gas Lift tops out at 90 meters but due to the recent world height increase that can no longer reach the bedrock. This makes it unable to pump lava should the player want. While increasing the max pressure to 10 would allow it to reach, currently the only machine that can generate at that pressure is the thermal generator, but since it freezes lava into obsidian instead of stone, it would be quite annoying to restock. Lowering the gradient would be a better option. 

Also making it able to accept range upgrades would be useful since its range is quite short

### Reasons why it should be considered

Before the height update the lift would have been able to reach the bottom with some margin, so it should be updated to account for that. actual pumps are rare in mods due to the high complexity and this is the only one that can also drill that i found.

**Comment by desht** [comment]
Yeah, fair point about the world height.  I'll have a think about that.

Other options for powering the Thermo Compressor btw include Magma (freezes to Netherrrack), or campfires (need relighting but that can be automated).  Or if you have Mek or IE, Uranium blocks (not very hot but last for ages).

**Comment by desht** [comment]
For now at least, I'm going to go with a simple solution: Gas Lift minimum pressure requirement to be capped at 4.9 bar, regardless of current depth.

I might make the Gas Lift a tier 1.5 machine in 1.19, but not decided on that yet.

**Comment by EnderiumSmith** [comment]
making the gradient half as steep would be a better solution. capping it would allow it to work from world height.

**Comment by desht** [comment]
Fair point.

**Comment by desht** [comment]
Fixed in 3.3.0
