### ISSUE TITLE
Vortex Cannon votexes spawn incorrectly for left hand

### ISSUE THREAD

**Issue by TeamSpen210** [TeamPneumatic/pnc-repressurized#103]
### Describe your problem, including steps to reproduce it
The vortexes emitted by the cannon spawn offset to the right, so they appear to come out of the item model. However, this is not flipped when held in the left hand so it appears totally incorrectly. This occurs either if you hold it in the offhand with right-hand mode, or in the main hand in left-hand mode.

Note Vanilla throwables come from the center of the player actually, so they don't need to worry about this. It

**Comment by TeamSpen210** [comment]
Same issue with the handheld Minigun.

**Comment by desht** [comment]
Confirmed.  Both rendering issues rather actual wrong entity positioning; the vortex actually does spawn centrally, but is rendered with an X offset to appear to be coming from the right-hand side.  This was fine in 1.7.10 of course, where there wasn't an offhand.

Simplest fix is probably to drop the offset and have it render centrally; it's consistent with vanilla behaviour at least.  Alternatively the "handedness" will need to be encoded with the vortex, which is more work.

MInigun rendering is done separately, and the draw position of the lines needs to be modified depending on which hand is in use.  Note that the minigun doesn't allow firing from the offhand (justification: it's a big heavy gun...), but this still needs to be fixed for left-handed players using the main hand.
