### ISSUE TITLE
Item disappearing 1.8

### ISSUE THREAD

**Issue by dyelsfx** [TeamPneumatic/pnc-repressurized#1031]
### Describe the bug

Empty pcb's disapearing.

### How to reproduce the bug

After using the uv ligth box to process the empty pcb and the process is finished it disappears when exiting the world or unloading the chunk.

### Expected behavior

Not disappear when left the pcb's on the uv light box.

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
Fixed in 3.3.0
