### ISSUE TITLE
Sort mobs from one mod

### ISSUE THREAD

**Issue by DrSigma4164** [TeamPneumatic/pnc-repressurized#1032]
### Describe the feature

Add the ability, for example, insentry turret, the ability to sort mobs from only one modification. For example, I want the turret to shoot at all mobs from the LycaniteMobs modification.

### Reasons why it should be considered

This makes it easier to sort when you need that all the mobs from this mod were the purpose of the turret, so as not to write the names of all the mobs, because there may be many.

**Comment by desht** [comment]
This will be in 1.19.  Will probably also backport to 1.18.2 (didn't make today's 3.3.1 release, sorry).

**Comment by desht** [comment]
Added in 3.4.0 release (for 1.18)
