### ISSUE TITLE
ATM7 PNC Spawner Agitator not working when far away. 

### ISSUE THREAD

**Issue by Snipzower** [TeamPneumatic/pnc-repressurized#1033]
### Describe the bug

As stated in the title, the Spawner Agitator does not work when you are far away from the spawner, despite it saying that it would allow the entities to continue spawning without an active user nearby. 

### How to reproduce the bug

Simply put agitator on spawner and it does not work.

### Expected behavior

When the agitator is placed upon a spawner it should act how it is stated in the description.

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
Version of the mod please?

**Comment by Snipzower** [comment]
18.2 is the version of the mod

**Comment by desht** [comment]
No, 1.18.2 is the version of Minecraft.  I need the mod version, please.

**Comment by Snipzower** [comment]
1.18.2-3.3.0-99

**Comment by desht** [comment]
They're spawning fine for me.  I presume you have the spawner chunk-loaded? (The agitator won't keep chunks loaded for you - you need a separate solution for that)

**Comment by Snipzower** [comment]
i mean ive had the chunks loaded for it but they just dont spawn, ill try
to figure it out.

**Comment by desht** [comment]
Other conditions still apply too - e.g. light level. Only the thing the Agitator does is override the player proximity requirement.

**Comment by desht** [comment]
There is an issue where the Agitator currently doesn't work if there are no players in the dimension at all (e.g. spawner in the Overworld, and you're in the Nether).  Could this be what's happening here?

**Comment by azukaar** [comment]
Same issue here in ATM 7 as well
- stand next to working spawner
- get to 30 ish blocks to the spawner with the agitator on it
- mobs dont spawn anymore

This is because Apothesis is in the Modpack, and override vanilla spawners. See #1063

**Comment by desht** [comment]
Right, as mentioned in that issue, Apotheosis overrides the spawner in a way that the Agitator can't deal with. If you have Apotheosis in the pack, just use its features for spawner management.

I should probably put some info in the Agitator item tooltip warning players about that if Apotheosis is installed.

**Comment by azukaar** [comment]
@desht yes, keep in mind though that the feature of the agitator allowing persistent mobs even when no players are < 128 bl. is still working fine with the agitator once you use Apothesis' star mechanism to override spawning condition
