### ISSUE TITLE
Crash: Minecraft crashes when I step on a block PNC:R

### ISSUE THREAD

**Issue by YtugDEQH** [TeamPneumatic/pnc-repressurized#1036]
### Describe the bug

I step on the block (does not apply to liquids) from PNC:R. The inscription appears: Save the world (I play on the server), And the minecraft is closed. If the block is not removed, then Minecraft will always close. How to solve the problem.

### How to reproduce the bug

Step on a pipe and stuff. I can make and send a video.

### Expected behavior

Walking on blocks. The same behavior as for the rest of the vanilla and non-vanilla blocks.

### Additional details

Friends on the server don't seem to have such a problem. 
I'm sorry if something is wrong in English. I don't know English well, so I use a translator.

### Which Minecraft version are you using?

1.16

### Which version of PneumaticCraft: Repressurized are you using?

2.15.10-329

### Crash log

https://drive.google.com/file/d/1GGIp_cIbF8JjlU5TkXGjVSBPiyhpm3hK/view?usp=sharing

**Comment by desht** [comment]
I don't have access to that stacktrace.  Please just use gist or pastebin or similar.

**Comment by YtugDEQH** [comment]
> I don't have access to that stacktrace. Please just use gist or pastebin or similar.
https://gist.github.com/YtugDEQH/8ec84db2401abe2a63fecb5201a30027

**Comment by desht** [comment]
Ugh, baritone :(

What you have here is a closed-source and obfuscated mod that's causing crashes in other mods.  I'd ask them why they're passing a null world object to `Block#getCollisionShape()`.
