### ISSUE TITLE
Pneumatic wrench can mess up tube connections

### ISSUE THREAD

**Issue by tDegan** [TeamPneumatic/pnc-repressurized#1037]
### Describe the bug

When using the pneumatic wrench on connected pressure tubes to first disconnect them and then reconnect them the tube network can get messed up making tubes visually connect but still leak air or not transferring from one tube to another (though not leaking air)

### How to reproduce the bug

There are a bunch of combinations you can do, here is an easy one to reproduce:

![2022-06-24_23 02 22](https://user-images.githubusercontent.com/103054313/175667743-acdb0d97-9039-4b9d-be32-af9cdf76c462.png)

1. Click on 2
2. Click on 2 again
3. Click on 3
4. Now the tubes look connected and do transfer air, but they also leak air.

### Expected behavior

Tubes that look connected do not leak air.

### Additional details

There seem to be variations which include closing and opening unconnected sides as steps, but I haven't been able to reliably reproduce those. Maybe they are just more complicated versions of the above steps tho?

no other mods are installed (apart from Patchouli)

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

1.18.2-3.3.0-99

**Comment by desht** [comment]
Would you be able to test the build from https://github.com/TeamPneumatic/pnc-repressurized/actions/runs/2560293398 and see if resolves the problems you're seeing?

**Comment by tDegan** [comment]
With the test build I can't reproduce the problem anymore.

**Comment by desht** [comment]
Fixed in 3.3.1 release
