### ISSUE TITLE
hacks are not affecting Ghasts or Blazes

### ISSUE THREAD

**Issue by superbrias** [TeamPneumatic/pnc-repressurized#1039]
### Describe the bug

While seemingly every other part of entity tracking seems to work fine, both ghasts and blazes seem to not actually be hackable. While the prompt comes up and "progresses" once it finishes nothing seems to happen and quite soon the prompt comes back as I still get face fulls of fire.
Of the other entities I have tested for some diligence all literal disarms (any entity holding a weapon) seems to work, creepers blow, soon-to-be pets are tamed, and even endermen get stuck. not all of them but I noticed no other problems with hacking

### How to reproduce the bug

Try to hack a blaze or ghast (with a pneumatic helmet with a security and entity tracking upgrade)
see if they continue to spew fire at you

### Expected behavior

They stop spewing fire/ firing fireballs

### Additional details

If I had to guess from the affected mobs, especially the fact creeprs and endermen are untouched, I would say the Datapack/mod Incendium (https://www.curseforge.com/minecraft/mc-mods/incendium) is what is fighting causing the issue to come up

Incendium does not add anything strictly non-vanilla per-say and thus reuses slightly modified ghasts and blazes in some of their modified biomes and structures, I bet whatever it is doing to ghasts and blazes is confusing or outwrite overwriting your hack hooks or whatever

but I could be wrong, no programmer myself and have not even peeked at any code for this case

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

1.18.2-3.3.0-99

**Comment by desht** [comment]
Your theory could well be correct.. hacking requires some, well, hacky code to reflect into the blaze and ghast code and delete their AI tasks which launch fireballs.  If some other mod is also modifying them in some way, conflicts could occur.

I'll do some testing and see if there's a more robust way of handling this.

**Comment by desht** [comment]
1.19 will have a very major internal rework of the whole hacking system, part of which will mean much less reflection needed for this situation.  The changes are big enough that I won't be backporting it all to 1.18, unfortunately.

**Comment by desht** [comment]
Fixed in 4.1.2 release
