### ISSUE TITLE
Crashing when book can't find recipe

### ISSUE THREAD

**Issue by Swedz** [TeamPneumatic/pnc-repressurized#1040]
### Describe the bug

I have modified a few recipes from PNC and the Patchouli book isn't taking it lightly.

### How to reproduce the bug

Remove a recipe for an item, say the Upgrade Matrix. Then add your own recipe with a different recipe id than the original recipe's. The book will fail to load, and no content will be present in it. Additionally, trying to open a page using the Programmer ("Press 'I' for info") it will crash the game completely.

### Expected behavior

The book would still load, and display the new recipe or not show the recipe at all, similarly to how Botania's book does it (see image below for what I mean).

### Additional details

I also have `disableAdvancementLocking` disabled in the Patchouli client config, I'm not sure if this is affecting it at all.

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

3.3.0-99

### Crash log

https://gist.github.com/Swedz/8a252f772842c317ecb8ca8dd1bcb582

**Comment by desht** [comment]
Fixed in 3.4.0 release
