### ISSUE TITLE
Active state property for liquid compressors

### ISSUE THREAD

**Issue by lOmicronl** [TeamPneumatic/pnc-repressurized#1041]
### Describe the feature

When pointing at a solid-fuel air compressor (basic or advanced) and pressing F3, one can see on the right side, below the block ID and its facing, that it reports its active state as a boolean value. It either says "on: false" or "on: true".

The two liquid-fuelled air compressors do not report such a property. Please consider adding it.

### Reasons why it should be considered

This property makes it very easy to set up the air compressors for Advanced Chimneys and Pollution of The Realms. By contrast, the lack of the property makes it incredibly difficult, as the active state must then be pulled from an NBT tag. And the player cannot see which tags the compressors use. There is currently no ingame NBT explorer tool available for Minecraft 1.18 or 1.19 that I am aware of.

I hope that adding this property will be a very quick and easy process, so that this request is not much of a burden despite not benefitting the mod itself in a vacuum.

### Additional details

Reference: [adding custom emitters for the two mentioned mods](https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms/pages/adding-a-custom-emitter)

**Comment by desht** [comment]
Yeah, I can do that.

**Comment by lOmicronl** [comment]
Awesome, many thanks :)

**Comment by lOmicronl** [comment]
Confirmed working in latest version, closing.
