### ISSUE TITLE
Drone not returning home

### ISSUE THREAD

**Issue by misfittweek** [TeamPneumatic/pnc-repressurized#1042]
Hello!

I have seen this issue a couple times with no real explanation so I was hoping you could help. Similar to #140 my drone will teleport to the right location, collect the oil, but not teleport back unless im standing at that oil field. I have claimed the chunk with FTB so I believe it should be loaded. 

ttps://pastebin.com/3Lh5JmAP - Is the code. Very simple one.

First time trying to open an issue I apologize if I did the pastebin wrong.

Thanks!

**Comment by misfittweek** [comment]
for more info sometimes it will return back to the oil field im standing at without me having to go find it at the base  but as soon as I leave it gets stuck

**Comment by misfittweek** [comment]
I got it to work by force loading the chunk the oil was in so it seems to be a chunk issue i'll have to figure out. Sorry for the waste of a post lol

**Comment by desht** [comment]
Yup just claiming the chunk with FTB Chunks won't keep it loaded, some kind of forced chunk loading is required here.
