### ISSUE TITLE
Make seismic sensor display the thickness of the liquid, not just its starting depth

### ISSUE THREAD

**Issue by EnderiumSmith** [TeamPneumatic/pnc-repressurized#1045]
### Describe the feature

When using the seismic sensor, in addition to saying the depth of the first fluid block found, it should also say the depth of the last one in the column.

### Reasons why it should be considered

The gas lift will not pump fluid from bellow its level so if you miss the deepest spot there will be fluid left behind blocked by stone from reaching the pump and you will have to move the lift and drill another hole. having the ability to target where the pump goes would allow you to get most of the fluid in one go.

**Comment by desht** [comment]
Yeah, don't see why not.

**Comment by desht** [comment]
Added in 3.4.0 release
