### ISSUE TITLE
Thermal Stability upgrade for Advanced Compressors

### ISSUE THREAD

**Issue by lOmicronl** [TeamPneumatic/pnc-repressurized#1048]
### Describe the feature

Please cosider adding an upgrade that, when installed into an advanced compressor (solid or liquid), increases the temperature limit after which loss of efficiency occurs.

Example: an upgrade, stacking to a maximum of five, that moves the threshold up by 5°. With five upgrades, the compressor would run up to 75° without losing efficiency, rather than the default 50°.

All numbers are examples and can be tuned for balance.

The upgrade could be made reasonably pricey or progress-gated, as it is meant for lategame useage. Although, perhaps some other uses could be found in other machines?

### Reasons why it should be considered

When settling in hot areas, it can be very difficult to run the advanced compressors. While it's fair to have an engineering challenge, the player should have appropriate tools at their disposal to deal with the challenge. And particularly where gasoline and its 1.5x burn speed multiplier is concerned, just slapping on more and more heat sinks feels limiting - and sometimes doesn't even solve the problem!

At an outside temperature of 26° - found for instance in a vanilla swamp biome at sea level - a two-long heatpipe with seven heat sinks attached will keep an advanced liquid compressor running on gasoline at 52°, just baaarely short of receiving efficiency penalties (shouldn't they start at 51 though, instead of at 53?).

Connecting the heat sinks directly to the compressor is much more effective, of course; when doing so, only three heat sinks are needed for the same 52° steady-state temperature. However, that's three out of six faces gone on the compressor. You need at least one for a pressure tube, leaving only two free ones. Then one for a redstone signal for pressure control... one for a logistics frame for automated fuel delivery... perhaps you'd like it to sit on solid ground for aesthetics purposes... maybe the way the workshop is set up means you can't actually see/access the compressor unless you leave a back face free... how about putting an Advanced Chimneys chimney on top? There's tons of ways to run out of sides, at which point you're back to trying to use the poorer-performing heat pipes and mass heat sinks.

These examples are without speed upgrades, which drastically increase heat production. This leads to double-dipping in fuel efficiency reductions.

And all of this is still in a fairly temperate biome. The vanilla badlands biome, for example, has a temperature of 56° at sea level! That's above the redline even while the compressor is off! In that biome, you cannot run any advanced compressor, solid or liquid, without severe efficiency penalties, regardless of fuel choice.

Hence, a request for additional tools to allow the player to manage the heat output of these compressors. By raising the internal temperature threshold, heat pipes and heat sinks become more effective, as the temperature gradients steepen. It also allows lessening penalties in very hot biomes. Finally, it makes using speed upgrades in advanced compressors more attractive and valid.

**Comment by TeamSpen210** [comment]
I'm fairly sure this is intentional behaviour. Fully passive cooling is only effective up to a point. In the more extreme cases, you'll need to use active methods - blowing air over heatsinks with Air Grate modules, or using a Vortex Tube.

**Comment by desht** [comment]
Correct, there are ways of keeping an advanced compressor cool even with 10 speed upgrades, and of course there's also the option of more compressors with fewer upgrades.  I won't be adding upgrades to trivialise heat dissipation.

See https://wiki.enigmatica.net/enigmatica6/gameplay/how-to.../pneumaticcraft-heating-and-cooling for some good info on efficient cooling of compressors.

Also:

> The vanilla badlands biome, for example, has a temperature of 56° at sea level! That's above the redline even while the compressor is off! In that biome, you cannot run any advanced compressor, solid or liquid, without severe efficiency penalties, regardless of fuel choice.

"severe" is a major overstatement here.  At 56°, compressors run at 98% efficiency, which is very minor.
