### ISSUE TITLE
You can remove the blocks of a pressure chamber without breaking the structure using extruder mk1 modular routers

### ISSUE THREAD

**Issue by Vashal0** [TeamPneumatic/pnc-repressurized#1049]
### Describe the bug

If you build a pressure chamber with an extruder mk1, and then take away the block with it the structure stays formed. It stays formed even though relog or from building blocks where the block used to be. If you use multiple routers and extruders sync'd, you can even remove the entire structure other than the valve and just have an invisible pressure chamber that still works. 

Here is the bug in action from a short clip I made showing it at its logical extreme, killing a wither with it

https://user-images.githubusercontent.com/107340954/178166353-69bdef6f-dc0e-4f2c-8b89-bdb0805ba3f2.mp4

.

### How to reproduce the bug

1. Complete pressure chamber with extruder mk1 modular router
2. Unpower the router, block goes away
3. remove the router, pressure chamber stays formed despite the block being gone

### Expected behavior

The structure is no longer considered formed after the router removes the block

### Additional details

1.16.5-7.5.2-83 is the version of modular routers I use, and this was all done on enigmatica 6: expert

### Which Minecraft version are you using?

1.16

### Which version of PneumaticCraft: Repressurized are you using?

1.16.5-2.15.8-324

**Comment by desht** [comment]
I believe I see the problem here - it actually originates from when the block is *placed* by the router, not *broken*, and probably happens with other automated block placers too.  I think I have a fix, but I need to do a lot of testing to ensure it hasn't introduced any other problems...

**Comment by desht** [comment]
Since you have a test world running, can you try out build 331 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ when you get a chance and see if it fixes your problem?

Would also be good to verify that existing pressure chambers in the world get loaded properly with the new version (they should be fine from my testing, but worth checking anyway)

**Comment by Vashal0** [comment]
Okay, I loaded it up and my normal pressure chambers were still there and working, however upon breaking and replacing any block of the structure they would bug out and I'd have to replace the valve. After replacing the valve they were normal working pressure chambers again. My bugged pressure chambers were also still there and working, but any new attempts at making a bugged pressure chamber didn't work. Seems fixed to me.

**Comment by Vashal0** [comment]
I spoke too soon, I thought that replacing the valve fixed those pressure chambers for good, and that it was simply an update thing. But upon reload, it turns out I had to fix them again. They become a weird mess of textures, sometimes still working and sometimes registering as a 0x0x0 size pressure chamber.

**Comment by Vashal0** [comment]
Just to make your job a bit easier, I made 3 4x4 pressure chambers, 1 built entirely by me, 2 finished being built by a router. upon reload if I broke a block and replaced it, or if a router broke and replaced it, all 3 became 0x0x0 pressure chambers with messed up textures until I broke and replaced the valve, And the valve had to be the last block I placed or they stayed broken.

**Comment by desht** [comment]
OK, hopefully nailed it this time.  Can you try build 333 when you get a chance?

**Comment by Vashal0** [comment]
Done, this time they all were working upon loading in, and breaking them caused them to break as expected. Didn't have any issues and the original fix was still working.

**Comment by desht** [comment]
Fixed in 3.4.0 release
