### ISSUE TITLE
Description of drone volume upgrade does not match effect

### ISSUE THREAD

**Issue by lOmicronl** [TeamPneumatic/pnc-repressurized#1050]
### Describe the bug

When placing a drone into a charging station, you can read the effect that various upgrades have on it via the pop-out tabs on the sides of the UI. Among them, the tab for the volume upgrade claims that each such upgrade increases the drone's base air capacity by 5,000 mL.

When you actually insert a volume upgrade, you get an extra 12,000 mL instead.

Extremely minor issue :) But just for completeness' sake...

### How to reproduce the bug

- Build or spawn in an empty generic drone
- Place the drone into a charging station
- Read the popout tab for the volume upgrade
- Read the popout tab for the current air capacity
- Place a volume upgrade into the drone
- Observe the changes in the popout tab for the current air capacity

### Expected behavior

Either the drone should gain the advertised 5,000 mL, or the popout tab should advertise what the drone actually gains.

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

1.18.2-3.3.1-110.jar

**Comment by desht** [comment]
Fixed in 3.4.0 release
