### ISSUE TITLE
Im suspecting Micromissles as a possible "Server-Bricker" 

### ISSUE THREAD

**Issue by Snorlax1337** [TeamPneumatic/pnc-repressurized#1056]
### Describe the bug

So my "selfhosted" Server (16 cores, 16GB Ram assigned) kept crashing over and over again until i spammed /kill @e to remove a all entities.
I tried that because someone on the FTB Discord pointed out, that a crash report that i posted said something about micromissles.

I also suspect another mod that gave me a permanent multishot buff to be a factor in the whole process since it gave me +2 rockets that seemed cosmetic but also had the same tracking when using the @mob "filter".

Afterall i got my server into a working state again after trying many diffrent things to solve the problem and i would like to know if the micromissles were actually at fault here
[crash-2022-07-27_00.28.31-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/9201484/crash-2022-07-27_00.28.31-server.txt)
![Book](https://user-images.githubusercontent.com/110115789/181333922-57d4cf2d-1f2a-40a1-88fc-b8c1b41abdaf.png)
.

### How to reproduce the bug

Use Micromissles while having the multishot buff on your character. Wait a bit. Server Crashes. Crash Report says something about a micromissle doing something somewhere that crashes the server. (Someone on the FTB Discord told me so)

### Expected behavior

Maybe add a rocket lifetime by default? I heard its possible somehere in a config file, but maybe make them disappear after 1 minute of not hitting anything or so.

### Additional details

I love your mod, thank you for working on it ♥

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.18.2-3.3.1-110.jar

### Crash log

https://pastebin.com/cDmvR62M

**Comment by desht** [comment]
Looking at the trace, it's timing out in vanilla checks to see if the entity has hit anything.  This would not normally be a problem, so it could be a case of simply far too many missile entities in the world.  Does it always cause a crash if you launch missiles with that enchantment?  And if so, after firing how many missiles?

Missiles should explode (and remove themselves from the world) as soon as they touch any solid block, so I'm not sure why they would be hanging around forever.  I can add a change so they auto-explode after a certain period, maybe twice as long as the fuel duration.  So with default settings: 15 seconds of powered flight, 15 seconds of falling from the sky, then explode and disappear.

**Comment by desht** [comment]
I've added a max liftime for the missiles (600 ticks by default, twice the fueled duration).  Can be adjusted in config too if needed.

Not sure what else I can add to this...
