### ISSUE TITLE
Can't connect to http server at start [1.12.2]

### ISSUE THREAD

**Issue by Desoroxxx** [TeamPneumatic/pnc-repressurized#1058]
### Describe the bug

When you arrive at the main menu pnc logs [this].

[this]: https://www.toptal.com/developers/hastebin/opivejidof.rb

### How to reproduce the bug

- Have pnc installed on 1.12.2
- Launch the game 
- When the game as launched look in the console

### Expected behavior

Pnc can connect to the http server and the console stay clean.

### Additional details

https://www.toptal.com/developers/hastebin/opivejidof.rb

### Which Minecraft version are you using?

1.12 - UNSUPPORTED

### Which version of PneumaticCraft: Repressurized are you using?

1.12.2-0.11.15-398

**Comment by desht** [comment]
Not supported, and not an important problem anyway.
