### ISSUE TITLE
Memory stick crash

### ISSUE THREAD

**Issue by Tazmondo** [TeamPneumatic/pnc-repressurized#1059]
### Describe the bug

Mined a block with memory stick, game crashed.

Might be caused by vein miner since I was vein mining.

### How to reproduce the bug

1) Have some xp in memory stick
2) Have xp collection off
3) Vein mine some blocks (I mined cracked stone bricks) using the memory stick

### Expected behavior

For the game to not crash.

### Additional details

Enigmatica 6 Expert modpack

### Which Minecraft version are you using?

1.16

### Which version of PneumaticCraft: Repressurized are you using?

1.16.5-2.15.8-324

### Crash log

https://gist.github.com/Tazmondo/1b4b32ac46f3f5f4a01ea95ff1d2bf66

**Comment by desht** [comment]
Couple of things I don't get about this report:
1. If XP collection was off, the method in question (where the crash occurs) could not possibly be called. That method is specifcally only called when XP collection is enabled.  Are you sure XP collection was actually off?
2. The method is called from an inventory tick handler, not when blocks are broken.
3. Most importantly: you're using Java 15, which isn't supported with MC 1.16.  Please test if this occurs with Java 8.

**Comment by Tazmondo** [comment]
I'm unable to replicate the bug since moving to java 8, sorry for wasting your time.
