### ISSUE TITLE
Sentry Gun dont do damage on Magma(ForgeXSpigot)

### ISSUE THREAD

**Issue by SrRapero720** [TeamPneumatic/pnc-repressurized#1061]
### Describe the bug

_I know Mods cannot coexists with Plugins. but i need it both._
**BUG IS SIMPLE:** Turrets dont do damage on a [Magma](https://magmafoundation.org/) server. i tested same version ([1.12.2-0.11.15-398](https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized/files/2978408)) on pure Forge and its works normally.

Essencially i report that to know how sentry internal works to search any setting on the server to allow functionality (or giving up)
![image](https://user-images.githubusercontent.com/29090346/181917134-5a3d1397-d28e-4375-9556-e7fef8365367.png)

And normal minigun works
![2022-07-30_08h49_58](https://user-images.githubusercontent.com/29090346/181917394-160ad822-86cf-44c9-b9b7-a9b62d2f7863.png)

### How to reproduce the bug

1. Place a sentry
2. Give bullets
3. Spawn any mob
4. Wait for sentry start spinning
5. Bug!

### Expected behavior

Do damage

### Additional details

Installed plugins
![image](https://user-images.githubusercontent.com/29090346/181917248-ac8b7d36-f0e2-42a8-b2ea-18016158e2c0.png)

### Which Minecraft version are you using?

1.12 - UNSUPPORTED

### Which version of PneumaticCraft: Repressurized are you using?

0.11.15-398

**Comment by desht** [comment]
1.12.2 is unsupported, and spigot/whatever is totally unsupported.
