### ISSUE TITLE
Infinite Crash with Pressure Tubes

### ISSUE THREAD

**Issue by Dankergy** [TeamPneumatic/pnc-repressurized#1062]
### Describe the bug

Every time I step on a pressure tube my game infinitely crashes until I have the server owner teleport me from console.

### How to reproduce the bug

Just stepping on a pressure tube or potentially the air compressor while it's pressurized

### Expected behavior

Infinite crash on logon until you are teleported away

### Which Minecraft version are you using?

1.16

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.16.5-2.15.10-329

### Crash log

https://pastebin.com/1R6CMq1P

**Comment by desht** [comment]
Baritone.  Just no.
