### ISSUE TITLE
[1.18.2] Spawner Agitator doesn't work with Apotheosis Spawners

### ISSUE THREAD

**Issue by CantBeLucifer** [TeamPneumatic/pnc-repressurized#1063]
### Describe the bug

Issue seems similar to #966 but in 1.18
Also see #1033

The spawner agitator does not work on Apotheosis spawners in 1.18.2. Furthermore, they cannot be removed by right clicking with another agitator, or with a wrench,

Video demonstration with zombie and blaze spawner.
https://streamable.com/lztdbk

### How to reproduce the bug

With both mods installed, place a spawner agitator on a mob spawner, it doesn't change anything.

### Expected behavior

The agitator should allow mobs to spawn without the player needing to be within the radius.

### Additional details

Mods:
Apotheosis-1.18.2-5.3.6
Bookshelf-Forge-1.18.2-13.2.21
EnchantmentDescriptions-Forge-1.18.2-10.0.4
jei-1.18.2-9.7.1.232
Patchouli-1.18.2-71.1
Placebo-1.18.2-6.4.2
pneumaticcraft-repressurized-1.18.2-3.3.1-110
theoneprobe-1.18-5.1.0

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

3.3.1-110

**Comment by desht** [comment]
There's really no good reason to use an agitator on an Apotheosis spawner so I don't consider this a serious problem at all. Apotheosis does way more with spawners than PNC does (or ever will).

In fact, how are you even placing an agitator on such a spawner?  PNC explicitly only permits agitators to be added to vanilla Spawners.

Having said that, it should be possible to remove agitators, so I'll check into that.

**Comment by desht** [comment]
Sneak-right-clicking with a Logistics Configurator removes the agitator, as expected.  Since you have Apotheosis installed, you could also break the spawner with Silk Touch to remove the agitator.

Closing this issue, there isn't much I can do here.  If you have Apotheosis, use its spawner management features; they're way more sophisticated than the agitator.
