### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Ch1216** [TeamPneumatic/pnc-repressurized#1064]
### Describe the bug

key.keyboard.u and entity.pneumaticcraft.tumbling_block translation is missing

### How to reproduce the bug

key.keyboard.u shows up when using pneumatic helmet has item search upgrade and entity.pneumaticcraft.tumbling_block shows up when summoning a tumbling block with /summon pneumaticcraft:tumbling_block

### Expected behavior

Instead of key.keyboard.u "u" shows up and instead of entity.pneumaticcraft.tumbling_block "Tumbling Block" shows up

### Which Minecraft version are you using?

1.18.2

### Which version of PneumaticCraft: Repressurized are you using?

3.4.0-134

**Comment by desht** [comment]
`/summon pneumaticcraft:tumbling_block` isn't a useful thing to do so I'm not really sure what you're expecting here. What are you trying to achieve by summoning a tumbling block (these are basically like falling blocks from vanilla) ?

"key.keyboard.u shows up when using pneumatic helmet has item search upgrade" - please explain this more clearly. I have an Item Search upgrade in my helmet and I'm not seeing that.

**Comment by Ch1216** [comment]
the tumbling block translation can also be seen using jade and probably the one probe

![helmietbug](https://user-images.githubusercontent.com/68875386/182649674-34883b9d-80b9-4c75-b8d1-a5345866d77d.png)
I guess i wordered badly its more like "key.keyboard.u shows up when using pneumatic helmet with air  and has item search upgrade enabled" 

also updated version numbers in the issue

**Comment by desht** [comment]
OK, thanks, will be fixed in next 1.18 & 1.19 releases.

**Comment by desht** [comment]
Fixed in current 1.18 & 1.19 releases
