### ISSUE TITLE
Distinguishable potion tipped ammo

### ISSUE THREAD

**Issue by edotenseilove** [TeamPneumatic/pnc-repressurized#1065]
### Describe the feature

I would like to be able to dye minigun ammo cartridge. Or show a text briefly with potion effect when switching ammo.

### Reasons why it should be considered

When using more then one potion tipped ammo in minigun it is hard to tell which potion effect is going to be applied because the item texture is the same. By beeing able to dye the cartridge or by showing potion effect text it would be much easier to distinguish between effects that are going to be applied.

P.S.:I really like this mod and I am grateful for the additional content and improvements

**Comment by desht** [comment]
Added in 3.4.0 release

**Comment by edotenseilove** [comment]
Thank you it is amazing.
