### ISSUE TITLE
No block place sound when placing stuff on valves

### ISSUE THREAD

**Issue by ChiefArug** [TeamPneumatic/pnc-repressurized#1067]
### Describe the bug

Similar to https://github.com/TeamPneumatic/pnc-repressurized/issues/963

https://user-images.githubusercontent.com/73862885/182569426-beeb1630-916e-49d6-a2ed-9a2926c67304.mp4

### How to reproduce the bug

Place a pressure chamber valve down
Try place any other block on top of it

### Expected behavior

Block place sounds

### Which Minecraft version are you using?

1.16

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.18.2-3.3.1-110

**Comment by ChiefArug** [comment]
Hmm, this is happening with formed pressure chambers too

**Comment by ChiefArug** [comment]
Oh, only ones that are technically formed but actually not formed (was experimenting with using create contraptions to move chambers and forgot to glue them together😆)

**Comment by desht** [comment]
Good timing, you caught me right before a new 1.18 release :D

Easy fix anyway.

**Comment by desht** [comment]
Fixed in 3.4.0 release
