### ISSUE TITLE
[bug] quark block "BrimStone" Removed 1.18.2

### ISSUE THREAD

**Issue by CKY-** [TeamPneumatic/pnc-repressurized#1068]
https://github.com/TeamPneumatic/pnc-repressurized/blob/fbafbce5d207f73caa2b7db72ceb27787ee40dc2/src/main/resources/data/pneumaticcraft/recipes/block_heat_properties/quark/brimstone.json#L3

causes error ``Failed to parse recipe pneumaticcraft:block_heat_properties/quark/brimstone[pneumaticcraft:heat_properties]: com.google.gson.JsonSyntaxException: unknown block id: quark:brimstone``

**Comment by desht** [comment]
Looks like Brimstone is no longer a thing in Quark.  The error is harmless but will be fixed in next release.

**Comment by CKY-** [comment]
thank you

**Comment by desht** [comment]
Fixed in current 1.18/1.19 releases
