### ISSUE TITLE
Add a "No hover" mode to the jet boots

### ISSUE THREAD

**Issue by ChiefArug** [TeamPneumatic/pnc-repressurized#1070]
### Describe the feature

Another check box in the Jet Boots config UI for completely disabling the jet boots hovering.
Could also merge that and the smart hover mode checkbox for a slider to change hover mode. "Off", "Smart", "Always".

### Reasons why it should be considered

It would allow using the stomp upgrade more effectively, and having the boots always hover can be an annoyance when doing some things (such as low controlled flying to the ground. then stopping and ending up hovering a block above the ground), or flying around in creative.

**Comment by desht** [comment]
Making it a slider/dropdown might be a bit more complex than it looks due to the way checkboxes have specific support for being toggleable with keybinds.  But it would be better from a UI point of view so I'll see how feasible it is to do that...

**Comment by desht** [comment]
Added in 4.1.1 for 1.19.2
