### ISSUE TITLE
Vaccuum trap works on mobs spawned by vanilla spawners if a spawner agitator is applied

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#1074]
### Describe the bug

Assuming this is not intended per the PNC Book entry on the vacuum trap

https://github.com/EnigmaticaModpacks/Enigmatica6/issues/5179

### How to reproduce the bug

1. Place or locate vanilla spawner
2. Apply Spawner Agitator
3. Suck up mobs

### Expected behavior

Expect mobs to not be sucked up

### Additional details

Can reproduce with only PNC and JEI installed. 

### Which Minecraft version are you using?

1.16

### Which version of PneumaticCraft: Repressurized are you using?

 pneumaticcraft-repressurized-1.16.5-2.15.11-334.jar

**Comment by desht** [comment]
Fixed in 2.15.12 release
