### ISSUE TITLE
Player flight not interrupted when disabling jet boots while stile pressing the thrust key

### ISSUE THREAD

**Issue by Delta-official** [TeamPneumatic/pnc-repressurized#1075]
### Describe the bug

When you start flying with the jet boots and disable them mid-flight while still holding down the thrust key the flight isn't actually interrupted and the player is gonna continue flying. In order for the player to stop flying they have to enable the jet boots again, and disable them without pressing the thrust key

### How to reproduce the bug

1. Activate the jet boots and begin flying
2. Deactivate the jet boots mid-flight while still holding down the thrust key

### Expected behavior

Jet boots deactivate when disabling them while still holding down the thrust key

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

1.18.2-3.4.0-124

**Comment by Delta-official** [comment]
is this going to be backported?

**Comment by desht** [comment]
Yes it's already in the 3.4.1 release for 1.18.2.

**Comment by desht** [comment]
Fixed in 4.1.2 release
