### ISSUE TITLE
Strange crash occurring preventing gameplay outright

### ISSUE THREAD

**Issue by billyma6** [TeamPneumatic/pnc-repressurized#1076]
### Describe the bug

This is on the Technodefirmacraft latest modpack version. After installing upgrades into my pneumatic armour and equipping it, every so often I'll encounter something when I'm looking around that will make my game crash without being able to recover. I'm not entirely sure what's going on, but my inexperienced glances tell me it seems like it's something to do with rendering a gui and it interacting with another mod? 

### How to reproduce the bug

Install Technodefirmacraft's latest version.
Get pneumatic armor.
Install helmet's vision upgrades (entity and block detector probably?)
Look around at the environment.

### Expected behavior

After some time after the steps, there should be a crash that forces crash on reload.

### Additional details

Here are the crash logs. I did my own experimentation when reloading backups and I still have the problem
[crash-2022-08-26_05.45.43-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/9433733/crash-2022-08-26_05.45.43-client.txt)
[crash-2022-08-26_05.55.35-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/9433734/crash-2022-08-26_05.55.35-client.txt)
[crash-2022-08-26_06.50.26-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/9433735/crash-2022-08-26_06.50.26-client.txt)
[crash-2022-08-26_06.51.39-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/9433737/crash-2022-08-26_06.51.39-client.txt)
[crash-2022-08-26_06.53.03-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/9433738/crash-2022-08-26_06.53.03-client.txt)
[crash-2022-08-26_05.30.27-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/9433739/crash-2022-08-26_05.30.27-client.txt)
[crash-2022-08-26_05.32.04-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/9433740/crash-2022-08-26_05.32.04-client.txt)
.

### Which Minecraft version are you using?

1.12 - UNSUPPORTED

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.12.2-0.11.15-398.jar

**Comment by desht** [comment]
1.12 is unsupported, sorry.
