### ISSUE TITLE
Logistic Module doesn't retain it's channel if changed with right-click

### ISSUE THREAD

**Issue by Rosewarden** [TeamPneumatic/pnc-repressurized#1078]
### Describe the bug

I am currently playing Plexiglass Mountain from FTB and I've run into an issue with setting the channel of a logistic module for my garden-cloche farm. When I setup the channel by right-clicking the logistic module then selecting the color, it changes it to the selected color but after a few seconds it reverts back to white. When I right-click the logistic module with a yellow dye (in my case), it keeps it changed.
![image](https://user-images.githubusercontent.com/112348780/187092855-e114af6b-ad20-4d0e-8ddc-26bff141c75f.png)

### How to reproduce the bug

Right-click a logistic module and change it's channel. After a few seconds it "should" revert back to white.

### Expected behavior

The module should remain on it's intended channel.

### Additional details

This is WORKING the setup I currently have because I changed the channel by right-clicking with a yellow dye.
![image](https://user-images.githubusercontent.com/112348780/187092959-0ee119d9-f9a6-492f-aa5a-077806550f6c.png)
![image](https://user-images.githubusercontent.com/112348780/187092968-65a93b15-d7f3-4a5b-ad73-e987ab6642bb.png)
![image](https://user-images.githubusercontent.com/112348780/187092988-0c0e1ad8-0d46-45d7-b1a2-2a3e18f0747c.png)

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

1.18.2-3.3.0-99

**Comment by desht** [comment]
From the 3.4.0 changelog:

* Fixed Redstone Modules not syncing settings properly on Reinforced or Advanced Pressure Tubes (only worked on basic tubes)

**Comment by Rosewarden** [comment]
Thank you very much!
