### ISSUE TITLE
CraftTweaker support for explosion crafting

### ISSUE THREAD

**Issue by Kaperios** [TeamPneumatic/pnc-repressurized#108]
As said in title.
There would be 2 options to do this: 
- Option in config that allows to disable compressed iron crafting through explosion,
- Add CrT compat to the explosion crafting

**Comment by desht** [comment]
I can see this being potentially useful for modpack makers if they wanted to force players down a different crafting route to get started with PNC.

We could just add a boolean config option to disable it entirely, with a warning in the comment that if you do so, it's up to you to set up some other method of creating compressed iron (most likely with CraftTweaker).

**Comment by desht** [comment]
Having said that, it might also be handy to add a CraftTweaker recipe to allow other resources to be explosion-crafted into compressed iron, e.g. an expert mode pack might require you do explosion-craft steel into iron.  Wouldn't be too hard to add CrT support for that...

**Comment by desht** [comment]
Part 1 - disabling explosion crafting in config - has been added, will be in upcoming 0.4.1 release.

Part 2 will be done soon...

**Comment by Bullorg74** [comment]
Hi Currently using the disabled explotion crafting option and have added another way to do it. But I was wondering if when I disable it in the configs could you do something about this aswell or is that not possible/your thing to solve. Would be nice if it was gone as its not true in my pack.
![exploti](https://user-images.githubusercontent.com/38103415/39710999-b803def6-521e-11e8-9f3a-328913fb842b.JPG)

**Comment by desht** [comment]
Yeah that's on us to fix. Easy change though, just need to disable the JEI category registration.

**Comment by desht** [comment]
Explosion crafting now has CraftTweaker support.  Examples:
```
# clear default recipes
mods.pneumaticcraft.explosioncrafting.removeAllRecipes();

# iron -> compressed iron has a 95% loss rate
mods.pneumaticcraft.explosioncrafting.addRecipe(<ore:ingotIron>, <pneumaticcraft:ingot_iron_compressed>, 95);

# steel -> compressed iron has only 10% loss rate
mods.pneumaticcraft.explosioncrafting.addRecipe(<ore:ingotSteel>, <pneumaticcraft:ingot_iron_compressed>, 10);

# netherrack to nether brick at 50% loss rate
mods.pneumaticcraft.explosioncrafting.addRecipe(<ore:netherrack>, <minecraft:netherbrick>, 50);
```

**Comment by desht** [comment]
Added in 0.8.0
