### ISSUE TITLE
Adding valves to a already upgraded pressure chamber makes it behave weirdly

### ISSUE THREAD

**Issue by Vapaman** [TeamPneumatic/pnc-repressurized#1081]
### Describe the bug

When adding a valve to a pressure chamber that already has upgrades, the other valve overrides it and it behaves like it had no upgrades. The upgrades can be gotten back if the additional valve is removed.

### How to reproduce the bug

1) Build a pressure chamber with 1 valve
2) Add some upgrades to it
3) Add another valve to the pressure chamber
4) When right clicking the chamber, the upgrades now seem to be missing

### Expected behavior

The valves should sync up properly, and display the upgrades whether the valve was placed before or after putting upgrades.

### Additional details

Workaround:
Add the valves first and then the upgrades.

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

1.18.2-3.4.1-131

**Comment by desht** [comment]
Hmm, yeah.  The pressure chamber considers the valve at the largest X/Y/Z blockpos to be the "primary" valve, and that's the valve of interest as far as upgrades go.  I'll need to have a think about the best way of dealing with this - there's a choice of either just moving all upgrades from non-primary valves to the primary valve when the multiblock is formed, or allowing upgrades to stay in each valve and take them all into account.

**Comment by desht** [comment]
This is fixed in the current 1.19.2 release.  Will backport to the next 1.18 release.

**Comment by desht** [comment]
Fixed in latest release
