### ISSUE TITLE
Desync between gui xp fluid setting in aerial interface and actual setting

### ISSUE THREAD

**Issue by Random832** [TeamPneumatic/pnc-repressurized#1083]
### Describe the bug

While using PneumaticCraft on the Ragnamod VI modpack, I had issues with the XP fluid feature in the aerial interface not working correctly. After some investigation, it turned out that the actual setting was not the same as setting displayed in the GUI. The disabled option is unaffected, the likely cause is the reliance on the contents of the forge:experience fluid tag, which is a HashSet object that is sorted differently between the client and server.

The modpack contains a large number of mods that add XP fluids, including Thermal Expansion, Mob Grinding Utils, Cyclic, and Industrial Foregoing.

### How to reproduce the bug

Try to use xp fluids in aerial interface

### Expected behavior

expected the displayed setting to match the fluid that i can insert or extract

### Which Minecraft version are you using?

1.16

### Which version of PneumaticCraft: Repressurized are you using?

2.15.6-315

**Comment by desht** [comment]
Fixed in 1.16/1.18/1.19
