### ISSUE TITLE
Logistics Module keeps forgetting its set color channel

### ISSUE THREAD

**Issue by SudoSpider** [TeamPneumatic/pnc-repressurized#1086]
### Describe the bug

Every time the module transfers an item it resets its channel to default white.

### How to reproduce the bug

Easily replicated anytime the module activates to move an item

### Expected behavior

I'm trying to set multiple systems of item transport over the same tubes using different color channels. Due to having separate systems using the same ingredients, I need them to stay separate between the ingredient source and the requesting machine.

### Additional details

Apologies if this is a bad report, its my first bug report so it is probably lacking.

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.19.2-4.1.1-132

**Comment by desht** [comment]
Hmm, are you using Reinforced or Advanced Pressure Tubes?  There is indeed a bug there, which I've just fixed in dev.

**Comment by SudoSpider** [comment]
I was indeed using Advanced Pressure Tubes.

**Comment by desht** [comment]
Fixed in 4.1.2 release
