### ISSUE TITLE
1.18.2 Compatibility Issue with Immersive Engineering's added Villagers

### ISSUE THREAD

**Issue by Starr12** [TeamPneumatic/pnc-repressurized#1088]
### Describe the bug

When playing single player with IE and PneumaticCraft installed, creating a "Machinist" villager using an anvil will result in their first trade being "Minecraft:Air" For Emeralds.

The trade is intended to be IE:CoalCoke, and works as intended when using only IE, the issue only appears when the villager attempts to generate a trade, as the village i tested on displayed correctly when loaded with IE and Pneuma installed, but after removing and replacing his work block, the "air" trade re-appeared.

This issue appears seemingly at random through out multiple IE Professions and trades.

### How to reproduce the bug

Fresh install of MC 1.18.2 with forge 40.1.74.
Installed Immersive Engineering and PneumaticCraft

Attempt to create a "machinist" using an anvil.

Confrim it's PneumaticCraft by uninstalling PCC but leaving Patchouli in place, villager will regain their CoalCoke Trade when refreshed.

### Expected behavior

The Machinist Villager should offer CoalCoke for trade along side the hammer every time, there's no other "level 1" options for the villager.

### Additional details

I do not know if this persists in multiplayer.

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.18.2-3.4.3-8.jar

**Comment by desht** [comment]
Sorry, I can't reproduce this.  Machinists in my test world (with PNC installed, of course) have perfectly working trades:

![2022-10-03_08 30 42](https://user-images.githubusercontent.com/736831/193523216-40187cb1-a9f4-4ed2-b2f8-c7dc4b55de56.png)

There must be some other mod interfering here in your instance.  PNC doesn't touch IE villager trades at all, and uses only normal Forge events to add trades to its own villagers.

**Comment by Starr12** [comment]
Here's a video on how I recreated it.
https://youtu.be/hMt2-aFA_hk
You can skip ahead to about 2:50 if you want to skip the loading process after the first 35 seconds

The "Long Term Save" instance in the video is where I first encountered the problem, I've recreated it in a test instance with only IE and PNC.

The log from the first run is attached.
[2022-10-03-1.log.gz](https://github.com/TeamPneumatic/pnc-repressurized/files/9698729/2022-10-03-1.log.gz)

This problem has already been reported to IE's git as well, and includes some further information.

https://github.com/BluSunrize/ImmersiveEngineering/issues/5435

I've also worked up that between my log and Belathus' these are the only common mods:

Create Crafts and Additions
Create Flywheel
Create Deco
Botania
AppleSkin
Architectury
AutoRegLib
Bookshelf
Building Gadgets
Caelus
Chipped
Compact Machines 4
Controlling
Rftools(all)
Engineer's Decor
Sophisticated(all)
FTB Ultimine
MCJTYLib
Mekanism and Generators
Patchouli
Placebo
Pneumaticraft
Quark
Runelic
Selene
Supplementaries
Shrink
StructureGel
TheOneProbe

The only one of these I know that actively deals with villagers at all it PNC, so I tested that on a whim and found the issue demonstrated in the video.

**Comment by desht** [comment]
Honestly, I don't know what to say.  I don't touch IE trades or tags in any way, and I simply can't reproduce the problem.

**Comment by qqtpie** [comment]
Same. ATM7 1.18  multiplayer and single player. Air  hold w to ponder.

**Comment by desht** [comment]
"Air hold w to ponder"

And what, exactly, does pondering have to do with either PNC or IE?

Once again:  I cannot reproduce the problem. I do not mess with IE trades _in any way_.

**Comment by emanuele246gi** [comment]
I've got this issue too, I have a whole modpack and I filtered every mod possible, after I was with only IE and PCR I can confirm I have this issue, I also reported this into IE's Discord server and they said it was probably a tag error, more info:
Forge 40.2.1
ImmersiveEngineering-1.18.2-8.4.0-161.jar
pneumaticcraft-repressurized-1.18.2-3.6.0-19.jar

**Comment by desht** [comment]
`¯\_(ツ)_/¯`

**Comment by emanuele246gi** [comment]
Is there a way I can fix it by myself? If it's a tag issue then I could make a datapack, but can I?

**Comment by desht** [comment]
I have no idea.  As I said before:  _I do not mess with IE trades in any way._

**Comment by emanuele246gi** [comment]
Not trades, but maybe tags in general?

**Comment by desht** [comment]
No, I don't touch IE tags.  If I did, it would break in my dev world with IE installed, and it doesn't break.

**I am not doing anything to break IE trades.**

**Comment by emanuele246gi** [comment]
But that's really weird, I even tried with only both mods! By the way, I'll try to find a solution. Thank you for at least have dedicated your time on this ¯\_(ツ)_/¯
