### ISSUE TITLE
Pressure chamber not transforming iron ingots/blocks

### ISSUE THREAD

**Issue by Nevrai** [TeamPneumatic/pnc-repressurized#1089]
### Describe the bug

I have a 3×3 pressure chamber with over 4 bar. When I insert an iron ingot or block of iron into a chest that’s on top of a hopper which is going into the input interface, the iron ingot or block just pops out into the chest I have on the output interface, without actually being transformed into compressed iron, and I don’t hear the “plop” sound either.

However, when I put _two_ iron ingots into the chest, or I put one iron ingot and one block of iron, the last item gets turned into compressed iron. E.g., if I put one iron ingot and one block of iron into the chest, the block becomes a block of compressed iron, but the ingot isn’t transformed at all. And if I do more than two, like 20, none of the ingots or blocks become compressed iron and just plop out the other end without being transformed again.

This is a weird issue, and I’m not sure whether I’m doing something wrong, but it seems like a bug to me.

![2022-10-13_06 33 06](https://user-images.githubusercontent.com/59761487/195503433-cdda7a93-7f7f-4740-ae81-23d5de55655d.png)

### How to reproduce the bug

Create a 3×3 pressure chamber, ‘power’ it with air compressors, and put one or multiple iron ingot(s) or block(s) into the interface.

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.80 (latest for 1.18.2)
* **PneumaticCraft: Repressurized:** 3.4.3-8 (latest for 1.18.2)

**Comment by desht** [comment]
Sounds like you have your output interface in "Export All" mode.  Check the settings in the interface's GUI - under normal circumstances, it should only export Crafted items.

**Comment by Nevrai** [comment]
Oh, whoops! You were right. I had activated that by mistake. Thanks for letting me know!
