### ISSUE TITLE
[1.18.2] Shift-clicking an inappropriate network item into the Security Station causes a crash/freeze.

### ISSUE THREAD

**Issue by BadIsMyUsername** [TeamPneumatic/pnc-repressurized#1091]
### Describe the bug

When shift-clicking a network item intended for the programming station (Network API, Network Data Storage) into the security station, it will cause the game to freeze until you manually shut it down. 
The security station correctly does not accept these items if you just attempt to click and place them in.
The programmer also does not have this issue and will appropriately not accept the other three security network items shift-clicked or dragged.

### How to reproduce the bug

1. Place a security station down.
2. Grab an inappropriate network item (API, Data Storage).
3. Attempt to shift-click the item into the station's inventory.
4. Observe freeze.

### Expected behavior

The security station to not cause a freeze and instead just reject the item normally.

### Additional details

Tested on a fresh install with just Pneumaticcraft and Patchouli. 
Forge version 40.1.84
No crash log produced and nothing inside the regular log out of the ordinary. 

Similar to issue #1018

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

1.18.2-71.1

**Comment by desht** [comment]
Fixed in latest release
