### ISSUE TITLE
Error in log referencing IEnchantableItem from CoFH Core being missing

### ISSUE THREAD

**Issue by brisingraerowing** [TeamPneumatic/pnc-repressurized#1092]
### Describe the bug

The following entry appears in the game log:

```text
[15:09:15] [modloading-worker-0/ERROR] [pneumaticcraft/]: CoFH IEnchantableItem interface is not where we expected! Continuing, but PneumaticCraft items won't be able to use the Holding enchantment. Notify the PNC mod author, including the versions of PNC and CoFH Core you're using, if you see this error.
```

CoFH Core: 9.0.0.24
PNC:R : 3.4.3-8

### How to reproduce the bug

Launch with the above mentioned versions

### Expected behavior

No log entry about the error.

### Additional details

I noticed this while trying to debug an unrelated crash with the game being unable to compile shaders, and thought to mention it.

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

3.4.3-8

**Comment by desht** [comment]
Hmm, CoFH core has moved the package for their `IEnchantableItem` interface in their latest release (v9.x).  I will update PNC to support this in a newer release, but that also means older versions of CoFH core will cease to be supported.

In the short term, it means that the PNC can't use CoFH's Holding enchantment on its items, but it's a not a fatal problem.

**Comment by desht** [comment]
Latest release supports the new CoFH release - 9.x and up.  But not older versions of CoFH.
