### ISSUE TITLE
Drone Interface crafting recipe is broken

### ISSUE THREAD

**Issue by ThePotato97** [TeamPneumatic/pnc-repressurized#1093]
### Describe the bug

https://github.com/TeamPneumatic/pnc-repressurized/blame/1.19.2/src/generated/resources/data/pneumaticcraft/recipes/drone_interface.json
According to this the crafting recipe needs M but M isn't defined it used to be "computercraft:wireless_modem_normal".

### How to reproduce the bug

Try and craft the Drone Interface
![](https://cdn.discordapp.com/attachments/850855983084732416/1035923978772029440/unknown.png)
![](https://media.discordapp.net/attachments/850855983084732416/1035923497123332166/unknown.png)

### Expected behavior

For the crafting recipe to work.

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.1.1-132

**Comment by desht** [comment]
~~Do you actually have CC:Tweaked installed in your instance?~~

Ignore that, I can see the problem (CC:Tweaked is only a compile-time dependency in my dev workspace, so the data generation isn't finding the wireless modem). Will get it fixed for next release.

**Comment by desht** [comment]
Fixed in 4.1.2 release
