### ISSUE TITLE
Pneumatic sword

### ISSUE THREAD

**Issue by scarabx** [TeamPneumatic/pnc-repressurized#1094]
### Describe the feature

Sword that is charged with air and that doesn't lose durability when it is charged. When it isn't charged it will lose durability when used and have the same damage as an iron sword. When charged it will deal 20 health points of damage. It will have special abilities determined by the upgrades installed to it: Dispenser: releases a blast of air that knocks targets back. Speed: Increases sword's attack speed. Jet boots and entity tracker together: You can choose an entity, launch sword and then it flies towards target, hits it until it dies and then returns to your hotbar. I would also like it to have a cool flying animation. Security: When you drop your sword it will immediately return to your hotbar. Volume: same as all other items in mod.

### Reasons why it should be considered

Pneumaticcraft has everything, except a dedicated and modular melee weapon and all the features fit into the mod because it uses air and existing upgrades.

### Additional details

I think it should have a challenging crafting recipe and I don't have a design in mind. I only know that I think it should be black and fit into the texture of the pneamatic suit.

**Comment by desht** [comment]
If I do get round to adding a sword, it will probably be something like #729

**Comment by scarabx** [comment]
My understanding was that a suggestion has to fit into the mod's atmosphere. What does a weapon that uses plasma have to do with compressed air. Everything about my sword suggestion has something to do with compressed air.

**Comment by desht** [comment]
Because the "light saber" linked in the video is using a pressurised gas feed.  A weapon requiring LPG and pressure would actually fit into the mod's theme quite well.

Some of the other ideas in your suggestion can actually be already done (knockback via pneumatic boots, homing missile attacks via micromissiles), and I don't personally like the idea of an item that's impossible to drop.
