### ISSUE TITLE
armada drone failing 

### ISSUE THREAD

**Issue by phillyboi72** [TeamPneumatic/pnc-repressurized#1098]
### Describe the bug

I cgarge the armada to get a pcb blueprint and it took the gems once and never delivered after that the drones bug in the air so no it doesnt take the gems nor give me the pcb blueprint i need thid to build the uv light box to continue the drones everything els works flawlessly 

### How to reproduce the bug

charge the armada and try to buy the pcb blueprint 

### Expected behavior

take the currency it wants and deliver the product  

### Additional details

it would be cool to produce the blueprint in the pressure chamber like you can with empty ones or at least have a 25% chance of getting one when making empty  ones 

### Which Minecraft version are you using?

1.16

### Which version of PneumaticCraft: Repressurized are you using?

1.16.2 

### Crash log

no crash log on server

**Comment by desht** [comment]
What's an "armada"?

Also, 1.16.2 isn't a valid mod version.

**Comment by mrlol4ever** [comment]
I think what they are trying to say is that they are charging the amadrone tabled and then ordering a pcb blueprint, But when they do this the drone gets stuck in the air and doesn't deliver it.

But yeah that doesn't matter if its in 1.16.2

**Comment by desht** [comment]
If the amadrone is appearing and just sitting there, it's possible that drone AI has been disabled on the server - check `config/pneumaticcraft-common.toml` for the `stop_drone_ai` setting.

That should always be true normally and only set to false if there's an actual problem with drones causing server crashes etc. But I've seen in the past people set that to false for whatever reason and then wonder why Amadron stops working.

**Comment by desht** [comment]
Closing due to lack of response
