### ISSUE TITLE
Personal Defense Drone

### ISSUE THREAD

**Issue by scarabx** [TeamPneumatic/pnc-repressurized#1099]
### Describe the feature

Will you please hear me out and consider my suggestion before discarding it. I will do anything I can to see this suggestion became a reality. As soon as I got the idea I realised that it is one of my biggest wishes for a mod.

Personal Defense Drone(PDD):
A drone that can be carried in your hotbar and that can be charged through the pneumatic chestplate charge upgrade and that can be charged via the aerial interface when it's in the air. You then press a keybind and the drone takes of out of your hotbar and it then follows you and to make it return to your hotbar you press the keybind again. 

You can shift click the drone while it's in your hotbar or you can press a keybind while it's in the air and then a gui appears where you can change the drone's mode or change the entity's it should track just like the micromissiles. The modes will be: jackhammer and minigun, only jackhammer, only minigun, only camera. And it can be equipped with a minigun upgrade and then it follows you and shoots attackers or it can shoot passive mobs if you choose that in the gui. 

And you can also look at entities with your helmet entity tracker upgrade and press a keybind like the hacking keybind that makes the drone lock onto the target. It then leaves you and flies to the target to attack it, it will have a limited range. If you are then attacked while it's away you can press the keybind again and it will return. You can also equip the drone with tnt and target a mob in a mob horde with another keybind, it will fly to the mob horde and explode. 

After a set amount of time the drone will stop and return to your inventory, and then a cooldown will start before you can use it again. Damage from mobs or the environment will make the drone start the cooldown faster. You then have to wait before you can use it again. 

The drone will be able to use the following upgrades:
Speed: increases it's flight speed and and makes the cooldown timer shorter.

Armor: makes the drone take longer before starting the cooldown.

Volume: increases it's air capacity.

Minigun: enables it to shoot mobs that you choose.

Jackhammer: When you send it to a target and the target is behind a obstacle, it will mine the obstacle. A new feature also for the block tracker: you can choose track ores, and you then press the same lock on button and the drone will go and mine it.

Camera: you can choose camera mode in the gui, you view then switch to the drone and you fly it with normal mouse and WASD keys. You can't move while doing this, and if you hang in the air with jet boots you will float to the ground. You can then fly around and do recon, it will also have a limited range and if you reach the limit it will stop flying and then you can only reverse or turn around.

Range upgrade: will increase camera mode range and lock on range.

### Reasons why it should be considered

Pneumaticcraft has a lot of drone types, but not personal drones. This suggestion fits well into pneumaticcraft's theme and when you play with a fully upgraded pneumatic suit, you still die to easily when playing with hard mods, and I think the option for more defense should be available and the drone gives that option.

**Comment by desht** [comment]
This is too complex for a pre-programmed drone, which are intended to be simple creations easy to make in the early game. Programmable drones can be programmed to do most of what you want here, and people have written some smart programs in the past to do this sort of thing.  The main point of drones is that players write programs for them; the pre-programmed drones are intentionally limited in functionality.

So, sorry but no.

**Comment by scarabx** [comment]
Ok, so is it possible to code drones to do it?

**Comment by desht** [comment]
Yes, it's possible.  Not easy, but possible.

**Comment by scarabx** [comment]
Do you know of an tutorial that tells you how to do it. If yes, will you please give me the link to a tutorial?
