### ISSUE TITLE
Drones cant be automatically dispatched

### ISSUE THREAD

**Issue by Fennecai** [TeamPneumatic/pnc-repressurized#110]
Ok, so, I am usnure if this is a bug or not, but there doesnt seem to be a way of automating the dispatch of drones from a charging station. I have a farm setup where drones automatically suicide over a hopper that connects to a charging station when they are too low on pressure. the problem is, Once they are charged, i have to keep manually going to take them out of the charger and place them again. i think i remember that in a former version of pnumaticraft, you could have a vanilla dispenser place them and they'd start working, but now it just drops the item. so- if you can add the ability for dispensers to place drones the way they place mobs with the spawn egg, that's be great.

**Comment by desht** [comment]
If you put a Dispenser Upgrade in your charging station(s), it becomes a charge pad which drones will automatically fly to when low on pressure - no need for suiciding or hoppers.  Once charged they should carry on with their tasks as normal.

Having said that, the ability to auto-deploy drones from a dispenser isn't a bad idea, although such drones wouldn't have a valid owner - which means if you're using any kind of protection like FTB utils, the drones would be unable to break anything.

Have you tried deploying them with (say) a Extra Utils 2 Mechanical User, or a Modular Router with an Activator Module?

**Comment by MineMaarten** [comment]
Placing down a drone with another drone should do the trick (using the 'right click block' piece)

**Comment by MineMaarten** [comment]
Confirmed that you can place down a Drone simply by using the Right Click Block piece, for example, use this program: https://pastebin.com/9cqCpb1U
Select for the import items piece a chest with another drone in.
Select for the right click block piece any block where you want the drone to spawn.

But, if you really want to use a Dispenser, you can in upcoming version ;).
