### ISSUE TITLE
[Feature Request] Tag mobs that have spawned from pressurized spawners.

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#1100]
### Describe the feature

What I mean is, to quite simply add an entry into `ForgeData` on any entity that has been spawned by the spawner. 

### Reasons why it should be considered

This would be useful for technical/pack making reasons, for example being able to target these spawned mobs via script to buff them in interesting ways. For instance, I could target any zombies it spawns and give them a special item in their hand that they could drop. Or buff them in interesting ways.

**Comment by desht** [comment]
Sounds good.  Say, a `pneumaticcraft:pressurized_spawner` boolean value (set to true) on entities spawned by a Pressurized Spawner?

Looking at 1.18+ for this?

**Comment by MuteTiefling** [comment]
That'd be perfect. I'm targeting 1.19, personally.

**Comment by desht** [comment]
Fixed in latest release

**Comment by MuteTiefling** [comment]
woo, thanks :D
