### ISSUE TITLE
Unable to configure pressure values in upgraded Tube Modules

### ISSUE THREAD

**Issue by Lgmrszd** [TeamPneumatic/pnc-repressurized#1114]
### Describe the bug

When trying to type values in the tube modules with Expansion Card installed, such as Regulator and Pressure Gauge (without advanced config enabled), value is not saved upon closing the gui.

Uploading Kooha-2022-12-22-08-16-35.mp4…

### How to reproduce the bug

Try to configure Tube Module

https://user-images.githubusercontent.com/16291541/209062700-f776ec26-9a5e-4784-a19e-33c8cb39ae76.mp4

### Expected behavior

Configuration is saved

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

3.4.3, but I've encountered this on previous versions as well

**Comment by desht** [comment]
As mentioned on discord, I can't actually reproduce this.  Any more info on your setup would be useful...

**Comment by desht** [comment]
Update: likely related to locale settings, although hard to reproduce.

**Comment by desht** [comment]
I think this is fixed; closing.  Feel free to re-open if you still see the problem in the latest release.

**Comment by AliveDevil** [comment]
On 4.3.4 (1.19.2, Forge 43.2.11, Microsoft JRE17) with game set to English, on Windows locale de_DE the pressure gauge module doesn't apply the simple pressure value.
