### ISSUE TITLE
Rejoining the singleplayer world disconnects heat pipes from blocks with heat frames

### ISSUE THREAD

**Issue by Lgmrszd** [TeamPneumatic/pnc-repressurized#1116]
### Describe the bug

As the title.
Made a setup in test world then rejoined it. Heat pipe got disconnected from chest with heat frame on it. This is both visual and in the heat exchanging logic, as the frame stayed ambient temperature until heat pipe got reconnected.

![image](https://user-images.githubusercontent.com/16291541/209907635-36f5cfb5-04d0-4731-b24c-83d4467d040b.png)

### How to reproduce the bug

1. Make a setup with heat frame and heat pipe in singleplayer world.
2. Exit the world.
3. Join back.

### Expected behavior

It stays connected

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

1.18.2-3.4.4-14

**Comment by desht** [comment]
Actually I noticed this too recently (and it's not just single player, I've seen it happen on dedicated server too)

Update: timing issue - the heat pipe (or any other block entity which handles heat) scans for neighbours before the semiblock tracker map (blockpos -> semiblock) has been populated.  Shouldn't be too hard a fix.

**Comment by desht** [comment]
Fixed in latest release
