### ISSUE TITLE
Manometer (and other tools possibly) shouldn't use air if the player is in Creative mode

### ISSUE THREAD

**Issue by Lgmrszd** [TeamPneumatic/pnc-repressurized#1117]
### Describe the feature

I'd want for pneumatic tools to not consume air (and kept working if there's no air) if the player that is using them is in creative mode.

### Reasons why it should be considered

When debugging setups or my machines I sometimes just spam Manometer on the blocks to see how air/temperature changes over time. This drains air quite quickly, and swapping new Manometers from JEI/Creative mode becomes a bit annoying.
Possible solution is to have a Pneumatic Chestplate with Charging + Creative upgrades... But it would be easier if tools just didn't consume air.

**Comment by desht** [comment]
Yeah tools shouldn't consume air in creative.  Just an oversight, really.

**Comment by desht** [comment]
Fixed in latest release
