### ISSUE TITLE
Crash when Part of a logistic system is in a loaded chunk and part in an unloaded chunk

### ISSUE THREAD

**Issue by akamber** [TeamPneumatic/pnc-repressurized#1118]
### Describe the bug

I have had a few crashes where a requester in a loaded chunk is making a request to a provider in an unloaded chunk, causing a crash.

### How to reproduce the bug

Not entirely certain, it once crashed upon loading into the game, but the systems are in a chunk right next to each other, and I was within 2 chunks of the entire system.

### Expected behavior

Shouldn't crash when it's unloaded.

### Additional details

[crash-2023-01-01_21.18.14-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/10332522/crash-2023-01-01_21.18.14-server.txt)
[crash-2023-01-01_21.49.38-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/10332523/crash-2023-01-01_21.49.38-server.txt)

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

3.4.3-8

**Comment by desht** [comment]
Should be fixed in latest release, closing.  Please reopen if you see continuing crashes.
