### ISSUE TITLE
Drone disapears with a "dig program"

### ISSUE THREAD

**Issue by gamelnderGamler** [TeamPneumatic/pnc-repressurized#112]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
1.12.2-forge1.12.2-14.23.1.2604
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.4.0-136
### Describe your problem, including steps to reproduce it
Made a program with a dig piece and after i dispatched the drone my drone vanished. (the dig place was 2 blocks away) 
I tried different programs allways with a dig piece and my drone allways disapeard after i dispatched it.
### Any other comments?
There was no teleport animation. My Helmet said "lost target" after the drone disapeard.

**Comment by desht** [comment]
Could you upload the program you're using please (use the Pastebin export button on the programmer and give us the link here)?  I haven't been able to reproduce this in my test world.

**Comment by gamelnderGamler** [comment]
sorry, i wrote the wrong forge version. This is the right version: 1.12.2-forge1.12.2-14.23.1.2587.
(Modpack all the mods 3)

I noticed, that the drone only vanished, if the dig area is within other blocks. If the area is "in air" the drone just does nothing.

I dont get drone death messages. Its just gone (in between 1-2seconds) with all items in its inventory. 
Until now i have this problem only with the dig piece. (place, pick up is working fine)

The program iam using: https://pastebin.com/4yP4u1vM 
(But it also happens with much bigger programs)

Area when drone disapears:
![drone disapears](https://user-images.githubusercontent.com/22398257/36062900-805f9c84-0e75-11e8-964b-62793fe2bc07.PNG)

Area when drone does what it should do:
![drone does nothing](https://user-images.githubusercontent.com/22398257/36062907-95749a02-0e75-11e8-9d23-868d6a1b5d0f.PNG)

**Comment by desht** [comment]
Very strange, and I can't reproduce it in my test world (tried both in dev environment, and in a dedicated server test world).  I wonder if some other mod is forcibly removing the entity because it's trying to dig somewhere the other mod thinks it shouldn't be...

Are you using FTB Utils and claimed chunks, maybe?

**Comment by gamelnderGamler** [comment]
The chunks arent claimed.

Hmm, this happens everytime when i try it. On the server and in the singleplayer world. 

But if you cant reproduce it, maybe its my modpack. If no one else have this problem, it isnt that big of a deal. The building part works fine and thats much more important. 
There are many other ways to get rid of stuff in a area. 
So maybe better wait if someone else has this problem aswell.
