### ISSUE TITLE
Elevator base not rendering after extending 25+ blocks

### ISSUE THREAD

**Issue by Archy-X** [TeamPneumatic/pnc-repressurized#1120]
### Describe the bug

When using the elevator and the base travels above around 25 blocks high, the floor of the elevator stops rendering and becomes invisible (though still functional). Moving the elevator back down makes the floor reappear. My entity render distance is set to 400% so it is unlikely that is the issue.

### How to reproduce the bug

Build a 2x2 elevator with a max extension of at least 30 meters. Use elevator callers to extend the elevator to its max height. The floor below will become invisible.

### Expected behavior

The floor should stay visible the entire time.

### Which Minecraft version are you using?

1.16

### Which version of PneumaticCraft: Repressurized are you using?

2.15.12-13

**Comment by SkyTheCodeMaster** [comment]
How did you manage to fix this? Running into this issue as of 6.0.16+mc1.20.1 .
