### ISSUE TITLE
Entity Filter Crash

### ISSUE THREAD

**Issue by ShadowzOfTheDark** [TeamPneumatic/pnc-repressurized#1123]
### Describe the bug

Client crashes when you insert a quote or apostrophe into an empty entity filter prompt.

### How to reproduce the bug

> Place something like a sentry turret.

> Clear the entity filter of the sentry turret.

> Type in an apostrophe or a quote into the entity filter prompt.

> Game will crash.

### Expected behavior

You should be able to enter these characters without the client crashing.

### Additional details

This will additionally happen if you try to append after a semicolon, so something like the following:
@mob;"
Would also crash the game.

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.2.0

### Crash log

https://gist.github.com/ShadowzOfTheDark/89e930f8dc4a30f4dcb1431f1419333a

**Comment by desht** [comment]
Fixed in latest 1.18/1.19 releases
