### ISSUE TITLE
Entity Filter Quoting Players

### ISSUE THREAD

**Issue by ShadowzOfTheDark** [TeamPneumatic/pnc-repressurized#1124]
### Describe the bug

It is currently not possible to select players by name with the entity filter functionality.

### How to reproduce the bug

> Place something with an entity filter like a sentry turret.

> Go into survival mode (So the turret can target you)

> Clear the default entity filter prompt so it is blank.

> Enter your player name in the filter like so: 'player_name'
This may crash your game until this is fixed: #1123 

> The sentry turret will not target you.

### Expected behavior

The entity filter should allow you to select a specific player.

### Additional details

Quoted filters do work on named mobs. So if your username was "Bob" the filter could never target you but it could target a creeper named "Bob".

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.2.0

**Comment by desht** [comment]
Fixed in latest 1.18/1.19 releases
