### ISSUE TITLE
PC:R breaks Ceramics' Clay Buckets

### ISSUE THREAD

**Issue by EmosewaPixel** [TeamPneumatic/pnc-repressurized#113]
### Describe your problem, including steps to reproduce it
 When PneumatiCraft is installed together with Ceramics, it causes Ceramics' Clay Buckets to turn into Iron Buckets when picking up any modded fluid. As out of all the 245 mods in my pack only PC:R causes this strange mod interaction, I believe that the issue is on its side (somehow).

**Comment by desht** [comment]
Yep, PNC:R was at fault (some code ported over from 1.7.10 didn't make sense in this environment).  Fixed now.
