### ISSUE TITLE
Visual bug with the Oculus mod

### ISSUE THREAD

**Issue by DrSigma4164** [TeamPneumatic/pnc-repressurized#1130]
### Describe the bug

When you turn on the block tracker, and for example track inventory, it looks like on the 1st screenshot. That is, until you hover over one of the inventories, you can see them through the blocks.
However, when you install the Oculus mod, which is required for shaders to work, these "frames" around the inventory are not visible until you hover over a specific inventory. 
I made a video of how it happens when this modification is installed, also pay attention to the end of the video, where you can see how this frame "pulsates", that is, it appears and disappears. ((https://imgur.com/a/QfEeovK)).
And this bug is not related to any shaders, but to the Oculus mod itself, even when there are no shaders in the folder with shaders, the bug is present.

![image](https://user-images.githubusercontent.com/93322905/213887996-b356b60a-6a22-47c3-80ed-2646c9f0cbaf.png)

### How to reproduce the bug

1) Install the Oculus mod and a sodium port, such as Rubidium.
2) Put on a helmet with a block tracker and turn on the tracker
3) To see that there is no frame around the tracked blocks until we hover over them.

### Expected behavior

So that everything was like on screenshot 1

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.2.0-16

### Crash log

debug: https://gist.github.com/bf06595f4739d60e4d329e6882a7d13d.git

**Comment by desht** [comment]
Problems like these are on Oculus to fix, not PNC.  Oculus/Rubidium significantly change several aspects of rendering, and it's up to those mods to ensure that all other mods continue to render when they're present.
