### ISSUE TITLE
Universal Sensor Entity Filter Text Box Selecting/Un-selecting Itself

### ISSUE THREAD

**Issue by CodyTheRed** [TeamPneumatic/pnc-repressurized#1132]
### Describe the bug

While setting up the Universal sensor, if you apply 0.5 or more bars of pressure, the entity filter of the sensor starts to select/un-select itself and does not allow you to enter more than 1 text character at a time, before needing to re-click on the text box.

Edit: It also does this after closing and re-opening the GUI and/or leaving the Entity Tracker options menu. 

Edit 2: Text box constantly clears

### How to reproduce the bug

Add pressure, close the GUI, or leaving the Entity Tracking options GUI causes the Text Box to start Selecting/un-Selecting itself.

Closing the GUI or leaving the Options GUI causes the text box to clear

### Expected behavior

Expected the text box to not constantly un-select/select itself.

### Additional details

This is all coming from the Beta 1.1.1 version of the DireWolf20 1.19 Modpack.

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.2-4.2.0-16

**Comment by desht** [comment]
Fixed in latest 1.18/1.19 releases
