### ISSUE TITLE
Creeper Seeds are not dropping

### ISSUE THREAD

**Issue by IgnisAstra** [TeamPneumatic/pnc-repressurized#1134]
### Describe the bug

I am using TNP Limitless 6 as a modpack for a server i'm on. Creeper seeds do not show up on JEI unless it's from Mystical Agriculture, yet there are supposed to be seeds dropping from Creeper added by PneumaticCraft, I already looked through the configs and couldn't find anything about the seeds. Unknown with what to do. 

I also know the creeper needs to not have exploded, which i am able to do multiple times.

### How to reproduce the bug

Killing the creeper without it exploding.

### Expected behavior

Was hoping a creeper would drop the seeds

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.2.0-16

**Comment by desht** [comment]
PneumaticCraft doesn't drop Creeper seeds, at all.  No idea who gave you that misinformation.

**Comment by desht** [comment]
Unless you're thinking about Creeper seeds from the very original PneumaticCraft in Minecraft 1.6.4... in which case - no that hasn't been a thing for a *very* long time.  It wasn't even a thing back in 1.7.10 *before* I did the port :D
