### ISSUE TITLE
Pressure Gauge render issue

### ISSUE THREAD

**Issue by dredgemage** [TeamPneumatic/pnc-repressurized#1136]
### Describe the bug

I have an ATM8 server I am playing on but whenever I place multiple pressure gauges in my base the rendering on them seems to stretch from one gauge to the other (see first screenshot below). 

Moving far enough away from the gauges will cause the issue to disappear. (example in second and third screenshots). 

![2023-02-02_09 58 54](https://user-images.githubusercontent.com/6761184/216376398-b112509f-8f07-413b-8bd6-5a809e10b054.png)

Issue present
![2023-02-02_09 59 31](https://user-images.githubusercontent.com/6761184/216377372-e8db5b81-9f40-4925-bd72-5967868cd522.png)
Take one step back and it is gone
![2023-02-02_10 06 13](https://user-images.githubusercontent.com/6761184/216377498-0fe79027-24c4-419b-ab22-9ecb4f770848.png)

### How to reproduce the bug

Place multiple pressure gauges in the world near enough for them to both 'be active' at the same time.

### Expected behavior

I expect the rendering of the gauges to not stretch between individual gauges

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.1-4.2.0-16

**Comment by desht** [comment]
Oculus is to blame here.  Works fine without Oculus (even if Rubidium is installed), but screws up with Oculus installed.  Complain to them, please.
