### ISSUE TITLE
Kerosene lamp doesn't like kerosene

### ISSUE THREAD

**Issue by Bitgedon** [TeamPneumatic/pnc-repressurized#1137]
### Describe the bug

The kerosene lamp seems to believe that kerosense isn't a valid fuel. Purely visual the lamp still works perfectly fine but it complains about it none the less.
![Minecraft_ 1 19 2 - Multiplayer (3rd-party Server) 2_3_2023 20_31_13](https://user-images.githubusercontent.com/95064899/216740122-fff989bc-1d73-4f60-aa4b-3c2a775f2f90.png)

### How to reproduce the bug

Not sure since it's so simple. It's a server so that might have something to do with it. I left it on at 15 blocks radius with no automation. Logged in and checked it only to find it reporting it as a "problem"

### Expected behavior

Kerosense is a valid fuel. Unless kerosense can somehow go bad.

### Additional details

Technically not the latest release of PnC but since it's the latest stable version and the real latest is beta and this wasn't mentioned in the changelog I thought I'd put it here just in case.

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.2-4.20-16

**Comment by desht** [comment]
It's fine here in my test world, so I suspect your instance has a problem with fuel values not sync'ing to the client properly.  Fuel values are done via the vanilla recipe manager (i.e. auto-sync'd to the player when they connect), so I'd check your server and client logs for errors when you log in.  If something is messing up recipe sync, that would cause this error.

The other thing to check is the Available Fuels tab in the Liquid Compressor gui - does that show the expected fuel values?

**Comment by Bitgedon** [comment]
I've rejoined since opening this and it seems to be fine now, no errors related to recipes in the console but if this is still open when I see the issue again I'll check all of these.

**Comment by Bitgedon** [comment]
Ok, I'm probably too much of an idiot for github. I didn't realise logs were past records of the console. Regardless I found them and checked everything on the day of when I found the problem and all I can find that's even tangentially related is this line

[20:28:39] [Render thread/ERROR]: detected someone trying to get recipes for PneumaticCraftRecipeType[pneumaticcraft:fuel_quality] with no world available - returning empty recipe list

From the client logs.

**Comment by desht** [comment]
That error can happen on startup if some mod is scanning recipes early on the client (I think Minecolonies might do it, IIRC).  It *shouldn't* break anything on PNC, just means certain info about the PNC fuels won't necessarily be available to that mod on the client.

**Comment by desht** [comment]
Seems like a one-off where recipe data didn't get sync'd to your client properly for some reason.  Going to close this for now, but if it re-occurs feel free to re-open.
