### ISSUE TITLE
Minigun Ammo duplication

### ISSUE THREAD

**Issue by niclan051** [TeamPneumatic/pnc-repressurized#1139]
### Describe the bug

You can throw minigun ammo out of the magazine GUI, move the minigun item to a different inventory slot, and when you re-open the GUI the ammo appears back

### How to reproduce the bug

1. Open the GUI of a loaded minigun
2. Unload the minigun without closing the GUI
3. Move the minigun item to a different inventory slot
4. Close the GUI

### Expected behavior

Ammo doesnt stay in the minigun

### Which Minecraft version are you using?

1.18

### Which version of PneumaticCraft: Repressurized are you using?

3.5.0

**Comment by desht** [comment]
Fixed in latest 1.18/1.19 releases.
