### ISSUE TITLE
Filter option in pneumatic helmet isnt working

### ISSUE THREAD

**Issue by gamelnderGamler** [TeamPneumatic/pnc-repressurized#114]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
1.12.2-forge1.12.2-14.23.1.2604
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.4.0-136
### Describe your problem, including steps to reproduce it
Maybe iam doing something wrong.
In the pneumatic helmet options i want to filter my entity tracker for drones (@drone). But if i close the menu, the filter isnt there.
### Any other comments?
You are doing a great job! Thank you very much :).

**Comment by desht** [comment]
This seems to be working fine here:

![2018-02-10_10 33 35](https://user-images.githubusercontent.com/736831/36061136-e0f5cf50-0e4d-11e8-9459-4f398e1f59e2.png)

The two drones are tracked but the cow is not.

**Comment by gamelnderGamler** [comment]
sorry, i wrote the wrong forge version. This is the right one: 1.12.2-forge1.12.2-14.23.1.2587.
(Modpack all the mods 3)

If i apply a filter in a singelplayer world (creativ mode) it works, but on a server the filter isnt working.

I started the singelplayer world with a different Pneucraft version, but i changed it so it shouldnt matter?

Helmet in the multiplayer world
![filter](https://user-images.githubusercontent.com/22398257/36062820-471bf69e-0e74-11e8-8a10-21e1407c7bcd.PNG)


Helmet in the singleplayer world
![filter2](https://user-images.githubusercontent.com/22398257/36062824-57c76370-0e74-11e8-97a1-3d8f6377ce10.PNG)

really strange.

**Comment by desht** [comment]
Yeah, guessing something's not being synced properly here.  I'll investigate further...

**Comment by desht** [comment]
Problem was a server-side packet handler (handling filter updates) calling a client-only method, which obviously failed.  Will be fixed in next release (or build 144+ from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/)
