### ISSUE TITLE
Fuel Tab in Kerosene Lamp

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#1140]
### Describe the feature

It would be nice if the Kerosene Lamp had an indication of what fuels it accepts.

### Reasons why it should be considered

It feels awkward that the only way to know what fuels are registered to it is to look in a Liquid Compressor.

**Comment by desht** [comment]
Yeah, it probably should.  I should probably also get this info displayed via JEI while I'm at it...

**Comment by MuteTiefling** [comment]
Jei integration would be wonderful.

**Comment by desht** [comment]
Added in 4.3.2 release

**Comment by MuteTiefling** [comment]
Awesome thanks!
