### ISSUE TITLE
Kerosene Lamps cause chunk saving problems

### ISSUE THREAD

**Issue by Bitgedon** [TeamPneumatic/pnc-repressurized#1141]
### Describe the bug

Placing down a kerosene lamp with a range more than zero and attempting to turn off my server results in all chunks with Kerosene lamps in it to fail to save. 

### How to reproduce the bug

ditto the description.

### Expected behavior

The chunks to save. 

### Additional details

As with an issue from last year with similar symptoms. The chunks will get shifted around sometimes. Only on single player however. Server usually is fine after I kill it. But obviously this is not a good solution.

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.2-4.3.1-20

### Crash log

https://pastebin.com/Vat3HkjV

**Comment by desht** [comment]
Hmm, yes, there's an issue here as well.  I'll see if I can get that sorted today (and an update released).  Potentially quite damaging, I'm surprised this hasn't been reported before. Although I suspect the Kerosene Lamp doesn't get a huge amount of use.

**Comment by desht** [comment]
Fixed in 4.3.3 release
