### ISSUE TITLE
Heat Frame in 1.19.2-4.2.0-16 produces "please report" error and does not work

### ISSUE THREAD

**Issue by DFireTech** [TeamPneumatic/pnc-repressurized#1142]
### Describe the bug

When you use a heat frame on an inventory and place lava around it, it is not smelting as it should and has the error above

### How to reproduce the bug

* Place heat frame around chest
* error shows up

### Expected behavior

Shouldnt have the error

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.2.0-16

**Comment by desht** [comment]
Update to latest.
