### ISSUE TITLE
Mekanism thermals only partly functioning

### ISSUE THREAD

**Issue by Vectrobe** [TeamPneumatic/pnc-repressurized#1145]
### Describe the bug

Mekanism thermal pipes can inject heat into pneumatic blocks, heatsinks, machines, etc, however pneu devices fail to transfer any heat into mekanism pipes and devices, even if you have a block of compressed iron at the 2000C cap

### How to reproduce the bug

Have both pneu and mek installed, place down a mek resistive heater and set the power to something silly like 100000, have it powered by something, and use any of the mek heat conductors to transfer the heat into a compressed iron block.
The block should heat to 2000C pretty quickly, but then if you place more mek conductors off of said block and into another block, you'll see that the second block remains at ambient, and the conductors will also remain cold.
You can try setting the mek conductor connections to push or pull, but this is completely ignored by the iron block, so it'll heat up from the hot conductor even if said conductor is set to pull heat instead.

### Expected behavior

the transfer behaviour should be fairly consistent in both directions, including with the heat ratio and transfer efficiency in the config applied. eg something like as follows;
`blockHeat = lerp(blockHeat, (pipeheat * mekRatio), 1 * deltaTime * transferEffeciency  )`
`pipeheat = lerp(pipeheat , (blockHeat / mekRatio), 1 * deltaTime * transferEffeciency  )`

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.2-4.3.2-21

**Comment by desht** [comment]
Yeah, there are problems there, and there isn't a simple fix. There are some very fundamental differences in how Mek and PNC handle heat internally, and there are some definite kludges in the code to compensate for that (see https://github.com/TeamPneumatic/pnc-repressurized/blob/1.19.2/src/main/java/me/desht/pneumaticcraft/common/thirdparty/mekanism/Mek2PNCHeatProvider.java#L87-L104 for more info)

Really, if you want to exchange heat between Mek & PNC, PNC Heat Pipes are the way to go.
