### ISSUE TITLE
Display amount/unit on logistics filter entries with only 1 unit

### ISSUE THREAD

**Issue by Shados** [TeamPneumatic/pnc-repressurized#1147]
### Describe the feature

Currently, the amount (and potentially the unit) for a given logistics filter entry is only shown if that entry is configured for >1 units. It would be better if they displayed the amount/unit even when configured for only 1 unit.

### Reasons why it should be considered

The majority of minecraft logistics mods that support some kind of "filtering" functionality work on the basis of moving *as many matching items as they can*, rather than on the basis of fulfilling a request for a *specific number* of items as Factorio and PNC do. 

When adding an item or fluid to a PNC logistics filter, it initially creates the filter entry with only 1 unit on it, meaning it does not render the amount/unit, and I've seen this mislead users (who are familiar with other mods) into believing that the filters are acting on the same "move as many matching as possible" basis as other mods do. By ensuring the amount/unit displays even for those newly-created entries, it would provide a visual cue that PNC logistics does *not* work that way, and thus provide a small improvement to the user experience.

### Additional details

Screenshots of current behaviour:
![dreamlogic-2023-03-02-14:59:22](https://user-images.githubusercontent.com/338268/222341134-1ad176ab-6400-4927-8b5b-134d2338d34c.png)

![dreamlogic-2023-03-02-14:59:39](https://user-images.githubusercontent.com/338268/222341149-56e4a9ec-4547-4f31-866c-1df29f5dfd88.png)

**Comment by desht** [comment]
Yeah, sounds like a sensible idea.

**Comment by desht** [comment]
Added in 4.3.4
