### ISSUE TITLE
presser mechanic JER name problem

### ISSUE THREAD

**Issue by Acat1234** [TeamPneumatic/pnc-repressurized#1148]
### Describe the bug

A very noticeable problem with JEI(+JER) and the presser mechanic villager if You search an item that the villager sells the name is VERY glitchy something like this
![2023-03-02_10 44 21](https://user-images.githubusercontent.com/126712560/222523983-a60a6d2a-9e95-43c7-9fca-f5a7f8ea0882.png)

### How to reproduce the bug

Simply use JEI(+JER) to see how to get an item that the mechanic will sell then the bug should be reproduced ok?

### Expected behavior

What I think shoud happen is Instead of that mess more of the right name idk what that will be though it will be better then that mess

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4,3,3-22

**Comment by desht** [comment]
Not sure what JER is doing there, but PNC correctly adds a translation key `entity.minecraft.villager.pneumaticcraft.mechanic` and `Entity#getTypeName()` returns the right translation, so I'd suggest complaining to the JER author about this.

**Comment by Acat1234** [comment]
ok
