### ISSUE TITLE
Player Special Variable Config

### ISSUE THREAD

**Issue by ShadowzOfTheDark** [TeamPneumatic/pnc-repressurized#1149]
### Describe the feature

A simple config to disable the ability to use the player special variable. Another option may be a range limitation on the variable, only allowing it to give a position of a player if the player is within "x" distance.

### Reasons why it should be considered

For some modpacks/servers being able to locate players with this variable may not be desirable.

**Comment by desht** [comment]
Related: max drone teleport range can already be limited in config, which can be used to mitigate griefing players with drones like this. 

However, more flexbility here is good, and being able to limit getting the location of another player is something that could be added.  Along with not allowing drones to teleport into areas protected by another player's security station(s).

**Comment by desht** [comment]
Added in 4.3.4
