### ISSUE TITLE
Update icon appears even though no new version is available

### ISSUE THREAD

**Issue by CSdiscoveries** [TeamPneumatic/pnc-repressurized#1152]
### Describe the bug

Playing with a set of mods running on Minecraft 1.16.5, I've noticed that Forge has a feature where it shows certain mods that have updates available. I'm not entirely certain whether or not this is a bug with Forge or with this mod, but the icon shows perpetually... And yes, I am using the latest version from Curseforge. 

### How to reproduce the bug

1. Install Forge 1.16.5, either recommended or latest doesn't seem to matter.
2. put the latest 1.16.5 version of PNCR in the mods folder, as well as dependencies.
3. start the game, look at the "mods" button on the main menu and if there's a green flashing thing... there's the issue.
4. Clicking on the mods button will show a list of installed mods, as normal. It'll show "Update available" for PNCR, linking to the Curseforge page... And there isn't any update available.

### Expected behavior

Since there's no update it seems, I'd expect it to... not show there being an update.

### Additional details

The update thing being incorrectly shown makes things difficult if there is an actual update available for a different mod. Which there sometimes is. 

### Which Minecraft version are you using?

1.16

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.16.5-2.15.12-13

**Comment by desht** [comment]
Should be OK now.  Problem was the build number in the mod version, which got reset when public builds moved from using a Jenkins server to Github Actions.
