### ISSUE TITLE
Nature's Aura compat with Extraneous Firestarter

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#1153]
### Describe the feature

This block functions nearly identically to the IE External Heater, using Aura instead of FE to heat a Furnace.

Would be neat if worked to provide PNC heat as well. 

### Reasons why it should be considered

Mostly just for fun. Cross mod compat is always appreciated.

**Comment by desht** [comment]
I don't suppose you know if Nature's Aura provides any kind of API for this block?  A quick perusal didn't find anything relevant, but I may have missed it.

IE does provide a clean capability-based API to its External Heater, making it easy to support.  I would need something equivalent in Nature's Aura to add integration - I don't want to do any non-API hacky solutions (that just causes headaches down the line...)

**Comment by MuteTiefling** [comment]
They have an extensive API, but I honestly have no idea if it covers that. 

https://github.com/Ellpeck/NaturesAura/tree/main/src%2Fmain%2Fjava%2Fde%2Fellpeck%2Fnaturesaura%2Fapi

**Comment by desht** [comment]
As far as I can tell, there's no kind of API for this integration in Nature's Aura, unfortunately :(

**Comment by MuteTiefling** [comment]
All good, thanks anyway!
