### ISSUE TITLE
Armor loosing functionality after going into free cam

### ISSUE THREAD

**Issue by 1Euro7Cent** [TeamPneumatic/pnc-repressurized#1155]
### Describe the bug

When I go into free cam the armor looses its advantages like elytra, and never goes back. Only when reloading the save game (rejoining the server)

### How to reproduce the bug

Have a free cam mod installed. Mine is this one:
[freecam_by_kapiteon-1.19.2.1.jar.zip](https://github.com/TeamPneumatic/pnc-repressurized/files/11131693/freecam_by_kapiteon-1.19.2.1.jar.zip)

(unzip it because of GitHub)

when going into free cam and back the armor looses its advantages

### Expected behavior

To work after going back into the main camera

### Additional details

Where is an example. I tried to activate the extra after going into free cam.

https://youtu.be/skb4zoAy6WY

(YouTube bc video is too large for GitHub)

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.19.2-4.3.2-21

**Comment by desht** [comment]
Not seeing that behaviour, sorry.  I can toggle in and out of freecam mode and my armour (flying, elytra, fall protection etc.) continue to work just fine.
