### ISSUE TITLE
PneumaticCraft lamp will prevent to build mekanism multi-block structure

### ISSUE THREAD

**Issue by zyxkad** [TeamPneumatic/pnc-repressurized#1159]
### Describe the bug

If I try to build a mekanism multi-block structure (e.g. thermal evaporation tower) near a active pneumatic lamp, it won't assemble cause some block placed wrong.

It actually is because pneumatic lamp will place some light source block to light the area, and it didn't tag the fake light source as minecraft:air

### How to reproduce the bug

1. Install forge, pneumaticCraft and mekanism
2. Place a pnC lamp, active it
3. Build a mekanism thermal tower next to it
4. The tower won't assemble cause there are some invalid blocks

### Expected behavior

The mekanism thermal tower should be assemble

### Additional details

https://github.com/mekanism/Mekanism/issues/7779

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.3.3-22

**Comment by zyxkad** [comment]
It will also block farming, I think the reason is same

**Comment by desht** [comment]
Fixed in 4.3.4 release
