### ISSUE TITLE
[feature request] blakclist of dimensions for oil lakes spawning

### ISSUE THREAD

**Issue by Zygus42** [TeamPneumatic/pnc-repressurized#116]
I really want Oil Lakes in our game, but really don't want them in the Twilight Forest dimension.  Would be great to have a blacklist of dimension ids to not spawn the lakes in.

**Comment by desht** [comment]
Yeah, good idea. We can add that.

**Comment by desht** [comment]
This is added in dev now, or you can test it with build 145+ from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/

See ``I:oilWorldGenBlacklist`` in pneumaticcraft.cfg, e.g.:
```
        # Oil worldgen blacklist: add dimension IDs to this list if you don't want oil worldgen to happen there.
        I:oilWorldGenBlacklist <
            1
            -1
            7
         >
```

Added 7 there, which is the default dimension ID for Twilight Forest.

**Comment by Zygus42** [comment]
Seems to work fine.  Well done, and in record time too :)
