### ISSUE TITLE
1.19.2 Liquid Compressors more customizable

### ISSUE THREAD

**Issue by DevDyna** [TeamPneumatic/pnc-repressurized#1160]
### Describe the feature

1. Create a config section with a blacklist/whitelist of liquid fuels that can burn on liquid compressors
2. JEI support of what can burn liquid compressors or custom tag to filter all fluids

### Reasons why it should be considered

1. Useful on making modpacks with custom fluids without add other mods that support liquid compressors
2. More clear view of what can burn before craft a liquid compressor or see any fuel

**Comment by desht** [comment]
Already doable via fuel value recipes: see https://github.com/TeamPneumatic/pnc-repressurized/tree/1.19.2/src/generated/resources/data/pneumaticcraft/recipes/pneumaticcraft_fuels for the default recipes.  Can be modified via datapack, CraftTweaker, KubeJS etc.
