### ISSUE TITLE
Bamboo Harvesting

### ISSUE THREAD

**Issue by Bitgedon** [TeamPneumatic/pnc-repressurized#1162]
### Describe the feature

Add bamboo to the harvester drone crop list.

### Reasons why it should be considered

I saw your message in the discord, nobody else posted it so might as well (atleast, nobody from what I can tell. I'm sometimes just blind).

**Comment by TheWommit** [comment]
You beat me to it!

**Comment by desht** [comment]
Fixed in 4.3.5 release
