### ISSUE TITLE
Stress on server when using transfer gadget between two Quark Oddities storage crates

### ISSUE THREAD

**Issue by Branjoman** [TeamPneumatic/pnc-repressurized#1163]
### Describe the bug

On my server I had two storage crates from Quark Oddities storing excess weapons from a mob farm, and a transfer gadget  on the top face transferring them from one to the other. For some reason, this seemed to put immense strain on the server and this small setup alone brought the server TPS down to 8, as can be seen in this spark log: https://spark.lucko.me/zaekLDob1L

### How to reproduce the bug

 - Place two storage crates from Quark Oddities next to eachother (in the initial case the crates were on top of eathother, unsure if positioning matters here)
 - Put a transfer node between them
 - This should cause the server to become significantly laggier. Each crate in the initial case was mostly full with items, but not completely (636/640 top, 397/640 bottom)

### Expected behavior

The server does not have significant strain put on it

### Additional details

Quark Versions:
 - Quark v3.4-395
 - Quark Oddities v1.18 

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.3.3-22

**Comment by desht** [comment]
If you drill right down through the Spark trace, you'll see the CPU time is actually being chewed up in Quark Oddities. The transfer gadget isn't doing anything special, just using the standard Forge capability system to move items from one item handler to another (and only one per second, it's not a fast transfer system).

So I'd suggest taking this over to Quark Oddities to see why their `CrateItemHandler.getTotal()` method is taking so much time.

![image](https://user-images.githubusercontent.com/736831/236666662-da9b0fac-0088-4c86-8f11-c30954e4955d.png)
