### ISSUE TITLE
Block Tracker crash

### ISSUE THREAD

**Issue by JWTHDYTWA** [TeamPneumatic/pnc-repressurized#1164]
### Describe the bug

Once i turned the "Enable Block Tracker" checkmark on, my client crashed. And it keeps crashing when I log in again.
I'm on TNP6 1.23.2 modpack.
It's likely a cross-mod issue.

### How to reproduce the bug

Try to activate Block Tracker upgrade in Pneumatic Helmet on TNP6 in a base with various machines within.

### Expected behavior

Not crashing...

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.2-4.3.4-24

### Crash log

https://gist.github.com/JWTHDYTWA/fe54db0309aaa2272b1ac3500930926d

**Comment by desht** [comment]
This is a bug in alchemylib (library mod used by Alchemistry), which is throwing an NPE while querying for the item handler capability.  While there's no requirement to support capability query on the client, the implementation shouldn't outright crash if used.

I'll add some code in PNC to guard against this in future releases, but this should also be reported to the Alchemistry authors.

**Comment by desht** [comment]
In the meantime, you can switch off the block tracker for your client by editing `config/pneumaticcraft/ArmorFeatureStatus.cfg` - find the line which says `"pneumaticcraft:block_tracker": true`, and change it to `false`.  That will get your instance up and running again.

**Comment by desht** [comment]
Fixed in 4.3.5 release
