### ISSUE TITLE
unfixed minor error:: imcompatable x10 speed boost with collector drones

### ISSUE THREAD

**Issue by tails1974seeyounextgame** [TeamPneumatic/pnc-repressurized#1166]
### Describe the bug

unfixed minor error:: imcompatable x10 speed boost with collector drones

atm8 modpack 19.2 minecraft 4.3.4-24

### How to reproduce the bug

from any version since the >10x speed boost was introduced
unfixed minor error:: imcompatable x10 speed boost with  collector drones
::>drone sits idle because it thinks its job is done and loops the line of code

### Expected behavior

the drone will move quickly

### Additional details

its directly due to the way the drone scans its lcoation vs other drones, it thinks its alreaydy arrived at its location to aquire the items and sits idle,

fairly certain it6 still works at up to 5x speed

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.3.4-24

**Comment by desht** [comment]
My collector drones with 10 speed upgrades work just fine to collect items.

> from any version since the >10x speed boost was introduced

No such version exists. 10 speed boosts is the maximum, and always has been.

**Comment by tails1974seeyounextgame** [comment]
always check the version number of your own mods before u respond. im in the latest version and using this modpack and the max speed for collectors is 25. butt anything above ten fails and ive had same issues in older versions. i also quite literally said 10 speed modules do work fine. anything above does not.

 itsa simple hit box scan issue

**Comment by desht** [comment]
Drone speed upgrades for all drones are hardcoded to 10, in the version you quoted and every other version for which I provide support. Hardcoded both in the GUI and when upgrades are checked by the entity.  And don't lecture me about checking the version of my own mod, thank you.

_It is not possible to install more than 10 speed upgrades in a collector drone._  If your modpack is somehow allowing, it's broken.

**Comment by tails1974seeyounextgame** [comment]
indeed ill notify the atm 8 modpack guy
