### ISSUE TITLE
Item Life Upgrade Description Missing in Armor Upgrade UI

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#1167]
### Describe the bug

The description for the upgrade does not show up in the Charging Station's upgrade UI, leading players to be confused about what the upgrade does

![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/70091260/f26ec564-73cd-4038-a5b4-97f098c34c6c)

### How to reproduce the bug

Place an armor piece in the Charging Station and try to expand the "Item Life Upgrade" GUI widget

### Expected behavior

There should be a description

### Additional details

I just grabbed this information from Discord, so cannot specify exact versions. Another player said it happens on Valhelsia 5. You can find the relevant Discord messages [here](https://discord.com/channels/380076480241336323/380100722420613121/1109159864317530192), [here](https://discord.com/channels/380076480241336323/380100722420613121/1109165632903192659) and [here](https://discord.com/channels/380076480241336323/380100722420613121/1109187547730559147)

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

Idk, just check latest

**Comment by desht** [comment]
Fixed in 4.3.5 release
