### ISSUE TITLE
Game crashes when loading

### ISSUE THREAD

**Issue by BloxMaster3** [TeamPneumatic/pnc-repressurized#1173]
### Describe the bug

Game Crashes whenever i try to load up my modpack saying: The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PneumaticCraft: Repressurized (pneumaticcraft)

### How to reproduce the bug

use the most recent release of pnc repressurized along with all the mods described in the crash report on windows 11

### Expected behavior

game doesn't crash

### Which Minecraft version are you using?

1.12 - UNSUPPORTED

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.12.2-0.11.15-398.jar

### Crash log

https://www.dropbox.com/t/npfEVcjdGAmzrKdZ

**Comment by desht** [comment]
You have a JSON syntax error in one of your config files under `config/pneumaticcraft/`, which means either your installation is corrupted, or you tried to manually edit one of those files and introduced an error.

Also, 1.12.2 is not supported (and has not been for a long time).

**Comment by BloxMaster3** [comment]
thing is though is that it works just fine when I remove pneumaticcraft so my save isn't corrupted, would it work if I deleted the config file or would that make it worse?

**Comment by desht** [comment]
It should work if you remove the config files under `config/pneumaticcraft/` - they will reset to their defaults next time you start. That includes armor gui settings etc.
