### ISSUE TITLE
[Config Addon] Max speed for jet boots upgrade

### ISSUE THREAD

**Issue by zyxkad** [TeamPneumatic/pnc-repressurized#1175]
### Describe the feature

We would like a configurable jet boots speed, because when it flys too fast, server will got stuck.
The jet boots could be config and limit the power in server side (now it's only on the client side).

### Reasons why it should be considered

Some server have a small world border which makes jet boot too powerful, some others have bad hardware then we gain chunk lag issue.

**Comment by desht** [comment]
Jet boots power is already configurable (from 0-100%) in the normal jet boots GUI.  The problem with adding a server side limit that players can't control is that this mod will get blamed when players' jet boots aren't as fast as they were expecting.

**Comment by zyxkad** [comment]
> Jet boots power is already configurable (from 0-100%) in the normal jet boots GUI. The problem with adding a server side limit that players can't control is that this mod will get blamed when players' jet boots aren't as fast as they were expecting.

This makes sence, but I want the server could set the **max limit**, and this limit should be show in the client side (set the maximum value of the slider), our server owner don't trust player will limit it in the client side, so please reopen it

**Comment by zyxkad** [comment]
Or anyway, can you give a option to disable flying for jet boots but reserve builder mode?
