### ISSUE TITLE
Solar Compressor temperature cannot be reduced when the compressor is off

### ISSUE THREAD

**Issue by belathus** [TeamPneumatic/pnc-repressurized#1176]
### Describe the bug

During the day, when the compressor is operating, a vortex tube next to the compressor works just fine. However, a storm came, and the vortex tube could no longer cool the machine; it ended up being locked at 407C. I was using a universal sensor targeting the compressor to maintain a temperature of 400C, but since the temperature was locked, the vortex tube ended up draining all of the compressed air throughout the rain storm.

### How to reproduce the bug

Use a universal sensor to control an active cooling system. Watch the system fail to cool when a rainstorm starts or at night.

### Expected behavior

I would expect to be able to reduce the machine's temperature even when it is raining or night time.

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.2-4.3.4-24

**Comment by belathus** [comment]
I see now that this is intentional: https://github.com/TeamPneumatic/pnc-repressurized/blob/1.19.2/src/main/java/me/desht/pneumaticcraft/common/block/entity/SolarCompressorBlockEntity.java#L243-L246

Hm. So, this encourages a passive cooling system rather than an active one. I figured an active one would work better given the temperature requirement.

**Comment by desht** [comment]
Yep, it is intentional.  Given that the Solar Compressor can produce a lot of pressure without any input other than sunlight, there are some management convenience trade-offs to be made...

**Comment by belathus** [comment]
That is a fair argument. Just modifying how I cool it solves my problem anyway, so I can't complain much.
