### ISSUE TITLE
Fluid Duplication using PNC tanks

### ISSUE THREAD

**Issue by belathus** [TeamPneumatic/pnc-repressurized#1177]
### Describe the bug

When putting a tank in the input slot of a full PNC tank and pumping from it, you can duplicate the fluid. You just have to pull the tank out of the input slot before it reaches the inner tank's contents.

### How to reproduce the bug

1. Place down a full tank (I used a 32,000 mb tank; see first screenshot).
2. Put another full tank in the first tank's fluid input slot (I used a 512,000 mb tank here; see second screenshot).
3. Pump from the tank to another tank (I was pumping into a reservoir for Create where each layer held 256 buckets; this way I never emptied the 512,000 mb tank).
4. When the third tank is full, take the second tank out of the first tank. Check the contents and note that it is still full.
5. Repeat steps 2-4.
![first tank](https://github.com/TeamPneumatic/pnc-repressurized/assets/3826783/90c2cbc5-8ccc-4a8d-bc10-6cd17b4f8087)
![second tank](https://github.com/TeamPneumatic/pnc-repressurized/assets/3826783/2a3c0612-c98a-4d8e-a916-51315156667b)

### Expected behavior

Well, I would expect the second tank to eventually run out of fluid.

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.2-4.3.4-24

**Comment by desht** [comment]
Confirmed, fix in progress.

**Comment by desht** [comment]
Fixed in 4.3.5 release
