### ISSUE TITLE
Selling Chisels&Bits Blocks via Amadron crashes multiplayer servers in 1.12.2.

### ISSUE THREAD

**Issue by HyperBeast43** [TeamPneumatic/pnc-repressurized#1178]
### Describe the bug

If you try to sell a Chisels&Bits block (say, a chair), a drone'll take all of them, crash the server upon the drone unloading, and remove the listing and take any that were left behind upon reboot.

### How to reproduce the bug

Create a custom trade listing, selling a Chisels&Bits block.
That's it. The drone will take your stock, crash the server, and remove your listing.

### Expected behavior

It'd sell them like usual, really. Not sure what else you want me to put.

### Additional details

If it helps, the NBT data for the C&B block I was trying to sell is `{side:3,BlockEntityTag:{b:61955,side:3b,s:4,nc:0b,X:[B;120B,-38B,99B,96B,97B,104B,102B,105B,126B,-62B,-36B,-84B,-62B,-32B,-64B,20B,26B,-58B,0B,-63B,17B,12B,12B,83B,-61B,24B,24B,84B,35B,24B,86B,77B,91B,-74B,64B,-3B,-26B,-44B,31B,-86B,-95B,-95B,17B,43B,51B,51B,-93B,-44B,50B,51B,103B,76B,91B,-103B,53B,99B,106B,104B,104B,24B,4B,47B,13B,-101B,-102B,25B,25B,49B,-75B,105B,81B, 4B,0B,101B,-50B,26B,-3B],lv:0}}`

### Which Minecraft version are you using?

1.12 - UNSUPPORTED

### Which version of PneumaticCraft: Repressurized are you using?

1.12.2-0.11.1-361

**Comment by HyperBeast43** [comment]
If this has been fixed in newer 1.12.2 versions, sorry; I'm only reporting this because I encountered it on a friend's Sevtech: Ages server.

**Comment by desht** [comment]
Sorry, 1.12.2 is a long way out of support.
