### ISSUE TITLE
Carbon Fiber as a Renewable Compressed Iron Substitute

### ISSUE THREAD

**Issue by Nathan-Harvey** [TeamPneumatic/pnc-repressurized#1183]
### Describe the feature

Carbon fiber composite item and block usable as a replacement for compressed iron in recipes, maybe with a higher yield for recipes like advanced tubes.
The process for producing it would begin with a thermopneumatic processing plant put under a vacuum with biofuel or an oil product, and given >= 300C to get carbon fiber sheets. (this is actually a truncation of a first oxygenated heating that is then followed by a much hotter heating in a vacuum, but that's extra steps that make the production too similar to plastic). These sheets then need to be processed in an etching chamber before being combined with liquid plastic in another TPP to make carbon fiber composites.

### Reasons why it should be considered

Right now the mod is hungry for compressed iron and the only factory-based option for producing it without having to go mining is with an iron golem farm, something which is somewhat out-of-character with the mod and probably violates the Geneva Convention. However, carbon fiber composites are strong, thermally conductive, used in construction and pneumatic parts, and produced from hydrocarbons, all of which is right up Pneumaticcraft's alley. It also provides additional uses for the etching machine past the assembly system and for the vacuum pump.

**Comment by desht** [comment]
It's a neat idea, but something that belongs in an extension (tbh it could be all done with KubeJS without even writing a mod) or modpack rather than the base mod.

As for getting lots of compressed iron, you're forgetting about drones and programmable controllers, both of which can be used to make a quarry (programmable controllers are ideal).
