### ISSUE TITLE
Fluid dupe with Fluid Tanks

### ISSUE THREAD

**Issue by andriihorpenko** [TeamPneumatic/pnc-repressurized#1184]
### Describe the bug

This bug introduces a dupe of any fluid. Reproduction steps are demonstrated below, but for now I will post a video of the whole process.

https://github.com/TeamPneumatic/pnc-repressurized/assets/13716167/48388248-916b-43df-9221-9177c8317938

### How to reproduce the bug

The order of steps is very important, but with these 8 steps you will be able to reproduce this issue.

#### Required items
2x filled buckets of the fluid you want to dupe
2x empty Fluid Tanks

#### Steps
1. Place any Fluid Task
2. Insert a filled bucket in the input slot
3. Take empty bucket from the output slot
4. Insert empty Fluid Task in the input slot
5. Take filled Fluid Task from the output slot
6. Insert a filled bucket in the input slot
7. Insert filled Fluid Task without taking empty bucket from the output slot
8. Keep taking and inserting filled Fluid Tank and see that internal fluid tank is filling up slowly, but the Fluid Tank item remains filled

### Expected behavior

Do not fill the tank if the output slot is filled and cannot be merged with the input item

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.3.5-25

**Comment by desht** [comment]
Confirmed, and thanks for the clear description.

**Comment by desht** [comment]
Fixed in 4.3.6
