### ISSUE TITLE
Logistics puzzle area

### ISSUE THREAD

**Issue by Coolcabbage** [TeamPneumatic/pnc-repressurized#1185]
### Describe the bug

The logistics puzzle piece requires a larger area than the logistic frames you are wanting to interact with
![Logi Bug](https://github.com/TeamPneumatic/pnc-repressurized/assets/24936875/89bf703e-4b70-4f15-85aa-3e63577b6d66)

### How to reproduce the bug

program a drone to logistic an area only just including the inventories

### Expected behavior

The drone should interact with blocks that are on the edge of its area

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.2-4.3.4-24

**Comment by johalun** [comment]
I saw this too. Not sure how much padding is required, I added 2-3 blocks on each side and got it to work. I know that just adding one extra block on the side where the frame is does not work so it might have to be on all sides.

**Comment by desht** [comment]
Fixed in recent 1.19 and 1.20 releases
