### ISSUE TITLE
Game crashes when using pneumatic wrench on create mod blocks

### ISSUE THREAD

**Issue by gruniu8** [TeamPneumatic/pnc-repressurized#1187]
### Describe the bug

when you use the pneumaticCraft wrench on any create mod blocks the game crashes (and when playing on server the entire server crashes)

### How to reproduce the bug

- open minecraft 1.19 forge with create mod and pneumaticCraft
- place any create mod block
- use the pneumatic wrench on it

### Expected behavior

it should rotate the block instead of crashing

### Additional details

yeah, idk what to say more about this

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.19.2-4.3.6-27.jar

### Crash log

https://pastebin.com/HWDuKnAt

**Comment by desht** [comment]
Create's changed their class layout since 0.5.0 when the PNC/Create wrench integration was added.  I'll support Create 0.5.1 in the next PNC release.

**Comment by desht** [comment]
Fixed in PNC 4.3.7 (now built against Create 0.5.1.c, latest 1.19.2 release)
