### ISSUE TITLE
[feature request] config for chest loot

### ISSUE THREAD

**Issue by Zygus42** [TeamPneumatic/pnc-repressurized#119]
I'm currently testing a new modpack, and I keep seeing Spawner Agitators in the chests i'm looking in.  As this is meant to be an expensive item due to the ghast tear and the steel, I would love a config option to remove this from the loot tables.

**Comment by Zygus42** [comment]
Oops, meant Compressed Iron not Steel - looks much the same.

**Comment by desht** [comment]
Yeah the default weighting is a bit common.  Discussing with @MineMaarten about this, my gut feeling is to leave it in the loot table, but make it much rarer (say 10% as likely).

**Comment by MineMaarten** [comment]
Agreed with the 10% of the current chance :)
