### ISSUE TITLE
Invalid moving sound AIR_LEAK for focus object

### ISSUE THREAD

**Issue by andriihorpenko** [TeamPneumatic/pnc-repressurized#1190]
### Describe the bug

We had an issue https://github.com/TeamPneumatic/pnc-repressurized/issues/1046 on 1.18.2 and it was marked as resolved. However, it is still valid for 1.19.2.

[crash-2023-07-27_20.35.17-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/12185330/crash-2023-07-27_20.35.17-client.txt)

### How to reproduce the bug

I cannot provide a complete reproduction as this happens quite unexpectedly. Sure enough players can hear air sounds prior to a client crash. This occurs quite frequently.

### Expected behavior

Play AIR_LEAK sound without accidental client crash

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.3.6-27

### Crash log

https://pastebin.com/NK4Ls3fs

**Comment by desht** [comment]
Fixed in recent 1.19 & 1.20 releases
