### ISSUE TITLE
Assembly Laser not affected by speed upgrades. 

### ISSUE THREAD

**Issue by Bitgedon** [TeamPneumatic/pnc-repressurized#1197]
### Describe the bug

The title explains it all. I noticed you fixed the drill brakes in issue 1146 which is greatly appreciate. I slapped a full 10 upgrades on the assembly line for the first time and noticed the laser arm is not at all affected by speed upgrades. Or if it is, it's severely under affected

### How to reproduce the bug

Create and use the assembly line with speed upgrades. The more speed upgrades the more obvious.

### Expected behavior

The laser arm should go zoooommm

### Additional details

https://github.com/TeamPneumatic/pnc-repressurized/assets/95064899/a1ddd157-360f-4038-8017-5de3183d5382

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.2-4.3.6-27

**Comment by desht** [comment]
Hmm.  Speed upgrades affect the robot arm movement speeds (and braking the drill faster is reasonable to have there). But the time taken for a laser (in effect, the laser intensity) to do its cutting isn't really the same thing.  So I'm calling this working as intended.
