### ISSUE TITLE
ID LIMIT ## The game crashed whilst initializing game The game crashed whilst initializing game Error: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Bajosi** [TeamPneumatic/pnc-repressurized#120]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### i just add mod and it wont start.

[crash-2018-02-13_19.33.39-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/1724147/crash-2018-02-13_19.33.39-client.txt)

**Comment by Bajosi** [comment]
when i add "NotEnoughIDs" mod it worked.. maybe you guys suggest it when you see this problem again.

**Comment by desht** [comment]
It's good that NotEnoughIDs fixed your problem.  I'll keep it in mind should anyone else have issues, thanks.
