### ISSUE TITLE
Vortex Cannon can Freeze Servers!

### ISSUE THREAD

**Issue by OliverWolf621** [TeamPneumatic/pnc-repressurized#1202]
### Describe the bug

With the Vortex cannon, you are cappable of hitting yourself. If you hit yourself repeatedly very quickly, the server (remote or integrated) will slow to a crawl, and can take MINUTES to update even a single tick.

### How to reproduce the bug

Spam click quickly to hit yourself with multiple vortex rings. Use alt+f3 to open the lagometer to view integrated server lag (on the right)

### Expected behavior

To not slow the server to a crawl

### Additional details

In my testing this does not outright crash the server, but slows it down so badly the only way to really fix it is to restart the server, or force quit with task manager in the case of a singleplayer world

### Which Minecraft version are you using?

1.18 - critical bugs only

### Which version of PneumaticCraft: Repressurized are you using?

1.18.2-3.6.1-29

**Comment by desht** [comment]
Best bet here is probably some rate limiting on how frequently each player can boost themselves with the vortex cannon.  Server slowdown is likely to be caused by fast player movement causing excessive chunk loading and (more seriously) chunk generation if player flies into new chunks.

**Comment by OliverWolf621** [comment]
I don't think its a chunk loading issue. I can cause this issue on my own singleplayer world, where after doing all of that, I stayed completely still for multiple minutes in already loaded chunks, and the integrated server only updated a total of 3 ticks. No chunks, new or pre-existing, were generated or loaded. I wouldn't describe the result as a server slowdown, but rather the server gets "stuck".
![2023-08-21_04 25 50](https://github.com/TeamPneumatic/pnc-repressurized/assets/142481537/cd70df89-ce0d-4308-bdc0-c96ef60cce87)
(ignore the 108 mods loaded, I tested this on a fresh install with only Pneumaticcraft and got the same result, I just don't have any other screenshots lol)
If used on a public server, one griefer could bring the entire server to a screeching halt, potentially force a server restart, or even prevent it from running. This only happens when the vortex cannon hits the user rapidly, so perhaps a fire rate limit could prevent this from happening

**Comment by desht** [comment]
Not sure what's up with your server then, since I've tested on both integrated and dedicated server and have no such problems.  Any messages in your server log?

**Comment by desht** [comment]
BTW, that's not a fresh install with only PNC.  I can see Optifine in there.  Please test without it; I won't deal with any problems where Optifine is in the instance.

**Comment by OliverWolf621** [comment]
> BTW, that's not a fresh install with only PNC. I can see Optifine in there. Please test without it; I won't deal with any problems where Optifine is in the instance.

![2023-08-21_04 45 17](https://github.com/TeamPneumatic/pnc-repressurized/assets/142481537/c5e0759c-ac90-424c-ba46-0e5067a55e3b)
Screenshot from fresh install

**Comment by OliverWolf621** [comment]
> Not sure what's up with your server then, since I've tested on both integrated and dedicated server and have no such problems. Any messages in your server log?

Nothing helpful in the latest or debug log file, the game never outright crashes
Also of note, using an autoclicker or macro to click quickly makes pulling this off 100x easier
Also of note, the game itself doesn't lag or freeze, only the server does. So you can walk around fine, but mobs entities cannot move or be interacted with, and chunks wont load.

**Comment by dovisutu** [comment]
Apparently this owes to performance issues for vanilla servers managing player speed, as I've seen an instance where *in vanilla game* a collision near the center of an Ender Dragon results in extreme velocities (as the speed gain is proportional to the *inverse* of distance from collision "center"), causing the server to lag forever.
~(Not quite able to reference that video though, as I apparently lost the Youtube link to it.)~

---

EDIT: Do managed to find that one; https://www.youtube.com/watch?v=DBYgB2sESmM if not mistaken

**Comment by OliverWolf621** [comment]
Issue was fixed quite a while ago, so I'm marking as closed! (I forgot)
