### ISSUE TITLE
Placement of the Regulator tube module

### ISSUE THREAD

**Issue by X3R0-FR** [TeamPneumatic/pnc-repressurized#1207]
### Describe the bug

When a regulator is fitted, it is not positioned in the correct orientation and changes the orientation of the tube, cutting off the circuit and allowing the air to escape.

### How to reproduce the bug

Install a pressure regulator on a tube

### Expected behavior

The regulator is placed in the continuity of the tube

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.4

**Comment by desht** [comment]
Not a bug.  Regulator modules are inline, and can only be placed on the open end of a tube.
