### ISSUE TITLE
Omnihopper placed with upgrade inside needs an "update" for upgrades to work

### ISSUE THREAD

**Issue by Soycakes** [TeamPneumatic/pnc-repressurized#1209]
### Describe the bug

1. Omnihopper with upgrades inside (ex. Speed upgrade) that is broken and replaced will act as if no upgrade is inside, until the the hopper is "updated" by having an upgrade put in or pulled out.

2. Omnihopper with Entity Tracker  placed sideways still will only pull from entities above the omnihopper as if it's placed with pull side facing up (but will still properly pull armors from Entities)

### How to reproduce the bug

for 1.
Place Omni hopper
Put in speed upgrades
Break the Omnihopper

Place the omnihopper as desired for items to flow through, you should see items slowly passing through as if no upgrade is inside.
Either Put in any upgrade, Pull out any upgrade so the hopper updates itself for whatever upgrade is inside for it to work using upgrade again.

for 2.
Place an omnihopper sideways, and put in entity tracker upgrade
Standing on the side of omnihopper with armor on will not pull the armor
Standing on top of the sideway omnihopper with pull the armor

### Expected behavior

for 1.
When placing an omnihopper that has been broken with upgrades held inside, it should properly be updated when placed again so upgrades are properly used again without them having to be updated again

for 2.
Sideway omnihopper should pull from entity side way (unless if this was intended?)

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.3.7

**Comment by desht** [comment]
Fixed in current release
