### ISSUE TITLE
Block atlas config stitches all entity textures to the block atlas

### ISSUE THREAD

**Issue by XFactHD** [TeamPneumatic/pnc-repressurized#1212]
### Describe the bug

The [block atlas config](https://github.com/TeamPneumatic/pnc-repressurized/blob/1.20.1/src/main/resources/assets/minecraft/atlases/blocks.json) in PNC stitches all entity textures to the block atlas. This is due to how the `DirectorySource` scans the specified source path in all packs regardless of the namespace. In a mostly vanilla environment this is merely an annoyance but in larger packs this significantly bloats the block atlas (i.e. in ATM9 it leads to the block atlas going from 8k x 8k with about 53% filled to 16k x 8k with about the same percentage due to other mods adding significant amounts of entities)

### How to reproduce the bug

Load into the game and either export the atlas for inspection via `F3 + S` or use a mod like [AtlasViewer](https://www.curseforge.com/minecraft/mc-mods/atlasviewer) to inspect the atlas in-game.

### Expected behavior

PNC should only add the entity textures it really needs, ideally through individual `SingleFile` sources. Forge provides a data generator for atlas configs (`SpriteSourceProvider`) to make this easier.

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.4

**Comment by desht** [comment]
Good catch, thanks.  Really, only the drone entity textures need to be in the block atlas (for use by drones in item form).

**Comment by XFactHD** [comment]
On further inspection I just noticed that this also applies to the `textures/model/` directory, a significant amount of mods seem to also use folders with that name. If the amount of textures is as small as in the case of the `textures/entity/` directory, then the same `SingleFile` treatment would be nice there as well. If all your textures from that directory should be stitched, then another option would be to namespace the directory, either by prepending it with some abbreviation (i.e. `textures/pnc_model/`) or by placing it in a namespace directory (i.e. `textures/pneumaticcraft/model`).

**Comment by desht** [comment]
The `model/` directory is not small, no, and those textures are pretty much all used for block & item models.  So yeah I can namespace that directory.

**Comment by desht** [comment]
Fixed in latest release
