### ISSUE TITLE
Copper block to 9 copper ingots recipe blocked 

### ISSUE THREAD

**Issue by raalpe** [TeamPneumatic/pnc-repressurized#1213]
### Describe the bug

When Pneumaticraft-repressurized is installed it is not possible to craft 9 ingots from a copper block.

### How to reproduce the bug

Clean install of minecraft with pneumaticraft as the only mod installed through curse forge:
craft a copper_block
put the copper_block in the crafting table recipe do not appear.

### Expected behavior

9 copper_ingots as output of crafting

### Additional details

also tested in pneumaticcraft-repressurized-6.0.0

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-6.0.4

**Comment by desht** [comment]
Oops, you're right.  Mistakenly overwrote the vanilla block->ingot recipe with my nugget->ingot recipe, sorry.

**Comment by raalpe** [comment]
No worries, thank you very much for your work 😄.
