### ISSUE TITLE
Function+F3 plays Minigun shutdown sound

### ISSUE THREAD

**Issue by starryfae** [TeamPneumatic/pnc-repressurized#1215]
### Describe the bug

Have a Kinesis keyboard, use fn+f3 to change volume, VERY loud minigun noise plays.

### How to reproduce the bug

use fn+f3 to change volume

### Expected behavior

Not to make any noise when key combo is pressed

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-6.0.5+mc1.20.1.jar

### Workaround?

Used Extreme Sound Muffler to stop the sound event for now

**Comment by desht** [comment]
Umm... no idea?

I don't have a Kinesis keyboard, but my keyboard (Roccat Ryos Mk Pro) does allow volume control via Fn + F3 (raise the volume).  And it works as I would expect.

Can you run some kind of key event debugger and find out exactly what your keyboard is sending when you press that key combo?

Also, what PNC items, if any, do you have equipped or in your inventory when this happens?

One other thing, can you paste me a copy of your `options.txt` file, in particular I need to see what your current keybindings are.

**Comment by starryfae** [comment]
Hello, this was in the ATM 9 modpack as well, so that probably complicates...everything. It was upon starting a new world with no Pneumaticcraft progress.
[options.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/12576984/options.txt)
![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/73800917/612021ba-592b-43ad-977f-532256c78a11)

**Comment by desht** [comment]
No PNC keys bound for any armor upgrade modules, then.  I honestly have no clue what's triggering that...

But yeah ATM9  does weird things to just about everything, in my experience.

**Comment by starryfae** [comment]
At least we have a workaround for anyone else experiencing the issue, thanks for your help!

**Comment by desht** [comment]
Release 6.0.7 should fix this (see also #1218)
