### ISSUE TITLE
Crash 1.12.2 (com.google.gson.JsonPrimitive cannot be cast to com.google.gson.JsonObject)

### ISSUE THREAD

**Issue by DaggerTM** [TeamPneumatic/pnc-repressurized#122]
### Minecraft Version
 1.12.2
### Forge Version
14.23.2.2615
### Mod Version
1.12.2-0.4.1-142
### Describe your problem, including steps to reproduce it
Don't know, crash started after my modpack was published to curse... didn't happen while i was testing for issues....
### Any other comments?
Crash:
https://pastebin.com/95gNLe3p

**Comment by desht** [comment]
Looks like one of the .json files in your ``config/pneumaticcraft`` folder is corrupt.

I've added a change to log an error (including the exact file where the error occurred) and continue if this happens; can you try build 149 from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ and see what you get?

**Comment by desht** [comment]
Closing due to lack of response.  Issue should be resolved in build 149 (better error logging in case of invalid JSON)
