### ISSUE TITLE
Harvesting Drone does not harvest Bamboo

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#1221]
### Describe the bug

When placed in a Bamboo farm, the Harvester Drone does not harvest bamboo. 

I have ensured the harvester drone has a hoe, is deployed in the center, I've also ensured that the crop has *fully* grown, I've also tried deploying the drone before the bamboo grows (when it is still in its sapling stage) vs deploying it afterwards (when its in its post-sapling baby bamboo stage), but the drone just remains idle.

### How to reproduce the bug

Typical harvester drone setup but with bamboo.

### Expected behavior

The drone shouldn't sit idle, it should collect bamboo

### Additional details

I am aware that support for this was recently added to the mod because I did a search on bamboo in the issues & code before posting this bug report. 

I noticed that the code does a call to a method called `isCactusLike` which just returns a block type like cactus, sugar cane, etc, which I'm *assuming* gets mapped to a routine that handles harvesting crops which behave like cactus. The thing is that bamboo doesn't behave *exactly* like cactus. There's a stage where it exists in sapling form: 

![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/70091260/7ffceacb-9567-4480-9d97-184eeff52956)

It only starts behaving like a cactus after this stage has progressed:

![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/70091260/2551533a-1871-4e71-a8fc-b20be3ed5485)

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.7

**Comment by johalun** [comment]
Just for a data point, in 1.19.2-4.3.7-30, I know this worked for me since a harvest drone did harvest bamboo that I'd planted for decoration so I had to program one with custom area.

**Comment by desht** [comment]
Looking at the two code branches, I think this could be as simple as a feature that got added to 1.19 but never got forward-ported to 1.20...

**Comment by desht** [comment]
Fixed in current release
