### ISSUE TITLE
Reinforced Air Canister does not have an entry in the manual

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#1222]
### Describe the bug

I consider this a bug, as there is an entry for the basic Air Canister, but not one for the Reinforced Air Canister.

### How to reproduce the bug

Try to find an entry for the Reinforced Air Canister in the manual.

### Expected behavior

The manual should have an entry for the Reinforced Air Canister, and, like the entry for the basic Air Canister, it should also explicitly list the base volume of the air canister.

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.7

**Comment by desht** [comment]
Fixed in 6.0.11 & 4.3.10
