### ISSUE TITLE
Drone stuck indefinitely on open trapdoors/doors

### ISSUE THREAD

**Issue by johalun** [TeamPneumatic/pnc-repressurized#1224]
### Describe the bug

The drone get stuck when trying to get through an open door. Specifically a Create mod glass door in this case. I've also seen this behavior for trapdors. If the door is closed, the drone will teleport.

### How to reproduce the bug

Simply force the drone  to pass through an open door to get to its destination

### Expected behavior

The drone to either pass through the open door, or teleport if get stuck

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4,.3.7

**Comment by desht** [comment]
Can you do a test for me with a vanilla entity, say a cow:

* Set the door up in a wall that the cow can walk around if needed
* Put the cow on one side of the door
* Stand on the other side and tempt the cow with some wheat
* Does the cow walk around the wall to get to you, or try to path through the door and get stuck?

**Comment by desht** [comment]
Actually never mind, I set up a test myself.  As I thought, the cow does indeed try to get through the open door, and gets stuck.  Which means it's a bug in the way the Create blocks are reporting their pathfindability.

This needs to be reported to the Create authors; the problem they need to fix is that the doors (and I expect trapdoors) must either override the `isPathfindable()` method to return false, or not have a motion-blocking collision box when they're open.

**Comment by desht** [comment]
Actually, don't raise any tickets against Create - they do seem to be doing the right thing with their doors.

And in my testing, drones don't get stuck indefinitely on Create doors - they do teleport if they can't get past one, just the same as for vanilla doors (which other entities also can't get through).

**Comment by johalun** [comment]
Hmm, that's odd. I have a green house with a glass door and the drone couldn't get out to deposit the crops outside of the green house. I had to remove the door.
