### ISSUE TITLE
Aerial interface singificantly lags the game

### ISSUE THREAD

**Issue by AlexiyOrlov** [TeamPneumatic/pnc-repressurized#1226]
### Describe the bug

Aerial interface contributes a lot to the tick lag. I noticed it when entities started pausing their movement every second

### How to reproduce the bug

In my case, I was using the interface to extract specific items from the player's inventory via Item Importer from Integrated Dynamics

### Expected behavior

It doesn't add noticeable lag

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

v6.0.5+mc1.20.1

### Crash log

https://spark.lucko.me/FV8c66RiDE

**Comment by desht** [comment]
This Spark trace shows the CPU usage is happening in Integrated Tunnels, not PneumaticCraft.  What makes you think the Aerial Interface is involved here?

Update: OK, I see the Aerial Interface in the tree further down.  But it's not the Aerial Interface itself here, it's the operation of copying some item with probably large NBT.  And iirc Integrated Tunnels can run very frequently, which could be happening in this case.  The Aerial Interface isn't actually doing much here itself, other than making the player's inventory look like any other inventory to the Integrated Tunnels writer, so I don't think there's much I can do about this.

**Comment by AlexiyOrlov** [comment]
You should press on the 'Mods' tab and it will show breakdown by mod, pneumaticcraft will be one of the top.

**Comment by desht** [comment]
See the update to my previous comment.

**Comment by johalun** [comment]
Integrated Dynamics and friends often defaults to 1 tick per operation which can be excessive. See if raising that value helps. There's config screen in the UI for each ID item.
