### ISSUE TITLE
Add a config option for oil rarity.

### ISSUE THREAD

**Issue by Puppyguarb** [TeamPneumatic/pnc-repressurized#1227]
### Describe the feature

Simply change the standard spawn rate of oil lakes to be tied to a config file rather than hard-coded to 25 and 6.

### Reasons why it should be considered

It is rather annoying to see hundreds of oil lakes on the map, it would be nice to have a way to decrease the rarity without completely blacklisting them from the overworld.

**Comment by desht** [comment]
Already configurable.  These are data packs, after all.  See https://github.com/TeamPneumatic/pnc-repressurized/wiki/Worldgen-1.19
