### ISSUE TITLE
Mod update is falsely reported in 1.18.2

### ISSUE THREAD

**Issue by CSdiscoveries** [TeamPneumatic/pnc-repressurized#1229]
### Describe the bug

Forge's built-in "Update checker" for certain mods shows an update available for this mod. Going to either the curseforge page or the github releases page shows there is no available update. This is not the first time something like this has happened, though if I recall it was 1.16.5 which had this issue previously.

### How to reproduce the bug

1. launch the game with the mod installed
2. see green flashing "update" icon

### Expected behavior

From what I understand, this is some kind of issue on github's side. I could be misremembering from my previous report though.

### Which Minecraft version are you using?

1.18 - critical bugs only

### Which version of PneumaticCraft: Repressurized are you using?

1.18.2-3.6.1-29

**Comment by desht** [comment]
I think there some issue with CF approving the 3.6.2 release.  In any case, I'm going to do a 3.6.3 release so that will sort that out.

**Comment by desht** [comment]
3.6.3 is available now.
