### ISSUE TITLE
Crash on placing basic pipe

### ISSUE THREAD

**Issue by SatyrRex** [TeamPneumatic/pnc-repressurized#123]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2

### Forge Version
14.23.2.2611

### Mod Version
1.12.2-0.4.1-142

### Describe your problem, including steps to reproduce it
On a multiplayer server, placing a basic pipe corrupted the chunk (it was backed up 20m before, so luck on that one.) and in both single player and multiplayer, it crashes the client.

https://pastebin.com/yH1U3t4i

### Any other comments?

zip for custom mod pack on Twitch: https://goo.gl/UNW275

**Comment by desht** [comment]
Did you enable Mcmp2 in the mod config? It's disabled by default for a reason (it doesn't work)...

**Comment by SatyrRex** [comment]
I don't even see that option in the configs. Which file is it in?
