### ISSUE TITLE
Add a creative ammo box for the turrets

### ISSUE THREAD

**Issue by moninformateur** [TeamPneumatic/pnc-repressurized#1231]
### Describe the feature

This ammo box will enable turrets to have unlimited ammo. This can be useful on servers to create a safe OP area. The box should take the textures that exist already, but with a glint.

### Reasons why it should be considered

It probably shouldn't be hard to code. Doesn't require new textures.

**Comment by desht** [comment]
Rather than adding a new ammo type, it would be a lot simpler just to allow the Turret to take a Creative Supply Upgrade.  That also means any existing ammo can be used.

**Comment by desht** [comment]
Added in 6.0.11 (using the Creative Supply Upgrade).  Also supported by drones & the Minigun.
