### ISSUE TITLE
[1.18.2] Guard Drone not worked properly

### ISSUE THREAD

**Issue by SnowBerryZ** [TeamPneumatic/pnc-repressurized#1235]
### Describe the bug

The Guard Drone worked only with the Diamond Sword and not with the Minigun Upgrade...
Then she going not properly back to her Chest Place...
And i mean, the coolant System from Air Compressor are not worked properly...
(I'm so sorry my Englisch is not the best but im French/German)

### How to reproduce the bug

Install the Minecraft Version 1.18.2 with the Forge Version 40.2.10 and launch the Game only with this MOD in Single Player..
So other Conflicts are excluded.

### Expected behavior

The Game is worked properly, only they Functions are broken :[

### Additional details

No Game-Crash or so ...

### Which Minecraft version are you using?

1.18 - critical bugs only

### Which version of PneumaticCraft: Repressurized are you using?

3.6.1 (Yesterday) & 3.6.3 (Today)

**Comment by HipHopHuman** [comment]
> The Guard Drone worked only with the Diamond Sword and not with the Minigun Upgrade...

Did you make sure the drone had enough ammunition? When given a minigun upgrade, it also needs a supply of minigun ammo (which it'll check for in the chest it was deployed on).

> Then she going not properly back to her Chest Place...

That could easily happen if the Drone checks to see if it needs ammo, then scans the chest it was deployed on for ammo but doesn't find any.

> And i mean, the coolant System from Air Compressor are not worked properly...

The basic Air and Liquid Compressors don't interact with the Heat system, so there's no need to provide coolant. If you mean the Advanced Compressors, then they need to be cooled. It would help if you could describe your cooling setup (even better if you can provide some screenshots) then it'd be easier to pinpoint the issue.

**Comment by SnowBerryZ** [comment]
> Did you make sure the drone had enough ammunition? When given a minigun upgrade, it also needs a supply of minigun ammo (which it'll check for in the chest it was deployed on).

The  double Chest are Full with Ammo, also this can not are my mistake :[

And the other errors probably come from exactly the same bug, because unfortunately something is not working correctly in the source code.

**Comment by desht** [comment]
Nope, can't reproduce this at all.  Made a guard drone, gave it a Minigun Upgrade, put some Ammo in a double chest, deployed the drone on the chest (be sure to sneak-right-click the drone against the chest), and it worked just fine.  It took the ammo, and it killed any mobs that came near.

> And the other errors probably come from exactly the same bug, because unfortunately something is not working correctly in the source code.

Not likely.  There's no relation between compressors and guard drones.  

> And i mean, the coolant System from Air Compressor are not worked properly...

That's not a proper bug report. Explain exactly what you're trying to do, and exactly what doesn't work.

**Comment by SnowBerryZ** [comment]
Oke thanks @desht for looking the Video ^_^
The Issue is the Minigun in the Chest, but i have see this from many Youtube Videos XD

Now, the only Bug is that she not return to the Chest after killing the Mobs.
And NO Mobs in the near. (You have see in the Video ^^)

**Comment by desht** [comment]
That's not a bug.  Why should the drone need to return to the chest, unless it's out of ammo?

**Comment by SnowBerryZ** [comment]
Aaaaaaah okay i understand ... 
I thought that was their “radius” starting point xD

Thank you so much and have an nice day ^_^

**Comment by desht** [comment]
Just to be clear, the chest is the centre of the drone's operating area, but it will only return there if it needs ammo.  But it will still aggro on any mobs which enter the area.
