### ISSUE TITLE
Custom Blocks with kubjes 

### ISSUE THREAD

**Issue by benbenlaw** [TeamPneumatic/pnc-repressurized#1236]
### Describe the bug

If i make a custom block in kubjes with a custom namespace at the begining eg "mycustommod:hot_block" i cannot add a recipe to that block for heat. if i use the kubejs namespace then the custom heat recipes do work for that block. I looked at the logs and it seems like pneuumaticcraft check to see if a mod is loaded when checking for these recipes so custom name spaces inside kubejs won't work

### How to reproduce the bug

add new blocks in kubejs startup scripts folder

StartupEvents.registry('block', event => {
   
   event.create('desertopolis:hardened_sandstone')
   .hardness(1.0)
   .displayName('Hardened Sandstone')		
   .tagBlock('minecraft:mineable/pickaxe')
   .tagBlock('minecraft:needs_stone_tool')
   .fullBlock(true)
   
   event.create('kubejs:scorching_iron_block')
   .soundType("metal")
   .hardness(1.0)
   .displayName('Scorching Iron Block')		
   .tagBlock('minecraft:mineable/pickaxe')
   .tagBlock('minecraft:needs_stone_tool')
   .fullBlock(true)
   .requiresTool(true)
})

Add custom recipes for heat:

{
    "type": "pneumaticcraft:heat_properties",
    "block": "kubejs:scorching_iron_block",
    "temperature": 1900,
    "thermalResistance": 100,
    "transformCold": {
      "block": "minecraft:iron_block"
    },
    "heatCapacity": 10000
}  

{
    "type": "desertopolis:hardened_sandstone",
    "block": "kubejs:scorching_iron_block",
    "temperature": 1900,
    "thermalResistance": 100,
    "transformCold": {
      "block": "minecraft:sand"
    },
    "heatCapacity": 10000
}

Blocks with Kubejs work, blocks with desertopolis as the namespace do not

### Expected behavior

custom blocks with custom namespace should work

### Additional details

happy to provide any additional information

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-6.0.8+mc1.20.1

### Crash log

n/a

**Comment by desht** [comment]
Yeah, this should be changed to first check if the block exists in the block registry, and only if that fails check if the mod is loaded for error logging purposes.

Should be an easy change, will let you know when there's a dev build to test out.

**Comment by benbenlaw** [comment]
awesome thanks :)

**Comment by desht** [comment]
Can you try out this dev build: https://modmaven.dev/me/desht/pneumaticcraft/pneumaticcraft-repressurized/6.0.9+mc1.20.1-SNAPSHOT/pneumaticcraft-repressurized-6.0.9+mc1.20.1-20231003.165531-2.jar

and let me know if it behaves better?

**Comment by benbenlaw** [comment]
yep this is perfect thanks

**Comment by benbenlaw** [comment]
tested a few blocks and all seem to be good

**Comment by desht** [comment]
Great, will be getting a 6.0.9 release out in the next day or two.

**Comment by benbenlaw** [comment]
awesome thank you

**Comment by desht** [comment]
6.0.9 released now
