### ISSUE TITLE
Ability to void the input tank

### ISSUE THREAD

**Issue by trevorjd** [TeamPneumatic/pnc-repressurized#1238]
### Describe the feature

I'm playing Project Ozone 3 which at 1.12.2, I admit isn't a recent version of PNC-R nor MC!

First time playing with PNC-R so perhaps I'm overlooking something but I went to change inputs for my refinery today from Oil to Crude Oil only to find that there were 9mB of Oil left in the refinery.

I couldn't find any way to drain the input tank.  No void button like Mekanism has.  Mek's Gauge Dropper didn't work.    Tried EnderIO conduits and PNC-R's own fluid hopper.  Tried re-crafting in my 2x2, tried shift-right-clicking on air.  Even breaking the block, it retained it's dregs!

### Reasons why it should be considered

I feel this should be self-evident.  Although a new refinery block isn't expensive, in principle it's not ideal to have to replace something because of dregs.

Thanks for the consideration.  I totally understand if you're not interested in backporting but might be worth checking if it's possible in the current releases.

### Additional details

pneumaticcraft-repressurized-1.12.2-0.11.15-398

**Comment by desht** [comment]
That's something I could consider for 1.19/1.20, but there's zero chance of a 1.12 (or even 1.16/1.18) backport, sorry.

**Comment by trevorjd** [comment]
No worries at all.  Thanks for the quick reply.  I'll let you add to your to-do list as you choose.
