### ISSUE TITLE
Pixel/Animation Error

### ISSUE THREAD

**Issue by SikiciBebek** [TeamPneumatic/pnc-repressurized#1241]
### Describe the bug

if u use Chamber glass the air inside the chamber will be outside around the chamber aswell

### How to reproduce the bug

if u use Chamber glass the air inside the chamber will be outside around the chamber aswell

### Expected behavior

if u use Chamber glass the air inside the chamber will be outside around the chamber aswell

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.19.2-4.3.9-39.jar

### Crash log

https://prnt.sc/1gGHy9T8d6b4

**Comment by desht** [comment]
Known problem with Oculus, complain to the author of that mod.

You can disable pressure chamber particles in the client config as a workaround (setting `pressure_chamber_particles` in `pneumaticcraft-client.toml`)

**Comment by SikiciBebek** [comment]
Ty! :D
