### ISSUE TITLE
Config option for drones to be able to be picked up while on "standby" (only while on standby).

### ISSUE THREAD

**Issue by Henrique143** [TeamPneumatic/pnc-repressurized#1242]
### Describe the feature

A configuration option that allows drones to be automatically picked up by Boats/Minecarts/etc. if they're on "standby" mode.

Example: "drones_can_be_picked_up_while_on_standby = true"

Maybe even set to "true" by default?

### Reasons why it should be considered

Sometimes you just have a drone doing condition checks and variables updates and not moving around or doing world actions, so it is on "standby" mode to save pressure.

And since drones on "standby" mode can't move around by themselves, they don't suffer the risk of accidentally colliding with a boat or a minecart.

So by allowing the drone to be picked up while on "standby" it would be able to interact with other entities and blocks and you would still be able to move it around using other means.  All without the risk of accidentally being picked up because of pathfinding.

Also this functionality would increase the drones interactability with other mods.

Like, for example, a drone that is programmed to update its name based on conditions and variables could be picked up by a "seat" (create mod), and have it's name detected by a "display link" (create mod).

**Comment by desht** [comment]
This could be very useful I agree, but I'm not sure a global config option is the way to do it. That could still lead to unwanted drone pickups.

But how about this: add a checkbox to the Standby widget: "Allow Entity Pickup". When true, drones in standby can be picked up; when false, they can't.

**Comment by desht** [comment]
Added in 6.0.11
