### ISSUE TITLE
Entity Tracker: Backspace deletes 2 characters

### ISSUE THREAD

**Issue by Oyu07** [TeamPneumatic/pnc-repressurized#1243]
### Describe the bug

![javaw_NPDQXSuIkm](https://github.com/TeamPneumatic/pnc-repressurized/assets/66401072/da2e4a28-a12a-4655-80ca-1cf81e3d5a7c)

Backspace was only pressed once
Nothing else suffers from this

### How to reproduce the bug

Minecraft 1.16.5
pneumaticcraft-repressurized-1.16.5-2.15.12-13.jar

Equip Entity Tracker upgrade
Type something
Press backspace once

### Expected behavior

For it to not delete 2 characters at once

### Additional details

I have been experiencing this bug for atleast 3 years
Last noticed on Enigmatica 6 modpack 1.16.5

### Which Minecraft version are you using?

1.16 - UNSUPPORTED

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.16.5-2.15.12-13

**Comment by desht** [comment]
Fixed in 6.0.11 & 4.3.10
