### ISSUE TITLE
Missing Description for Item Life upgrades in armor upgrade screen

### ISSUE THREAD

**Issue by x4dr** [TeamPneumatic/pnc-repressurized#1244]
### Describe the bug

When viewing the armor upgrades in the charging station, the description for the Item Life Upgrade is missing (all others seem to be fine)
![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/9962272/d9e42347-cce9-439b-9775-05a33b2b141d)

### How to reproduce the bug

Take Pneumatic Chestplate, put it in a charger (with dispenser upgrade installed) and open its upgrades.
Click to tip for Item Life Upgrade.

### Expected behavior

Upgrade Name, Max Upgrades and Description is shown.

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.9+mc1.20.1 on forge 47.2.1

**Comment by desht** [comment]
Fixed in 6.0.11 & 4.3.10
