### ISSUE TITLE
Oil Lake Generation Filtering by Biome datapack not working

### ISSUE THREAD

**Issue by dr3ams** [TeamPneumatic/pnc-repressurized#1245]
### Describe the bug

Created a datapack in location, decided to tweak oil lake gen
(was loading recipes before and they're working fine)
\config\paxi\datapacks\litiv2-datapack\data\pneumaticcraft\tags\worldgen\biome\has_surface_oil_lakes.json

that contain only:
```
{
  "values": [
    "#minecraft:savanna"
  ]
}
```
And can't find any oil lakes in savanna. This was tested with default world gen, with no added mods.
With my file: (completely no oil lakes, but they should generate only in savanna)
![2023-11-01_09 35 45](https://github.com/TeamPneumatic/pnc-repressurized/assets/7347489/652f0c3d-5a30-428f-afce-1188c9cda492)

Without: (you can see oil lakes, even in savanna biome)
![2023-11-01_09 39 34](https://github.com/TeamPneumatic/pnc-repressurized/assets/7347489/936ec638-e364-43ab-95c3-c00d6a8239fd)

### How to reproduce the bug

Try to create datapack that limits oil lake gen to certain biomes

\config\paxi\datapacks\litiv2-datapack\data\pneumaticcraft\tags\worldgen\biome\has_surface_oil_lakes.json

```
{
  "values": [
    "#minecraft:savanna"
  ]
}
```

### Expected behavior

Oil lakes to generate only in specified biome (savanna)

### Additional details

forge 47.2.1

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.9

**Comment by desht** [comment]
`#savanna` isn't a valid biome tag.  I think you meant to use `#is_savanna` here.

Valid vanilla biome tag list can be found here: https://minecraft.wiki/w/Tag#Biomes
