### ISSUE TITLE
Stacked Bucket of Molten Plastic will not cool in a inventory with a Heat Frame.

### ISSUE THREAD

**Issue by kalutro** [TeamPneumatic/pnc-repressurized#1246]
### Describe the bug

Using an inventory that allows for multiple stacks per slot, Sophisticated Storage barrels with a stack upgrade, for example, will prevent the plastic from cooling. Removing the stack upgrade fixes this as does simply unstacking the buckets manually.

### How to reproduce the bug

Sophisticated Storage barrel with a stack upgrade. I used Netherite and Diamond, respectively. Add multiple buckets of molten plastic, they will stack in a single slot. Watch as the buckets refuse to cool.

### Expected behavior

I would have expected the buckets to cool properly.

### Additional details

This is on Minecraft 1.19.2 using ATM8 1.0.28 and PNC 4.3.8.

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.3.8

**Comment by desht** [comment]
Working as intended, buckets aren't stackable items, and I don't plan to support mods which alter that mechanic, sorry.
