### ISSUE TITLE
rendering error

### ISSUE THREAD

**Issue by 123qwqeq** [TeamPneumatic/pnc-repressurized#1247]
### Describe the bug

![9276309744808f718f3ccd1d30c3a06e280699294](https://github.com/TeamPneumatic/pnc-repressurized/assets/138661199/7891c53c-7701-4de6-bee0-dffd7799fa25)
like this

### How to reproduce the bug

Use 2 pressure display modules for pipelines

### Expected behavior

I want it fixed.

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized v1.19.2-4.3.9

**Comment by desht** [comment]
Oculus bug, complain to them. https://github.com/Asek3/Oculus/issues/340

As a workaround you can right-click the pressure gauges with a pneumatic wrench to switch to a plain text display.
