### ISSUE TITLE
Stacked air canisters consume air pressure, but do not charge from auto-charger

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamPneumatic/pnc-repressurized#1248]
### Describe the bug

If you have stacked (empty) air canisters in your inventory, the Pneumatic Chestplate's Auto Charger will drain all of its air without filling them.

### How to reproduce the bug

1. Obtain a pneumatic chestplate, install auto-charger, and charge it to full
2. Craft multiple air canisters at once, such that they stack together
3. Watch your air pressure tick down to zero, while the stacked canisters don't fill

### Expected behavior

Either no air should be consumed, or the canisters should fill up

### Additional details

This may also happen on the charging station with dispenser upgrade
(I know the canisters don't charge, but haven't checked for air usage)

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.2-4.3.9-39

**Comment by desht** [comment]
Fixed in 6.0.11 & 4.3.10
