### ISSUE TITLE
Fluid order not editable.

### ISSUE THREAD

**Issue by EnotScript** [TeamPneumatic/pnc-repressurized#1250]
### Describe the bug

Min fluid order not clickable or edit. I tried instal only PNCR that not work.  Forge 47.2.1
![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/78641086/b1e6a70b-d77f-42a1-a454-1ce2ac2f06ab)

### How to reproduce the bug

Install mod

### Expected behavior

Editable.

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.10

**Comment by desht** [comment]
Fixed in 6.0.11
