### ISSUE TITLE
Omni Hoppers are unable to pick up items through a carpet

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#1252]
### Describe the bug

Omni hoppers appear to be unable to pick up items through a carpet in contrast to the way a vanilla hopper works. 

### How to reproduce the bug

Place an omni hopper, place a carpet on top, drop an item

### Expected behavior

Items on a carpet over the hopper should still be picked up

### Additional details

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/759#issuecomment-1804272804

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.19.2-4.3.9-39

**Comment by desht** [comment]
Fixed in 4.3.10 and 6.0.11
