### ISSUE TITLE
Modular routers broken

### ISSUE THREAD

**Issue by mattba10** [TeamPneumatic/pnc-repressurized#1255]
### Describe the bug

When using modular router it breaks when block placed within 5 blocks of the top of router. Block can be placed on block 6 and work. See screenshot

### How to reproduce the bug

When using modular router it breaks when block placed within 5 blocks of the top of router. Block can be placed on block 6 and work. See screenshot

### Expected behavior

Should work.

### Additional details

See screenshot

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

Im not

### Crash log

N/A

**Comment by mattba10** [comment]
![2023-11-20_16 47 04](https://github.com/TeamPneumatic/pnc-repressurized/assets/124603841/095fdcbc-a1b0-4b08-88a4-371be50867a0)
![2023-11-20_16 47 08](https://github.com/TeamPneumatic/pnc-repressurized/assets/124603841/a0707235-5a93-4f41-a43c-b564765ead80)
![2023-11-20_16 47 11](https://github.com/TeamPneumatic/pnc-repressurized/assets/124603841/0d0b783c-5df3-42fd-a827-da3cfb6b595c)
![2023-11-20_16 47 01](https://github.com/TeamPneumatic/pnc-repressurized/assets/124603841/cdfeb169-61de-48f5-acda-7ea6d7f7b31b)

**Comment by desht** [comment]
wrong mod
