### ISSUE TITLE
Faster movement in builder mode

### ISSUE THREAD

**Issue by johalun** [TeamPneumatic/pnc-repressurized#1257]
### Describe the feature

Movement speed when in builder mode should be improved with speed upgrades. Possible using the existing "run speed" upgrade and its setting.

### Reasons why it should be considered

Moving around in builder mode is rather slow. It would be great if speed upgrades could make it a bit faster. Not so fast that it replaces non-builder mode, but for example the "run speed" upgrade and its setting could be used to increase also builder mode speed. I think this approach would require minimal change to the code.

**Comment by desht** [comment]
Hmm.  Not convinced, no.  The point of builder mode is for making fine adjustments, when... building.  You get rapid block break speed and the trade-off is slower movement compared with travel mode.

Plus, it's very easy to bind a key to toggle modes when you want a bit more speed.
