### ISSUE TITLE
Server crash from programmable controller

### ISSUE THREAD

**Issue by SatyrRex** [TeamPneumatic/pnc-repressurized#126]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2

### Forge Version
14.23.2.2611

### Mod Version
0.4.1-142

### Describe your problem, including steps to reproduce it
I was using a programming controller, and everything was fine for a few minutes, then this server crash ( https://pastebin.com/XAdeghc4 ) happened. Here's the program I was using https://pastebin.com/WpKMmfjH

**Comment by desht** [comment]
This looks very similar to a problem we had with drones and FTBUtils interaction before - see https://github.com/TeamPneumatic/pnc-repressurized/issues/84.

I'll speculate that the root cause (losing owner information) is likely related, although in this case with the Programmable Controller tile entity, rather than the Drone entity.  I'll take a look...

Had you stopped & restarted the client and/or server between initial deployment and getting the crash?

**Comment by desht** [comment]
Can you try build 156+ from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ and see if it fixes your problem?

5c1531eaf0a7fbad5534b887400927a58ccfb9a1
5c1531eaf0a7fbad5534b887400927a58ccfb9a1

**Comment by desht** [comment]
Just to add: you'll probably need to break and replace the programmable controller block to ensure it stores your player ID.

**Comment by desht** [comment]
This change is in the 0.5.0 release too, BTW.

**Comment by SatyrRex** [comment]
Sorry it took so long, finally got the server updated. It seems to work, though the drone spawned by the controller didn't precisely follow the program. It was supposed to import items then build something. It hovered over to the inventory to import the items, then stayed there, never actually picking up the items.

**Comment by desht** [comment]
Thanks for that, I'll see if I can reproduce that problem.  Did this occur with a freshly-spawned "drone" ?  Also, did you break/replace the controller?

**Comment by SatyrRex** [comment]
Yes, to both questions.

**Comment by desht** [comment]
Bug confirmed.  Looks like the fake drone is trying to insert the atomic disassembler into the programmable controller block rather than its own inventory, which obviously won't work...

**Comment by desht** [comment]
Okay, I've done a bunch of work on the programmable controller (it was one of those blocks that was never well tested after porting), and I'm hoping your problems will be solved.   I tested your dig program and it worked OK with an Atomic Dissassembler.

If you'd like to test, you can use builds 160+ from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ - would appreciate any feedback.

**Comment by desht** [comment]
Haven't heard a response so going to mark this as fixed.  This will be going out in the next release (0.5.1?)
