### ISSUE TITLE
Programmer Breaks Manual

### ISSUE THREAD

**Issue by Khymeira** [TeamPneumatic/pnc-repressurized#1260]
### Describe the bug

The programmer block breaks the manual such that it only opens to last viewed widget with no way back.

### How to reproduce the bug

Open Programmer block UI, middle click on a widget, try to use the manual

### Expected behavior

The manual should open to the normal index/table of contents page.

### Which Minecraft version are you using?

1.18 - critical bugs only

### Which version of PneumaticCraft: Repressurized are you using?

3.6.3-37

**Comment by desht** [comment]
I've seen this occasionally, and as far as I can tell it's a problem with Patchouli that I can't do anything about, sorry.  I just use the Patchouli API as normal, but it sometimes seems to get stuck on a page.
