### ISSUE TITLE
Visual Bug from Pressure Gauge

### ISSUE THREAD

**Issue by DiggityMan420** [TeamPneumatic/pnc-repressurized#1261]
### Describe the bug

Looking at the pressure gauge from certain angles makes a visual glitch bug see screenshoots
this is is in FTB Genesis but i believe it a PneumaticCraft issue ftb has a report too

### How to reproduce the bug

install pressure gauge i added a mod expansion card to it but it happen with or with out the card
walk around
see visual pics

### Expected behavior

no tearing

### Additional details

![Screenshot_2](https://github.com/TeamPneumatic/pnc-repressurized/assets/45196448/c0a644a3-aa5a-4a13-bb3a-624b28032803)
![Screenshot_6](https://github.com/TeamPneumatic/pnc-repressurized/assets/45196448/a9efa121-6216-4d17-88c5-52d805e6a878)
![Screenshot_3](https://github.com/TeamPneumatic/pnc-repressurized/assets/45196448/b76107f8-bf35-4b88-a2c2-82527311581a)
![Screenshot_4](https://github.com/TeamPneumatic/pnc-repressurized/assets/45196448/4ae6f5f4-eeb9-47c4-b7ac-3760099f4c95)
![Screenshot_5](https://github.com/TeamPneumatic/pnc-repressurized/assets/45196448/ec32eb64-4317-438e-b0c5-ff6b3dac0d61)

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.2-4.3.10-42

### Crash log

no log n o crash

**Comment by desht** [comment]
Known bug in Oculus, and the Oculus author isn't interested.

You can work around it by right-clicking the gauge with a pneumatic wrench to put it into text only mode.
