### ISSUE TITLE
PNC:R Manual does not work with Patchouli 1.20.1-83

### ISSUE THREAD

**Issue by GrimmCookie** [TeamPneumatic/pnc-repressurized#1265]
### Describe the bug

The pneumaticraft manual does not properly function when the latest version of patchouli is used.
![2023-12-01_19-46](https://github.com/TeamPneumatic/pnc-repressurized/assets/110426546/dd9ba00f-07c2-437c-b2ea-833ac3c3b8db)

### How to reproduce the bug

Open a PNC:R Manual with Patchouli 1.20.1-83 installed.

### Expected behavior

The manual should open and function as a properly working guide book.

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-6.0.11+mc1.20.1

**Comment by desht** [comment]
Fixed in 6.0.12
