### ISSUE TITLE
Game Crashes When Drone runs 'Dig'

### ISSUE THREAD

**Issue by ReptileSkin** [TeamPneumatic/pnc-repressurized#1269]
### Describe the bug

Single player game crashes when drone attempts to 'dig' a vine while holding shears. Game is unable to load. Was able to recover game by blacklisting dig command in 'ProgrammingPuzzleBlacklist.cfg'

logs?
[crash-2023-12-04_18.59.16-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/13553517/crash-2023-12-04_18.59.16-server.txt)
[crash-2023-12-04_19.01.47-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/13553518/crash-2023-12-04_19.01.47-server.txt)
[crash-2023-12-04_19.04.30-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/13553519/crash-2023-12-04_19.04.30-client.txt)
[crash-2023-12-04_19.07.33-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/13553520/crash-2023-12-04_19.07.33-server.txt)
[crash-2023-12-04_19.11.24-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/13553521/crash-2023-12-04_19.11.24-server.txt)

update, Also occurs when drone is not holding an item and attempts to 'dig' and oak log:

[crash-2023-12-04_20.27.12-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/13553765/crash-2023-12-04_20.27.12-server.txt)

update 3: Crash with sample from guidebook with added store items in inventory on end. Drone grabs axe, flies to oak log, and crashes. Below is program:

[crash-2023-12-04_20.39.53-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/13553893/crash-2023-12-04_20.39.53-server.txt)

![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/60828329/cf0b87fb-d131-4d10-a89a-6bd745fed6cb)

### How to reproduce the bug

Program drone (minus the dig command I removed with the blacklist config):

![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/60828329/0b145095-fd74-4a91-8611-4b0a6ce1b967)

Drone flies to vine block in defined area after acquiring shears from AE interface

Game crash when drone reaches vine block

### Expected behavior

Expect drone to harvest vine block

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-6.0.12+mc1.20.1

### Crash log

https://gist.github.com/ReptileSkin/ad6f829c7470c37f27c0661bc8070277

**Comment by desht** [comment]
There's something very broken with your instance, since the crash is because of a missing Forge event class, which definitely exists in a healthy 1.20.1 Forge instance.  Just tested it with Neoforge 47.1.70, and it works fine.

**Comment by ReptileSkin** [comment]
I updated my forge instance to 47.2.0  and it appears to of fixed the issue. Thanks a lot for helping to get my cobble of a mod pack working!
