### ISSUE TITLE
Stats Screen bug

### ISSUE THREAD

**Issue by ViniciusMakimoto** [TeamPneumatic/pnc-repressurized#1272]
### Describe the bug

After add the Jet Boots upgrade a new Stat screen have appeared, I moved it to the right corner of my screen making it basically invisible. But when I open my world today, the Stat screen slowly increased to the left until takes the entire botton of my screen.

<img width="960" alt="Sem título" src="https://github.com/TeamPneumatic/pnc-repressurized/assets/146846992/602d42b2-1d42-4308-a161-9ad75f59c806">

### How to reproduce the bug

I have add the

### Expected behavior

Move the Stat Screen to the Left Corner

<img width="960" alt="Screenshot_1" src="https://github.com/TeamPneumatic/pnc-repressurized/assets/146846992/c1462f7a-1d03-43f8-bd4b-f7c40d06fd1a">
<img width="960" alt="Screenshot_4" src="https://github.com/TeamPneumatic/pnc-repressurized/assets/146846992/ab88caba-ea03-4146-8e11-3f5909be2ea2">

Close and open the game

https://github.com/TeamPneumatic/pnc-repressurized/assets/146846992/29725a7d-23a2-416a-9788-b620e777387b

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.19.2-4.3.11-43

**Comment by desht** [comment]
Fixed in 1.19 and 1.20 releases
