### ISSUE TITLE
Heat Frame not cooling water

### ISSUE THREAD

**Issue by Ryutso** [TeamPneumatic/pnc-repressurized#1273]
### Describe the bug

Heat Frame, cooled with Ice/Heat Pipe and Vortex Pipe shows "Error" in Jade and does not cool.

### How to reproduce the bug

1. Put Heat Frame on chest
2. Jade shows Error

### Expected behavior

Should show temperature, even if temperature is 0

### Which Minecraft version are you using?

1.18 - critical bugs only

### Which version of PneumaticCraft: Repressurized are you using?

3.6.4-45

**Comment by desht** [comment]
Known issue, and not a critical bug, sorry.
