### ISSUE TITLE
Scuba gear wont turn on

### ISSUE THREAD

**Issue by s4sutler100** [TeamPneumatic/pnc-repressurized#1276]
### Describe the bug

I put on the scuba gear 
i key bind the tank for "end' 
Press end  
tank wont turn on.

### How to reproduce the bug

I put on the scuba gear 
i key bind the tank for "end' 
Press end  
tank wont turn on.turn 

### Expected behavior

turn the tank on

### Additional details

tank to turn on.

[latest.log](https://github.com/TeamPneumatic/pnc-repressurized/files/13782890/latest.log)

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.12

### Crash log

[latest.log](https://github.com/TeamPneumatic/pnc-repressurized/files/13782890/latest.log

**Comment by desht** [comment]
What do you mean by "put on the scuba gear"?  You've installed the scuba upgrade in the pneumatic helmet?

**Comment by s4sutler100** [comment]
> What do you mean by "put on the scuba gear"? You've installed the scuba upgrade in the pneumatic helmet?

I was looking at rhe wrong mod sorry. Thanks for your time.

**Comment by s4sutler100** [comment]
thank you for your time i realized i have called support for the wrong mod
