### ISSUE TITLE
Dupe interaction

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#1277]
### Describe the bug

Starbuncles from Ars Nouveau (with Starbuncle Mania addon) are able to extract fluids from the input side of a TPP. When they do so, the TPP's input tank doesn't actually go down, allowing them to dupe whatever fluid is in the input tank. 

### How to reproduce the bug

Install PNC, Ars Nouveau, and Starbuncle Mania
Place a TPP and put some fluid in. doesn't matter what
Configure a starbuncle to pull from the TPP and send to any form of tank.

### Expected behavior

If the starbuncle pulls fluid out, the level should go down appropriately

### Additional details

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/812

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.3.12-46

**Comment by desht** [comment]
Bug in Starbuncle mania, as described in the linked issue.
