### ISSUE TITLE
Immersive engineering mod conflict

### ISSUE THREAD

**Issue by Adiosospl** [TeamPneumatic/pnc-repressurized#1282]
# Solved

## Edit: both worked when I saw that newer wersion of PneumaticCraft was available on Curse Forge - Modrinth newest download is outdated

--------------------------------

### Describe the bug

**Mod conflict: immersive engineering and PneumaticCraft**

**------------**

_PneumaticCraft_ without _Immersive engineering_ works

_Immersive engineering_ without _PneumaticCraft_ works

### How to reproduce the bug

1. Install Immersive Enigineering mod for forge 1.20.1
2. Install PneumaticCraft: Repressurized mod for forge 1.20.1
3. Run minecraft

### Expected behavior

After loading a world it will crash after 1-5 minutes

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.0

### Crash log

https://pastebin.pl/view/a482087e

**Comment by desht** [comment]
Your version of PNC is ridiculously outdated.  Install the latest.

Update: where is Modrinth showing you that 6.0.0 is latest?  I don't see that anywhere. Going to PNC and then the Versions tab shows 6.0.13 (for 1.20.1) at the top currently.
