### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by mxnmnm** [TeamPneumatic/pnc-repressurized#1289]
### Describe the bug

I tried to log on my server and the server crashed

### How to reproduce the bug

1. Try to summon a collector drone using commands on a server (haven't tried singleplayer)
2. Get an error in chat
3. Shutdown server
4. Say bye bye to your world

### Expected behavior

no crash

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.13

### Crash log

https://gist.github.com/mxnmnm/7ec05a5ddd94af45019b13f94042bb21

**Comment by desht** [comment]
I'll add a fix for the crash, but trying to summon a drone in via commands isn't supported and will never work correctly.  So don't do that.

**Comment by desht** [comment]
Will be fixed in next release, but this dev build should get your world loaded again: https://modmaven.dev/me/desht/pneumaticcraft/pneumaticcraft-repressurized/6.0.14+mc1.20.1-SNAPSHOT/pneumaticcraft-repressurized-6.0.14+mc1.20.1-20240217.133851-3.jar

**Comment by mxnmnm** [comment]
tyty
