### ISSUE TITLE
Drone EntityAttack Bats

### ISSUE THREAD

**Issue by GeMine1** [TeamPneumatic/pnc-repressurized#129]
I use PneumaticCraft-1.7.10-1.12.7-150-universal.jar in Minecraft 1.7.10 (other mods aren't available later) and wanted to create drones, which kill bats. I read that since PneumaticCraft-1.7.10-1.11.2-122-universal.jar you added this feature. So what Text-Tag should I use (like @mob) in order to kill those?

I tried @mob and @animal, but I don't know all the Tags I could use.

**Comment by desht** [comment]
First off, the 1.7.10 version is no longer supported; this is for the 1.12.2 version (PneumaticCraft: Repressurized) only.

Having said that, the syntax for selecting entity types hasn't changed, and @mob and @animal still both work.  If you refer to the code here: https://github.com/TeamPneumatic/pnc-repressurized/blob/master/src/main/java/me/desht/pneumaticcraft/common/util/PneumaticCraftUtils.java#L663-L680

...you will see all the special @ strings that are accepted.  

Also, if the entity is named (e.g. any player, or any entity which has been named with a name tag, or any drone which has been named via the programmer), you can also use the entity's name to filter by.
