### ISSUE TITLE
Fluid Duplication

### ISSUE THREAD

**Issue by sharkweekthings** [TeamPneumatic/pnc-repressurized#1290]
### Describe the bug

This is an issue with pneumaticcraft-repressurized-1.19.2-4.3.14-49 and supplementaries-1.19.2-2.4.20.

When using this simple setup:
![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/134178249/bdea5798-25f3-4576-802f-c819829144cb)

Any fluids in the left side:
![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/134178249/161d887b-7ed7-4f27-8070-fa34fe69e013)

Will duplicate when poured into a tank using a Supplementaries faucet. 

I dont think this is a problem with the faucet itself, but I can report it on their git as well? I figured this was a better place to start. 

### How to reproduce the bug

using an air compressor, thermopneumatic processing plant, 2 tanks, and a faucet.

### Expected behavior

fluid should properly be consumed from the processing plant and placed into the tank. 

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

 pneumaticcraft-repressurized-1.19.2-4.3.14-49

**Comment by desht** [comment]
This is _absolutely_ a problem with the Faucet, which is misusing the forge IFluidHandler API.  The faucet is extracting an arbitrary tank from the fluid handler it gets and extracting from that.  The arbitrary tank is picks is tank 0, the input tank.

The correct way to do this is to call `drain()` directly on the fluid handler itself, __not__ mess about with the tank internals.

**Comment by sharkweekthings** [comment]
<3 I'll report it over to Supplementaries!
