### ISSUE TITLE
The id for Memory Essence so I can use it with Cognitive/Experience Obelisk

### ISSUE THREAD

**Issue by LunarAnticGitHub** [TeamPneumatic/pnc-repressurized#1294]
### Describe the feature

When i go into the common config for Cognitive, I am first met with this:

["Allowed Experience Fluids"]
	#Add IDs of fluids you want the obelisk to support here in the form mod_id:fluid_name. Fluids have to be tagged forge:experience.
	AllowedFluids = ["mob_grinding_utils:fluid_xp", "cofh_core:experience", "industrialforegoing:essence", "sophisticatedcore:xp_still", "enderio:xp_juice"]

What is Memory Essence's mod id so i can add it to the compat list?

Also why can't i join the discord, the link says it'll put up on my application, but it never happens

### Reasons why it should be considered

I just need an ID

### Additional details

Cognitive for 1.19.2
Pneumacraft Reloaded also for 1.19.2

**Comment by desht** [comment]
`pneumaticcraft:memory_essence`

> Also why can't i join the discord, the link says it'll put up on my application, but it never happens

No idea, sorry. The link is good (people are joining all the time).
