### ISSUE TITLE
Rendering errors may occur when using the Pressure Gauge Tube Module with Oculus

### ISSUE THREAD

**Issue by 123qwqeq** [TeamPneumatic/pnc-repressurized#1295]
### Describe the bug

Same as the title
Oculus will cause rendering errors in the Pressure Gauge Tube Module

### How to reproduce the bug

Use and place two or more Pressure Gauge Tube Modules with Oculus in the game
Add a shader at will

### Expected behavior

Two dials may have the same connection scene

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-6.0.14+mc1.20.1.jar

**Comment by desht** [comment]
#1261
