### ISSUE TITLE
Unmodifiable initial Emit Redstone Widget signal

### ISSUE THREAD

**Issue by Cycro54** [TeamPneumatic/pnc-repressurized#1297]
### Describe the bug

When using the [Emit Redstone] widget near something that accepts a Redstone signal it will cause those blocks to be affected.

When trying to emit a different Redstone signal later on, those same blocks will not change their current Redstone power level to match the drones Redstone signal unless a block nearby gets destroyed.

### How to reproduce the bug

Program drone with [Emit Redstone] widget with a power of 15 and a [Wait] widget with 1 second, then put another [Emit Redstone] widget with a power of 0 and another [Wait] widget with 1 second again.

place the drone near something that accepts a redstone signal (like redstone). 

### Expected behavior

I expect the Redstone level of all the affectable blocks near the drone to change when another Redstone signal is emitted by the drone

### Additional details

I tested this in a clean modpack (only had pneumatic craft)

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.3.14-49

**Comment by desht** [comment]
Fixed in 6.0.15
