### ISSUE TITLE
Recipe generation error for pneumaticcraft:radiation_shield_mekanism

### ISSUE THREAD

**Issue by afzalarsalan** [TeamPneumatic/pnc-repressurized#1298]
### Describe the bug

When loading PneumaticCraft with Mekanism on the same server, the Minecraft RecipeManager is unable to pase the recipe for the radiation shield with PneumaticCraft armor. I've provided a snippet of the error message below. From my understanding, the components of this recipe still exist so the "Item array cannot be empty" error doesn't make sense.

### How to reproduce the bug

Load Minecraft 1.20.1 with Neoforge 47.1.101 along with PneumaticCraft 6.0.14 and Mekanism 10.4.6

### Expected behavior

The recipe should generate successfully and not produce an error message

### Additional details

[main/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe pneumaticcraft:radiation_shield_mekanism
com.google.gson.JsonSyntaxException: Item array cannot be empty, at least one item must be defined

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.14

### Crash log

https://gist.github.com/afzalarsalan/3726166fcdb0a78eb068fcf692aaed3c

**Comment by desht** [comment]
Fixed in 6.0.15
