### ISSUE TITLE
Range Upgrade keeps reach distance after taking off a chestplate

### ISSUE THREAD

**Issue by andriihorpenko** [TeamPneumatic/pnc-repressurized#1301]
### Describe the bug

After taking off a Pneumatic Chestplate with a Rage Upgrade installed, the extended reach distance keeps affecting a player until they quit and enter the world again.

https://github.com/TeamPneumatic/pnc-repressurized/assets/13716167/89761aaa-dc92-4e38-bb6a-32dd6dbe7ed8

### How to reproduce the bug

1. Install a Range Upgrade in a Pneumatic Chestplate and activate it
2. Take off a Pneumatic Chestplate

The reach distance modifier remains the same.
Quit and enter the game to have this effect cleared.

### Expected behavior

Purge reach distance modifier after taking off a Chestplate.

### Additional details

This bug was tested on 1.20.1 and 1.19.2 versions. Both have it.

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

6.0.14

**Comment by desht** [comment]
Fixed in 6.0.15 release
