### ISSUE TITLE
1.20.4 neoforge, server crash

### ISSUE THREAD

**Issue by Saereth** [TeamPneumatic/pnc-repressurized#1302]
### Describe the bug

Player said the crash triggered when they placed a pressure chamber valve

### How to reproduce the bug

Not sure, play on a server I believe with modular routers and PNC and place a pressure chamber valve while a modular router is down (not sure if this is relevant at all, its just the scenario they explained to me)

### Expected behavior

No server crash

### Additional details

(Your template doesnt let me pick mc 1.20.4 but thats what its on)

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-7.0.0+mc1.20.4-20240425.212832-2.jar

### Crash log

https://mclo.gs/zd5qT8u

**Comment by desht** [comment]
Possibly fixed by 78d42e984144c4c67322b22837b41820365f97f9 ?

Will leave this open for now, please update if/when you hear more from the reporter.

**Comment by desht** [comment]
Fixed as far as I know
