### ISSUE TITLE
Crash on /reload Command from Smooth Plastic Brick Block

### ISSUE THREAD

**Issue by SpCoGov** [TeamPneumatic/pnc-repressurized#1303]
### Describe the bug

When standing on Smooth Plastic Brick blocks, attempting to use the /reload command causes the game to crash.

### How to reproduce the bug

1. Place Smooth Plastic Brick blocks in the game.
2. Stand on top of the smooth plastic bricks and move.
3. Execute the `/reload` command in the game.

### Expected behavior

Players should be able to safely use the /reload command while standing on Smooth Plastic Brick blocks without crashing the game.

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.19.2-4.3.15-52

### Crash log

https://gist.github.com/SpCoGov/9b648f6f9f33586b277ff6bff03fb29b

**Comment by desht** [comment]
There's absolutely nothing in the stacktrace to indicate the PNC is at fault here, and the crash does not happen in any of my test worlds. So it's pretty much certain to be another mod at fault here, sorry.

**Comment by SpCoGov** [comment]
> There's absolutely nothing in the stacktrace to indicate the PNC is at fault here, and the crash does not happen in any of my test worlds. So it's pretty much certain to be another mod at fault here, sorry.

After my investigation, I found that the problem was caused by at least 3 mods. I really can't point out which other mod caused the entire problem.
