### ISSUE TITLE
Shulker boxes and PNC chests can be put in one another

### ISSUE THREAD

**Issue by NumanSadik** [TeamPneumatic/pnc-repressurized#1306]
### Describe the bug

You can put smart chests in reinforced chests and both of them could be put in a shulker box on top of that a shulker box that may contain them may also be put inside the pnc chests. 

### How to reproduce the bug

Get a shulker box and put it in a pnc chest
Get a pnc cheest and put it in a shulker

Get a smart chest and put it in a reinforced chest

### Expected behavior

They shouldn't be able to fit one another

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-6.0.15+mc1.20.1

**Comment by desht** [comment]
Fixed in 1.20 & 1.21
