### ISSUE TITLE
 Manual is Missing in Neoforge

### ISSUE THREAD

**Issue by Saereth** [TeamPneumatic/pnc-repressurized#1307]
### Describe the bug

The PNC Manual doesn't show in JEI/Creative tab menu 
Neoforge: 40.0.234 
MC: 1.20.4 
PNC: pneumaticcraft-repressurized-7.0.0+mc1.20.4

This is for an Indev Pack which @desht should have access to if needed. I can also do any more testing if needed. 

### How to reproduce the bug

Make a Neoforge 1.20.4 pack and include patchouli and PNC. Look in the creative tab and JEI and the manual is no where to be found.

### Expected behavior

For the manual to be available. 

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-7.0.0+mc1.20.4

**Comment by desht** [comment]
That's odd, it's fine here (1.20.4 dedicated server):
![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/736831/3814b0e2-8606-4174-b7d2-0ff395d36afe)

Also shows up as expected with EMI+JEI as the recipe mod.

Using pneumaticcraft-repressurized-7.0.0+mc1.20.4.jar and Patchouli-1.20.4-85-NEOFORGE.jar

**Comment by desht** [comment]
Although, for some reason a recipe isn't showing up when I click it in the EMI/JEI display.  Not sure why that's happening, will take a look at that.

**Comment by Saereth** [comment]
confirmed it is showing up now, I suspect some other mod bug that got fixed updating recently. No recipe like you found but thats easy enough to sort, thanks for taking a look!
