### ISSUE TITLE
you forgot to include a method and basic machine to MAKE etching acid

### ISSUE THREAD

**Issue by tails1974seeyounextgame** [TeamPneumatic/pnc-repressurized#1309]
### Describe the bug

you forgot to include a method and basic machine to MAKE etching acid

### How to reproduce the bug

you forgot to include a method and basic machine to MAKE etching acid

### Expected behavior

a basic machine before circuitry that can heat etching acid from bucketable substance

### Additional details

since 2 years ago

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

latest

**Comment by TeamSpen210** [comment]
Etching acid is [made](https://github.com/TeamPneumatic/pnc-repressurized/blob/1.20.1/src/generated/resources/data/pneumaticcraft/recipes/pressure_chamber/etching_acid.json) in the pressure chamber. One bucket of plastic, 2 gunpowder, 2 rotten flesh, 2 spider eyes.

**Comment by desht** [comment]
As @TeamSpen210 pointed out, no I didn't forget.

![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/736831/58eb21db-7417-4638-8b3d-b8064e765f9b)

**Comment by tails1974seeyounextgame** [comment]
https://www.reddit.com/r/feedthebeast/comments/gg9dsh/pncr_manual_for_pneumaticcraft_not_available_as/?rdt=38393
and jei also doesnt list a method for making etching fluid, as it still is now for 6 years
![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/5803466/d39e0a4e-a914-4e9e-92fb-80342c66c8c4)

thanks for the image above tho ill save it to my hardrive.

**Comment by tails1974seeyounextgame** [comment]
![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/5803466/14a74192-8be3-4f79-9ee9-1a63490bba8d)

**Comment by tails1974seeyounextgame** [comment]
as u can see no jei method , the onyly way i ever achieved an amadron despite havving finished 95% of the mod was through random drops, of 3 solid months of gameplay. so if u want to argue about it delete this message and see how far u get lol

**Comment by TeamSpen210** [comment]
Try checking recipes for the bucket, not the fluid itself.

**Comment by tails1974seeyounextgame** [comment]
there no entry previous it simply loops, ever wonder why theres no screenshots of the pcb printing? now u know

    On Saturday, June 8, 2024 at 03:15:26 PM MST, Spencer Brown ***@***.***> wrote:  
 
 


Try checking recipes for the bucket, not the fluid itself.

**Comment by desht** [comment]
Give it a rest, dude.  Your installation is broken, there's nothing wrong with making etching acid or PCB printing.  Otherwise every modpack that included PNC as part of progression "for the last 6 years"  would be broken, and I would have a load of complaints.

Take it to the author of whatever modpack you're using (which you didn't bother to mention in this issue - oh and "latest" isn't a valid mod version btw)

**Comment by tails1974seeyounextgame** [comment]
enough with your retardations its been like that for 2 years across 15 modpacks. updates irrelvant

    On Monday, June 10, 2024 at 12:41:14 AM MST, desht ***@***.***> wrote:  
 
 


Give it a rest, dude. Your installation is broken, there's nothing wrong with making etching acid or PCB printing. Otherwise every modpack that included PNC as part of progression "for the last 6 years" would be broken, and I would have a load of complaints.

**Comment by desht** [comment]
Bye bye.
