### ISSUE TITLE
1.21 - add `c:capturing_not_supported` to blacklist vacuum trap tag

### ISSUE THREAD

**Issue by TelepathicGrunt** [TeamPneumatic/pnc-repressurized#1310]
### Describe the feature

Dont replace the mod-specific tag. Just have it pull from c tag that is now official.
![image](https://github.com/TeamPneumatic/pnc-repressurized/assets/40846040/8bcd0c9f-18df-4d2e-8647-4dd506d02ce6)

### Reasons why it should be considered

better mod compat and less mod-specific tags I need in my mod

**Comment by desht** [comment]
When I finally finish the port to 1.21, I will keep this in mind :+1:

**Comment by desht** [comment]
Not released yet, but `pneumaticcraft:vacuum_trap_blacklisted` now includes `#c:capturing_not_supported` by default.
