### ISSUE TITLE
Dust Recipes Dissappeared 

### ISSUE THREAD

**Issue by ikeroy** [TeamPneumatic/pnc-repressurized#1311]
### Describe the bug

I've been playing the UniversIO modpack with a friend on essential, but when he sent the world file to me, I wasn't able to make iron dust with the pressure chamber anymore. The pressure chamber interface doesn't accept iron at all. This also extends to things like copper and gold.

### How to reproduce the bug

Download a world you didn't start (?)

### Expected behavior

Putting 16 iron/gold/copper vials into the pressure chamber interface via a hopper should output iron/gold/copper dust.

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

1.19.2-4.3.15-52

**Comment by desht** [comment]
Iron dust is not a native PNC recipe, so this is a problem with the modpack.
