### ISSUE TITLE
Lag spikes when vortex tubes meet refinery and barely sustain 100C

### ISSUE THREAD

**Issue by RemyDaBunBun** [TeamPneumatic/pnc-repressurized#1312]
### Describe the bug

The game drops to 20fps at times, only when the vortex tubes keep going from 99C to 100C and back rapidly due to low bar in the system, it generates lag due to the refinery being connected I believe

### How to reproduce the bug

Place hot side of vortex tube on refinery, make a starter pressure system and as you barely reach refinery process temp, lag will occur

### Expected behavior

FPS drops from 75+ to 20 Fps

### Additional details

I am playing on Project Ozone 3: A New Way Forward with 4 added mods; Rustic, Rustic Witchcraft, Bewitchment (Legacy), and Essential Mod.

### Which Minecraft version are you using?

1.12 - UNSUPPORTED

### Which version of PneumaticCraft: Repressurized are you using?

1.12.2-0.11.15-398

**Comment by desht** [comment]
Sounds like you haven't insulated your refinery.

Also: "1.12 - UNSUPPORTED"
