### ISSUE TITLE
Reinforced Chest does not drop contents if broken with less than iron pickaxe

### ISSUE THREAD

**Issue by Zygarde365** [TeamPneumatic/pnc-repressurized#1314]
### Describe the bug

When a reinforced chest is broken with a pickaxe that is worse than iron, the chest does not drop it's contents

### How to reproduce the bug

break reinforced chest in survival mode with pickaxe worse than iron

### Expected behavior

the chest should drop it's contents when broken but not drop itself when broken with weak pickaxe, like the way a dropper works when broken with ones fist

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

4.3.15

**Comment by desht** [comment]
Fixed in 1.20.1.  Issue is not serious enough to warrant a 1.19.2 backport (critical fixes only).
