### ISSUE TITLE
1.20.4 crafting with tanks not working

### ISSUE THREAD

**Issue by Zero-ui9** [TeamPneumatic/pnc-repressurized#1316]
### Describe the bug

Recipes that require a tank, despite appearing in JEI, are not actually craftable.

### How to reproduce the bug

Try to craft anything that requires a fluid tank(refinery controller/thermopneumatic processing plant)

### Expected behavior

.

### Which Minecraft version are you using?

1.20

### Which version of PneumaticCraft: Repressurized are you using?

7.0.1

**Comment by desht** [comment]
Confirmed, problem with the recipe not distinguishing between empty NBT and no NBT at all.

**Comment by desht** [comment]
Fixed in 7.0.2
