### ISSUE TITLE
Server crash when Player joins

### ISSUE THREAD

**Issue by Whitefern** [TeamPneumatic/pnc-repressurized#1317]
### Describe the bug

Server crashes when a play joins. The last time I was on, I tried setting a Drone delivery to an underground drawer storage controller but it never arrived

### How to reproduce the bug

The last time I was on, I tried setting a Drone delivery to an underground drawer storage controller but it never arrived and it behind doors

### Expected behavior

Allow player to join without the server crashing

### Which Minecraft version are you using?

1.19

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-1.19.2-4.3.11-43

### Crash log

https://1drv.ms/u/s!AqiPrhDA8lWrvJshJaYhgCgNAmkiAQ?e=qnbjv7

**Comment by desht** [comment]
Please post your stacktrace to a sit that _doesn't_ require sign-in.

**Comment by Whitefern** [comment]
Hi, the link is an anonymous link to a zip file in a OneDrive location

**Comment by desht** [comment]
The site asks for a login when I try to read it. Please post your stracktrace to a site that doesn't. Last request, issue will be closed otherwise.
