### ISSUE TITLE
Readd seismic sensor configuration

### ISSUE THREAD

**Issue by Mantlecrawler** [TeamPneumatic/pnc-repressurized#1318]
### Describe the feature

#748 added the ablity to configure the fluids the seismic sensor detected via config file, but this was removed at some point and replaced with a hardcoded file (src/generated/resources/data/pneumaticcraft/tags/fluids/seismic_sensor_interesting.json).

### Reasons why it should be considered

 The description for the seismic sensor still eludes to being able to configure it, so that should either be changed or the feature added back.

**Comment by desht** [comment]
That is not a hardcoded file in any way.  It's a fluid tag, and it's configurable via datapack.
