### ISSUE TITLE
refinery

### ISSUE THREAD

**Issue by Demonborn6669** [TeamPneumatic/pnc-repressurized#1320]
### Describe the feature

allow heat pipes to connect to blaze burns with straws so a compact refinery design is possible so that u can pump the desiel back into the blaze burner so it heats the heat pipes and is a endless cycle if it could be done on 1.20.1 amazing thank you

### Reasons why it should be considered

it makes refineries more compact and user friendly

### Additional details

the mod for straws is right here[ ](https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things)

**Comment by desht** [comment]
> the mod for straws is right here

Right where? I don't see it anywhere.

This can be done, but I need to which mod this is from, and the block id and blockstate properties of the blaze burners with straws to create the correct datapack entries.
