### ISSUE TITLE
generators and ender io redstone conduit compat

### ISSUE THREAD

**Issue by Tsumiki129** [TeamPneumatic/pnc-repressurized#1321]
### Describe the feature

is it possible to allow ender IO Redstone conduit to interact with the generators as the fluid conduits interact with the generators

### Reasons why it should be considered

it would give people who play with both more options to control the generator from new locations unable to be done with Redstone dust and more sides to alow more efficient cooling as the ender io conduits can exist and work in one block would make for a nice addition for the 1.20.1 version

**Comment by desht** [comment]
It's up to redstone conduits to emit a vanilla redstone signal for PNC machines to listen to.  If they're not doing that, ask them about it. I have no intention of adding specific support for redstone from other mods.

Also: PNC provides redstone over pressure tubes using Redstone Modules.
