### ISSUE TITLE
Refinery Bug

### ISSUE THREAD

**Issue by cweet01** [TeamPneumatic/pnc-repressurized#1323]
### Describe the bug

Cannot put crude oil into the refinery controller no matter if I use a bucket or a pipe and I have used them all. Had my partner try and he could not get it either on his end.

### How to reproduce the bug

Build the refinery controller with 4 refinery outputs on top. Insulate where you are not putting a heating element and a pipe and get a tank of crude oil and try to pump it in.

### Expected behavior

Nothing will happen. Crude oil will stay in tank.

### Additional details

It is actually for NeoForge 1.21

### Which Minecraft version are you using?

1.20.4

### Which version of PneumaticCraft: Repressurized are you using?

NeoForge 1.21

**Comment by EnotScript** [comment]
![image](https://github.com/user-attachments/assets/f58cfb62-b871-4c6e-8069-0b5f0a021def)
Strange, maybe a mod conflict? Or oil from another mod?  Everything works fine for me even with a bucket.

**Comment by cweet01** [comment]
Strange, I tried everything to get it in the machine. Maybe it is a compatibility issue because it is in a modpack. ATM10  to be exact. Thank you.

**Comment by EnotScript** [comment]
> Странно, я перепробовал все, чтобы получить его в автомате. Возможно, это проблема совместимости, потому что он находится в модпаке. ATM10, если быть точным. Спасибо.

ATM 10 too.

**Comment by desht** [comment]
Can't reproduce this, Refinery is working fine here in dev and on my test server.

**Comment by cweet01** [comment]
It was my fault, I was trying to use crude oil from Modern Industrialization, dummy me. It's working now since I am using the right crude oil for the mod. Apologies and thanks for the help.

**Comment by desht** [comment]
It's probably worth raising an issue with ATM10 (or maybe MI itself, up to the mod author if they want to do that) to get them to add the MI crude oil into the `c:fuels/crude_oil` fluid tag. That would allow the Refinery to accept MI crude oil.
