### ISSUE TITLE
Tags for Armour

### ISSUE THREAD

**Issue by TheBedrockMaster** [TeamPneumatic/pnc-repressurized#1324]
### Describe the feature

Add armour specific tags to the Compressed Iron and Pneumatic Armour sets.

Also if both armour sets had a custom tag like pneumaticcraft:compressed_iron_armor for example that would also be awesome.

### Reasons why it should be considered

This would help with sorting armour together or even specific armour pieces (like boots, helmets etc).

### Additional details

A few examples of what I mean (This is for Forge):
(Some tags would add other tags automatically of course)

Compressed Iron and Pneumatic Boots:
forge:boots
forge:armors
forge:armors/boots

**Comment by desht** [comment]
I can add `pneumaticcraft:compressed_iron_armor` and `pneumaticcraft:pneumatic_armor` in 1.20.1 and 1.21

In 1.21 the tag is `c:armors`, which includes the new vanilla tags `minecraft:head_armor`, chest_armor etc. (which the compressed iron and pneumatic pieces are already in), so there's nothing to be done there.

In 1.20.1 there are `forge:armors/helmets` etc. which I can add the compressed & pneumatic pieces to.

**Comment by desht** [comment]
Added in 1.21, will also be added in next 1.20.1 release

**Comment by TheBedrockMaster** [comment]
Thank you so much! This should come in handing when making quests :)
