### ISSUE TITLE
Just Enough Professions Villager Name

### ISSUE THREAD

**Issue by TheBedrockMaster** [TeamPneumatic/pnc-repressurized#1326]
### Describe the bug

When Just Enough Professions is installed, while looking at the uses for the Charging Station and going to the villagers section, the Mechanic shows it's lang key instead of its actual name, however when looking at the charging station's recipe and going to the villagers section it shows up as normal.

Let me know if this is an issue with JEP instead.

### How to reproduce the bug

Look at the uses for the Charging Station with Just Enough Professions installed.

### Expected behaviour

It coming up with the word Mechanic instead of the lang key.

### Which Minecraft version are you using?

1.20.1

### Which versions?

PneumaticCraft: Repressurized: 6.0.15
Just Enough Professions: 3.0.1

**Comment by desht** [comment]
With JEP installed, I don't see anything at all related to villagers when viewing uses for the Charging Station, i.e. mousing over the Charging Station in JEI and pressing 'U', I see:

![image](https://github.com/user-attachments/assets/3f7adacb-dc37-429a-813c-4ef911bb116c)

And the same for any other vanilla block (e.g. Fletching Table).  So I'm not sure what you actually mean by this.

Viewing recipes for the Charging Station does show the JEP tab as expected, with "mechanic" as the name, which is consistent with JEP's display of all the vanilla villagers.

**Comment by TheBedrockMaster** [comment]
This isn't a problem with pnc, sorry

**Comment by desht** [comment]
OK
