### ISSUE TITLE
1.21 armor enchanting

### ISSUE THREAD

**Issue by EnotScript** [TeamPneumatic/pnc-repressurized#1328]
### Describe the bug

Armor from the mod is not enchanted on the table.

### How to reproduce the bug

Try to enchant across the table.

### Expected behavior

Enchantment

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

6.0.10

**Comment by EnotScript** [comment]
![image](https://github.com/user-attachments/assets/c7c42f6b-ddaf-4e22-9c1d-2feaf09d4148)
![image](https://github.com/user-attachments/assets/3382a49b-303a-4b3d-b409-00a67fa66cca)

**Comment by desht** [comment]
Confirmed, will be fixed in next release.

**Comment by desht** [comment]
Fixed in 8.0.3 release
