### ISSUE TITLE
Remove "Air Conditioning not installed"

### ISSUE THREAD

**Issue by TheBedrockMaster** [TeamPneumatic/pnc-repressurized#1329]
### Describe the feature

Whenever I put on my Pneumatic Chestplate/join the world with it on, it comes up saying:
![image](https://github.com/user-attachments/assets/a3bcf1e6-f9a4-48ad-8119-50d26a95042e)
As I can't see a way of obtaining the Air Conditioning Upgrade it would be nice if that didn't show up.

### Reasons why it should be considered

It's just kind of annoying and it doesn't make sense for it to even be in the game, let alone have it come up every time I join.

**Comment by desht** [comment]
Yeah Air Conditioning upgrade probably should be disabled for now at least. Maybe one day there will integration again for TAN or similar mods.

Note, you can also set the armor to report _only_ the enabled upgrades (or none at all) on startup with a setting on the Core Components page.

**Comment by TheBedrockMaster** [comment]
Thanks, I didn't realise that :)
