### ISSUE TITLE
Pneumatic Armor Upgrades

### ISSUE THREAD

**Issue by Lychosis** [TeamPneumatic/pnc-repressurized#1331]
### Describe the bug

Armor Upgrades in Pneumatic Armor are not adding armor.

### How to reproduce the bug

Crafted Armor upgrade for Pneumatic Armor.  Adding them to the armor did not change the armor rating.

### Expected behavior

Armor should increase accordingly.

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

8.0.3

**Comment by desht** [comment]
Fixed in 8.1.0
