### ISSUE TITLE
Memory Leak of Client Player

### ISSUE THREAD

**Issue by pietro-lopes** [TeamPneumatic/pnc-repressurized#1334]
### Describe the bug

Memory leak of Client Player

ArmorMainScreen holds an static instance of self that:
 -> holds a upgradeOptions which is SearchOptions that:
-> holds player

![image](https://github.com/user-attachments/assets/1dc5a12f-18e9-4636-8fc8-5e7e5b87203e)

### How to reproduce the bug

Join game and exit to main screen, Player is leaked

### Expected behavior

No leak

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

8.0.3

**Comment by desht** [comment]
Fixed in 8.1.0
