### ISSUE TITLE
Memory Leak of Client Level

### ISSUE THREAD

**Issue by pietro-lopes** [TeamPneumatic/pnc-repressurized#1335]
### Describe the bug

There is a memory leak of Client Level

AreaRenderManager instance holds client level

### How to reproduce the bug

Join game, exit game to main menu, client level is leaked

### Expected behavior

No leaks

### Additional details

![image](https://github.com/user-attachments/assets/ae4c6f6a-9a21-42ae-8f4d-570de93d7838)

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

8.0.3

**Comment by desht** [comment]
Fixed in 8.1.0
