### ISSUE TITLE
Memory Leak of MinecraftServer

### ISSUE THREAD

**Issue by pietro-lopes** [TeamPneumatic/pnc-repressurized#1336]
### Describe the bug

This memory leak is caused by not unregistering the DroneEntity from event SemiblockEvent when entity leave the level.

### How to reproduce the bug

Join a world, summon any drone, leave world, join again and server is leaked in memory.

### Expected behavior

Should unregister by storing a local variable holding the consumer, registering via consumer and unregistering via object does *NOT* match and fails to unregister.

Registering via Consumer
https://github.com/TeamPneumatic/pnc-repressurized/blob/a010f97a5f04ebbd32e65405a8616a5c5c5eda32/src/main/java/me/desht/pneumaticcraft/common/entity/drone/DroneEntity.java#L573

But trying to unregister via object (not only those cases, look for more)
https://github.com/TeamPneumatic/pnc-repressurized/blob/a010f97a5f04ebbd32e65405a8616a5c5c5eda32/src/main/java/me/desht/pneumaticcraft/common/entity/drone/AmadroneEntity.java#L202
https://github.com/TeamPneumatic/pnc-repressurized/blob/a010f97a5f04ebbd32e65405a8616a5c5c5eda32/src/main/java/me/desht/pneumaticcraft/common/entity/drone/DroneEntity.java#L984

Also trying to unregister on `die` might not include when single players leave world.
You might want to override `onRemovedFromLevel` or whatever you choose is the best for your case.

### Additional details

![image](https://github.com/user-attachments/assets/dffbc1ab-2962-4c59-8bb8-e44e95d6c50a)

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

8.0.3

**Comment by desht** [comment]
Fixed in 8.1.1
