### ISSUE TITLE
EMI/JEI Info Tab showing Electrostatic Grid blocks

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#1337]
### Describe the feature

Similar to the fuels/heat tabs, it'd be nice if there were a pane showing the items in this tag.

### Reasons why it should be considered

With the upcoming inclusion of the lightning rod in the tag by default, it's becoming less obvious to the player what blocks can be used. This would help with discoverability.

**Comment by desht** [comment]
Just to be clear, are you looking for a separate JEI tab with this info (like the heat properties info), or a PNC side tab (like the fuels display in the liquid compressors) ?

**Comment by MuteTiefling** [comment]
I was thinking more along the lines of the Heat Properties info in JEI. 

A side tab in the compressor would probably end up being uselessly long in some cases. For example, in e10 I've added every solid copper block so you can build a nice platform for them to sit on that you can walk on without falling through. It's got somewhere just north of 120 blocks between Vanilla and Chipped.

![image](https://github.com/user-attachments/assets/bfc347c2-19c7-465b-b4cc-d74c4ecc7302)
![2024-08-28_08 53 20](https://github.com/user-attachments/assets/602bf243-f9df-465e-a943-0e52e8d8aeef)

**Comment by desht** [comment]
Yeah, sounds like a case for a JEI pseudo-recipe and associated category...  shouldn't be too hard, I think.

Hmm, taking this a step further, maybe proper datapack recipes for block would be interesting. Where the block type can map to various properties like strike chance, strike multiplier, sound volume modifier... :thinking: That would be a much more ambitious project though, so initially just a "grid properties" tab.

**Comment by MuteTiefling** [comment]
That would certainly be cool. Corroded copper could have less conductivity, while nice clean copper/waxed copper maintains a higher conductivity and thus gives the thing a bonus.

You only really need 4 layers for an optimal setup, so 5th layer could be wool with no conductivity but sound dampening.

**Comment by desht** [comment]
Added in 8.1.1

**Comment by MuteTiefling** [comment]
Awesome thanks!
