### ISSUE TITLE
Online-only chunk loading 

### ISSUE THREAD

**Issue by johalun** [TeamPneumatic/pnc-repressurized#1342]
### Describe the feature

A config option to limit chunk loading to online players only. With this option enabled, drones and PCs would stop chunk loading when the owner goes offline, and resume when the owner comes back online. Optionally with a configurable delay to avoid a break in chunk loading if a player needs to logout briefly (like Chunk Loaders mod). 

### Reasons why it should be considered

To reduce lag on multiplayer servers.

**Comment by desht** [comment]
Added in 8.1.2

**Comment by johalun** [comment]
Nice! Will this be backported to 1.20.1?

**Comment by desht** [comment]
Maaaaybe... it's not a trivial backport due to Forge -> NeoForge changes, but I'll take a look if & when I have some time. Unfortunately 1.21 has to be priority for all new features.
