### ISSUE TITLE
Crop support

### ISSUE THREAD

**Issue by ThatCursedBre** [TeamPneumatic/pnc-repressurized#1349]
### Describe the feature

Can crop supports please be not entities.

### Reasons why it should be considered

 I'm on a server with friends and we killed the server's tps (ranging from 60-80 ticks behind) by placing some of these not knowing they were entities.

**Comment by desht** [comment]
No, they can't not be entities. Do you have some evidence that crop supports are causing performance issues? E.g. some spark output?

Just to note, I _have_ done some spark profiling, and there's no evidence that crop supports (even big fields of them) cause any TPS issues. So I suspect you have something else going on with your server.

**Comment by desht** [comment]
Closing due to lack of response.
