### ISSUE TITLE
Elevator callers not working as elvator only extends up to 4 blocks giving errors place more elevator frames when I already placed them

### ISSUE THREAD

**Issue by williamforber** [TeamPneumatic/pnc-repressurized#135]
*For feature requests, just erase this template and cle
![2018-04-01_11 43 23](https://user-images.githubusercontent.com/37976094/38172306-fb1a7c3e-35a1-11e8-892a-e2e32f6564f4.png)
![2018-04-01_11 43 33](https://user-images.githubusercontent.com/37976094/38172309-0afc792c-35a2-11e8-95c3-bbdf100989c2.png)

arly describe the feature you'd like to see*
 Version 1.12.2

**Comment by desht** [comment]
Have you stacked enough elevator bases vertically? By default you need one base per 4 blocks of elevator height, but that can be changed in config (I:elevatorBaseBlocksPerBase)

**Comment by williamforber** [comment]
Oh sorry for being so dumb

**Comment by desht** [comment]
Going to assume you have it sorted now, closing.
