### ISSUE TITLE
Sentry Turret Upgrades tab missing localization

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamPneumatic/pnc-repressurized#1350]
### Describe the bug

The upgrade tab in the Sentry Turret uses the wrong localization key. 
The correct one seems to be `pneumaticcraft.gui.tab.upgrades.sentry_turret.range`, which is not set.
![image](https://github.com/user-attachments/assets/dc943285-e9bc-42a9-8ae5-97a1aa29daa0)

### How to reproduce the bug

Look in the Sentry Turret GUI

### Expected behavior

Localized text 

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-8.1.3+mc1.21.1

**Comment by desht** [comment]
Fixed in 8.2.0
