### ISSUE TITLE
Crash with drone crafting items

### ISSUE THREAD

**Issue by Laveticus** [TeamPneumatic/pnc-repressurized#1354]
### Describe the bug

Playing on the Direwolf20 v11 pack on version 1.2.1 (also tested after updating PNC to 8.1.4, crash persists)

Attempting to craft with the drone with a single item recipe (tried both sugar cane -> sugar and logs -> planks) will crash the game as soon as it tries crafting. The relevant errors I get in the log seem to be these:

[Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity

and

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/java.util.Arrays$ArrayList.get(Arrays.java:4266) ~[?:?] {}

### How to reproduce the bug

1. place down inventory (chest, sophisticated storage crate, etc.) and put an item in it that crafts by itself (sugar cane, logs, etc)
2. Make drone pick up 1 item in that inventory
3. Make drone craft that item into something (sugar, planks, etc.)
4. Crash

### Expected behavior

I expect it would craft the item, not crash the game immediately.

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

8.1.3/8.1.4

### Crash log

https://pastebin.com/SFUkcjGH

**Comment by desht** [comment]
Fixed in 8.2.0
