### ISSUE TITLE
Railcraft Reborn Logistic Frames

### ISSUE THREAD

**Issue by T1ckss** [TeamPneumatic/pnc-repressurized#1357]
### Describe the bug

Logistic frames (requester and provider) seem to not recognize the multiblocks steam boiler, turbine and iron tanks of railcraft reborn when a world is reloaded.

Since they do not recognize them as inventories the frames will pop off the multiblocks when you save and reload a world.

Once the world is loaded however the multiblocks seem to have "formed" allowing the frames to replaced back on the multiblocks and function correctly.

### How to reproduce the bug

Minecraft 1.21.1
PneumaticCraft 8.1.4
Railcraft Reborn 1.2.2

In singleplayer world.
Create a Boiler to produce steam from railcraft.
Create a Turbine to create FE from railcraft
Connect using pressure tube network to transfer the steam from boiler to turbine.
Place logistic provider frame on boiler
Place logistic requester frame on turbine

Power the pressure tube network with any compressor (used advance liquid compressor)

The Turbine will get water and steam transferred through the pressure tube logistic network.
Save the world and reload.

The logistic frames will pop off the multiblocks.

### Expected behavior

Expected behavior is for the logistic frames to remain attached to the multiblocks.

### Additional details
The issue has also been reported over at railcraft github.
https://github.com/railcraft-reborn/railcraft/issues/253

### Which Minecraft version are you using?

1.21.1

### Which version of PneumaticCraft: Repressurized are you using?

8.1.4

**Comment by desht** [comment]
As discussed on discord, Logistics Frames will pop off any blocks which offer neither an item nor fluid capability on the side they're attached to. So I would surmise that the item/fluid capability is present on the side of the railcraft blocks when the frames are placed, but absent on a server restart when the logistics frame entities are reloaded. I do not consider this a bug with PNC.
