### ISSUE TITLE
Security Upgrade ignored by compressors upon reloading singleplayer-world or multiplayer-world

### ISSUE THREAD

**Issue by Stephen-Seo** [TeamPneumatic/pnc-repressurized#1359]
### Describe the bug

A compressor with a Security Upgrade installed will not eject excess air after the world is reloaded. This can be temporarily fixed by removing the Security Upgrade and putting it back, but can be tedious if there are a lot of compressors with Security Upgrades. For now, a workaround is to use the Safety Tube Modules on Pressure Tubes instead.

### How to reproduce the bug

Set up a compressor like a Solar Compressor and give it a Security Upgrade, and ensure that it has reached "max pressure". Leave the game in singleplayer (or restart the world in multiplayer) and come back. The compressor will act as if the Security Upgrade wasn't installed and may explode at critical levels of pressure.

### Expected behavior

The compressors should eject excess air as advertised by the Security Upgrade even after a world reload.

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

8.1.4

**Comment by desht** [comment]
3e1bd043cfd4522f6a95a0eca9d4511897365550

**Comment by desht** [comment]
Fixed in 8.2.0

**Comment by ShadowDrakken** [comment]
Any chance of backporting this to 1.20.4 for FTB NeoTech?
