### ISSUE TITLE
Entity Tracker Upgrade for Omnidirectional Hopper not deteck

### ISSUE THREAD

**Issue by YamikazeEiji** [TeamPneumatic/pnc-repressurized#1362]
### Describe the bug

I have used this setup in 1.19.2 and it is supposed to detect the inventory of Minecraft: Witch and Occultism: Crusher Marid and input/Output items from them. However in the latest 1.21.1 version, It can't seem to detect the inventory. Thus, all the items are just stuck in the system.

### How to reproduce the bug

![image](https://github.com/user-attachments/assets/5a0329e7-4afb-4770-87eb-a4213d6e442d)

### Expected behavior

This setup is supposed to put the life-mending enchanted equipment into the witch's inventory and export it out when the item is repaired.
similarly, the Omnidirectional hopper was supposed to detect the empty inventory slot in Crusher Marid and input raw ores into it for crushing.

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-8.1.4%2bmc1.21.1

**Comment by MuteTiefling** [comment]
Noticed this as well. Doesn't seem to interact with any entity anymore, player included.

**Comment by desht** [comment]
That's already fixed in 8.2.0.  Please test with the _actual_ latest version before creating issues, thanks.
