### ISSUE TITLE
Patchouli book's image broken (maybe from 1.18.1)

### ISSUE THREAD

**Issue by momo-i2** [TeamPneumatic/pnc-repressurized#1365]
### Describe the bug

src\main\resources\assets\pneumaticcraft\textures\patchouli\heat_sinks.png may broken. When I check your each branches(but I checked only from 1.16.5 to 1.21), 1.16.5 not broken, but from 1.18.1 to 1.21 may broken. (sorry for my bad English)

### How to reproduce the bug

1. Open PNC:R Manual
2. Click Entry Index
3. Search "Heat Sink" and click that

![image](https://github.com/user-attachments/assets/4f376850-ddae-4b86-964a-d35082952a13)

### Expected behavior

The image should look like this
![heat_sinks](https://github.com/user-attachments/assets/d5b0eed0-38f7-48ce-948a-08030295be2f)

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-8.2.2+mc1.21.1

**Comment by desht** [comment]
Merged your PR, thanks!
