### ISSUE TITLE
ATM9 Server won't relaunch due to PneumaticCraft

### ISSUE THREAD

**Issue by Merkkus** [TeamPneumatic/pnc-repressurized#1366]
### Describe the bug

I previously had server running ATM9 Server using PneumaticCraft: Repressurized, I stopped the server and then restarted my VM.

Following this I cannot successfully relaunch the server due to issue with PneumaticCraft. Full crash log attached in pastebin.

### How to reproduce the bug

Launch Minecraft Server using startserver.sh

### Expected behavior

Minecraft Server Launch successfully

### Which Minecraft version are you using?

1.20.1

### Which version of PneumaticCraft: Repressurized are you using?

6.0.17

### Crash log

https://pastebin.com/qYtWXjd0

**Comment by desht** [comment]
One of the json files in the config/pneumaticcraft subfolder is corrupt.

The log doesn't say which, so you can either check them manually (or run them through a json syntax checker),
or just delete them all and new defaults will be generated on next startup.
