### ISSUE TITLE
Ensure MCMP2 support can't be accidentally enabled (Crash From PneumaticCraft refinery)

### ISSUE THREAD

**Issue by IchigoGames** [TeamPneumatic/pnc-repressurized#137]
### connecting Pressure Tube to to a PneumaticCraft refinery crashs you puts the server in a crash loop and in singeplayer it makes your game stopped responding.

if you need a full mod pack list let me know its big so not posting it here unless needed.

Crash Report https://pastebin.com/5FyYSNdb

**Comment by desht** [comment]
Have you switched on Mcmp2 support? It needs to be left off, since it doesn't work.

**Comment by IchigoGames** [comment]
nope is there a config option for that ?

**Comment by IchigoGames** [comment]
nvm found it thank you ill see if that stops it

**Comment by IchigoGames** [comment]
ok that worked if Mcmp2 does not work maybe leave it disabled till it does.

**Comment by desht** [comment]
Yeah, it's disabled by default in config.  Probably worth hardwiring it off to prevent accidental enabling... going to leave this open till that's done.
