### ISSUE TITLE
Crash on initial loading screen maybe due to conflict with UnionLib 12.0.7

### ISSUE THREAD

**Issue by Proaxel** [TeamPneumatic/pnc-repressurized#1377]
### Describe the bug

Setup is version 1.4.1 of the Direwolf20 Season 14 modpack, installed and configured using Prism Launcher 9.1.
I used Prism Launcher to add the ControllerSupport mod by StereoWalker; Prism Launcher automatically added UnionLib as it is a dependency.

Upon launching, the game crashes during loading with the following crash log. In order for the game to launch normally I had to disable UnionLib; disabling ControllerSupport was not sufficient. Since the crash log explicitly states that it was PneumaticCraft that had encountered an error I figured it was maybe due to sort of conflict with UnionLib.

### How to reproduce the bug

Install "FTB Presents Direwolf20 Season 14" through whatever means and launch it normally.
Close the game and add the ControllerSupport and UnionLib mods to the install.
Launch the game.

### Expected behavior

The game is expected to at least load into the main menu alongside the Controllersupport and UnionLib mods without any crash.

### Additional details

This was done on a Steam Deck.

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

8.2.3

### Crash log

https://mclo.gs/dNYFn7W

**Comment by desht** [comment]
That's on Unionlib. PNC is doing nothing wrong here.
