### ISSUE TITLE
Drone duplication bug on drone coloring recipe.

### ISSUE THREAD

**Issue by KodYazanDruid** [TeamPneumatic/pnc-repressurized#1380]
### Describe the bug

[        ItemStack drone = stacks.get(0).copy();](https://github.com/TeamPneumatic/pnc-repressurized/blob/7cbd90ee2c24fa27a9603c8101ea4c24b895c9e7/src/main/java/me/desht/pneumaticcraft/common/recipes/special/DroneColorCrafting.java#L56C9-L56C48) This method copies whole stack instead of copying with single count.

### How to reproduce the bug

Simply try to color drone stack that has more than 1 item.

### Expected behavior

It should given onlye one drone instead of whole stack.

### Additional details

I think it is a critical bug. This also exists on 1.20.4 maybe even earleir versions.

### Which Minecraft version are you using?

1.21

### Which version of PneumaticCraft: Repressurized are you using?

1.21 and 1.20.4

**Comment by desht** [comment]
Fixed in 8.2.5 release
