### ISSUE TITLE
Items glitch out in roughly enough items when pnc is installed

### ISSUE THREAD

**Issue by NumanSadik** [TeamPneumatic/pnc-repressurized#1382]
### Describe the bug

![image](https://github.com/user-attachments/assets/79fea313-c230-4705-8a83-189e87ce03b1)
When you have the crafting filter on and some items that are craftable into something, the items flicker in and out in the side bar where roughly enough items show what you can craft out of those items.

Forge Version 47.2.30

### How to reproduce the bug

Have your crafting filter enabled for Roughly Enough Items
Being on creative works better.
Get some craftable material, I‘ve gotten logs, planks and woods etc. in my instance.
Check the right items panel

### Expected behavior

Items should hold still

### Which Minecraft version are you using?

1.20.1

### Which version of PneumaticCraft: Repressurized are you using?

pneumaticcraft-repressurized-6.0.18+mc1.20.1

**Comment by NumanSadik** [comment]
https://github.com/user-attachments/assets/1a5f880a-68e0-45fb-b514-dd61ab688708

**Comment by NumanSadik** [comment]
Oh and items should not even be showing up at all since I‘m not in a crafting hud.

**Comment by desht** [comment]
Sounds like an REI problem to me.  I don't do anything out of the ordinary with JEI, and PNC doesn't have any REI integration at all. So no idea what I could possibly change here to fix whatever problem this is.
