### ISSUE TITLE
Lazy drone don't work when I don't stalk them

### ISSUE THREAD

**Issue by Sewef** [TeamPneumatic/pnc-repressurized#140]
Minecraft 1.12.2

 forge-1.12.2-14.23.2.2624

pneumaticcraft-repressurized-1.12.2-0.5.1-163

When I'm not near to my Drones, they just stop working.
I have this issue with my 4 Drones : a Wheat right-clicker, a Wheat getter, a Leaves breaker and a Sapling placer. All of them, when I'm not here to keep them working, hibernate.
The Drones are in perma-loaded chunks (using PersistantsBits' Chunk Loader). They have enough pressure to work.

**Comment by desht** [comment]
Can you please export your program to pastebin (using the pastebin button on the left of the programmer gui) and add the link to this issue?

(and do the same for the other two issues you created)

**Comment by Sewef** [comment]
Didier - The Wheat Right-clicker
https://pastebin.com/ZBaJ9d9Q

Jean - The Wheat Getter
https://pastebin.com/CHgMYeBP

**Comment by desht** [comment]
I haven't been able to reproduce this one.  I set a drone digging a very large area, chunkloaded it, and left.  When I got back later, the drone had definitely continued to work while I was away.

I wonder if the PersistantsBits chunk loader is working as expected?  I used an IC2 chunk loader.

**Comment by Sewef** [comment]
Oh. I can reproduce anytime by disconnecting or going away. Meh.
I will try with HammerCore chunk loading command and Steves's Cart Chunk Loader.

**Comment by desht** [comment]
Also tested (on a server instance) using FTBUtils chunkloading, and it worked fine here too.  Flew a long way away, and also logged off for a while.  When I came back, the drone was still digging fine (and had been when I was away, given the huge hole it had made...)

**Comment by Sewef** [comment]
Tested with ChickenChunk's Chuck Loader, and it works. We can blame Persistent Bits ^_^

**Comment by desht** [comment]
Good to know!  Going to close this here, it seems work with every chunk loading mod except for PB.
