### ISSUE TITLE
Drone can't export item in inventory if not used in any way

### ISSUE THREAD

**Issue by Sewef** [TeamPneumatic/pnc-repressurized#141]
Minecraft 1.12.2

forge-1.12.2-14.23.2.2624

pneumaticcraft-repressurized-1.12.2-0.5.1-163

My Sapling Planter drone is pretty stupid.

_What I did_ : 
- **Import from inventory** piece to get items from a Drawer (Storage Drawers)
- **Place** piece to an area
- **Export to inventory** piece to put excess items in the same Drawer
- **Goto** charging station

_What it was supposed to do_ : 
- Take a stack of items
- Place them if possible
- Put excess item in the drawer
- Wait on the Charging Station

_What it do_ : 
- Take a stack of items
- IF it didn't use any taken item, keep them
ELSE put them in the drawer
- Wait on the Charging Station

Is the "don't put unused stack" a bug of a feature ?

**Comment by Sewef** [comment]
Chapo - The Sapling Planter
Program here : https://pastebin.com/RaF0V0QS

**Comment by desht** [comment]
Just tested this, and it worked as I expected.  I set up a drawer with 64 saplings, and a 5x5 area to plant in.

- First run: drone takes 32 saplings, plants 25, returns 7 to the drawer, goes to the charging station and waits
- Next run: no saplings grown.  Drone goes to drawer, takes saplings, immediately puts them all back in the drawer (nowhere to place them), returns to the charging station
- Next run (I broke few saplings).  Drone goes to drawer takes saplings, replants in gaps, returns remainder to drawer, returns to charging station

Exactly as I would expect.  It never kept any unused saplings, even if it didn't use any.

**Comment by Sewef** [comment]
Uh. I can reproduce this without problem... I will make a video when I will be back home.
Are you using the same program as me ? Or maybe we do not have the same forge version ?

**Comment by Sewef** [comment]
https://www.dropbox.com/s/elktmq480o9uinh/Minecraft%201.12.2%2009_04_2018%2017_45_30.mp4?dl=0

I just tested in single player, and it works !
Maybe all my problems are multiplayer only ?

**Comment by desht** [comment]
I'll test it out on a dedicated server instance and see what happens.

**Comment by desht** [comment]
Tested on a server, and still can't reproduce it - the drone does exactly as I'd expect, putting away all saplings it took even if it can't plant any...

**Comment by Sewef** [comment]
Oh.
That's weird.
It works in singleplayer but not in multiplayer, so maybe we have a server-side problem ?
Here's the server\mods folder : https://pastebin.com/QqqfbaCX

**Comment by Sewef** [comment]
Update: The drone puts correctly the items if the "Export to Inventory" don't point the drawer it used to get the items.

https://pastebin.com/GsN0shzR

For now, I Import the sapling from my drawer and Export into a hopper pointing into the drawer.
Still a bug, but there's a parade.

**Comment by Sewef** [comment]
Build 175 fixed this !

**Comment by desht** [comment]
Excellent!
