### ISSUE TITLE
[1.12.2] pneumatic craft fluid handler issue on new forge 14.23.3.2657 version 1.12.2-0.5.1-163.jar

### ISSUE THREAD

**Issue by warcommando2** [TeamPneumatic/pnc-repressurized#146]
### Minecraft Version
1.12.2
### Forge Version
14.23.3.2657
### Mod Version
1.12.2-0.5.1-163
### Describe your problem, including steps to reproduce it
seem to be having an issue loading minecraft after mod loading. It seems to crash and gives me this error below. I am currently getting updates on the go for my modpack Called cryo's chronicles on curse/twitch launcher and it even crash's with optifine as well. please see attached notepad file.
[stack trace after mods loaded.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/1899096/stack.trace.after.mods.loaded.txt)

**Comment by desht** [comment]
At exactly what point is this crash occurring?  It would be useful to see a complete stack trace to know exactly when this is happening.  It looks like onItemTooltip() is getting called much earlier than expected, i.e. before capabilities are even initialised.  I don't have access to my dev instance right now so can't tell for sure, but I'll take a look later.

**Comment by desht** [comment]
Actually, it may be a very simple fix.  Can you try out build 167 (or later) from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ and let me know if it fixes your problem?

**Comment by warcommando2** [comment]
i will give that a try tonight here is the full log as requested.
[crash-2018-04-11_07.50.42-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/1899964/crash-2018-04-11_07.50.42-client.txt)

**Comment by desht** [comment]
I'm going to back this change out; it's not a PNC:R problem, and the one-liner I added isn't the appropriate fix.  This is actually a Forge bug - see https://github.com/MinecraftForge/MinecraftForge/issues/4865 - introduced in build 2655 and appears to be fixed in build 2658+.
