### ISSUE TITLE
Programmable Controller : infinite sucking and drone giving glitch

### ISSUE THREAD

**Issue by Sewef** [TeamPneumatic/pnc-repressurized#148]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Mod Version pneumaticcraft-repressurized-1.12.2-0.5.1-163

Hey, it's me again !
Definitly, something is wrong with my server.

_What I did :_ 
I placed my drone in a Programmable Controller with the following program : https://pastebin.com/8emcR71J
The programmable Controller is powered by a 5Bar pressure.

_What it was supposed to do :_ 
- Get the saplings from the Drawer
- Plant them if possible
- Get the saplings back

_What it do :_ 
- Get the saplings
- Get the saplings
- Get the saplings
- Get my 32 stacks of saplings. That's all.

Gonna play a sad music.

_What I did :_
I placed my drone in a Programmable Controller with the following program : https://pastebin.com/N4A3Q8xP (I don't know what I expected without a suck from chest piece)
This time I replaced my drawer by a chest filled with 20 Ironwood Sapling (because I lost everything, thanksfully I don't care that much).

_What it was supposed to do :_
Maybe use the 32 stacks the latest drone stole me up, or simply nothing

_What it do :_
The drone started filling my chest with a copy of the Drone I placed in the Programmable Controller.

![image](https://user-images.githubusercontent.com/27089398/38771184-cdafaa8a-401e-11e8-941f-6aa9dcaec55e.png)

I have a lot of Chapo now !

Please kill me.

**Comment by desht** [comment]
Yeah, you're right - the Programmable Controller really isn't working too well right now.  I'm taking a look.

**Comment by Sewef** [comment]
Much better !
However, is there a way to kill a ghost drone ? I have a little drone from the Programmable Controller that just sit, waiting for the end of all things. Removing the controller don't do anything.

![2018-04-17_13 07 05](https://user-images.githubusercontent.com/27089398/38866225-7d762e08-4240-11e8-8cfa-6a076eabaad0.png)

**Comment by desht** [comment]
That should already be fixed in the latest dev build.  Removing the drone from the controller will reset the current program, and the fake drone will return to the controller.  I've not seen a problem where removing the controller itself leaves ghost entities around, though...

**Comment by Sewef** [comment]
I'm using the 171 build. I already had this ghost before updating, it moves sometimes when trees grows (even if it can go through the walls) but I can't kill it.

**Comment by desht** [comment]
Hmm, possibly a sync issue?  Does it stick around if you disconnect/reconnect (or restart) your client?

**Comment by Sewef** [comment]
Looks like a sync issue, yup.
I broke the Programmable Controller this afternoon and I just reconnected : the ghost disapeared ^_^'

**Comment by Sewef** [comment]
Maybe it was a remainder of the previous version, we'll see when I'll reconnect !
It's not a serious problem, thanksfully :p
