### ISSUE TITLE
Server-Crash : Ticking Block Entity (Refinery)

### ISSUE THREAD

**Issue by Sewef** [TeamPneumatic/pnc-repressurized#149]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Mod Version pneumaticcraft-repressurized-1.12.2-0.5.2-171

Hello again :D 
My server is in a crash-loop.

_My Setup :_ 
- A Portable Tank (Thermal Expansion) filled with Oil placed on an Iron Drum (Ex2)
- A Liquid PhantomFace (ActuallyAdditions) connected to the Drum
- The Refinery placed on the PhantomFace

_What I did :_ 
- I toggled the Portable Tank to empty him to the Drum (then PhantomFace, then Refinery)
- The server crashed.
- Crash loop : I can't start it properly.

_Crash report :_ 
[crash-2018-04-17_16.22.55-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/1920238/crash-2018-04-17_16.22.55-server.txt)

It worked before updating to 171.

**Comment by desht** [comment]
Yeah, I see the problem here - getInputTank() is a client-only method.

**Comment by desht** [comment]
https://github.com/TeamPneumatic/pnc-repressurized/commit/d4120f3b500d8e74712c176e6cb9b9a2518cd0ca

**Comment by desht** [comment]
Build 172 should fix that.

**Comment by Sewef** [comment]
Build 172 fixed that.

Nice work, thanks ^_^
