### ISSUE TITLE
Security Station - Share Input / Button

### ISSUE THREAD

**Issue by artdude543** [TeamPneumatic/pnc-repressurized#150]
### Minecraft Version
1.12.2
### Forge Version
14.23.2.2651
### Mod Version
0.5.1-163
### Describe your problem, including steps to reproduce it
Got an issue posted to the SevTech Tracker about the security station "share" input not working as it should. The issue can be found here: https://github.com/Darkosto/SevTech-Ages/issues/1931

**Comment by desht** [comment]
Closing
