### ISSUE TITLE
[JEI] Issue / Crash

### ISSUE THREAD

**Issue by artdude543** [TeamPneumatic/pnc-repressurized#152]
### Minecraft Version
1.12.2

### Forge Version
14.23.3.2669

### Mod Version
0.6.0-174
JEI Ver: 4.9.1.165

### Describe your problem, including steps to reproduce it
Working on the next major update to SevTech: Ages and with the latest update, something is up/broken with the Liquid hopper (a broken recipe or something) in turn this issue causes a crash when you try to view the recipe. Along with breaking internals of JEI _(Which I think is another bug on top of this one)_ I.E. Recipe/Item hiding breaks due to this issue; downgrading this mod to 0.5.1-163 resolves the recipe error from JEI.

### Log/s
Crash Log / JEI Log: https://gist.github.com/artdude543/8fd07e29dbfcb615494e45090f0bd63b

**Comment by artdude543** [comment]
@mezz want me to report this on your tracker also? As I don't think this should break your entire start phase for JEI itself. As this stops the item hiding from continuing/loading also when the broken recipe error gets thrown out.

**Comment by MineMaarten** [comment]
Hmm it's probably related to this commit: https://github.com/TeamPneumatic/pnc-repressurized/commit/d5a9b6ff5a46d88b483534e531c635db14916ed6

**Comment by MineMaarten** [comment]
Okay, you can grab a fix here: http://jenkins.k-4u.nl/view/Desht/job/PneumaticCraft-Repressurized/176/
The same build is under review on curse, which should be approved soon, to put in the pack if you'd like.

@mezz I wouldn't mind either way what you do about this (adding a null check or not), while it isn't said explicitly in getTankProperties, you could say it should be a non nullable return value "Returns an array of objects which represent the internal tanks."

**Comment by mezz** [comment]
Thanks, please report it to JEI and link back here. It should tolerate all kinds of bad input without completely breaking. I can look at updating the docs as well.

**Comment by mezz** [comment]
I'm looking into this and I don't think it's breaking JEI that badly. There have been issues lately with hiding items and recipes and I've been making fixes, but it's probably unrelated to this.
I will log an error if I get `null` for `IFluidTankProperties` but otherwise I think things should be fine.
