### ISSUE TITLE
Crash on world load related to Spawner Agitator

### ISSUE THREAD

**Issue by DerpityDoo** [TeamPneumatic/pnc-repressurized#153]
https://github.com/Darkosto/SevTech-Ages/issues/2029

https://pastebin.com/iHd5ywvE

**Comment by desht** [comment]
The crash occurs in ``WorldServer#sendPacketWithinDistance()``, called from ``WorldServer#spawnParticle``.  It looks like ``WorldServer#sendPacketWithinDistance()`` is getting a null player.

Quick workaround: in your server-side Despawning Spawners config, set **B:displaySpawnerParticle** to false.  This will stop Despawning Spawners playing particle effects but should resolve the crash for now.  I'll do some debugging and work out if it's on PNC:R or Despawning Spawners (or both) to resolve this issue properly.

**Comment by desht** [comment]
Build 177 from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ should fix the problem - if you're in a position to test that, I'd like to know if it helps.

**Comment by desht** [comment]
Should be fixed in 0.6.2 release.
