### ISSUE TITLE
Can't Shift+RightClick to place a block on a charging station

### ISSUE THREAD

**Issue by Sewef** [TeamPneumatic/pnc-repressurized#155]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it

Hey, did I missed you ?
Still on server.

When I try to place a block on the up side of a Charging Station using shift+rightclick, the block is placed but it quickly go back into my inventory (like if a server protection plugin denied the action).
Same issue with and without Dispenser Upgrade.
By focusing another block, the placement works properly.

**Comment by desht** [comment]
Fixed in 0.6.3 release
