### ISSUE TITLE
Coloring en entityDrone takes the whole stack of dye

### ISSUE THREAD

**Issue by Sewef** [TeamPneumatic/pnc-repressurized#156]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
Because I never dye my drones before putting them in the world.

*What I did*
- Take some Cyan dye
- Right click Call of Duty with
- Take some Light Blue dye
- Right click Overwatch with
- Take ONLY ONE Lapis Lazuli
- Right click League of Legends

Yup, just wanted to talk about my Salt Delivery Drones.

*What it was supposed to do*
Use one dye to color each drone

*What it do*
Use the whole stack of dye to color each drone

Thanksfully, I spotted that before dyeing with my lapis :D 

As everytime, on server.

**Comment by desht** [comment]
I'm not seeing the whole stack being used, but it is using two dyes instead of one.  Very easy fix though...

**Comment by Sewef** [comment]
Woops, maybe I speculated too much ^^'

**Comment by desht** [comment]
Fixed in 0.6.3 release
