### ISSUE TITLE
Suggestion: Plastic Mixer JEI Display

### ISSUE THREAD

**Issue by artdude543** [TeamPneumatic/pnc-repressurized#159]
Hello!

With SevTech Ages we change the Dyes to use another mod, which the Plastic Mixer supports out of the box. But we are having users getting confused with using the machine as we remove the Vanilla Dyes from the OreDictionay. But JEI displays the Vanilla ones as it's harded coded [here](https://github.com/TeamPneumatic/pnc-repressurized/blob/master/src/main/java/me/desht/pneumaticcraft/common/thirdparty/jei/JEIPlasticMixerCategory.java#L50-L52).

Could it be possible to use the Ore Dictionary/Config and show the first item in that insead? (As our first one is the custom one) to allow the displaying of the "correct" item for the dyeing.

Thanks!

**Comment by desht** [comment]
Yeah, that sounds sensible. I'll have a look at that.

**Comment by desht** [comment]
This is added in builds 184+ from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ - please give that a try and see how it looks...

**Comment by artdude543** [comment]
Yep, works amazing!

![image](https://user-images.githubusercontent.com/1885466/39472505-cad54542-4d41-11e8-9046-819779944253.png)

Thank you for doing this! ❤️

**Comment by desht** [comment]
Excellent.  Do you have a date yet for the next SevTech release?  Would be nice to get this in there.

**Comment by artdude543** [comment]
Currently, we don't wait for some minor/major updates to a few mods and to complete some script changes. But if anything it would late this week at latest due to us wanting to get this update out cos of the number of fixes already.

But having this in the update would be ideal for us also.

**Comment by desht** [comment]
That's cool.  We have only one other change (a RFTools-related crash fix) since our last release, but I could probably get a minor release out this week.

**Comment by desht** [comment]
Fixed in 0.6.4 release
