### ISSUE TITLE
Suggestion: Oredict for the Compressed Iron Gear

### ISSUE THREAD

**Issue by Xiaminou** [TeamPneumatic/pnc-repressurized#160]
Thermal Expansion uses oredict to add gears to their [Gearwork Die](https://teamcofh.com/docs/augment-gearworking-die/), however the Compressed Iron Gear doesn't have one so it isn't automatically detected. 
I suspect Immersive Engineering might do something similar for their Metal Press.

**Comment by desht** [comment]
Do you have a link to where TE is detecting suitable oredict entries?  Guessing it's looking for stuff starting with "gear", but it would be good to know for certain.

**Comment by Xiaminou** [comment]
I don't, I've only been told that it requires an ore dictionary, my guess is the same as yours, "gear". If you want to be sure you'd have to ask one of their developers. But I think "gearIronCompressed" should work.

**Comment by desht** [comment]
OK, I'm sure I'll figure it out.  "gearIronCompressed" does make sense.

**Comment by desht** [comment]
Fixed in 0.6.4 release
