### ISSUE TITLE
Refinery Volume Upgrades

### ISSUE THREAD

**Issue by bookerthegeek** [TeamPneumatic/pnc-repressurized#161]
## Heyo ##
That them their's a prudy template you got going. 😄 

### Issue
I can not seem to find the location to add the volume upgrade to the refinery

![Setup](https://i.imgur.com/Q4eFBQ7.png)
![Interface](https://i.imgur.com/OE4M57m.png)
### Versions
- Minecraft 1.12.2
- Pneumaticcraft Repressurized 0.6.3-181
- Forge 14.23.3.2678

Full mod list online on [GIST](https://gist.github.com/bookerthegeek/8cdf5287b5c2345723c063b62a95369b)

**Comment by desht** [comment]
That's because the refinery doesn't take any upgrades.

I not sure how much point there really would be in adding volume upgrades here - the refinery is a processing machine, not a storage device. "Volume upgrades" can be achieved by connecting tanks to the input and/or output of the refinery.

**Comment by desht** [comment]
But I see the problem now... That's a misleading info panel, alright :)

**Comment by bookerthegeek** [comment]
I can see the point about it not being a storage device. I was more looking for the stabilization of temperature modifications.

**Comment by desht** [comment]
I'll leave this ticket open; changing the refinery's heat behaviour is more of a balance/design issue which needs some further thought.

Note that covering as many open faces of the refinery as possible with any solid block (slabs & trapdoors work too) does have a big effect on heat loss and overall efficiency, so might be sufficient for your stabilization needs.

**Comment by desht** [comment]
Closing this; the Refinery is OK as it is.  But see #308 for making it clearer about insulating the Refinery.
