### ISSUE TITLE
ZenMethod XPFluid

### ISSUE THREAD

**Issue by Vyraal1** [TeamPneumatic/pnc-repressurized#162]
### Minecraft Version
1.12.2
### Forge Version
2669
### Mod Version
181
### Describe your problem, including steps to reproduce it
What is this for? Is it a legacy zenmethod? Looking around I wasn't able to find a machine that makes use of it.

**Comment by desht** [comment]
Hmm, that's something that needs documenting on https://crafttweaker.readthedocs.io/en/latest/#Mods/PneumaticCraft_Repressurized/

Anyway, the machine in question is the Aerial Interface, which can convert player experience levels to or from XP fluids.  By default it will detect XP juice from Openblocks/EnderIO/Cyclic, Essence of Knowledge from TE, and Mob Essence from Industrial Foregoing.

The CraftTweaker method allows any other fluid to be registered for use with the Aerial Interface with a given fluid->XP ratio; the value represents the amount of player XP that 1mB of the fluid is worth.

**Comment by desht** [comment]
Docs updated now.
