### ISSUE TITLE
Suggestion: PnC Potentiometer

### ISSUE THREAD

**Issue by z64555** [TeamPneumatic/pnc-repressurized#164]
Since several of the pressure tube modules use redstone levels to set the pressure limit (such as the regulator) it would be a good QoL feature to have a potentiometer/rheostat that player can place on or nearby so that they can set the redstone level without needing a clunky chest + comparator.

Currently the only mod that I know of that has this kind of block is Draconic Evolution.

Alternatively, instead of adding a new block, the UI of the modules and other analog RS devices could have a manual setting by right clicking on the block with a wrench to set the desired levels

**Comment by desht** [comment]
The Universal Sensor can actually already do this (define a "Constant" sensor).  The only downside is that it uses a little pressure to run - not much though.  The Universal Sensor can do a lot; it's one of the more underrated machines in PneumaticCraft, IMHO.  Well worth playing with.

Also, if you add an Advanced PCB to your regulator or pressure gauge modules, you have pretty much unlimited control over the pressure->redstone level mapping (the Advanced PCB gives the module a GUI upgrade which allows the mapping to be graphically manipulated).

How does that fit your needs?

**Comment by z64555** [comment]
Ahh, did not know that about either of those.  The Advanced PCB is probably the closest to the desired effect, as its standard GUI mode allows you to directly set the threshold, and the advanced mode opens up some refinement for redstone automation.

The Universal Sensor is also good, but a bit clunky when you just want to set a constant redstone signal, so a potentiometer/rheostat might still be a good addition.

Most of my experience with the mod is from the Project Ozone 2 days, and haven't actually gone through all of the items until now. (actually still in the process of doing this)

**Comment by desht** [comment]
Yeah, constant pressure requirement just for a constant redstone signal does make the US a bit clunky, agreed.  I'd be open to the argument that it shouldn't consume air while running, while needing to be "primed" with enough pressure to start up. i.e. once it has the right pressure (can't remember how much offhand), it can be disconnected from the pressure source.

Note that would only apply to the Constant sensor - other more powerful sensors (e.g. the remote comparator sensor) would still continue to consume a small amount of air.

**Comment by z64555** [comment]
@desht That does seem to be a reasonable exception for the universal sensor, to have a pressure value to generate an RS level, but doesn't consume air.

@MineMaarten The removal of the pressure requirement makes sense on the safety valve, since folks really just want to make sure their machines don't blow up.  If they want to do something more advanced, then they can just install an advanced PCB on it.

The regulator module on the other hand may still want the RS sensitivity, since you can do a lot of things by controlling the pressure level to off-branches of a supply line, or when using a compression chamber as the main air storage. but I dunno. (_shrug_)

**Comment by desht** [comment]
As of v0.6.6 the Universal Sensor can be used as a potentiometer without requiring air (although it does still need to be primed with at least 0.5 bar pressure to run at all).

**Comment by z64555** [comment]
👍
