### ISSUE TITLE
Enderio tanks dont have a GUI 

### ISSUE THREAD

**Issue by coolgaza16** [TeamPneumatic/pnc-repressurized#165]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
when i place my ender fluid tanks and pressurized fluid tanks down when i right click them to open the gui it does not open. 
### Any other comments?
im using the ftb beyond pack and have added Ender IO to it

**Comment by desht** [comment]
I think you may have submitted this issue in the wrong place?  This isn't EnderIO (and FTB Beyond is a 1.10.2 pack...)

**Comment by coolgaza16** [comment]
your right sorry wrong site
