### ISSUE TITLE
Crafting Pneumaticcraft Speed Upgrade Crashes Game

### ISSUE THREAD

**Issue by justinrusso** [TeamPneumatic/pnc-repressurized#167]
### Minecraft Version
1.12.2

### Forge Version
14.23.3.2679

### Mod Version
1.12.2-0.6.4-186

### Describe your problem, including steps to reproduce it
Speed upgrade is crashing when crafting the speed upgrade

### Any other comments?
Reference https://github.com/DarkPacks/SevTech-Ages/issues/2366

**Comment by desht** [comment]
Confirmed.  Careless coding & assuming CoFH core is present, my fault.

**Comment by desht** [comment]
Fixed in 0.6.5 release, just approved on Curseforge (that was fast...)
