### ISSUE TITLE
Pressure Chamber GUI : Enchanted Item texture glitch

### ISSUE THREAD

**Issue by Sewef** [TeamPneumatic/pnc-repressurized#171]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
Minor bug on enchanted item while the pressure chamber gui is opened.

![image](https://user-images.githubusercontent.com/27089398/40011741-fa03598c-57a8-11e8-9b99-efdbdce08dbe.png)
(item on the left)
I'm using default ressource pack and Optifine.
Looks like it's the only interface affected, tested with all the machines I have without problem except Pressure Chamber.

**Comment by desht** [comment]
Well, first question... does it still happen without Optifine installed?

**Comment by desht** [comment]
Actually, never - I see the same thing here without Optifine.  Only happens in the first two slots of the inventory - very strange.

**Comment by desht** [comment]
Something to do with the last side tab (Pressure Chamber Status).  Most likely related to not resetting the GL lighting state properly after drawing the tab's item texture...
