### ISSUE TITLE
Client Crash when Crafting Speed Upgrade from Tinker's Tool Station

### ISSUE THREAD

**Issue by ArsFrags** [TeamPneumatic/pnc-repressurized#172]
### Minecraft Version
1.12
### Forge Version
1.12.2-14.23.3.2679
### Mod Version
0.6.4-186
### Describe your problem, including steps to reproduce it
Attempted to craft "speed upgrade" from a tinker's toolstation
### Links
https://pastebin.com/jxEiD7q7
https://imgur.com/a/ktMJ3xg

**Comment by desht** [comment]
#167
