### ISSUE TITLE
crash when cyclops from ice and fire attempts to bite the head off of a pneumaticcraft turret

### ISSUE THREAD

**Issue by lag42** [TeamPneumatic/pnc-repressurized#173]
### issue on ice and fire's repository here: https://github.com/Alex-the-666/Ice_and_Fire/issues/687
      crash log here: https://paste.dimdev.org/emebiyacez.txt

**Comment by desht** [comment]
See my comments in https://github.com/Alex-the-666/Ice_and_Fire/issues/687
