### ISSUE TITLE
Drone Variable Integration w/ OpenComputers

### ISSUE THREAD

**Issue by SirR3AL** [TeamPneumatic/pnc-repressurized#175]
### Describe your problem, including steps to reproduce it:
Hello so I am trying to program Drones with OpenComputers and I wanted to be able to set and get local and global variables for the Drone using the <prefix>.setVariable() and <prefix>.getVariable() methods. But I am having a hard time in finding out how to actually retieve the varaibles (Global and Local) from the drones. I guess if was looking for an explanation on how to use the two methods properly and if there is any additional setup required for the drone. Here is my test program below, Drone Program, and the error I recieve when I run it:

OpenComputers Program:
![2018-05-23_11 46 56](https://user-images.githubusercontent.com/39563312/40436521-1f258c7e-5e81-11e8-8663-2de2b6c77478.png)

Drone Program:
![2018-05-23_11 46 43](https://user-images.githubusercontent.com/39563312/40436531-25c8df7c-5e81-11e8-8fa2-bd8602389ba5.png)

Result Output:
![2018-05-23_11 47 06](https://user-images.githubusercontent.com/39563312/40436541-2ac804ee-5e81-11e8-92e9-990b6c426aca.png)

### Any other comments:
P.S. - I made a global variable prior named "Test" for the sake of the test program using the /setGlobalVariable command

**Comment by desht** [comment]
I have to admit I'm not really familiar with OpenComputers (and I haven't heavily tested CC/OC integration since porting), but should ``drone.getVariable(#Test)`` read ``drone.getVariable("#Test")`` ?

Probably time for me to learn some OpenComputers...

**Comment by SirR3AL** [comment]
I changed the requested variable as you said to be entered as a string and it gave me the requested results, thanks alot!

**Comment by desht** [comment]
Excellent, closing now.
