### ISSUE TITLE
Pressure "Leakage" inside chamber?

### ISSUE THREAD

**Issue by PaladinWho** [TeamPneumatic/pnc-repressurized#178]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2

### Mod Version
pneumaticcraft-repressurized-1.12.2-0.6.6-192.jar

### Describe your problem, including steps to reproduce it
Having two valves on a pressure chamber can cause a "leakage" of air, even though the air leakage is inside the chamber.
This happened when I had two valves on my chamber and both sides had more pressure than was inside the chamber

EDIT: This may have occurred because my pressure chamber is not entirely in one chunk
(This happened in the All The Mods 3 pack)
![2018-06-13_14 28 36](https://user-images.githubusercontent.com/27911004/41373714-bb7afadc-6f16-11e8-8aee-a48ccb24af20.png)
![2018-06-13_14 28 24](https://user-images.githubusercontent.com/27911004/41373709-b6a149ee-6f16-11e8-898f-845902f441a8.png)
The images don't show it well but both sides have tubes connected

**Comment by desht** [comment]
Yeah, this does have the feel of a cross-chunk problem.  Will try to reproduce this...

**Comment by desht** [comment]
I haven't been able to reproduce this so far; tested with a 4x4x4 chamber with two valves, both valves in different chunks.  I've seen no air leakage on the inside of the chamber (valves will leak outwards if not connected, but that's correct behaviour).

Some screenshots and/or a video would be helpful to fully understand your setup...

**Comment by Sewef** [comment]
Once I got a problem with cross-chunk pressure tubes. In a force-loaded chunk I had 4 Bar, but getting into an unloaded chunk made the pressure goes to 0, like the tube wasn't recognized.

Do you use chunk loaders ? Does they cover the entire pressure chamber ? Which chunk loading mod ? There's some issues with PersistantBits... :l

**Comment by PaladinWho** [comment]
Sorry, I never checked back in on the forum (I fixed the error through chunkloading) and I have screenshots now

**Comment by desht** [comment]
I've had another report of this; it's possible the auxiliary valves don't think they're part of the multiblock on reloading of the world.  The primary valve recognises the auxiliary valves (so the multiblock forms OK), but not vice versa.

**Comment by desht** [comment]
OK, I can reproduce it; it happens on world reload.
