### ISSUE TITLE
CraftTweaker support

### ISSUE THREAD

**Issue by desht** [TeamPneumatic/pnc-repressurized#18]
Following machines' recipes need CraftTweaker support for modifying them:

* Pressure Chamber
* Thermopneumatic Processing Plant
* Assembly controller
* Refinery?

**Comment by Zixxl** [comment]
Supported CraftTweaker commands:

* __Assembly__ - mods.pneumaticcraft.assembly
  * __Laser__
    * `addLaserRecipe(IItemStack input, IItemStack output)`
    * `removeLaserRecipe(IIngredient output)`
    * `removeAllLaserRecipes()`
  * __Drill__
    * `addDrillRecipe(IItemStack input, IItemStack output)`
    * `removeDrillRecipe(IIngredient output)`
    * `removeAllDrillRecipes()`
  * __DrillLaser__
    * `addDrillLaserRecipe(IItemStack input, IItemStack output)`
    * `removeDrillLaserRecipe(IIngredient output)`
    * `removeAllDrillRecipes()`
  * __Common__
    * `removeAllRecipes()`
* __Heat Frame Cooling__ - mods.pneumaticcraft.heatframecooling
  * `addRecipe(IItemStack input, IItemStack output)`
  * `addRecipe(IOreDictEntry input, IItemStack output)`
  * `removeRecipe(IIngredient output)`
  * `removeAllRecipes()`
* __Pressure Chamber__ - mods.pneumaticcraft.pressurechamber
  * `addRecipe(IIngredient[] input, double pressure, IItemStack[] output)`
  * `removeRecipe(IIngredient[] output)`
  * `removeAllRecipes()`
* __Refinery__ - mods.pneumaticcraft.refinery
  * `addRecipe(ILiquidStack input, ILiquidStack[] outputs)`
  * `removeRecipe(IIngredient[] outputs)`
  * `removeRecipes(ILiquidStack input)`
  * `removeAllRecipes()`
* __Thermopneumatic Processing Plant__ - mods.pneumaticcraft.thermopneumaticprocessingplant
  * `addRecipe(IItemStack itemInput, double pressure, double temperature, ILiquidStack output)`
  * `addRecipe(ILiquidStack liquidInput, IItemStack itemInput, double pressure, double temperature, ILiquidStack output)`
  * `removeRecipe(IIngredient output)`
  * `removeAllRecipes()`

**Comment by desht** [comment]
Once PNC:R has its first release (pretty soon!), I'll see if I can get this information into the wiki at https://crafttweaker.readthedocs.io/.

**Comment by desht** [comment]
PR raised at https://github.com/jaredlll08/CraftTweaker-Documentation/pull/27 for docs inclusion.  Waiting on that, then this issue can be closed.

**Comment by desht** [comment]
Docs are now available at http://crafttweaker.readthedocs.io/
