### ISSUE TITLE
Upgradable devices can hold more than the maximum number of upgrades

### ISSUE THREAD

**Issue by wrincewind** [TeamPneumatic/pnc-repressurized#182]
###Minecraft Version
1.12.2

###Forge Version
14.23.3.2676

###Mod Version
1.12.2-0.5.1-163

###Describe your problem, including steps to reproduce it:
In all of the upgradable machines that i've tested (the Oil Pump, Pressure Chamber Interface, Drone, Logistics Drone, Assembly Line And Charging Station), it's possible to put in more upgrades than are allowed. For example I can put in a stack of Speed Upgrades into the Charging Station, though the maximum limit is 10. I haven't checked but I see no reason not to be able to put in 2 stacks - this should probably be checked for as a part of this. 

I also admittedly haven't checked if having additional upgrades has a greater effect on the speed, but i'd be somewhat surprised if it did. I'll check in an hour or two when i get home (assuming I remember to) 

###Any other comments?
some limitations on letting us drop in upgrades might be nice, so we can't put upgrades into devices that aren't compatible with them (e.g. Dispenser Upgrades in Logistics Drones)

Oh, also... thanks for making this mod! You guys rock.

**Comment by desht** [comment]
Closing this very old issue.  Hard upgrade limits have been in place since the 1.14 update.
