### ISSUE TITLE
Computer control puzzle piece not available with only OC installed.

### ISSUE THREAD

**Issue by ruifung** [TeamPneumatic/pnc-repressurized#191]
I'm not sure what OC support is present, but the computer control puzzle piece does not seem to be available when only OpenComputers is installed.

**Comment by desht** [comment]
Hmm, I think I know what might be happening (puzzle piece is getting registered at the wrong time in initialization).

**Comment by desht** [comment]
Can you try build 214+ from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ please?

**Comment by ruifung** [comment]
Confirmed. It shows up properly now.

**Comment by desht** [comment]
Leaving open till  0.6.8 release.

**Comment by desht** [comment]
Fixed in 0.6.8 release
