### ISSUE TITLE
Can't seem to get Heat Frame to work

### ISSUE THREAD

**Issue by pharaun** [TeamPneumatic/pnc-repressurized#192]
### Minecraft Version
- 1.12.2

### Forge Version
- 14.23.3.2702

### Mod Version
- 1.12.2-0.6.7-210

### Describe your problem, including steps to reproduce it
Right clicking any inventory with a heatframe seems to cause a stacktrace: https://gist.github.com/pharaun/4d2b906d18c46e7a4f4feb29aca04a88

**Comment by desht** [comment]
Confirmed.  Looks like an easy fix though.

**Comment by desht** [comment]
Fixed in build 213+ from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/changes

Will be in the 0.6.8 bugfix release out fairly soon

**Comment by desht** [comment]
Fixed in 0.6.8 release

**Comment by pharaun** [comment]
This is confirmed to work, thank you :)
