### ISSUE TITLE
Drones shouldn't permanently remove fluids (?)

### ISSUE THREAD

**Issue by ruifung** [TeamPneumatic/pnc-repressurized#193]
Okay, so I have a undersea dome in a Deep Sea biome where thaumcraft stuff is done. I have a drone that goes out of the dome to kill mobs (taint seeds) that spawn on the exterior of the dome.

However, as the drone moves / teleports through the water, it leaves many many air pockets behind. 
Would it be possible to either restore the removed fluids after leaving or trigger a block update to let the fluids flow back?

Maybe make this optional as I can see some potential uses for the fluid removing function but...
This just results in a lot of ugly air pockets surrounding the dome =).

**Comment by desht** [comment]
Yeah, that sounds pretty reasonable.  Will need to consider how to configure temporary vs permanent fluid removal (most likely with an alternative upgrade in the drone..)

**Comment by desht** [comment]
OK, changed as follows:

* With one Security Upgrade, liquid displacement is now temporary.  Liquids will be restored when the drone moves away (>1 block distance), dies, or changes dimension
* With more than one Security Upgrade, liquid displacement is permanent, like the old behaviour.

This way drones can operate underwater as you want them, but can also be set up to clear liquids (which is still potentially desirable behaviour).

**Comment by desht** [comment]
I can go one better:

* 1 upgrade: swim through liquids, no displacement at all
* 2 upgrades: temporary fluids displacement
* 3+ upgrades: permanent fluid removal (although infinite fluids might flow back later)

Drones still won't enter lava (willingly) regardless of how many security upgrades.

**Comment by desht** [comment]
Fixed in 0.6.8 release
