### ISSUE TITLE
mcmultipart2 support for pressure tubes

### ISSUE THREAD

**Issue by desht** [TeamPneumatic/pnc-repressurized#2]
MCMultiPart2 code is present but currently non-functional.  Pressure pipes will not render as properly connected when mcmultipart is active.

**Comment by desht** [comment]
Spent some time on this today.  This is a huge horrible mess.  I'm pretty sure multipart in general is badly busted at the moment, even outside PNC:R's broken support for the mod, having tested interaction between C&B and Refined Storage in a separate work (you can't put C&B covers in RS cables).

So multipart support for tubes is not happening any time soon.  Life is too short to attempt to debug this.

**Comment by desht** [comment]
Pushing this out to a later date.  MCMP2 won't be in the initial release.

**Comment by Manuepolis23** [comment]
Will be a method to stop 2 tubes connecting?

**Comment by desht** [comment]
I have been thinking about that, yes.  Two things I plan to add:

* A way to camouflage blocks, including tubes.  Similar to EnderIO facades in spirit, but probably using some kind of applicator tool.
* To disconnect two tubes, I'm thinking simply a right-click with the pneumatic wrench on a side to close that side off (or reopen it).

**Comment by desht** [comment]
Dropping the idea of MCMP2 support entirely.
