### ISSUE TITLE
hacked drones shove the player around

### ISSUE THREAD

**Issue by wrincewind** [TeamPneumatic/pnc-repressurized#203]
### Minecraft Version
1.12.2
### Forge Version
14.23.3.2676
### Mod Version
1.12.2-0.5.1-163
### Describe your problem, including steps to reproduce it
If you hack a drone to make it follow you, it will try and occupy the same space as you, continually pushing you around until you tell it to return to its usual programming.

**Comment by desht** [comment]
Fixed in 0.7.0 release
