### ISSUE TITLE
Ability to create pressure chamber recipes requiring negative pressure

### ISSUE THREAD

**Issue by 666lumberjack** [TeamPneumatic/pnc-repressurized#204]
It would be nice to create recipes for the Pressure Chamber in CraftTweaker that only craft under vacuum pressure (for example a replacement for the vanilla chorus fruit -> popped chorus recipe). I think the best way to implement this in the syntax without invalidating existing scripts would be to add an optional/default 5.0 fourth term which defines the maximum pressure for a recipe. That would also allow modpack makers to require say 3-3.5 bar for a recipe if they wanted to require a narrow pressure range but avoid the risk of explosion with pressure requirements close to the maximum.

**Comment by desht** [comment]
Actually, if the pressure supplied in your CraftTweaker recipe is negative, it's already automatically treated as a maximum.  E.g. a pressure of -0.5 will only allow crafting if the pressure chamber's pressure is -0.5 or lower.

Requiring a particular pressure range is something that could be added, but I'm not convinced yet about the usefulness of that...

**Comment by 666lumberjack** [comment]
Ah, I was confused by the fact the recipe in JEI still shows the required pressure as (for example) -0.5-5 bar (for a recipe requiring -0.5 to craft). I presume that's a bug. The recipe works fine when I actually try it, although I did run into an oddity that you may be interested in:
Since pressure chamber valves have a minimum pressure they obviously won't work in a chamber with a vacuum which makes it fiddlier to automate. That's not necessarily an issue that needs to be addressed (in fact, I'd probably leave it as-is if I were you and let modpack makers implementing negative pressure recipes to come up with ways to automate it if necessary) but I thought it was worth mentioning in case you wanted to implement a toggle that makes chamber interfaces run off of vacuum pressure or have them run in reverse or something.

**Comment by desht** [comment]
Yeah, sounds the JEI support needs looking at.

When you say "valves", do you mean the interfaces?  It's true they need pressure, and yeah I quite like the idea of reversing their direction when the pressure is negative (although it may confuse people a bit, it would need to be made clear somehow).  I'll have a think about that anyway.

**Comment by 666lumberjack** [comment]
I do mean interfaces, sorry. On further testing having the interfaces reverse seems like a good idea, because teleporting items inside using the Botania spectranthemum (which was the alternative I had in mind) doesn't work since the items inside the pressure chamber aren't supposed to be actual item entities.

**Comment by desht** [comment]
OK, you'll find the gauge renders a bit better for negative pressure recipes now.

As for the interface, there's no problem here.  Interfaces *do* run with negative pressure, although its pressure will rise (instead of fall) toward 0 when items are inserted/extracted.

**Comment by 666lumberjack** [comment]
Ah, turns out the 'insufficient pressure' error was because the one bar of negative pressure isn't enough to transfer a whole stack. I'll have to remember to make a not of that in the relevant quests so players aren't confused.

**Comment by desht** [comment]
Going to mark this as closed now, I think we're in good shape here?
