### ISSUE TITLE
Crash on Load with new version

### ISSUE THREAD

**Issue by 666lumberjack** [TeamPneumatic/pnc-repressurized#207]
### Minecraft Version
1.12.2
### Forge Version
1.12.2-14.23.4.2729
### Mod Version
1.12.2-0.7.0-228
### Describe your problem, including steps to reproduce it
I'm getting a crash on load with the newest Pneumaticcraft version that seems to be related to the pneumatic armour/helmet. 
### Any other comments?
Crash Log: https://paste.ee/p/yv54J

**Comment by desht** [comment]
Weird. I have tested this outside my dev environment, honest! Anyhow, I'll see if I can get to the bottom of this.

As a quick test, could you try starting an instance with only PNC installed and let me know if it still crashes?

**Comment by MasterEnderman** [comment]
Still crashes with the newest jenkins build.
Crash Report: https://paste.dimdev.org/ikaqaveqoj.mccrash

**Comment by desht** [comment]
OK that's a different issue, and easier to explain at least... Thaumcraft isn't in your instance.  Pushing a fix for that now.

**Comment by MasterEnderman** [comment]
Now it doesn't crash anymore. 👍

**Comment by desht** [comment]
Excellent.  You're running build 230 now I presume?

**Comment by MasterEnderman** [comment]
Exactly.

**Comment by 666lumberjack** [comment]
Can confirm as of build 232 it's fixed for me too

**Comment by desht** [comment]
Fixed in 0.7.1 / 0.7.2 releases
