### ISSUE TITLE
Other Pneumatic Armor pieces

### ISSUE THREAD

**Issue by desht** [TeamPneumatic/pnc-repressurized#21]
This needs some consideration as to what they do, but the first piece is likely to be Pneumatic Boots; they will use stored air pressure to absorb some or all fall damage.  Makes a nice complement to the Air Cannon (in Entity Tracker mode), and the Vortex Cannon.

**Comment by desht** [comment]
Been thinking this over a bit more...

* Pneumatic Boots
    * Fall damage absorption (use a little air, dependent on fall damage taken)
    * Step assist?
    * Pneumatic Kick attack - moderate damage, big knockback for some air usage (target may also take additional fall damage if aimed right).  Bind to a hotkey?  Probably require an upgrade.
* Pneumatic Chestplate
    * *Lots* of air storage capacity
    * Able to charge other armor pieces and items in inventory from its storage (but only up to its pressure, of course)
    * Can take Magnet Upgrade to pull items in (magnet range depends on number of upgrades, respects Botania Solegnolia)
* Pneumatic Leggings
    * Jump boost?
    * Speed boost?  (with speed upgrades, possibly use some air)

Various switchable options would still be configured using the helmet GUI.  No need to add separate GUI's for each armor piece.

Other upgrades:

* Diamond plating - 1 Diamond Block in Assembly Table (laser recipe) makes 4 diamond plating
    * Diamond Plating can be crafted into Armor Upgrade
    * Armor Upgrades add some damage absorption to armor pieces (exact amount TBD.  Maybe 2 or 3 upgrades brings it up to diamond-level protection?)
* Jump Upgrade for Pneumatic Legs
* Kick Upgrade for Pneumatic Boots (see above)

**Comment by PaladinWho** [comment]
maybe add some sort of elytra attachment modification and allow the player to use air pressure to speed themselves up while flying?

**Comment by desht** [comment]
Yeah, flying is something that did occur to me.  Two ways of going about this:

1. Elytra upgrade added to the chestplate could allow gliding (full elytra functionality maybe?)
1. An "air jet" upgrade added to the boots which could provide a fast vertical boost (or horizontal boost when elytra-flying), and allow for slow hover-descent.  Would need to be fairly expensive in terms of air, though.

Option 2 is probably a lot easier to implement.  I recall reading that adding elytra functionality to other armor is extremely difficult due to the way the elytra are coded, but I'll do some investigation.
