### ISSUE TITLE
Performance issues with Liquid Hoppers

### ISSUE THREAD

**Issue by kihira** [TeamPneumatic/pnc-repressurized#210]
### Minecraft Version
1.12.2

### Forge Version
14.23.4.2709

### Mod Version
1.12.2-0.6.7-210

### Describe your problem, including steps to reproduce it
Liquid Hoppers appear to cause quite an FPS drop in certain conditions that I'll try to explain below.
I have been talking to MineMaarten about this a little so he might also be able to provide some insight.

I've been using this mod on Forgecraft (server) and wanted to pull out the fluids from the Refinery and using Liquid Hoppers seemed like the best way. However I've been running into two issues with them, one appears to cause "micro stutters" (20-50ms freezes about every time the Refinery updates) and the other is a massive FPS decrease.

#### Micro Stutters
This appears to be caused by having hoppers feeding into each other. I've tried to reproduce this in a single player world but the issue isn't as noticeable, possibly as there isn't a lot of other stuff around. I have attached a screenshot of the example setup however.
![image](https://user-images.githubusercontent.com/1486841/42470499-ebc54bb2-83ba-11e8-9d9d-fa5c1ef015c1.png)

#### FPS Drops
The next issue (might be related) is more full on FPS drops and it appears to possible be related to the fact that hoppers seem to accept input from their "output" side, almost being able to cause a loop. 
![image](https://user-images.githubusercontent.com/1486841/42470620-5637eb30-83bb-11e8-8fcf-f7bb0afff9b8.png)
In this screenshot I am using TD tubes however the issue can be replicated with any other liquid transport modes. 

### Any other comments?
I've tried this with the latest beta available on CF and the issues still seem to persist.

**Comment by kihira** [comment]
Ah so much better thank you!

I've only been able to test in SP for now but I'll try to get it in for when we next update the server and report if it's fine there too :)

**Comment by desht** [comment]
Good stuff!  BTW v0.7.2 (beta) has just been approved on CF, and it has these changes.

**Comment by kihira** [comment]
We got the latest build on the server but good news and bad news.

Second case with the input/output is good. Not having this issue anymore.

However the first case with liquid hoppers piping into each other seems to almost feel worse now. Before it was micro stutters but now it freezes far more frequently it feels like. It's hard to get a video of it but I can try tomorrow. We've kept it at the default value for syncing stuff and it shouldn't be updating that often (the refinery seems to do its thing about once a second). 

I can ignore that issue as I can now just pipe out all into a IE pipe however it does seem like something is cascading when they pump to each other. I'll try and take a profile of it during it tomorrow and mess around more.

I've also got a crash report for you involving using other mods wrenches on pressure pipes but I didn't have time to upload it. I'll create a new issue for that in about 12 hours though once I can confirm if it is this mod at fault (or even if you support other mods wrenches haha)

**Comment by desht** [comment]
OK. I'll do some profiling myself but I've been having trouble with VisualVM locking up the instance so I'll need to find another profiler.

Regarding modded wrenches, I've had some compat issues in the past... a stack trace will be useful there. Right now a couple of other mods' wrenches are supported (TE & RFTools) but I have been meaning to add more.

**Comment by desht** [comment]
Quick question: is it client side FPS stuttering or server lag that you're seeing?

**Comment by kihira** [comment]
Certainly client side, doesn't seem to be causing any lower TPS but I'll ask if we're noticing a drop. 

And I'll get that stack trace to you tomorrow (need to sleep now) :)

**Comment by desht** [comment]
I think the FPS problem is due to the hopper tanks rapidly switching between empty and not-empty.  While I optimised the case where the fluid level changes by small amount, a switch from empty to not-empty or vice versa counts as a change in the fluid type, which still always causes a sync to the client.  So there are 4 refinery tanks and 4 hoppers spamming the client with fluid tanks sync updates every tick. 

I need to find a way to "smooth over" those very brief switches from empty to not-empty, i.e. if it only spends a tick with fluid in it, avoid sending sync updates.  Will need to have a think about this...

**Comment by kihira** [comment]
Certainly plausible! However shouldn't the tanks also switch rapidly between empty and not-empty when they still transfer to a pipe? It's a rather weird issue and it does almost sound like delayed sync would be the best solution. You could make it so every 10 ticks, it compares it to the last fill value from 10 ticks ago and if it's changed by x amount, send update? I don't think you need to sync the status more then twice a second honestly and players shouldn't notice much of a big difference.

**Comment by desht** [comment]
I made a few more tweaks today and they're available for testing in build 235.  Basically, tanks sync much less often now: every 10 ticks for switching from empty<->not empty, or for large (>1% capacity) fluid level changes, and every 40 ticks for small changes.  This seems to be pretty smooth, but feedback is invited...

**Comment by desht** [comment]
Going to mark this as closed, I think we're in fairly good shape here.  Feel free to reopen if you experience any further performance issues with fluid tank syncing.

**Comment by kihira** [comment]
My apologies for not responding, deadlines at work and tons of stress ^^;;

Yeah, I'll let you know anything else I come across. I think a lot of mods are having similar issues, I notice the same issues with the crafting table from TiCon etc. 

Been having a ton of fun with the mod though, next up is trying to understand how to program drones haha

**Comment by desht** [comment]
I'd recommend viewing MineMaarten's old video series on YT (search "drone programming pneumaticcraft") - although they're for the 1.6/1.7 versions of Pneumaticcraft, the concepts still all apply - drone programming hasn't really changed since then.

**Comment by MineMaarten** [comment]
Or DW's off course :)
