### ISSUE TITLE
Crash from drone (possibly from the Amadron tablet?)

### ISSUE THREAD

**Issue by ResqDiver1317** [TeamPneumatic/pnc-repressurized#212]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Forge Version  1.12.2-14.23.4.2705
SpongeForge Version  1.12.2-2705-7.1.0-BETA-3206

### Describe your problem, including steps to reproduce it

We have what appears to be a rogue drone that is causing crashes. One of our players flew near someone's base and the server crashed. Everytime he logged back in, the server would immediately crash again until I was able to edit his playerdata to have him load in at a diff location.

### Any other comments?

The latest crash report will be attached.
[crash-2018-07-10_02.55.28-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/2178503/crash-2018-07-10_02.55.28-server.txt)

**Comment by desht** [comment]
Found a null ItemStack reference that got missed in porting.  Should be fixed in build 233, will be in the upcoming 0.7.2 release.

**Comment by desht** [comment]
Fixed in 0.7.2 release
