### ISSUE TITLE
Request - Coordinate Piece that contains current location of drone

### ISSUE THREAD

**Issue by Landstryder** [TeamPneumatic/pnc-repressurized#213]
I would really love to have a puzzle piece that I could pull the current location of the drone from. Most likely it would be a coordinate piece that would fit onto a coordinate operator. This would open a ton of possibilities and make it much easier to program mining drones without having to put down a programer and change coordinate pieces every time the site moves.

It would be great too if there was a way to get the coordinate of an entity, making it possible to make a drone that would follow the player for example.

**Comment by desht** [comment]
There are three special (predefined) variables you can use in conjunction with coordinate operations:
* ``$owner`` - coordinates of the drone's owner
* ``$drone`` - the drone
* ``$player=<playername>`` - a specific named player
It should be possible to do what need with that.  Also, a old video of MineMaarten's explains the whole variable and coordinate system really well: https://www.youtube.com/watch?v=FIjEdD_Yj9Y

Let me know if that helps...

**Comment by Tekstack** [comment]
@Landstryder you can assign dynamic variables to achieve what you are looking for already. You can see my response to https://github.com/TeamPneumatic/pnc-repressurized/issues/190 Issue #190
