### ISSUE TITLE
Suggestion: give drones the ability to have Magnet upgrades 

### ISSUE THREAD

**Issue by wrincewind** [TeamPneumatic/pnc-repressurized#218]
I think this would be nice when combined with the 'pick up items / fluids in an area' puzzle pieces, to let the drone grab items from a distance away. It'd help with pathfinding, speeding them up when they need to grab a bunch of items at once from an area, and it'd allow me to finally have a semi-effective drone-based nether pump. What do you think?

**Comment by desht** [comment]
Drones can already take magnet upgrades :)

**Comment by wrincewind** [comment]
Welp, that's what I get for thinking up cool ideas without testing them. :p oh well, excitement! Can't wait to give it a go.
