### ISSUE TITLE
Hopper Ticking Block Entity with an Aerial Interface

### ISSUE THREAD

**Issue by PokeMaserJ** [TeamPneumatic/pnc-repressurized#219]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14,23,4.2739
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.7.3-239
### Describe your problem, including steps to reproduce it
Crash to desktop when putting an Aerial Interface on top of a hopper
Get an Aerial Interface
put it on top of a hopper
crash
https://pastebin.com/64EfZNps
### Any other comments?
Not sure if this effects SMP, I did this on SSP.

**Comment by desht** [comment]
Confirmed.  Easy fix though.

**Comment by desht** [comment]
Fixed in 0.7.4

**Comment by PokeMaserJ** [comment]
I can confirm that it does indeed work!
