### ISSUE TITLE
Drones Not Exporting Items

### ISSUE THREAD

**Issue by gudenau** [TeamPneumatic/pnc-repressurized#220]
### Minecraft Version
1.12.2

### Forge Version
14.23.4.2739

### Mod Version
1.12.2-0.7.3-239

### Describe your problem, including steps to reproduce it
I tried a few different things:

1. Program drone to pick up an item
2. Program drone to export item into an area with only a drawer

1. Program drone to pick up an item
2. Program drone to export item into an area with only a chest

1. Tell drone to pick up an item
2. Tell drone to export item into an area with only a drawer

1. Tell drone to pick up an item
2. Tell drone to export item into an area with only a chest

None of these worked, while the drone was rendering with an item in it's "hand".

### Any other comments?

This is on a server, the drawers are from "Storage Drawers" and I am using Open Computers to "tell" the drones what to do.

**Comment by desht** [comment]
Please post the program you used for the drone. You can export the program to Pastebin via the programmer GUI and then paste the link here.

**Comment by wrincewind** [comment]
I will say that i've got drones happily picking up items, moving them around and storing them - both in storage drawers' Drawer Controllers and also into Ender Chests. I have noticed the occasional rendering bug where a drone appears to be holding an item after it's stored it or used it, but it wasn't easily reproduced so i decided to just leave it be.

**Comment by gudenau** [comment]
At the moment my program is just this:
```
{
  "widgets": {
    "type": 9,
    "value": [
      {
        "name": {
          "type": 8,
          "value": "start"
        },
        "x": {
          "type": 3,
          "value": -40.0
        },
        "y": {
          "type": 3,
          "value": -20.0
        }
      },
      {
        "name": {
          "type": 8,
          "value": "computerCraft"
        },
        "x": {
          "type": 3,
          "value": -40.0
        },
        "y": {
          "type": 3,
          "value": -9.0
        }
      },
      {
        "coord1Variable": {
          "type": 8,
          "value": ""
        },
        "boxType": {
          "type": 1,
          "value": 0.0
        },
        "type": {
          "type": 8,
          "value": "box"
        },
        "z1": {
          "type": 3,
          "value": 162.0
        },
        "name": {
          "type": 8,
          "value": "area"
        },
        "x": {
          "type": 3,
          "value": -25.0
        },
        "y1": {
          "type": 3,
          "value": 53.0
        },
        "z2": {
          "type": 3,
          "value": 162.0
        },
        "y": {
          "type": 3,
          "value": -9.0
        },
        "x1": {
          "type": 3,
          "value": -176.0
        },
        "y2": {
          "type": 3,
          "value": 53.0
        },
        "coord2Variable": {
          "type": 8,
          "value": ""
        },
        "x2": {
          "type": 3,
          "value": -176.0
        }
      }
    ]
  }
}
```

With a computer telling it to do stuff.
```
drone=components.droneInterface
drone.clearArea()
drone.addArea(-176,58,160)
drone.setAction("inventoryExport")
```
With an item in it's "hand" from `drone.setAction("pickupItem")`.

**Comment by Sewef** [comment]
Haha, I just did a CC program yesterday for a drone :D 

add
`while not droneInterface.isActionDone() do os.sleep(1) end`
after drone.setAction("inventoryExport")

**Comment by gudenau** [comment]
It does exit, and the drone just sits there as before.

Am I missing something stupid?

**Comment by gudenau** [comment]
Okay, that is odd. The pieces are working now and the computer is not. Whatever, guess it works now.

**Comment by desht** [comment]
Github autoclosed this one but I do intend to investigate further. Also gives me a chance to learn Open Computers :p
