### ISSUE TITLE
Amadron tablet causing crash-to-desktop on creating a new trade

### ISSUE THREAD

**Issue by wrincewind** [TeamPneumatic/pnc-repressurized#222]
### Minecraft Version
1.12.2
### Forge Version
14.23.4.2705
### Mod Version
1.12.2-0.6.8-219
### Describe your problem, including steps to reproduce it
When trying to set up a basic trade using the amadron tablet, the world will run fine for about 20 seconds before hard-crashing. Any attempts to load up this level will crash to desktop. Servers will refuse to boot. (thank god for aroma backup!)

Steps to reproduce: 
I've boiled this down to the very basics. This works in an otherwise vanilla instance with no other mods. 

1) shift+rightclick an amadron tablet onto a chest (or other container)
2) put emerald ore and emerald blocks into said chest.
3) Have emerald ore and emerald blocks in your inventory
4) open up your amadron tablet. Set up a trade - one block of emerald for one emerald ore. I don't think the items or the positioning matter much.

Leave the 'input/output chest' settings at default (i.e. the chest you selected earlier'
finalise the trade. 

Wait about a minute and, bomf, crash. 
https://paste.ee/p/6ocpy Here's a crashlog. 
The relevant line seems to be: 
"An Entity type me.desht.pneumaticcraft.common.entity.living.EntityDrone has thrown an exception trying to write state. It will not persist. Report this to the mod author"
and more specifically "Null string not allowed"

### Any other comments?
after a little more fiddling, I found out that deleting the config file AmadronOffersStatic.cfg and allowing it to regenerate will let you get back into the world. 

In my tests I was always playing in creative mode, and on the server I was an OP/admin so i don't know if that affects things. 

Incidentally, is there a way to put new trades into the AmadronOffersStatic.cfg file in-game, while the world is running? It'd certainly be nicer than fiddling with JSON.

**Comment by desht** [comment]
That's already fixed in 0.7.2.

**Comment by desht** [comment]
Regarding adding trades in-game, as it happens that's exactly what I'm working on right now. The latest dev release on jenkins allows new periodic offers to be added, and adding new static offers will be coming next. Removing those offers will still need to be done via file editing, for now at least
