### ISSUE TITLE
[Suggestion/Request] Heat Source Rate of Consumption Config

### ISSUE THREAD

**Issue by Boolyman** [TeamPneumatic/pnc-repressurized#223]
Would like to make a small suggestion.  Is it possible have a config option that controls how quickly liquid heat sources are exhausted when they are  used to heat things like the refinery?  Placing down a source block of something like Blazing Pyrotheum, it's consumed in literally 6 seconds.

**Comment by Sewef** [comment]
Related suggestion : why not adding Magma Block as a Heat source?

**Comment by desht** [comment]
Yes, Magma block should be added.

Regarding heat transfer rates, I do want to look at this more closely once I've finished with Amadron.  @Boolyman Are you suggesting that the block should contain more heat overall, or should simply transfer its heat more slowly (so need replacing less often) ?

**Comment by desht** [comment]
Just to note, although Pyrotheum is consumed super-fast, it does transfer all its heat into the refinery almost instantly, getting it to max temperature.  One bucket of pyro can refine 240mB diesel and 170mB LPG (in a two-block refinery).

**Comment by desht** [comment]
I've made the thermal resistance for non-vanilla fluids configurable, via the ``D:fluidThermalResistance`` config value.  Raising that will make heat flow more slowly between fluids and blocks like the refinery.  Note that it affects all fluids; it can't be set on per-fluid basis.  And it doesn't affect the total amount of heat in a block of pyrotheum, just how fast it transfers.

**Comment by desht** [comment]
Fixed I  0.7.4

**Comment by Boolyman** [comment]
Sorry I did not check back on this sooner.  But you nailed it perfectly... the rate of transfer is really all that I propose need configuration.  Thanks for the quick response!
