### ISSUE TITLE
ComputerCraft suggestion : add string getDroneName() & string getOwnerName()

### ISSUE THREAD

**Issue by Sewef** [TeamPneumatic/pnc-repressurized#224]
Hi there,
I was building a doc ([link, if someone want...](https://docs.google.com/spreadsheets/d/1XPk3cyjXmTwLOWTo8Ytw3_BHYGRjiwM4y12sa4Osf1k/edit?usp=sharing)) and something is wrong imo : 
- We have setRenameString(string name) but we don't have a getDroneName(string name) function. That's not consistent with other get/set functions
- The method that adds setBlockOrder(<closest/highToLow/lowToHigh>) converts the argument into string. Why don't we have setBlockOrder(string <"closest"/"highToLow"/"lowToHigh">) instead? Again, it would be consistent with setOperator(string <"="/">=">)

**Comment by Sewef** [comment]
(`string getOwner()` would be cool too)

I'll try today, but according to the code it converts the argument into string anyway. It's not very fancy, imo, as it suggests you can send something else. I'd use `args[0]` instead of declaring `string arg` and let [the no valid order exception](https://github.com/TeamPneumatic/pnc-repressurized/blob/a05133fbc27c06d75ad1ef679a3d6c9cc8f8a03b/src/main/java/me/desht/pneumaticcraft/common/thirdparty/computercraft/TileEntityDroneInterface.java#L177) works, or something like that

**Comment by Sewef** [comment]
Back from testing!
Well, everything is right : it does accept strings only.
![image](https://user-images.githubusercontent.com/27089398/43149679-5ac380ac-8f68-11e8-9ae0-6a411487fba8.png)

So, documentations need a fix [here](https://github.com/TeamPneumatic/pnc-repressurized/blob/a05133fbc27c06d75ad1ef679a3d6c9cc8f8a03b/src/main/resources/assets/pneumaticcraft/wiki/en_us/block/drone_interface.txt#L19) : 
From
`[prefix{l}]setBlockOrder(<closest/highToLow/lowToHigh>) [prefix{}] `
To
`[prefix{l}]setBlockOrder(<"closest"/"highToLow"/"lowToHigh">) [prefix{}] `
😃

**Comment by desht** [comment]
Cool, that's an easy change then :)

**Comment by desht** [comment]
Fixed in 0.7.4
