### ISSUE TITLE
Can't craft Gun_Ammo

### ISSUE THREAD

**Issue by Sewef** [TeamPneumatic/pnc-repressurized#226]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
Someone got the issue [here](https://forum.feed-the-beast.com/threads/pneumaticcraft-minigun-and-ammo.285676/).
Gun Ammo are uncraftable., even if they appeared in JEI and the crafting book.
![image](https://user-images.githubusercontent.com/27089398/43148710-28113548-8f66-11e8-80f9-809e7382f249.png)

**Comment by Sewef** [comment]
Well, didn't want to update because of the crash when Thaumcraft weren't installed, then I forgot to XD

**Comment by desht** [comment]
Yeah, the Thaumcraft crash is sorted.  0.7.3 is pretty stable, but 0.7.4 will add some more cool stuff, especially around the Amadron system :)

**Comment by Sewef** [comment]
Oooh, stop it, you
Yesterday I made a complete waypoint system to get transported by drone using computercraft, sooooo good. I love your mod so much ^_^

**Comment by Shybella** [comment]
Thanks, I was about to open a issue on this. Thanks for the hard work on the mod

**Comment by desht** [comment]
Gun ammo craftable now, and as a bonus I've also added splash & lingering potion craftability (although the ammo cost for those is higher - 3x for splash and 6x for lingering).

**Comment by desht** [comment]
Fixed in 0.7.4
