### ISSUE TITLE
[1.12] Crash with Penumatic Dynamo

### ISSUE THREAD

**Issue by MasterEnderman** [TeamPneumatic/pnc-repressurized#229]
### Minecraft Version
1.12.2
### Forge Version
14.23.4.2739
### Mod Version
0.7.4-245
### Describe your problem, including steps to reproduce it
1. place down a pneumatic dynamo
2. open the GUI of it
3. click on the "output" tab
4. the game 'crashes' back to the main menu (actually the mulriplayer page. even when tested in single player)
### Any other comments?
Console Message: https://pastebin.com/hFWg5bFW

**Comment by desht** [comment]
That stacktrace isn't related to the dynamo in any way.  I think it's pure coincidence that you kicked at that point.

**Comment by desht** [comment]
Having said that, I don't see how this crash could have occurred.  ``FMLOutboundHandler$OutboundTarget$7.validateArgs`` complains that the passed argument isn't a ``TargetPoint``, but that's exactly what we pass in ``NetworkHandler.sendToAllAround``.

Does this happen reproducibly, or was it a one-off?

**Comment by desht** [comment]
OK closing. Feel free to reopen if it reoccurs.
