### ISSUE TITLE
Amadron Drone crashes world on spawn when setting up player trades

### ISSUE THREAD

**Issue by Shadowfire86** [TeamPneumatic/pnc-repressurized#231]
### Describe your problem, including steps to reproduce it: I am currently trying to set up a Trade using an Ender Chest (Not Vanilla, the kind with the three dot color code) for a stack of sugarcane for a Diamond via the Amadron tablet. When the drone spawns, the game crashes. 
[crash-2018-07-25_10.38.46-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/2229150/crash-2018-07-25_10.38.46-server.txt)

**Comment by desht** [comment]
Fixed in 0.7.2.

**Comment by Shadowfire86** [comment]
Copy. Thank you. I'll talk to the players and see if they're okay with manually updating past the pack's version

**Comment by desht** [comment]
Yeah 0.7.4 should work fine in DW20.
