### ISSUE TITLE
Multiple players on Opened to LAN singleplayer world. Other Players have 0/0 Available Trades and Cannot see trades

### ISSUE THREAD

**Issue by Shadowfire86** [TeamPneumatic/pnc-repressurized#232]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Mod Version  7.4-245

###I can share trades and it shows me having 2/50 available. Other player can't see my trades and when looking at the make trade tab it says 0/0 available trades.

**Comment by desht** [comment]
Should be fixed in build 246 from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/, can you try that please?

**Comment by Shadowfire86** [comment]
Can't do that just yet. Running as a server for a few people through the Twitch Launcher. Will give it a shot once it hits the launcher.

**Comment by desht** [comment]
OK. I will likely have to push another change to fully sort out trade syncing for 'open to lan' servers which I'll hopefully do today.

**Comment by desht** [comment]
0.7.5 has been released, should fix the problem.
