### ISSUE TITLE
Bright heat frame in darkness

### ISSUE THREAD

**Issue by masterbobli** [TeamPneumatic/pnc-repressurized#233]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
Create a new world and make sure there is little light
Place a chest and put a heat frame on it
Heat frame looks very bright
![2018-07-27_06 37 06](https://user-images.githubusercontent.com/37212918/43293202-89d86628-916b-11e8-9a20-6e9d6c762bff.png)

**Comment by desht** [comment]
Looks like a missing GL lighting call. Shouldn't be too hard to sort out.

**Comment by desht** [comment]
Fixed in 0.7.6 release
