### ISSUE TITLE
Crash Shortly after Server Startup Due To ConcurrentModificationException on a HashMap

### ISSUE THREAD

**Issue by john01dav** [TeamPneumatic/pnc-repressurized#234]
### Minecraft Version
1.12.2

### Forge Version
1.12.2-14.23.4.2709-universal

### Mod Version
0.6.8-219 (Direwolf20 1.12 pack)

### Describe your problem, including steps to reproduce it
This crash occurred on a public server running the Direwolf20 1.12 pack. The crash log is [here](https://paste.ubuntu.com/p/tcjs6HVsKZ/). After talking to the players who were online at the time of the crash, the only lead is this quote from a player "of note, there is an issue on the pneumaticraft github about shulkers and a helmet. No response yet, but I did JUST leave the end fighting a bunch of shulkers prior to the restart. May have picked up a helmet, but no idea
"

### Any other comments?
The map file is available to a confirmed developer of Pneumaticraft, as long as they agree to not distribute it outside of the Pneumaticraft developers.

**Comment by desht** [comment]
Just to note this is certainly not shulker related - that issue is just a reminder to add shulker hacking at some point in the future.

**Comment by desht** [comment]
Closing since this is in the 0.7.6 release.  Please reopen if the problem reoccurs.

**Comment by Mekadrom** [comment]
Hello, a server I'm playing is currently in a crash-on-startup loop due to a very similar exception arising from the same area in the code.

Here is the stacktrace: [https://pastebin.com/WjgZ1Z1m](https://pastebin.com/WjgZ1Z1m)

If this is found to be the same problem, can I re-open this?
