### ISSUE TITLE
Negative air volume can be created

### ISSUE THREAD

**Issue by masterbobli** [TeamPneumatic/pnc-repressurized#235]
### Describe your problem, including steps to reproduce it
Build a pressure chamber
Place a vacuum pump next to the pressure chamber valve with the negative side pointing to it
Place a creative compressor and set its pressure to 5 bar
Put 10 speed upgrades in the vacuum pump and wait for a few seconds
Not only the pressure chamber have negative air volume
![2018-07-29_18 17 09](https://user-images.githubusercontent.com/37212918/43373139-4472bea0-93da-11e8-97b4-1cae118ec36e.png)
but also the vacuum pump
![2018-07-30_09 24 28](https://user-images.githubusercontent.com/37212918/43373148-5fa78e80-93da-11e8-86c1-b252b7f65e23.png)

### Any other comments?

**Comment by desht** [comment]
Yeah looks a bit derpy but it shouldn't be anything more than a cosmetic problem. Will get it sorted for the next release though.

**Comment by desht** [comment]
Fixed in 0.7.6 release
