### ISSUE TITLE
Crop Support Dimension Rendering Leak?

### ISSUE THREAD

**Issue by artdude543** [TeamPneumatic/pnc-repressurized#236]
### Minecraft Version
`1.12.2`
### Forge Version
`14.23.4.2707`
### Mod Version
`0.6.6-192`
### Describe your problem, including steps to reproduce it
_SevTech: Ages Report_

Got a report from GennyB who was streaming last night, messing around in dimensions and he found this situation: https://clips.twitch.tv/BigAgileSalamanderSoonerLater seems like the rendering is leaking? I've seen a similar bug in another mod ages ago. But the cause was never found.

This could be caused from another mod in the pack. But I can't put a finger on a mod but could be someone not completing their render and it's leaking over the place. This could of been noticed/fixed in newer builds. But I don't see any commits in regards. I don't have any logs from his session as he crashed and had to restart (as was streaming) but I can get his latest ones if that may help somewhat.

If you need more info or what not; ask away! 🙂

**Comment by desht** [comment]
I think i might know what's causing this, but it will be a few days before I can actually do some testing...

**Comment by desht** [comment]
Can you please try out PNC build 251 and let me know if it helps at all? I have not been able to reproduce this issue myself, but this build may help.  Should work fine with the current SevTech, but I'd advise trying it on it a copy of your world (PNC 0.7.x adds a few new items).

**Comment by artdude543** [comment]
Sure can do! Currently, we have people playing the beta update. So I can drop this build in and get them to test. Will also get Genny the build as he had the issue and knows where to find it in his world again :)

**Comment by artdude543** [comment]
Yep looks good. Could not reproduce the issue anymore. From a world, I had the render leak ^_^ Thanks for the fix! ❤️

**Comment by desht** [comment]
Excellent.  The fix is in 0.7.6 which has been released.  Closing this now..
