### ISSUE TITLE
JEI : Weird frame for Explosion Crafting

### ISSUE THREAD

**Issue by Sewef** [TeamPneumatic/pnc-repressurized#237]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it

![image](https://user-images.githubusercontent.com/27089398/43801438-661be60c-9a93-11e8-807c-8e4ebbe70205.png)
The frame looks wrong sized/positionned, bug or intended ?

**Comment by desht** [comment]
Yeah, that's a cosmetic bug.  Shouldn't be hard to fix...

**Comment by desht** [comment]
Hmm.  Just went to test this, and it's fine here...
![2018-08-08_17 01 41](https://user-images.githubusercontent.com/736831/43849231-e2ae3f82-9b2c-11e8-9a9e-5c85ae53d24e.png)

**Comment by Sewef** [comment]
Ahem. Strange.
Can you try with JustEnoughRessources installed? That's my only JEI addon... I don't have any other idea

**Comment by desht** [comment]
Nope, tried with JER as well, no difference.  Not sure what else to say, really...

I'll leave this open for now, maybe I'll track it down :)

**Comment by desht** [comment]
What version of JEI are you using?  I'm testing with 4.8.5.159 here.

**Comment by Sewef** [comment]
I'm using jei_1.12.2-4.11.0.202

**Comment by desht** [comment]
I'll test with that when I get a chance, thanks.

**Comment by desht** [comment]
Yep, was the JEI version.  Build 252 fixes the problem.

**Comment by desht** [comment]
Fixed in 0.7.6 release
