### ISSUE TITLE
Game crashes after drone removed 1 block while running a "dig program"

### ISSUE THREAD

**Issue by gamelnderGamler** [TeamPneumatic/pnc-repressurized#240]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
forge-14.23.4.2729
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.7.5-248
### Describe your problem, including steps to reproduce it
Hello,
i have again a problem with drones which should dig stuff. Hope this time it isn´t only on my server ;-)

I have a "dig program" (https://pastebin.com/86TBmGeR) to dig one block dirt. The drone flys there and starts diging the one block dirt. After it is finished (the sound of a broken block apears normaly), the block is still there and the game crashes. 
If i restart the game/server, the block is removed.

I get the feeling, that drones just dont want to dig stuff for me :-(

### Any other comments?
This is the crash report:
[crash-2018-08-12_17.31.01-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/2281075/crash-2018-08-12_17.31.01-server.txt)

**Comment by desht** [comment]
This is a bug in Inventory Pets, not PneumaticCraft.

That mod's HarvestHandler class is making incorrect assumptions about the size of the player's inventory (assuming it has at least 9 slots), which is not necessarily true for a drone's fake player (only 1 slot by default).  They should be checking the player's inventory size before iterating over it.

As a workaround, adding 8 dispenser upgrades to your drone will probably get round the problem, but you should report this to the Inventory Pets maintainer.

**Comment by desht** [comment]
No worries.  I never did get to the bottom of why your drone was vanishing, but I'll close that now.  Can always reopen if it happens again.
