### ISSUE TITLE
Minigun raytrace crash (doesn't actually crash)

### ISSUE THREAD

**Issue by BrisingrAerowing** [TeamPneumatic/pnc-repressurized#241]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version

1.12.2

### Forge Version

2745

### Mod Version

0.7.5-248

### Describe your problem, including steps to reproduce it

Get a minigun and ammo
Aim the minigun
Fire the minigun

The crash report will be written to the logs (but the game doesn't actually crash).

### Any other comments?

[Crash Log](https://paste.dimdev.org/ijevekezov.mccrash)

Noticed thanks to VanillaFix.

**Comment by desht** [comment]
Fixed in 0.7.6 release
