### ISSUE TITLE
Handheld Minigun seems to do no damage

### ISSUE THREAD

**Issue by erindalc** [TeamPneumatic/pnc-repressurized#243]
Minecraft: 1.12.2
Forge: 14.23.4.2756
Mod Version: 0.7.7-255

### Describe your problem, including steps to reproduce it
 I crafted a minigun, both instant damage and normal bullets seemed ineffective against both living and (un)dead targets.

### Any other comments?
I don't think I have conflicting mods (tbh I don't know what would possibly conflict with this), but I'll upload a curse export upon request.

**Comment by desht** [comment]
I think I might need to see your mod list, since I haven't been able to reproduce this...

**Comment by erindalc** [comment]
[Minigun Bug-1.0.zip](https://github.com/TeamPneumatic/pnc-repressurized/files/2303541/Minigun.Bug-1.0.zip)

**Comment by desht** [comment]
Well I've spent some time on this (dev instance and on a SMP server) and can't reproduce it at all.  I can't see any mods in your list which would cancel that damage either....

**Comment by erindalc** [comment]
I'll try and isolate the cause on my end and get back to you.

**Comment by erindalc** [comment]
And of course, now I can't reproduce it in my world either. If I can consistently reproduce it I'll reopen this.

**Comment by erindalc** [comment]
I'm pretty sure it was a combination of lag, tall grass, and the fact that spiders are immune to instant harm damage.

**Comment by desht** [comment]
Yeah that would do it (though I didn't know spiders were immune to instant harm, TIL).

Tall grass is an annoyance; I might see if I can have the minigun ignore that when tracing targets.
