### ISSUE TITLE
Amadron Tablet Not Working In Multiplayer

### ISSUE THREAD

**Issue by ChosenArchitect** [TeamPneumatic/pnc-repressurized#245]
### Tested on FTBs servers using the FTB Pyramid Reborn (Dev) Test Pack.
![2018-08-24_04 27 32](https://user-images.githubusercontent.com/35053440/44577228-24217a80-a756-11e8-8914-58efeec2f163.png)

**Comment by desht** [comment]
Yeah, I discovered this myself a few days ago. It's actually fixed in dev already, but not released yet - hopefully on the next day or so.

If you want to try a dev release in the meantime , http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ build 257 should work.

**Comment by 016Nojr** [comment]
Hey @desht, I see you wanted to release it a couple days ago, I dont see a build on Curse, are you able to publish 258 to Curse?

**Comment by desht** [comment]
A release will be coming in the next 24 hours or so.

**Comment by desht** [comment]
0.7.8 is out now, should fix the problem. Closing this now, please reopen if problems persist.
