### ISSUE TITLE
Suggestion - Filter Metadata/Health values on Logistics Frames

### ISSUE THREAD

**Issue by Seaniau** [TeamPneumatic/pnc-repressurized#246]
At the moment, as an example; If i put a Requester frame on a Sentry Turret to ensure the turret always has ammo, the second a bullet is fired, the drone brings a new ammo pouch to the turret, because it is requesting Ammo with 1000 bullets.

The ability to ignore Metadata/health values in Logistics frames would be useful.

**Comment by desht** [comment]
Yeah sounds reasonable. I'll look into it.

**Comment by desht** [comment]
Added in 0.8.0 release
