### ISSUE TITLE
Drones from tablet orders appear in the distance but do not move.

### ISSUE THREAD

**Issue by ResqDiver1317** [TeamPneumatic/pnc-repressurized#247]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

1.12.2 Minecraft Version

1.12.2-14.23.4.2745 Forge Version
1.12.2-2705-7.1.0-BETA-3328 SpongeForge Version (not sure if this makes any difference but figured I'd add it to be safe)

1.12.2-0.7.8-259 Mod Version

### Describe your problem, including steps to reproduce it
We updated last night to the latest version and this morning when one of our players tried using the Amadron tablet to order something, he reported it was not working. I went and looked and apparently, he made several attempts before saying something as there was roughly 15 drones all positioned a little ways away from his base, not moving. I destroyed the drones and took his tablet and tried it myself, and a new drone appeared out where the others had been, but again, it just sat there not moving. 

I tried one more time while watching our console to see if any errors were being reported and nothing showed up in it, but again, a drone appeared and just sat there.

1st pic is just the field of drones. 2nd pic is the drone that appeared when I tried it. Right on top of the "n" in Amadron is the chest the drone should be accessing.

![2018-09-04_10 06 22](https://user-images.githubusercontent.com/18246580/45040638-17413880-b02c-11e8-9176-0f7a61828f0a.png)
![2018-09-04_10 11 36](https://user-images.githubusercontent.com/18246580/45040644-1a3c2900-b02c-11e8-8584-43dae981e681.png)

**Comment by desht** [comment]
This could be "fun" to track down...

* What version did you upgrade from?
* Did everything work fine in that version?
* Did you add any other mods?
* I presume you haven't changed any mod config (in particular the ``B:stopDroneAi`` setting) ?
* Have other players (in different parts of the world) had the same problem?

**Comment by ResqDiver1317** [comment]
Upgraded from 0.6.8.219.
As far as I know, the drones worked, or at least nobody had said anything about them not working until this morning. I have put a message out to our players to see for sure. We were having MAJOR TPS issues related to pressure chambers and the charging station. I did not file an issue with you on that though as I knew we were behind on versions and I hate filing issues if we are not up to date. 
No other mods have been changed/updated at this time.

Oh hell. yep. I was working my way down your list of questions and answering each one individually and sure enough, we do have have the stopDroneAI set to true. We did that to keep people from using drones for other tasks. This particular server is designed to focus on building with very little to no tech/automation options. Is there a way to allow the Amadron Delivery Drones to function without allowing players to be able to use drones for other tasks? My alternative is to just setup a trading market where the players can just do trades with the server instead of actually using the tablet, but I would rather keep the tablet/delivery drone working if possible.

**Comment by desht** [comment]
Well, the good news is that TPS issues for the pressure chamber and charging station should be pretty much resolved in the new version; I found and fixed a couple of major performance issues there a few releases ago.

``stopDroneAi`` is really intended to prevent all drones running, generally only to be used if there's a bug in the AI code which is causing server crashes.  I think a better solution might be to use CraftTweaker to disable the crafting of drones and/or the Programmer, although I appreciate that wouldn't stop existing drones from running.

I could add another configurable which prevents drone entities other than the Amadron drones from being spawned, I guess...

**Comment by ResqDiver1317** [comment]
A config option would be great, but I can def do the crafttweaker method (I just hate how we can't edit recipes on the fly with 1.12.2 like we could on older MC versions). I only know of a couple players that had the drones and programmers setup prior to me blocking the AI function and both of those players will gladly not use them if I ask. 

And definitely glad to hear about the TPS issues being resolved. Most of our players just want to build stuff on this server, but some get tired of building so they want to dig into the mods. The TPS issues came up big last night when one of our players decided to get into PC as part of a "factory" he was making and when he got his chambers and charging station all up and running, the TPS dropped out and kept freezing the server, hence why we updated last night.

I'll go ahead and re-enable the DroneAI and disable the programmer and such via CraftTweaker so we can get this going again. I have 2 or 3 people ready to get into PC and they all want the blueprint so they can get their UV Boxes going :)

Thanks for your help!!!

**Comment by desht** [comment]
Keeping this open for now while I decide on the best way of disabling drones via config.  This may form part of a more general feature-control section in the mod config.

**Comment by desht** [comment]
It occurs to me that there may be a better way to handle this: using Forge permissions.

By requiring a player to have a specific permission node, use of drones can be enabled or disabled.  Nodes can be registered to require a player to be an op to have the node, or you can install a permissions mod to grant specific permissions to specific players.

This feels like a better way of controlling access to mod features than a blanket enable/disable.

**Comment by TheNamesJosh** [comment]
Have this same exact issue on a server I'm on.. 1.20.1 game version. They sit still in the air.

**Comment by desht** [comment]
This post is 6 years old!  Please don't necro issues like this.  Separate issue please, with full details of your instance, including any "optimisation" mods.
