### ISSUE TITLE
[Suggestion] Add crafttweaker handler for explosion crafting

### ISSUE THREAD

**Issue by wormzjl** [TeamPneumatic/pnc-repressurized#252]
~~Because explosion is cool~~

Actually I wanted to make compressed iron from steel instead of iron, but currently with the config I can only remove the explosive recipe.
A customize-able explosive crafting recipe handler will be a great tool for pack makers.

**Comment by desht** [comment]
Covered by #108.  Closing this as duplicate, but thanks for the reminder - I'll see if I can get this added for the next release.
