### ISSUE TITLE
Problem creating Lubricant

### ISSUE THREAD

**Issue by krismoellegaard** [TeamPneumatic/pnc-repressurized#253]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

**Comment by desht** [comment]
I presume you mean the Thermopneumatic Processing Plant rather than the Refinery (the TPP makes Lubricant from Diesel & Redstone).

Solution is just to keep the TPP stocked with Redstone.  That's all.

**Comment by krismoellegaard** [comment]
thangs tha woorked :-)

**Comment by desht** [comment]
OK, good to hear.  Closing this now.
