### ISSUE TITLE
Crash upon using the armor's config GUI

### ISSUE THREAD

**Issue by Famous5000** [TeamPneumatic/pnc-repressurized#254]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.4.2760
### Mod Version
1.12.2-0.7.8-259
### Describe your problem, including steps to reproduce it
Upon pressing U [the key bound to this mod's armor config screen], the game would violently crash had VanillaFix not been installed.

If it helps, my armor is mostly discharged, and I only equipped my helmet as per this screenshot: https://i.imgur.com/i18vg5L.png
### Any other comments?
Here's the crash report generated by VanillaFix... https://paste.dimdev.org/tejocehohe.mccrash

**Comment by Famous5000** [comment]
It appears to be happening whenever I hit the key at all... I'm going to see if it's conflicting with JEI by changing the keybind, I'll edit this comment when I get more info.

**Comment by desht** [comment]
I can't reproduce this, although I can probably add a bit of code to prevent the crash (it's reaching a point which shouldn't be reachable, where the gui init code thinks there are no upgrades to add handlers for, which does not appear to be the case).

I'll do some more investigation, but a couple of questions:

* Does this crash happen every time?  Has it ever worked?  I ask because the durability bar on your helmet (207/264) suggests the helmet is not new.
* Were you wearing any of the other pneumatic armor pieces at the time?  If so, which (and which upgrades where installed) ?

**Comment by Famous5000** [comment]
Upon the time of the INITIAL crash:
1. It DID work when everything was unpowered and I had all of my gear worn w/o pressure.
2. Yes, I took it all off except for the helmet once it occurred to see if I could replicate it.

Upon the most recent crash:
1. Same as above
2. All armor was equipped, all charged somewhat.

And the GUI appears to crash whenever I hit the key, even if it's bound to a new key.

**Comment by desht** [comment]
Thanks for the info. 

Yeah definitely something weird going on here, and it does appear to be strictly clientside. Like I said, I could code around the symptoms, but I can't yet see what the root cause is. But I have some lines of investigation to follow...

**Comment by Famous5000** [comment]
Alright, let me know when a solution is found please, as I'd like to be able to fly around like a maniac again.

**Comment by desht** [comment]
OK, build 268 (http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/268/) has a bunch of debugging in it which might be helpful.  All the relevant messages contain the string "ISSUE254" to make it easy to extract the relevant data from the log file.  If you could try that build out and reproduce the crash, that would be great.

The build is based off the 0.8.0 beta, but it should work fine with your existing world (there aren't any new or removed blocks/items relative to 0.7.8).

**Comment by Famous5000** [comment]
I was actually going to do this on a copy of the modpack that was created, so no need to worry about corruption in either case.

I'll do as I did before: Set up the keybind, then try to replicate the crash. If it crashes, I'll send you the crash and the logs if I can.

**Comment by desht** [comment]
Closing due to lack of feedback.
