### ISSUE TITLE
Interaction between PneumaticCraft: Repressurized and Actually Additions 

### ISSUE THREAD

**Issue by DinnerBeef** [TeamPneumatic/pnc-repressurized#255]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.4.2760
### Mod Version
1.12.2-0.7.7-258
### Describe your problem, including steps to reproduce it
Using the Amadron Tablet  Actually Additions crate will consume all the items that are used for the trans but it only does that for AA Items.
### Any other comments?
https://github.com/FTBTeam/FTB-Pyramid-Reborn-3.0/issues/10

**Comment by desht** [comment]
I just tested with AA v137 and the latest in-dev PneumaticCraft, and the problem does not occur.  The Ama-drone only takes what it needs.

There were some problems with logistics/drones and some (but not all) non-vanilla inventories in previous releases, but that should all be fine now in the PNC 0.8.0 release.

**Comment by desht** [comment]
Going to close this; as far as I can tell, this is working fine in recent PNC versions.
