### ISSUE TITLE
The electrostatic compressor responds to lightning created by mods like Psi, making cheap pressure

### ISSUE THREAD

**Issue by TheDeviantCrafter** [TeamPneumatic/pnc-repressurized#256]
### Minecraft Version

1.12.2

### Forge Version

14.23.4.2759

### Mod Version

0.7.8-295

### Describe your problem, including steps to reproduce it

Several mods have the ability to summon lightning. Psi's trick:smite is one example, but there are countless others. When these mods trigger a lightning strike on an electrostatic compressor, it treats it as if it it was a vanilla lightning strike.

This generates huge amounts of free pressure at almost no cost.

### Any other comments?

From what I can tell, the electrostatic compressor waits for a vanilla lightning bolt to appear close by and then generates power. This means that it creates power if a mod triggers a lightning bolt.

Immersive Engineering's lightning rod machine takes a different approach. Instead of waiting for a lightning strike, it has a small chance every tick to emulate one. When it does, it generates a bunch of power, and then creates a vanilla lightning strike.

To the end user, it looks like a vanilla lightning strike happened, but mods that trigger lightning strikes won't affect the machine.

**Comment by desht** [comment]
Electrostatic compressor has been redone in 0.8.2 release
