### ISSUE TITLE
Unable to break pipes in survival mode

### ISSUE THREAD

**Issue by lOmicronl** [TeamPneumatic/pnc-repressurized#259]
### Minecraft Version
1.12.2

### Forge Version
14.23.4.2760

### Mod Version
1.12.2-0.8.1-274

### Describe your problem, including steps to reproduce it
Attempting to destroy pipes or advanced pipes with a pickaxe no longer drops the item. Instead, it remains in the world, albeit reverted to just a central nodule that is not connected to any neighboring pipes anymore.

Using a pneumatic wrench allows reconnecting the pipe to its neighbors, as well as picking it up as designed. However, the changelog makes no mention of intentionally making the wrench a hard requirement to pick up pipes. It _does_ mention something about breaking camouflage without breaking the underlying block. Something like that appears to happen here, except that there never was any camouflage applied.

In creative mode, destroying pipes works normally.

### Any other comments?
Might affect other blocks besides pipes, but I only tested those.

Can reproduce with only Forge, JEI, Ingame Wiki, and Pneumaticraft. Affects both existing worlds and new worlds.

Downgrading to 1.12.2-0.8.0-267 makes the issue go away, so it must be introduced by something in 0.8.1.

**Comment by desht** [comment]
The changes to camo breaking are the most likely culprit here (intended as a QoL feature to make it easier to break camouflage off camouflageable blocks, like pressure tubes).  I'll do some testing when I'm at my dev machine.

**Comment by desht** [comment]
Fixed in 0.8.2 release
