### ISSUE TITLE
Speed upgrades in charging station might not be working properly

### ISSUE THREAD

**Issue by lOmicronl** [TeamPneumatic/pnc-repressurized#261]
### Minecraft Version
1.12.2

### Forge Version
14.23.4.2760

### Mod Version
1.12.2-0.8.1-274

### Describe your problem, including steps to reproduce it
Yesterday I made a speed upgrade for the first time, after discovering how long it takes for a pneumatic chestplate to fill in an unupgraded charging station. Inserting one speed upgrade improved the charging rate from 10 ml/t to 15 ml/t, as expected.

...Or so I thought.

Despite the number in the info panel updating, there was actually no change in air consumption from the network. I could tell because that particular network had a single coal-fired compressor on it, currently running at its default speed of 10 ml/t. Meaning, the charging station without any upgrades was pushing air into charging items at exactly the same speed the compressor produced air. As a result, the amount of air in the network remained perfectly constant the entire time.

After I added a speed upgrade... it still remained perfectly constant. I would expect to see the total amount of air in the network gradually drop, since the charging station removes 50% more than the compressor is producing. Or depending on how speed upgrades work, perhaps it should even be increasing air consumption by 65%, since that is the current default config value for consumption increase.

But either the speed upgrade increased the charging station's speed for free, without consuming additional air, or it didn't do anything at all beyond updating the info panel. I couldn't really tell a difference with just one upgrade.

### Any other comments?
At the time, the network was at 4.6 bar, and the pneumatic armor piece inserted for charging was at 1.5 bar. So it was not a result of the pressure already being equalized.

**Comment by desht** [comment]
Build 279 from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ should fix that problem.

**Comment by desht** [comment]
Fixed in 0.8.2 release
