### ISSUE TITLE
Elevator extension configuration not functional

### ISSUE THREAD

**Issue by lOmicronl** [TeamPneumatic/pnc-repressurized#263]
### Minecraft Version
1.12.2

### Forge Version
14.23.4.2760

### Mod Version
1.12.2-0.8.1-274

### Describe your problem, including steps to reproduce it
After having built a base at Y=138, and not particularly fancying the prospect of building and repeatedly climbing a 128-block long ladder or staircase down to mining level, I hatched a cunning plan: a Pneumaticcraft elevator! Mines always have huge mechanical elevators, after all. Very themely.

By the time I found out that elevators only go up four blocks per base, I had already hyped myself up too much to abandon the plan. But I had a problem: at mining depth, Y=14 or Y=11, there is no way I could physically fit enough bases underneath to lift myself all the way to the surface.

But hey, there's a config setting, right? It's even mentioned in the ingame wiki. I:elevatorBaseBlocksPerBase=4 is the default value, but it accepts anything up to 256, so I chose 16. That meant that with 8 elevator bases, which would just fit between bedrock and the mine, I could go up 128 blocks - enough to reach the surface.

Unfortunately, this does not work. After spending over 220 iron on building the entire thing, including two elevator callers, I took a test ride and... stalled out not far from the bottom. Coming back down to investigate, I noticed that the elevator base indeed reports "Max Extension: 32 Blocks". In other words, the value expected for the default config setting of 4. The value I changed did not do anything in practice.

### Any other comments?
This is a singleplayer world, so there cannot be a config mismatch with the server.

Fun effect, by the way: in order to get the elevator to retract again after getting stuck in the shaft amidst solid rock, I used creative mode to fly up all the way to the top, so I could command the elevator caller to retract the elevator. As soon as the button was pressed, I was immediately standing on the (now descending) elevator platform again... 96 blocks below where I had just pressed the button. Instant teleport! You're probably using that in the background to make sure the player stays on top of the platform while ascending, don't you?

**Comment by desht** [comment]
Confirmed.  That's not right at all!  Definitely worked at some point, so I'll try to work out what's changed.

**Comment by desht** [comment]
And yes, there is code to move the player (or any entity which is in an elevator frame's space) to the position of the elevator platform.  I also just added a little code which nudges the player toward the center of the frame if they're hanging over the edge of the platform too much (although it's possible to overcome that "nudge" by walking in that direction).

**Comment by lOmicronl** [comment]
Great to hear it was simple to fix =)

Did that affect other config fields as well? Because I just changed the speed upgrades from 1.5/1.65 to 1.4/1.5, but upon placing one in a generator, it still increased the output from 10 to 15 mL/t. Wasn't just a display issue either, as the connected vortex tube stabilized at 1.5 bar. (Those things are the most precise airflow measurement devices in the mod, amusingly enough!)

Of course, this could also be related to the other bug you already fixed, wit the speed upgrades not correctly applying in the charging station...?

**Comment by desht** [comment]
Yes, I think this fix should also fix that problem.

**Comment by desht** [comment]
Fixed in 0.8.2 release
