### ISSUE TITLE
JEI recipe for turbine blade incorrect

### ISSUE THREAD

**Issue by lOmicronl** [TeamPneumatic/pnc-repressurized#264]
### Minecraft Version
1.12.2

### Forge Version
14.23.4.2760

### Mod Version
1.12.2-0.8.1-274

### Describe your problem, including steps to reproduce it
To make a turbine blade in the pressure chamber, JEI suggests to insert one redstone and one gold ingot. This is incorrect, as processing actually required two redstone per gold ingot.

### Any other comments?
The ingame wiki has the correct recipe.

**Comment by desht** [comment]
Yeah I spotted that too a few days ago - think it might be a JEI issue. Anyhow I worked around it, so it's fixed in dev already.

**Comment by desht** [comment]
Fixed in 0.8.2 release
