### ISSUE TITLE
Ticking Screen crash with Amadron tablet

### ISSUE THREAD

**Issue by lOmicronl** [TeamPneumatic/pnc-repressurized#267]
### Minecraft Version
1.12.2

### Forge Version
14.23.4.2760

### Mod Version
1.12.2-0.8.2-288

### Describe your problem, including steps to reproduce it
Upon trying to open the Amadron tablet's GUI, the client crashes. There are no extra steps; opening literally any tablet, whether freshly crafted or spawned in or existing, activates immediate self-destruct.

### Any other comments?
If I roll back to 0.8.1, the problem goes away.

Crash report: https://pastebin.com/FdUYK9sy

**Comment by desht** [comment]
Yeah, I know what happened here :(  My fault, but easily fixed.

**Comment by desht** [comment]
Fixed in Jenkins build 297

**Comment by desht** [comment]
Fixed in 0.8.3 release
