### ISSUE TITLE
[Suggestion] Configurable Dispenser Upgrade

### ISSUE THREAD

**Issue by EmosewaPixel** [TeamPneumatic/pnc-repressurized#268]
Could you perhaps add a config option for whether the Dispenser Upgrade should let Fluid Hoppers collect fluids? In my pack I only want certain machines to be able to collect Water, but I'd also want to have the Dispenser Upgrade for the Drones.

**Comment by desht** [comment]
Yeah, that wouldn't be a problem to add.  Probably just a simple boolean 'B:liquidHopperDispenser' config setting in the short term.

(Longer term - maybe not till 1.13 - there will be a more comprehensive system for controlling the max. number of each upgrade a machine can accept.  At that point, it will be possible to set the max Dispenser upgrades for the hopper to 0, which will obsolete this change.  But 1.13 will see quite a significant overhaul of how much of the mod works anyway - see #130 for some ideas)

**Comment by desht** [comment]
Fixed in 0.8.3 release
