### ISSUE TITLE
[Suggestion] So, about that elevator...

### ISSUE THREAD

**Issue by lOmicronl** [TeamPneumatic/pnc-repressurized#269]
I've already mentioned in a previous issue that I was trying to make an elevator between my mine and my surface base, which, due to custom terrain, ended up being 126 blocks tall. Version 0.8.2 fixed the bug with the config setting not applying ingame, and now, my elevator can actually extend the whole distance without needing more bases than space to bedrock allows for.

...Theoretically. Because in practice, the elevator still gets stuck after around 100 to 110 blocks, out of 126. The reason is quite simple: it runs out of air. Even when pressurizing the system to its breaking point of 5 bar, it's not enough.

Tossing in a volume upgrade or three would solve that problem easily. But there is a deeper issue here. Namely the fact that in this 16k mL system, each unit of coal consumed by the compressor adds exactly 1.0 bar of pressure. And the elevator consumes 2.0 bar (from the maximum of 5 down to the minimum of 3), and therefore 2 coal, but still falls short of reaching the surface. Now add the fact that I'd want at least 2-3 speed upgrades so the journey doesn't take forever, which reduces the efficiency somewhat, and I'm easily looking at 3 units of coal for every single trip up. If not more. Considering that the competing solution - a ladder - doesn't cost over 200 compressed iron and a bunch of plastic to initially set up, and is free to use infinitely often, that's a pretty harsh energy cost.

Now at this point, I'll concede that I'm probably using the elevator in a way it was not designed for. That I had to quadruple the lifting distance per base block to even make it physically fit is as much of a giveaway as the sheer cost of each trip. So if you want to say that you want to stick to keeping elevators balanced for buildings a couple dozen blocks tall at most, that's fine. It's not like I need to travel constantly to my mine and back.

But if you're open to suggestions - how about allowing the elevator to recoup half of the air it expended going up, on the way down? Or even just half of the air it would have spent without speed upgrades. The elevator base could accept a valve module in its upgrade slots the same way compressors do to give players the option of protecting against overpressure induced by this recuperation. Such a model would still require the player to provide a large amount of air storage to cover large distances; simply changing the lifting cost per block would not maintain that part. But at the same time, it doesn't make elevators so expensive to use on large height differentials.

**Comment by desht** [comment]
I actually quite like the idea of air regeneration when the elevator is descending. It should perhaps require a specific upgrade to do that, though (apart from anything else, just adding the feature could cause some unexpected explosions in existing setups). 

Note that you should already be able to add a Security Upgrade to prevent over-pressure explosions so that's covered.

**Comment by desht** [comment]
Fixed in 0.8.3 release
