### ISSUE TITLE
Under negative pressure, items slip through pressure chamber interface

### ISSUE THREAD

**Issue by lOmicronl** [TeamPneumatic/pnc-repressurized#270]
### Minecraft Version
1.12.2

### Forge Version
14.23.4.2760

### Mod Version
1.12.2-0.8.1-274
1.12.2-0.8.2-288

### Describe your problem, including steps to reproduce it
Chanced across this multiple times when using the enchantment stripping function of the pressure chamber. (I love it! Totally OP tho)

I have a hopper point at the inserting interface, and usually when I fill that hopper completely, the interface will insert the contents into the chamber one by one. The outer door opens, the item enters, the outer door closes, the inner door opens, the item exits, and so on and so forth. But while there is negative pressure on the chamber, what actually happens is that as the first item enters the interface and the doors begin to move, the entire rest of the hopper's contents slip right past the interface and into the chamber.

I have not done any exhaustive testing on whether this affects all items equally, but it definitely works with enchanted tools and armor that I want to unenchant.

The extracting interface does not display this behavior.

### Any other comments?
Possibly one of the least important bugs ever reported =P

**Comment by desht** [comment]
Hmm.  Curious.

I'll do some testing and see what happens...

**Comment by desht** [comment]
Yeah, the interface wrongly allows items to be inserted into it when the input door isn't fully open.  That's a bug.

**Comment by desht** [comment]
Fixed in 0.8.3 release
