### ISSUE TITLE
Ideas for Minigun enhancements

### ISSUE THREAD

**Issue by desht** [TeamPneumatic/pnc-repressurized#271]
The Minigun is super stylish but often overlooked and/or overshadowed by other mod weapons.  Would be fun to expand its abilities in a balanced way.   Thoughts:

New ammo types (not craftable with potions):

* Armor-piercing ammo (craft ammo with one or more diamonds) - ignore enemy armor when doing damage.
* Incendiary ammo needing blaze rods.  Set targets on fire.
* Shocking ammo? Stuns targets?
* Explosive ammo? Probably no terrain griefing though...
* Weighted ammo? Very damaging but very short range.

Some of these specialty ammo types would likely need smaller max ammo amounts (basic ammo has 1000 shots per stack).

In addition, make the Minigun upgradable in a Charging Station:

* Speed upgrades give chance of multiple rounds fired in a shot (in effect raising the weapon damage).  Would need to increase air usage a lot though to balance this.
* Volume upgrades do the expected: increase minigun's air storage.
* Range upgrades increase range over existing 50 block range, increases air usage.
* Security upgrade prevents damage to other players and/or tamed animals?
* Entity Tracker upgrade to zoom in on a target while firing?
* Dispenser Upgrade to increase potion proc chance - big air and/or ammo usage increase
* Item Life upgrade... very slow ammo regen for heavy air cost?

And give the Minigun its own small (5-slot?) inventory to carry ammo and avoid cluttering the player's inventory.  Shift-right-click to open it.

**Comment by Sewef** [comment]
Suggestion : Through Aerial Interface, allow recharging Ammo directly in Minigun inventory
Nice ideas, though :)

**Comment by desht** [comment]
Yeah, could be an option.  The Aerial Interface would need specific support (is the item ammo? if so, does player have a minigun with free slots?  if so, send to minigun instead of inventory). Care would also be needed to avoid flooding the player's inventory with ammo (the Aerial Interface doesn't know or care how many of an item a player has - it's up to whatever is interfacing with the inventory to do that).

**Comment by KirinDave** [comment]
Hi, I hope you don't mind me stepping in. I've been doing a lot of hours of play with your mod.

I'm not sure it's necessarily wise to try and make the minigun directly competitive with the various top-end weapon options in the game. This is a pretty linear design space (more # = more bigger) and there's also a lot of risk if you start doing things like overriding the minimum damage time of targets to interact in crazy ways with stuff like Astral Sorcery and other superpower mods.

May I instead recommend that you consider changing it such that it's capable of firing indpendently even in the player's inventory in the offhand? Or perhaps as an armor modification? With the current modest damage values, this wouldn't be overwhelmingly strong. However, it'd be extremely flavorful, feel cool and inline with the helmet's look and feel.

In general, I think that Pneumaticcraft's most distinct feature is that it has loads of "autonomous" options. Drones & Security Systems and Tank Interfaces all feel like extremely high tech, and the security systems are similarly "very smart." 

Trying to open up an alternative design space for weapons around things that enable the player to engage multiple targets at once (as opposed to creating The Blessed Stick Of One Shot One Kill) is a better route to consider. It also means you can use less overwhelming damage numbers but still provide obvious value.

**Comment by desht** [comment]
Actually, I already have the enhanced Minigun available for playing with if you get the latest (306+) build from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/.  If you feel like having a play with that, I would be interested in feedback for the upcoming 0.9.0 beta release...

Just to note that the Minigun is still not a guaranteed one-shot-kill weapon, although it's definitely more effective given the right ammo type and sufficient upgrades.  There are still plenty of weapons from other mods which eclipse it in terms of sheer damage and OP'ness.  The new ammo types and upgrades have costs and drawbacks of their own to balance out the increased damage and/or utility (e.g. more expensive crafting costs, smaller ammo cartridge sizes, increased air usage, reduced range).

I should also note that the Minigun is now highly configurable (see the "minigun" section in pneumaticcraft.cfg) so can be heavily tweaked by modpack developers in terms of damage, air usage, cartridge size, proc chances etc.

I do quite like the "autonomous fire" idea if it's in the offhand.  I think it would have to also require the Helmet Entity Tracker to be installed & active, and a way of locking to a target - right now the Entity Tracker needs the player to be looking right at the target, so this would need a new hotkey to toggle a lock.  It might be possible to overload the Drone Debug hotkey to become a Lock/Debug hotkey (would rather not add more hotkeys than necessary)...

As for multiple targets, the Micromissiles (also new in this dev build) might be worth a look... :)

**Comment by KirinDave** [comment]
I'll take a look. I also opened another issue after reading some of your other work! I'll make a minigun and get a feel for it asap.

**Comment by desht** [comment]
Added in 0.9.0 release
