### ISSUE TITLE
Diamond Recipe Pressure Chamber

### ISSUE THREAD

**Issue by SkaOArts** [TeamPneumatic/pnc-repressurized#272]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2768
### Mod Version
1.12.2-0.8.1-274
### Describe your problem, including steps to reproduce it
The recipe to craft a Diamon with a Block of Coal doesn´t work. I tried it with a Block of Coal, single Coal, and also with Charcoals Variants. But the Diamond won´t be craftet. The Condition are set, but the Pressure chamber won´t work. In generell they work. I can put iron bares to craft compressed iron or other recipe.

**Comment by desht** [comment]
You need 8 blocks of coal to make a diamond, not one.

If jei is showing the wrong recipe, try upgrading to 0.8.3 (which you should anyway - there are many bug fixes).

**Comment by desht** [comment]
Closing this - as far as I can see there's no issue with diamond crafting.  Just be sure to use 8 coal blocks.
