### ISSUE TITLE
Pneumaticraft Incompatibility: Exception in Gorgon setAttackTarget

### ISSUE THREAD

**Issue by ErickThePresident** [TeamPneumatic/pnc-repressurized#273]
When Pneumaticraft: Repressurized is installed and a Gorgon spawned, NullPointerExceptions are continually thrown inside a FutureTask. The problem occurs in a small instance with only Ice and Fire, Pneumaticraft and JEI, though it only shows up in the logs. The Ice and Fire version tested is 1.5.2, and Pneumaticraft version is pneumaticcraft-repressurized-1.12.2-0.8.2-288.

Here are some crash reports from a larger instance generated by VanillaFix after encountering a Gorgon structure:

Report 1 - first type of error seen
https://paste.dimdev.org/fipezeheke.mccrash
Report 2 - seen later, perhaps after Gorgon was unloaded
https://paste.dimdev.org/ugaqovojey.mccrash

**Comment by ErickThePresident** [comment]
This crashes the game!

**Comment by desht** [comment]
Thanks. Although it's technically I&F's problem, I think I can add a workaround for it in PNC.

Although setAttackTarget() isn't usually called clientside, PNC does it for the Pneumatic Helmet so it can track when mod are targeting the wearer and warn them. This works fine for vanilla and modded mobs until now - I&F assumes its server side and tries to run some AI code which doesn't exist on the client... crash.

I can add a try / catch in the PNC client side code and blacklist any mods which throw an exception, such as the Gorgon. This will prevent the crash but also disable the tracking warning, unfortunately.

**Comment by ErickThePresident** [comment]
Awesome, thank you so much!

**Comment by desht** [comment]
Fixed in 0.8.4 release
