### ISSUE TITLE
Logistic Modules don't move fluid far enough

### ISSUE THREAD

**Issue by mcsaboteur** [TeamPneumatic/pnc-repressurized#275]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.4.2760
### Mod Version
1.12.2-0.8.3-299
### Describe your problem, including steps to reproduce it
Logistics Modules don't move fluids very far.  Logistics frames try to move the largest amount possible and will often get clogged and move no fluids if the distance is too great.  I did some creative testing with a pipe network at 19 bars and the distance to move 16 buckets at once is only seven pipe blocks.  Moving only 1 bucket is 27 pipe blocks. 1-100ml of fluid moves further, but you can't technically request this amount.  This makes it very difficult to impossible to keep thermo plants and liquid compressors full without keeping your build really small.  It would be nice if fluids were more in line with items, which have much higher limits on distance.  As is, the limits prevent even moderate sized builds.

### Any other comments?
Thanks!

**Comment by desht** [comment]
Yeah, I had actually noticed that too. A significant overhaul of tube costs is planned, including making them cheaper overall in terms of air used, but also not trying to move everything at once.

**Comment by mcsaboteur** [comment]
Awesome, thank you!  In the meantime, I can have drones do the work, or send fuel in buckets.

I have two other issues I was thinking about posting(sorry).  One is AE2 integration not working consistently and the other is a vanilla furnace with a heat frame pushing coal/charcoal to the wrong slots and double smelting them into graphite if Extreme Reactors is installed.  If you want I can write these up.   If you're aware of the issues, I can just ignore them.  I have workarounds for both issues so it's not a problem for me atm.

**Comment by desht** [comment]
The AE2 issue might be difficult to solve. If noticed it before back when the AE2 dev added it (the integration was done by them) and we never could fully track it down.

As for the heat frame issue, please raise a new request for that. Think I might know what's happening there...

**Comment by desht** [comment]
Update on the heat frame, now that I think about it: you don't actually need a heat frame on a furnace.  Pointing the hot side of a vortex tube at the furnace is sufficient, and should not trigger the wrong slot insertion issue.  Alternatively put the heat frame on any regular inventory (vanilla chest will do), and it will cook the items.

The basic problem is that heat frames don't have the concept of sidedness, so they just use the null face to insert/extract items - which basically leaves it up to the tile entity to decide which item handler actually gets used.  In the case of the furnace, it's clearly the wrong one :)  I could add a specific workaround for the furnace, I suppose, but the heat frame is more intended for non-sided inventories like chests.

**Comment by mcsaboteur** [comment]
I didn't know about the vortex tube to furnace trick and I forgot about chest smelting.  Chest smelting is pretty cool.  There would still be an issue with coal/charcoal being smelted into graphite unintentionally, but that seems like an unsolvable issue.  There are endless ways to smelt, so it's not really an issue.

Bummer about AE2 just because it's such a cool feature.  I've had builds where it works perfectly and builds where it just doesn't work.  Ender chests and a storage bus are a pretty easy alternative, so no issue here either.  

Thanks, for being cool.

**Comment by desht** [comment]
No problem.  Feel free to create an issue for AE2 - I might have another look at it at some point (I have a far better understanding of how it all works now than back when I did the port to 1.12.2 :)

**Comment by desht** [comment]
Fixed in 0.8.4 release.  Logistics modules can now move items much further, and for much less air.
