### ISSUE TITLE
Assembly table says duplicate machine

### ISSUE THREAD

**Issue by owskie** [TeamPneumatic/pnc-repressurized#276]
Minecraft version: 1.12.2

Forge Version: 14.23.4.2707

Mod Version: 1.12.2-0.6.6-192

Im playing on my sevtech server and im at the point of setting my assembly 
system up. I have all the parts and placed them but the controller always tells me i have duplicate machines. I have all the right things and all set in the right spot. Nothing i do changes it

**Comment by desht** [comment]
I would need to see a screenshot of your setup.

**Comment by owskie** [comment]
Here is a link (http://imgur.com/a/jH7sBpj) One pic has the message and other is the setup. The setup has changed because I've been trying different configurations.

**Comment by desht** [comment]
Well, I don't see any duplicates, but I can tell you that your second setup won't work, since the laser needs to be directly adjacent (not diagonally) to the assembly platform.

The import/export arms can be diagonal to the chest(s) and platform, but the laser and drill must be directly adjacent to the platform.

I'll make a copy of your setup this evening and see if I get the duplicate error.

**Comment by owskie** [comment]
The problem is I've set it up so the laser and drill weren't diagonal. I still got the error

**Comment by desht** [comment]
OK then, please show me a screenshot of your exact current setup so I can build a copy and debug.

**Comment by owskie** [comment]
Here is a setup I used. It's not my picture but the setup is the same. (https://i.imgur.com/5GScEV0.png)

**Comment by desht** [comment]
That setup is running fine, though.  You've built exactly this, and you're still getting the "duplicate machine" error??

**Comment by owskie** [comment]
Yes

**Comment by desht** [comment]
OK, might be difficult to track down.  I'd still like a screenshot of your actual current setup when you're able.

**Comment by owskie** [comment]
When I get home from work I'll try installing a new version of the model I think there is a newer version

**Comment by owskie** [comment]
This is my current set up.
(https://imgur.com/uhQfRYE)

**Comment by owskie** [comment]
I've tried  other setups but nothing works

**Comment by owskie** [comment]
Someting i just noticed. When i disconnect from my server and go back in the IO unit i set to extract always reverts back to input. Maybe that is something. I havent had any issues with my server up to this point.

**Comment by desht** [comment]
Yeah, that would cause a dupe error since you then have 2 input units. Not sure why it's reverting though. If you wrench it back to output does the error go away?

**Comment by owskie** [comment]
No when I wrench it back the error stays.

**Comment by desht** [comment]
Very odd.  I'll keep this open for now and try to reproduce it but it might be difficult.  Would be useful to know if anything else changed with your server when the issues started.

**Comment by owskie** [comment]
Nothing else has changed. I've been doing lots of other stuff while the assembly didnt work and nothing else gave me issues.
I tried restarting the server but nothing changed

**Comment by desht** [comment]
I'm doing some reworking of how the Assembly system finds its machines for 0.8.4, which *might* help.  I will let you know once that version is out (or when a dev version is available for testing purposes).

**Comment by owskie** [comment]
That's really great.  I tried to update the mod on my server but it's a sevtech server and I dont think it liked it as it kept crashing. I will try a new version though if I can try it

**Comment by desht** [comment]
Yeah, I know Sevtech is really close to the item limit, and the newer PNC release add a few extra items which might be enough to push it over the limit.  https://minecraft.curseforge.com/projects/notenoughids might help there, but it can also cause instability, so I'd try it out on a test world first.

**Comment by owskie** [comment]
Cool I'll give that a shot when I get home. I am also going to try taking the world of my server and make it single player see if it works in single player world then move the save back.

**Comment by owskie** [comment]
Ok.... so I got it working. Of all the things it could have been. It was the wrench i was using..... I just made a random wrench that made the IO blue. I have to use the pneumaticcraft wrench. I dont know if that's something that is normal but that did the trick.

**Comment by desht** [comment]
No worries. Newer versions of the mod do have some better 3rd party wrench support, so you might find that works better in future. But good to know that the Pneumatic Wrench does the job.

**Comment by desht** [comment]
Problem resolved, but further work done in 0.8.4 to make it clearer what machines are missing.
