### ISSUE TITLE
Suggestion: increase kerosene lamp tank size slightly

### ISSUE THREAD

**Issue by lOmicronl** [TeamPneumatic/pnc-repressurized#280]
I've built a huge building for toying with Advanced Rocketry. It's being lit by four Pneumaticcraft kerosene lamps, all toggled by a central light switch. They work beautifully... until they run out of fuel. Or rather, until they _don't_ run out of fuel.

In each of the four lamps, I have placed a bucket of kerosene to refill the internal tank when it falls low. Problem is: the internal tank is only 1000 mB, which is exactly one bucket's worth. That means the lamp needs to fall all the way to zero fuel before the bucket can be emptied into the tank.

Contrary to my expectations however, the lamps don't actually ever run out of fuel. When they get low, they will reduce their area, and thus their fuel consumption... apparently, all the way to zero. And they do this before the tank is completely empty.

Case in point: one of my lamps has been sitting at 2/1000 mB fuel for a full Minecraft night now. It has reduced its action radius to 2, and it no longer consumes any fuel, so the provided bucket can never refill the internal tank.

Rather than asking you to completely rewrite the way kerosene lamps work, I thought: why not just increase the internal tank to 1200, or 1500, or even 2000 mB? That should completely circumvent the problem.

**Comment by desht** [comment]
That's a possibility, yeah. Normally I'd just use a liquid hopper, logistics drones or some other mod piping solution to keep them filled, but using buckets should be a viable option too.

**Comment by desht** [comment]
Incidentally, I'd be interested to know what your thoughts are on the lamp's fuel efficiency.  It uses kerosene (or other fuels) proportional to the lighting radius cubed, so at a radius of 30 it does guzzle fuel.  Interested to know how well your fuel production keeps up with your lighting needs, and what radius you're running the lamp at.

**Comment by lOmicronl** [comment]
Two of the lamps are set to 8, one of them is at 9, and one is at 10. There is some overlap between them because of the awkward (read: not simply four-sided) shape of the building. I'm definitely feeling the fuel usage, but I'm not too bothered by it, for three reasons:

* I only have them turned on when I'm in the building, which is not all that often.
* The floor is lit up by torches anyway - the kerosene lamps are just luxury for making the cavernous, high-ceiling interior feel less, well, cavernous.
* I have kerosene coming out of my ears.

Personal opinion: generally in Minecraft, lamps that require power are inconvenient, lamps that require renewable fuel are borderline unusable, and lamps that require non-renewable fuel are outright unusable. Because of the way mob spawning works, and because the assortment of mobs includes one that explodes violently, intermittent lighting just doesn't work. Light switches are pointless. Indoor lights must be on at all times, day and night, period, and because of this, the lighting solution must be maintenance-free. With powered lamps, you can at least have a reliable, centrally managed source take care of them all, even though in pretty much all cases, the price and inconvenience of the required wiring completely obliterates whatever advantage they might have had over torches - if the wiring can even be implemented in the room design you had envisioned. A fuelled lamp takes this inconvenience and makes it worse, because liquid fuel is more difficult to distribute over a large network than power, and solid fuel is even more so. And if you can't implement a fuel delivery system, each individual lamp becomes a point of failure that gets you creepers among your valuable machinery.

Pnemuaticcraft has the unique capability of wireless liquid fuel transfer via drones. That's a game changer for fuelled lighting sources, because it means you can keep them fuelled without ugly, expensive and immersion-breaking piping. And yet, I still wouldn't use them, ordinarily. I would have to get into examining the fuel use each lamp would need in its intended usage scenario, then figure out how fast I would need to run the refinery to make sure they never run out. Then I'd have to figure out what to do with the three other products the refinery will spit out, for which I'd have no use. Void them? Build endlessly increasing columns of tanks? And then, of course, after a week or so, my oil source would be dry, even when using Buildcraft's much larger but less common deposits. Then I would have to figure out a way to constantly haul in oil from a remote source.

And for what? For the exact same job that placing down a dozen torches does? Yeah, no, I'll pass.

It just so happens that I have fifty-odd buckets of kerosene lying around unused as a side product from making all the plastic I needed for progression, the giant mining elevator, and drone programs. And since I'm exploring Pneumaticcraft, I thought I might as well try out the kerosene lamps too. Not as a replacement for torches, of course, that is completely unsustainable. No, as an _addition_ to torches, to make a giant room a little friendlier, and to have a lightswitch not because it's useful but because I can.

As far as that goes, at least, I am very pleased with the performance of the lamps. The difference between [the lamps off](https://i.imgur.com/kXj6vEs.png) and [the lamps on](https://i.imgur.com/k4vhA0p.png) is pretty much literally night and day. I am glad that I built them. And since I made four lamps with low settings instead of trying to use one at high settings (I noticed early on that that was a very bad idea), the fuel use is within acceptable bounds. I mean, I'm going to run out sooner or later, no questions about that - I've already gone through four buckets in an evening of 2-3 hours of playtime. But that's okay. By the time my reserves run out, I'll probably have done most of what I want to do with Advanced Rocketry anyway.

**Comment by desht** [comment]
Added in 0.8.4 release
