### ISSUE TITLE
Drone does not dig snow layers

### ISSUE THREAD

**Issue by Cyxxus** [TeamPneumatic/pnc-repressurized#281]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2775
### Mod Version
0.8.3
### Describe your problem, including steps to reproduce it
Drones can not dig snow layers(minecraft:snow_layer) or snow layer derived blocks(ie. Shoggoth Ooze from AbyssalCraft).
When set to dig snow layers in an area, the drone will just stay in one place as if it sees no snow layers.

**Comment by desht** [comment]
I'm not seeing this behaviour.  Just programmed a Drone to dig snow layers, and it worked fine: https://youtu.be/WZS14J2rbBw

**Comment by desht** [comment]
Note that if you're using a filter to select *only* snow blocks, be aware that filtering works by item dropped, not by block.  So don't filter on snow layers, filter on snowballs.  (You don't need to equip the drone with a shovel unless you actually want the snowballs).

**Comment by Cyxxus** [comment]
That solves the problem for snow layers but in the case of me wanting to clean up Shoggoth Ooze, from AbyssalCraft, I can't do that with drones as nothing drops from it. I am able to filter the dig to the ooze's block itemstack but that doesn't work because the drones are looking for a drop.

**Comment by desht** [comment]
Yeah... no easy fix for that at this point.  You could leave filter empty, but that would also dig up anything under the ooze too.  I presume you just want to set an area and have the drone remove only the ooze from it?

**Comment by desht** [comment]
Had an idea: I can add another checkbox to the Item Filter piece: "Match by Block".  When checked, the selected item (which must be a block, of course) will be matched directly against the in-world block.  This will allow matching against blocks which never drop an item, such as Shoggoth Ooze.

**Comment by Cyxxus** [comment]
Awesome! That sounds perfect. Thank you!

**Comment by desht** [comment]
Added in 0.8.4 release
