### ISSUE TITLE
Drone can't pick up Minecart / Boat

### ISSUE THREAD

**Issue by Sewef** [TeamPneumatic/pnc-repressurized#283]
### Describe your problem, including steps to reproduce it
Yup, I should update PNC.

With a simple "Pickup entity in area" program, the drone can't take a Minecart or a Boat. Tested with all carts (even Minecart with Mana Pool), with and without Railcraft (which changes some minecart beavours).

And, by the way, Minecarts and Boat can pick up drones. The result is... stupidly fun.
![2018-11-22_10 30 37](https://user-images.githubusercontent.com/27089398/48893920-bc0c2e80-ee41-11e8-9a1c-135fa6afbc1b.png)

**Comment by desht** [comment]
Yep, currently drones can only pick up living entities.  However, it looks like boats and minecarts are not too problematic to allow as well, so this should be doable :)

**Comment by desht** [comment]
Added in 0.8.4 release
