### ISSUE TITLE
Weird issue on Player after using Air Cannon

### ISSUE THREAD

**Issue by Minamikaze392** [TeamPneumatic/pnc-repressurized#285]
### Mod Version: 0.8.4-303

Steps to reproduce:
- Use an Air Cannon with Entity Tracker Upgrade to launch yourself.
- After that, if you have any Jet Boots Upgrades installed, you can hear hover sound when standing still.
- Sometimes when shooting arrows from a bow,  the arrows fly higher than where the crosshair aims at.
- This one is very strange, it just _sometimes_ happens. Disable Jet Boots and make your jumping height 3 blocks high, by having 2 x Range Upgrades on leggings or other means. You may take falling damage sometimes when jumping on normal flat land.
- This issue will be there until you re-login to the world.

**Comment by desht** [comment]
Confirmed on all counts.  Yep, there's definitely something odd going on there.

**Comment by desht** [comment]
Fixed in 0.9.0 release.
