### ISSUE TITLE
Suggestion: Blacklist options?

### ISSUE THREAD

**Issue by Minamikaze392** [TeamPneumatic/pnc-repressurized#286]
I find that many filtering features in this mod are only whitelist based. Like the most concerned one for me is the filter puzzle pieces in programming. For example if I write a farming program using a hoe, The Export to Inventory can be more convenient if there is an option to set the hoe to blacklist. Right now you have to either deposit the hoe and take it back again, or use a long whitelist having one puzzle piece for each farm product.

And it would be a great plus if blacklist function is also added to the (Hold F1 for help) filtering system too. Maybe treat the string as a blacklist instead of whitelist if it starts with "!"?

**Comment by desht** [comment]
If you put filter pieces on the *left* of the programming piece, they function as a blacklist. Does that solve your problem?

**Comment by desht** [comment]
For entity filter strings, a "!" is a good idea which wouldn't be hard to add.

**Comment by Minamikaze392** [comment]
> t filter pieces on the _left_ of the programming piece, they function as a blacklist. Does that solve your problem?

Whoops I didn't know that, thanks lol!

**Comment by desht** [comment]
Added in 0.9.0 release.  Prefix a filter with "!" to negate it.
