### ISSUE TITLE
Pressure sometimes doesn't travel through chunk borders

### ISSUE THREAD

**Issue by Minamikaze392** [TeamPneumatic/pnc-repressurized#287]
### Mod Version: 0.8.4-303

Maybe it is easier to explain this one with pics:
![image](https://user-images.githubusercontent.com/40918110/49341773-27999b80-f68d-11e8-90e1-51d3d96fc06d.png)
![image](https://user-images.githubusercontent.com/40918110/49341778-38e2a800-f68d-11e8-8c3e-d580c0324f17.png)
Seems that it happens after the chunks are unloaded then reloaded. Not very sure though.

BTW sorry for spamming multiple issues :0

**Comment by Sewef** [comment]
I got the issue long time ago. Fixed it by placing more chunkloaders.

**Comment by desht** [comment]
Not at my computer at the moment so can't really test this, but yeah - keeping the chunks loaded is generally the only option. I will take a look when I have a chance though just to check there isn't any invalid caching or similar happening.

**Comment by desht** [comment]
Having been through the code, I don't think there's much I can do.  If tubes cross chunk boundaries, then you need to ensure they stay loaded, unfortunately.
