### ISSUE TITLE
Compatibility with Forestry

### ISSUE THREAD

**Issue by romanknyaz** [TeamPneumatic/pnc-repressurized#288]
Minecraft Version 1.7.10

Forge Version 1.7.10-1614.201

Mod Version 1.7.10-1.12.7-152

Hi. Faced with a strange error on my server when running this mod. The server has Forestry installed for 1.7.10. Error on server: Failed on getting Forestry''s farm blocks, using defaults. On the work of fashion is not affected. Question-is PneumaticCraft mod compatible with Forestry? Is it worth worrying about this error?

P.S. About PneumaticCraft. This is a great mod, but I think that the minigun does not look. It would be more logical to add hydraulic pistons with their specific work.

**Comment by desht** [comment]
I'm sorry, but this mod is for 1.12.2.  1.7.10 isn't supported at all.
