### ISSUE TITLE
[Suggesting] Add temperature to refinery craftweaker integration

### ISSUE THREAD

**Issue by wormzjl** [TeamPneumatic/pnc-repressurized#295]
Currently I believe that all recipes will start at a temperature of 100°C.
Could you make it customizable via CT? Maybe an optional float number in the end which don't break current scripts.
This will allow recipes with different level of energy usage

**Comment by desht** [comment]
Yeah, sounds reasonable.

**Comment by desht** [comment]
Although, some consideration would need to be given to how refining speed is calculated for different minimum temperatures...

**Comment by desht** [comment]
Fixed in 0.9.0 release
