### ISSUE TITLE
Ore dictionary chest in recipes

### ISSUE THREAD

**Issue by LemADEC** [TeamPneumatic/pnc-repressurized#296]
### Mod Version
1.12.2-0.8.4-303

### Describe your problem, including steps to reproduce it
Recipes are forcing vanilla chest, preventing integration with other mods.
Consider using 'chest' or 'chestWood' ore dictionary entries instead to support other mods.

**Comment by desht** [comment]
Following recipes are using vanilla chests:

* network_component.json:      "item": "minecraft:chest"
* network_component_v2.json:      "item": "minecraft:chest"
* network_component_v3.json:      "item": "minecraft:chest"
* network_component_v4.json:      "item": "minecraft:chest"
* network_component_v5.json:      "item": "minecraft:chest"
* network_component_v6.json:      "item": "minecraft:chest"
* omnidirectional_hopper.json:      "item": "minecraft:chest"

Will replace these with oredicted chests for next release.

**Comment by desht** [comment]
Fixed in 0.9.0 release
