### ISSUE TITLE
Crash on loadup. Texture issue.

### ISSUE THREAD

**Issue by SavageKiller13** [TeamPneumatic/pnc-repressurized#297]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
Minecraft version is 1.12.2
### Forge Version
Forge version is 14.23.5.2796
### Mod Version
Mod version is latest. 0.8.4-303
### Describe your problem, including steps to reproduce it
The problem I get is when loading up a modpack called "The Culmination" (on the latest release). while getting to the Texture stitching stage on loadup the game crashes with the error (in the crash log). I have loaded up the pack twice with the same log and started happening today.
[crash-2018-12-23_14.50.54-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/2706363/crash-2018-12-23_14.50.54-client.txt)

### Any other comments?
I don't have any texture packs loaded or modified textures for Pneumaticcraft.

**Comment by desht** [comment]
This isn't specifically a Pneumaticcraft problem, just that your modpack is loading too many textures. It just happened to run out of space when it was loading PNC textures.

I will take a look and see if any textures can be shrunk or maybe combined, but no promises.

**Comment by desht** [comment]
Having taken a look, there's definitely room for improvement here.  Many of the programming widget textures are unnecessarily high-res - 64x64 should be fine (maybe even 32x32), but many are 128x128, and there are even seven 256x256 textures.  Should be possible to scale everything down to 64x64 (perhaps 32x32 though that might not look too good) and save a good deal of space.

**Comment by desht** [comment]
Fixed in 0.10.0 release
