### ISSUE TITLE
Game closes after breaking pipes

### ISSUE THREAD

**Issue by WesleyBalestrini** [TeamPneumatic/pnc-repressurized#298]
### I believe the error is only with shaders (optifine use).
[crash-2019-01-04_21.30.34-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/2728896/crash-2019-01-04_21.30.34-client.txt)

**Comment by desht** [comment]
This is PneumaticCraft-Repressurized for 1.12.2.  The old 1.7.10 mod is not supported at all, sorry.

**Comment by NuclearAtoms** [comment]
I'm having an issue with 1.7.10  too. Where do I go to fix it?

**Comment by desht** [comment]
Nowhere, sorry.  1.7.10 is not supported anymore.
