### ISSUE TITLE
[Feature request] A way to tweak air usage from jet upgrade

### ISSUE THREAD

**Issue by Alessandro404** [TeamPneumatic/pnc-repressurized#299]
Hi! Loving your mod.

I'm testing it for checking what it can do, but I didn't find a way to control how much air the jet boots upgrade uses when flying/hovering

I'm trying to make a modpack where flying is severely limited in time and is costly to mantain, so your mod would be perfect... if even the basic setup with only boots+jet upgrades werent so... lasting. 

A multiplier for ability usage would be beautiful, I would tweak it for giving players only brief moments of fly at most

Thank you

**Comment by desht** [comment]
Yeah, I could add a usage setting in the config for that.

**Comment by desht** [comment]
This will be in the upcoming 0.9.1 beta release.  See 'I:jetBootsAirUsage' in the "Pneumatic Armor" section of the config.

**Comment by desht** [comment]
0.9.1 released
