### ISSUE TITLE
Add Electric Compressor & Pneumatic Generator (IC2)

### ISSUE THREAD

**Issue by desht** [TeamPneumatic/pnc-repressurized#3]
These machines are currently missing entirely.

I wonder how much demand there is for these?

**Comment by pharaun** [comment]
I certainly noticed them missing. And then came to github, and aha there it was.

If its too much trouble its probably fine to omit. I found them useful.

**Comment by desht** [comment]
Not too much trouble, no.  They will be going back in for the beta release, hopefully.

**Comment by desht** [comment]
Started work on this one.

**Comment by desht** [comment]
Electric Compressor & Pneumatic Generator are back in the mod.

Note: lacking the fancy models they had in 1.7.10; they have simpler cube-based models for now at least.  Will need a more skilled modeller than I to restore the 1.7.10 appearance...
