### ISSUE TITLE
Required Temperature of TPP Recipe doesn't show correctly in JEI

### ISSUE THREAD

**Issue by SihenZhang** [TeamPneumatic/pnc-repressurized#302]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2811
Mod Version: 0.9.2-321
JEI Version: 4.14.4.264
Singleplayer/Multiplayer: Multiplayer
Description:
![](https://i.imgur.com/mBcqEfO.png)
![](https://i.imgur.com/K9VHTmJ.png)
![](https://i.imgur.com/w4qo8s0.png)
![](https://i.imgur.com/NI8UOtx.png)
![](https://i.imgur.com/PDO9Guz.png)

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Fixed in 0.9.3 release.
