### ISSUE TITLE
Coordinate Operator deviding problems (maybe iam just stupid)

### ISSUE THREAD

**Issue by gamelnderGamler** [TeamPneumatic/pnc-repressurized#303]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Mod Version
1.12.2-0.9.1-317
### Describe your problem, including steps to reproduce it
Hi,

the description of the coordinate operation piece out of the ingame wiki mod tells me qote:"Multiplies the pieces connected to the right. Divides the result by the pieces on the left".

So i made this Programm:
![1](https://user-images.githubusercontent.com/22398257/53238506-afde7a00-3699-11e9-806e-d26bcc5e0410.PNG)
(https://pastebin.com/8Sw3D6T9)

As far as i understand, i multiply the 10 height with 1 so it should still be 10. After that i devide it by 2. so the variable "height1" should be 5?
So if i add the 5 height to the 86 height it should be at 91 height?

But i get this result: (iam using a programmable controller filled with stones to execute the programms)

![2](https://user-images.githubusercontent.com/22398257/53238733-60e51480-369a-11e9-9e88-af7249d731ae.PNG)

(The drone places to blocks. One at height 96 and one at height 95)

The controller placed the block at height 96 first, after that it placed the block at 95 aswell. i guess after the "second loop". 

After i changed my programm to this:
![3](https://user-images.githubusercontent.com/22398257/53239010-229c2500-369b-11e9-9339-d2cbea7d25aa.PNG)
(https://pastebin.com/YhC7FJmf)
(i devide by 1:2:1 now not by 0:2:0)

i get this result:
![4](https://user-images.githubusercontent.com/22398257/53239143-8d4d6080-369b-11e9-9848-5be7e09e71b3.PNG)
(The drone placed a block at height 91 and a block at height 90)

again it placed the block at the height 91 first. after that it also placed a block at height 90.

So this time it was more or less the right height after the first loop. but 1 block to much.

I dont know if i do something wrong or something is not working correct.
So iam sorry if i did something wrong again :/

### Any other comments?
(if you do this: 
![5](https://user-images.githubusercontent.com/22398257/53239488-722f2080-369c-11e9-9ec9-2f378a4a2ceb.PNG)

you get also kinda strange results)

I also have a question to this. If i divide a coordinate and i get a 2.4 and i use this as a coordinate to place things, will the controller round this down to 2?

**Comment by desht** [comment]
I'll have to do some testing on this and get back to you. I haven't played too much with the coord arithmetic operators other than basic addition so it's possible there are problems...

**Comment by gamelnderGamler** [comment]
Wow, yeah i normaly use the  "place block piece", but i was to much into testing, that i didnt even realize that iam using the wrong piece... 
Only for enderIO conduits you have to use the "right click piece". 
Iam really sorry. I figured out that i have to divide by 1,2,1 but i got so confused by the second block...
But it all makes sense with the "right click piece".
Sorry for wasting your time and thanks for the help!

**Comment by desht** [comment]
No problem :)

**Comment by desht** [comment]
Actually, going to leave this open; I'll add an error in the programmer GUI if any divide by 0 attempt is made (i.e. coordinate with a 0 found on the left of a mul/div operator piece).

**Comment by desht** [comment]
Fixed in 0.9.3 release.
