### ISSUE TITLE
Cannot pump fluid into the refinery

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#305]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2768
### Mod Version
1.12.2-0.8.4-303

### Cannot pump fluid into the refinery
I've tried various options including
* Gas Lift
* Liquid Hopper (with and without dispenser installed)
* Immersive Engineering Pump (powered and not powered)
* Immersive Engineering pipes connected to a Pump 

![image](https://user-images.githubusercontent.com/4198031/53494609-72655c80-3a9e-11e9-8f41-8c82eebb6976.png)

I've also tried different fuels and different hights

### Any other comments?
Any hints?

**Comment by desht** [comment]
What fluid is that in the screenshot? Doesn't look like oil...

**Comment by duncanwebb** [comment]
Ah the penny drops, so the refinery can only refine oil. I've been using 4 magneticraft refineries to split oil into the nine different products and was seeing if I could refine gasoline, diesel or kerosene into LPG using the pneumaticcraft refinery as well as using thermopneumatic processor

The project page says:
Refining - converting an input fluid to one of more output fluids via heat
Thermopneumatic Processing - converting a fluid and/or item to another fluid via pressure and/or heat

Thanks

**Comment by desht** [comment]
Right, by default the Refinery only processes Oil into 2-4 output fluids (Diesel/Kerosene/Gasoline/LPG, depending on the number of blocks in the Refinery multiblock).

The Thermopneumatic Processing Plant is what you need to convert a heavier processed fuel to a lighter one (Diesel->Kerosene, Kerosene->Gasoline, Gasoline->LPG).

Note that both machines have CraftTweaker support, so recipes in your pack could potentially be different. But both machines also have JEI support and that will always tell you which fluids can be converted to which, and how.

**Comment by duncanwebb** [comment]
Danny's Real Tech pack leaves most if the recipes as the mod author designed them. 

Thanks I'd figured the rest out.

![plastic-setup](https://user-images.githubusercontent.com/4198031/53571280-cfc5e000-3b68-11e9-8667-4ce71ebe65a2.png)

**Comment by desht** [comment]
One minor tip: any faces of your refinery and thermo-plants that are exposed to air will lose a little heat.  It's not so noticeable with the thermo-plant but much more noticeable with the multiblock refinery.  Putting any block on the side will stop that leakage and improve your efficiency.  Even non-full-cube blocks work like trapdoors, slabs or chisels & bits creations.

**Comment by duncanwebb** [comment]
Thanks
