### ISSUE TITLE
Game froze when i shift right click pressure tube

### ISSUE THREAD

**Issue by freopt** [TeamPneumatic/pnc-repressurized#306]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.5.2808
### Mod Version
0.9..2-321
### Describe your problem, including steps to reproduce it
Shift right click a pressure tube with a pneumatic wrench and then game freezes.
### Any other comments?
Here is a really long log: https://gist.github.com/freopt/ef8637c59876e4ea9229f3565e680b86
I was in creative mode, the wrench had no bar, the tube was an advanced pressure tube disguised as a grass block

**Comment by desht** [comment]
I can't reproduce this, and your posted log is just a startup log with a whole bunch of repeated messages from some other mod, nothing at all from Pneumaticcraft other than a couple of lines of info logged during startup.

Shift & right-clicking an advanced pressure tube camouflaged as a grass block with a fully-charged wrench dropped both the pressure tube and the grass block, as expected.

**Comment by desht** [comment]
Closed due to lack of feedback.
