### ISSUE TITLE
Armor pieces won't start up unless wearing the helmet

### ISSUE THREAD

**Issue by desht** [TeamPneumatic/pnc-repressurized#310]
Need to be wearing the Pneumatic Helmet to switch on the armor initially (i.e. when first logging in). Once the armor is switched on, the helmet can be removed, but it should be possible for players to use armor pieces without requiring the helmet initially.  The problem is basically that the armor "master switch" is attached to the helmet (a holdover from when the helmet was the only armor piece).

Workaround for now:
* Wear the helmet, open the armor GUI
* Select "General", and bind a key to the "Enable Pneumatic Armor" checkbox
* Now when you log in, and you're not wearing the helmet, you can tap that bound key twice to force an armor re-init, and any other armor pieces you're wearing will start up.

I will come up with a solution for the next release to get around this, possibly simply having the armor switched on by default.

**Comment by TeamSpen210** [comment]
Maybe a logical way to have it function is to enable all functionality always without the helmet, IE there’s no/minimal GUI. Although the helmet has so much functionality already...

Alternatively maybe a button in the charger that opens the config GUI for the inserted armour piece.

**Comment by desht** [comment]
Yeah, your first idea is kind of similar to the "on by default" thought I had. Rather than needing to switch the armor on in the GUI (currently requiring the helmet), just have it on by default. In the unlikely event that it needs to be shut down, the master switch remains (probably still needing the helmet).  In most cases though it's more useful to switch on/off individual features (mainly the jet boots and the magnet, but sometimes also step assist/run speed/jump boost).

**Comment by desht** [comment]
Fixed in 0.10.0 release
