### ISSUE TITLE
refinery not using redstone to make lube

### ISSUE THREAD

**Issue by StrommKral** [TeamPneumatic/pnc-repressurized#311]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.5.2808
### Mod Version
9.1-317
### Describe your problem, including steps to reproduce it
project ozone 3
the refinery is not consuming the redstone to make lube, instead you get kero. i have broke and replaced all parts multiple times. once i had it working, but when the lube was pumped out it started making Kero again. i am using enderio conduits, and exu2 drums
### Any other comments?
![2019-03-21_21 16 46](https://user-images.githubusercontent.com/18456978/54794643-d0f5a480-4c1e-11e9-8dc9-1c2ffadfdd68.png)
![2019-03-21_21 17 01](https://user-images.githubusercontent.com/18456978/54794646-d652ef00-4c1e-11e9-8c30-73c71c12e6cc.png)

![2019-03-21_20 38 34](https://user-images.githubusercontent.com/18456978/54794280-039e9d80-4c1d-11e9-9a77-b69582c57b74.png)

**Comment by desht** [comment]
1) You mean the thermopneumatic processing plant, not the refinery.

2) This is correct behaviour; you're giving the TPP pressure, so yes it will make Kerosene. Look at the recipes in JEI. The fix is not to give the TPP any pressure.

**Comment by StrommKral** [comment]
thank you for the quick response, that was the problem. me being unable to interpret the recipe in jei properly. plugging the pipe to the TPP allowed it do do it's thing.
