### ISSUE TITLE
[FEAT] Scrolling the programs in programmer

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#312]
Scrolling the programs in programmer is sometime tricky would it be possible to:
1) scrolling with the mouse the position of the program under the mouse stays still and the image zooms in and out around it
2) scrolling with the scrollbar the position of the centre of the window remains stationary.
3) Have a program fills window button.

### Mod Version
1.12.2-0.9.3-324

**Comment by desht** [comment]
Yeah I'm aware of 1 and 2, and tried to fix that before, without success. That part of the code is a bit mind bending  :)  I'll have another look though, maybe I'll get some inspiration. 

Point 3 would be useful and I'll see what can be done with that.

**Comment by duncanwebb** [comment]
Don't know the code, sounds tricky. Thanks anyway for all your efforts.

**Comment by duncanwebb** [comment]
This is looking very good with the latest version, pneumaticcraft-repressurized-1.12.2-0.10.3-337.

**Comment by desht** [comment]
Think this is all good, closing now.
