### ISSUE TITLE
Client side crash

### ISSUE THREAD

**Issue by SacrificialFlame** [TeamPneumatic/pnc-repressurized#314]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.5.2808
### Mod Version
1.12.2-0.10.0-328
### Describe your problem, including steps to reproduce it
Launch game and crash before loading screen
### Any other comments?
https://gist.github.com/SacrificialFlame/2309f869c66cfa80efa642b09d6254ff

**Comment by desht** [comment]
See #313, fixed in dev, will be fixed in next release.
