### ISSUE TITLE
Suggestion Stirling compressor

### ISSUE THREAD

**Issue by DevTimur** [TeamPneumatic/pnc-repressurized#316]
Add early game Stirling compressor so you can utilize excess heat and cold from machines. Like vortex tube. I vent cold into heat radiator. Basically waste it. With striking compressor I can utilize it.
I think it would be fun.

**Comment by desht** [comment]
Do you have some examples of machines which convert heat differentials directly to pressure?  I'm aware of thermoelectric generation, but not of direct air compressing.  Such a system would also require both hot and cold sources, so it wouldn't be just a simple matter of utilizing cold air from your vortex tube.

It's kind of a neat idea, but I'm not convinced...

**Comment by DevTimur** [comment]
Well.... i can't find any Heat/Cold to Pressure engines, because there is none. Stirling engines is quite experimental and mostly a gimmick because of low efficiency. But, in your mod Heat+Cold => Presure generator will fit well enough, and will have slightly more sense then... idk... Lightning => Pressure generator.
Most of your compressors have idea in mind that "give them fuel or power, and they will PUMP air", basicaly they all MECHANICAL pumps. You could say solid fuel generator make pressure by heat produced by coal or other fuel, but... advanced compressor LOSE efficiency when overheated. That mean it is mechanical aswell, not thermodynamical (or whatever).

So, Stirling engine...
It require Heat and Cold to work. And more heat against cold difference it get, more efficient it is.
And torque it generate can be used to PUMP air.

You know... the more i think the more i understand, your compressors... "...MAKES NO GODDAMN SENSE!" (c) Austin Hourigan
1) first compressor (fuel to pressure) does not have ANY mechanical components in recipe. If you ment it generate pressure by heating air, then how does is keep pressure up? If air cool down in pipes it shrinks again. Also, adv compressor lose efficiency by overheating, but in main idea it should get more efficient. That means it MUST be mechanical pump using fuel... somehow... to generate torque... idk...eh. Is it stirling engine undercover? Or steam engine? Because you must convert heat energy into torque somehow, and then convert it to pressure...
2) Lightning compressor, forgot it name. How da hell does it ment to work? Got any IRL analogues?
Does anyone ever use it? In game i meant...
3) Liquid fuel compressors... actually quite reasonable. They use fuel to run fuel engine, and convert torque into pressure using simple pump. Only one issue i got with it... Rotor... it got no sense. You can't expect big pressure using simple FAN as pumping mechanism. You need actual PISTONS (not wooden one, pistons like in a car). You can probably use cylinders for that, makes more sense.
4) Powered compressors. Same deal as fuel compressors, pumping mechanism. But also... powered compressor is VERY easy to use. If i can, i just skip advsolid/liquid/advliquid and especially lightning compressors, and rush to powered ones. Just because they are VERY easy to use. No brain required.

That is all i wanted to say. Sorry if i hurt your feelings. That's just my thoughts in loud.

**Comment by desht** [comment]
Nah, those are all fair comments.  In defense, this is a game where you can carry hundreds of tons of gold blocks in your inventory and have chunks of rock hanging in mid-air, so... :)  But I get your point about realism.  Just not convinced about the balance of a "thermopneumatic compressor".  Not saying no, since it's a good idea, but I feel it needs to be more interesting than just "hot side + cold side = pressure and you're done"...

As for recipes, I've no intention of making the standard recipes more expensive; realism isn't much fun when players are cursing the amount of microcrafting needed just to get started with the mod.  But at the same time I have no objections if a modpack wants to change them around.

**Comment by desht** [comment]
Added in 0.11.0 release (called the Thermal Compressor rather than Stirling Compressor)
