### ISSUE TITLE
Regulator not working

### ISSUE THREAD

**Issue by thelapisfox** [TeamPneumatic/pnc-repressurized#317]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2781
### Mod Version
1.12.2-0.9.1-317
### Describe your problem, including steps to reproduce it
Regulator Tube Module is not working for me as it does not stop airflow like it should.

1. Attach Regulator to tube.
2. Apply redstone (I have applied a signal of 8).
3. Run compressors.
4. Watch as pressure tubes beyond the narrow point of the Regulator exceed the threshold.

With my current setup, I have the regulator attached to an advanced pressure tube going to the assembler. I had it set up for 5.0 bar, but the assembler kept blowing up. I tried to reduce it to 4.0 bar and same thing. I eventually had to apply a redstone signal of 8, which lowers the Threshold to 3.5 bar. I also had to add a safety tube module beyond the regulator that had a restone signal of 6 for a bar of 4.5. If the regulator was working right, the safety tube module would never go off, but it is constantly releasing compressed air. Even though the regulator is setup with a Threshold of 3.5 bar, the assembly controller is always around 4.7 bar.

### Any other comments?
This is with the 1.59 version of Enigmatica 2 (standard not expert).

**Comment by desht** [comment]
I can't reproduce this.  Just connected a regulator between advanced and regular tubes; 15 bar on the high side, gave the regulator 8 redstone, and it regulated to 3.5 bar on the low side, as expected.

Can I see a screenshot of your setup please?

**Comment by desht** [comment]
Closed due to lack of response.
