### ISSUE TITLE
This is a crash report

### ISSUE THREAD

**Issue by magcicada** [TeamPneumatic/pnc-repressurized#319]
I don't konw why the game crashed,sience I used the virsion 0.10.0-328 or 0.10.1-330,the game was continually crashing.
[crash-2019-03-29_12.41.12-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/3022199/crash-2019-03-29_12.41.12-client.txt)

**Comment by desht** [comment]
Not sure why this is happening, but I've added some extra sanity checking which should prevent the crash.  Can you test out build 331 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ and let me know if it helps?

You might also see some warnings in your log like "unable to retrieve custom heat entry for fluid XXX" - if you see those can you paste them here please?  That would be really helpful in tracking down which fluid has the problem.

**Comment by magcicada** [comment]
I think it should be a problem with the coolant of ic2.

**Comment by magcicada** [comment]
Although there is no warning, the coolant does not provide heat or change to another liquid.

**Comment by magcicada** [comment]
And there seems to be a problem here in the BlockHeatProperties.cfg file.
![20190330001921](https://user-images.githubusercontent.com/45464670/55247050-8fe63b80-5281-11e9-8793-02a108f6d6bb.png)

**Comment by desht** [comment]
Are you running now with build 331?

Regular IC2 coolant "ic2coolant" is room-temperature so won't change any machine temperatures (easiest test is to put a fluid down beside a compressed iron block and see what the block's temperature does).

IC2 Hot coolant "ic2hot_coolant" is very hot and should rapidly heat up any machine it's next to, eventually turning into "ic2_coolant" once enough heat has been extracted.

What problem do you see in  BlockHeatProperties.cfg?  Those entries look OK to me.

**Comment by magcicada** [comment]
The first one I selected was that the hot coolant provided 20,000 heat and turned into the coolant. The second one was that the coolant supplied 20,000 heat and turned into hot coolant. This is the default data. I think this is a mistake.

**Comment by magcicada** [comment]
And I did use the build 331 version.

**Comment by desht** [comment]
Yeah it is the default data, but not a mistake.  "totalHeat" is the overall heat _capacity_ - the amount of heat the block can gain _or_ lose before it transforms to another blocks.  I admit that's a bit misleading but the comment at the top of that file explains what those fields mean.

So "ic2hot_coolant" can lose up to 20000 heat before it turns into "ic2coolant" (va the ``transformCold`` line).  Because it has no ``transformHot`` line, it won't transform if it gains too much heat.

Similarly "ic2coolant" (the cool stuff) can gain 20000 heat before turning into "ic2hot_coolant", and it won't transform if it loses heat.

**Comment by magcicada** [comment]
I tested all the marked fluids in BlockHeatProperties.cfg without any warnings, and I don't think I can afford more help.I haven't tried those solids yet, but at least the game didn't crash.

**Comment by desht** [comment]
OK, thanks for the input.  Just to note that _all_ fluids actually have heat properties - the temperature is defined by the mod that adds them (e.g. hot coolant is around 1000C), and if they're not explicitly listed in the .cfg file, they have default thermal resistance = 100 and default total heat capacity = 10000 (see the "defaults" section of the file.

So e.g. blazing pyrotheum should still heat your refinery even though it's not listed there.

I'll do some more testing this weekend and verify everything is working as it should be.  It's odd you didn't get any warnings from build 331, the null check I added does log a warning if it detects a null that caused the crash in build 330.

**Comment by magcicada** [comment]
Now it’s already in Beijing time, 0:45, I am very sleepy now, I think I should continue to experiment tomorrow.:)
![20190330004832](https://user-images.githubusercontent.com/45464670/55248895-bb6b2500-5285-11e9-9307-117863c08eef.png)

**Comment by desht** [comment]
This should all be working now, so closing.
