### ISSUE TITLE
Aerial Interface and Baubles integration

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#322]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2768
### Mod Version
1.12.2-0.9.3-324
### Describe your problem, including steps to reproduce it
From what I've read the aerial interface is supposed to pump air into the armour. I can't get this to work.

I've tried with and without a dispenser upgrade. Pointing the charging module at the aerial interface. Adding a advanced PCB to the charging module.

The armour has a charging upgrade in it.

### Any other comments?
Power work fine for items in the inventory but not the bauble slots.

Thanks,

**Comment by desht** [comment]
To charge the armour, you will need to put a charging module on a pressure tube pointing at the Aerial Interface, and ensure that side of the interface is connected to the armour slots (via the Side Configuration tab).

There isn't any Baubles support right now, but that wouldn't be too hard to add...

**Comment by duncanwebb** [comment]
If I understand this correctly it should be like this?
![image](https://user-images.githubusercontent.com/4198031/55432269-c0d0b400-5592-11e9-9223-ca20292fef19.png)
![image](https://user-images.githubusercontent.com/4198031/55432397-14430200-5593-11e9-98a6-16e3180b04d3.png)

Bauble support would be just great.

**Comment by TeamSpen210** [comment]
You'd need to place it one block closer, there's a gap there.

**Comment by duncanwebb** [comment]
I did that first but may not have set the sides correctly. Now I've moved it back and it is working perfectly.

Many thanks again for your help. Also this mod has lots of cool features it must take a lot of time to maintain. Thanks for this too.

**Comment by desht** [comment]
Excellent.  Going to leave this open as a reminder for the Baubles integration.

And yep, there is indeed a lot to maintain, but it's fun.  Much of the credit must go to Minemaarten though, who created the mod in the first place :)

**Comment by desht** [comment]
Added on 0.10.3 release
