### ISSUE TITLE
BlockHeatProperies.cfg Client Crash

### ISSUE THREAD

**Issue by utoxin** [TeamPneumatic/pnc-repressurized#324]
### Minecraft Version
1.12.2

### Forge Version
14.23.5.2808

### Mod Version
0.10.2

### Describe your problem, including steps to reproduce it
Loading minecraft causes a NullPointerException in BlockHeatPropertiesConfig

### Any other comments?
See log here: https://pastebin.com/WNku5udk

**Comment by desht** [comment]
This should be fixed in build 333 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ - feel free to try that out.

There will be a  0.10.3 release in the next few days.

**Comment by utoxin** [comment]
Tested and confirmed. Thanks for the quick fix. :)

**Comment by desht** [comment]
Fixed in 0.10.3 release
