### ISSUE TITLE
Dupe bug with Liquid Hoppers

### ISSUE THREAD

**Issue by Freebi85** [TeamPneumatic/pnc-repressurized#325]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
Dupe bug with Liquid Hoppers. If one rightclick with a liquid hopper in hands on a tank, then the liquid goes into the tank and stays in the hopper at the same time. This is how the dupe is created.

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Fixed in 0.9.4 release (and also in latest 0.10.3 Jenkins build 334)
