### ISSUE TITLE
Crafttweaker Support for Plastic Mixer

### ISSUE THREAD

**Issue by TedKnudsen** [TeamPneumatic/pnc-repressurized#326]
Greetings desht et al:

Would like to be able to tweak inputs and outputs, particularly the input fluid (oddly I'll grant)

Possibly overlaps with #318.  Didn't see any other conflicts.

If that's too annoying to implement, I have alternative plans that would work with just a configurable input fluid type (<somemod:fluid_super_nifty_plastic>).

Or you know, none of the above, whichever.  Mod's still the best.

**Comment by desht** [comment]
Adding alternative input plastic fluids wouldn't be a problem, and Crafttweaker is probably the easiest way to handle that. While the ratio can be configured in config (as you've seen in #318), it might also be useful to allow that via CT.

Configurable outputs is more of a problem though:
* Would dyes be used? 
* How would the output selection GUI side tab function? It's pretty specifically geared toward different colours of plastic right now...

**Comment by pyure** [comment]
(FYI I accidentally posted this request under my non-minecraft account)
Honestly I simply ruled out CT-outputs as more-work-than-worth.  The plastics-selector looks extremely baked-in.

Giving us an array of IItemStack for the outputs selector works in theory from a user-perspective for the plastics, but from what you're saying it would require something of a refactor.

I don't think there's much you can do with the dyes buffers at all.  Anything I can think of would be pretty gross in a cost/benefit analysis.  Not saying we wouldn't find a use for it, but really the biggest problem is simply being able to define the liquid that goes in in the first place.

**Comment by desht** [comment]
OK, support added.  Docs will be on https://crafttweaker.readthedocs.io/en/latest/#Mods/PneumaticCraft_Repressurized/PneumaticCraft_Repressurized/ eventually, but for now:

```
# to add a new fluid as a valid plastic mixer input
# e.g. 100mB lava makes one plastic sheet
mods.pneumaticcraft.liquidplastic.addLiquidPlastic(<liquid:lava>, 100);

# to remove an existing input fluid
mods.pneumaticcraft.liquidplastic.addLiquidPlastic(<liquid:plastic);

# to remove all existing input fluids
mods.pneumaticcraft.liquidplastic.removeAllLiquidPlastics();
```

**Comment by pyure** [comment]
Thanks desht :)

**Comment by desht** [comment]
Added in 0.10.4 release.
