### ISSUE TITLE
Crash using coordinate puzzle piece

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#327]
### Minecraft Version
1.12.2
### Forge Version
forge-1.12.2-14.23.5.2768-universal
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.10.3-337
### Describe your problem, including steps to reproduce it
Clicking the area GPS tool in the GPS target causes the game to crash
### Any other comments?
The crash happens as the area tool is clicked.
![javaw](https://user-images.githubusercontent.com/4198031/56141180-9fad9180-5f9c-11e9-93c6-a9d11739e7da.gif)

**Comment by desht** [comment]
Do you have a stack trace for this crash?

**Comment by duncanwebb** [comment]
Yes sure, I have a few hopefully it is this one.
[crash-2019-04-15_16.19.50-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/3100219/crash-2019-04-15_16.19.50-client.txt)

**Comment by desht** [comment]
Yeah, got it.  Should be an easy fix...

**Comment by desht** [comment]
OK, next update will allow GPS Area tools to be used (and not crash if an unconfigured area tool is selected).  Note however that if the area tool contains multiple positions, an arbitrary position within the area will be selected.

**Comment by duncanwebb** [comment]
Thank you very much again for your effort and help. You could alternate between point 1 and point 2.

**Comment by desht** [comment]
That's actually trickier than it might initially appear (due to the way the the GPS tools are coded - they use the same interface which gets a list of all the blocks to highlight).  While it *could* be done, I'm not sure of the value, and it would introduce a lot of code clunkiness.

In any case, it's usually a lot quicker and easier just to click the GPS (Area) Tool onto the programming area directly to add or update an Area piece. The GUI popup is actually the older system for updating.

**Comment by duncanwebb** [comment]
No problem it was just an idea.

Could bug this have caused drone duplication, if so I don't need to report it? 

I have about six additional drones in a chest but only four crash reports. The farming drone with a few magnet upgrades and placed items in this chest. It sits a few blocks away from where I was testing the program. 

I hope you don't mind questions and bug reports.

**Comment by desht** [comment]
Hmm, not sure about the duplication.  I haven't seen that before but it's possible I suppose...

And yeah, I totally don't mind questions & reports, anything that helps improve the mod quality is a good thing :)

**Comment by desht** [comment]
Fixed in 0.10.4 release.
