### ISSUE TITLE
Crash when testing security station

### ISSUE THREAD

**Issue by Sakata-MC** [TeamPneumatic/pnc-repressurized#329]
### Minecraft Version
1.12.2
### Forge Version
FML: MCP 9.42 Powered by Forge 14.23.5.2825 330 mods loaded, 330 mods active
### Mod Version
| LCHIJA | pneumaticcraft                    | 1.12.2-0.9.4-CUSTOM       | pneumaticcraft-repressurized-1.12.2-0.9.4-1.jar           | None                                     |
### Describe your problem, including steps to reproduce it
io node top right, diagnostic bottom left, green node just above. Folder nodes in all other squares. press test, reinforce the IO node, and instantly crash
### Any other comments?
[crash.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/3099742/crash.txt)

**Comment by desht** [comment]
The crash suggests the code isn't finding an IO port.  I'll do some testing and try to reproduce this.

**Comment by desht** [comment]
I couldn't reproduce this in testing.  Can you provide a screenshot of your setup (or even better a video) ?

**Comment by desht** [comment]
Closed due to lack of response.
