### ISSUE TITLE
Does $drone work?

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#331]
### Minecraft Version
1.12.2
### Forge Version
forge-1.12.2-14.23.5.2768-universal
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.10.3-337
### Describe your problem, including steps to reproduce it
The drone variable always shows 0,0,0 wherever it is. More that likely I'm doing something incorrectly.
![2019-04-22_18 46 34](https://user-images.githubusercontent.com/4198031/56512431-9d64ad80-652f-11e9-9567-55c8fc719fd5.png)
https://pastebin.com/2Qrhezwt

### Any other comments?
The patchouli manual says use $drone but I think this should be ${drone} as $drone shows $drone.

**Comment by desht** [comment]
Yeah, the docs are a bit muddled here, my fault.  There are actually three types of variable:

* Local variables (no prefix)
* Global variables (prefix the var with a '#')
* Special variables (prefix the name with a '$') - these are documented in the Coordinate Operator manual page

On top of that, there is the ``${varname}`` syntax used to interpolate variables into text in places like the sign edit widget or drone rename widget.

So, to interpolate the special ``$drone`` variable into the drone name, you would need ``${$drone}``.

Yeah, it's confusing.  Had me scratching my head for a bit too :)

**Comment by duncanwebb** [comment]
Thank you I thought I was doing something incorrectly and I even read the manual page.
