### ISSUE TITLE
Duplicatication of drones and items

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#332]
### Minecraft Version
1.12.2
### Forge Version
forge-1.12.2-14.23.5.2768-universal
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.10.3-337
### Describe your problem, including steps to reproduce it
I'm not 100% sure what is happening but breaking items near a drone with 5 magnet upgrades may be causing these items to duplicate. I've seem duplicated drones and aphorism tiles
### Any other comments?
My chestplate has 2 magnet upgrades installed. The duplication happens infrequently, making it difficult to analyse.

**Comment by desht** [comment]
I've made a few changes here which may hopefully resolve this (haven't seen dupe issue myself but I can see the potential).  Can you give build 342 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ a go and let me know if it helps?  I know it's an intermittent problem so may take a while to get an idea if it's helping or not.

**Comment by duncanwebb** [comment]
Running pneumaticcraft-repressurized-1.12.2-0.10.4-342 now. Cyan damage bars :-)

Will let you know if I see any duplicated items. Thanks

**Comment by desht** [comment]
Yeah I changed the pressure bars since they're not actually showing damage.  Wanted to distinguish them from regular damage bars :)  What do you think?

**Comment by duncanwebb** [comment]
Very cool, cyan feels like air pressure. Does armour have a second bar as it can take damage, I have life upgrades so I rarely see damage?

**Comment by desht** [comment]
Yeah the armour will display both bars if necessary.

**Comment by duncanwebb** [comment]
I've not had a duplicate item since running 0.10.4-342 and I've developed a fairly large program, which means that I've been frequently breaking items.

**Comment by desht** [comment]
Excellent.  Expect a 0.10.4 release very soon :)

**Comment by desht** [comment]
Fixed in 0.10.4 release.
