### ISSUE TITLE
Substantial frame lag when charging amadron tablet in charging station

### ISSUE THREAD

**Issue by X1machinemaker1X** [TeamPneumatic/pnc-repressurized#335]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.5.2808
### Mod Version
1.12.2-0.9.1-317
### Describe your problem, including steps to reproduce it
I put the Amadron tablet into the Charging Station and instantly had a massive drop in frames. Removing the tablet fixes the issue 100% of the time.

*EDIT: This same issue happens in the UV Light Box while working on a pcb*
### Any other comments?
It only happens when the tablet is actually charging up. If it is charged to the pressure level of the system, it does not cause the frame drop.

**Comment by desht** [comment]
This should have been fixed way back in 0.7.3.  It's not a problem I can reproduce on my test world. 

Are you on a server or a single player world?

How many speed upgrades in your charging station?

**Comment by X1machinemaker1X** [comment]
I am on a server (Project Ozone 3). And there are no speed upgrades. Only a security one.

**Comment by desht** [comment]
Yeah there might be something going on with excessive packet sending and it would be more noticeable on a server.

I'll do some debugging and see if there's room for improvement there.

**Comment by desht** [comment]
Yep, found and fixed.  Fix will be in the imminent 0.10.4 release.

**Comment by desht** [comment]
Fixed in 0.10.4 release.
