### ISSUE TITLE
Ghost machines

### ISSUE THREAD

**Issue by X1machinemaker1X** [TeamPneumatic/pnc-repressurized#336]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.5.2808
### Mod Version
1.12.2-0.9.1-317
### Describe your problem, including steps to reproduce it
Occasionally when I place down a pneumaticraft machine (so far its happened with the liquid compressor and thermo... ) it ghost blocks. What I mean is that if I try to break it, the block doesn't drop and placing say a piece of cobble in its place makes the machine show up again. Further attempts to break it result in the same problem. Trying to break the block with the Embers block breaker resulted in a full crash. This is not consistent and I can't see a pattern.

**Comment by desht** [comment]
This bug was fixed in 0.9.2.
