### ISSUE TITLE
Crash when connecting air compressor to charging station directly

### ISSUE THREAD

**Issue by benserwa** [TeamPneumatic/pnc-repressurized#338]
### Minecraft Version
1.12.2

### Forge Version
14.23.5.2836

### Mod Version
0.10.4-343

### Describe your problem, including steps to reproduce it
1. Spawn an Air Compressor and a Charging Station in via JEI
2. Place the Air Compressor down
3. Place the Charging Station down against it backwards (they're not lined up properly)

### Any other comments?
Doesn't seem to occur in version 0.10.3-337.

Here's the log: https://paste.dimdev.org/ruwexalojo.mccrash

**Comment by desht** [comment]
Fixed in 0.10.5 release.
