### ISSUE TITLE
Suggestion Multiblock Hydraulic Robots (MHR)

### ISSUE THREAD

**Issue by dawonder113** [TeamPneumatic/pnc-repressurized#339]
can you pls add multiblock hydraulic robots.
Details:-
To create this robot you need 3 items - hydraulic pipes, remote control
and obviously blocks. 

first you need to add two legs with:-
legend: block=# hydraulic pipe=| one block space = -  remote control= +

###
|-  |
#-#

for the body
#+#
###

for the arms (both will be same)
#
|
#

for the head 
#

full structure will be
           #
       ##+##
       |  ### |
       # ### #
          |   -|
         #   #

Functions:
W to walk forward
A to strafe left
D to strafe right
S to go backwards
SPACE to jump
______________________

it will suffocate all entities in its path
it will sink in water
and it will fly
it will also pick up things
______________________________-

P.S All this is fictional and no realism is present.
Edit: if the devs want images of the structure
pls tell me

**Comment by desht** [comment]
I'm not really sure what purpose this would achieve.  Is it supposed to be some golem-like entity?

I have to say, given the effort required versus the utility of this, I don't foresee adding this in the near future.  But if you can expand on your ideas, I'm prepared to listen.

**Comment by desht** [comment]
Closed due to lack of response.

**Comment by dawonder113** [comment]
Oh sorry I did not see the replies
