### ISSUE TITLE
[Feature/Suggestion] A way to purge Processing Plant Input

### ISSUE THREAD

**Issue by Targren** [TeamPneumatic/pnc-repressurized#340]
I would suggest some way to purge the input tank of the Thermopneumatic Processing Plant, since as it is (in 0.10.3-337, as seen in PO3) the process stops when there's not enough input to make a full run of it, which means the only options are to somehow manage to get exactly enough input in for one more run (haven't figured out a way to do this yet), or to stop processing anything altogether until you can completely fill the input tank and run it all the way through.  This is biting me trying to use mass storage for liquids (in my case, a Tinker's Tank multiblock

If there's a way to do this already that I'm missing, then please disregard (and maybe tell me? :) )

**Comment by desht** [comment]
Yeah there was a button to do that before but I removed it, which I now realise was a bad idea :)  Expect to see it back in the next release.

**Comment by desht** [comment]
Added in 0.11.0 release
