### ISSUE TITLE
Thermopneumatic Plant not recognizing valid input?

### ISSUE THREAD

**Issue by Targren** [TeamPneumatic/pnc-repressurized#341]
### Minecraft Version
1.12.2

### Forge Version
14.23.5.2836

### Mod Version
1.12.2-0.10.3-337

### Describe your problem, including steps to reproduce it

After running out of kerosene on the last processing job, which worked (that led to suggestion in #340), I turned the machine off by setting it to "High Signal" to let the tank fill completely, then turned it back to "Always enabled"

Input tank is full of Kerosene, Output tank is empty, Temperature is 422C, Pressure is 4 bars. 

According to JEI, this should be producing fuel. Instead, the machine is telling me "no valid input or no room for output". Restarting the server is the only fix for this I've managed to find. 

Edit: On further testing, adding and removing coal from the UI (not a valid recipe) seems to reset the recipe. I think it may be related to #321. 

The problem isn't specific to kerosene. It's done it to me today with Diesel as well. 

### Any other comments?

Screenshots: https://imgur.com/a/96SjLtW

**Comment by desht** [comment]
This was fixed in 0.10.4 (although you should update to 0.10.5).
