### ISSUE TITLE
Cannot craft plastic that is on the bottom/right row

### ISSUE THREAD

**Issue by evenas98** [TeamPneumatic/pnc-repressurized#344]
1.12.2

forge-14.23.5.2836

1.12.2-0.10.5-346

i can only craft plastics that show the name of the plastics (better seen in the pictures below).

As you can see in the pictures the bottom row is outside the green border and therefore i cant click them, it also happens on the right row when my mouse pointer outside of green border
gets worse if minecraft is not fullscreen? my res is 2560x1440p when fullscreen. also happens without texture patch

Seperate but i think it corresponds with my issue above:
 text is cut of the available fuels tab on liquid compressor, mod not scaling correctly on 1440p res?

![2019-05-21_17 02 33](https://user-images.githubusercontent.com/6554873/58107618-82e32a00-7bea-11e9-9cd1-03f67f368fa2.png)
![2019-05-21_16 48 38](https://user-images.githubusercontent.com/6554873/58106743-e1a7a400-7be8-11e9-8fda-4735fcbe8177.png)
![2019-05-21_16 48 39](https://user-images.githubusercontent.com/6554873/58106744-e2403a80-7be8-11e9-8f96-d52ff5d41831.png)
![2019-05-21_16 48 40](https://user-images.githubusercontent.com/6554873/58106745-e2403a80-7be8-11e9-8080-a5ec38fd976a.png)
![2019-05-21_16 49 01](https://user-images.githubusercontent.com/6554873/58106746-e2403a80-7be8-11e9-892d-31f15a7771f1.png)
![2019-05-21_16 49 03](https://user-images.githubusercontent.com/6554873/58106748-e2403a80-7be8-11e9-88f2-06a6aca03be1.png)
![2019-05-21_16 48 37](https://user-images.githubusercontent.com/6554873/58106750-e2d8d100-7be8-11e9-8c70-dd8061f8bfb1.png)
when streching my minecraft window i am able to manipulate the green border not allowing me or allowing me to craft the plastics:
![2019-05-21_17 07 51](https://user-images.githubusercontent.com/6554873/58107869-1157ab80-7beb-11e9-8384-9bb721e2866f.png)
![2019-05-21_17 07 59](https://user-images.githubusercontent.com/6554873/58107872-13216f00-7beb-11e9-88af-ba93c5df4bb1.png)

**Comment by desht** [comment]
This will be difficult for me to test, since I don't have a 1440p monitor (1080p is the best I can test with).

**Comment by evenas98** [comment]
i belive it should show on 1080p if your drag/stretch the mc window? like the 2 bottom pictures

**Comment by desht** [comment]
I'll give that a go when I'm at my dev machine next.

**Comment by desht** [comment]
I've added some code to do some better sizing calculations for the side tabs - should work for almost all situations (short of making the screen stupidly narrow). You can test this out in build 358 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized.  Or wait until the 0.11.1 release.

**Comment by desht** [comment]
Fixed in 0.11.1 release.
