### ISSUE TITLE
Plastic mixer input into output

### ISSUE THREAD

**Issue by Coolcabbage** [TeamPneumatic/pnc-repressurized#345]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2838
### Mod Version
1.12.2-0.10.5-346
### Describe your problem, including steps to reproduce it
A hopper will insert plastic into the output slot of a plastic mixer

**Comment by desht** [comment]
Yeah, that's not right.  Will be addressed in the next release.

**Comment by desht** [comment]
This should be resolved in build 358 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized if you'd like to test.  Or wait until the 0.11.1 release.

**Comment by desht** [comment]
Fixed in 0.11.1 release.
