### ISSUE TITLE
Pneumatic Chestplate not upgradable

### ISSUE THREAD

**Issue by Coolcabbage** [TeamPneumatic/pnc-repressurized#346]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2838
### Mod Version
1.12.2-0.10.5-347 (edit 1.12.2-0.11.0-347)
### Describe your problem, including steps to reproduce it
The pneumatic chestplate is not showing any valid upgrades and will move them back into player inventory if I try to add any more
Any upgrades I had in it before I updated still work (scared to remove them)
I cheated in a new chestplate via jei and it had the same problem even with the same kind of upgrades that are working in my first one
Possibly bugged when adding TaN compat?

**Comment by desht** [comment]
I think I'd need to see your full startup log here. Sounds like something has gone wrong in init.

**Comment by Coolcabbage** [comment]
Did some more testing
new world, still happens
new instance with just forge stuff and pneumaticcraft, still happens
Below is a log of the startup and going into that stripped instance and opening the upgrades of a chestplate in a charging station
https://pastebin.com/2vF61JmC

**Comment by desht** [comment]
TaN compat wasn't added until 0.11.0 but you're running 0.10.5. Have you run a dev build and then gone back to 0.10.5?

I suspect the nonexistent AC upgrade is what's causing the crash - away from my dev machine for the next few days but I'll take a look when I can.

**Comment by Coolcabbage** [comment]
only upgrade of pneumaticraft in that world was from 346-347
sorry just noticed I put version wrong in op , should be 1.12.2-0.11.0-347
I copy pasted the upper section from previous post to avoid having to retype forge version and didnt notice the the middle part of the mod version had changed

**Comment by desht** [comment]
This should be fixed in build 359 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/changes if you'd like to test (0.11.1 release coming soon).

Note this also makes some changes to how armor GUI panels (pressure display etc.) are positioned so you might need to adjust those the first time you launch this version. See https://github.com/TeamPneumatic/pnc-repressurized/blob/master/Changelog.md for more info.

**Comment by desht** [comment]
Fixed in 0.11.1 release.
