### ISSUE TITLE
Changing Dimensions cause armour to stop working

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#347]
### Describe your problem, including steps to reproduce it
When going from the Overworld to the End or Nether the armour stop working. I think this was working in version 0.10

Many thanks again.

**Comment by desht** [comment]
Confirmed.  Think I know why...

**Comment by desht** [comment]
OK, build 362 should fix this.  Hopefully will be in a 0.11.2 final release soon...

**Comment by duncanwebb** [comment]
Many thanks, you're super fast. :-)

**Comment by desht** [comment]
Fixed in 0.11.2 release
