### ISSUE TITLE
Liquid Hopper won't go in a charging station

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#349]
### Minecraft Version
1.12.2

### Forge Version
1.12.2-14.23.5.2768

### Mod Version
1.12.2-0.11.2-364

### Describe your problem, including steps to reproduce it
Cannot place a liquid hopper into the charging station.

**Comment by desht** [comment]
It's not a chargeable item...

**Comment by Coolcabbage** [comment]
I think the actual problem here is the mouseover text of a liquid/omni hopper that has no upgrades in it will prompt you to insert it into a charging station to install upgrades
"Insert in a Charging Station to install upgrades"

**Comment by desht** [comment]
Oh. Yeah that would be a bug!

**Comment by duncanwebb** [comment]
IIRC the liquid hopper can take speed upgrades and dispenser upgrades - just checked and my aged memory was correct.

**Comment by desht** [comment]
Yes, it can - but it's a block, so you insert upgrades into the block when it's placed down. The charging station is used for inserting upgrades into (non-block) items.

The next release will, however, not include any misleading "Insert in a charging station..." messages for items that definitely don't go into a charging station.

**Comment by duncanwebb** [comment]
Thanks for the help. I knew I'd added upgrades to it but had forgotten how.

**Comment by desht** [comment]
Fixed in 0.11.2 release
