### ISSUE TITLE
Air Grate tube module filters not working all the time

### ISSUE THREAD

**Issue by ct-klein** [TeamPneumatic/pnc-repressurized#350]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### pneumaticcraft-repressurized-1.12.2-0.11.0-357.jar

Air grate tube module filter doesn't always work. 

I am trying to set a filter in the air grate to exclude pushing my player around.  I added the Advanced PCB to an air grate and for the filter I have tried putting !Irongron (character name).  Entity Filter: "Irongron" appears in the Air Grate Tube Module mouse-over. Clicking anywhere outside of the entity filter GUI causes the ! in front of the name to disappear.

If I just hit ESC after entering in !Irongron the air grate tube filter will work 'for a while' not pushing the character away but after some random amount of time (or movement away) it will start again.

Any ideas?  Thanks!

**Comment by desht** [comment]
I'll check this when I can, but my dev computer is currently dead, so it might be a few days...

**Comment by desht** [comment]
Fixed in 0.11.2 release
