### ISSUE TITLE
[Bug] - Crash on world load

### ISSUE THREAD

**Issue by BasieBrinkie** [TeamPneumatic/pnc-repressurized#351]
### Minecraft Version

> 1.12.2

### Forge Version

> 14.23.5.2838

### Mod Version

> 0.11.2-365

### Describe your problem, including steps to reproduce it
I updated the mod from version 0.10.5-346 to version 0.11.2-365. Then I joined a world and I could see the world for a short amount of time. Only the rendering was a bit off. The world was more blue than normal and also didn't load in blocks. After that the game did crash. The two  crash-reports that were created after the crash: https://gist.github.com/BasieBrinkie/d32d3210ea128dfcf42c7358b69464d3, https://gist.github.com/BasieBrinkie/d6c49707ced1d9479e8498d4ff707b36

### Other Comments
The pack starts in an advanced rocketry dimension right from creation.

**Comment by Zundrel** [comment]
I can confirm this because it happened to me as well using the exact same version of the mod. Looking in the logs it looks like the Armor HUD freaks out a bit right before the crash, so it may be the culprit.

**Comment by desht** [comment]
Yep my fault, sorry about that.  0.11.3 release - now available - fixes it.
