### ISSUE TITLE
[bug] pnc-repressurized drone causes ticking entity crash when harvesting complex crops cucumber

### ISSUE THREAD

**Issue by wideblaze** [TeamPneumatic/pnc-repressurized#352]
Minecraft 1.12.2

Forge 14.23.5.2823

Modpack Digsite 1.0.01

pneumaticcraft-repressurized-1.12.2-0.11.3-366
Complex Crops 1.12.2-4.1.3

pnc-repressurized drone causes ticking entity when harvesting mature complex crops cucumber

crash log in referenced issue link:

https://github.com/wideblaze/DigSite/issues/6

**Comment by desht** [comment]
Bug in Complex Crops, updated the DigSite issue.

**Comment by wideblaze** [comment]
perfect -- thanks for such a timely response
