### ISSUE TITLE
Omni Hopper doesn't load carts

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#353]
### Minecraft Version
1.12.2

### Forge Version
1.12.2-14.23.5.2768

### Mod Version
1.12.2-0.11.3-366

### Describe your problem, including steps to reproduce it
Not sure is this is by design but I cannot use the omni hopper to load Minecraft carts or Moar-Boats with chests.

Here is an example of a Moar-Boats dock that unloads and loads a boat and if the hopper is replaced with an omni-hopper it doesn't load.

![loading-station-1](https://user-images.githubusercontent.com/4198031/60201050-b64b5100-9847-11e9-82c5-7ab2c2b467f7.png)

**Comment by desht** [comment]
Yeah, that's a feature that was just never added. Guess you're the first person to ask for it 😊

I'll look into the feasibility of adding it, anyway.

**Comment by duncanwebb** [comment]
I thought an omni hopper was just a souped-up Minecraft hopper. Sort of surprised that no one asked for this to be used to load of unload a minecart with a chest.

Unloading a cart using an omni hopper is not possible as I couldn't place a track on it, at least the locking rail.

![hopper-under-rail](https://user-images.githubusercontent.com/4198031/60207785-05e54900-9857-11e9-9da0-43eeefd707bf.png)

**Comment by desht** [comment]
No, the omnihopper shares no code at all with the vanilla hopper (just as well because the vanilla hopper is horribly inefficient on sever cpu). It's a complete reimplementation.
