### ISSUE TITLE
Security upgrades cannot be added to pneumatic helmets

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamPneumatic/pnc-repressurized#357]
Minecraft version 1.12.2

Minecraft forge 14.23.5.2838

Mod version 1.12.2-0.11.3-366

Security upgrades cannot be added to pneumatic helmets

Steps to reproduce:
1. Place a pneumatic helmet in a charging station
2. Press the upgrades button
3. Try to add a Security Upgrade

### Any other comments?
1. The security upgrade isn't marked as an allowed upgrade for pneumatic helmets in either the charging station or the security upgrade itself:
![image](https://user-images.githubusercontent.com/22590237/60738962-18821100-9f2e-11e9-806e-dcc916356eda.png)
![image](https://user-images.githubusercontent.com/22590237/60739045-6139ca00-9f2e-11e9-8249-d7e65281b4bd.png)
2. Using the following command, a pneumatic helmet containing a security upgrade can still be obtained (The upgrade is functional)
`/give @p pneumaticcraft:pneumatic_helmet 1 0 {volume:12000,UpgradeInventory:{Size:9,Items:[{id:"pneumaticcraft:security_upgrade",Count:1b,Damage:0s}]},air:120000}`
This upgrade can be removed, but not re-inserted

**Comment by desht** [comment]
Confirmed (and easy to fix, expect it in 0.11.4)
