### ISSUE TITLE
Pneumatic armor reboots upon relogging

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamPneumatic/pnc-repressurized#363]
Minecraft version 1.12.2

Minecraft forge 14.23.5.2838

Mod version 1.12.2-0.11.3-366

When you exit and re-enter the game, Pneumatic armor will restart in initialization
Steps to reproduce:
1. obtain any piece of pneumatic armor, and charge it
2. Equip it, and wait for it to initialize
3. Exit the game
4. Enter the game; The armor will re-initialize

### Any other comments?
This also happens when exiting the nether on a server

**Comment by desht** [comment]
Intended behaviour. Not a bug.
