### ISSUE TITLE
Security station connection lines divert downwards

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamPneumatic/pnc-repressurized#365]
Minecraft version 1.12.2

Minecraft forge 14.23.5.2838

Mod version 1.12.2-0.11.3-366

Self-Explanatory
![image](https://user-images.githubusercontent.com/22590237/60743775-052c7100-9f41-11e9-9b56-bd4927e513ae.png)
Steps to reproduce:
1. Place a security station
2. Place network nodes in a line from the left side to the right side
3. Observe as the connection line slopes downwards

**Comment by desht** [comment]
Confirmed
