### ISSUE TITLE
Security station is hacked after hacking two network nodes

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamPneumatic/pnc-repressurized#366]
Minecraft version 1.12.2

Minecraft forge 14.23.5.2838

Mod version 1.12.2-0.11.3-366

Video:
https://youtu.be/dohIFfVqb7U
![image](https://user-images.githubusercontent.com/22590237/60744146-9d772580-9f42-11e9-8f67-0adb2ea8e709.png)

Steps to reproduce:
1. Place security station
2. Set up network as seen in image
3. Click "Test Security"
4. Click the two nodes connected to the IO port

Edit:
After further testing, it seems only the second node needs to be hacked (The node below the IO port)

**Comment by desht** [comment]
Confirmed.
