### ISSUE TITLE
New Omnihoppers dont stack with old

### ISSUE THREAD

**Issue by Coolcabbage** [TeamPneumatic/pnc-repressurized#368]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2838
### Mod Version
1.12.2-0.11.3-366
### Describe your problem, including steps to reproduce it
Freshly crafted omnihoppers/liquidhoppers do not properly stack with hoppers that have been placed and broken. They sometime appear to stack properly but it is just a desync causing them to get thrown when the inventory is closed
### Any other comments?
They will stack fine with others after placing and breaking

**Comment by desht** [comment]
Sounds like some NBT is getting written when the hopper is broken.  Can you verify there's definitely nothing in the liquid hopper tanks, and no installed upgrades when the hopper is broken?

**Comment by Coolcabbage** [comment]
Yeah, just did a test with 2 new hoppers
Stacked fine
placed and broke one
bugged
placed and broke both(lost track of which was which)
stacking fine again

I installed the NBT Tooltip mod and using that I can't see any difference in the nbt using that but when I use the command /dumpNBT I get 
New Hoppers 
![Fresh Hopper nbt](https://user-images.githubusercontent.com/24936875/60931641-e3d6d680-a2ec-11e9-8d80-4ec697bd8233.png)
With older hoppers it returns No NBT

**Comment by desht** [comment]
Yep, it's saving an empty upgrades inventory.  Not sure where that crept in, but should be an easy fix.
