### ISSUE TITLE
Air Grate Lag

### ISSUE THREAD

**Issue by Nethet** [TeamPneumatic/pnc-repressurized#371]
1.12.2

14.23.5.2838

0.11.3-366

I would use air grates to maximize the efficiency of the heat sinks, but there are this green lines everywhere, which creates tonnes of lag. How can I fix this ?

By the way: you do a great job.
![2019-07-12_21 45 38](https://user-images.githubusercontent.com/38501555/61169565-7bdbf680-a55f-11e9-8eda-0b2b5df51c00.png)

**Comment by desht** [comment]
The green lines indicate the range of the air grate, and shouldn't be causing any lag (it's just a few OpenGL line draw calls, which is very cheap).  However, they can be quite annoying (they appear whenever the pressure of the tube changes), so I think I will probably change it so they're only shown when the air grate is right-clicked (or sneak-right-clicked when upgraded; right-click will show the entity filter GUI in that case).

**Comment by Nethet** [comment]
ok thanks !

**Comment by desht** [comment]
Leaving open until 0.11.4 release (will be in next day or two)
