### ISSUE TITLE
Drone condition: Entity doesn't work

### ISSUE THREAD

**Issue by Coolcabbage** [TeamPneumatic/pnc-repressurized#372]
### Minecraft Version 
1.12.2
### Forge Version
14.23.5.2838
### Mod Version
1.12.2-0.11.4-368
### Describe your problem, including steps to reproduce it
The program piece Drone Condition : Entity always outputs false
![test prog](https://user-images.githubusercontent.com/24936875/61285145-f5d7de00-a7f2-11e9-9e7b-ab7139371e00.png)
Tried it with @player, my actual username and also blank
### Any other comments?
from at least v366

**Comment by desht** [comment]
Fixed in 0.11.5 release
