### ISSUE TITLE
Pneumatic Chestplate says "Air Conditioning not Installed" even when tough as nails isn't present

### ISSUE THREAD

**Issue by FriendlyTurnip** [TeamPneumatic/pnc-repressurized#373]
The chestplate will report that it doesn't have air conditioning even if you don't have tough as nails installed. This is a minor issue but it seems like odd and undesired behavior.

**Comment by desht** [comment]
Yep, that should be easy enough to exclude.

**Comment by desht** [comment]
Fixed in 0.11.5 release

**Comment by Ch1216** [comment]
The glitch is back
