### ISSUE TITLE
hud crash on equipping armor

### ISSUE THREAD

**Issue by FriendlyTurnip** [TeamPneumatic/pnc-repressurized#375]
### Mod Version 0.11.4-368

I can't seem to reproduce this consistently but it happens when equipping pneumatic armor. It might be related to equipping directly from the charging station gui. I have also gotten it to crash in an instance with just pnc.

https://pastebin.com/YBsaYxD9

**Comment by desht** [comment]
I haven't seen this one myself (appears to be some kind of race condition between armor init and HUD display), but looks like an easy fix - just one I can't test...

**Comment by desht** [comment]
Fixed in 0.11.5 release
