### ISSUE TITLE
client crash while making a puzzle program

### ISSUE THREAD

**Issue by gamelnderGamler** [TeamPneumatic/pnc-repressurized#376]
### Minecraft Version 
1.12
### Forge Version
forge-14.23.5.2836
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.10.5-346
(Modpack: "Enigmatica 2" Version: 1.67d)
### Describe your problem, including steps to reproduce it
I middle clicked a cooridnate piece with my mouse (to copy it) and dragged it over a other piece.
After that my client crashed. If i restart and click at the programmer my client crashs again.
Crash report:
[crash-2019-07-24_00.22.35-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/3428593/crash-2019-07-24_00.22.35-client.txt)
### Any other comments?
Thats the first time that happend to me and i use the programmer a lot. So its not really a problem. 
Just wanted to give you the crash report.

**Comment by desht** [comment]
Jenkins build 370 should fix that problem...

**Comment by desht** [comment]
Fixed in 0.11.5 release
