### ISSUE TITLE
Amadron custom offer crashes ATM3 server

### ISSUE THREAD

**Issue by niki9796dk** [TeamPneumatic/pnc-repressurized#377]
### Minecraft Version
1.12.2

### Forge Version
14.23.5.2825

### Mod Version
pneumaticcraft-repressurized-1.12.2-0.9.4-1.jar

### Describe your problem, including steps to reproduce it
Our ATM3 server keeps crashing on startup, and loops like this forever.

It seems from the crash report that the amadron custom offer i made shortly before the first crash might be the root of the problem.

I made the custom offer: 1 pizza for 64 carrots and marked the chests; And the little drone came taking 20 pizzas a time into inventory.
Because this is my first time using this, i wanted to keep some of the pizzas so i removed the chest from which it was restocking from - And shortly after the first crash came.

And the world now seems corrupted.

### Any other comments?
The chunk and whole area around the chest is always chunkloaded.

Crash report: https://pastebin.com/c4mnmeMU

**Comment by niki9796dk** [comment]
I just restored a backup of the world and tried again.

I first removed the chest with nothing in it, and wait a _little_ while and nothing seemed to happen.
Then i added a pizza to the chest, and right after seeing the drone spawn, i broke the chest - The drone came down, did nothing and returned. Shortly after the server crashed, and the world corrupted.

**Comment by desht** [comment]
Fixed in 0.11.5 release
