### ISSUE TITLE
[localization]Some in-game text are in-built in code

### ISSUE THREAD

**Issue by dovisutu** [TeamPneumatic/pnc-repressurized#378]
### Minecraft Version
1.12.2
### Forge Version
1.12.2-14.23.5.2838
### Mod Version
1.12.2-0.11.4-368
### Describe your problem, including steps to reproduce it
Some of the in-game texts are in-built in code, so people **can't** localize them in their language even if they translated the whole `en_us.lang`.
For Example, the status of `security station` (range, security, etc.) in always English despite from the language you chosen, even if it's fully translated.
### Any other comments?
I'm a localizer of PneumaticCraft in [here](https://github.com/cfpaorg/minecraft-mod-language-package), so I'm hoping for the change.
The codes including the problem texts are down here: (I only focused on the security station, so there may be other *hard-coded* texts I didn't notice.
https://github.com/TeamPneumatic/pnc-repressurized/blob/530de9f7f08190d971599827556528a1d2a32d39/src/main/java/me/desht/pneumaticcraft/client/gui/GuiSecurityStationInventory.java#L105-L109
https://github.com/TeamPneumatic/pnc-repressurized/blob/530de9f7f08190d971599827556528a1d2a32d39/src/main/java/me/desht/pneumaticcraft/client/gui/GuiSecurityStationInventory.java#L125-L160
https://github.com/TeamPneumatic/pnc-repressurized/blob/530de9f7f08190d971599827556528a1d2a32d39/src/main/java/me/desht/pneumaticcraft/client/gui/GuiSecurityStationInventory.java#L165-L181

**Comment by desht** [comment]
Yeah, I know.  There's a ton of historic hard-coded text which I've been slowly moving into `en_us.lang`, but there's plenty left to do.

I'll keep this issue open as a reminder...

**Comment by desht** [comment]
I think pretty much everything is in the lang file now, closing.
