### ISSUE TITLE
Pressure Chamber Leaks Pressure When Left The Area Or Relogging

### ISSUE THREAD

**Issue by LoopyStegosaurus** [TeamPneumatic/pnc-repressurized#380]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.5.2838
### Mod Version
1.12.2-0.11.5-371
### Describe your problem, including steps to reproduce it
1. Build a 5x5 pressure chamber
2. Connect a normal air compressor to the pressure chamber using at least 5 pressure tubes
3. Build up the pressure to at least 2.0 bars
4. Log out/ leave the area and come back
### Any other comments?
I've seen a similar issue happen with the original Pneumaticcraft, and this might be the same issue

**Comment by desht** [comment]
In my experience, these issues are invariably due to chunk loading.
1. Is your area chunk-loaded?
2. Does the pressure chamber cross any chunk boundaries?
Keep it all in a single chunk if you can; that's much more reliable.

**Comment by LoopyStegosaurus** [comment]
1. No, I do not believe my area is being chunk loaded, though I am not certain.
2. I checked the chunk boundaries, and my pressure chamber is entirely inside one chunk.

I will double check to see if it is being chunk loaded to confirm.

**Comment by desht** [comment]
I haven't been able to reproduce this, but I'll keep it open for now.

**Comment by MuteTiefling** [comment]
I noticed something similar a very long time ago if I attempted to have 3 or more valves in the pressure chamber.

Basically instead of piping all my compressors through a single line, I wanted to input air from multiple valves. Invariably, when I left the area and came back, one of those valves was no longer connected to the it's pipe. I'd have to break and replace that one valve to fix it. 

This was back in an old version of sevtech and at the time I figured it was more or less intended. Might help you to reproduce the issue?

**Comment by LoopyStegosaurus** [comment]
I have tried a variety of things to try and resolve this issue. I think I have narrowed it down to a chunk issue, like it was previously mentioned. Moving the pressure chamber to a new chunk seems to have fixed it and it is now no longer leaking.

**Comment by desht** [comment]
> I noticed something similar a very long time ago if I attempted to have 3 or more valves in the pressure chamber.
> 
> Basically instead of piping all my compressors through a single line, I wanted to input air from multiple valves. Invariably, when I left the area and came back, one of those valves was no longer connected to the it's pipe. I'd have to break and replace that one valve to fix it.
> 
> This was back in an old version of sevtech and at the time I figured it was more or less intended. Might help you to reproduce the issue?

That was actually a separate bug which I fixed almost as soon as I saw ToAsgaard's playthrough video of it happening :)
