### ISSUE TITLE
Experience collecting

### ISSUE THREAD

**Issue by Sendir** [TeamPneumatic/pnc-repressurized#384]
Make it so a drone is able to collect "fresh" experience from the ground (the orbs mobs drop when killed)
 If my attack drone is able to get those orbs to fall down it would be fun to make a mob farm with drones or make the most of it when I have them defending my base

**Comment by desht** [comment]
Yeah, would be useful.  I'd need to consider how the drone stores any XP it collects (could be via XP fluids added by other mods, or in the absence of those, vanilla Bottles o' Enchanting...)

**Comment by desht** [comment]
This is added in the 1.4.1 release (for MC 1.15.2).  Use the Entity Import puzzle piece, along with a `@orb` entity filter if you need to whitelist/blacklist XP orbs.  Orbs are converted to Memory Essence fluid at a rate of 1 xp = 20mB fluid.
