### ISSUE TITLE
Air cannon - Life extension upgrade working with TnT

### ISSUE THREAD

**Issue by Sendir** [TeamPneumatic/pnc-repressurized#386]
I wanted the other one to shoot TNT at unwanted guests from a mile away and I have no shame to admit it but I've notice something fast, the air cannon can hardly time the TNT to go BOOM as it hits the ground many times it just goes off somewhere on the air or it falls, takes way to long them explodes. Maybe in the Life extension upgrade make it so lit TNT will "live" for as long as it needs so it explodes soon after it lands on the coordinates it was set to land on

**Comment by desht** [comment]
That would be rather difficult to implement (TNT going off after landing, as opposed to on a timer).  It would be easier to add some kind of custom TNT variant that does that...

**Comment by desht** [comment]
Added in 2.7.1 (for MC 1.16.4)
