### ISSUE TITLE
Question on cooling

### ISSUE THREAD

**Issue by Sendir** [TeamPneumatic/pnc-repressurized#388]
How the heck do I manage to cool down a flux compressor with 7+ speed upgrades? I can stick 20 compressed irons having heat sinks on all the sides of said block (ofc on the hot side since I'm pressing the cool side on the flux air compressor) and the compressor will still go to the 500 degrees or 1000 (can't recall exactly) even if by some strange miracle I manage to stable it a bit over the efficiency arrow all that needs to happen to mess it all up is for the system to suddenly need more air pressure(like... adding volume upgrades somewhere...) and steal it away from the vortex. Sudden drop of compressed air in vortex -> Less temperature difference -> less cooling -> Flux compressor overheats like a feminist who as just been told shes wrong -> entire system shuts down because no air flow (this example is only using the 7+ speed upgraded flux compressor for air)

P.S I have my own little modpack to play with and there isn't really any blocks to cool down others, there is cryogenic (I believe that is the name) cooling but I notice during my tests that this liquid will soon turn to just snow given enough time so that's pretty much out of the question.

**Comment by desht** [comment]
Sorry for the slow response here, I missed this one...

Simple answer is: you don't.  You could build a huge array of heatsinks, but to be honest it's not worth it.  You'll get much better results just by using multiple flux compressors with a smaller number of upgrades.
