### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by appleaddict88** [TeamPneumatic/pnc-repressurized#392]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.5.2838
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.11.5-371.jar
### Describe your problem, including steps to reproduce it
Equip the pneumatic helmet and turn on the block tracking thing and it just crashes now whenever i try join the server it crashes for everyone
[crash.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/3639943/crash.txt)

**Comment by desht** [comment]
I don't see anything related to PNC here.  Looks like a Galacticraft problem, plain and simple.  I'd suggest raising an issue with them.
