### ISSUE TITLE
[Feature Request]Drone entity filter for shearing sheep

### ISSUE THREAD

**Issue by mcsaboteur** [TeamPneumatic/pnc-repressurized#393]
Add an entity filter to check if a sheep is sheared, @animal(sheared=yes/no).  Would be a cool addition to a drone's farming capabilities.

Not officially requesting this, but if you're looking at sheep conditions, sheep also have a color condition from 0-15.

Thanks!

**Comment by desht** [comment]
This will be in the 1.1.1 release for 1.15.2.

Color support too, but using color names rather than numbers.
