### ISSUE TITLE
client crashing

### ISSUE THREAD

**Issue by thestungun96** [TeamPneumatic/pnc-repressurized#394]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.5.2838
### Mod Version
1.12.2-0.11.5-371 (not sure what one it means but thats the all the versions it says)
### Describe your problem, including steps to reproduce it
when i try to get on my friends server my i disconnect from it. before it was when i opened the PNC:R manual and went to compressors then when i clicked on air compressor i get kicked out of the server. i know he didnt make any restrictions since its a personal server and not a public one so no chance it being that. but not i cant even get into the server to play. i dont have the error logs cuz i dont have the server logs so i cant post them but i was wondering if you knew. i got up to chaging my minigun so i have the air compressor chamber and charger and thats it. dont know if any of those are the cause but its getting annoying and he doesnt know how to fix it. he hasnt used the mod and isnt far enough into it to have the problems i have. he tried to see if he would crash with the PNC:R manual bit i mentioned but he didnt have the compressor category unlocked yet. so do you know what is happening and if so how to fix it or is it on my end and thats why i cant join. cuz like i said he has no banned items or restrictions to the server.

**Comment by desht** [comment]
Without seeing your client logs, I have zero chance of being able to tell what the problem is.

**Comment by thestungun96** [comment]
ill see if i can get it form him then.

**Comment by desht** [comment]
Closed due to lack of response.
