### ISSUE TITLE
Crop Support Semiblock Crash

### ISSUE THREAD

**Issue by MVethana** [TeamPneumatic/pnc-repressurized#396]
### Minecraft Version
1.12.2
### Forge Version
forge-1.12.2-14.23.5.2836-universal
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.11.5-371
### Describe your problem, including steps to reproduce it
It seems that the semiblocks used by crop supports crash our server. Have had many issues crashes relating to this issue. No reproducible steps. Just happens after some time. On server starts it seems that there is a higher chance for a crash upon initial loadup of the chunk.

[crash-2019-10-26_16.12.59-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/3775421/crash-2019-10-26_16.12.59-server.txt)

**Comment by desht** [comment]
Could you give build 372 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/372/ a go please?  I can't reproduce the problem, but that build has a rework of the code where the error's occurring, and it might help you.

**Comment by bluelightning32** [comment]
The modpack just had a new release today and included pneumaticcraft build 375. Here is the new crash report.
[debug-1.log.gz](https://github.com/TeamPneumatic/pnc-repressurized/files/3827947/debug-1.log.gz)
[crash-2019-11-09_16.43.15-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/3827948/crash-2019-11-09_16.43.15-server.txt)

**Comment by desht** [comment]
Ok, guess I'll keep trying on this one.  Would be really helpful I could actually reproduce the problem myself, but can see a possible change that might help.  If you have any info on what was happening when the crash occurred, that would also be very helpful.

**Comment by bluelightning32** [comment]
It only happens on reboot, before any players login. The sever will crash loop a couple of times then start up successfully. It doesn't happen every time.

**Comment by desht** [comment]
Please give https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/377/ a go if you can; I've pushed another change in the hopes of fixing the problem.

**Comment by desht** [comment]
Closed due to lack of response
