### ISSUE TITLE
Book Crash

### ISSUE THREAD

**Issue by aikainnet** [TeamPneumatic/pnc-repressurized#397]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
forge-14.23.5.2838
### Mod Version
Project Ozone 3 3.1.44, PneumaticCraft version 0.11.5-371
### Describe your problem, including steps to reproduce it
Open the pneumaticcraft book, click the base concepts category, click getting started, click pressure tubes or pressure chamber. Crash.
### Any other comments?
https://pastebin.com/3kLhAXJi

**Comment by desht** [comment]
That looks like a problem in Patchouli to me.  I'd suggest reporting it to them.
