### ISSUE TITLE
Game Breaking Freeze when going above 6 bar on pressure chamber

### ISSUE THREAD

**Issue by teron281** [TeamPneumatic/pnc-repressurized#401]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version

1.12.2 (on Win 10)

### Forge Version

1.12.2 - 14.23.5.2847

### Mod Version

pneumaticcraft-repressurized-1.12.2-0.11.6-374 (newest)

### Describe your problem, including steps to reproduce it

Whenever a 7x7x7 (3x3x3 inside) pressure chamber with at least one "pressure chamber glass" block, reaches a Pressure of 6.0 bar the game freezes and stop responding (no crash log). 

I've tested so far:

removing all other mods except PneumaticCraft - freeze
creative instead of advanced compressor - freeze
3x3x3 pressure chamber - no freeze
7x7x7 pressure chamber without glass - no freeze

The bug is not perfectly reliable, it only happens about 90% of the time.

### Any other comments?
world download of demo world:
[Pneumatic bug test.zip](https://github.com/TeamPneumatic/pnc-repressurized/files/3814841/Pneumatic.bug.test.zip)

**Comment by desht** [comment]
Yeah, I can see what's happening even without testing :)  Division by 0 error when the pressure hits 6 bar causes the particle count inside the pressure chamber to go to infinity.  Easy fix though and a 0.11.7 release will be out shortly.

In the meantime, don't let your pressure chamber get to 6 bar... (there's a 50% chance it will have exploded by then anyway).

**Comment by desht** [comment]
Fixed in 0.11.7 release.

**Comment by teron281** [comment]
Nice thanks for fixing it.

Best to remember:
Only Chuck Norris is allowed to divide by Zero ^^
