### ISSUE TITLE
Drones are unable to place fluid sources in flowing liquids

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#402]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it 

Drones don't appear to be capable of placing source blocks of fluids if the block is already occupied by a flowing version of that fluid. 

For example, I'm trying to build a drone program to build an Astral Sorcery Starlight Infuser. Part of this structure includes four trenches of starlight, each three blocks long. The drone is building the structure fine, then places a single bucket in each of the four trenches. The liquid quickly spreads out, filling the 3x1 trench and the drone considers it's job to be complete. 

The program I was using to test just the fluid placement was pretty basic. 
Start
Import Fluid from targeted tank
Export Fluid (Place In World enabled) into the 5x5 area
Export Fluid to return excess fluid to the tank
Suicide

https://streamable.com/c1u6m

### Any other comments?

For the record, the drone does have security upgrades in it. I tried with 1 and 2.

**Comment by desht** [comment]
Yeah, the drone is looking for an air block at the placement position right now, where it probably should be looking for any replaceable block (including flowing fluids).  Should be an easy fix, hopefully.

**Comment by desht** [comment]
Can you give build 378 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ a go?  It should fix your problem.

**Comment by desht** [comment]
Fixed in 0.11.8 release
