### ISSUE TITLE
RF Widget typo in Patchouli manual

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#403]
### Minecraft Version 
1.12.2

### Forge Version 
14.23.5.2838

### Mod Version 
1.12.2-0.11.7-375

### Describe your problem, including steps to reproduce it 
The Patchouli entry for the Drone Condition: RF widget appears to be incorrectly referring to the Drone Condition: Pressure widget. 

The actual explanation text appears correct for the RF widget, it just calls it the Pressure Widget

> The _Drone Condition: Pressure_ widget allows you to check the amount of Forge Energy (FE) carried by this Drone.

![rf condition](https://user-images.githubusercontent.com/9543430/69500366-722cad00-0ec8-11ea-89e2-42f3e63c4fe4.PNG)

**Comment by desht** [comment]
Yep, simple typo.  This is what happens when I rush a copy/paste job :)

**Comment by desht** [comment]
Fixed in 0.11.8 release
