### ISSUE TITLE
Pressure Chamber massive lagspike when completed.

### ISSUE THREAD

**Issue by Sakata-MC** [TeamPneumatic/pnc-repressurized#406]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2844
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.11.5-371
### Extra bits
ATM3:R base with a few things tossed in and/or yanked out.
MultiMC launcher

## Expected Behavior
Place blocks normally, multiblock does its thing, continue on with life.

## Current Behavior
I thought the client had crashed, however determined that the client was just under a *massive* lag spike. First time closed client. Tried again, and could not repeat.  While getting to this page and getting ready to pull logs, it actually came back -- however a LOT of logging happened. 

## Possible Solution
Not 100% sure what is causing it. Chat seems to indicate an achievement was obtained, just after the client came back to life.  Since it doesn't happen again, I think it may be related to achievements.

## Steps to Reproduce
* Start getting into PneumaticCraft.
* Place edges and top/bottom of pressure chamber.
* Fill in walls with glass, w/ two valves.
* Place bottom interface (normally do this from inside the tank)
* Jump up top and place top interface
* wait for a bit -- it will seem as though client is dead -- it should recover.

# MultiMC Log - with complaint about 10k lines:
https://gist.github.com/Sakata-MC/0b8688eef6caf4e5c60658813fe79e61
# Actual logfile:
Is actually not able to upload cause its too flippin big, and gist times out.

https://github.com/AllTheMods/ATM3-Remix/issues/301

**Comment by Sakata-MC** [comment]
I have noticed that if I break and re-make the pressure chamber there is still a noticeable lag spike, but not the white-screen inducing bit with "Not responding" coming up.

**Comment by desht** [comment]
Fixed in latest release. Update.
