### ISSUE TITLE
textures with png extension are formatted as jpeg

### ISSUE THREAD

**Issue by artheus** [TeamPneumatic/pnc-repressurized#407]
### Minecraft Version
1.12.2

### Mod Version
0.11.7-375

### Describe your problem, including steps to reproduce it
I made a script which detects format of images in mod assets (for an unrelated purpose)
it gave me this:
```
jpeg: assets/pneumaticcraft/textures/wiki/aphorism_tile.png
jpeg: assets/pneumaticcraft/textures/wiki/coordinate_tracker.png
jpeg: assets/pneumaticcraft/textures/wiki/pneumatic_door.png
jpeg: assets/pneumaticcraft/textures/wiki/pneumatic_door_camo.png
``` 
I think this is a good thing to fix.
Though, if the textures work in-game, there is no issue.

**Comment by desht** [comment]
Yeah, there are indeed some JPEGs in there (been like that since 1.7.10) but they do appear to work in-game, so I'm not overly concerned about it.  In any case, IGW support is probably going to disappear in 1.14.4 (to be replaced by Patchouli) so this will resolve itself :)
