### ISSUE TITLE
Charging module to Aerial interface excessive tick time

### ISSUE THREAD

**Issue by Sakata-MC** [TeamPneumatic/pnc-repressurized#408]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
2844
### Mod Version
0.11.7-675
### Describe your problem, including steps to reproduce it
Noticing server lag, and trying to go through and eliminate worst offenders. There is a system with aerial interface causing a fair bit of lag. Player has a charging module with advanced PCB under aerial interface. It's the highest time on the server in several profiling runs.
![image](https://user-images.githubusercontent.com/3158362/70856183-ea253c00-1ea4-11ea-8092-0f30ab9928a2.png)
![image](https://user-images.githubusercontent.com/3158362/70856185-05904700-1ea5-11ea-9941-54107c1047ba.png)
![image](https://user-images.githubusercontent.com/3158362/70856202-6029a300-1ea5-11ea-9ed8-f401f01a579d.png)

### Any other comments?
If there is anything I can do to help with this, please let me know.   I'm not sure why this one pipe is causing so much lag. the player this one is connected to only has the armor equipped, along with a wrench at times (lives in a morph-o-tool if that has anything to do with it)

**Comment by desht** [comment]
Hmm, shouldn't be so high.  I did spend some time optimizing this a few releases back and I thought it was performing a lot better than this.  I'll do some investigation though.

It would be useful to know if it also happens without an Advanced PCB installed (I suspect it does, but I'd like to know for sure)

**Comment by desht** [comment]
Update: did some testing and yes, there is some slowness with the charging module and pneumatic armor (specifically the armor, not so much other items).

However, 1901μs/t still seems _extremely_ high - I was seeing more like 180μs/t in my testing.  This was on my i7-4770k dev machine so not super high-end or anything.

Anyway, I've made a change which halved the tick time for me (down to 87μs/t).  Can you give build 378 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ a go and let me know if it helps?

**Comment by desht** [comment]
Fixed in 0.11.8 release
