### ISSUE TITLE
Patchuli Causes minecraft to crash

### ISSUE THREAD

**Issue by Marius-Ventrue** [TeamPneumatic/pnc-repressurized#411]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

Minecraft Version 1.12.2

Forge Version 14.23.5.2847

Mod Version Patchouli 1.0-20

Causes minecraft to crash every time i try and play the mod pack

other comments: i am using the latest version on Glacial Awakening and every time i launch it it loads all the way to Patchouli then crashes

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.9-1.12.2.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  AALoadingPlugin (arcanearchives-0.2.0.13.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  LoadingPlugin (LoadingProfiler-MC1.12-1.3.jar)
  Narrator Hotkey Disabler (rebindnarrator-1.0.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  CorePlugin (SmoothFont-mc1.12.2-2.1.1.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 12/22/19 1:08 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Patchouli (patchouli)
Caused by: java.lang.NullPointerException
	at vazkii.patchouli.client.book.ClientBookRegistry.func_110549_a(ClientBookRegistry.java:83)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at vazkii.patchouli.client.book.ClientBookRegistry.init(ClientBookRegistry.java:62)
	at vazkii.patchouli.client.base.ClientProxy.preInit(ClientProxy.java:18)
	at vazkii.patchouli.common.base.Patchouli.preInit(Patchouli.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 771221784 bytes (735 MB) / 2413821952 bytes (2302 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -Xmx6144m -Xms256m -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 175 mods loaded, 175 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version              | Source                                            | Signature                                |
	|:----- |:--------------------------------- |:-------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2               | minecraft.jar                                     | None                                     |
	| LCH   | mcp                               | 9.42                 | minecraft.jar                                     | None                                     |
	| LCH   | FML                               | 8.0.99.99            | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
	| LCH   | forge                             | 14.23.5.2847         | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
	| LCH   | smoothfontcore                    | mc1.12.2-2.1.1       | minecraft.jar                                     | None                                     |
	| LCH   | foamfixcore                       | 7.7.4                | minecraft.jar                                     | None                                     |
	| LCH   | smoothfont                        | mc1.12.2-2.1.1       | SmoothFont-mc1.12.2-2.1.1.jar                     | None                                     |
	| LCH   | vaultopic                         | 2.1                  | vaultopic-2.1.jar                                 | None                                     |
	| LCH   | crafttweaker                      | 4.1.20               | CraftTweaker2-1.12-4.1.20.jar                     | None                                     |
	| LCH   | forgelin                          | 1.8.4                | Forgelin-1.8.4.jar                                | None                                     |
	| LCH   | alib                              | 1.0.12               | alib-1.0.12.jar                                   | None                                     |
	| LCH   | alchemistry                       | 1.0.36               | alchemistry-1.0.36.jar                            | None                                     |
	| LCH   | endertweaker                      | 1.1.7                | EnderTweaker-1.12.2-1.1.7.jar                     | None                                     |
	| LCH   | mtlib                             | 3.0.6                | MTLib-3.0.6.jar                                   | None                                     |
	| LCH   | modtweaker                        | 4.0.17               | modtweaker-4.0.17.jar                             | None                                     |
	| LCH   | jei                               | 4.15.0.292           | jei_1.12.2-4.15.0.292.jar                         | None                                     |
	| LCH   | athenaeum                         | 1.12.2-1.17.4        | athenaeum-1.12.2-1.17.4.jar                       | None                                     |
	| LCH   | bookshelf                         | 2.3.590              | Bookshelf-1.12.2-2.3.590.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | gamestages                        | 2.0.117              | GameStages-1.12.2-2.0.117.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | dropt                             | 1.12.2-1.16.1        | dropt-1.12.2-1.16.1.jar                           | None                                     |
	| LCE   | patchouli                         | 1.0-20               | Patchouli-1.0-20.jar                              | None                                     |
	| LC    | theoneprobe                       | 1.4.28               | theoneprobe-1.12-1.4.28.jar                       | None                                     |
	| LC    | pyrotech                          | 1.12.2-1.4.13        | pyrotech-1.12.2-1.4.13.jar                        | None                                     |
	| LC    | fastbench                         | 1.7.3                | FastWorkbench-1.12.2-1.7.3.jar                    | None                                     |
	| LC    | actuallyadditions                 | 1.12.2-r151          | ActuallyAdditions-1.12.2-r151.jar                 | None                                     |
	| LC    | ctm                               | MC1.12.2-1.0.1.30    | CTM-MC1.12.2-1.0.1.30.jar                         | None                                     |
	| LC    | appliedenergistics2               | rv6-stable-7         | appliedenergistics2-rv6-stable-7.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LC    | bdlib                             | 1.14.3.12            | bdlib-1.14.3.12-mc1.12.2.jar                      | None                                     |
	| LC    | ae2stuff                          | 0.7.0.4              | ae2stuff-0.7.0.4-mc1.12.2.jar                     | None                                     |
	| LC    | akashictome                       | 1.2-12               | AkashicTome-1.2-12.jar                            | None                                     |
	| LC    | applecore                         | 3.2.0                | AppleCore-mc1.12.2-3.2.0.jar                      | None                                     |
	| LC    | appleskin                         | 1.0.9                | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
	| LC    | baubles                           | 1.5.2                | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LC    | gbook_snapshot                    | 2.9.1.s5             | Guidebook-1.12.2-2.9.1.s5.jar                     | None                                     |
	| LC    | arcanearchives                    | 0.2.0.13             | arcanearchives-0.2.0.13.jar                       | None                                     |
	| LC    | architecturecraft                 | @VERSION@            | architecturecraft-1.12-3.98.jar                   | None                                     |
	| LC    | mousetweaks                       | 2.10                 | MouseTweaks-2.10-mc1.12.2.jar                     | None                                     |
	| LC    | artisanworktables                 | 1.12.2-1.22.15       | artisanworktables-1.12.2-1.22.15.jar              | None                                     |
	| LC    | astralsorcery                     | 1.10.20              | astralsorcery-1.12.2-1.10.20.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LC    | quark                             | r1.6-177             | Quark-r1.6-177.jar                                | None                                     |
	| LC    | autoreglib                        | 1.3-32               | AutoRegLib-1.3-32.jar                             | None                                     |
	| LC    | base                              | 3.13.0               | base-1.12.2-3.13.0.jar                            | None                                     |
	| LC    | betteradvancements                | 0.1.0.77             | BetterAdvancements-1.12.2-0.1.0.77.jar            | None                                     |
	| LC    | betterbuilderswands               | 0.13.2               | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar | None                                     |
	| LC    | blockdrops                        | 1.4.0                | blockdrops-1.12.2-1.4.0.jar                       | None                                     |
	| LC    | bnbgaminglib                      | 2.17.6               | BNBGamingLib-1.12.2-2.17.6.jar                    | None                                     |
	| LC    | bonsaitrees                       | 1.1.3                | bonsaitrees-1.1.3-b156.jar                        | None                                     |
	| LC    | buildinggadgets                   | 2.7.4                | BuildingGadgets-2.7.4.jar                         | None                                     |
	| LC    | carryon                           | 1.12.3               | CarryOn MC1.12.2 v1.12.3.jar                      | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LC    | chameleon                         | 1.12-4.1.3           | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| LC    | roots                             | 1.12.2-3.0.21        | Roots-1.12.2-3.0.21.jar                           | None                                     |
	| LC    | mysticalworld                     | 1.12.2-1.6.1         | mysticalworld-1.12.2-1.6.1.jar                    | None                                     |
	| LC    | chisel                            | MC1.12.2-1.0.1.44    | Chisel-MC1.12.2-1.0.1.44.jar                      | None                                     |
	| LC    | chiselsandbits                    | 14.33                | chiselsandbits-14.33.jar                          | None                                     |
	| LC    | classicbar                        | @VERSION@            | classicbar-0.5.2.jar                              | None                                     |
	| LC    | codechickenlib                    | 3.2.3.358            | CodeChickenLib-1.12.2-3.2.3.358-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux                      | 2.1.0                | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                          | 4.6.3                | CoFHCore-1.12.2-4.6.3.27-universal.jar            | None                                     |
	| LC    | contenttweaker                    | 1.12.2-4.9.1         | ContentTweaker-1.12.2-4.9.1.jar                   | None                                     |
	| LC    | controlling                       | 3.0.7                | Controlling-3.0.7.jar                             | None                                     |
	| LC    | cookingforblockheads              | 6.4.71               | CookingForBlockheads_1.12.2-6.4.71.jar            | None                                     |
	| LC    | craftingstation                   | @VERSION@            | craftingstation-0.1.7b.jar                        | None                                     |
	| LC    | craftingtweaks                    | 8.1.9                | CraftingTweaks_1.12.2-8.1.9.jar                   | None                                     |
	| LC    | ctgui                             | 1.0.0                | CraftTweaker2-1.12-4.1.20.jar                     | None                                     |
	| LC    | crafttweakerjei                   | 2.0.3                | CraftTweaker2-1.12-4.1.20.jar                     | None                                     |
	| LC    | cucumber                          | 1.1.3                | Cucumber-1.12.2-1.1.3.jar                         | None                                     |
	| LC    | custommainmenu                    | 2.0.9                | CustomMainMenu-MC1.12.2-2.0.9.jar                 | None                                     |
	| LC    | darkutils                         | 1.8.230              | DarkUtils-1.12.2-1.8.230.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | deepmoblearning                   | 1.12.2-2.5.2         | deepmoblearning-1.12.2-2.5.2-universal.jar        | None                                     |
	| LC    | journeymap                        | 1.12.2-5.5.6b2       | journeymap-1.12.2-5.5.6b2.jar                     | None                                     |
	| LC    | defaultoptions                    | 9.2.8                | DefaultOptions_1.12.2-9.2.8.jar                   | None                                     |
	| LC    | diethopper                        | 1.1                  | diethopper-1.1.jar                                | None                                     |
	| LC    | ding                              | 1.0.2                | Ding-1.12.2-1.0.2.jar                             | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | discordcraft                      | 1.0                  | DiscordCraft-1.0.3.1.jar                          | None                                     |
	| LC    | elevatorid                        | 1.3.12               | ElevatorMod-1.12.2-1.3.12.jar                     | None                                     |
	| LC    | endercore                         | 1.12.2-0.5.73        | EnderCore-1.12.2-0.5.73.jar                       | None                                     |
	| LC    | enderio                           | 5.1.52               | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
	| LC    | enderiointegrationtic             | 5.1.52               | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
	| LC    | enderiobase                       | 5.1.52               | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
	| LC    | enderioconduits                   | 5.1.52               | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
	| LC    | enderioconduitsappliedenergistics | 5.1.52               | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
	| LC    | enderioconduitsopencomputers      | 5.1.52               | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
	| LC    | enderioconduitsrefinedstorage     | 5.1.52               | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
	| LC    | enderiointegrationforestry        | 5.1.52               | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
	| LC    | enderiointegrationticlate         | 5.1.52               | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
	| LC    | ftblib                            | 5.4.4.5              | FTBLib-5.4.4.5.jar                                | None                                     |
	| LC    | enderiomachines                   | 5.1.52               | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
	| LC    | enderiopowertools                 | 5.1.52               | EnderIO-1.12.2-5.1.52.jar                         | None                                     |
	| LC    | enderioendergy                    | 5.1.52               | EnderIO-endergy-1.12.2-5.1.52.jar                 | None                                     |
	| LC    | essentials                        | 1.12.2-1.2.1         | essentials-1.12.2-1.2.1.jar                       | None                                     |
	| LC    | extraanvils                       | @VERSION@            | extraanvils-0.9.jar                               | None                                     |
	| LC    | fastleafdecay                     | v14                  | FastLeafDecay-v14.jar                             | None                                     |
	| LC    | featuredservers                   | 1.12-1.0.6           | FeaturedServers-1.12-1.0.6.jar                    | None                                     |
	| LC    | fencejumper                       | 1.0.5                | fencejumper-1.12-1.0.5.jar                        | None                                     |
	| LC    | foamfix                           | 0.10.9-1.12.2        | foamfix-0.10.9-1.12.2.jar                         | None                                     |
	| LC    | forbidden_arcanus                 | 1.12.2-1.1.4         | forbidden_arcanus-1.12.2-1.1.4.jar                | None                                     |
	| LC    | ftbbackups                        | 1.1.0.1              | FTBBackups-1.1.0.1.jar                            | None                                     |
	| LC    | ftbutilities                      | 5.4.0.124            | FTBUtilities-5.4.0.124.jar                        | None                                     |
	| LC    | itemfilters                       | 1.0.3.12             | ItemFilters-1.0.3.12.jar                          | None                                     |
	| LC    | ftbquests                         | 1.8.0.237            | FTBQuests-1.8.0.237.jar                           | None                                     |
	| LC    | glacialawakeningtweaks            | 1.0.2                | glacialawakeningtweaks-1.0.2.jar                  | None                                     |
	| LC    | headcrumbs                        | 2.0.4                | Headcrumbs-1.12.2-2.0.5.17.jar                    | None                                     |
	| LC    | hearthstones                      | 1.0.0.1              | Hearthstones-1.12.2-1.0.0.1.jar                   | None                                     |
	| LC    | hwell                             | 0.4.2                | hwell-0.4.2.jar                                   | None                                     |
	| LC    | immersiveengineering              | 0.12-92              | ImmersiveEngineering-0.12-92.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | immersivecables                   | 1.3.2                | ImmersiveCables-1.12.2-1.3.2.jar                  | None                                     |
	| LC    | mekanism                          | 1.12.2-9.8.3.390     | Mekanism-1.12.2-9.8.3.390.jar                     | None                                     |
	| LC    | teslacorelib                      | 1.0.15               | tesla-core-lib-1.12.2-1.0.15.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | industrialforegoing               | 1.12.2-1.12.2        | industrialforegoing-1.12.2-1.12.13-237.jar        | None                                     |
	| LC    | initialinventory                  | 2.0.2                | InitialInventory-3.0.0.jar                        | None                                     |
	| LC    | mantle                            | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                          | None                                     |
	| LC    | inspirations                      | 1.12.2-0.2.8         | Inspirations-1.12.2-0.2.8.jar                     | None                                     |
	| LC    | nuclearcraft                      | 2.18l                | NuclearCraft-2.18l-1.12.2.jar                     | None                                     |
	| LC    | rustic                            | 1.1.2                | rustic-1.1.2.jar                                  | None                                     |
	| LC    | integrationforegoing              | 1.12.2-1.9           | IntegrationForegoing-1.12.2-1.9.jar               | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LC    | inventorytweaks                   | 1.64+dev.146.2180b27 | InventoryTweaks-1.64+dev.146.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | inworldcrafting                   | 1.12.2-1.2.0         | inworldcrafting-1.12.2-1.2.0-universal.jar        | None                                     |
	| LC    | itlt                              | 1.0.0                | itlt-1.12.2-1.0.2.jar                             | None                                     |
	| LC    | jeiintegration                    | 1.5.1.36             | jeiintegration_1.12.2-1.5.1.36.jar                | None                                     |
	| LC    | jetif                             | 1.5.1                | jetif-1.12.2-1.5.1.jar                            | None                                     |
	| LC    | jee                               | 1.0.8                | JustEnoughEnergistics-1.12.2-1.0.8.jar            | None                                     |
	| LC    | loottweaker                       | 0.1.2                | LootTweaker-0.1.2+MC1.12.2.jar                    | None                                     |
	| LC    | jeresources                       | 0.9.2.60             | JustEnoughResources-1.12.2-0.9.2.60.jar           | None                                     |
	| LC    | kleeslabs                         | 5.4.12               | KleeSlabs_1.12.2-5.4.12.jar                       | None                                     |
	| LC    | laggoggles                        | FAT-1.12.2-4.9       | LagGoggles-FAT-1.12.2-4.9.jar                     | None                                     |
	| LC    | loadingprofiler                   | 1.1                  | LoadingProfiler-MC1.12-1.3.jar                    | None                                     |
	| LC    | magneticraft                      | 2.7.0                | Magneticraft_1.12-2.8.2-dev.jar                   | None                                     |
	| LC    | mcjtylib_ng                       | 3.5.4                | mcjtylib-1.12-3.5.4.jar                           | None                                     |
	| LC    | mechanics                         | 0.2.1                | mechanics-0.2.1.jar                               | None                                     |
	| LC    | modelloader                       | 1.1.7                | modelloader-1.1.7.jar                             | None                                     |
	| LC    | modnametooltip                    | 1.10.1               | modnametooltip_1.12.2-1.10.1.jar                  | None                                     |
	| LC    | morecharcoal                      | 1.12.2-1.0.9         | morecharcoal-1.12.2-1.0.9.jar                     | None                                     |
	| LC    | moreoverlays                      | 1.15.1               | moreoverlays-1.15.1-mc1.12.2.jar                  | None                                     |
	| LC    | morpheus                          | 1.12.2-3.5.106       | Morpheus-1.12.2-3.5.106.jar                       | None                                     |
	| LC    | naturesaura                       | r18                  | NaturesAura-r18.jar                               | None                                     |
	| LC    | topography                        | 1.10.1               | Topography-1.12.2-1.10.1.jar                      | None                                     |
	| LC    | naturestopography                 | 1.0.1                | naturestopography-1.0.1.jar                       | None                                     |
	| LC    | netherchest                       | 1.1.1                | netherchest-1.1.1.jar                             | None                                     |
	| LC    | openglider                        | @VERSION@            | OpenGlider-1.12.1-1.1.0.jar                       | None                                     |
	| LC    | oreexcavation                     | 1.4.143              | OreExcavation-1.4.143.jar                         | None                                     |
	| LC    | pickletweaks                      | 2.1.3                | PickleTweaks-1.12.2-2.1.3.jar                     | None                                     |
	| LC    | pillar                            | 1.2-10               | Pillar-1.2-10.jar                                 | None                                     |
	| LC    | placebo                           | 1.6.0                | Placebo-1.12.2-1.6.0.jar                          | None                                     |
	| LC    | rebind_narrator                   | 1.0.0                | rebindnarrator-1.0.jar                            | None                                     |
	| LC    | recipestages                      | 1.1.3                | RecipeStages-1.1.3.jar                            | None                                     |
	| LC    | resourceloader                    | 1.5.3                | ResourceLoader-MC1.12.1-1.5.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LC    | rsgauges                          | 1.1.10-b2            | rsgauges-1.12.2-1.1.10-b2.jar                     | ed58ed655893ced6280650866985abcae2bf7559 |
	| LC    | scavenge                          | 1.8                  | Scavenge V1.12-1.8.3.2.jar                        | None                                     |
	| LC    | simple_trophies                   | 1.2.1                | simpletrophies-1.2.1.jar                          | None                                     |
	| LC    | skyresources                      | 2.3.8                | skyresources-2.3.9.jar                            | None                                     |
	| LC    | sledgehammer                      | 1.12.2-1.6.6         | Sledgehammer-1.12.2-1.6.6.jar                     | 565fa4dbf20e7c3c4423950ca8e0bdabf7568796 |
	| LC    | speedyhoppers                     | 1.1.19               | speedyhoppers-1.1.19.jar                          | None                                     |
	| LC    | speedyladders                     | 1.1.3                | speedyladders-1.1.3.jar                           | None                                     |
	| LC    | stonechest                        | 1.0.4                | StoneChest-1.0.4.jar                              | None                                     |
	| LC    | storagedrawers                    | 1.12.2-5.4.0         | StorageDrawers-1.12.2-5.4.0.jar                   | None                                     |
	| LC    | supersoundmuffler                 | 1.0.2.10             | supersoundmuffler-1.12.2-1.0.2.10.jar             | None                                     |
	| LC    | telepastries                      | 0.3.4                | TelePastries-0.3.4.jar                            | None                                     |
	| LC    | tetra                             | 0.39.1               | tetra-1.12.2-0.39.1.jar                           | None                                     |
	| LC    | tipthescales                      | 1.0.4                | TipTheScales-1.12.2-1.0.4.jar                     | None                                     |
	| LC    | toastcontrol                      | 1.8.1                | Toast Control-1.12.2-1.8.1.jar                    | None                                     |
	| LC    | tombstone                         | 3.6.2                | tombstone-3.6.2-1.12.2.jar                        | None                                     |
	| LC    | vanillafoodpantry                 | 4.3.1                | vanillafoodpantry-mc1.12.2-4.3.1.jar              | None                                     |
	| LC    | vanillasatchels                   | 1.0.2                | VanillaSatchels-1.12.2-1.0.2.4-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | waddles                           | 0.6.0                | Waddles-1.12.2-0.6.0.jar                          | None                                     |
	| LC    | wanionlib                         | 1.12.2-2.4           | WanionLib-1.12.2-2.4.jar                          | None                                     |
	| LC    | waterstrainer                     | 3.2.0                | WaterStrainer-1.12-3.2.0.jar                      | None                                     |
	| LC    | worldstripper                     | 1.6.0-1.12.2         | World-Stripper-1.6.0-1.12.2.jar                   | None                                     |
	| LC    | xencraft                          | 1.0.0.4              | XenCraft-1.0.0.4.jar                              | None                                     |
	| LC    | xnet                              | 1.8.2                | xnet-1.12-1.8.2.jar                               | None                                     |
	| LC    | llibrary                          | 1.7.19               | llibrary-1.7.19-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | reauth                            | 3.6.0                | reauth-3.6.0.jar                                  | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| LC    | solcarrot                         | 1.8.3                | solcarrot-1.12.2-1.8.3.jar                        | None                                     |
	| LC    | mysticallib                       | 1.12.2-1.4.0         | mysticallib-1.12.2-1.4.0.jar                      | None                                     |
	| LC    | teslacorelib_registries           | 1.0.15               | tesla-core-lib-1.12.2-1.0.15.jar                  | None                                     |
	| LC    | unidict                           | 1.12.2-2.9.3         | UniDict-1.12.2-2.9.3.jar                          | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.9-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
AALoadingPlugin (arcanearchives-0.2.0.13.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (LoadingProfiler-MC1.12-1.3.jar)
  lumien.loadingprofiler.asm.ClassTransformer
Narrator Hotkey Disabler (rebindnarrator-1.0.jar)
  quaternary.rebindnarrator.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.73-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.20.jar)
  
CorePlugin (SmoothFont-mc1.12.2-2.1.1.jar)
  bre.smoothfont.asm.Transformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.6812' Renderer: 'Intel(R) HD Graphics 630'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)
		- TheOneProbePlugin (Enabled/Not Forced)

**Comment by desht** [comment]
Why are you sending me issues for a modpack this mod isn't even in?  Don't, please.
