### ISSUE TITLE
Shift Clicking GPS with no Coords in Air Cannon Crashes Client/Server

### ISSUE THREAD

**Issue by xJon** [TeamPneumatic/pnc-repressurized#412]
Crash report with game/forge/mod versions: https://paste.dimdev.org/usuwuvofud.mccrash

> If you have a GPS from PneumaticCraft without setting the coordinates, than shift click from inventory into pressurized air cannon, it will crash both the server, user client, and local game server.

Reported to my modpack repo over https://github.com/xJon/The-1.12.2-Pack/issues/147

**Comment by desht** [comment]
Confirmed.  Easy fix though.  Will be fixed in next release, coming in a day or two.

**Comment by desht** [comment]
Fixed in 0.11.8 release
