### ISSUE TITLE
Minigun loading corrupting world

### ISSUE THREAD

**Issue by CyberneticSquid** [TeamPneumatic/pnc-repressurized#415]
### Minecraft Version
1.12.2

### Forge Version
14.23..5.2847

### Mod Version
1.12.2-0.11.8-380

### Describe your problem, including steps to reproduce it
When loading the minigun, middle-clicking ammo in the player's inventory causes the game to crash and the world to become permanently corrupted. Creative mode, using (Ice/Freeze?) Ammo.

### Any other comments?
Two crash reports attached. The first one occurred when middle-clicking the ammo, second one occurred when trying to rejoin the world
[first-crash.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4074384/first-crash.txt)
[second-crash.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4074385/second-crash.txt)

**Comment by desht** [comment]
Build 381 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ should fix your problem, can you try that please?

And don't worry, your world is not permanently corrupted.  You just have a piece of bad NBT on the minigun item, that's all.  The new build will check for that and clean it up (and prevent it from re-occurring).

**Comment by CyberneticSquid** [comment]
I'd deleted the world as I didn't have much built on it, but by recreating the bug and then updating, it seems to work perfectly again. Thanks!

**Comment by desht** [comment]
Fixed in 0.11.9 release.
