### ISSUE TITLE
Drop down box text is truncated upon editing the widget

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamPneumatic/pnc-repressurized#419]
Minecraft version 1.12.2
Forge version 14.23.5.2847
Pneumaticcraft: Repressurized version 1.12.2-0.11.9-383

Steps to reproduce:
- Add a dropdown box widget to a remote
- Edit the text to a string longer than 32 characters
- Hit escape to finish editing the widget
- Right click the widget again
The text is now truncated back to 32 characters

### Any other comments?
The text is only ever truncated when the widget is edited.

**Comment by desht** [comment]
Fixed in 0.11.10 release
