### ISSUE TITLE
[Feature Request] Variable displays in tooltips

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamPneumatic/pnc-repressurized#420]
Variables in the remote control can currently only be displayed in widget names with ${varname}
Ideally, they should also be visible in tooltips, but they are not:
![image](https://user-images.githubusercontent.com/22590237/74690053-95a38300-51ab-11ea-8273-b7d4c127904d.png)
Should display as
![image](https://user-images.githubusercontent.com/22590237/74689932-1d3cc200-51ab-11ea-9de5-475748317946.png)

**Comment by desht** [comment]
Normally I'd leave feature requests to 1.14 at this point, but this is a small simple change so can go into the next 1.12 maintenance release.

**Comment by desht** [comment]
Added in 0.11.10 release
