### ISSUE TITLE
Regulator Tube Module is being ignored

### ISSUE THREAD

**Issue by Goddfrey** [TeamPneumatic/pnc-repressurized#423]
Minecraft Version 1.12.2

Forge Version forge-14.23.5.2838

Mod Version pneumaticcraft-repressurized-1.12.2-0.11.4-368.jar

Basically the Regulator Tube Module with Advanced PCB installed and threshold set, is being completely ignored, air pressure flows as if it wasn't there. 

Modpack ATM 3

**Comment by desht** [comment]
Does this happen with the latest version of the mod installed? (0.11.10)

**Comment by desht** [comment]
Closed due to lack of response
