### ISSUE TITLE
Crash with pressure chamber enchanting

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamPneumatic/pnc-repressurized#424]
### Mod Version 1.12.2-0.11.10-385

The server crashed 4 times in a row (identical crashes), then ran normally
https://hastebin.com/agixepubak.coffeescript

I filled a pressure chamber with a few stacks of books and a bunch of enchanted items, then supplied it with -.75 bar

**Comment by desht** [comment]
Fixed in 0.11.11 release
