### ISSUE TITLE
[Suggestion] Enchanted book separation

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamPneumatic/pnc-repressurized#425]
The pressure chamber contains a recipe to remove enchantments from tools with vacuum, one enchantment at a time:
![image](https://user-images.githubusercontent.com/22590237/75740070-b05e1780-5cd4-11ea-96f2-1e1ffbe7dd1c.png)

This could be extended to remove enchantments from books that contain multiple enchantments; This would allow multi-enchanted books to be separated:

![image](https://user-images.githubusercontent.com/22590237/75740113-d71c4e00-5cd4-11ea-8c42-06f8d93f3fa1.png)

Could be separated into:

![image](https://user-images.githubusercontent.com/22590237/75740141-ea2f1e00-5cd4-11ea-90c3-b01caffba8e2.png)
![image](https://user-images.githubusercontent.com/22590237/75740149-f0bd9580-5cd4-11ea-8402-0ff08aa446cf.png)

**Comment by desht** [comment]
This is a good idea, but due to way the pressure chamber is implemented in 1.12, it would be problematic to do.

However, 1.14.4 has a quite different implementation, which will make it a lot more practical to add, so I will defer this one to the 1.14.4 release.

**Comment by desht** [comment]
This is added in MC 1.16 (2.10.1).
