### ISSUE TITLE
All enchantments are applied, regardless of compatibility

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamPneumatic/pnc-repressurized#426]
### Mod Version 1.12.2-0.11.10-385

1. Obtain an enchanted book with both Sharpness and Protection
2. Place the enchanted book and a sword in a pressure chamber
3. The sword will gain both enchantments, rather than just sharpness

### Any other comments?
- *at least one* of the enchantments must be applicable to the tool for them to transfer
- Enchantments do not have to be compatible with each other. For example, you can combine sharpness and smite with single-enchantment books

**Comment by desht** [comment]
Confirmed, should be a very straightforward fix.

**Comment by desht** [comment]
Should be fixed in build 387+ from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/

**Comment by desht** [comment]
Fixed in 0.11.11 release
