### ISSUE TITLE
Pressure chamber interior overflows with items when disenchanting

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamPneumatic/pnc-repressurized#427]
### Describe your problem, including steps to reproduce it
- add many items with many enchantments into a pressure chamber with a vacuum
- add a stack of books
- Most of them will pop as items, rather than rendering in a circle like the rest of them
(These items can then only be accessed by breaking the pressure chamber, thus losing all the pressure)

### Any other comments?
I'm using a 5x5x5 pressure chamber

**Comment by desht** [comment]
Yeah, this is down to the pressure chamber internal inventory being limited to 27 stacks, for performance reasons (recipe searching involves scanning the inventory, so the smaller the better - it will be smaller yet in 1.14+)

Right now the code just drops resulting items in-world if they won't fit, but I can possibly add a check to hold off on the crafting if there isn't room for the result in the chamber's inventory.  So resulting items would need to be extracted before crafting can continue.

**Comment by desht** [comment]
Can you test this is build 387+ from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ please?

**Comment by ThizThizzyDizzy** [comment]
Confirmed working in build 388; pressure chamber never overflows

**Comment by desht** [comment]
Fixed in 0.11.11 release
