### ISSUE TITLE
Programmer returned puzzle pieces can be output to assembly arms

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamPneumatic/pnc-repressurized#428]
### Describe your problem, including steps to reproduce it
- Program a drone
- De-program the drone in a programmer next to an Assembly IO unit
![image](https://user-images.githubusercontent.com/22590237/75882411-1fc82a00-5def-11ea-8cd2-c57bc885cc0f.png)

### Any other comments?
Most of the pieces go into the chest, but one color always seems to get into the arm

**Comment by desht** [comment]
For possibly historical reasons, the IO units expose the `IItemHandler` capability, which they probably shouldn't... there's no good reason to be piping items into them (they should handle all their item picking up and putting down internally).  Should just be possible to stop exposing the capability, but some testing will be needed to avoid unintended consequences.

**Comment by desht** [comment]
Fixed in build 387+ from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/

**Comment by desht** [comment]
Fixed in 0.11.11 release
