### ISSUE TITLE
Heat Frame Cooling JEI Entry Issue

### ISSUE THREAD

**Issue by drhaber** [TeamPneumatic/pnc-repressurized#432]
The recipes using the Heat Frame are obscured in JEI.
[See Picture](https://i.imgur.com/0YmSdVJ.png)

**Comment by desht** [comment]
Yeah, I remember seeing that and making a mental note to fix it... then forgetting about it.

I'll get that sorted out for the next release (text will become a tooltip when hovering over the arrow).

**Comment by desht** [comment]
Fixed in 0.11.11 release
