### ISSUE TITLE
Thermo Pneumatic Processor, -Bar does not display in JEI correctly/at all

### ISSUE THREAD

**Issue by drhaber** [TeamPneumatic/pnc-repressurized#433]
Negative Pressure does not display in JEI correctly 
My code `mods.pneumaticcraft.thermopneumaticprocessingplant.addRecipe(<liquid:pig_iron>*288, <tfc:powder/flux>, -0.75, 773.0, <liquid:steel>*144);`

[JEI](https://i.imgur.com/iD15NDb.png)
[TPP GUI](https://i.imgur.com/YTSwnN0.png)

Please ignore previous title and text I overlooked Temp being in rounded Kelvin

**Comment by desht** [comment]
Negative pressures are interpreted as an arithmetic maximum, i.e. the pressure must be less than the specified pressure.  For your recipe that would mean a range of -0.75 to -1.0, which is what the pressure gauge shows.

Having said that, the TPP was never coded with negative pressures in mind, but that might not be too hard to add support for, similar to the way the Pressure Chamber handles it.

**Comment by desht** [comment]
Fixed in 0.11.11 release
