### ISSUE TITLE
Draining Thermopneumatic Processeing machine

### ISSUE THREAD

**Issue by techkrill** [TeamPneumatic/pnc-repressurized#434]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

Not sure if it's a bug or not, but I attached hoppers and Thermal Expansion liquiducts to all sides of thermopneumatic processing plants, and I cannot seem to drain liquid from its input tank. Once the liquid's in there, I cannot get it back out. Extremely annoying when I accidentally put 206 mB of gasoline into the input instead of LPG, and I had to craft a whole new machine, because I couldn't seem to drain it no matter what I tried.

Something I'm unaware of? Thought I'd bring it up.

**Comment by desht** [comment]
Yep, only the output tank can be drained. Right now, the only option is to press the X button in the gui to dump the input contents, but I'd be open to replacing that with a button to transfer the input to the output to avoid losing the contents...

**Comment by techkrill** [comment]
Most big mods like Thermal Expansion have dedicated faces to filling/draining. I was not aware of the "dump" button, however, so thanks for that help. I ended up making 4 thermoneumatic plants for each of the refinery outputs, just in case I ended up wanting to further process them.

I've been using your mod in a series of Minecraft Survival videos on YouTube, and made a huge fuss about getting 400 mB of the wrong fluid in there, lol. I'll point out the "dump" button to the viewers. Thanks for your help!

**Comment by desht** [comment]
FYI, next release (0.11.13, coming very soon) will change the dump button to be a move button by default - move the input fluid to the output tank.  But holding Shift will make it act like a dump button, as it does now.  This gives players a chance to reclaim the fluid if they want to (since the output tank is easily drained).

**Comment by desht** [comment]
Closing this now. Added improved fluid dump/move functionality in 0.11.13 release.
