### ISSUE TITLE
Thermopneumatic Processing Plant not working

### ISSUE THREAD

**Issue by Chibu68** [TeamPneumatic/pnc-repressurized#437]
**Minecraft Version:** 1.12.2

**Forge Version:** forge-14.23.5.2847

**Modpack:** Project Ozone 3 (normal mode)

**Mod Version:** 1.12.2 - 0.11.11-390

**Describe your problem, including steps to reproduce it**
I'm going to refer to the Thermopneumatic Processing Plant as the "TPP" because of the long name.

I build a 4 layered refinery, it is working properly. The output liquids are going into drums and i'm piping LPG into the TPP. I put coal into it, there is enough heat, but it just sits there and does nothing. I tried playing with redstone, but it doesn't help. I'm playing on singleplayer and have restarted the game.

**Any other comments?**
Screenshots: https://imgur.com/a/8XN9Ipo

I took this video as a reference to build the refinery in which the TPP works just fine.
https://youtu.be/TVYFCXYskb0?t=1425
Timestamp: 23:45

**Comment by stragulus** [comment]
Also confirming this in PO3-3.2.53 that has version 1.12.2-0.11.11-390 installed

**Comment by LoneStarrr** [comment]
It looks like the '>0' should be a '>=0' in this line: https://github.com/TeamPneumatic/pnc-repressurized/blob/master/src/main/java/me/desht/pneumaticcraft/common/tileentity/TileEntityThermopneumaticProcessingPlant.java#L140

**Comment by LoneStarrr** [comment]
I have a PR with a proposed fix: https://github.com/TeamPneumatic/pnc-repressurized/pull/438

**Comment by LoneStarrr** [comment]
@Chibu68 Until the new version is out (assuming this is not desired behavior) there is a workaround. You can attach a vacuum pump to the TPP to get negative pressure, and then it will work.

**Comment by Chibu68** [comment]
Thanks, I'll try it tomorrow.

**Comment by desht** [comment]
Yeah @LoneStarrr has it right, sorry about that.  I'll get a fix out tomorrow hopefully.

**Comment by desht** [comment]
If you want to try a dev build, build 391 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ should fix your problem (the only change from the 0.11.11 release is a fix for this bug).

Alternatively I'll get a 0.11.12 release out tomorrow.

**Comment by Chibu68** [comment]
Thanks for the update, TPP is working now :)

**Comment by desht** [comment]
Fixed in 0.11.12 release
