### ISSUE TITLE
Crash when using the elevator.

### ISSUE THREAD

**Issue by thiago1255** [TeamPneumatic/pnc-repressurized#440]
### Minecraft Version:
Minecraft 1.12.2

### Forge Version:
Forge 14.23.5.2838

### Mod Version:
 pneumaticcraft-repressurized-1.12.2-0.11.11-390

### Describe your problem, including steps to reproduce it:
It happened when I tried to use the elevator (when I pressed the control button) on pneumaticcraft.
The elevator was working normally, but suddenly the minecraft crash and now I can't play in the world that it happened.

### Any other comments?
(I'm using google translator to write this text)

Here is the report of when the crash happened for the first time:
[crash-2020-03-30_23.14.36-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4406479/crash-2020-03-30_23.14.36-client.txt)

And here is the report of when I try to access the world:
[crash-2020-03-30_23.29.45-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4406489/crash-2020-03-30_23.29.45-client.txt)

**Comment by desht** [comment]
That has nothing to do with PneumaticCraft elevators. Don't know what mod that stack trace is from, but not this one for sure.

**Comment by desht** [comment]
The mod in the stacktrace is Better Portals, by the way (`de.johni0702.minecraft.view.impl.client.render.ViewRenderPlan.renderSelf`)

Doesn't mean it's necessarily that mod's fault, but I'd check with them (https://github.com/Johni0702/BetterPortals/issues)
