### ISSUE TITLE
1.14.4 Hackable tracking kills FPS

### ISSUE THREAD

**Issue by Qsandas** [TeamPneumatic/pnc-repressurized#441]
MC 1.14.4
Forge 28.2.3
Mod 1.0.0-8

Normally a bit of an FPS drop isn't something I'd make a report for, But whenever I turn the block tracker on, then select "hackables" My FPS does more than drop. It goes down to 1 or 2 FPS, even in places with nothing to track. (tried it in a complete void, same result). If I do manage to find and attempt to hack something (like a lever) the game freezes, but never actually crashes.

What's weird is that all the other options such as spawners and inventories work fine, along with tracking and hacking entities. It's solely the hackables option that has problems.

**Comment by desht** [comment]
Yep, all is definitely not well with the block tracker.  Looking into it.

**Comment by desht** [comment]
Yep, block tracker code was a bit of a mess indeed.  Should be a lot better now - could you give build 9 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.14/ a go and let me know how's it working for you?

**Comment by Qsandas** [comment]
Thanks, It's working great now.

**Comment by desht** [comment]
Fixed in 1.0.1 release
