### ISSUE TITLE
Thermopneumatic  Processing Plant explodes after going past 1 bar of pressure

### ISSUE THREAD

**Issue by Solverbolt** [TeamPneumatic/pnc-repressurized#442]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it

Hook up a liquid or standard air compressor with a bar max of 5, machine will detonate after it clears 1 bar of pressure. 

### Any other comments?
So far, I have noticed it is impossible to use the pressure chamber, as it will never pressurize above .03 bar. Ever. Myself and 9 others have tried.  At this point, we are likely going to strip this mod from the pack permanently, and recommend others do the same.

**Comment by desht** [comment]
Your version is ancient. Upgrade.

**Comment by Solverbolt** [comment]
Cant, since your newest version is incompatible with 85% of the mods that people use when assembling a pack. If you knew what you were actually doing, it would be amazing.  But that is the same as expecting Trump to actually grown a brain, and a set of balls bigger than the nucleus of an atom.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by desht** [comment]
Bye bye.
