### ISSUE TITLE
Elevators floor is sometimes invisible

### ISSUE THREAD

**Issue by agentwolf88** [TeamPneumatic/pnc-repressurized#443]
### Describe your problem, including steps to reproduce it:

When  i stay in front of a elevater (stage 1,2,3...not 0) and i look up and down, the floor will be invisible.

### Any other comments?:

Try on window and mac. Graphic Card is an Intel HD Iris 6100

**Comment by desht** [comment]
Yeah, I'd noticed that before and meant to fix it, but kept forgetting.  Actually a really simple fix, so it'll be in the next release.

**Comment by desht** [comment]
If you want to test this before the next release, you can try build 393 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/

**Comment by desht** [comment]
Fixed in 0.11.13 release
