### ISSUE TITLE
Gasoline is registered as <liquid:fuel>

### ISSUE THREAD

**Issue by Hogan-Dazs** [TeamPneumatic/pnc-repressurized#444]
When using this mod alone, this doesn't cause any issues. But when using it together with another mod that adds `<liquid:gasoline>` and `<liquid:fuel>` like Magneticraft, it doesn't make much sense to have this mod's gasoline as `<liquid:fuel>`. Magneticraft fuel is a much denser form of oil that isn't interchangeable with gasoline. Cracking `<liquid:fuel>` into LPG doesn't make any sense, and having the `<liquid:fuel>` in magneticraft's refining process labeled as gasoline is inaccurate.

Registering gasoline as `<liquid:gasoline>` would resolve this
### Minecraft Version
1.12
### Mod Version
0.11.13-394

**Comment by desht** [comment]
Sorry, its far too late now to change this fluid's name. It's always been called "fuel" - changing it now would be grossly disruptive.
