### ISSUE TITLE
Programmable Controllers cannot interface RF

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#447]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2847
### Mod Version
1.12.2-0.11.13-394
### Describe your problem, including steps to reproduce it
Programmable Controllers cannot interface RF
### Any other comments?
Program tested: https://gist.github.com/MuteTiefling/5a61b71f149da39828c4b567e8098ae0

This works fine in an ordinary drone, but the Programmable Controller just doesn't do anything. Tried it with an Immersive Engineering Capacitor and a Mekanism Energy Cube. Programmable Controller had 35 dispenser upgrades in it.

**Comment by desht** [comment]
Yeah, the programmable controller doesn't expose an energy capability.  It probably should...

I wouldn't normally be adding features to the 1.12.2 version anymore, but this does look like a bit of an oversight and shouldn't be too difficult to do, so I'll take a look.

**Comment by desht** [comment]
Added in 0.11.14 release.
