### ISSUE TITLE
Unable to hide Neat's status bars on Programmable Controller

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#448]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2847
### Mod Version
1.12.2-0.11.13-394
### Describe your problem, including steps to reproduce it
Neat adds status bars floating above entities showing their health and name. It has a config option to hide these based on the entity's ID (discovered by using the F3 menu while looking at the entity.

Programmable controllers appear to use an entity with the ID of "null". I've attempted blacklisting these in Neat's configs by using both the string null and an empty string. The issue has been [reported](https://github.com/Vazkii/Neat/issues/36) to them as well, however I wanted to bring it up with you too in case there's anything that needs doing on your end. 

### Any other comments?

![2020-04-15_13 28 01](https://user-images.githubusercontent.com/9543430/79368166-f554ab00-7f1c-11ea-90d6-dea0655a36d0.png)

![Capture](https://user-images.githubusercontent.com/9543430/79368335-35b42900-7f1d-11ea-9671-1858e81d7082.PNG)

**Comment by desht** [comment]
Think this will be very easy to get round (add a `getEntityString()` method to the programmable controller entity should do the trick - probably just return "Programmable Controller").

**Comment by desht** [comment]
Fixed in 0.11.14 release - you should be able to use "programmableController" to blacklist it now.
