### ISSUE TITLE
[1.14.4] Apostrophes in signs can cause client-side "missing method definition"

### ISSUE THREAD

**Issue by noobanidus** [TeamPneumatic/pnc-repressurized#449]
1.14.4
28.2.3
1.0.0-8

https://paste.ubuntu.com/p/vwsx3MGpGW/

**Comment by desht** [comment]
Confirmed.  Looks like `ArrayUtils` is not present in the obfuscated client.  Will implement a local array insertion method for this.

**Comment by desht** [comment]
Fixed in 1.0.1 release
