### ISSUE TITLE
Oil generation Breaks with GregTech Classic

### ISSUE THREAD

**Issue by AbieTheFishman** [TeamPneumatic/pnc-repressurized#452]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Mod Version pneumaticcraft-repressurized-1.12.2-0.11.14-395

When the GregTech Classic mod is installed ( GTClassic-1.1.4.jar ). The oil generation for PneumaticCraft  breaks or turns off (no oil  is generated). The config file is also modified during world generation. It changes the config setting in Pneumaticcraft for oil generation to 0 (default is 15).

    # Chance per chunk in percentage to generate an Oil Lake. Set to 0 for no spawns
    # Min: 0.0
    # Max: 100.0
    D:oilGenerationChance=0

Initially reported to the GT-Classic site. They seem to suggest the issue may be on your side.
 [https://github.com/e99999/GT-Classic/issues/133]

**Comment by desht** [comment]
That's intended behaviour, and won't be changed.  The point is both mods are using the same fluid and Minecraft 1.12 and earlier doesn't have namespaced fluids.

PNC does switch off its own oil generation if it discovers another mod has already registered the "oil" fluid.  In this case, just use GTC's oil  - it should be accepted by the Refinery without any issue.

**Comment by AbieTheFishman** [comment]
So if understand correctly - PNC detects GTC has oil and turns off it's oil generation. GTC has no oil generation so, I get no oil generated in the world. So I need to add another mod that actually generates oil in the world. Buildcraft?

**Comment by desht** [comment]
If you *really* want in-world oil, then sure.  Another option might be to force PneumaticCraft to load before GTC, so that it gets to register its oil first.  This should be doable by editing `config/injectedDependencies.json` to contain something like:
```
[
  {
    "modId": "gtc",
    "deps": [
       {"type" : "after", "target":"pneumaticcraft" }
     ]
  }
]
```
(Not sure what GTC's actual mod-id so you might need to change that)

**Comment by AbieTheFishman** [comment]
Thank you - this works quite nicely! I apologize for any unnecessary drama I may have caused.
