### ISSUE TITLE
Security Station duplicating its area of effect and causing unauthorised users to be told there is more than one security station

### ISSUE THREAD

**Issue by SniperKillshot** [TeamPneumatic/pnc-repressurized#453]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2847
### Mod Version
1.12.2-0.11.13-394
### Describe your problem, including steps to reproduce it
security station when broken, and when rebooting still does not allow non-whitelisted users to interact with the environment. it also duplicates itself, notifying unauthed users that there is 3 security stations, not just one. furthermore,  users cannot be added to the security station, making a good chunk of our base unusable. we have tried to reproduce the former issue with no avail.

**Comment by desht** [comment]
By "broken", do you mean the block was broken with a pick, or that it was hacked?

Does the problem persist through a server restart?

I can't reproduce this right now, so any more information you can give me would be helpful...

**Comment by SniperKillshot** [comment]
with a pick, and we havent been able to restart the server, as the owner is not available now, but hopefully will be later tonight

**Comment by desht** [comment]
Does it prevent the original placer of the block from doing anything?  Or just other players, who haven't been added?

What do you mean by "users cannot be added to the security station"?  Is there some error, or is it because you can't open the GUI?

**Comment by SniperKillshot** [comment]
the original placer, (me) is fine, and can do everything. the plus button on the gui is broken for some reason.

**Comment by desht** [comment]
What does "the plus button on the gui is broken" mean? I need more detail than you're giving me. Just saying "it's broken" tells me nothing.

**Comment by SniperKillshot** [comment]
sorry, the plus button highlights when i mouse over it, but clicking on it does nothing, even with a persons name in the field to add them to the whitelist. there is no sound that plays when clicking on the button.

**Comment by SniperKillshot** [comment]
also, it is fixed with a server restart

**Comment by desht** [comment]
I haven't been able to reproduce this problem (working when I test on a dedicated server) but I'll keep this open and continue to investigate...

**Comment by desht** [comment]
Not much to do here.... 1.12.2 is now long out of support, so closing.
