### ISSUE TITLE
[QUESTION] How can you feed oil into the refinery?

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#454]
### Minecraft Version
1.14.4
### Forge Version
28.2.4
pneumaticcraft-repressurized-1.14.4-1.0.1-10

### How can you feed oil into the refinery?
The allthemods4 pack has silent's machines and oil, it looks like the oil is compatible and the tooltip says it can be refined.

### Any other comments?
I've tried various things including liquid hoppers, buckets, logistic frames, drones and modules. Also tried immersive engineering's pipes and tank.

BTW, the changes on the pressure chamber are nice. There is no JEI recipe for the manual. If you replace the vacuum pump with a pipe, the pipe keeps the negative pressure.

**Comment by desht** [comment]
Are you feeding into the Refinery Controller?  Refinery multiblock is a little different in 1.14/1.15 - you need a Refinery Controller, then stack 2-4 Refinery Outputs either on top of or beside the controller.

Only the controller will accept fluids; the outputs are, well, output only :)

![image](https://user-images.githubusercontent.com/736831/80945179-21a86c80-8de3-11ea-8840-8d1bf9af097e.png)

**Comment by desht** [comment]
JEI not showing the manual recipe is a known issue with JEI.  I've worked around it in 1.15.2, I suppose I could backport those changes to 1.14.  (1.15 is getting all new development, with only critical fixes backported to 1.14)

Got a bit more info about the vacuum pump/pressure tube issue?  Not quite sure I understand what you mean there.

**Comment by duncanwebb** [comment]
Yes, I tried both configurations. Is there a specific face where the oil is needed to be fed? In the picture the right small tank has 1 bucket of silent's mechanism's oil. I tried with and without filters on the logistic frames.

![2020-05-04_12 18 43](https://user-images.githubusercontent.com/4198031/80956553-bd48d580-8e01-11ea-899e-dcf9f0611474.png)

There's no need to backport the changes, I would be nice if the recipe was on the github or curseforge page. I just couldn't remember if I had to pressurize a book or if it was a crafting recipe. The penny dropped eventually.

Honestly, I don't know which version of Minecraft to play as the Minecraft versions are changing so quickly. If the forge API is very different with each version then it may be too much work for developers to keep up.

It was a bit like this (the vacuum pump was reversed), the compression chamber has -1 bar, the pipes were disconnected as shown. Next the pump was replaced with a pipe. The pipe has -1 bar and it didn't pressurize even when the stop was removed. The fix was to break the pipe again.

![2020-05-04_12 50 19](https://user-images.githubusercontent.com/4198031/80958790-deabc080-8e05-11ea-90f4-6fee4aadcd82.png)

**Comment by desht** [comment]
Ah, wait - just noticed you're trying to pump a different mod's oil in?  Due to way fluids have changed in 1.14+ (they're now namespaced, like items), the Refinery won't by default take oil from other mods - it only accepts the `pneumaticcraft:oil` fluid.

That can be worked around by adding new Refinery recipes via a datapack.   You can put recipes in `data/<modid>/pneumaticcraft/machine_recipes/refinery/*.json` to add or override Refinery recipes.  See https://github.com/TeamPneumatic/pnc-repressurized/tree/1.14/src/main/resources/data/pneumaticcraft/pneumaticcraft/machine_recipes/refinery for an example of the existing recipes.

In the next 1.15.2 release, it will be a bit simpler since all fluids & recipes are done with tags (also all machine recipes are handled through the vanilla recipe system, so found in `data/pneumaticcraft/recipes/<machine-type>/*.json`).  Just adding another fluid to the `pneumaticcraft:oil` fluid tag will be sufficient to make the refinery accept it.

**Comment by desht** [comment]
And yeah, the whole 1.14/1.15 situation is a bit confusing right now.  My feeling is that most modders (at least all the ones I've talked to on Discord) are more interested on working on 1.15, since it'll be a lot easier to port forward once 1.16 is release.

But then again, Forge has decided that 1.14 should be a LTS release, so... *shrug*

**Comment by desht** [comment]
The vacuum pump issue sounds a bit like something (a tile entity or capability) has been cached and not cleared properly.  I'll see if I can reproduce that.

**Comment by duncanwebb** [comment]
Yes indeed, while you were replying I added a bucket of pneumaticcraft:oil using creative to get the bucket. And sure enough it went in to the refinery.

So if I create an oil_2.json for a tower with two outputs
```
{
  "input": {
    "type": "silents_mechanisms:fluid",
    "fluid": "silents_mechanisms:oil",
    "amount": 10
  },
  "results": [
    {
      "fluid": "pneumaticcraft:diesel",
      "amount": 4
    },
    {
      "fluid": "pneumaticcraft:lpg",
      "amount": 2
    }
  ]
}
```
I'm not sure where to place the file, currently it is here:

`D:\MultiMC\instances\All-the-Mods-4-1.3\minecraft\saves\world\datapacks\pneumaticcraft\data\pneumaticcraft\machine_recipes\refinery\oil_2.json`

There is a bluepower datapack installed with a similar path.

Does this look correct? It takes quite a few minutes to start the modpack and load a game.

**Comment by desht** [comment]
"type" should be "pneumaticcraft:fluid" - that's the ingredient type, not the fluid name. Otherwise, the recipe looks good.

The JSON should go in `saves/world/datapacks/YOURDATAPACKNAME/data/pneumaticcraft/pneumaticcraft/machine_recipes/refinery/RECIPE_ID.json`, where
* `YOURPACKNAME` is the name of the data pack you are adding (can be anything you want, but must also contain a valid `pack.mcmeta` file - see https://minecraft.gamepedia.com/Data_pack)
* `RECIPE_ID` is the unique ID for the recipe. If you use `oil_2.json`, you'll overwrite the default `oil_2` which PNC:R adds, which you may or may not want.  You could use something like `silents_oil_2.json` if you want both recipes to be in effect.

**Comment by duncanwebb** [comment]
Thank you very much, works nicely. 

[silents_oil.zip](https://github.com/TeamPneumatic/pnc-repressurized/files/4575214/silents_oil.zip). Has an imaginative YOURDATAPACKNAME as duncan :-)

I guessed that pneumaticcraft/pneumaticcraft was deliberate from the git repo. Wasn't sure if the RECIPE_ID needed to be specific or just anything. I know you are very observant and would notice this.

Delighted pnc-repressurized is now in 1.14.4 as it is a really fun mod. Looking forward for more drone programming with the lego pieces.

**Comment by duncanwebb** [comment]
BTW, this is why I thought I could use silent's mechanisms oil

![2020-05-04_15 22 32](https://user-images.githubusercontent.com/4198031/80978407-4a9e2100-8e26-11ea-92ec-ce6ab40f1cfb.png)

**Comment by desht** [comment]
Hmm, yeah - that's a bug :)

**Comment by duncanwebb** [comment]
Did I mess something up, both silents_mechanisms:oil and pneumaticcraft:oil are processing but not producing any output.

![2020-05-04_18 22 35](https://user-images.githubusercontent.com/4198031/80988976-92c44000-8e34-11ea-8386-9b9b956616bf.png)

**Comment by duncanwebb** [comment]
The liquid is in the output tanks but when the controller GUI is opened it disappears from the tanks.

![2020-05-04_18 33 43](https://user-images.githubusercontent.com/4198031/80989900-d9ff0080-8e35-11ea-83c5-eef97dd4cd45.png)

**Comment by desht** [comment]
Yeah, I think there is a GUI sync bug there. I fixed something very similar on 1.15, with luck it will be a simple backport.

The refinery should work otherwise, this is a just a sync issue, I think.

**Comment by desht** [comment]
OK, v1.0.2 has been release which I think addresses all of the issues here.  Give it a go :)

I also made it easier to add new fluids for Refinery (or TPP) purposes - they now use fluid tags, so you can just add the other fluid to (say) `pneumaticcraft:oil` to get it accepted in the Refinery.

E.g. if you add this to `datapacks/duncanwebb/data/pneumaticcraft/tags/fluids/oil.json`:
```
{
  "replace": "false"
  "values":  [
     "silents_mechanisms:oil"
  ]
}
```
and you shouldn't need the custom recipes you added anymore.

**Comment by duncanwebb** [comment]
Looks way better, many thanks. The refinery outputs disappear when the controller is accessed.

![refinery](https://user-images.githubusercontent.com/4198031/81067809-9234b380-8edf-11ea-8930-be60f4022346.gif)

The tooltip is also fixed.

Is the path correct as it doesn't work with this path? Is only one pneumaticcraft correct?
D:\MultiMC\instances\All-the-Mods-4-1.3\minecraft\saves\world\datapacks\silents\data\pneumaticcraft\tags\fluids\oil.json

I see the datapack is loaded as `/datapack list` shows `, [file/silents]`. Is there a way to see the description of the datapack?

**Comment by desht** [comment]
Hmm, that *looks* correct (yes only one `pneumaticcraft` needed in this case)... what do you mean by "description of the datapack" ?

**Comment by desht** [comment]
Just tested in my dev instance, where I don't have silent's installed so I added `minecraft:lava` to `pneumaticcraft:oil`.
```
$ cat saves/New\ World\ \(1\)/datapacks/extra_resources/data/pneumaticcraft/tags/fluids/oil.json
{
	"replace": false,
	"values": [
		"minecraft:lava"
	]
}
```
That works correctly for me; I can put lava in the Refinery and it refines it just like oil.

**Comment by desht** [comment]
The disappearing-fluids-while-GUI-open problem seems to be a ather general rendering issue - *all* of my rendered fluids (in any machine, not just Refinery) don't render when *any* GUI is open.

Not going to treat that as urgent, since everything renders fine in-game :)

**Comment by duncanwebb** [comment]
No comma after the false in the json file, guess that's it.

The pack.mcmeta contains:
```
{
    "pack": {
        "pack_format": 4,
        "description": "pnc refinery for silents oil"
    }
}
```
Was wondering where the description is used?

**Comment by desht** [comment]
Ah, right - if you run `/datapack list` in game (i.e. not on the server console), then if you hover over the displayed datapack name, it should show the description as a tooltip.

**Comment by duncanwebb** [comment]
Thank you again.

No problem, many thanks for the fixes and help.
