### ISSUE TITLE
crashes at random times 

### ISSUE THREAD

**Issue by 5kedone** [TeamPneumatic/pnc-repressurized#456]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*
Minecraft Version
1.15.2

Forge Version
31.1.74

Mod Version
1.1.0-3

Describe your problem, including steps to reproduce it

random crash intermittent timing provided crash log

Any other comments?

here is the crash log 
https://pastebin.com/GSHYcPzV

**Comment by desht** [comment]
Known issue (see #455), will be fixed in next release.

**Comment by desht** [comment]
You can try build 4 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ if you want to test the fix now.

**Comment by 5kedone** [comment]
oh thanks will give that a go in the am gonna watch some tv and zone out
