### ISSUE TITLE
Elevator extends to random heights when going between floors

### ISSUE THREAD

**Issue by darthvader45** [TeamPneumatic/pnc-repressurized#457]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it  Elevator bases extend to random heights when using flux compressor to pressurize system.

1. build elevator base of any size, and add frames to desired height
2. Add callers at desired locations, with one being two blocks above bases and touching one frame.
3. Add flux compressor and power source, connecting them together.
4. Wait for pressure to build to 3.1 bar.
5. Choose floor.
6. Watch as each individual base block extends to different lengths just before it reaches the desired floor, with roughly one reaching said floor.

**Comment by desht** [comment]
If you're running multiple elevators off a single Flux Compressor (you don't say how many speed upgrades the compressor has), and you're powering the elevators when they're only just over minimum pressure, then yeah - I'd expect them to be a bit start/stop.  Sounds like they don't all have sufficient pressure.

Options (do one or both):
* Provide more pressure (more compressors and/or more speed upgrades)
* Provide more volume (add volume upgrades to your elevators). This means they'll take longer to get up to working pressure, but once there, the pressure drop will be much smaller when they run.

**Comment by darthvader45** [comment]
I was running a 4x4 or 16 elevator bases (connected) off a single compressor, no upgrades.

**Comment by desht** [comment]
Yep, you're not providing enough pressure - 4x4 is a lot of elevators to power.  See my previous comment for your two options (you can do both).

Also, charging upgrades will help to reclaim a bit of air when the elevator descends (although it will descend slightly slower).

**Comment by darthvader45** [comment]
Alright.  So how many would be sufficient?  I'm thinking about 4 should do it.
