### ISSUE TITLE
Recipe issues / ore dictionary tags

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#458]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
forge-31.1.46
### Mod Version
1.15.2-1.1.0-3
### Describe your problem, including steps to reproduce it
This is in the context of a mod pack. Specifically Enigmatica 5 with PNC added. I'm discovering certain recipes are.... not quite working. So, the pack also includes Silent's Mechanisms, which has it's own Compressed Iron (ingots/compressed_iron). 

When attempting to craft Reinforced Stone for some pressure chamber walls, I'm forced to use Silent's Compressed Iron. Thankfully, there appears to be a conversion recipe (one PNC Compressed Iron in a crafting grid converts to Silent's), so I am able to move forward. Still, it's odd that the recipe doesn't seem to let me use PNC compressed iron.

Similarly, I'm attempting to build a pneumatic wrench and I'm hitting the exact opposite wall. See, I converted all my compressed iron to Silent's compressed iron... and now I can't craft the wrench since it only accepts PNC ingots.

**Comment by desht** [comment]
This sounds like more of a modpack issue than a mod issue...

I add a "pneumaticcraft:ingots/compressed_iron" tag, but I don't add that to a "forge:ingots/compressed_iron" tag; I don't want PNC compressed iron being automatically equated with other mods' compressed iron by default.  That's really something a modpack developer should be handling when they decide how or if mods should interact.

Is the conversion recipe something E5 has added?  I would have thought it would be better for them to add a tag in this case.  And did E5 change the Reinforced Stone recipe to use Silent's compressed iron?  This is all rather odd...

**Comment by MuteTiefling** [comment]
E5 hasn't done anything to PNC recipes since PNC isn't normally in the pack. So it's just a straight drop in, interacting oddly with Silent's. There are some scripts CraftTweaker scripts for tag unifications (added) but that's targetting "compressed_iron", not ingot_iron_compressed as you say. 
[unify-tags.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4578296/unify-tags.txt)




There've been a few other recipes that are acting off in the same way. All in all, I've got 13 recipes that use PNC compressed iron and 29 that use Silent's and there doesn't appear to be any overlap. 

Requiring Silent's

- Crop Support
- Transfer Gadget
- Advanced Liquid Compressor
- UV Light Box
- Small Fluid Tank
- Pneumatic Door and Base
- Sentry Turret
- Omnidirectional Hopper
- All Assembly table parts
- Pneumatic Dynamo
- Heat Sink
- Pressure Chamber Valve
- Pneumatic Cylinder
- Programmable Controller
- Display Table
- Compressed Iron Block
- Vortex Tube
- Pressure Gauge
- Reinforced Stone
- Minigun and Ammo
- Advanced Air Compressor 
- Pneumatic Armor
- Elevator Frame
- Pressure Tube
- Air Canisters
- Compressed Iron Gear
- Kerosene Lamp
- Reinforced Chest
- Heat Frame 



I'll try spinning up a test copy without any of the scripts to see what it does.

**Comment by MuteTiefling** [comment]
Yeah, even with default configs these recipes are off. I've also spun up another instance with only JEI, Silent's and PNC and interestingly both Silent's and PNC Compressed Iron can be used for all recipes. So there is something going on with the unification there... I just don't understand how.

**Comment by MuteTiefling** [comment]
Alright. Fixed it by adding pneumaticcraft as higher priority in that script I attached. Still, there might be something that needs looking at if you don't want automatic cross compatibility with Silent's

**Comment by desht** [comment]
Ah yeah, I've remember I *do* add my Compressed Iron to `forge:ingots/compressed_iron`.  So those recipes which require that will accept Silent's compressed iron.  How hard is that stuff to make?  If it's equivalent difficult or harder then I don't have much of an issue with it (PNC compressed iron isn't exactly hard to get).

I should also go through all my recipes and make sure I'm consistent about using the tag rather than the item directly, so leaving this open for now...

**Comment by desht** [comment]
Fixed in 1.1.1 release.  Everything uses `forge:ingots/compressed_iron` now, and looking at the recipe for Silent's compressed iron, I don't have a problem with it being treated as equivalent.
