### ISSUE TITLE
Refinery not rendering output fluids

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#459]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
forge-31.1.46
### Mod Version
1.15.2-1.1.0-3
### Describe your problem, including steps to reproduce it

In the GUI, I simply don't see any of the fluids being made from oil. 

They are there and I can bucket them out, however.

**Comment by desht** [comment]
Yeah, I'm aware of that one having just fixed it in 1. 14. So that'll be in the next release.

**Comment by desht** [comment]
Fixed in 1.1.1 release.
