### ISSUE TITLE
Logistics Modules not rendering correctly

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#461]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
forge-31.1.74
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-6
### Describe your problem, including steps to reproduce it

Logistics Modules are not rendering as expected when placed in world. They are functional, but appear to maybe have a broken texture for the model. 

### Any other comments?

![2020-05-05_13 31 12](https://user-images.githubusercontent.com/9543430/81096644-ba6ae500-8ed4-11ea-9351-6bbcff8ba32d.png)

**Comment by desht** [comment]
Oops!  Yep, fixed in dev.

**Comment by desht** [comment]
Fixed in 1.1.2 release
