### ISSUE TITLE
Oil Tag for compatibility

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#462]
So I ran into the issue was referenced here: https://github.com/TeamPneumatic/pnc-repressurized/issues/454 where oil wasn't allowed to go in. I eventually realized it was also Silent's oil upon finding that post. 

I didn't want to do a datapack to fix it, so I instead went the CraftTweaker route. In doing so I came to realize that Silent's is actually referring to it's own oil as 'forge:oil' in its recipes. So I used that in my CT script and it worked to add the recipes to the PNC refinery.

[refinery_tweaks.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4582681/refinery_tweaks.txt)

This got me thinking that it might be nice for PNC to simply use the forge tag in the Refinery. I'd think this should automatically solve any compatibility issues.

**Comment by desht** [comment]
Hmm, this needs a little thought.  I would have thought the tag should really be `forge:fluids/oil` (following the `forge:ingots/XXX` convention).

I'm not quite decided on whether I should just allow any other oil in by default, or whether it should be left to the modpack maker to determine all aspects of cross-mod compatibility...

**Comment by TeamSpen210** [comment]
Well the `fluids/` part is implied, since it's a fluid tag. There's not really anything else it'd be, unless you want folders for liquid/gas. That'd be kinda pointless though since it's not like there'd be much overlap.

**Comment by MuteTiefling** [comment]
I have to say that it was always nice that it was immediately compatible with other mod's oils in previous versions. Some basic cross mod compat just makes things feel cleaner.

**Comment by desht** [comment]
> Well the `fluids/` part is implied, since it's a fluid tag. There's not really anything else it'd be, unless you want folders for liquid/gas. That'd be kinda pointless though since it's not like there'd be much overlap.

Yeah, fair point!

**Comment by desht** [comment]
> I have to say that it was always nice that it was immediately compatible with other mod's oils in previous versions. Some basic cross mod compat just makes things feel cleaner.

Yeah, I get that.  That was mainly because fluids had no namespacing in 1.12, unlike items.  So if two mods registered "oil", that was it.  Now we have "pneumaticcraft:oil", "silentmechanisms:oil", and so on.  I guess accepting a "forge:oil" fluid would be alright here (and I'll add "pneumaticcraft:oil" to "forge:oil").

**Comment by desht** [comment]
OK, I've moved Oil & Lubricant to forge:oil & forge:lubricant tags - tested with Silent Mechanisms, and their oil is now accepted by default in the refinery.  You can play with this in build 8 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/

**Comment by MuteTiefling** [comment]
Awesome! I'll give this build a spin. Thank you very much!

**Comment by desht** [comment]
Fixed in 1.1.2 release
