### ISSUE TITLE
Slime Recipe in Pressure Chamber doesn't require green dye

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#463]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
forge-31.1.74
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-6
### Describe your problem, including steps to reproduce it

Placing two or more milk buckets in the pressure chamber results in one being crafted into slime without the need for green dye. Green dye is only necessary if there is exactly one bucket in the chamber.

**Comment by desht** [comment]
Confirmed & fixed :)

**Comment by desht** [comment]
Fixed in 1.1.2 release
