### ISSUE TITLE
Fluid Tanks are not used in crafting recipes

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#464]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
forge-31.1.74
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-6
### Describe your problem, including steps to reproduce it
Place one small tank and 64 hoppers in a crafting grid and you'll be able to craft 64 liquid hoppers. The tank always remains in the grid. 

This appears to be the case for every recipe that need tanks, even the medium and large tanks.
 
### Any other comments?

There _may_ be a dupe going on here too as I noticed I had far more tanks than I ever recall crafting in my survival world. I'm not sure what I was doing when that happened though. I may just be derping and forgetting that I crafted a bunch for use in liquid hoppers that I then never actually used.

**Comment by desht** [comment]
Yep, bug on my part.  I intended for fluid tanks not to get used up in fluid crafting operations (e.g. making speed upgrades), but neglected to ensure that empty tanks *do* get used up when being used as items.  Fixed in dev.

**Comment by desht** [comment]
Have a play with build 7 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ - should fix this problem and your other recent reported issues, hopefully...

**Comment by desht** [comment]
Fixed in 1.1.2 release
