### ISSUE TITLE
Refined Storage Crafter cannot insert into Pressure Chamber Inlet

### ISSUE THREAD

**Issue by utoc** [TeamPneumatic/pnc-repressurized#467]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.1.74
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-6
### Describe your problem, including steps to reproduce it

Any basic Refined Storage Autocrafting system will do: the crafter faces the inlet interface of the camber.  When ordering a recipe (turbine blade used for the example) the crafter will give the error "Machine doesn't accept item".

The workaround is to interface the crafter with a chest and an itemduct of sorts (I've used Mek for testing).  

### Any other comments?
This one may not be the fault of the Pressure Chamber, I honestly don't know, I am happy to do all the troubleshooting in the world for you to help.  

Also, I've noticed something when using itemducts with the chamber: if you don't send the items as a stack, the inlet block doesn't wait for the rest of the stack.  One item slips in and the others are sent back to the chest.  Could the wait time be increased a few ticks?  

Here are some pretty pictures which may not help at all:

![javaw_tQv1qvM20L](https://user-images.githubusercontent.com/11995956/81295538-2fa1fb80-9036-11ea-8110-81564a4bce5c.png)
![javaw_Bf624lH0Y4](https://user-images.githubusercontent.com/11995956/81295540-303a9200-9036-11ea-9f43-602122917162.png)

The red exclamation mark mouseover says "Machine does not accept item".

**Comment by desht** [comment]
The input interface only accepts item when the input door is fully open. It will start to close the input exactly 10 ticks after the last item has been inserted, and once the output door (i.e. the one inside the pressure chamber) is fully open, the items are pushed into the chamber itself.

So, as long as you have a piping system which can move at least one item every 10 ticks, you shouldn't have the problem where the input door closes before you've pumped all the items in.  Vanilla and PneumaticCraft hoppers both work fine for this (8 ticks per item at worst).  I'm guessing the Mekanism pipes you're using are slower than that?

As for the RS Crafter problem... I'm not sure. I wonder if RS is caching the fact that because the interface didn't accept the item at some point (because the door wasn't fully open), it then refuses to even try on subsequent occasions...?

I'll see if I can get RS into my dev instance and do some testing there.  Might turn up something interesting.

**Comment by utoc** [comment]
I'll try the faster variant of the Mek ducts to see if they play nice..  The 10-tick timeout is good information though, I can design my setup around that.  

Thank you for checking into the RS side of the issue.

**Comment by desht** [comment]
I think my RS theory was correct: https://github.com/raoulvdberge/refinedstorage/blob/mc1.15/src/main/java/com/raoulvdberge/refinedstorage/apiimpl/autocrafting/task/v6/CraftingTask.java#L781

You could ask Raoul about this and see if he has any ideas, but I think he could also validly argue that RS isn't doing anything wrong; it's reasonable to mark an inventory as "faulty" if it doesn't accept the items it's supposed to.  It just doesn't account for the fact that the pressure chamber interface isn't always open :)

But by far the easiest workaround is just to put a buffer between the crafter and interface.  I personally recommend a PNC Omnidirectional Hopper with a few speed upgrades, but faster piping from something like Mek should also do the trick.

**Comment by utoc** [comment]
Funny you mention the hopper: the hopper sucks the recipes out of the crafter.  I submitted a bug report to RS about it though.  What I'm doing instead of a Crafter->Chest->Hopper->Inlet.  I'll make a ticket with RS and see if they can do something about that and link back to this issue.  

Going back to the itemducts, No matter which duct I use, the first gold bar makes it into the inlet and then all following gold bars are stuck in the pipe/rejected until the inlet door opens back up.  When the inlet re-opens, all the remaining gold bars are inserted into the inlet in one go.  When the inlet opens again (for the redstone), all redstone make it into the inlet in one go.

**Comment by desht** [comment]
> Going back to the itemducts, No matter which duct I use, the first gold bar makes it into the inlet and then all following gold bars are stuck in the pipe/rejected until the inlet door opens back up.

I think I might know why that is (timeout counter isn't reset until new items are inserted, but probably should be reset as soon as the output door starts opening). I'll do some testing on that.

**Comment by desht** [comment]
Regarding hoppers, can't you point the crafter at the side of a hopper?  Have the hopper outputting to the pressure chamber, but have its input pointing at air, or some non-inventory block.  Both vanilla and PNC hoppers will accept items pumped into the side by another block (in this case, the crafter).

**Comment by utoc** [comment]
I didn't even think about that! It worked marvelously with the Onmi hopper/inlet upgraded with speed and the crafter pointing to literally any other side of the hopper.

**Comment by Darkere** [comment]
Heya. Actually RS doesn't cache a faulty Inventory. All options are recalculated next update. 

However, RS only inserts if it can insert all items specified in the pattern at once. Not sure if the interface allows for that?

**Comment by desht** [comment]
> However, RS only inserts if it can insert all items specified in the pattern at once. Not sure if the interface allows for that?

Aha, that'll be it, thanks.  The interface only has a 1-slot inventory.  So yep - use a buffer.

**Comment by utoc** [comment]
Thank you for looking in to this; everything is working as intended.  Cheers.
