### ISSUE TITLE
Infinite energy with thermal compressors

### ISSUE THREAD

**Issue by Aazh** [TeamPneumatic/pnc-repressurized#468]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.1.63
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.2-10
### Describe your problem, including steps to reproduce it
Vortex tube connected to two thermal compressors produces more pressure than it consumes leading to a positive feedback loop.
![2020-05-07_18 00 02](https://user-images.githubusercontent.com/32171775/81311001-80910e80-908d-11ea-8018-7efc0443864b.png)

**Comment by desht** [comment]
Yeah, that shouldn't happen :)  I tested this in 1.12 and couldn't get enough air from it to power the vortex tubes, but looks like this needs revisiting.

**Comment by desht** [comment]
I've done some retuning on the Thermal Compressor's internal heat resistance, and with your setup, it can no longer produce sufficient pressure to keep the vortex tube running - the pressure in that system  slowly drops.  Tried adding a couple more compressors to the system, which worked as expected - compressors now use up heat faster than the vortex tube can produce it.

You can try out build 11+ from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ if you'd like to test this before I get a release out.  Would be interested to see if you can break it now :)

**Comment by Aazh** [comment]
Broken 
![2020-05-08_19 27 42](https://user-images.githubusercontent.com/32171775/81426605-1b5b1d00-9162-11ea-8983-bfbd0de8ebc0.png)

The logic i use is if the system reaches a steady state, does a compressor in it produce more mL/t than the pressure/ number of compressors. the vortex tube uses 10mL/t per 1 bar.
as each compressor in my new example generates a bit more than 2.5 at 1 bar, it is still raising.

**Comment by Aazh** [comment]
This setup seems broken as well, temperature at the vortex tube seems to keep dropping, have not reached a steady state yet though.

![2020-05-08_20 03 17](https://user-images.githubusercontent.com/32171775/81429861-1c427d80-9167-11ea-88e7-ed1d4287dbec.png)
![2020-05-08_20 03 21](https://user-images.githubusercontent.com/32171775/81429872-22385e80-9167-11ea-984b-1e710003dc00.png)
![2020-05-08_20 03 28](https://user-images.githubusercontent.com/32171775/81429876-25cbe580-9167-11ea-9ad4-5c72ecdef3de.png)

**Comment by desht** [comment]
This could be tricky to fix properly.  Short of nerfing the compressor into uselessness, I'm not sure...

I will do some more tuning and see if I can find a compromise.

**Comment by Aazh** [comment]
I have barely looked at your code but if AIR_GEN_MULTIPLIER means what i think it means,
i can just stack compressors like that to increase their effective resistance to make the temperature difference between the vortex tube and the heat sinks as high as i want.

**Comment by Aazh** [comment]
So the compressor should take energy away from the system somehow.

**Comment by Aazh** [comment]
So considering setups like this
![2020-05-08_20 34 53](https://user-images.githubusercontent.com/32171775/81432345-69c0e980-916b-11ea-877f-c76a1ac24acd.png)

Something as simple as cooling the hotter side by an extra degree every now and then could work.

**Comment by Aazh** [comment]
Basically, it should also do the same thing as a vortex tube does but backwards.

**Comment by Aazh** [comment]
Might be a seperate issue but as far as infinite energy goes it seems that thermal compressors have an immense potential even beyond wierd loops.
![2020-05-08_21 08 20](https://user-images.githubusercontent.com/32171775/81435250-39c81500-9170-11ea-8e4c-ceb89222dbce.png)

**Comment by desht** [comment]
There's a thermal connection between the two pairs of sides, so heat equalises across them.  That's how energy is removed from the system.  I initially reduced the resistance of that connection, meaning the temperature equalises faster, but clearly not by enough.  If I reduce it much further, then legitimate heat sources (e.g. a magma cube) will just get used up really fast and produce very little air.

AIR_GEN_MULTIPLIER (0.05) means it generates 0.05 mL of air each tick per degree of temperature difference across each side pair.

I notice a creative compressor in quite a few of your images.  Might I ask what pressure that's set to? :)

**Comment by Aazh** [comment]
![2020-05-08_21 34 14](https://user-images.githubusercontent.com/32171775/81437342-aee91980-9173-11ea-8428-58c3a0c34bd1.png)

**Comment by Aazh** [comment]
The problem here is that the heat equalization needs to relate to energy extraction not conductivity.

**Comment by desht** [comment]
> The problem here is that the heat equalization needs to relate to energy extraction not conductivity.
Yeah you're right there.

Just need to point out that a creative compressor set to 1.0bar will keep the whole system constantly at 1 bar, so that's where your free energy is coming from.  Any tests you do can't be valid when there's a creative compressor attached.

**Comment by Aazh** [comment]
![2020-05-08_21 38 59](https://user-images.githubusercontent.com/32171775/81437734-56fee280-9174-11ea-9d86-822443882984.png)

**Comment by Aazh** [comment]
![2020-05-08_21 41 16](https://user-images.githubusercontent.com/32171775/81437972-a8a76d00-9174-11ea-8201-f38ed191674d.png)

**Comment by desht** [comment]
Looks to me like the creative compressor is connected to the vortex tube?  So you're constantly pumping (infinite) energy into the vortex tube.

But I get your point about equalising heat based directly on air generated rather than allowing temperature to equalise "naturally" across the internal heat connector.  I'll do some recoding of the thermal compressor tomorrow and push another dev build.

**Comment by Aazh** [comment]
You can try to build it yourself

**Comment by desht** [comment]
I can but my point re: the creative compressor stands :)  The creative compressor is free energy, no ifs no buts.

**Comment by Aazh** [comment]
![2020-05-08_21 47 34](https://user-images.githubusercontent.com/32171775/81438495-89f5a600-9175-11ea-9f41-4544fe13821f.png)
![2020-05-08_21 52 27](https://user-images.githubusercontent.com/32171775/81438923-3899e680-9176-11ea-9c12-eecd741ba0c3.png)

**Comment by desht** [comment]
Have a try of build 12 and see if you can break it now :)

I did implement your suggestion of the "vortex tube in reverse".  This is *in addition to* the natural heat leakage between the two sides, although I increased the thermal resistance there.  I haven't been able to get any runaway air generation with any of your builds above, so maybe this one's the charm.

Since the compressor is now quite a bit weaker, I did bump up the heat capacity of blocks like magma to compensate, otherwise the thermal compressor becomes a bit useless... This also makes the Refinery & TPP a bit easier to heat with magma, but that's fine with me.

**Comment by Aazh** [comment]
I still seem to be getting energy loops but i am thinking of how best to demonstrate them.

**Comment by desht** [comment]
If you disconnect the creative compressor from that system, and close off the leak, does the pressure in the system continue to rise forever?  Or does it eventually level off and drop again?

**Comment by Aazh** [comment]
![2020-05-09_19 32 32](https://user-images.githubusercontent.com/32171775/81479458-e3b8a780-922b-11ea-8383-b036c129d963.png)
This creative compressor free system has rising pressure

**Comment by Aazh** [comment]
![2020-05-09_19 51 02](https://user-images.githubusercontent.com/32171775/81479831-7a866380-922e-11ea-9b30-c20bbe7ff883.png)
![2020-05-09_19 51 19](https://user-images.githubusercontent.com/32171775/81479833-7bb79080-922e-11ea-99bf-4265c72bf815.png)

**Comment by desht** [comment]
Yeah, that last build of yours does manage to keep the pressure rising.  But very slowly, and there's also the point that if you actually try to do any work with that pressure, the energy removed disrupts the feedback cycle.

So yeah, it's technically "wrong" in that it breaks the laws of physics (but this is a game where blocks can hang in mid-air...), but I don't think it's game-breaking at this point.  It's hard to make that free pressure do any useful work.

**Comment by Aazh** [comment]
Mhm, at this point it is not really than passive desert border energy considering the resource cost and it is not efficient enough to stumble onto the effect by just deciding to build two thermal compressors to help recover air for refinery heating like I did.

**Comment by desht** [comment]
Gonna close this since I think we're about as good as we can get here.  Thanks for all your effort in testing this!
