### ISSUE TITLE
Amadron - Compass Trade 

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#470]
### Minecraft Version
1.15.2
### Forge Version
forge-31.1.74
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-8
### Describe your problem, including steps to reproduce it

I assume this is an NBT issue. I had a Compass > Emerald trade pop up in Amadron that I couldn't complete because it didn't detect my compasses as valid. An auto crafted compass piped directly into my input chest does work, so the Item matching is probably too strict here.

**Comment by desht** [comment]
Amadron does do strict NBT matching at this time, yes - it needs to since things like potions and enchanted gear can be traded (and player-player trades are a thing).  I didn't think vanilla compasses could have NBT data?  At least not before 1.16.

I guess I could add some kind of "match nbt" setting in Amadron recipes.  Or possibly just not do NBT matching if the recipe item doesn't have any NBT...

**Comment by desht** [comment]
Update: I crafted a compass, and it doesn't have any NBT.  And I didn't have any problem trading it via Amadron, either.  Got a bit more info about these compasses you can't trade?  The `/dumpNBT` command (added by PneumaticCraft) might be helpful here.

**Comment by MuteTiefling** [comment]
I'd have to wait for it to come back I think.  Perhaps NBT is the wrong term, but it's when the compass direction doesn't point straight up. When crafted, the compass needle is up, but once a player holds it it starts to spin. I had placed some of these in the chest and the trade was still red in Amadron.

**Comment by desht** [comment]
Yeah, I'd held the compass and moved around with it, it still had no trouble being accepted by Amadron...

**Comment by MuteTiefling** [comment]
Compass seems to get NBT data on it from Quark that isn't there on one dragged straight in from JEI. The JEI ones work, but not the ones that get tagged by quark. 

https://streamable.com/vvb00h

`{"quark:compass_calculated":1b,"quark:compass_in_nether":0b}`

**Comment by desht** [comment]
Ah, Quark.  OK.  I'll see if I can work around this by not checking for NBT on items which don't naturally have it.

**Comment by TeamSpen210** [comment]
You could trigger this with just PneumaticCraft as well, by renaming the item in an anvil.

**Comment by desht** [comment]
Build 12 should resolve this.  Would be useful if you could do some extra testing on this to ensure this change doesn't introduce any subtle problems...

**Comment by MuteTiefling** [comment]
I'll drop in 12 tonight and let you know what I find.

**Comment by desht** [comment]
Fixed in 1.1.2 release
