### ISSUE TITLE
Aerial Interface - Localization Missing

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#471]
### Minecraft Version
1.15.2
### Forge Version
forge-31.1.74
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-8
### Describe your problem, including steps to reproduce it

Curio Inventory localization is missing. 

### Any other comments?

![2020-05-07_20 29 27](https://user-images.githubusercontent.com/9543430/81357409-901a5280-90a1-11ea-8785-54339daefc77.png)

**Comment by desht** [comment]
Yep, I'd left the old `baublesInv` translation in there.

**Comment by desht** [comment]
Fixed in build 10+ from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/

**Comment by desht** [comment]
Fixed in 1.1.2 release
