### ISSUE TITLE
Crash when drone works

### ISSUE THREAD

**Issue by Ibirtem** [TeamPneumatic/pnc-repressurized#473]
When i place drone into world and they start working after some time become random crash

Forge: 31.1.77
Mod Version: 1.1.1-6

Crash report:
https://gist.github.com/Ibirtem/ddf937d1dd069e3cc140dbcd9cbfc9d7

**Comment by desht** [comment]
I can add some extra checks to prevent this, but what other mods are you running here?  I can see a lot of mixin/accesstransformer reference in the crash log, and there's a good chance something else is interfering here.

**Comment by desht** [comment]
Should be fixed with build 11+ from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/

**Comment by desht** [comment]
Fixed in 1.1.2 release
