### ISSUE TITLE
Amadron crash when creating custom trades

### ISSUE THREAD

**Issue by utoc** [TeamPneumatic/pnc-repressurized#474]
### Minecraft Version
1.15.2
### Forge Version
31.1.74
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-6
### Describe your problem, including steps to reproduce it
Open up amadron to create a custom trade like so:

![javaw_QmUFfdJ4FH](https://user-images.githubusercontent.com/11995956/81416237-0bfeb400-910f-11ea-8b61-4c933788e621.png)

Upon clicking "Add Trade" you're treated to a Server Closed message.  When reconnecting to the server, no custom trades are listed.

(Using strictly vanilla items also causes a crash, this was just the first item that came up to get a screenshot)

In singleplayer you will get an exception: https://gist.github.com/utoc/2da5a4bcb22ddec8737d38a01d67770b and the trade is not listed when opening the Amadron GUI back up.

Fluids also cause a crash
### Any other comments?
See crashlogs here:

[crash-2020-05-08_14.03.25-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4599586/crash-2020-05-08_14.03.25-server.txt)
[crash-2020-05-08_14.23.35-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4599587/crash-2020-05-08_14.23.35-server.txt)
[crash-2020-05-08_14.31.53-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4599588/crash-2020-05-08_14.31.53-server.txt)

**Comment by desht** [comment]
Both problems should be fixed in build 12 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/

**Comment by desht** [comment]
Fixed in 1.1.2 release
