### ISSUE TITLE
Fluid Dupe Bug

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#477]
### Minecraft Version
1.15.2
### Forge Version
forge-31.1.74
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-14
### Describe your problem, including steps to reproduce it

Cross mod interaction. I've placed a Liquid Hopper on a Mekanism Dynamic Tank (directly on the valve). It appears to be endlessly extracting from the Dynamic Tank.

### Any other comments?

https://streamable.com/tl4uvx

Log: https://gist.github.com/MuteTiefling/35035792f5d37b3dc23c97a931ba7190

**Comment by desht** [comment]
Not seeing that behaviour in my test world (dedicated server, Mekanism 9.10.2.415).  I can see the liquid level in the Dynamic Tank steadily dropping as the liquid hopper extracts, just as expected.

**Comment by desht** [comment]
I'd recommend re-testing with the latest Mek (https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2952808) - I know they're updating pretty fast over there.

**Comment by MuteTiefling** [comment]
Ah, hadn't realized I was on an old version with that. Fair enough. Probably been fixed already

**Comment by desht** [comment]
Think this can be closed.  Seems to be fine with up-to-date Mek releases.
