### ISSUE TITLE
Problem with folder aux on windows filesystems

### ISSUE THREAD

**Issue by GeldornOfDragonhill** [TeamPneumatic/pnc-repressurized#478]
The foldername "aux" [src/main/java/me/desht/pneumaticcraft/common/config/aux] is problematic on windows devices as it is in a group of reserved names (https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions).

Maybe consider renaming it to something else so that the repository works with windows filesystems.

**Comment by desht** [comment]
Done!
