### ISSUE TITLE
Minor Log Issues with Quark Compatibility

### ISSUE THREAD

**Issue by NillerMedDild** [TeamPneumatic/pnc-repressurized#479]
### Minecraft Version
1.15.2

### Forge Version
1.15.2-31.1.79

### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.2-14

### Describe your problem, including steps to reproduce it
I found some errors from PneumaticCraft, looks like there's an old reference to blocks Quark no longer has:
https://gist.github.com/NillerMedDild/b454af74fa17ab06a584f29d81f56f4e

**Comment by desht** [comment]
Yeah they're from 1.12.2.  I'll get those updated.

**Comment by desht** [comment]
Fixed in 1.1.3 release
