### ISSUE TITLE
NBT Filtering issues with Logistics Frames

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#480]
### Minecraft Version
1.15.2
### Forge Version
forge-31.1.78
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-14
### Describe your problem, including steps to reproduce it

There's two issues here. If you want me to split them up, that's fine. But it all seems to be related to the requester frame logic.

As you'll see in the video, the NBT filter breaks down under specific conditions.

Working: 
1. Set Requester to pull Empty gas tanks by NBT matching
1. Put an empty gas tank in the Storage Frame
1. Watch it get pulled
1. Put a full one in the Storage Frame and it will not get pulled.
1. Put an Empty one in any slot and a full one in any slot with a higher index and it will correctly pull only the empty tank

Not Working:
1. Put a full tank in any slot
1. Put an empty tank in any slot with a higher index than the full tank.
1. Watch as the logistics network triggers, but pulls the first item, regardless of NBT matching. 

This becomes problematic when I'm using an inventory that cannot accept the item that's being sent. In the linked example, that's a mekanism gas tank. This will not accept a full tank in the charging slot. It would appear that the logistics network pulls the items without first checking if they have a valid place to send them. Since they can't go into the tank, they appear to be voided. 

I can recreate the NBT issue with just PNC tanks and vanilla inventories, but I can't think of another block to insert into that specifically limits what can go into it based on the NBT data. So that one is tougher. Also of note, if I use a hopper as an intermediate inventory, it still gets the full tanks incorrectly, but at the least it does not void the full tanks.

### Any other comments?

https://streamable.com/7ij1p5

Nothing in the logs, unfortunately.

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Give build 16 a go, should hopefully fix that...

**Comment by MuteTiefling** [comment]
Yep, looks all good in 16. Awesome-sauce :D

**Comment by desht** [comment]
Fixed in 1.1.3 release
