### ISSUE TITLE
Issues with GUI layers in Programmer

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#482]
### Minecraft Version
1.15.2
### Forge Version
forge-31.1.78
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-14
### Describe your problem, including steps to reproduce it

There are some layering issues in Drone programming. Occasionally drop down menus (for variables, for instance) will display behind the other GUI elements on the object. I'm finding that when picking new puzzle pieces out of the side bar, it will also pick up the puzzle pieces already laid out on the programmer if they're underneath the new piece you're attempting to grab. 

### Any other comments?

https://streamable.com/qnfdm9

![2020-05-14_00 48 04](https://user-images.githubusercontent.com/9543430/81893908-a4b48a00-957c-11ea-9209-03cbe3053747.png)

**Comment by desht** [comment]
Confirmed & fixed in dev (along with a few other GUI annoyances I'd meant to address but forgot about...)

**Comment by MuteTiefling** [comment]
Yep! Seems to work much more cleanly, thanks!

**Comment by desht** [comment]
Fixed in 1.1.3 release
