### ISSUE TITLE
Drone Programming - Area Collection having difficulty with items in planted bamboo

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#483]
### Minecraft Version
1.15.2
### Forge Version
forge-31.1.87
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-17
### Describe your problem, including steps to reproduce it

Drones cannot pickup items if they fall inside of bamboo.

https://streamable.com/oevthv

### Any other comments?

I'm also having trouble with it collecting bamboo in general in my actual game world. I cannot reproduce that in my test world, however. Effectively I've got a small platform out in the water with bamboo growing on it. Anything that falls in the water, in bamboo, or on the stairs bordering the whole structure is not detected as a valid item for pickup. With or without a filter on the pickup widget. It only seems to want to grab the bamboo that's fallen on a flat surface.

**Comment by desht** [comment]
Yeah, drones don't consider Bamboo to be pathfindable, and it would actually be quite difficult to make it so.  Vanilla entities also refuse to path through bamboo (try luring a chicken across a bamboo patch with some seeds, for example).

What you can do as a workaround is give your collector a few magnet upgrades.  In my testing, that works in most cases, as long as the dropped items are in range of the drone's magnet range.

Actually, I have an idea for getting round this problem... which should help with stairs too.  Let me do some experimentation and I'll get back to you.

As for water, drones won't enter water with a Security Upgrade.  So if your items are likely to fall in water, adding that upgrade should help.

**Comment by desht** [comment]
OK, give build 18 a go ;)

It should work fine as long as you don't have dense thickets of bamboo... items in the middle of a 3x3 patch still won't be reachable but I don't consider that an error.  What my change does is allow the drone to get next to the bamboo (or stairs etc.) and pull the item out of the blockspace.

**Comment by MuteTiefling** [comment]
Awesome. I'll give it a try. 

For water though, in my testing world the drone was getting the things floating on the surface of the water. I'll try dropping in a security upgrade as well to see if that helps with that in the game world though.  

Here's a quick video of the current situation though. Something is keeping it from collecting even the stuff on the sand now and I don't get it. It's outside of the range of the solegnolia (and that doesn't effect the drone anyway). It picked up a couple, but clearly not nearly as much as one would expect.

https://streamable.com/2w09u7

Program: https://gist.github.com/MuteTiefling/18852b66ec5bca3e4a4fbe8238899cc0

This attempt was using a clear cutting approach that would only replant after all the bamboo was harvested. But it's just not working out. I'm baffled by this though because this works fine in my test world...

I guess in the end I may just have to move the bamboo away from the mana production so I can use magnets without the drone interfering with the mana production itself.

**Comment by MuteTiefling** [comment]
18 is working perfectly in test for the pickup, so that's great. Nice job!

This actually means a thick grove works, so long as you cut them down to 1 high. The drone is successfully picking up from above as well as the sides. 

I'll test some more in my play world, but I suspect something else is also interfering there that I just can't put my finger on. That's OK though.

**Comment by MuteTiefling** [comment]
So, bit of a bummer here, but I'm having trouble using a magnet drone to drop the bamboo since it picks it right back up (only has 2) before it can fall away from the drone. 

It got me thinking that it could be neat to have a program puzzle piece that let's you set a filter on the magnet pickup. So early on in the program I could set the magnet to allow bamboo, but then when I want to drop it, I could change the filter again just before.

**Comment by desht** [comment]
Hmm, it might be simpler just to have the magnet respect the pickup delay on dropped items (40 ticks, I think).

**Comment by MuteTiefling** [comment]
You rock! Can't wait to give it a try.

**Comment by desht** [comment]
Fixed in 1.1.3 release
