### ISSUE TITLE
Drone Magnets do not respect Botania Solegnolia

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#484]
### Minecraft Version
1.15.2
### Forge Version
forge-31.1.87
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.1-17
### Describe your problem, including steps to reproduce it

Place down a Solegnolia, a couple items, and then place a drone that has magnet upgrades in it. It will immediately pickup all of the items.

**Comment by desht** [comment]
Yeah, they only affect players right now. That should be fixed.

**Comment by desht** [comment]
Fixed in 1.1.3 release
