### ISSUE TITLE
PneumaticCraft:fuid ingredient type error

### ISSUE THREAD

**Issue by NillerMedDild** [TeamPneumatic/pnc-repressurized#485]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2

### Forge Version
1.15.2-31.1.87

### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.2-14

### Describe your problem, including steps to reproduce it
The Speed Upgrade recipe fails to be registered in the modpack Enigmatica 5 - The log indicates that something goes wrong with the PneumaticCraft fluid ingredient type:
`
[21:20:13] [Server thread/ERROR]: Parsing error loading recipe pneumaticcraft:speed_upgrade: Shaped recipe ingredient {"type":"pneumaticcraft:fluid","fluid":"pneumaticcraft:lubricant","amount":1000} with key 'C' is not a valid ingredient!
`
However, I've been told that the recipe works just fine with PneumaticCraft standalone, so this isn't really a bug report, it's more of a PSA that the ingredient type can error.

### Any other comments?
Feel free to close the issue.

**Comment by desht** [comment]
Thanks for letting me know.  Out of interest, do you know what's causing the problem at this point?  Anything else relevant in the server logs?

**Comment by NillerMedDild** [comment]
Not yet I'm afraid, but I suspect either CraftTweaker or KubeJS plays a role in it.
Here's the latest.log: https://gist.github.com/NillerMedDild/dce2e469d286b1652449b185afae07e0

**Comment by Darkere** [comment]
I assume this is the same issue as this one. https://github.com/KubeJS-Mods/KubeJS/issues/11

This is what appears in the debug log.
[02Jul2020 13:39:43.139] [Server thread/ERROR] [KubeJS Server/]: Parsing error loading recipe pneumaticcraft:speed_upgrade: Shaped recipe ingredient {"type":"pneumaticcraft:fluid","fluid":"pneumaticcraft:lubricant","amount":1000} with key 'C' is not a valid ingredient!

**Comment by NielsPilgaard** [comment]
It is indeed, and the KubeJS dev has fixed it: https://github.com/KubeJS-Mods/KubeJS/issues/14
