### ISSUE TITLE
The texture for the pressure chamber glass is missing

### ISSUE THREAD

**Issue by JoaqsJoaqs** [TeamPneumatic/pnc-repressurized#486]
#120 
# Minecraft Version
1.14.4
### Forge Version
1.14.4-forge-28.2.11
### Mod Version
pneumaticcraft-repressurized-1.14.4-1.0.3-12
### Describe your problem, including steps to reproduce it
place down a piece of pressure chamber glass.
### Any other comments?
It is visible in inventory, on hand, or jei. The texture is only missing when placed down or in multiblock form.

**Comment by desht** [comment]
Try F3+T and see if that helps.  I've seen occasional problems where the custom block model loader for pressure glass doesn't get registered, and I don't know what causes it, but a resource reload usuall fixes it.

If that doesn't help, post a link (pastebin etc.) to your full log.

**Comment by JoaqsJoaqs** [comment]
> Try F3+T and see if that helps. I've seen occasional problems where the custom block model loader for pressure glass doesn't get registered, and I don't know what causes it, but a resource reload usuall fixes it.
> 
> If that doesn't help, post a link (pastebin etc.) to your full log.

Thank you, it worked!

**Comment by desht** [comment]
Closing this, the problem is a race condition fixed in newer Forge releases, and 1.14.4 is no longer supported.
