### ISSUE TITLE
Crash on new version of forge

### ISSUE THREAD

**Issue by BedrockLegends** [TeamPneumatic/pnc-repressurized#487]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
Crashes on Launch of pack
### Any other comments?
https://gist.github.com/BedrockLegends/2f5070f1fe270bce441d4252a99330b4

**Comment by desht** [comment]
Need to see your full log.  The problem is almost certainly a crash earlier on which prevent further registration of objects (in this case pressure tubes), NOT a bug in PNC itself.

**Comment by lamoyrl90** [comment]
I've got a similar issue going on, and even without Pneumaticcraft it happens. I think one (or more) of the mods we share didn't implement their registries in a way that worked when Forge updated recently. I'm not sure where the issue originates for me, though. I'll post here if it's relevant when I figure it out.

**Comment by lamoyrl90** [comment]
Try it without Botania.

**Comment by lamoyrl90** [comment]
I think it's BoP. RIP!

**Comment by desht** [comment]
Closing this, it's not PneumaticCraft at fault here (just the first mod which tries to register a color handler).  Some other mod has broken registration, and it might be BoP.  But it's not this mode.
