### ISSUE TITLE
[Error][Bug?]: TOP support being loaded despite it not being present, causing errors to be thrown in log.

### ISSUE THREAD

**Issue by Lanse505** [TeamPneumatic/pnc-repressurized#489]
### Minecraft Version
1.15.2

### Forge Version
31.2.0

### Mod Version
pneumaticcraft-repressurized-1.15.2-1.1.2-14

### Describe your problem, including steps to reproduce it
TOP third-party support is being loaded regardless of it being present or not.
Throwing errors in log:
![bild](https://user-images.githubusercontent.com/1495068/82208563-12a9da00-990c-11ea-8d64-ace121b2f3fc.png)

### Any other comments?
I do have Hwyla in-place and it works just fine :)

**Comment by desht** [comment]
Yeah, I can see what's going on here.  Will fix for the next release.

**Comment by desht** [comment]
Fixed in 1.2.0 release
