### ISSUE TITLE
Crash from Security station Render

### ISSUE THREAD

**Issue by UltimateFisher** [TeamPneumatic/pnc-repressurized#493]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.1.74
### Mod Version
1.2.0
### Describe your problem, including steps to reproduce it
I tried to use my Pneumatic helmet to hack a friends security station that I placed and they locked me out of. As soon as the block outline renders, I crash

### Any other comments?

[crash-2020-05-19_14.54.33-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4652821/crash-2020-05-19_14.54.33-client.txt)

**Comment by desht** [comment]
Yeah I need to disable that.  It's broken right now and needs a complete rework.

**Comment by desht** [comment]
Security Station hacking is a thing again in MC 1.16 (mod version 2.9.1)
