### ISSUE TITLE
[Feature proposal] Etching Acid tweaks

### ISSUE THREAD

**Issue by DevTimur** [TeamPneumatic/pnc-repressurized#494]
I got couple ideas about etching acid, take any if you like, or none of them, and just close this topic

1) You can speed up pcb development in etching acid by "heating it up".
**How I see it:** _You place compressed iron blocks  around pool of acid (similarly to AE2 growth chamber accelerators), and you just heat thous blocks using... heat... It will add bubbling effect to block of acid, and any empty pcb dropped in acid will develop much faster_

2) You add heat frame to vanila cauldron, and now you can place acid inside. If you place fire under cauldor bubbling effect will apear, now just rightclick empty pcb to cauldron and develop it instantly. Tho it will come with a cost of 1/3 of acid (similar to bottling water from cauldron). It would be great if you can add acid to cauldron using pipes (from other mods), and maybe add alternative recipe for etching acid. for example using Thermopneumatic Plant, not sure what recipe will be, because originally Etching Acid is FeCl3 + 6H2O (Mix of Ferric Chloride and Water, aka Iron, Salt and Water).

**Comment by desht** [comment]
Your ideas are pretty much already in the 1.15 version of the mod :) although there is a specific Etching Tank machine rather than a cauldron. Heating is optional, and speeds up the process and (slowly) uses up the acid. 

Won't be back porting to 1.12 though... no new dev will be happening there.

**Comment by DevTimur** [comment]
Oh cool. I haven't check 1.15 yeat tho.

ср, 20 Май 2020, 21:24 desht <notifications@github.com>:
