### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Cardoso2812** [TeamPneumatic/pnc-repressurized#495]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2 
### Forge Version
31.1.46
### Mod Version
1.1.0-3
### Describe your problem, including steps to reproduce it
Playing the game normally and out of nowhere server crashes happened to me 3 times and all the same logs anyway I will post them all
[crash-2020-05-20_22.01.04-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4659461/crash-2020-05-20_22.01.04-server.txt)
[crash-2020-05-20_22.23.09-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4659462/crash-2020-05-20_22.23.09-server.txt)
[crash-2020-05-20_22.44.27-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4659463/crash-2020-05-20_22.44.27-server.txt)

**Comment by desht** [comment]
Upgrade to the most recent version (1.2.0).  That bug has been reported and fixed already.
