### ISSUE TITLE
Programmer puzzle pieces not visible in program area

### ISSUE THREAD

**Issue by Ademius** [TeamPneumatic/pnc-repressurized#496]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2

### Forge Version
31.1.41

### Mod Version
1.1.2-14

### Describe your problem, including steps to reproduce it
I placed a Programmer, have puzzle pieces in my inventory, put a drone or a disk in the top right slot. I drag a puzzle piece from the menu on the right, and nothing seems to happen. Except that now the program won't write because there are errors, like "no piece below the start piece". If I mouse around carefully, I can find where it thinks the start piece is, but I can't see it. I can grab it and remove it from the area, and watch it fly off to the side, but I can't see it (or any other piece) while it's in the active area.

### Any other comments?
https://gyazo.com/1ec03c156d12a05436cf75ba90fc4028

**Comment by desht** [comment]
Hmm, possible clipping issue there. What is your screen resolution and scale setting? I'll try to reproduce but I'll need that info.

**Comment by Ademius** [comment]
1100 x 700 window resolution, 'Auto' scaling.

Interesting; if I set it to any fixed scale, it works fine. So it's somehow an issue with the Auto scale GUI. 

I don't know if it's worth trying to fix or not, or just recording that it's a thing. I'll let you decide on closing this issue or not.

Thanks

**Comment by desht** [comment]
I'd like to fix it if I can, so I'll keep this open for now and see if I can reproduce it.

**Comment by VeryFriendlyOne** [comment]
I have absolutely same issue! GUI scale wasn't auto, it was 1, now I put the scale to 2 and it works!

**Comment by desht** [comment]
Yeah, I believe I've fixed this in dev. Should be fine in the next release.

**Comment by desht** [comment]
Fixed in 1.2.2 release
