### ISSUE TITLE
Minigun doesn't hurt wither

### ISSUE THREAD

**Issue by UltimateFisher** [TeamPneumatic/pnc-repressurized#498]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.1.74
### Mod Version
1.2.0
### Describe your problem, including steps to reproduce it
I don't know if this is a bug, but the minigun doesn't do any damage to the wither.

**Comment by desht** [comment]
The minigun *does* hurt the wither - I just tested.

Basic ammo with an un-upgraded gun doesn't do much damage, but it does work.  If you want the minigun to actually be useful against the wither, I'd use a different ammo type and upgrade your gun.

In my testing, a Minigun with 3 Speed Upgrades and Weighted Ammo slaughters the wither pretty quickly.  Other ammo types are also worth playing with.

**Comment by desht** [comment]
Going to close this because the minigun is definitely damaging the wither as expected.  Feel free to reopen if you can document a case where no damage is being done.
