### ISSUE TITLE
Drone Programming - External Program doesn't appear to work

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#499]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.0
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.2.0-21
### Describe your problem, including steps to reproduce it
I can't seem to get External Programs to execute. I've got a drone programmed to look for programs in a reinforced chest that, when placed on the ground, does nothing. It just sits there.

I had multiple programs in there, so I took them out to simplify things. I've currently only got a single program that consists of a Go To, Standby, and Wait 1m. It should go sit on it's charger and do nothing else. But the drone just sits wherever I happened to deploy it. 

### Any other comments?
Ran a similar test in my testing world and the drone didn't seem to do anything with the programs stored in the chest either. 

On a side note, debugging these types of programs tends to be a bit complicated since the debugger only shows what's programmed into the drone, not the external program it would be executing.

**Comment by desht** [comment]
Easier fix than I expected.

As for debugging external programs, that's a little more difficult.  I'll leave this ticket open for now to remind me I need to investigate the feasibility of a fix for that.  It's not trivial to do since it involves a lot of server <-> client sync'ing.

**Comment by MuteTiefling** [comment]
Cool! I've gotten in the habit of just tossing the API on a drone instead to test it first, or setting a bunch of Rename Drone actions in it to figure out what it's doing, but if there's anything you can do, that'd be awesome.

**Comment by MuteTiefling** [comment]
This is working great now, thanks!

**Comment by desht** [comment]
Fixed in 1.2.1 release
