### ISSUE TITLE
[suggestion] more config options for sound emitting blocks

### ISSUE THREAD

**Issue by Knito58** [TeamPneumatic/pnc-repressurized#501]
I only found the elevator at this time. An option to switch off pressure related sounds would be highly appreciated.

**Comment by desht** [comment]
Yeah, I can add that.  Along with a big disclaimer that switching off air leak noises could leave you with pipes leaking (and wasting fuel) that you never find out about...

**Comment by Knito58** [comment]
Thank you Sir.

**Comment by Knito58** [comment]
Of course, I would allow leak noises in the config.

**Comment by desht** [comment]
Yep, they'll still be noisy by default.  But players will be able to make the sound quieter (or even off) if they want to.

**Comment by Knito58** [comment]
Thank you for planning that. I'm already happy :)

**Comment by MuteTiefling** [comment]
One thing I'd love to see with this is to have the jet boot noise for build mode mutable separately from normal flight mode.

I love hearing them while I'm zipping around the world, but I find them distracting when doing some creative building.

**Comment by Knito58** [comment]
@MuteTiefling: This would be a "remute" : **RE**mote sound **MUT**Er.

**Comment by desht** [comment]
Fixed in 1.2.1 release

**Comment by Knito58** [comment]
Thank you! Works.
I left a star...
