### ISSUE TITLE
[1.15.2] Refinery controller can see through blocks

### ISSUE THREAD

**Issue by ocram9** [TeamPneumatic/pnc-repressurized#502]
### Minecraft Version
1.15.2

### Forge Version
31.2.0

### Mod Version
1.2.0-20

### Describe your problem, including steps to reproduce it
When the refinery controller is placed against a block, the left or right side (depending which one hits the block) makes the block next to it invisible.

Steps to reproduce:
- Place the refinery controller next to a wall with the front of the controller facing you.
- The block next to the controller turns invisible.

### Screenshots
![2020-05-24_16 12 07](https://user-images.githubusercontent.com/49008532/82756347-06c18a80-9dda-11ea-9356-568083dcf684.png)

![2020-05-24_16 12 11](https://user-images.githubusercontent.com/49008532/82756352-0923e480-9dda-11ea-8681-654f4e54d41d.png)

**Comment by desht** [comment]
Fixed in 1.2.1 release
