### ISSUE TITLE
Request: Allow multiblock tanks to fill from the bottom

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#503]
I wasn't sure if this was a bug or intentional, so I'm making this as a feature request. 

When multiple tanks are wrenched together, it could be nice if fluids pumped into the bottom tank would flow up into the others as the lower ones fill up.

For instance, last night I left an oil processing system set up where diesel gets converted to lubricant. The lubricant is simply pushed from the TPP using a dispenser upgrade and feeds into a stack of 4 connected tanks. When the first tank filled up, however, it simply backed up in the TPP and eventually halted the operation. 

![2020-05-25_09 13 04](https://user-images.githubusercontent.com/9543430/82816041-69616780-9e68-11ea-83fd-2693cee2cac0.png)

**Comment by desht** [comment]
It's actually intentional (and indeed documented in the Patchouli manual), partly for "realism" (the amount of pressure needed to push fluid up that high is enough that some kind of powered system would be needed), and partly for simplicity of implementation.

I can appreciate it would be useful to do this, but it doesn't work that way...

**Comment by MuteTiefling** [comment]
Fair enough. Hadn't noticed the documentation in patchouli. Thanks!

**Comment by desht** [comment]
Probably the easiest option in your setup would be with a Logistics Module on the top tank requesting the lubricant.

Liking your use of Heat Pipes btw :)

**Comment by MuteTiefling** [comment]
Heat pipes are amazing. Such a helpful addition. One vortex tube supplies all of the heating and cooling for the whole setup and it just gets piped around

And ultimately I will probably either logistics pipe it to a bigger storage or even just have a drone craft speed upgrades on the spot. I'm torn on that. The whole thing needs to be moved anyway though.
