### ISSUE TITLE
[Suggestion] Pneumatic Lamps

### ISSUE THREAD

**Issue by cyberdragon442** [TeamPneumatic/pnc-repressurized#504]
I was originally planning on adding this as compatibility in a mod idea I have about powered lamps (not going into detail on that here), but thought it would be cool if it was in the base mod.

This is based on a real device (by the same name), and in-game would basically be an alternative to Immersive Engineering's powered lantern.

Required Pressure: 7 bar (typical for the real device)

**Comment by desht** [comment]
The kerosene lamp basically does this already...

**Comment by cyberdragon442** [comment]
It isn't powered by air itself though and as far as I checked it could not be piped into (run continously, unless that was recently changed).

**Comment by desht** [comment]
It's always been possible to pipe fuel into it, and drives can also be used to fill it.

A compressed air lamp is a cool idea, and makes sense in the context of this mod, but it would just be a bit redundant at this point, unfortunately.

**Comment by cyberdragon442** [comment]
That's fine, as I said I planned to make my own about upgradable powered lamps some day and it would have way more functionality in that mod anyway, as an "alternative power" option to those machines. (There'll also be an upgraded version of the kerosene lamp that adds new mechanics).

Yes, I will keep balance in mind (hence the 7bar pressure requirement, aka needs upgraded pipes) and not infringe on any mechanics of this or other mods I plan to be compatible with.

**Comment by desht** [comment]
That's cool, I will look forward to see what you come up with :)  Gonna close this now, but feel free to come back with any questions.  I know the PNC:R API hasn't had much (if any) testing so any problems you encounter, I'll be happy to help with.

**Comment by wander34** [comment]
hey cyberdragon 442, any chance you can help me with a bit of coding? I saw a comment you left on another post and thought you may be able to help me out. if you can, shoot me an email

willyanderson987654321@gmail.com
