### ISSUE TITLE
[Mod Interaction] Astral Sorcery Attunement stops Pneumaticcraft armor from working

### ISSUE THREAD

**Issue by Duckapple** [TeamPneumatic/pnc-repressurized#505]
### Minecraft Version
1.12.2

### Forge Version
14.23.5.2847

### Mod Version
1.12.2-0.11.14-395
*Astral Sorcery* - 1.10.22

### Describe your problem, including steps to reproduce it
I use pneumaticcraft armor to fly around and get movement speed and such, but as soon as I completed the Astral Sorcery Attunement ritual for my player character, the pneumaticcraft armor didn't give any of my benefits.

### Any other comments?
**This problem can be fixed by saving the world and reloading it**, but I wanted to report the bug anyways.
I have posted this issue to the Astral Sorcery GitHub as well, link [here](https://github.com/HellFirePvP/AstralSorcery/issues/1294).

**Comment by desht** [comment]
Since this isn't a critical bug and it's on 1.12.2, I'm afraid I won't be looking into fixing it, sorry.  All development is now on 1.15.2.

**Comment by NielsPilgaard** [comment]
This issue has re-emerged on 1.16.5 :)
https://github.com/NillerMedDild/Enigmatica6/issues/2362

**Comment by desht** [comment]
More updates in the E6 issue, but I just tested and I don't see a problem. Vicio + Pneumatic Armor works perfectly fine for me.  Maybe there's some other mod interfering, I don't know.

**Comment by NielsPilgaard** [comment]
Yup you're right, the original reporter no longer has the issue, a reload fixed it ^^'
