### ISSUE TITLE
[1.15.2] Amadron drones drop loot when they despawn

### ISSUE THREAD

**Issue by ocram9** [TeamPneumatic/pnc-repressurized#507]
### Minecraft Version
1.15.2
### Forge Version
31.2.5
### Mod Version
1.2.1-25

### Describe your problem, including steps to reproduce it
When an amadron drone picks up the emeralds from the chest, they fly away and then "die."
When they die they sometimes drop their emeralds (I haven't been able to reproduce this 100% of the time). They always drop their nametag though.

Steps to reproduce:
1. Buy something using the amadron tablet.
2. Let the drone pick up the emeralds.
3. Follow the drone until it "dies" and watch as it drops loot.

**Comment by desht** [comment]
Not seeing this at all (either in dev environment or on dedicated server).  Amadrones are not dropping their items or name tags.

So this is probably related to some other mod you have installed.  I'd need to know what.

**Comment by ocram9** [comment]
I have test removing Ai improvements and performant already without succes. This is my modlist:
- https://prnt.sc/spew2q
- https://prnt.sc/spewcr
- https://prnt.sc/spewlf

**Comment by desht** [comment]
That's a pretty long mod list - I can't see anything obvious there.

Can you try out build 26 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ ? It may or may not help...

**Comment by ocram9** [comment]
I have figured out the problem by testing the mods individually with pneumaticcraft. The latest build still caused items to be dropped but the nametags are caused by the vanillatweaks mod. 

I haven't seen it drop emeralds anymore though so that might have been a one-off.

**Comment by desht** [comment]
OK, give build 27 a go.  Amadrone inventory *should* be empty by the time they die, but there are possibilities (shouldn't happen but apparently do) where the inventory might not get emptied.  I've added an extra safeguard for that.

**Comment by ocram9** [comment]
I have tested quite a few drones in creative and I haven't seen it drop any emeralds so it seems to be fixed.

**Comment by desht** [comment]
Fixed in 1.2.2 release
