### ISSUE TITLE
Inserting Network API crashes the game

### ISSUE THREAD

**Issue by VeryFriendlyOne** [TeamPneumatic/pnc-repressurized#508]
Minecraft Version: 1.15.2
Forge Version: 31.1.77
Mod Version: 1.1.0-3
Describe your problem, including steps to reproduce it:
Hi, so, i have a problem, i don't think how you're able to reproduce it, may have something to do with other mods or just my old pc, but i was able to reproduce it. Basically, inserting Network API into programmer crashes the game, i even have crash logs
[crash-2020-05-29_00.30.46-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4698494/crash-2020-05-29_00.30.46-client.txt)
[crash-2020-05-29_00.37.23-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4698495/crash-2020-05-29_00.37.23-client.txt)
[crash-2020-05-29_00.44.19-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4698496/crash-2020-05-29_00.44.19-client.txt)
[crash-2020-05-29_00.53.05-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4698497/crash-2020-05-29_00.53.05-client.txt)
Any other comments?
I'll provide any info, if you need it.
Was trying to make drone quarry, so the program was export from chest, dig, pick up, import into the chest

**Comment by desht** [comment]
Please test this against the latest release - 1.2.1-25.  I don't provide support for old releases (1.1.0-3 was the very first alpha release and many fixes have been applied since then).

**Comment by VeryFriendlyOne** [comment]
Will do, thanks!

**Comment by VeryFriendlyOne** [comment]
Installed new version, it still crashes the game.

**Comment by desht** [comment]
Stacktrace, please.

**Comment by VeryFriendlyOne** [comment]
I decided to create new world, it works fine, idk what had happened in previous world. I think it's better to close the issue
