### ISSUE TITLE
Fuel buckets in solid-fuel compressors

### ISSUE THREAD

**Issue by desht** [TeamPneumatic/pnc-repressurized#51]
* The bucket is currently consumed by the compressor; empty bucket should be returned
* Revisit the efficiency of fuel buckets.  I suspect they are way too good right now; ensure that the liquid compressor always does a better job here.  Arguably the solid fuel compressor shouldn't take fuel buckets at all.

**Comment by desht** [comment]
Some more thoughts on balance of liquid fuels:

- One piece coal has a burn time of 1600 (smelt 8 items)
- A lava bucket has a burn time of 20000 (smelt 100 items)
- A (crude) oil bucket has a burn time of 75000 (smelt 375 items)
- A LPG bucket has a burn time of 900000 (smelt 4500 items!)

Feels like fuel buckets are much too good right now.  Oil is fairly common by default in lakes both on the surface and deep down, and a single bucket is nearly 50 times as a good as a lump of coal (and lakes can spawn ~100 buckets of oil...).

Current burn time as calculated as the mB->mL of air rate divided by 2 - see ``Fluids#preInit()`` and ``EventHandlerPneumaticCraft#handleFuelEvent()``.  Maybe this divisor should be a lot bigger.  And crude oil should possibly not be usable as a fuel, or at least be much poorer.

**Comment by desht** [comment]
And fuel buckets should probably be banned from the Air Compressor / Advanced Air Compressor.  That's what the Liquid Compressor / Advanced Liquid Compressor are for.

**Comment by MineMaarten** [comment]
I'm not too sure, but I think at the time the Liquid Compressore balance was based around Lava for the most part. And the hydrocarbons' fuel value based on BuildCraft's fuel. Currently I do agree some rebalancing would be appropiate, and this sounds like a good approach.

I also agree about the disabling buckets containing fuel to be burned in the solid fuel Air Compressors.

**Comment by desht** [comment]
Perhaps make the divisor configurable, with a default of 20? So 10 times weaker than currently...  450 items for LPG, which is still pretty good. And lower crude oil's time further? Maybe worth 2 pieces of coal?

**Comment by MineMaarten** [comment]
Sounds good. I would make the config use 1/N, so it's a multiplier instead of a divisor. A bit simpler to work with, and less chance of someone causing weird behaviour with dividing by 0 ;)

**Comment by desht** [comment]
Yeah definitely.

**Comment by desht** [comment]
https://github.com/TeamPneumatic/pnc-repressurized/commit/416faae749e407e42080396a8adec462603d2b52
