### ISSUE TITLE
[Feature] Tanks emit redstone level

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#510]
Would it be possibly for tanks to emit a redstone level depending on how full they are?

We could turn off the regulator controlling a themopneumatic processing plant when the tank is full.

![small-tank-with-comparitor2](https://user-images.githubusercontent.com/4198031/83250318-3ab8f900-a1a8-11ea-9d66-06e3f157513c.png)

Thanks for you consideration.

**Comment by desht** [comment]
Yeah, good idea & easy enough to add.

**Comment by desht** [comment]
Added in 1.0.6 & 1.2.2
