### ISSUE TITLE
Programmable controller, drone not picking up items

### ISSUE THREAD

**Issue by VeryFriendlyOne** [TeamPneumatic/pnc-repressurized#512]
Okay, i'm not really sure if it's a bug or i don't know that this is a feature. So, i don't see "pick up items" in excluded puzzle pieces of programmable controller, so i assumed, that it could pick up items, and that's what inventory upgrade for, but i can't get it to work, it doesn't pick up items. If i'm wrong, and it is intended not to pick up items just close the issue, please

**Comment by desht** [comment]
Confirmed.  Works with regular drones, not with the programmable controller.

**Comment by VeryFriendlyOne** [comment]
It is also not taking items from inventory like a chest.

**Comment by desht** [comment]
Almost certainly the same issue, but I'll verify before the release.

**Comment by desht** [comment]
Actually if you feel like it, you can test build 28 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ which has the above fix.

Or you can wait for the 1.2.2 release which will be in the next couple of days probably.

**Comment by VeryFriendlyOne** [comment]
Thank you a lot! I'll give it a try!

**Comment by VeryFriendlyOne** [comment]
So, i tested it, and it's really cool! Thanks! But i found a couple of othe bugs.
1) Programmable controller, inventory upgrade doesn't do anything. I wasn't able to give more than 1 tool or more than 1 stack of items. It's not really a problem, given how easy it is to provide programmable controller with items, but then it's just a waste of inventory upgrades.
2) Crop support is consumed in creative. Not that big of a deal, but still noticeable. Also, you can stack multiple crop supports on the same block. Not sure if it will make the plant grow quicker

**Comment by desht** [comment]
Yep, confirmed and fixed both of those, thanks.

**Comment by desht** [comment]
Fixed in 1.2.2 release
