### ISSUE TITLE
Crashloop since teleport

### ISSUE THREAD

**Issue by spthiel** [TeamPneumatic/pnc-repressurized#514]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2847
### Mod Version
1.12.2-0.11.14-395
### Describe your problem, including steps to reproduce it
A friend had a pneumaticcraft setup on their base and I teleported there via FTB Utils after which I crashed. Since then I cannot log into the server again.
This only happens to me (tested with another person) and I first had optifine installed but it doesn't appear to be causing the issue. I unfortunately can't give any more in depth steps to reproduce
### Any other comments?
[crash-2020-06-05_20.54.01-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/4737992/crash-2020-06-05_20.54.01-client.txt)
Pipe that is mentioned in the crash: ![Unbenannt](https://user-images.githubusercontent.com/17518682/83914682-0037f900-a772-11ea-8bd5-21463d19fbca.png)

**Comment by desht** [comment]
Looking at the stacktrace, the tile entity has been ticked before the client-side block has been properly loaded (hence the `as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}` part of the error).

What concerns me is this line:
```at com.zeitheron.hammercore.asm.McHooks.tickTile(McHooks.java:38)
```

That's a coremod which is changing the behaviour of the vanilla `World#updateEntities()` method in some way, and without knowing exactly what it does, I won't even start to investigate this problem.  If you can reproduce this crash without the coremod installed, then I can take a look.

In the meantime, I would suggest getting your server admin to edit your player dat file (in `world/playerdata/{UUID}.dat` to move you to a different location.

Sorry I can't help more at this point.

**Comment by spthiel** [comment]
For future reference in case anybody else experiences this: It's an issue with voxelmap
