### ISSUE TITLE
The Electrostatic Compressor's tooltip is massive and unreadable

### ISSUE THREAD

**Issue by aaronhowser1** [TeamPneumatic/pnc-repressurized#516]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Mod Version
1.12.2-0.11.14-395
### Describe your problem, including steps to reproduce it
![image](https://user-images.githubusercontent.com/15698722/84006954-3bcef080-a935-11ea-87fd-1ff037fcaaf1.png)

**Comment by desht** [comment]
I agree, it's a bit excessive and ideally would be split into a shortened form for the item tooltip.  

However, this is a cosmetic problem and the 1.12.2 version is only getting critical fixes at this point, so I'm sorry but this doesn't merit a fix & new release at this point.  If a new release for 1.12.2 ever happens, I'll keep this issue around and roll it into that.

**Comment by desht** [comment]
Fixed in 0.11.15 release
