### ISSUE TITLE
Can't discharge items in Charging Station

### ISSUE THREAD

**Issue by aaronhowser1** [TeamPneumatic/pnc-repressurized#517]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12
### Forge Version
14.23.5.2847
### Mod Version
1.12.2-0.11.14-395
### Describe your problem, including steps to reproduce it
![image](https://user-images.githubusercontent.com/15698722/84029789-962d7880-a958-11ea-91c1-e66e485cef45.png)
![image](https://user-images.githubusercontent.com/15698722/84029793-99c0ff80-a958-11ea-864f-3b36d83d4259.png)
The pressure in the Charging Station is 0 bar and the pressure in the Canister is 20 bar, but the Charging Station says that they're equalized and won't discharge. Am I doing it wrong?

**Comment by desht** [comment]
No that should work. I tested and I can see the problem too, although it doesn't always fail...

**Comment by desht** [comment]
Build 396 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/ should fix this.  Was a bug that caused the charging station not to allow any air transfer if its pressure was at 0.

You can use the dev build until the 0.11.5 release, or work around the issue by putting a tiny bit of air into the charging station.

**Comment by aaronhowser1** [comment]
Thank you very much 👍

**Comment by desht** [comment]
Fixed in 0.11.15 release
