### ISSUE TITLE
[1.15] [Question] Multiple inputs/outputs for assembler recipes

### ISSUE THREAD

**Issue by slava110** [TeamPneumatic/pnc-repressurized#521]
Hi. I see 4 slots for assembly recipe in JEI but I don't see any info about how to define multiple ingredients/results for assembly. Is it even possible?

**Comment by desht** [comment]
It's actually not possible at this point. I think that might have been something MineMaarten planned at some point, but it was never implemented.

I might take a look at this again, but it will likely need to wait until 1.16.

**Comment by desht** [comment]
This is actually also covered by #682 so closing this.  Haven't totally forgotten about it, but it hasn't yet been implemented...
