### ISSUE TITLE
Crash pressing I in drone programmer

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#523]
### Minecraft Version
1.14.4

### Forge Version
28.2.4

### Mod Version
pneumaticcraft-repressurized-1.14.4-1.0.7-19

### Describe your problem, including steps to reproduce it

Straightforward to reproduce, press I in on the item.
![programmer-press-i](https://user-images.githubusercontent.com/4198031/84801736-d5fefa80-afff-11ea-8102-feccae6a4970.png)

### Any other comments?
I cannot right click a small tank with a bucket in the drones 'hand', not sure if this should work, I guess not. The intention is to automate plastic sheets with a drone.

**Comment by desht** [comment]
Can I get a stracktrace for that crash please?

Right clicking with a bucket should work in theory; I can do some debugging on that one.

**Comment by desht** [comment]
Actually, I know what's happening here; it's an incompatibility between Patchouli versions (you're using a newer version than I'm building against).  Easily fixed, fortunately.  I'll need to require that you're using Patchouli 1.1-26 or newer, which I'm pretty sure you already are.

**Comment by desht** [comment]
Build 20 from jenkins should fix your problem...

**Comment by duncanwebb** [comment]
Thank you, it now works and the manual page is opened.

**Comment by desht** [comment]
Fixed in 1.0.8 release
