### ISSUE TITLE
[1.15.2] Blocks placed down take on appearance of other blocks.

### ISSUE THREAD

**Issue by TRzerg** [TeamPneumatic/pnc-repressurized#524]
### Minecraft Version
1.15.2

### Forge Version
31.2.0

### Mod Version
1.3.0-33

### Describe your problem, including steps to reproduce it
This seems to only be happening on multiplayer, and all is needed is to place a block down. Specifically any of the blocks needed to form the pressure chamber. 

The multiblock forms and appears to be working as intended but looks completely wrong.
![2020-06-16_14 02 51](https://user-images.githubusercontent.com/67021848/84817882-47788200-afdb-11ea-84e8-35d1a72cb927.png)
![2020-06-16_14 03 02](https://user-images.githubusercontent.com/67021848/84817895-4a737280-afdb-11ea-9276-c3942f740bd1.png)
![2020-06-16_14 03 19](https://user-images.githubusercontent.com/67021848/84817914-5101ea00-afdb-11ea-9f7e-25ac1fcb824b.png)
![2020-06-16_13 52 36](https://user-images.githubusercontent.com/67021848/84818301-e8ffd380-afdb-11ea-9755-d8e3a1f9fb1a.png)

[latest.log](https://github.com/TeamPneumatic/pnc-repressurized/files/4788668/latest.log)

### Any other comments?
Because some of the blocks appear as blocks from Immersive Engineering I cannot easily tell if it is PneumaticCraft, Immersive Engineering, or another mod entirely causing this issue. However no other mods seem to be affected.

**Comment by desht** [comment]
Needless to say, I cannot reproduce this.  I think the only way to get to the bottom of this will be to start removing other mods and see what makes a difference.  What mods do you have loaded?

Update: never mind, I see you attached a log.  Please try this without Optifine and let me know.

**Comment by TRzerg** [comment]
I have tried it without optifine and it produces the same results.

It could just be the server itself, but its not mine nor do I have access to its files. I can't really check if there are any errors on it. I can try and get into contact with the owner of the server and see if there are any issues there.

**Comment by desht** [comment]
What about if you create a local single player world with the same instance?

**Comment by TRzerg** [comment]
Well I have spoken with the server owner, and weirdly he was not having any issues. He gave me a copy of his files and after swapping to that, everything seems to now be working. Still unsure as to what was really causing the issue, as I didn't have anything thing different from him. In any case it is all working now, and I will close this out.

Thanks for the help.
