### ISSUE TITLE
[1.15] Swimming in oil causes visual glitches

### ISSUE THREAD

**Issue by merlerm** [TeamPneumatic/pnc-repressurized#525]
### Minecraft Version 
1.15

### Forge Version 
31.2.20

### Mod Version 
1.3.0-33

Pretty self explainatory, I'm adding a screenshot. Running this on Enigmatica 5 0.5.0

https://imgur.com/a/4wczKMe

**Comment by desht** [comment]
It's a fundamental Forge fluid issue, nothing I can do about it in the mod, sorry.  Fluids are only partially implemented so far, in 1.14 and later.
