### ISSUE TITLE
[1.15.2] Univsersal sensor is buggy

### ISSUE THREAD

**Issue by ocram9** [TeamPneumatic/pnc-repressurized#527]
### Minecraft Version
1.15.2

### Forge Version
31.2.20

### Mod Version
1.3.0-33

### Describe your problem
The universal sensor seems to have a few issues (unless I'm using it wrong). The upgrades tab doesn't include all the upgrades (the range upgrade isn't shown in the list for example).

The GPS doesn't seem to be working when inserted into the sensor. The GPS area tool is being ignored and the normal GPS can only select one block (according to the description I should be able to place 2 of the GPS tools to create an area but I can't place more then one in the sensor). 

And as a side note, the GPS icon in the sensor (as in, the place you need to put the GPS) isn't the right icon.

**Comment by desht** [comment]
Yep, I can't argue with any of that.  In fact I was just thinking yesterday that the sensor needs some work.

**Comment by desht** [comment]
Actually, the GPS Area Tool seems to be working fine.  I did a test with an area of 8 blocks and the Block Presence sensor; if all blocks are air, the signal is off, and if any block is not air, the signal is on, which is what I'd expect.

What were you trying that didn't work as expected there?

Update: make sure you have sufficient Range Upgrades installed to cover the area (the GUI "problems" side tab will warn you if you don't).

**Comment by ocram9** [comment]
Hmm, I will test it some more later today but I was detecting a player within range (with my name in the entity filter). As far as I could tell it didn't use the area tool but the range from the sensor. It did go through a door (made with the multi-piston from the structurize mod) so I don't know if that is causing issues.

**Comment by desht** [comment]
Right, the entity-in-range sensor doesn't use GPS - only block sensors use GPS tools.  Entity sensors work purely off the number of range upgrades installed.

The GUI docs in the next release will make this a lot clearer (I'm doing a big cleanup commit right now, as it happens).

**Comment by ocram9** [comment]
Well that explains it :p  Fair enough, I just need to remove some range upgrades then, thank you!

**Comment by ocram9** [comment]
Also, I'm not sure if you have changed it already but when you select a sensor type (like the player or block) the show range dissapears. It might be useful to be able to show the range even though you have already selected a sensor type.

**Comment by desht** [comment]
Also fixed in the commit I pushed today :)

**Comment by desht** [comment]
Fixed in 1.3.1 release
