### ISSUE TITLE
No longer able to set the Coordinate Puzzles

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#528]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.20
### Mod Version
1.3.0-34
### Describe your problem, including steps to reproduce it

I can't seem to set Constants or Variables in the Coordinate puzzle anymore. I can still use a GPS tool to set them, but anything I manually set is lost upon leaving and re-entering the programmer. 

### Any other comments?

This is happening in my test world as well as my E5 world which is running 1.2.2-30. Not really sure when it started happening since I know I've set both constants and variables in these fairly recently without issue.

**Comment by desht** [comment]
Confirmed, and fortunately a very easy fix.

**Comment by desht** [comment]
Fixed in 1.3.1 release
