### ISSUE TITLE
Request: Round Robin export for Omni-hopper

### ISSUE THREAD

**Issue by Tekstack** [TeamPneumatic/pnc-repressurized#529]
I believe a round robin export toggle/upgrade to the Omni-hopper could be useful. This can be achieved using other mod's item conduits, but would like to see within Pneumaticcraft if possible. One use case that I've run into is in packs that give diminishing returns on food that you have ate recently. The areal interface with the food upgrade is one of the first mid/late-game blocks I personally set up for the auto feeding and armor charging. If the hopper could be set up in round-robin mode, you could have it feed you enough different foods as to not run into this issue. Like I stated, most of the time, their are many work arounds available, so this is not an urgent request by any means. Thanks for the hard work.

**Comment by desht** [comment]
Fixed a while ago (can't remember which release offhand!)
