### ISSUE TITLE
[1.15.2] Air Grate Tube Module can push player in spectator mode

### ISSUE THREAD

**Issue by ocram9** [TeamPneumatic/pnc-repressurized#530]
### Minecraft Version
1.15.2

### Forge Version
3.2.20

### Mod Version
1.3.0-33

### Describe your problem, including steps to reproduce it
I'm not sure if this is intended but Air Grate Tube Modules can push a player who is using spectator mode. 

Steps to reproduce:
 - Place an Air Grate Tube Module on a pressure tube.
 - Switch to spectator mode and fly near it

**Comment by desht** [comment]
Yeah, that's probably not desirable...

**Comment by desht** [comment]
Fixed in 1.3.1 release
