### ISSUE TITLE
Has the Aerial Interface changed?

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#531]
### Minecraft Version
1.14.4

### Forge Version
28.2.4

### Mod Version
pneumaticcraft-repressurized-1.14.4-1.0.8-21

### Describe your problem, including steps to reproduce it
The Aerial Interface is not pushing air into the armour.

![aerial-interface](https://user-images.githubusercontent.com/4198031/85175883-c4745780-b278-11ea-9615-aba79129d36e.png)

The aerial interface has been rotated, just in case this was positional.

**Comment by desht** [comment]
Hard to tell from the image, but it should work. How have you got the sides set up in the gui?

**Comment by duncanwebb** [comment]
Ah that's it, sorry my mistake. I knew it was something like this as I rotated the interface all the way round. I checked manual too but the page is blank.

Many thanks.
