### ISSUE TITLE
Should Drones be able to read redstone from a Universal Sensor

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#532]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.20
### Mod Version
1.3.0-34
### Describe your problem, including steps to reproduce it

I'm not sure if this is a problem per se, or intended behavior. I've got a universal sensor set up in Comparator mode and I just wanted to read the redstone signal from it using a drone program. Effectively shutting off the drone when a mana pool is full. So far though, it doesn't seem to read directly from the sensor. I have to put a bit of dust next to it instead and point the drone program at that.

**Comment by desht** [comment]
The condition widget use the `world.getRedstoneFromNeighbours(pos)` call to determine the signal level of the block it's monitoring, so it is sort-of-intended, though I agree it's not the most intuitive.

Having said that, it works for things like levers, so it should probably also work for a redstone emitter like the sensor.  I'll take a look at that.

**Comment by desht** [comment]
Fixed in 1.3.1 release
