### ISSUE TITLE
[1.15.2] Turret firing animation doesn't match the position

### ISSUE THREAD

**Issue by ocram9** [TeamPneumatic/pnc-repressurized#533]
### Minecraft Version
1.15.2

### Forge Version
31.2.20

### Mod Version
1.3.0-33

### Description
When the sentry turret is firing at it's target the animation is sometimes below the barrel:

![2020-06-20_03 23 49](https://user-images.githubusercontent.com/49008532/85188309-ecc67b00-b2a5-11ea-9c3e-61708a6637e6.png)

![2020-06-20_03 24 03](https://user-images.githubusercontent.com/49008532/85188285-ce607f80-b2a5-11ea-903c-a2a5d1ded5fe.png)

The turret also always faces south when placed down, it would be nice if we could choose which way it's facing when placing it down (like the way the player is facing for example) for aesthetic purposes.

**Comment by desht** [comment]
Odd, I'm not seeing the tracer offset at all (tested both in single-player & dedicated server):

![2020-06-20_09 22 52](https://user-images.githubusercontent.com/736831/85197258-cae5ec00-b2d7-11ea-81e8-5d303348e3ee.png)

It's always positioned properly for me, regardless of the gun's pitch & yaw.  Tried it on a slab too, as you have, but it still worked OK.

Changing the turret's default facing would be nice, I agree.  Although bear in mind that its idle direction is always based on the last mob it targeted, so it won't point in the placed direction for very long (though I suppose I could change it so it reverts to its initial idle direction...)

**Comment by ocram9** [comment]
That is really weird, I just tested it on a different server with only pneumaticcraft installed and it happened again:

![2020-06-20_19 27 54](https://user-images.githubusercontent.com/49008532/85207890-4b363c80-b32c-11ea-9170-3b77bed1c168.png)

Maybe a stupid question, but did you try another mob besides the spider? I think it only happens with taller mobs like zombies and skeletons.

**Comment by desht** [comment]
Not a stupid question - I haven't yet but I'll check that out too. 

Update: yep, you're right.  Tested with a Husk and the tracers are indeed a little too low.

**Comment by desht** [comment]
Fixed in 1.3.1 release
