### ISSUE TITLE
Programmer sometime behaves oddly

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#534]
### Minecraft Version
1.14.4

### Forge Version
28.2.4

### Mod Version
pneumaticcraft-repressurized-1.14.4-1.0.8-21

### Describe your problem, including steps to reproduce it

I'm not sure if you can reproduce these, but they are odd.

The buckets were in slot 1
![allthemods-0390 avi-trimmed](https://user-images.githubusercontent.com/4198031/85198589-05588480-b2ea-11ea-885b-c45625f9f67d.gif)

Cannot attach the item filter to the RHS of the puzzle piece.
![allthemods-0391 avi-trimmed](https://user-images.githubusercontent.com/4198031/85198599-2620da00-b2ea-11ea-9acf-d2378581c2bc.gif)
The left-hand side worked and it worked later with a new conditional widget.

### Any other comments?
Both clips were taken from Episode 43.

**Comment by desht** [comment]
I have noticed the slot problem once or twice but it happens so rarely, I've not ever been able to debug it.

Never seen the problem with pieces not attaching before...

**Comment by duncanwebb** [comment]
I don't expect that they are fixed. Both are strange and intermittent. I noticed the slot problem most frequently with Blood Magic, where the chestplate was swapped out.

**Comment by duncanwebb** [comment]
Here is another intermittent one for you, I've seen this happen before, last time it worked the time before it was grey.

![gps-area-tool](https://user-images.githubusercontent.com/4198031/85317652-055dad80-b4bf-11ea-9844-15f2c3c77131.png)

I've also seen the drone window as a grey box.

![drone-entity-tracking](https://user-images.githubusercontent.com/4198031/85318660-abf67e00-b4c0-11ea-9988-dc6376f431e0.gif)

**Comment by desht** [comment]
Only took 6 months, but I figured this one out :)  Fixed in build 119, will be in 2.9.3 release.
