### ISSUE TITLE
1.15.2 Bug Crop Supporter

### ISSUE THREAD

**Issue by MKnance1990** [TeamPneumatic/pnc-repressurized#535]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.9
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.2.2-30
### Describe your problem, including steps to reproduce it
I placed crop supports on all my crops on the farmland and i logged out because its was time for bed then i came back onto my friends server and bada bing bada boom my room was dark and when i harvested only one crop supporter stayed on the farmland i don't know how to reproduce this other than plant crop supporters and log out and stay logged out over time i was unable to reproduce it but ever since i stopped using crop supporter the issue has no appeared since

**Comment by desht** [comment]
There really isn't enough information to go on here.  I've not seen this behaviour at all and it sounds like a lot of coincidence to me.  Crop supports are just entities and they don't affect lighting in any way whatsoever.

If you can come up with a way to reproduce this, feel free to reopen, but there's nothing for me to go on here.
