### ISSUE TITLE
Fluid Tank duplication bug while crafting upgrades

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#536]
### Minecraft Version
1.15.2
### Forge Version
31.2.20
### Mod Version
PneumaticCraft 1.3.0-34

### Describe your problem, including steps to reproduce it

Using filled tanks to craft upgraded tanks results in dupes.

Fill two small tanks with water
Place them in a crafting table with the gold/plastic/tubes required to make a medium tank
Taking the Medium tank out results in each of the small tanks having 1 bucket of water subtracted, but the whole tank remains in the crafting table.

**Comment by desht** [comment]
Fixed in 1.3.1 release

(You must now use a completely empty tank for crafting; item must have no NBT at all, so newly-crafted tank is recommended)
