### ISSUE TITLE
Fluid Tanks duplicating fluids when filled with a stack of tanks

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#537]
### Minecraft Version
1.15.2
### Forge Version
31.2.20
### Mod Version
PneumaticCraft 1.3.0-34

### Describe your problem, including steps to reproduce it

Right clicking on a fluid tank with a stack of tanks will double the fluid input into the tank in world. 

Hold a stack of small tanks full of water
Place a large tank in world
Right Click the large tank with the stack of tanks. 
One tank is removed from the stack and correctly placed into your inventory empty. 32 buckets are correctly placed in the large tank.  Then a moment later an additional 32 buckets are added to the large tank

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
I do believe this is a bug in Forge, specifically at https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L183

Fluid is always transferred even when the method is called with `doDrain` = false, i.e. for transfer simulation. I can probably work around it, but this will probably need a PR to Forge to fix properly.

**Comment by desht** [comment]
https://github.com/TeamPneumatic/pnc-repressurized/commit/74cafe085008088504b381133a055d8f007289d5

**Comment by desht** [comment]
Fixed in 1.3.1 release
