### ISSUE TITLE
[1.15.2] Sentry turret tracers render in front of everything

### ISSUE THREAD

**Issue by ocram9** [TeamPneumatic/pnc-repressurized#538]
### Minecraft Version
1.15.2

### Forge Version
31.2.21

### Mod Version
1.3.1-39

### Describe your problem, including steps to reproduce it
When the turret is firing at a target, the tracers render in front of any blocks in between the player and the sentry turret.

![2020-06-22_16 25 14](https://user-images.githubusercontent.com/49008532/85299311-67a9b480-b4a5-11ea-99b0-df3b41e75ace.png)
![2020-06-22_16 25 17](https://user-images.githubusercontent.com/49008532/85299330-6c6e6880-b4a5-11ea-8a2b-0be3f9314dd1.png)

**Comment by desht** [comment]
Yeah, I know what I did there :(  Will be fixed in the next release.

**Comment by desht** [comment]
Fixed in 1.3.2 release
