### ISSUE TITLE
Drones are not properly using up blocks on placement if they're not in the 'primary' slot

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#539]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.20
### Mod Version
1.3.0-33
### Describe your problem, including steps to reproduce it

Sorry, I would have reported this with the other dupes but I just had a flash tonight that made me realize how to reliably reproduce the bug. I'd seen it happen a few times but wasn't sure of what I'd done to cause it. 

Put a single non place-able item (an ingot, for instance) in a chest along with a single block. Instruct the drone to pick up then ingot so that it is the 'held' item. Now instruct the drone to pick up the block. Finally if you tell it to place it in an area and filter to place the block, it will place them infinitely. 

### Any other comments?

Example Drone code. 
https://gist.github.com/MuteTiefling/db8ec5dcc341789cc14d565c632ac554

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Give build 40 a go...

**Comment by MuteTiefling** [comment]
Lookin good. Thanks!

**Comment by desht** [comment]
Fixed in 1.3.2 release
