### ISSUE TITLE
[1.15.2] Render crash with Omnidirectional hopper on a moving create contraption

### ISSUE THREAD

**Issue by WhitePhant0m** [TeamPneumatic/pnc-repressurized#540]
### Minecraft Version
1.15.2
### Forge Version
31.2.20
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.3.1-39
create-mc1.15.2_v0.2.4d
### Describe your problem, including steps to reproduce it
I get a render crash when I have an omnidirectional hopper on a moving Create contraption, didn't cause a render crash with pneumaticcraft-repressurized-1.15.2-1.3.0-33
### Any other comments?
I have more information posted in the issue bellow
https://github.com/Creators-of-Create/Create/issues/383
[Crash log](https://pastebin.com/p9yXwyQP)

**Comment by desht** [comment]
If its what I think it is, then I've already fixed that in dev. Will be a new release out soon.

**Comment by desht** [comment]
This will be fixed in the 1.3.2 release.  In the meantime, you can try build 41 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ which also has the fix.

**Comment by WhitePhant0m** [comment]
Seems that build indeed fixed it, nice!

**Comment by desht** [comment]
Fixed in 1.3.2 release
