### ISSUE TITLE
Lag from capabilities?

### ISSUE THREAD

**Issue by Darkere** [TeamPneumatic/pnc-repressurized#542]
### Minecraft Version
1.15.2
### Forge Version
31.2.19
### Mod Version
pneumaticcraft-repressurized-1.15.2-1.3.0-33
### Describe your problem, including steps to reproduce it
20% tick time from HackTickHandler
https://spark.lucko.me/#PgiHJ8gezH

Aware I'm not on the latest version. But I haven't seen anything in the changelogs regarding this.

**Comment by desht** [comment]
Yep, that's excessive.  And looking at the code, I can see why - the event handler's iterating over all entities on the server, every tick.

Fortunately, it should be a very easy fix: store a local list of those entities which have actually been hacked (by the Pneumatic Helmet hacking feature), which should in most circumstances be a very small list, or empty.

**Comment by desht** [comment]
Not sure if you're in a position to test, but build 43+ from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ should behave a lot better.

**Comment by Darkere** [comment]
I've since figured out that we have 44k non-ticking items on the server. That is probably why the issue is that extensive. Still trying to figure out how to get rid of them.

**Comment by desht** [comment]
Yeah that be a problem in its own right. Still, PNC was being pretty inefficient about it...

**Comment by desht** [comment]
Fixed in 1.4.0 release
