### ISSUE TITLE
Programming puzzle pieces not showing up.

### ISSUE THREAD

**Issue by NotBigSurprise1** [TeamPneumatic/pnc-repressurized#543]
![Minecraft-1144-2020-06-28-00-15](https://user-images.githubusercontent.com/67534149/85939788-793ff180-b8d5-11ea-8bf1-115010953c7d.gif)

*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.14.4
### Forge Version
28.2.1
### Mod Version
1.0.2-11
### Describe your problem, including steps to reproduce it
Whenever I try to put a programming puzzle piece in the programmer, it disappears, but remains there. I cannot see it, but when I hover over it, it shows the information.

**Comment by desht** [comment]
That version is really out of date. Upgrade to the latest 1.14 release.
