### ISSUE TITLE
Holding shift or control prevents hotbar switching and opening inventory

### ISSUE THREAD

**Issue by Revvilo** [TeamPneumatic/pnc-repressurized#545]
**Minecraft Version**
1.15.2

**Forge Version**
31.2.30

**Mod Version**
1.15.2-1.3.2-42

### The issue
Holding control or shift and pressing the number keys to switch your active hotbar slot, or E to open your inventory, will work correctly only once for that respective keybind AND modifier key, but never again while either of those modifier keys are held. Inputs return to being functional if the modifier keys are released. This is hard to explain, see the explanation at the end of the steps.
To be clear the behavior is the exact same for inventory opening, where it will work once but never again while either modifier is held.

1. Hold Control
2. Press 1 then 2 to cycle between hotbar slots
3. - Works
4. Press 1 then 2 again
5. - Doesn't work
6. Release Control
7. Press 1 then 2 again
8. - Works
9. - Subsequent attempts with Control held will bring you back to 4, skipping 1 to 3.
10. Repeat for Shift if you like
_Shift and Control seem to act independently. Each storing their own memory of whether they have expended their one successful input._

https://github.com/AllTheMods/ATM-5/issues/167

**Comment by desht** [comment]
Can you give build 50 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ a go please?  Should fix your problem.

**Comment by Revvilo** [comment]
Hell yeah, you're onto it! That fixed it :D

**Comment by desht** [comment]
Fixed in 1.4.0 release
