### ISSUE TITLE
Strange Heat Behaviour

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#546]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.30
### Mod Version
1.15.2-1.3.2-49
### Describe your problem, including steps to reproduce it

I have no idea how to reproduce this. It's probably just some weird funkiness caused by the low FPS I've been getting lately (been struggling to find the cause, but don't think it's related to this).

So basically I noticed that my wireless pressure had run out. That seemed odd because I recently built two flux compressors that are passively cooled enough to run with 9 speed upgrades each and remain efficient. I'm not using anywhere near that much air and there are no leaks that I can see.

This lead me to look at the compressors themselves and the wireless link. When I got there, the compressors were fine and the canister in the ender chest started filling again. This is where I realized I was a derp and wasn't chunk loading the area any more.

Chunk loading fixed, I decided to improve the flow rate into the ender chest by adding three more charging modules to it. This is where things get weird.... while placing the pipes I accidentally caused a brief air leak that I was trying to avoid. This caused the whole system to kick on and a massive lag spike. When the lag cleared, I started taking damage from fire... my heat sinks had instantly hit the red zone on one compressor and solid blue on the other. A moment later the damage stopped. Both the compressors and all of the heat sinks were now showing -273C

I relogged to try to fix it, but all that did was to reset the colors on the red heat sinks to the proper blue.

![2020-07-09_09 07 05](https://user-images.githubusercontent.com/9543430/87045513-fb79c100-c1c5-11ea-9f1a-643dda6a15a1.png)

Now, I think it's worth noting that the two compressors are being powered by Mekanism Quantum Entangloporters and both of those had their heat controls set to Input on all sides. I don't know if this is at all related, but since this version is the one where you added mek compatibility back in, I thought it was worth mentioning. I have since disabled the heat portion of those entantloporters and it hasn't had any impact. 

### Any other comments?

Including the log, but I'm not seeing much in there. This happened prior to the log out at 8:58. Relogging didn't do anything but to fix the colors on the heat sinks. Restarting the game similarly did not fix anything. 
[latest.log](https://github.com/TeamPneumatic/pnc-repressurized/files/4897003/latest.log)

**Comment by desht** [comment]
I have a feeling this is indeed related to the Entangloporters.  Are they directly adjacent to the compressors, or connected via power cables? Difficult to tell from the image...

**Comment by MuteTiefling** [comment]
They are in direct contact with the bottom face of the compressors in that picture, but not touching any other heat capable block. Sorry, hard to get a good angle on them since everything is packed in there tight.

I didn't feel like tearing everything out and rebuilding to fix it, so I just restored a backup. I've now moved the entangloporters away and connected them by power cables instead so they're no longer in direct contact with any  heat capable blocks.

Prior to restoring the backup, however, I did rip out all of the heat sinks/heat pipes and even the compressors remained at -273 C all by themselves. It was rather comical that I could run them at 10 speed upgrades with no consequences. Breaking and replacing the compressor finally fixed it. 

So far in the restored world, it's been stable.

**Comment by desht** [comment]
I know what's going on here, and the solution is probably going to have to be a bit of hack, down to the different ways Mekanism & PNC handle heat internally.  A simple "adapter" doesn't quite work, and leads to exactly the problem you saw there, where Mek blocks can cause PNC blocks to wildly fluctuate in temperature.  Neither mod's heat system is wrong, as such - they just don't quite play well together.

I'd already worked around this for Mek Thermodynamic Conductors (TC - the Mek equivalent of the Heat Pipe), but didn't consider the Quantum Entangloporter (QE).  Problem being, the workaround will need to look a little different for the QE, since TC's actively push heat around, while the QE does not - it just provides a heat capability which is intended (in Mekanism) to be moved around with TC's.

A lot of this is necessarily going to be a bit of a hack, but right now I don't see any truly elegant ways of avoiding that. Still, I think I can come up with something that's Good Enough (tm).

**Comment by MuteTiefling** [comment]
I wish you luck, good sir. 

Would it be easier to maybe simply ignore QEs entirely, however? Considering that someone could simply use the Mek Thermal conductors if they wanted to pass through a QE.

**Comment by desht** [comment]
Yep, I think for now that's the simplest option!

**Comment by desht** [comment]
Build 51 should fix that problem.

**Comment by desht** [comment]
Fixed in 1.4.0 release
