### ISSUE TITLE
Request: Activate Block with Drones

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#548]
I think this is probably more of a suggestion than a bug report as I suspect the current functionality is intended.

I'm currently attempting to automate Create's Mechanical Crafter with Drones. If you're not familiar with it, you've basically got an extended crafting table built out with one 'slot' per block. 

![2020-07-11_22 39 02](https://user-images.githubusercontent.com/9543430/87237676-59292b80-c3c7-11ea-95fa-3f7b53113f09.png)

Inserting the items in each slot is done via right click. Inserting via pipes/hoppers does not work. I figured this should be a breeze to automate with drones, but I've since determined that they appear to be missing the functionality needed to interact with these blocks. The "Right Click Block" puzzle piece just doesn't work.

I tested using Modular Routers to see if that would do it, and it does. The Activator module successfully inserts the item into the crafter, but only if it is in "Activate Block" mode. The "Right Click Item in Buffer" option can't insert the item. So I'm assuming that this is effectively the issue for the Drone in this case, it's trying to right click the item onto the block, rather than activate the block. 

Would it be possible to add an option in the Right Click Block puzzle to 'activate the block'?

**Comment by Tekstack** [comment]
Have you tried designating the block face that you are right clicking with the drone to something other than the default? You can change that on the puzzle piece.

**Comment by MuteTiefling** [comment]
@Tekstack I have, yeah. Originally it was on Up and the drone wouldn't even try to click it. Then I set it to South (the face visible in that image) and it did go over and click it, but the item was never inserted. Tried every other face as well, but at that point I had no expectation for it to work since I was actively giving it bad sides.

**Comment by Tekstack** [comment]
I know that you've probably already tried this as well, but did you try swapping out the right click piece for insert to inventory with the South side selected?

**Comment by MuteTiefling** [comment]
I have, just out of curiosity, but that didn't work either. The crafters aren't meant to be piped into, however. I think normally in a pure Create automation of this, you'd have Brass Hands inserting into them (which replicate right click). Even a vanilla hopper can't insert into them.

**Comment by desht** [comment]
That's a reasonable request; drones probably should be able to do this.  Will need an option in the progwidget GUI to select between "click item" and "click block" but that shouldn't be a problem.

**Comment by desht** [comment]
This should work in build 51 - go into the progwidget GUI and change "Operation" to "Click Block" (default is "Click Item").

I haven't tested it on the Create crafter (don't have Create in my dev workspace), but it does work to right-click items onto a PneumaticCraft Display Table (where it didn't before).  Let me know how you get on...

**Comment by MuteTiefling** [comment]
Works beautifully, thank you :D 

https://streamable.com/7pp6x8

I can even properly set/remove the slot covers used to fill empty crafters. 

You rock!

**Comment by desht** [comment]
Added in 1.4.0 release
