### ISSUE TITLE
Feedback: Plastic Cooling

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#549]
First off, I really love the new plastic mechanics. Not much to complain about here. 

I have gotten to thinking lately, however, that there would appear to be little point in setting up the Heat Frame method compared to the in world cooling method. 

In world cooling is effectively instant and requires no expenditure of power in any way (other than possibly moving the fluid to a hopper). A liquid hopper outputting plastic on top of an omni hopper with maybe a few blocks around the whole thing to keep items from popping away is exceptionally quick, even without speed upgrades.

Compare that to the Heat Frame method that requires passing buckets back and forth to a tank to fill them (which is more complicated than it sounds at first since you must precisely control the number of buckets in the tank), then moving them to a chest that's being actively cooled, then shifting the resulting bucket and plastic sheet out. Add onto that the cost of cooling (sure, you can double up on the refinery's vortex tube to get the cooling, but still, it's a cost)

It was a challenging build to set up with PNC alone, compounded by the fact that I couldn't have a logistic frame on the chest with a heat frame. That's fine, however, nothing a couple smart chests or hoppers can't fix. 

What I think could help offset this increased challenge would be higher throughput. If the heat frame could actively work on more than one item at a time, for instance. Similar to what you've done with the etching tank that's effectively able to do 25 at a time if you're willing to go to the effort of setting up the production line.

**Comment by desht** [comment]
Yeah, I'm not totally happy about how this works right now either.  One thing to bear in mind is that you're not limited to buckets; any item that offers a fluid capability will also work.  This includes PNC tanks, and (I believe) Mekanism tanks, and Immersive Engineering jerrycans.  So you can drop in a Large Tank with 128000 mB of molten plastic, and it will all be processed.

Also bear in mind that you're not limited to chests; any inventory will work, e.g. a Smart Chest with one slot for only the fluid container, one slot for plastic and the rest closed off...

I did want this to take some effort, since it allows bonus plastic output, and plastic is a relatively expensive item (require 100mB of valuable LPG to create).  So there should be some cost to it, but I agree it's rather cumbersome right now to automate.

One thing I might do in 1.16 is allow this to be done with the Thermopneumatic Processing Plant, when its temperature is below zero (that will require a little extra coding to handle bonus outputs, though).  Not quite decided on that yet.

**Comment by MuteTiefling** [comment]
All this time and I didn't even realize I was getting extra output, lol. Well that actually helps a lot.

I'm not sure that changing the way it's automated is necessary though. Using logistics pipes to do it was fun and challenging, and made me really think about how to arrange things. My whole line of reasoning was that for all that effort I'm getting the same output and slower, which is false. I just ran a full large tank through and got 220 sheets for my 128 buckets. That's pretty good.  And it was much faster than bouncing buckets back and forth.  

Plus, once you get into plastic, setting up drones to make the job easier becomes possible too.

Also could have sworn I tested with a PNC tank rather than a simple bucket without success, but now I realize I never tested plastic, only water (which does not appear to work).

**Comment by desht** [comment]
Hmm, any suggestions on how I could make it clearer that the Heat Frame gives bonus output?  It's mentioned in the Patchouli book, and as a tooltip on the JEI page for making plastic via Heat Frame, but I guess it's still too easy to miss...

**Comment by desht** [comment]
Regarding water->ice, the cooling recipe right now is specifically written for water buckets (and lava buckets for obsidian), for historical reasons: fluid ingredient support in cooling recipes is something I only added in 1.14.4, and I didn't think to change over the existing two recipes.

It *should* be possible just to add recipes using water/lava as a fluid ingredients.  I'll experiment with that and maybe get it into the 1.4.0 release (which isn't far off).

**Comment by MuteTiefling** [comment]
Well, if you could have the text somehow visible in JEI without the need for mousing over, that would be helpful. At a quick glance it just looks like a bucket equals a sheet for both recipes. If the mouse over text was listed directly below the recipe all the time, that would do it. Or a shorter blurb like 'bonus plastic at colder temperatures'. 

Or maybe if it just had a 1-2 on the plastic sheet like so?

![plastic](https://user-images.githubusercontent.com/9543430/87425713-20967700-c5ac-11ea-8490-4f8d29a699d8.png)

That's enough to make it obvious there's a bonus there, even if the details of how to achieve that bonus aren't known without further investigation. It gives a clue that there's more going on there. 

I'll be honest, with the book I usually look in it for things that take a bit of explanation. So, I'll reference it a lot for programming puzzles, but not so much for anything else. Part of that's just because of familiar enough with the mod at this point that I feel I don't really _need_ to look at it, even though it would probably be helpful a lot of the time. That's on me though. Knowing you've changed so much I really _should_ have gone through and read it by now.

**Comment by desht** [comment]
I think we're ok to close this one now?

**Comment by MuteTiefling** [comment]
Yep. Think it's good.

**Comment by MarobsKoco** [comment]
Quetion: does the liquid molten plastic has a tag like air (minecraft:air) or stone (minecraft:stone)???
