### ISSUE TITLE
Heat Frame - Smelting Multiplication

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#551]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.22
### Mod Version
1.4.0-53
### Describe your problem, including steps to reproduce it
Drop a stack of raw beef in an inventory heated by a heat frame. The first one cooked is fine. Then you get a second. Then you get four, eight, sixteen, and so forth until you're getting a full stack of cooked steak for every raw one.

Sometimes these are ghost items, but more often than not, they're legitimate dupes. 

Seems that if you move the items around in the inventory, they'll turn into ghost items. Eventually this breaks the recipe entirely and the item is no longer listed as smeltable in JEI. 

However, if you simply take them out and drop them in your own inventory, they mostly just remain as duped items.

### Any other comments?

First noticed this earlier today in 1.3.2-42 in my play world. Replicated in current release in my testing pack. 

https://streamable.com/wep6ii

**Comment by desht** [comment]
Build 54 should fix this

**Comment by MuteTiefling** [comment]
Looks good. Can't replicate anymore.

**Comment by desht** [comment]
Fixed in 1.4.1 release.
