### ISSUE TITLE
Heat Frame Tank Cooling - Fluids voided

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#552]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.22
### Mod Version
1.4.0-53
### Describe your problem, including steps to reproduce it

If you have a stack of 2 or more PNC tanks filled with Water, Lava, or Plastic and put them in a cooled inventory, the fluid is simply drained out and voided without providing any of the expected ice, obsidian, or plastic sheets.

### Any other comments?

Otherwise, working great. Nice addition. Definitely feels nicer to have it processed like this for batches of material.

**Comment by desht** [comment]
Yeah, stacks of any fluid container need to be ignored here.

**Comment by desht** [comment]
Build 54 should fix this

**Comment by MuteTiefling** [comment]
Bummer that you had to take this route to fix it, but it's probably for the best.

**Comment by desht** [comment]
You mean filled fluid tanks not stacking anymore?  Yeah, it probably is for the best.  Having a stack of 64 tanks with up to 128000mB of fluid seems a bit... OP... in any case.  But tanks will still stack fine when empty.

**Comment by desht** [comment]
Fixed in 1.4.1 release.
