### ISSUE TITLE
Crashing on 1.15.2 for no reason

### ISSUE THREAD

**Issue by Fireworkstars46** [TeamPneumatic/pnc-repressurized#553]
https://cdn.fbsbx.com/v/t59.2708-21/109639457_870786466658223_9154261038114352456_n.txt/crash-2020-07-18_13.57.51-client.txt?_nc_cat=100&_nc_sid=0cab14&_nc_ohc=grIy-GjLx9cAX_3EBFd&_nc_ht=cdn.fbsbx.com&oh=837fb821bd45c375dca8fb09faf9431d&oe=5F1530CE&dl=1

**Comment by desht** [comment]
Now try without optifine and let me know if it still happens.

**Comment by desht** [comment]
Update: never mind, spotted the bug.  Will be fixed in next release.

**Comment by Fireworkstars46** [comment]
Is 1.14.4 version bug free though?

**Comment by desht** [comment]
~~No the same bug will be present on 1.14.  Since it's a crashing bug, I'll apply the fix there too.~~

Ignore that, this bug is in fact specific to 1.15.2.  1.14 should be fine.

**Comment by desht** [comment]
Fixed in 1.4.1 release.
