### ISSUE TITLE
Crash upon placing a Programmable Controller

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#557]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.22
### Mod Version
1.4.1-56
### Describe your problem, including steps to reproduce it

The game crashes upon placing a Programmable Controller. 

### Any other comments?

https://gist.github.com/MuteTiefling/09cb891b0e6ed81344a6a6312a30f14d

Tried updating forge and building a test pack with only jei and pnc and this still ended up crashing with the same ticking entity issue.

On the bright side, it's fine once you restart. But if you move the block again, you're stuck with a crash.

**Comment by desht** [comment]
Hmm, I see the problem.  The puzzle is how it ever actually worked.. there's some seriously flawed logic in there :(

**Comment by desht** [comment]
Fixed in 1.4.2 release
