### ISSUE TITLE
Crash when interacting with Logistics frames (sometimes)

### ISSUE THREAD

**Issue by KrAzYGEEK32** [TeamPneumatic/pnc-repressurized#563]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.1
### Forge Version
32.0.88
### Mod Version
2.0.0-4
### Describe your problem, including steps to reproduce it
client seems to crash sometimes when interacting with logistics frames, such as adding filters to them
### Any other comments?
latest crash: 
[crash-2020-08-06_13.18.26-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5034063/crash-2020-08-06_13.18.26-client.txt)

**Comment by desht** [comment]
... and this is why coremodding is Bad (tm)

This is *not* a problem with Pneumaticcraft - the mod dank storage is doing something funky with mixins, modifying `ItemStack#getTooltip()` in some way completely out of my control. Complain to them, please.

Update: actually, might not be Dank Storage, but something is definitely intercepting the `ItemStack#getTooltip()` call between when I call it and when it crashes (and it's not me).
