### ISSUE TITLE
Entity Tracker Name Filter not working

### ISSUE THREAD

**Issue by ben-mkiv** [TeamPneumatic/pnc-repressurized#565]
### Minecraft Version
1.16.1

### Mod Version
2.0.0.4

### Describe your problem, including steps to reproduce it
according to the entity filter description it should be possible to filter by mob names which doesn't work (tested with cow, creeper and rats from Rats mod)

Other filters like `@animal` do work as intended and highlight the mob

![](https://i.imgur.com/fV8ZlMC.png)
![](https://i.imgur.com/pEkBC6y.png)

**Comment by theboo** [comment]
asterisk filters also don't seem work, *pig* will not identify pigs or zombie pigmen and z* will not identify zombies

**Comment by desht** [comment]
Confirmed & easy fix, will be in next release.

**Comment by desht** [comment]
Fixed in 2.1.0 release
