### ISSUE TITLE
NPE upon opening the Jack Hammer Gui

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#570]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.1
### Forge Version
32.0.106
### Mod Version
1.16.1-2.0.1-7
### Describe your problem, including steps to reproduce it
Just crafted a new jack hammer and opened the gui. It crashed a moment later. Continues to crash without showing the gui upon reloading the game.
### Any other comments?

https://gist.github.com/MuteTiefling/553a86ce3a21287b9aa90f174dd2fe70

**Comment by MuteTiefling** [comment]
No issue once it has been charged a bit.

**Comment by desht** [comment]
Oops. Should be an easy fix though.

**Comment by desht** [comment]
Couldn't make it fail (shouldn't be possible since nothing on that line can be null).  Entirely possible I've fixed it since the 2.0.1-7 build, though.

Gonna close this for now, feel free to reopen if it's still happening after I push the next build...
