### ISSUE TITLE
Suggestion - sneak right click to open jack hammer gui

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#571]
Partially, this is to bring it in line with the mini gun. But also, it would allow placing torches or other off hand blocks while using the hammer.

Beyond that, this is a really nice addition. Feels great having a multi tool that'll accept enchants.

**Comment by desht** [comment]
Yeah, right now it's reversed - sneak right click can be used to place torches but switching that round might be better...

**Comment by desht** [comment]
Done in 2.1.0-11
