### ISSUE TITLE
Jack Hammer is breaking Bedrock in AoE mode

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#573]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16
### Forge Version
32.0.106
### Mod Version
1.16.1-2.0.1-7
### Describe your problem, including steps to reproduce it
I have a netherite bit in my hammer, set to 3x3 mode with a fortune book in it. If I mine into the side of a block just above bedrock, it also breaks the bedrock. I don't get bedrock as a drop, but it sure scared the pants off me when all of the sudden the void opened up below me.
### Any other comments?

https://streamable.com/2bukzi

**Comment by desht** [comment]
Oops :)

**Comment by desht** [comment]
Build 12 should fix that.

**Comment by MuteTiefling** [comment]
Awesome :D

**Comment by desht** [comment]
Fixed in 2.1.1 release
