### ISSUE TITLE
Drones can be crafted without pcb

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamPneumatic/pnc-repressurized#574]
### Minecraft Version
1.16.1

### Forge Version
1.16.1-32.0.108

### Mod Version
pneumaticcraft-repressurized-1.16.1-2.0.1-7

### Describe your problem, including steps to reproduce it
The Drone has a recipe that takes 1 Printed Circuit Board and 1 Basic Drone. However, the recipe does not require the Printed Circuit Board for some reason, meaning you can just craft an easier Drone and re-craft it into an ordinary Drone.
![billede](https://user-images.githubusercontent.com/21295394/89948600-b1ea1f00-dc26-11ea-826a-834366ecbe0b.png)

### Any other comments?
Original report: https://github.com/NillerMedDild/Enigmatica6/issues/94

**Comment by desht** [comment]
Bit of a derp there... should be fixed in build 13 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/

Will be getting a 2.1.1 release out soonish.

**Comment by desht** [comment]
Fixed in 2.1.1 release
