### ISSUE TITLE
Do the drones cause lag.

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#576]
### Minecraft Version
1.15.2

### Forge Version
31.2.36

### Mod Version
pneumaticcraft-repressurized-1.15.2-1.4.3-60

### Describe your problem, including steps to reproduce it
I'm getting lots of lag with a small world, there are only two main mods in the pack, PneumaticCraft: Repressurized and Mystical Agriculture. It often helps to create a server with the same mods and play against this server.

When creating a server with the same mods it is crashing, single player doesn't crash. The server is crashing because the tick takes more than 60 seconds.

https://pastebin.com/HWGVmBNB

### Any other comments?
I've built the base near world spawn so the chunks will be loaded. However, I don't think this is the cause. On problem with the server version is that drones don't go back to the charging station to recharge.

**Comment by desht** [comment]
This looks like pathfinding gettting itself tied up in a knot and infinitely looping somewhere and I actually fixed something sort of related in 1.16 not long ago.  I didn't backport the fix at the time but I'll do that now since it could help here.

**Comment by desht** [comment]
Give build 62 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ a go, and see if it helps any.  Other than a fix for drones not navigating to the space above "tall" blocks like fences & walls, this also reduces a max-path-length constant which was incorrectly far too large (i.e. if the drone can't find a path, it'll give up after 1000 blocks now instead of about 2 billion...).

**Comment by duncanwebb** [comment]
Same problem I'm afraid. https://pastebin.com/QdzAHs4r
.62 crashed during the startup, .60 didn't do this. Currently, I'm testing .61 on the server.
Thanks for your help.

**Comment by desht** [comment]
Oops, used a client-only method (which isn't client-only in 1.16).   Build 63 will be ready in a sec, should fix that.

**Comment by duncanwebb** [comment]
I think this change has made a significant difference, both sp and mp are much smoother.

All the drone should be able to find a charging station within 50-80 blocks, which is where I would guess that they would be going.

Many thanks.
