### ISSUE TITLE
add more options for monitoring and automating linear pressure and flow rate [suggestion]

### ISSUE THREAD

**Issue by ghost** [TeamPneumatic/pnc-repressurized#577]
currently, you can only really monitor flow rate, pressure and temperature using redstone, however that seems somewhat lacking in resolution, if i'm monitoring a normal pressure gauge with redstone, and the pressure goes above 7.5 bar, all i know is it is above 7.5 bar. it could be 7.6 bar, or 20 bar.

it would be cool to see some form of logic system that lets you monitor various temperatures, pressures and flow rates to one decimal place, using sensors that connect to any block from pneumaticraft and measure temperatures (above and below zero), pressures, and flow rates, then send that data to a single block, powered by compressed air, that you can then use to control your valves and compressors based on the information received. and also send the information to some sort of configurable display.

or just add integration with computer craft.

**Comment by desht** [comment]
Most of what you want is already in the mod:

* The Universal Sensor can monitor the heat of any block and emit a signal if the temperature goes above a configured threshold
* The Pressure Gauge can emit a signal if the pressure goes above or below a configured threshold (with an Advanced PCB installed)
* There is already ComputerCraft support for measuring the pressure and temperature of blocks
* The one thing that can't be measured as precisely is flow rates - the Flow Detector will emit a signal of `air_per_tick / 5`, so it's good for up to 75mL/t.  I'm not sure how useful it would be to extend this.

**Comment by ghost** [comment]
what blocks have computercraft support?

**Comment by desht** [comment]
All pressure and heat handling blocks do, and many other machines do too (e.g. the Elevator can be controlled & queried by computer, as can the Air Cannon). It's all documented in the Patchouli manual (see the ComputerCraft page in the Base Concepts section).
