### ISSUE TITLE
Crash when attaching an active provider frame to a IE garden cloche

### ISSUE THREAD

**Issue by yueh** [TeamPneumatic/pnc-repressurized#580]
### Minecraft Version
1.16.1

### Forge Version
32.0.108

### Mod Version
2.1.1-14

### Describe your problem, including steps to reproduce it
Attaching an active provider frame (and probably other frames) to an IE garden cloche causes it to not render immediately.
Then trying to access the frame with a logistics configurator leads to a client crash:

https://pastebin.com/hJqGMMrn

### Any other comments?
After restarting, it seems to render the frame correctly, but I did not take the chance to test, if using the logistics configurator would then work again without a crash.

**Comment by desht** [comment]
Seems like the clientside frame entity either didn't get sync'd, or spawned and then immediately despawned.  Does the frame render at all when you place it (i.e. even for a tick or so) then disappear?

I've managed to reproduce this once or twice on a dedicated server, but most of the time it works fine, and haven't been able to reproduce it yet in my dev environment.  Which is going to make this *really* hard to track down...

**Comment by desht** [comment]
Fixed in 2.2.0 and 1.4.5 release
