### ISSUE TITLE
Crash with block tracker sometimes on vanilla chests

### ISSUE THREAD

**Issue by gchpaco** [TeamPneumatic/pnc-repressurized#581]
### Minecraft Version

1.15.2

### Forge Version

31.2.36

### Mod Version

1.4.3-60

### Describe your problem, including steps to reproduce it

Client crashes with attached error sometimes when I have the block tracker set to track inventories and I return home.

### Any other comments?

This isn't super reliable; sometimes it happens when I come home, sometimes not.

[crash-2020-08-19_22.01.46-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5100438/crash-2020-08-19_22.01.46-client.txt)

**Comment by desht** [comment]
Yeah, seen this one before (the chunk isn't fully loaded when the crash happens, so the chest block is still AIR).  Actually fixed already in 1.16.2, but I'll get the same fix into 1.15.2.

**Comment by desht** [comment]
Fixed in 1.4.4 release
