### ISSUE TITLE
Drone crafting deletes tools from TerraFirmaCraft

### ISSUE THREAD

**Issue by masau** [TeamPneumatic/pnc-repressurized#582]
### Minecraft Version
1.12

### Forge Version
1.12.2-14.23.5.2847

### Mod Version
pneumaticcraft-repressurized-1.12.2-0.11.15-398

### Describe your problem, including steps to reproduce it
I created a drone program to craft sandwiches from the 1.12 version of TerraFirmaCraft (in the modpack TechNodeFirmaPack). Everything (opening/closing TFC barrels, picking up items, making bread, etc) works until it gets to actually crafting them - it crafts the first one and the deletes the knife instead of giving it durability damage and putting it back in the drones inventory.

Steps to reproduce:
Install TFC-TNG and Pneumaticraft
Set up drone program to pick up ingredients for a sandwich and then craft sandwich
Have drone deposit items in a chest and it will no longer have the knife

### Any other comments?
I encountered a similar issue with crafting TFC dough using tanks from openblocks - the tank gets deleted instead of losing water. I switched to using buckets and it works fine.

**Comment by desht** [comment]
Sorry, 1.12.2 is out of support now.

**Comment by masau** [comment]
Can you update the readme? It still says 1.12 is being supported
