### ISSUE TITLE
Cannot see puzzle pieces in Programmer

### ISSUE THREAD

**Issue by gchpaco** [TeamPneumatic/pnc-repressurized#584]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version

1.15.2

### Forge Version

31.2.36

### Mod Version

1.4.3-60

### Describe your problem, including steps to reproduce it

Reoccurrence of #496 and #543, but attempting to change the GUI scale doesn't help.

### Any other comments?

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/17789/90838361-56045200-e31a-11ea-86a8-cefb79d3b6ea.png">

**Comment by gchpaco** [comment]
I tried at least GUI scale = auto, 1, 2, 3 and 4 and couldn't see the puzzle pieces that are obviously there in any of them.

**Comment by desht** [comment]
Sorry, not seeing this behaviour at all.  Tried several combinations of resolution and GUI scale, and it's all working for me.

Anything in your logs?

**Comment by gchpaco** [comment]
All I can see in the logs is
```[20Aug2020 18:56:55.527] [Render thread/ERROR] [Waila/]: Caught unhandled exception : [class me.desht.pneumaticcraft.common.thirdparty.waila.SemiblockProvider$Component] java.lang.AbstractMethodError: Method me/desht/pneumaticcraft/common/entity/semiblock/EntityLogisticsPassiveProvider.getDisplayName()Lnet/minecraft/util/text/ITextComponent; is abstract```
which looks like a Waila thing.

**Comment by gchpaco** [comment]
Yeah just checked again, not seeing anything.

**Comment by gchpaco** [comment]
Just reproduced with only JEI, 1.15.2, Forge 31.2.36, and mod version 1.4.4-64.  It may matter that I'm on a Mac.

![image](https://user-images.githubusercontent.com/17789/90942147-2b79ce00-e3da-11ea-8019-ce5cc7c58031.png)

**Comment by gchpaco** [comment]
Tested and experienced the same problem with 1.16.1 with 32.0.108, and pneumaticcraft 2.1.1-14, again on my Mac.  Having a friend try on her Linux box.

**Comment by gchpaco** [comment]
Friend confirms she can see the tokens on Linux.  She's testing on her mac to see if it's version specific.

**Comment by esotericist** [comment]
as the friend in question, i used:
minecraft 1.15.2, forge 31.2.36, jei 6.0.2.14, pneumaticraft 1.4.4. no other mods present for testing.

on both linux and macos (10.14.6) i'm able to see the tokens just fine, so i can only guess it's either an install-specific issue, a configuration-specific issue, or something that only manifests on certain version[s] of macos.

**Comment by gchpaco** [comment]
So on a hunch I tried older releases.  The 1.12 Programmer works fine.  The 1.14 Programmer shows the same problem (i.e. cannot see tiles); I tested back as far as 1.14.4-1.0.0 (the alpha).  1.12.2-0.11.14-395 worked in 1.12.  So whatever it is that's doing this (and I have a hunch the canvas widget is drawing the tiles, just waaaaaaaay off the play field, like on mars) was introduced in the 1.14 transition, which I know doesn't nail it down much.

**Comment by gchpaco** [comment]
Hm.  Something that occurs to us; I have a Retina display.  I wonder if that's a contributing factor.

**Comment by desht** [comment]
Yeah that's probably significant. What's your display resolution?

There were major changes in the programmer gui code between 1.12 and 1.14, mainly due to very different gui code in vanilla. It's not quite a rewrite but pretty big all the same.

**Comment by gchpaco** [comment]
True display size: 3072 x 1920.  I believe this is a 2x retina, so it pretends to be 1536 x 960.  I tested on an external display with the laptop in headless mode, but no love.  If I tell it to pretend to be 1536 x 960, still no love.  I know I've tried telling it to pretend to be 1152 x 720, and it didn't help.  If you have a debug build you want me to run with more logs that reports e.g. where the actual position of the canvas display is on the screen and where it thinks its drawing stuff, I'm happy to do that.

**Comment by desht** [comment]
Yeah I might put a debug build together for this. It's not so much where it draws as the size of the OpenGL scissor area that limits where drawing of widgets happens.

**Comment by desht** [comment]
There might be a more general problem with Glscissor and hi-dpi macos displays... a bit of googling turned up a couple of links with unrelated (non minecraft) projects experiencing similar issues on macs.

**Comment by gchpaco** [comment]
Interesting! https://github.com/ocornut/imgui/commit/e58f99179aa3e8fa78e783f772c31ee23d40863d might be of use as an example.

**Comment by desht** [comment]
Strangely enough, I'm just looking at that now :)

**Comment by desht** [comment]
Before I go too deep into that, I've made a small change which makes the scissor box calculations more like 1.12.  Can you give build 22 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ a go and let me know if it helps any?

**Comment by desht** [comment]
Oh just realised you're on 1.15...this build is for 1.16, sorry. I'll get a 1.15 build done later but I need to go out for a bit.

**Comment by desht** [comment]
Build 66 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ has the same change.

**Comment by gchpaco** [comment]
That did it. 
<img width="966" alt="image" src="https://user-images.githubusercontent.com/17789/90957002-d4631000-e450-11ea-9936-a76a22e802b8.png">

**Comment by desht** [comment]
Excellent, turned out to easier than I'd feared then!  That fix will be in the next 1.15 and 1.16 releases.

**Comment by desht** [comment]
Fixed in 2.2.0 and 1.4.5 release
