### ISSUE TITLE
Cannot make Etching Acid in the Pressure Chamber.

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#587]
### Minecraft Version
1.15.2

### Forge Version
31.2.36

### Mod Version
pneumaticcraft-repressurized-1.15.2-1.4.4-64

### Describe your problem, including steps to reproduce it
This one is easy to reproduce, adding the four ingredients into the pressure chamber with a hopper the bucket does not go into the chamber. Break the chamber and add the bucket manually the message no valid ingredients.

The ingredients are: a bucket, 2 gunpowder, 2 spider eye and 2 rotting flesh.

**Comment by desht** [comment]
"a bucket" ?  Double check the recipe: it's a bucket of molten plastic :)

**Comment by duncanwebb** [comment]
Sorry, it looked like an empty bucket, sometimes I'm blind. 

Why plastic instead of water? If it is to gate PCBs behind plastic, it doesn't make sense as you need plastic to make the Amadron tables and empty PCBs.

**Comment by desht** [comment]
Etching acid has always needed plastic to make, although in earlier versions of the mod it was Green Plastic items, rather than a bucket of molten plastic. Otherwise the requirements are very similar.

**Comment by duncanwebb** [comment]
There is something that you could do, molten plastic is grey and plastic is white how hard would it be to make molten plastic a lighter colour?

**Comment by desht** [comment]
Yeah probably not a bad idea.
