### ISSUE TITLE
Coordinate Tracker doesn't work with Pnuematic Helmet

### ISSUE THREAD

**Issue by Neko-LoverDisc** [TeamPneumatic/pnc-repressurized#588]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
When using the Pneumatic Helmet, the Coordinate Tracker doesn't work, no matter at what depth

To reproduce, install a Coordinate Tracker into the Helmet and at any location press U and hit "navigate to surface"

**Comment by desht** [comment]
Yep, the coord tracker has not really worked properly since 1.7.  There are a lot of dependencies on vanilla pathfinding which worked well back then but not so much since 1.12.  I do want to fix it, but I only have so much time, and this isn't high priority.

**Comment by desht** [comment]
And it's not true to see it doesn't work no matter what.  It does work in many situations, just not as reliably as I'd like.

**Comment by Neko-LoverDisc** [comment]
It didn't work at all for me though? Navigate to surface doesn't show anything, and navigate to coordinates doesn't seem to do anything. Just says to right click to set coordinates though nothing else

**Comment by desht** [comment]
Did you actually switch on the upgrade?

**Comment by Neko-LoverDisc** [comment]
Yes I did; I made sure of it

**Comment by desht** [comment]
I don't know then. It works when I test it. Just be sure the check box in the top of the gui is checked

**Comment by Neko-LoverDisc** [comment]
I double checked, redownloaded it, I seem to be not able to get it to work in any way shape or form

**Comment by desht** [comment]
As I said, I don't know what to tell you.  It works.
![2020-09-04_12 31 28](https://user-images.githubusercontent.com/736831/92235046-f7f37500-eeaa-11ea-9c1e-4abde4754e82.png)
![2020-09-04_12 32 13](https://user-images.githubusercontent.com/736831/92235151-2709e680-eeab-11ea-93ec-f4739445e61c.png)

**Comment by Neko-LoverDisc** [comment]
Could you give me steps to select a coordinate, or should I record and attach a video? I feel like maybe i'm missing something

**Comment by desht** [comment]
1. Open your armor GUI ('U' by default, but it can be rebound)
2. Select "Coordinate Tracker" (assuming you have a Coordinate Upgrade installed in the helmet)
3. Ensure the "Enable Coordinate Tracker" checkbox is ticked (see my first image above).  
3b. Optionally, you can bind a hotkey to the checkbox by right-clicking it, then pressing the key you want (shift/ctrl/alt modifiers allowed too).  That lets you switch it on & off from outside the armor GUI.
4. Click the "Select Target..." button.  GUI will close, and you then right-click the block you want to target.  That will highlight the block as in my second image above.
5. If you want the green navigator line to show, also ensure "Navigation Enabled" is showing.  Click the button to toggle it.

**Comment by Neko-LoverDisc** [comment]
Are you using 1.15.2 and stuff? Or could it possibly be because of my forge version? I did those exact steps and nothing happened

**Comment by desht** [comment]
OK, I've actually found a rendering issue on 1.15.2 where the positioning matrix was missing.

**Comment by desht** [comment]
Fix will be in next release.  If you want to try it sooner, you can test out build 70 from https://jenkins.k-4u.nl/view/Desht/job/PneumaticCraft-Repressurized-1.15/

**Comment by Neko-LoverDisc** [comment]
Oh ok, thank you! I thought I was being a moron or something and missing something very obvious

**Comment by desht** [comment]
Nah, was indeed my fault :)  Sorry for the confusion.  Developing simultaneously for 1.15 and 1.16 gets me confused sometimes.

**Comment by Neko-LoverDisc** [comment]
It's fine, we all have a lot we're going through due to this corona stuff. It's 4 AM here, so after I wake up I'll test the mod. Also +1 respect for porting pnuematiccraft in the first place. Have a good night

**Comment by desht** [comment]
Fixed in 1.5.0 release
