### ISSUE TITLE
Dupe glitch

### ISSUE THREAD

**Issue by omarmartinez97** [TeamPneumatic/pnc-repressurized#589]
### Minecraft Version
1.16.1

### Mod Version
newest
### Describe your problem, including steps to reproduce it
killing a harvesting drone(havent tried the others) with looting sword seems to dupe the drone along with its installed upgrades

**Comment by desht** [comment]
Not in my world, it doesn't.  I killed a Harvesting Drone with a Looting III sword, and it dropped one drone item, as expected.

I suspect another mod is interfering here.  What else do you have installed, and can you reproduce this problem with just PNC loaded (utility mods like JEI and Waila/TOP are fine as well) ?

**Comment by duncanwebb** [comment]
I've seen items being duplicated too and I think this happens between shutdown and starting of the game. I've had items duplicated for both PneumaticCraft and Mystical Agriculture. It is easier to notice an additional supremium watering can than duplicated dirt, etc.

**Comment by desht** [comment]
I don't have enough to go on here.  Any specific instructions for reproducing this would be useful.

**Comment by duncanwebb** [comment]
I was trying to say that this is a general "feature" rather than PneumaticCraft specific.

**Comment by desht** [comment]
Closed due to lack of response
