### ISSUE TITLE
Coal blocks into diamond recipe cause JEI display bug

### ISSUE THREAD

**Issue by misterplus** [TeamPneumatic/pnc-repressurized#590]
### Minecraft Version
1.12.2
### Forge Version
2847
### Mod Version
1.12.2-0.11.15-398
### Describe your problem, including steps to reproduce it
1.Install penumaticcraft and jei and some other mods that displays recipes related to coal blocks (botania's earth rune for example)
2.JEI shows 8 coal blocks instead of one
3.Disable enableCoalToDiamondsRecipe fixes this issue
### Any other comments?
nope, should be clear enough

**Comment by desht** [comment]
It's supposed to do that.

**Comment by misterplus** [comment]
NO! It's affecting other mods' recipes! Botania's earth rune shows 8 coal blocks instead of 1, I'm not talking about the diamond recipe.

**Comment by SeraphJACK** [comment]
It does not suppose to do that.

**Comment by desht** [comment]
Ok. Since 1.12.2 isn't supported anymore, just disable the coal to diamonds recipe.
