### ISSUE TITLE
"Draw from logistics" and "insert into logistics" would be nice pieces

### ISSUE THREAD

**Issue by gchpaco** [TeamPneumatic/pnc-repressurized#592]
One missing thing in the puzzle pieces is a "draw from the nearby logistics providers" and "send to nearby logistics providers"; for example, so I can make a crafting drone that isn't super specific about everything it needs to draw from or send to.

**Comment by desht** [comment]
Neither are necessary.

* "Draw from providers": set up a chest with a Requester Frame, and use a "Import from Inventory" piece.
* "Send to providers": set up a chest with an Active Provider Frame, and use a "Export to Inventory" piece.
