### ISSUE TITLE
GPS Area Tool picks values I didn't expect

### ISSUE THREAD

**Issue by gchpaco** [TeamPneumatic/pnc-repressurized#593]
### Minecraft Version

1.15.2

### Forge Version

1.15.2-31.2.36

### Mod Version

Unreleased pneumaticcraft-repressurized-1.15.2-1.4.4-66.jar

### Describe your problem, including steps to reproduce it

When I try to select a P1 and a P2 from a GPS Area Tool, it seems to pick something in the middle of the space swept out.  I assumed it would use the P1 and P2 on the tool.  Left clicking with the tool on the puzzle piece does work as normal, however.

Tool: 
<img width="657" alt="image" src="https://user-images.githubusercontent.com/17789/91236173-dbae4600-e6fc-11ea-80e0-59ef06f2e0bb.png">

Coordinate selection:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/17789/91236194-e79a0800-e6fc-11ea-8113-2dbc37b81b3d.png">

### Any other comments?

Hopefully easier to fix this time :D

**Comment by desht** [comment]
This is actually intended behaviour, since the Area GPS Tool is not intended to be used for getting a specific coordinate.  If you need that, use a plain GPS Tool.
