### ISSUE TITLE
Done conditions on teleport and go to location are reversed

### ISSUE THREAD

**Issue by gchpaco** [TeamPneumatic/pnc-repressurized#594]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version

1.15.2

### Forge Version

1.15.2-31.2.36

### Mod Version

Unreleased pneumaticcraft-repressurized-1.15.2-1.4.4-66.jar

### Describe your problem, including steps to reproduce it

"Done when departing" and "Done when arrived" are reversed in the teleport and go to location commands.

View from programmer:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/17789/91236409-6c852180-e6fd-11ea-9190-620bfdbccd9a.png">

View from widget:
<img width="290" alt="image" src="https://user-images.githubusercontent.com/17789/91236433-7a3aa700-e6fd-11ea-9801-98c37075263f.png">

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Fixed in 2.2.0 and 1.4.5 release
