### ISSUE TITLE
Aerial Interface doesn't recognize Industrial Foregoing XP Fluid(Essence)

### ISSUE THREAD

**Issue by Particle1904** [TeamPneumatic/pnc-repressurized#598]
Minecraft Version: 1.16

Forge Version: 32.0.108

Mod Version: 2.1.1-14

Describe your problem, including steps to reproduce it: The Aerial Interface can't use the Industrial Foregoing XP Fluid. 

Thanks! :)

**Comment by desht** [comment]
I can get that added easily enough.

**Comment by desht** [comment]
Fixed in 2.2.0 release
