### ISSUE TITLE
Immersive Engineering 4.0.0 API break for fuels

### ISSUE THREAD

**Issue by yueh** [TeamPneumatic/pnc-repressurized#599]
### Minecraft Version
1.16.1

### Forge Version
32.0.108

### Mod Version
2.1.2-25

### Describe your problem, including steps to reproduce it

IE broke the method to register fluids from using a concrete `Fluid` to accepting a `ITag<Fluid>` now.
See [DieselHandler.java#L32](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.16/src/main/java/blusunrize/immersiveengineering/api/energy/DieselHandler.java#L32)

Not tested yet, if the pnc biodiesel would now work automatically.

### Any other comments?
No

**Comment by desht** [comment]
Fixed in 2.2.0 release
