### ISSUE TITLE
Server Kicking Players when using pneumatic devices

### ISSUE THREAD

**Issue by Kuvios** [TeamPneumatic/pnc-repressurized#600]
### Minecraft Version
1.16.1
### Forge Version
32.0.108
### Mod Version
2.1.1-14
### Describe your problem, including steps to reproduce it
My friends and I have been playing on a 1.15.2 Modded server and recently decided to update to 1.16.1. After double-checking world compatibility, we updated now every time someone uses a pneumatic device in a player's inventory ex.(minigun or pneumatic armor) every player on the server except the user is kicked and shown the error I have pinned below. Any help would be much appreciated on a possible fix or to see if this is a more widespread problem.
### Any other comments?
![Crash](https://user-images.githubusercontent.com/70493978/91672867-ee5ebb80-eafe-11ea-9973-b8944aed0767.jpg)

**Comment by desht** [comment]
That's weird. Anything in the server or client log files?

**Comment by desht** [comment]
So, I just tried to reproduce this using a dedicated server and two accounts, I can't - it works absolutely fine.  Which suggest there may be some other mod interfering.  Can you reproduce this with just PneumaticCraft installed?  And if you do have any stacktraces in your server log, or the client log of someone who's getting kicked, I really need to see those.

**Comment by Kuvios** [comment]
I just realized I forgot to include this, it only kicks players when more than 3 people are on the server total. I will check the log files as soon as I can

**Comment by desht** [comment]
That's going to be really difficult for me to reproduce if that's the case. And also suggests a problem outside PNC. But I'll be interested to see any logs.

**Comment by Kuvios** [comment]
#

**Comment by Kuvios** [comment]
@desht I was able to get the server log, sorry it took so long the server isn't at my house

**Comment by desht** [comment]
Unfortunately the server log just shows the same error that the original screenshot shows, no stacktrace to indicate where it's originating.  So we're back to square one :(

**Comment by Kuvios** [comment]
@desht It’s okay, we will simply avoid pneumatic items until we can solve the problem. Thanks for the help

**Comment by desht** [comment]
If you can get the client log from someone who's been kicked by this, it might help to track the problem down.

**Comment by Rosentti** [comment]
This bug happens because patchouli is not installed.
```
[Render thread/ERROR] [mezz.jei.plugins.vanilla.crafting.VanillaRecipeValidator/]: Recipe has no output. PneumaticCraft: Repressurized pneumaticcraft:patchouli_book_crafting class me.desht.pneumaticcraft.common.recipes.special.PatchouliBookCrafting
Outputs:
net.minecraft.item.ItemStack: [[1 air minecraft:air]]
Inputs:
net.minecraft.item.ItemStack: [[1 book minecraft:book], [1 ingot_iron_compressed pneumaticcraft:ingot_iron_compressed]]
```

**Comment by desht** [comment]
Nope, that's a non-fatal error from the client, and won't cause a kick (although I should be able to avoid with a conditional recipe).  I've tested without Patchouli available, and I don't get kicked.

**Comment by Rosentti** [comment]
There is nothing else about that in the client log.

**Comment by desht** [comment]
Nothing else about what?

**Comment by Rosentti** [comment]
The disconnect.

**Comment by desht** [comment]
Without actually seeing the client log (and I never have despite repeated requests), I'll just have to take your word for that.
