### ISSUE TITLE
[1.15.2] Compressed block blue flickering

### ISSUE THREAD

**Issue by TheUntamed** [TeamPneumatic/pnc-repressurized#602]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2
### Forge Version
31.2.36
### Mod Version
1.4.4-64
### Describe your problem, including steps to reproduce it
If a compressed block is placed it flickers blue before it takes on the normal color.
The block screenshotted in the moment it is placed:
![Screenshot_1](https://user-images.githubusercontent.com/48363903/91729094-53b8b800-eba4-11ea-9aca-f534c00654af.jpg)

**Comment by desht** [comment]
Yeah, known issue, since the block's temperature isn't instantly sync'd to client when it's placed (so it defaults to 0K, i.e. super cold).  Very minor problem but I'll see if I can get it defaulted on the client when placed to avoid visual confusion.

**Comment by desht** [comment]
Fixed in 2.2.0 & 1.4.5 release
