### ISSUE TITLE
Using a pneumatic wrench to rotate a block with a GUI will also open it

### ISSUE THREAD

**Issue by yueh** [TeamPneumatic/pnc-repressurized#603]
### Minecraft Version
1.16.1

### Forge Version
32.0.108

### Mod Version
2.1.2-25

### Describe your problem, including steps to reproduce it
When using a penumatic wrench to rotate a block, it will rotate it by one step and also open the GUI. 

---
Edit: This only applies when being in creative mode

**Comment by desht** [comment]
Fixed in 2.2.0 release
