### ISSUE TITLE
[1.16.1] Memory Stick doesn't display stored XP

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamPneumatic/pnc-repressurized#605]
### Minecraft Version
1.16.1 

### Forge Version
1.16.1-32.0.108

### Mod Version
pneumaticcraft-repressurized-1.16.1-2.2.0-29

### Describe your problem, including steps to reproduce it
The Memory Stick does not display stored xp.

### Any other comments?
The Left-click to auto-absorb only works when left-clicking a block with the Memory Stick, very minor inconvenience. 

Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/221

**Comment by desht** [comment]
Confirmed.  Always showing 0 XP.

**Comment by desht** [comment]
Fixed in build 30 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/

**Comment by NielsPilgaard** [comment]
Thanks for the swift fix :)

**Comment by desht** [comment]
Fixed in 2.2.1 release
