### ISSUE TITLE
Pneumatic armors can work with only 2 armor upgrades

### ISSUE THREAD

**Issue by SSSShion** [TeamPneumatic/pnc-repressurized#606]
I'm playing Minecraft 1.12.2 with Forge 14.23.5.2854, and the mod version is pneumaticcraft-repressurized-1.12.2-0.11.15-398. As can be seen in the screenshot, the pneumatic boots installed with 6 armor upgrades exhibit only 2 armor points in item information and 4 points in armor column, which should be 2+6=8 both. The same issue exists for other armor parts. 
![1](https://user-images.githubusercontent.com/70960750/92489096-eea73700-f221-11ea-82c8-9b2eac0d28ac.png)

**Comment by desht** [comment]
It's a visual issue IIRC, you do actually get the protection even if it doesn't show.

In any case, 1.12.2 version of the mod isn't supported anymore so won't be changed.
