### ISSUE TITLE
Amadron Ordering failing on orders over 64 emeralds

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#608]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.1
### Forge Version
32.0.108
### Mod Version
1.16.1-2.2.0-29

### Describe your problem, including steps to reproduce it

Looks like possible regression issue with Amadron as you had this fixed before in #547

I had a trade of 1 emerald for 1 pink wool just now. If I traded 64 or fewer emeralds, I'd get the correct number of wool in return. However, as soon as I traded 65 or more emeralds, the drone would come in, collect one stack of emeralds, and fly away never to be seen again. 

### Any other comments?

https://streamable.com/6peocq

**Comment by desht** [comment]
That fix is still in, unfortunately.  Which means a new problem :(  Will investigate when I can, but it might be a few days due to RL.

**Comment by desht** [comment]
Got a chance to look at it - actually a completely different bug, where the Amadrone wrongly thought it had only one inventory slot.  Easy enough to fix, fortunately!  Will try to get a build uploaded soon.

**Comment by MuteTiefling** [comment]
Cool! I'll test it out later.

**Comment by desht** [comment]
Build 31 should do the trick...

**Comment by MuteTiefling** [comment]
Lookin good. All fixed up. Thanks!

**Comment by desht** [comment]
Fixed in 2.2.1 release
