### ISSUE TITLE
Collector drones deposit stuff wierdly into chests

### ISSUE THREAD

**Issue by KrAzYGEEK32** [TeamPneumatic/pnc-repressurized#610]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.1
### Forge Version
32.0.108
### Mod Version
1.16.1 - 2.2.0-29
### Describe your problem, including steps to reproduce it
collector drones seem to deposit same items into different stacks,  normally this wouldnt be an issue, it becomes one when a logistics drone tries to interact with the chest as well, it will wait for a set items to be collected in a stack before transferring them
 
### Any other comments?
![2020-09-10_20 28 40](https://user-images.githubusercontent.com/59537798/92754186-3952bb80-f3a8-11ea-9421-03b5a5c5157b.png)
pic just to clarify my stupid explaination XD

**Comment by desht** [comment]
Yeah, I see what you mean.  I'll get them to always add to an existing stack if they can.

**Comment by desht** [comment]
Fixed in 2.2.1 release
