### ISSUE TITLE
Missing death message for pressure chamber

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#612]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.1
### Forge Version
32.0.108
### Mod Version
pneumaticcraft-repressurized-1.16.1-2.2.1-32

### Describe your problem, including steps to reproduce it

Goofing around earlier, I noticed the death message for dying in the pressure chamber doesn't seem to pull the proper message from the lang files. Just getting '"death.attack.pressure1". 

### Any other comments?

![image](https://user-images.githubusercontent.com/9543430/93157639-97e5a580-f6d8-11ea-8f3a-30402fb6b7ce.png)

**Comment by MuteTiefling** [comment]
All good! Working as expected now 😃

**Comment by desht** [comment]
Fixed in 2.2.2 release
