### ISSUE TITLE
Pneumatic Jackhammer dupe bug

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#614]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.1
### Forge Version
32.0.108
### Mod Version
pneumaticcraft-repressurized-1.16.1-2.2.1-32

### Describe your problem, including steps to reproduce it

1. Build multiple jack hammers. 
2. Hold the stack and enter the GUI
3. Insert an enchanted book and a drill bit. 

All of the jackhammers get the book/drill, so if you separate the stack and access the GUI on each, you can pull out a book/drill bit from each. 

### Any other comments?

Probably best to make it non stackable to avoid this.

**Comment by desht** [comment]
Oops, yeah.

**Comment by desht** [comment]
Fixed in 2.2.2 release
