### ISSUE TITLE
[1.15] Add a config option to disable the PneumatiCraft villager + village house from spawning

### ISSUE THREAD

**Issue by Unhook** [TeamPneumatic/pnc-repressurized#616]
A config option to disable the PneumatiCraft village house from spawning would be appreciated. This is especially useful for progression packs, where the villager and village house could be used to skip progression/get access to pneumaticraft earlier than wanted.

**Comment by desht** [comment]
Yeah, that's reasonable.  I'll get that into the next release.

**Comment by desht** [comment]
Build 71 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.15/ has this functionality added, if you'd like to test it out.  See the `Villages` section in `config/pneumaticcraft-common.toml`.

It's possible to disable generation of houses, and disable the trades a Pressure Mechanic offers (or limit the trades to _only_ the PCB Blueprint).  Switching off Pressure Mechanic villagers entirely is not an option (controlling registration via config is a no-no), but the changes I've added should prevent any issues with progression.

Note also the config settings should be applied _before_ worldgen happens; any houses or villagers which are generated beforehand won't (can't) be affected by these config settings.

**Comment by desht** [comment]
Added in 1.5.0 release
