### ISSUE TITLE
Crash when breaking water logged chests while block tracker is tracking inventories

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#618]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.1
### Forge Version
32.0.108
### Mod Version
1.16.1-2.2.2-35
### Describe your problem, including steps to reproduce it

Place a chest in some water
Turn on block tracker for inventories
Break the chest

### Any other comments?

[crash-2020-09-22_08.56.48-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5261530/crash-2020-09-22_08.56.48-client.txt)

[latest.log](https://github.com/TeamPneumatic/pnc-repressurized/files/5261531/latest.log)

**Comment by MuteTiefling** [comment]
Running into this when breaking chests in sunken ships, but also can reproduce in a 3x3x3 area of water.

**Comment by desht** [comment]
Confirmed & fixed!

**Comment by desht** [comment]
Fixed in 2.2.3 release
