### ISSUE TITLE
[1.15.2] Crash on startup

### ISSUE THREAD

**Issue by Unhook** [TeamPneumatic/pnc-repressurized#620]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15.2

### Forge Version
forge-31.2.41

### Mod Version
1.15.2-1.5.0-73

### Describe your problem, including steps to reproduce it
Game crashes on start up. Everything was fine earlier, then I hid an item in JEI and added a datapack to add some recipes to AE2's grinder. When I restarted my game it kept crashing - reverted both those changes, but the game keeps crashing now.

### Any other comments?
Crash log: https://pastebin.com/dM0gu7AN

**Comment by desht** [comment]
Yep, seen this one way too many times before.  It's not a PNC issue at all.  Check (much) earlier in your logfile and you'll find something else has crashed during registration.  Forge stupidly carries straight on though, leading to the first mod which tries to register a color handler to crash, and wrongly get blamed for it.
