### ISSUE TITLE
Drone: Trouble with shaped (cylinder) collection area

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#621]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.1
### Forge Version
32.0.108
### Mod Version
1.16.1-2.2.2-35
### Describe your problem, including steps to reproduce it

If given a cylinder (axis y) collection area, the drone does not detect any items to collect. 

If given a box type collection area, it works fine. 

### Any other comments?

Test Programs: https://gist.github.com/MuteTiefling/2967ce8dc8b087b01c35fd32de6c8a79

**Comment by MuteTiefling** [comment]
I think it may be treating it as a line area instead of a cylinder. I just realized this was the problem I was having with a milking operation too, it was only milking the cows that were between the two points, rather than in the entire circular area that was defined by the two points.

**Comment by desht** [comment]
This is intended behaviour, I'm afraid and actually documented in the Patchouli guide:

> Keep in mind that any Area widgets connected to this widget will always be interpreted as area type Box, regardless of the given area type. It's possible to create more complex shapes, though, by using whitelisting/blacklisting of multiple areas."

Always been this way for performance reasons, but I might take a look at ways to get around this, if possible to do without being a lag monster...

**Comment by desht** [comment]
BTW (since this is a handy place to mention it), I'll be ceasing development on 1.16.1 pretty soon, especially since there's now a RB out for Forge on 1.16.3, and PNC has a 1.16.3 alpha (with another alpha planned today).  Just don't have time to keep all three of 1.15.2 (LTS), 1.16.1 and 1.16.3 updated...

**Comment by MuteTiefling** [comment]
Oh, dang. Silly me, sorry. I've always done square setups and just recently started making more rounded shapes as they're slightly easier to define from a central point. But if this is for performance, then stick to it. Performance is more important in a case like this I think.

I presume it's the same thing for the right click entity as well? I'm not seeing a mention of the box type restriction in the patchouli manual, but since both are dealing with entities in some way it would make sense.

**Comment by MuteTiefling** [comment]
Also, totally understood for 1.16.1. I'll pop over to that as soon as I'm able. Pretty much just waiting for e6 to update to have a larger pack to play it in.

**Comment by desht** [comment]
> I presume it's the same thing for the right click entity as well? I'm not seeing a mention of the box type restriction in the patchouli manual, but since both are dealing with entities in some way it would make sense.

Yeah same deal. I'll get the manual updated for that as well.

**Comment by desht** [comment]
Docs updated.  The Programmer GUI will also now actually disallow adding area widgets with a non-box shape to those widgets which need a box (which are basically those widgets which interact with entities in an area).

Such programs won't compile anymore (but existing drones which have these invalid programs will continue to work and treat the area as a box).
