### ISSUE TITLE
Advanced Liquid Compressor crashing after fuel intake

### ISSUE THREAD

**Issue by TheFern2** [TeamPneumatic/pnc-repressurized#622]
### Minecraft Version
1.16.3

### Forge Version
1.16.3

### Mod Version
pneumaticcraft-repressurized-1.16.3-2.4.0-36

### Describe your problem, including steps to reproduce it
Creative mode. The Advanced Liquid Compressor is crashing minecraft. I placed it on the world, then went to put some fuel, looks like the fuel is taken, bucket gets emptied then it crashed. I restarted the game fine, right click into the compressor and crashed right away again.
[crash-2020-09-24_19.19.16-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5279854/crash-2020-09-24_19.19.16-client.txt)

**Comment by desht** [comment]
Yep, I hit this myself yesterday. Actually already fixed in dev, I'll be getting another release out today probably.

**Comment by TheFern2** [comment]
Awesome, now is working. :smiley:
