### ISSUE TITLE
Pressure chamber voiding items when they are inserted with Mekanism logistical transporters(item pipes)

### ISSUE THREAD

**Issue by KrAzYGEEK32** [TeamPneumatic/pnc-repressurized#624]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.1
### Forge Version
32.0.108
### Mod Version
2.2.1-32
mekanism - 10.0.9.432
### Describe your problem, including steps to reproduce it
its in the title
this only happens when the pipe tries to insert multiple items into the interface when it is closed for input
1. form a pressure chamber
2. connect a mekanism logistical transporter from a chest to an interface
3.  put some items in the chest and set the pipe to pull
4. voids some items 100% of times
### Any other comments?
i seriously thought this was an issue with mekanism https://github.com/mekanism/Mekanism/issues/6543 the dev says its an issue with PNC so im reporting here

**Comment by desht** [comment]
Confirmed.  Added 1 gold & 2 redstone to a chest and although everything appeared to flow into the interface, only 1 gold and 1 redstone made it into the chamber.

**Comment by desht** [comment]
Nope, I believe this is a Mekanism issue, and I added a detailed explanation of why in their issue.

**Comment by desht** [comment]
Confirmed as a Mekanism issue and they're working on a fix now.
