### ISSUE TITLE
Drone Programmer Preview Area not fully shown

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#625]
### Minecraft Version
1.15.2

### Forge Version
31.2.36

### Mod Version
pneumaticcraft-repressurized-1.15.2-1.5.0-75

### Describe your problem, including steps to reproduce it
Using the place piece to make an irregular shape, like a soul sand "T" for the wither base, with two area pieces. The preview area does not show the shape, only the bottom. When the preview area is active it seems to be applied to all areas, and they are not being shown.

### Any other comments?
Thanks again you're doing a great job.

**Comment by duncanwebb** [comment]
When previewing a position in the programmer, the position does not show when there is a block there. I was testing for a sticky piston being at a position and the preview does not show. However, it does show when using the GPS tool.

**Comment by desht** [comment]
Yeah that should be more consistent...

**Comment by desht** [comment]
Fixed in 1.5.1 release
