### ISSUE TITLE
Pressure Chamber with a vacuum and volume upgrades doesn't work.

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#626]
### Minecraft Version
1.15.2

### Forge Version
31.2.36

### Mod Version
pneumaticcraft-repressurized-1.15.2-1.5.0-75

### Describe your problem, including steps to reproduce it
Using the pressure chamber in vacuum mode, when adding volume upgrades, it no longer works. The maximum air is increased from 16000 to 32000 but the pressure stop at 16000 so the pressure is insufficient for disenchanting.

### Any other comments?
I was searching for a faster way to make the vacuum and this does not seem to work with volume or speed upgrades in the pump. Any ideas how to achieve this with a single pump?

**Comment by desht** [comment]
Yeah, I actually discovered this myself when coding some new stuff for 1.16.3... it's an easy fix and I'll do backport for 1.15.2.

**Comment by desht** [comment]
Btw speed upgrades should work OK in the vacuum pump - at least they did when I was testing in 1.16.3.  The vacuum pump is fairly slow to create a vacuum, though - it only removes 2 air from the vacuum side for every 10 air used on the main side.  Speed upgrades do have an effect, but they also make the pump less efficient (i.e. use more air per vacuum created)

Where S is the number of speed upgrades:

* Air used / tick = 10 * (1.65 ^ S)
* Vacuum produced / tick = 2 * (1.5 ^ S)

In my testing, I found that an Advanced Liquid Compressor (but limited to 5 bar) powering a vacuum pump produces a vacuum reasonably quickly.  Both the compressor and pump should have some Speed Upgrades too - as many as you can get into both while not overheating the compressor too much (a little excess isn't much of a problem).

**Comment by desht** [comment]
Build 76 should fix the volume problem...

**Comment by duncanwebb** [comment]
You're superfast ;-) I'll test it shortly.

**Comment by duncanwebb** [comment]
Thanks for your tips, I ended up using two pumps and an advanced air compressor. Need to process more oil for the speed upgrades.

![vacuum-chamber](https://user-images.githubusercontent.com/4198031/95236698-8be89180-0807-11eb-8a34-ea56243d1741.png)
