### ISSUE TITLE
Right click Drone command does not right click blocks yet.

### ISSUE THREAD

**Issue by MineMaarten** [TeamPneumatic/pnc-repressurized#63]

**Comment by desht** [comment]
By "right click blocks", we're talking about the drone right-clicking with a block item in its slot 0, yes?

I guess one question to be asked is: under what circumstances would you want to use the "right click" puzzle piece rather than "place block" puzzle piece if placing blocks is what you want to be doing?

**Comment by MineMaarten** [comment]
No, it's mainly about actually right clicking a block, I tested for example right clicking a lever to let it toggle redstone state. But it would also have to be able to wrench stuff for example.

**Comment by desht** [comment]
OK, made a few little changes.  Working much better now, but maybe not 100% yet.

What works:
* Drone can flip a lever 
* Drone can get a TE crescent hammer and wrench a TE tank - works without sneak (toggles tank), and with sneak (drops tank as item)
* Drone can get a vortex cannon and fire it at an empty block (until vortex cannon is empty)

What does not work:
* Getting a pneumatic wrench and trying to rotate a chest (either vanilla or iron chest).  ``Block#onBlockActivated`` gets called and appears to return success, but the chest is not activated.  With iron chests nothing happens, with vanilla chests the chest lid pops open.

**Comment by desht** [comment]
Now it's behaving much better!  I think this is solved, but can you do some testing too @MineMaarten ?

**Comment by MineMaarten** [comment]
Awesome, works great now!
