### ISSUE TITLE
[1.16.1] Occasional server crash on player login when aerial interface is fed by Mekanism Universal Cable

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamPneumatic/pnc-repressurized#630]
### Minecraft Version
1.16.1

### Forge Version
1.16.1-32.0

### Mod Version
1.16.1-2.2.1-32.0.108

### Describe your problem, including steps to reproduce it
Sometimes the server crashes with attached exception when player logins while his/her aerial interface is fed by Mekanism's ultimate universal cable.

It seems to happen more when there is more cpu load on the server, but I was unfortunately unable to pinpoint more specific conditions how to reproduce.

### Any other comments?
 Crash-report: https://pastebin.com/wFSd2gBY
Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/322

**Comment by desht** [comment]
One of those problems that "shouldn't" happen, but does... I suspect some kind of race condition.  But it should be easy enough to add some extra checks for protection, I think.

**Comment by desht** [comment]
Fixed in 2.2.4 release (and 2.4.4 for MC 1.16.3)
