### ISSUE TITLE
[Feature Request] Mining Gadgets Integration

### ISSUE THREAD

**Issue by Tekstack** [TeamPneumatic/pnc-repressurized#631]
This request may be quite a stretch, and honestly, I understand, but could there be a way to add support for Direwolf20's Mining Gadget (https://www.curseforge.com/minecraft/mc-mods/mining-gadgets) for drones? I personally enjoy making drone quarries over traditional mods, and I'm always looking for ways to improve the world destruction. Parring PNC with this mod via upgrade or the drone recognizing the tool in the inventory could make for a very interesting quarry :P.

**Comment by desht** [comment]
Could be fun... I'll have a think about it and see if there's something interesting that can be added.

**Comment by desht** [comment]
Looking at this, what's really needed is a more general method of doing "right-click and hold" functionality with the Right Click Block progwidget.  Right now, the only support is for a one-shot click of the held item (or of the targeted block).

Not sure how feasible this would be too add, but it might be possible.  I will have a play when I get a chance.

Meanwhile (assuming you're on 1.16), have you played with the Pneumatic Jackhammer?  It's used more like a traditional pickaxe (left-click blocks to dig), and drones can make good use of them...

**Comment by Tekstack** [comment]
I am running 1.16, and I just started a fresh 'All The Mods 6' (v1.1.3b). I did not realize the Jackhammer had been added. I'll mess around with it for sure. Also, the direct support of the Mining Gadget isn't necessarily what I'm looking for after giving it some more thought, it really boils down to the upgradability of the tool. The main upgrades (and something like this may have been added since my last play through) are:

- the void upgrade -- this helps with ground clutter issues and garbage collection that I've ran into the past with large drone quarries. Basically I've found three solutions. First either have the collection drone(s) ignore cobble, dirt, etc. Second, the collection drone picks up everything and deposits filtered blocks into a trash can. Finally, have the collection drone deposit all into a dump chest for filtering that way. I've found that solution one can cause issues on servers with all the items that need to despawn. Maybe a void puzzle piece used with existing filter logic?

- the 3x3 (or more) mining area. This is not as big of a deal, but can make everything more efficient.

Everything else added by the tool can already be achieved with drones with some creativity.

**Comment by Tekstack** [comment]
Almost ready to give the new Jackhammer a whorl. Don't mind the mess, still early :P 
![Screenshot 2020-10-16 231530](https://user-images.githubusercontent.com/14859369/96327252-dcc96880-1005-11eb-9ee3-2d434254fa7e.png)
I have to say, though, I'm digging the new mechanics and the consolidation of the puzzle pieces. Great work.

**Comment by desht** [comment]
I do like the idea of a void puzzle piece...

**Comment by Tekstack** [comment]
Ok, I've had some time to mess around with the jackhammer (netherite drill bit), and that is an amazing tool with the drone. It's what I've been waiting on since I started using this mod a long time ago. One thing that I've noticed is:

-  I have a very simple dig routine set up, where the drone gets the jackhammer out of the charging station, mines (limited to 64 block interactions; seems to be about the sweet spot for air even with 25x volume upgrades due to the vein mine), then places the jackhammer back in to charge, and drone goes on standby. This works flawlessly if I chose 'closest' as the dig option, but if I chose lowest to highest, the drone appears to use up the 'block interactions' on the scan and never mines past the first row. My test quarry is 64x64x30. Ideally, mining from bottom up with the drones makes for a much smaller collection area needed for the collection drone and makes for a cleaner working area. I can get around this using relative cords and better checks to break out of the dig routine, but I'm unaware of how to break out of a dig routine without using relative cords and restarting the scan each time.
![Screenshot 2020-10-18 171442](https://user-images.githubusercontent.com/14859369/96386331-28942300-1168-11eb-99d3-7bde0eb59b2f.png)
![Screenshot 2020-10-18 171611](https://user-images.githubusercontent.com/14859369/96386333-292cb980-1168-11eb-8d67-82ff772c455a.png)

**Comment by desht** [comment]
Just to note that 2.4.5 (for MC 1.16.3) now has a "Void Item" widget which should work pretty much as you'd expect...

Finding out why a bottom-up dig isn't behaving itself is on my TODO list (although for "industrial strength" quarries, using variables to control the drone is generally a much better idea...).

**Comment by desht** [comment]
> but I'm unaware of how to break out of a dig routine without using relative cords and restarting the scan each time.

There's the "Limit Interactions" checkbox on the Dig progwidget; checking that allows you to specify the max number of blocks the drone will try to dig before moving on to the next widget.  Not sure if that's sufficient for your needs here, though.

**Comment by Tekstack** [comment]
I haven't had the chance to try out the Void piece yet, but below I've included 2 programs for you to mess around with (or anyone for that matter). The first being the Quarry Routine I've put together using relative cords and instruction within the program. The quarry program needs two jackhammers, charging station, and hopper to run (the hopper directed into the charging station to keep one jackhammer charged at all times; see screen shot below).
![Screenshot 2020-10-26 104246](https://user-images.githubusercontent.com/14859369/97188295-baf48200-1779-11eb-8c85-33876bc13c1f.png)

 I can say that it runs like a dream, and with some optimization, possibly the fastest quarry since I've been playing modded MC. It is scalable as well with multiple 'digger' drones, but this one is intended for one digger and two collector drones (separate program attached, pretty straight forward and cords will need to be adjusted)

![Screenshot 2020-10-26 104542](https://user-images.githubusercontent.com/14859369/97188528-fabb6980-1779-11eb-888c-adf36c3b520b.png)


>>>>Quarry Dig routine --- https://pastebin.com/L4A95ys4

>>>>Collection drones Sample --- https://pastebin.com/meDYg4PT

Thanks for Everything!

**Comment by desht** [comment]
Awesome, gonna have to try this out :)

**Comment by Tekstack** [comment]
This can be closed since the jackhammer now accomplishes the large majority of this unless your leaving it open for the ‘right click hold’ functionality for drones.
