### ISSUE TITLE
Universal Sensor not working for heat frame

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#632]
### Minecraft Version
1.15.2

### Forge Version
31.2.36

### Mod Version
pneumaticcraft-repressurized-1.15.2-1.5.0-76

### Describe your problem, including steps to reproduce it

I don't think the universal sensor is working with heat. The setup is like this.

![2020-10-13_16 29 04](https://user-images.githubusercontent.com/4198031/95875488-5b0ddc80-0d72-11eb-9489-0a6bc8e10fcc.png)

Should have a redstone signal
![2020-10-13_16 28 23](https://user-images.githubusercontent.com/4198031/95875504-5ea16380-0d72-11eb-8e92-600345c238fb.png)

Are negative temperatures valid?
![2020-10-13_16 27 26](https://user-images.githubusercontent.com/4198031/95875512-6103bd80-0d72-11eb-9b57-f259d71c3fc2.png)

### Any other comments?
The manual says that with a temperature of -100 you should have 100% chance of a second sheet of plastic, doesn't always give a second sheet of plastic. Does the temperature need to be near -100 or lower than -100?

**Comment by desht** [comment]
Yeah, the Heat Sensor only works for tile entities which provide a heat capability.  Heat Frames are entities which attach to a non-heat-handling tile entity (like the chest there), so the Heat Sensor isn't aware of those.

Having said that, it might not be too hard to add the ability for Heat Sensors to read a Heat Frame's temperature, so that could be a useful enhancement.

> The manual says that with a temperature of -100 you should have 100% chance of a second sheet of plastic, doesn't always give a second sheet of plastic. Does the temperature need to be near -100 or lower than -100?

Where does it say that?  Because it's an error if it does ;)  The best you'll get is 175% output (i.e. 75% chance of a second plastic) at -75C or below.

**Comment by desht** [comment]
Oh, and negative temperatures should work fine.  The temperature you supply in the text box is in Celsius.

**Comment by duncanwebb** [comment]
The text has changed, it was in the heat frame cooling when looking at the recipe for plastic sheet - now it has a limiter of 1.75.

I'd realized that the temps are in Celsius as the heat frame cools to -273. ;-)

I was thinking about a drone waiting for the inventory to be below 100 °C before placing a bucket of plastic in the inventory.

You know, I still don't know all the types of blocks that Minecraft has, is there a good description of them, like tile entity is?

**Comment by desht** [comment]
Tile entities are also known as block entities: https://minecraft.gamepedia.com/Block_entity

Basically any block with more complex data storage, and possibly also ticking behaviour. So pretty much any machines, and also chests which need to store an inventory. But not things like buttons, which just have a simple on/off state.

**Comment by desht** [comment]
1.5.1 release will add support for reading heat frame temperatures, and negative temperatures are supported (but note that the sensor will emit a signal when *above* -100, so your crafting will need to be started by a low signal from the Sensor).

**Comment by duncanwebb** [comment]
Many thanks and thanks for the link to tile entities. I'll give build 81 a test.

**Comment by duncanwebb** [comment]
Build 81 works.
