### ISSUE TITLE
[1.16.3] Crash Mod Loading has failed

### ISSUE THREAD

**Issue by Switch-Back18** [TeamPneumatic/pnc-repressurized#636]
### Minecraft Version
1.16.3
### Forge Version
34.1.19
### Mod Version
1.16.3-2.4.3-58
### Describe your problem, including steps to reproduce it
I had this mod in my modpack and the game can't run

the crash report write this

Thread: Render thread
Stacktrace:
	at me.desht.pneumaticcraft.common.thirdparty.ThirdPartyManager.discoverMods(ThirdPartyManager.java:93) ~[?:1.16.3-2.4.3-58] {re:classloading}
-- MOD pneumaticcraft --
### Any other comments?
Mod List: 
		rsrequestify-1.16.3-2.0.jar
		enchantedbookredesign-3.1a.jar
		ftbessentials-1603.1.0.7.jar
		NetherPortalFix_1.16.3-7.2.0.jar
		CraftingAutomat-MC1.16.3-1.2.2.jar
		forge-1.16.3-geckolib-2.1.2.jar
		ExtendedCrafting-1.16.3-3.1.1.jar
		Uppers-0.3.1.jar
		SilentMechanisms-1.16.3-0.8.3+67.jar
		modnametooltip_1.16.2-1.15.0.jar
		KleeSlabs_1.16.3-9.2.0.jar
		rsgauges-1.16.3-1.2.4.jar
		Neat+1.7-24.jar
		IronJetpacks-1.16.3-4.1.1.jar
		essentials-1.16.3-2.9.3.jar
		CookingForBlockheads_1.16.3-9.2.1.jar
		Controlling-7.0.0.8.jar
		ReAuth-1.16-Forge-3.9.2.jar
		Placebo-1.16.3-4.3.2.jar
		dankstorage-3.11.jar
		Powah-1.16.3-2.3.0.jar
		ftb-gui-library-1603.1.1.24.jar
		rangedpumps-0.8.2.jar
		jumbofurnace-1.16.3-2.1.0.0.jar
		culinaryconstruct-forge-1.16.3-4.0.0.1.jar
		Wither-Skeleton-Tweaks-1.16.3-5.2.1.jar
		Bookshelf-1.16.3-8.5.17.jar
		Tips-1.16.3-2.0.9.jar
		Reliquary-1.16.3-1.3.4.1015.jar
		u_team_core-1.16.3-3.1.10.183.jar
		randompatches-1.16.2-1.22.1.2.jar
		buildinggadgets-3.7.0.jar
		Apotheosis-1.16.3-4.3.1.jar
		MekanismGenerators-1.16.3-10.0.11.436.jar
		WaterStrainer-1.16.3-10.0.0.jar
		JustEnoughResources-1.16.3-0.12.0.100.jar
		ftb-teams-1.0.1.12.jar
		MysticalAgradditions-1.16.3-4.1.0.jar
		MmmMmmMmmMmm-1.16.3-1.0.0.jar
		refinedstorage-1.9.7.jar
		Industrial-Reborn-1.16.3-0.9.1.jar
		PrettyPipes-1.6.0.jar
		industrial-foregoing-1.16.3-3.1.1-a834e76.jar
		useful_backpacks-1.16.3-1.11.5.82.jar
		torchmaster-2.3.3-alpha.jar
		resourcefulbees-1.16.3-0.5.3b.jar
		crashutilities-3.5.jar
		BiomesOPlenty-1.16.3-12.0.0.409-universal.jar
		MekanismAdditions-1.16.3-10.0.11.436.jar
		Lollipop-1.16.3-3.2.0.jar
		ironfurnaces-1.16.3-2.4.0.jar
		ftb-ranks-1.0.0.7.jar
		mining_dimension-1.16.3-1.0.5.jar
		simplefarming-1.16.3-1.3.3.jar
		xercamod-1.16.3-1.1.jar
		SolarFluxReborn-1.16.3-16.2.3.jar
		curios-forge-1.16.3-4.0.2.0.jar
		Botania-1.16.3-407.jar
		Patchouli-1.16.2-44.jar
		collective-1.16.3-1.51.jar
		blockcarpentry-1.16.2-0.3.3.jar
		angelring-1.16.3-1.3.3.jar
		MysticalCustomization-1.16.3-2.1.0.jar
		elevatorid-1.16.3-1.7.6.jar
		Gobber2-1.16.3-2.3.13.jar
		ftb-ultimine-1.1.0.11.jar
		EnigmaticLegacy-2.6.1.jar
		Runelic-1.16.3-5.0.1.jar
		DarkUtilities-1.16.3-6.0.3.jar
		starterkit_1.16.3-2.1.jar
		MekanismTools-1.16.3-10.0.11.436.jar
		constructionwand-1.16.2-1.5.jar
		furniture-7.0.0-pre19-1.16.3.jar
		cc-tweaked-1.16.3-1.93.0.jar
		moreoverlays-1.18.9_PREVIEW_1-mc1.16.3.jar
		globalxp-1.16.3-v1.4.14.jar
		trashcans-1.0.3-mc1.16.3.jar
		woodcutter-1.3-1.16.3.jar
		bwncr-1.16.3-3.8.15.jar
		FastLeafDecay-v25.jar
		Cyclic-1.16.3-0.8.2.jar
		BetterAdvancements-1.16.3-0.1.0.102.jar
		ClientTweaks_1.16.3-5.2.0.jar
		doubledoors_1.16.3_2.1.jar
		Ma-Enchants-1.16.3-3.5.0.jar
		biggerreactors-1.16.3-0.1.2-beta.jar
		Cucumber-1.16.3-4.1.2.jar
		TrashSlot_1.16.3-12.2.0.jar
		mining-helmet-1.16.3-1.0.9.jar
		flatbedrock-1.16.3-1.1.3.jar
		woot-1.16.2-1.0.0.0.jar
		snad-1.0.2-1.16.3.jar
		item-filters-2.2.2.17.jar
		BetterThanBunnies-1.16.3-1.2.0.jar
		jei-1.16.3-7.6.0.49.jar
		kubejs-1603.2.8.72.jar
		metalbarrels-3.3a.jar
		Mekanism-1.16.3-10.0.11.436.jar
		caelus-forge-1.16.3-2.0.0.3.jar
		reap-1.16.3-1.0.2.jar
		colytra-forge-1.16.3-5.0.0.1.jar
		invtweaks-1.16.2-1.0.0.jar
		Clumps-6.0.0.11.jar
		fakeblocks-1.16.3-1.0.1.jar
		appliedenergistics2-8.1.0-alpha.3.jar
		NaturesCompass-1.16.3-1.8.5.jar
		SimpleStorageNetwork-1.16.3-1.1.2.jar
		DimStorage-1.16.3-4.2.1.jar
		BotanyPots-1.16.3-5.1.11.jar
		BotanyTrees-1.16.3-1.0.7.jar
		phosphophyllite-1.16.3-0.0.1-beta.jar
		engineerstools-1.16.3-1.1.0.jar
		FarmingForBlockheads_1.16.3-7.2.0.jar
		pneumaticcraft-repressurized-1.16.3-2.4.3-58.jar
		mcjtylib-1.16-5.0.9.jar
		rftoolsbase-1.16-2.0.5.jar
		xnet-1.16-3.0.7.jar
		rftoolsstorage-1.16-2.0.5.jar
		rftoolscontrol-1.16-4.0.5.jar
		ClickMachine-1.16.3-4.2.0.jar
		JEITweaker-1.16.3-1.0.1.4.jar
		mininggadgets-1.6.0.jar
		ars_nouveau-0.21.0.jar
		rftoolspower-1.16-3.0.7.jar
		ftb-chunks-1.1.2.36.jar
		forge-1.16.3-34.1.19-universal.jar
		Ceramics-1.16.3-1.5.1.jar
		scuba-gear-1.16.3-1.0.1.jar
		exp_bottling-1.16.3-5.jar
		MysticalAgriculture-1.16.3-4.1.0.jar
		ironchest-1.16.3-11.2.6.jar
		CraftingTweaks_1.16.3-12.2.0.jar
		forge-1.16.3-34.1.19-client.jar
		rftoolsutility-1.16-3.0.10.jar
		EnchantmentDescriptions-1.16.3-5.0.5.jar
		theoneprobe-1.16-3.0.4-beta.jar
		MouseTweaks-2.13-mc1.16.2.jar
		ToolBelt-1.16.3-1.15.1.jar
		titanium-1.16.3-3.1.0.jar
		ftb-quests-1603.0.2.2.jar
		ImmersiveEngineering-1.16.3-4.1.0-124.jar
		useful_railroads-1.16.3-1.4.4.31.jar
		SilentLib-1.16.3-4.8.1+61.jar
		pamhc2crops-1.16.3-1.0.1.jar
		Ding-1.16.3-1.2.0.jar
		LargeFluidTank-16.0.5.jar
		rftoolsbuilder-1.16-3.0.7.jar
		jeiintegration_1.16.3-6.0.0.8.jar
		Mantle-1.16.3-1.6.40.jar
		pamhc2foodcore-1.16.3-1.0.0.jar
		itemcollectors-1.0.6-mc1.16.3.jar
		gravestone-1.16.3-2.0.1.jar
		ftb-backups-2.1.1.6.jar
		FastWorkbench-1.16.3-4.4.0.jar
		polymorph-forge-1.16.3-0.15.jar
		StorageDrawers-1.16.2-8.1.0.jar
		DoubleSlabs-1.16-3.4.10.jar
		InventoryHud_1.16.x.forge-3.1.3.jar
		tubesreloaded-1.16.3-1.5.0.0.jar
		PickleTweaks-1.16.3-5.1.2.jar
		FastFurnace-1.16.3-4.3.0.jar
		AppleSkin-mc1.16.2-forge-1.0.14.jar
		engineersdecor-1.16.3-1.1.3-b1.jar
		connectedglass-1.0.6-mc1.16.3.jar
		RefinedRelocation_1.16.3-8.2.0.jar
		Aquaculture-1.16.3-2.1.1.jar Aquaculture 2
		refinedstorageaddons-0.7.2.jar
		extremeSoundMuffler-2.1.3_Forge-1.16.3.jar
		CosmeticArmorReworked-1.16.3-v1.jar
		overloadedarmorbar-5.1.0.jar
		morered-1.16.3-2.0.0.0.jar
		balancedenchanting-1.0.jar
		DefaultOptions_1.16.3-12.2.0.jar

**Comment by desht** [comment]
That is not a proper crash report.  Please paste the actual crash report on pastebin or similar and post a link here.

**Comment by Switch-Back18** [comment]
https://pastebin.pl/view/5e083a2b

**Comment by desht** [comment]
Yep, that's better, I can see what's happened now.  I'm surprised I haven't see a bug report on this before :(   Will get a new release out shortly.

**Comment by Switch-Back18** [comment]
Thanks You !

**Comment by Switch-Back18** [comment]
That's works thank you !
