### ISSUE TITLE
Crash with programmer

### ISSUE THREAD

**Issue by Darkere** [TeamPneumatic/pnc-repressurized#637]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.15
### Forge Version
/forge-1.15.2-31.2.36
### Mod Version
1.15.2-1.5.1-81
### Describe your problem, including steps to reproduce it
https://gist.github.com/Darkere/5605c922afbd0c36132733973b9692a8

**Comment by desht** [comment]
Er, oops.

**Comment by desht** [comment]
Fixed in 2.4.5 (MC 1.16.3) and 1.5.2 (MC 1.15.2)
