### ISSUE TITLE
Crash while attempting to plant Farmer's Delight rice with drones

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamPneumatic/pnc-repressurized#638]
### Minecraft Version
1.15.2

### Forge Version
1.15.2-31.2.36

### Mod Version
1.5.0.73

### Describe your problem, including steps to reproduce it
I had a drone attempting to plant a rice field. To save a little effort, I made my area selection larger than the fields so I could use it to also collect the drops later (since they tend to fall all over the place). Normally with vanilla or even modded crops this is not an issue. The drone will gracefully fail to place a crop if it's not properly tilled land and move on to the next block space.

In this case, it appears that the crash happens as soon as the drone attempts to place the rice in an invalid space (air). 

### Any other comments?
[crash-2020-10-18_09.51.01-server.txt](https://github.com/NillerMedDild/Enigmatica5/files/5397601/crash-2020-10-18_09.51.01-server.txt)

Relayed from: https://github.com/NillerMedDild/Enigmatica5/issues/530

**Comment by MuteTiefling** [comment]
To add a little to this, the Farmer's Delight Rice needs to be planted on dirt that's under 1 block of water. It then grows up one block out of the water to a total of 2 blocks tall. It's the placement that seems to be tricky here.

**Comment by desht** [comment]
Yeah, I see the problem.  `Block#getStateForPlacement()` can return null, and I'm not checking for that.  Easy fix, fortunately.

**Comment by desht** [comment]
Fixed in 2.4.5 (MC 1.16.3) and 1.5.2 (MC 1.15.2)

**Comment by NielsPilgaard** [comment]
Thanks!
