### ISSUE TITLE
Connected texture of the Pressure Chamber Glass are broken

### ISSUE THREAD

**Issue by MineMaarten** [TeamPneumatic/pnc-repressurized#64]
![2017-11-19_11 00 42](https://user-images.githubusercontent.com/5345405/32989624-2f0c8e1a-cd1a-11e7-9f59-08826accce1e.png)

**Comment by desht** [comment]
![2017-11-23_13 25 28](https://user-images.githubusercontent.com/736831/33174944-e88b3f5a-d051-11e7-898a-3ceb5a3d6b3f.png)

Looking better? :)

**Comment by MineMaarten** [comment]
It's looking great!
