### ISSUE TITLE
[1.16.3] Parsing error in any Assembly Line Drill recipe

### ISSUE THREAD

**Issue by baysupercool** [TeamPneumatic/pnc-repressurized#643]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

Minecraft Version: 1.16.3

Forge Version: 34.1.23

Mod Version: 2.4.5-62

I ran into this bug while trying to make a netherite drill bit, which uses the Drill program in Assembly Line. Drill recipes did not load. Then I took a look to the logs to find out if there is a loading error.

Error log  (redstone -> red dye as an example):
[recipe error.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5450926/recipe.error.txt)

Edit: Apparently related to #629 
It capitalizes "drill" as "DRİLL"

**Comment by desht** [comment]
Yep, same problem... me being careless about locales :(  Sorry about that.  Will be fixed in next release.

**Comment by desht** [comment]
Fixed in build 63 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ if you'd like to test.

**Comment by baysupercool** [comment]
Build 63 didn't work sadly :(
Also this only happens with assembly line drill recipes, even the refinery (which also has "i" in the word) works correctly.

**Comment by desht** [comment]
Sorry, build 64 should do it.

**Comment by baysupercool** [comment]
Build 64 works. 👍

**Comment by desht** [comment]
Fixed in 2.5.0 release
