### ISSUE TITLE
[Feature Request] Thermopneumatic Processing Plant (TPP) show its state with a comparator

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#645]
### Minecraft Version
1.15.2

### Describe your problem, including steps to reproduce it
It would be nice if the thermopneumatic processing plant behave similarly to the refinery. Attaching a comparator to the TTP would emit a redstone value when it has a valid recipe and enough space for the output. This would allow simple redstone control to control a vortex tube to be active when required. Similar to this

![image](https://user-images.githubusercontent.com/4198031/97472384-15443d00-194a-11eb-8a2f-0c25561bafa4.png)

Many thanks

**Comment by desht** [comment]
Give build 85 a go...

**Comment by duncanwebb** [comment]
Works a treat, checked both conditions.

**Comment by desht** [comment]
Fixed in 1.5.3 release
