### ISSUE TITLE
Cannot drag drone debugger program

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#646]
### Minecraft Version
1.15.2

### Forge Version
31.2.36

### Mod Version
pneumaticcraft-repressurized-1.15.2-1.5.2-85

### Describe your problem, including steps to reproduce it
Cannot drag the program in the drone debugger. This used to work is 1.12. Can follow the active widget and the program centres on the active widget.

![image](https://user-images.githubusercontent.com/4198031/97558407-5c7b0e00-19dc-11eb-84e4-88dd63b5757a.png)

### Any other comments?
This is useful for larger programs.

**Comment by desht** [comment]
Confirmed.  That got lost when the armor GUI code had a significant rewrite between 1.12 & 1.14.  Easy enough to restore, fortunately.

**Comment by duncanwebb** [comment]
Works fine now. Many thanks

**Comment by desht** [comment]
Fixed in 2.7.0 release (and 1.5.3 for 1.15.2)
