### ISSUE TITLE
Regulator Tube Module not working

### ISSUE THREAD

**Issue by ghost** [TeamPneumatic/pnc-repressurized#652]
Minecraft Version = 1.12.2
Forge Version = 8.0.99.99
Mod Version = 1.12.2-0.11.15-398

Describe your problem, including steps to reproduce it = The regulator tube module does not stop pressure, this is in both cases with PCB installed/not installed. To reproduce it, make any sort of pressure system and try to make a lower pressure zone with the regulator tube, the pressure just flows through it no matter what is it set to or what redstone input it has.

Any other comments? = I don't know if this is only exclusive to this mod. pls fix is possible
Edit: This is on a dedicated server

**Comment by desht** [comment]
Not aware of any regulator problems, but 1.12.2 isn't supported anymore, sorry.
