### ISSUE TITLE
Crash when entity tracker upgrade of helmet registers jukeboxes

### ISSUE THREAD

**Issue by Dasavanth** [TeamPneumatic/pnc-repressurized#661]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.4
### Forge Version
35.1.0
### Mod Version
2.6.2-73
### Describe your problem, including steps to reproduce it
client crash when PNC helmet registers jukeboxes with the entity tracker upgrade, i also had the hacking upgrade. this happened with 100% consistancy. it was a claimed chunk from ftbchunks mod. didnt test if that matters or not.

### Any other comments?
https://pastebin.com/sxnQvCMb - latest crash

**Comment by desht** [comment]
Fixed in 2.7.0 release
