### ISSUE TITLE
Transfer gadget not rendering

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#662]
### Minecraft Version
1.16.4

### Forge Version
35.1.4

### Mod Version
1.16.3-2.5.0-66

### Describe your problem, including steps to reproduce it

![image](https://user-images.githubusercontent.com/70091260/100618851-05db5980-3325-11eb-9b06-9756445a4beb.png)

The Transfer Gadget is not rendering. It appears invisible.

1. Place chest down
2. Place transfer gadget on chest
3. Note that the tile is invisible

Expected behavior: The transfer gadget should be visible, so the player can easily identify the gadget's current state (blue or orange).

### Any other comments?
I don't think this is related, but I am also using Client Tweaks, FPS Reducer, Mantle, More Overlays Updated and RandomPatches, which are the only mods that may affect rendering.

**Comment by desht** [comment]
Yeah, the Transfer Gadget rendering has been a bit broken since the port to 1.14.4...  It's actually next on my list to revamp, as it happens.

**Comment by HipHopHuman** [comment]
The latest release seems to have fixed this, having no isses, also the performance seems a lot smoother

**Comment by desht** [comment]
Excellent.  Closing now.
