### ISSUE TITLE
Liquids do not have any collisions.

### ISSUE THREAD

**Issue by ghost** [TeamPneumatic/pnc-repressurized#663]
### Minecraft Version
1.16.4
### Forge Version
35.1.3
### Mod Version
1.16.4-2.7.0-83
### Describe your problem, including steps to reproduce it
None of the custom liquids provided by this mod seem to have any collisions.

**Comment by desht** [comment]
Not a PNC problem, but a fundamental limitation of modded fluids in anything later than 1.12. Won't be fixed until the necessary support is in Forge.
