### ISSUE TITLE
Mod conflict with Ender Crop

### ISSUE THREAD

**Issue by SatyrRex** [TeamPneumatic/pnc-repressurized#664]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2

### Forge Version
14.23.5.2847

### Mod Version
0.11.15-398

### Describe your problem, including steps to reproduce it
Placing a gardening drone down next to fully grown Ender Seeds causes a crash once the path-finding of the drone initializes. I was able to re-load the world, pull out my pneumatic wrench and destroy the drone to continue playing on the world.

**Comment by desht** [comment]
Sorry, 1.12.2 is no longer supported.
