### ISSUE TITLE
Crash when clicking Aerial Interface w/ PNCR Manual Held

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#665]
### Minecraft Version
1.16.4

### Forge Version
35.1.4

### Mod Version
1.16.3-2.5.0-66

### Describe your problem, including steps to reproduce it

The game crashes when you right click an Aerial Interface that has a Requester Frame on it while holding the PNCR manual book.

1. Place down Aerial Interface
2. Attach Logistics Requester Frame to Aerial Interface
3. With manual in hand, right-click the Aerial Interface

### Any other comments?

Here's the crash log: https://gist.github.com/HipHopHuman/5ff1315c81fd84385e6776a7f9caddb4

**Comment by desht** [comment]
Update to 2.7.0 and see if it still crashes.  I can't supported old versions of the mod.

**Comment by HipHopHuman** [comment]
2.7.0 Doesn't seem to work. It's also marked as beta on CurseForge, as are all the versions before it with the exception of 2.5.0 which is marked as stable.

![image](https://user-images.githubusercontent.com/70091260/101015944-ca34cf80-3570-11eb-954a-0c9b44e77c64.png)

**Comment by desht** [comment]
Don't read too much into the alpha/beta/release status.  I need to see your logfile to have any idea what your datapack problem is.

**Comment by HipHopHuman** [comment]
Here you go: https://gist.github.com/HipHopHuman/172a0906e2977cc613b4b00ecce08ef7

It seems to be caused by a missing forge fluid tag for ethene and hydrogen - not sure what that means, are these even fluids in PNC? 

Seems to also be related to #666 (cursed issue number lol)

**Comment by desht** [comment]
Yeah, fluid tags for Mekanism fuel compat.  I'll get it fixed for 2.7.1, should have a dev build out soon though.

**Comment by desht** [comment]
Build 84 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ should fix the problem.

**Comment by desht** [comment]
Can you confirm that the 2.7.2 release fixed the Patchouli crash?

**Comment by HipHopHuman** [comment]
It seems to be fixed :D
