### ISSUE TITLE
Air grate tube module + Advanced PCB not respecting filter settings

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#667]
### Minecraft Version
1.16.4

### Forge Version
35.1.7

### Mod Version
1.16.4-2.7.2-86

### Describe your problem, including steps to reproduce it
An attracting air grate tube module upgraded with an advanced PCB is not respecting it's filter settings. If I set it to only attract "@item", it will still pull in nearby entities, including drones, mobs and crop supports.

1. Place down a creative compressor.
2. Set the compressor's pressure to -1 bar.
3. Attach an Advanced Pressure tube to the compressor.
4. Attach an Air Grate Tube Module to the Advanced Pressure Tube.
5. Right click the Air Grate Tube Module with an Advanced PCB.
6. Right click the Air Grate Tube Module with an empty hand to open the GUI.
7. Set the filter to "@item".
8. Using creative spawn eggs, spawn some peaceful mobs in range of the Air Grate.
9. Place a Crop Support in range of the Air Grate.
10. Deploy a Drone in range of the Air Grate.
11. Notice the Air Grate attracts all of these entities, as opposed to only attracting Items.

### Any other comments?
I have recorded a video of the issue to better illustrate what's going on, but the video will expire in a few weeks. You can see the video here: https://streamable.com/sx8its

**Comment by HipHopHuman** [comment]
Another observation: It seems to start working properly after re-logging.

**Comment by desht** [comment]
Confirmed, sort of.  I just tested on a dedicated server, and it didn't work when I first set it up, but worked when I adjusted the creative compressor's pressure a second time (didn't need to relog).  There is a sync problem there, by the looks of it - I'll take a look.

It also pulled all of my nearby crop supports out, which isn't ... ideal.   I need to make semiblocks (crop supports, logistics frames, transfer gadgets etc.) completely immune to the air grate.

**Comment by desht** [comment]
So the problem was, when you edit the filter text in the GUI, it sends it to the server, but neglects to set it locally on the client.  And the entity pulling code runs on both sides... very easy fix, fortunately.

**Comment by desht** [comment]
Build 87 has the fix, if you'd like to test.

**Comment by HipHopHuman** [comment]
That makes sense. I noticed some weirdness there where setting the text wouldn't actually save the text. I had to edit it in multiple times for it to persist, but I thought it was just weirdness on my instance because I was having unrelated issues with clicks not registering. Glad to hear the fix is easy.

**Comment by HipHopHuman** [comment]
Tested build 87 and it works a lot better!
