### ISSUE TITLE
Camouflaged Elevator Base Rendering Artefacts

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#675]
### Minecraft Version
1.16.4

### Forge Version
35.1.7

### Mod Version
Build 88

### Describe your problem, including steps to reproduce it

Camouflaged elevator bases have strange rendering artefacts that make them appear as if they have no blocklight. 

All of the elevator bases in the below image should look like Sandstone. problem persists after F3+T and a client restart.

![image](https://user-images.githubusercontent.com/70091260/101418449-994cf580-38f6-11eb-9751-b65a2ac3539f.png)

**Comment by desht** [comment]
Yep, I'm aware of that, and spent a lot of time not finding out why it happens. I suspect it originates in a vanilla problem. However I've found that reloading the client world has always fixed it for me .

Generally I find it happens if a camo'd block gets a block update, so the workaround is to fully build all the bases and only then apply the camo.

**Comment by HipHopHuman** [comment]
> I've found that reloading the client world has always fixed it for me .

I thought about that and tried it as well, I guess I am not so lucky because that didn't fix it :s 

> Generally I find it happens if a camo'd block gets a block update, so the workaround is to fully build all the bases and only then apply the camo.

I did, I must have triggered a block update afterwards somehow. Probably when I was messing w/ the door bases

**Comment by desht** [comment]
Think I've come up with a slightly ugly hack to get round the problem...

**Comment by desht** [comment]
Build 89 "fixes" this problem.  Bit of a hack, but it works.

**Comment by HipHopHuman** [comment]
This looks much better, although I am experiencing FPS drops while riding an elevator in singleplayer now, and have noticed a few incidents where the player gets "stuck" underneath the elevator platform while travelling up - however I can't seem to consistently trigger this bug. I'll keep testing

**Comment by DraGonFiirE** [comment]
Ive noticed the falling through the elevator platform bug sometimes aswell

**Comment by desht** [comment]
I've never, ever, fallen through an elevator platform.  Not once.

If it does happen, I need to know your *exact* elevator setup - elevator height, number of speed upgrades etc., and also what gear you were wearing at the time (e.g. if you have Pneumatic Armor on, don't have your jet boots switched on, same applies to other flying items).

Also seeing no FPS issue in single player.  The change I made just has the elevator check the light level of a neighbouring block every couple of seconds (client side only), which would not cause FPS drops.

**Comment by HipHopHuman** [comment]
The falling through isn't a consistent thing, I don't see a reliable way of forcing it to happen, but it does sometimes happen. The elevator setup is the same elevator as in the OP, 3x3, four floors, each floor being 3 blocks tall, the elevator bases are stacked 3 high to accommodate the 4th floor and room for extra floors. No upgrades, not wearing any gear, running at 20 bar.

I'll try to get a performance profile + video of FPS drops here soon, just have a busy weekend so may take a bit, also I haven't checked if this is an issue in build 91 as I know you've done some elevator changes there, so I'll have to confirm it first

**Comment by desht** [comment]
Do you have any charging upgrades in your elevator, by chance?  I just spotted & fixed a bug where the upgrade count wasn't always sync'd to the client, meaning client/server disagreed about the descent rate of the elevator, causing jerky behaviour for the player on the elevator.  That fix will be in the next build.

Also included will be some elevator optimisations which should help performance in general (smarter caching of tile entity positions for a lot less block scanning).  Just testing those now to ensure there aren't any caching issues.

**Comment by HipHopHuman** [comment]
Good spot but to answer your question, no, there were no upgrades in the elevator at all

**Comment by desht** [comment]
Build 93 includes the elevator fixes I mentioned; may or may not help with your noticed performance issues.

**Comment by desht** [comment]
Fixed in 2.8.0 release

(if performance problems are persisting and you have more information, please raise a new issue)
