### ISSUE TITLE
Suggestion: "Iron Door" mode for Pneumatic Door Base

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#676]
Right now there are 3 modes:

- Player nearby
- Player nearby and looking
- Wooden Door

The wooden door mode is nice for more granular redstone control, but the door can still be right-clicked to open/close. I suggest an "Iron Door" mode that behaves exactly like the wooden door mode, but without the click behavior - i.e. it works only via redstone, just like an iron door.

**Comment by desht** [comment]
Well that turned out to be really easy :)  Build 89.

**Comment by HipHopHuman** [comment]
It works beautifully! Thanks :D

**Comment by desht** [comment]
Fixed in 2.8.0 release
