### ISSUE TITLE
Transfer Gadget on "Up" face prevents attaching further Transfer Gadgets

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#677]
### Minecraft Version
1.16.4

### Forge Version
35.1.7

### Mod Version
Build 88

### Describe your problem, including steps to reproduce it

I cannot attach Transfer Gadgets to an inventory if there is already a Transfer Gadget on the "Up" face.

1. Place a chest, barrel, furnace or another inventory in the world.
2. Attach a Transfer Gadget to the top/up side of the inventory.
3. Attach a Transfer Gadget to any other side of the inventory.

**Expected Behavior**: The Transfer Gadget should attach.
**Actual Behavior**: Nothing happens.

### Any other comments?
This only happens when there is a Transfer Gadget is on the "Up" side of the inventory. You can still attach many Transfer Gadgets, just as long as you place the "Up" transfer gadget last.

**Comment by desht** [comment]
Confirmed & fixed in dev.

**Comment by HipHopHuman** [comment]
Fix tested and working :)

**Comment by desht** [comment]
Fixed in 2.8.0 release
