### ISSUE TITLE
Amadrone market limited stock

### ISSUE THREAD

**Issue by DevTimur** [TeamPneumatic/pnc-repressurized#683]
### Minecraft Version 1.12.2
Not sure if you still support 1.12.2 version, but maybe you will like this feature, and will add it to other version.

How about to implement a limited stock/request for amadron market. I mean, you can set up in config how much of items buyer could buy, and then just replace this position with another random position.

**Comment by desht** [comment]
1.12.2 is not supported anymore but I'm open to feature requests for 1.16.4 (1.15.2 is bugfixes only).

I would not want to do this for core, static, offers - like PCB Blueprints or Assembly Programs.  Those are vital for progression, so need to be always available (although they can be removed by mods like KubeJS, but then it's up to the modpack maker to provide an alternative).

For periodic trades (villager offers & datapack-defined periodic trades), this could be an option, but they get reshuffled anyway once per Minecraft day, by default.  Limits, if they were to be added, would be probably need to be based on the rarity of the trade (1 - 5), with very rare trades maybe only allowing one item to be bought before it went unavailable.

I will consider this for a future 1.16 (or maybe 1.17) release, but nothing will be going into 1.12.2, sorry.

**Comment by desht** [comment]
Added in 2.9.1
