### ISSUE TITLE
Crash on login to server

### ISSUE THREAD

**Issue by Divineaspect** [TeamPneumatic/pnc-repressurized#684]
### Minecraft Version
1.16.4

### Forge Version
forge version 35.1.11

### Mod Version
pneumaticcraft-repressurized-1.16.4-2.8.0-95.jar

### Describe your problem, including steps to reproduce it
Crash on login to server

### Any other comments?
Crash Report
https://pastebin.com/eXnxNT8v

**Comment by belathus** [comment]
We're playing on the same server. We ended up reverting back to 2.7.2-86 for now, where this crash doesn't exist.

**Comment by desht** [comment]
Client crash, triggered by Minecolonies (which I don't have in my test world), but something I can fix, I think.  Stand by for a dev build...

**Comment by desht** [comment]
Fixed in 2.8.1 release
