### ISSUE TITLE
[Feature Request] Coordinate Operator Min/Max mode improvement

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#687]
Would it be possible to have the min/max mode of the coordinate operator just affect specific coordinates?

What I was trying to set a coordinate based on the drone position (the program controller) and wanted to set the Y position to 127 and leave the other coordinates alone. Using 0, 127, 0 didn't give the desired result.

Don't know of an algorithm to achieve this with multiply/divide add/subtract.

**Comment by desht** [comment]
Added in 2.8.2 release
