### ISSUE TITLE
[Feature Request] Add item to filter of  smart chest

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#688]
### Minecraft Version
1.16.4

### Forge Version
35.1.13

### Mod Version
pneumaticcraft-repressurized-1.16.4-2.8.1-96

### Describe your problem, including steps to reproduce it
Add an item to a smart chest by Alt-Left-Clicking the item on to a locked slot. We can lock slots with Alt-Left-Clicking the slot and all slots to the right will be locked. I would like to be able to replace an empty locked slow with an item while items are being fed through the smart chest.

The reason is to allow new items to be added to the list of locked items without taking the tools from the program controller

### Any other comments?
I get a crash sometime when trying this, this is why the version numbers are here.
[crash-2020-12-21_17.19.03-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5725359/crash-2020-12-21_17.19.03-client.txt)

**Comment by desht** [comment]
Added in 2.8.2 release
