### ISSUE TITLE
Crashing when teleporting

### ISSUE THREAD

**Issue by JalterPlays** [TeamPneumatic/pnc-repressurized#689]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.4
### Forge Version
forge-35.1.13
### Mod Version
pneumaticcraft-repressurized-1.16.4-2.7.2-86
### Describe your problem, including steps to reproduce it
When teleporting away from an area with pneumaticcraft stuff casuses the client to crash.
### Any other comments?
https://pastebin.com/fYFcsCsB

**Comment by desht** [comment]
Please try this again with v2.8.1 of the mod (although it's listed as beta, it should be pretty stable).  The elevator has been significantly reworked in 2.8.0.

**Comment by desht** [comment]
Closed due to lack of response.
