### ISSUE TITLE
Memory stick auto-collect randomly stops working, then never works again.

### ISSUE THREAD

**Issue by Nightcaste** [TeamPneumatic/pnc-repressurized#691]
### Describe your problem, including steps to reproduce it
Craft Memory Stick
Activate Auto-Collect with a left-click.
Keep memory stick in your inventory, or hotbar, or curio slot (doesn't seem to matter)
Memory stick will automatically collect XP, until it doesn't, and then it never will again.  You can still *manually* put xp into it, but auto-collect can not be made to function in any way that I have been able to find.

### Any other comments?
As I said earlier, I've been having this problem since a pack called Open DevCraft 7, which was a 1.14.4 pack.  Currently having this problem in Enigmatica 6 3.2

**Comment by desht** [comment]
Not seen this happen myself, but I'll keep an eye out for it.

**Comment by desht** [comment]
This is hopefully fixed in build 98 (will be in upcoming 2.8.2 release).  I have redone the way memory sticks are found in the inventory quite a bit (which should also reduce server CPU time a bit, much less inventory scanning needed).

**Comment by desht** [comment]
Fixed in 2.8.2 release (hopefully).  Feel free to reopen if you see this problem again.

**Comment by Nightcaste** [comment]
I will be waiting for a pack update that brings this in, but I'll try to remember to report what happens.

Also, I think I have an idea what might be causing it.  I have a backpack from Sophisticated Backpacks.  The memory stick stopped working when I put the backpack in a curio slot.  It seems almost like they're competing for which item collects what stuff from the environment.

I will un-equip the backpack and see if the memory stick starts working again.
