### ISSUE TITLE
[1.16.4] Memory Stick Experience Dupe

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamPneumatic/pnc-repressurized#693]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.4

### Forge Version
1.16.4-35.1.13

### Mod Version
1.16.4-2.8.1-96

### Describe your problem, including steps to reproduce it
The Memory Stick is stackable, so when 64 memory sticks are in the hotbar and xp is picked up, it is duplicated x64

### Any other comments?
I propose making the memory stick unstackable, and perhaps check if there are multiple in the inventory/curio slots.

Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/623

**Comment by desht** [comment]
Oops, yeah, for definite.  Will be unstackable in the next release.

**Comment by desht** [comment]
Fixed in build 98

**Comment by desht** [comment]
Fixed in 2.8.2 release

**Comment by NielsPilgaard** [comment]
Thanks!
