### ISSUE TITLE
Relative coodinate drone program no longer working

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#694]
### Minecraft Version
1.16.4

### Forge Version
35.1.13

### Mod Version
pneumaticcraft-repressurized-1.16.4-2.8.2-98

### Describe your problem, including steps to reproduce it

The program is https://pastebin.com/3bM3vUxq

This how it should work
https://user-images.githubusercontent.com/4198031/103155418-0ccc7f00-47a0-11eb-85c0-cdbe952f759e.mp4

This is what is happening
https://user-images.githubusercontent.com/4198031/103155416-0b02bb80-47a0-11eb-8e88-882191fbb8bf.mp4

### Any other comments?
pneumaticcraft-repressurized-1.16.4-2.8.1-96 program was working

**Comment by desht** [comment]
Hmm, I broke something in the coord operator commit. Will take a look tomorrow...

**Comment by desht** [comment]
This is fixed in build 100, dumb missing brackets error.

**Comment by desht** [comment]
Fixed in 2.8.2 release
