### ISSUE TITLE
 Failed to get the pneumaticWrenchCharged advancement

### ISSUE THREAD

**Issue by torndar** [TeamPneumatic/pnc-repressurized#695]
### Minecraft Version
1.16.4

### Forge Version
?

### Mod Version
2.7.2-86

### Describe your problem, including steps to reproduce it
Failed to get the pneumaticWrenchCharged advancement. I suspect since the check is for a specific volume of air `"nbt": "{\"pneumaticcraft:air\":30000 }"` that it missed it charging past that so I didn't get the advancement.

**Comment by desht** [comment]
30000 is the max air that can be stored, so shouldn't be possible to go past.  Although that does mean 10 bar, so tier 2 compressors required.  I might use a custom advancement condition there and allow any pressure over (say) 1 bar.

**Comment by torndar** [comment]
I'd figured 30000 was 3 bar (nice multiple of 10 scenario) so I didn't consider the case of not having gotten the pressure high enough. That explains why I couldn't get the advancement to trigger.

I'd be fine with gating it behind making one of the advanced compressors. That said having it available right away does help make it clear that it needs to be charged before use which helps with learning the mod. I'm curious to see how the custom advancement would work as I couldn't figure out how to change the current condition to a "greater than or equal". The documentation I could find on advancements wasn't great.

**Comment by desht** [comment]
OK, it'll now trigger at >= 3 bar, which makes more sense.  I didn't really intend for this advancement to require tier 2 pressure.

I used a custom advancement here, triggered from `ItemPneumaticWrench#inventoryTick()` - code's all in the commit, but if you have any questions, feel free to ask.  Discord is probably the best place: https://discord.gg/Zf5XwbfBRj

**Comment by desht** [comment]
Fixed in 2.8.2 release
