### ISSUE TITLE
PCB Duplication with Mekanism

### ISSUE THREAD

**Issue by phit** [TeamPneumatic/pnc-repressurized#696]
### Minecraft Version

1.16.4

### Forge Version

1.16.4 - 35.1.15

### Mod Version
pneumaticcraft-repressurized-1.16.4-2.8.1-96.jar
Mekanism-1.16.4-10.0.18.445.jar

Modpack is FTB's Direwolf20 1.16 version 1.1.2

### Describe your problem, including steps to reproduce it

extracting PCBs from uv light box with mekanisms advanced logistical cable gives you two instead of one

image of setup

![image](https://user-images.githubusercontent.com/2097483/103180292-c86edb00-4894-11eb-8c1d-a8995330809a.png)

**Comment by desht** [comment]
Debugging this confirms it's a Mekanism bug.  `TileEntityUVLightBox.UVInvWrapper#extractItem()` (https://github.com/TeamPneumatic/pnc-repressurized/blob/1.16.4/src/main/java/me/desht/pneumaticcraft/common/tileentity/TileEntityUVLightBox.java#L319) is correctly returning a stack of a single PCB to Mekanism's `TileTransitRequest.TileItemData#use()` method.  But for some reason, 2 PCB's get transferred via the Logistical Transporter to the target inventory.

**Comment by desht** [comment]
Actually, might not be a Mekanism issue...

Update: confirmed, subtle bug in the UV output handler led the Mek transporter to believe there were 2 PCB's to extract.  Will be fixed in next PNC release.

**Comment by desht** [comment]
Fixed in 2.8.2 release
