### ISSUE TITLE
Issue with Armor Set

### ISSUE THREAD

**Issue by p33fn00d3r** [TeamPneumatic/pnc-repressurized#698]
### Things I made are just randomly disappearing , specifically under the Armor, first my chestplate disappeared along with the upgrades when I dismantled the charging stations I had set up with my armor pieces in them, everything was accounted for except for the chestplate, after remaking my armor i started upgrading the armor again, and recently upgrades I made also randomly disappeared as they were equipped to my boots inside the charging station , I had the speed upgrades , the jet boots III , and armor upgrades already installed, when i added the life upgrade, the jet boots just disappeared from the upgrades, and they didnt go into my inventory or anything , I pressed middle click which is the hotkey for my auto sorting mod, and the upgrades that i have already installed just disappeared, does middle click do something else in this mod ? 
is there something wrong with the mod cause i am just flabbergasted and running out of resources to keep re-making everything I made

**Comment by desht** [comment]
No idea, sorry. Never ever seen any of the behaviour you are describing. And no, middle click had no special handling.
