### ISSUE TITLE
Maybe a bug about Creative Compressor

### ISSUE THREAD

**Issue by SihenZhang** [TeamPneumatic/pnc-repressurized#70]
Minecraft Version: 1.12.2
Forge Version: 14.23.0.2552
Mod Version: 0.1.0-70
Singleplayer/Multiplayer: Singleplayer
IndustrialCraft Version: 2.8.27-ex112

Additional Information:
* At first, I find this bug will happen only when a Creative Compressor connect with a Pneumatic Generator.
* First of all, the Pneumatic Generator and the Creative Compressor are both 0 bar.
* And then, add the pressure, both of the "+" buttons are okay. (For example, add to 8.0 bar. So sorry that I'm using Chinese.)
![](https://i.imgur.com/wkO2JVi.png)
* Then, reduce the pressure by "-1" button. Here is the problem. The pressure is reduced to 7.2 bar but not 7.0 bar.
![](https://i.imgur.com/QDSfjhA.png)
* Continue reducing pressure by "-1" button. The pressure is 6.2 bar. (Now the "-1" button is okay.)
![](https://i.imgur.com/cayfIoH.png)
* Reduce the pressure by "-0.1" button. The pressure is reduced to 5.9 bar but not 6.1 bar,
![](https://i.imgur.com/XzMg7MW.png)
* Continue reducing pressure by "-0.1" button. The pressure is 5.8 bar. (Now the "-0.1" button is okay.)
![](https://i.imgur.com/70SyTw1.png)
* Reduce the pressure by "-1" button. The pressure is reduced to 5.0 bar but not 4.8 bar. (So it is bug again.) (And the bug will loop just like above.)
![](https://i.imgur.com/DYE0HnW.png)
* Now add the pressure by "+1" button. The pressure is added to 5.8 bar but not 6.0 bar.
![](https://i.imgur.com/yRyIUAA.png)
* Continue add pressure by "+1" button. The pressure is added to 6.8 bar. (Now the "+1" button is okay.)
![](https://i.imgur.com/G4cL7ff.png)
* Now add pressure by "+0.1" button. The pressure is 6.9  bar. (It is okay.)
![](https://i.imgur.com/KXElnw6.png)
* Now add pressure by "+1" button. The pressure is 7.9 bar. (It is still okay.)
![](https://i.imgur.com/bZ9jnKJ.png)
* I try to use other machines to reproduce this bug. And I find **Elevator Base**, **Universal Sensor**, **Aerial Interface**, **Programmable Controller**, **Gas Lift**, **Thermopneumatic Processing Plant** will have the similar situation.

So I was confused. ***Is this a bug or not?***

**Comment by desht** [comment]
Hmm, not sure if it's a bug, but I will do some testing on this. The creative compressor does work a little oddly compared with any other compressor.
