### ISSUE TITLE
[Documentation Update] Drone Charging

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#700]
It seems that the manual entries for basic drones only point out that they'll seek out a charging station if low on air. These entries don't mention the requirement for a dispenser upgrade.

When following the link to the Charging Station, it doesn't specifically that the 'charge pad' mode charges drones, only items and players.

This has apparently led to some confusion with some players. 

I'd suggest each of the non smart drones either get a page about auto charging, just like the programmable drones do. Or the entry on the charge pad be expanded to specifically mention drones as well.

**Comment by desht** [comment]
Fixed in 2.9.0 release
