### ISSUE TITLE
Ticking Particle Crash when removing Elevator Bases

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#701]
### Minecraft Version
1.16.4

### Forge Version
35.1.28

### Mod Version
pneumaticcraft-repressurized-1.16.4-2.8.3-104

### Describe your problem, including steps to reproduce it
Using the Pneumatic Wrench to remove an elevator caused the crash

### Any other comments?
I could have been using mod version pneumaticcraft-repressurized-1.16.4-2.8.1-96. Not sure how to fix the world save to remove this entry.

[crash-2021-01-01_14.02.56-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5758954/crash-2021-01-01_14.02.56-client.txt)

**Comment by desht** [comment]
392bd681557dddee7b436e0887b38fe1ca42ca23

**Comment by desht** [comment]
Build 106 should sort that out

**Comment by duncanwebb** [comment]
It fixed the ticking particle. Now there is a ticking entity on a drone.
[crash-2021-01-01_14.45.40-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5758996/crash-2021-01-01_14.45.40-server.txt)

**Comment by desht** [comment]
Oops!  Build 107 for that one.  Thanks for being a good beta tester :)

**Comment by duncanwebb** [comment]
Works a treat. Thanks for fixing the bugs so fast.

**Comment by desht** [comment]
Fixed in 2.9.0 release
