### ISSUE TITLE
Can place redstone on liquid compressors but not the advanced version

### ISSUE THREAD

**Issue by torndar** [TeamPneumatic/pnc-repressurized#703]
### Minecraft Version
1.16.4

### Forge Version
35.1.15

### Mod Version
2.8.2-101

### Describe your problem, including steps to reproduce it
I can place redstone on top of regular liquid compressors but not the advanced compressors.

![image](https://user-images.githubusercontent.com/1268782/103485122-36019680-4dc2-11eb-8d53-fd7853cd68e4.png)

**Comment by desht** [comment]
Fixed in 2.9.0 release
