### ISSUE TITLE
Drone fakePlayer name includes serialized TextComponent 

### ISSUE THREAD

**Issue by telemenar** [TeamPneumatic/pnc-repressurized#706]
### Minecraft Version
1.16.4

### Forge Version
35.1.29

### Mod Version
pneumaticcraft-repressurized-1.16.4-2.9.0-111

### Describe your problem, including steps to reproduce it
Drone fakePlayer name includes serialized TextComponent 
Example:
e6665b1e60ad4cee8ca0203cf34cf40f-TextComponent{text='telemenar', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}_drone

This causes all kinds of interesting errors. Like packet too long errors that cause the FTB Teams UI to fail to display at all.

Also this error:
[22:41:24] [Server thread/INFO]: [com.feed_the_beast.mods.ftbchunks.impl.ClaimedChunkManagerImpl:serverSaved:144]: java.nio.file.FileSystemException: ./world/data/ftbchunks/e6665b1e60ad4cee8ca0203cf34cf40f-TextComponent{text='telemenar', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}}_drone.json: Filename too long

I think the fix is really simple:
https://github.com/TeamPneumatic/pnc-repressurized/blob/6bc9c10d6d90aeea697592cc2bdeb1b5f10a0918/src/main/java/me/desht/pneumaticcraft/common/entity/living/EntityDrone.java#L1001

I /think/ it will be fixed if that line ownerName.getString()

**Comment by desht** [comment]
Yeah that's down to annoying change in vanilla between 1.15 and 1.16. Thought I'd caught all those but clearly not.

**Comment by desht** [comment]
Build 112 should fix this, and more: drone fake players should now have exactly the same rights as the owning player.

However, note that this build does require Forge 34.1.36 or newer (latest at time of writing).

**Comment by desht** [comment]
Fixed in 2.9.1
