### ISSUE TITLE
Claiming FTB Chunks blocks mining drones

### ISSUE THREAD

**Issue by torndar** [TeamPneumatic/pnc-repressurized#707]
### Minecraft Version
1.16.4

### Forge Version
35.1.15

### Mod Version
2.8.2-101

### Describe your problem, including steps to reproduce it
Claiming chunks using the FTB Chunks tool in the Direwolf 20 1.16 pack blocks mining drones from being able to break blocks. I don't need to claim them but I want to chunk load them and I haven't found a way to do that without claiming them first. The drones know who placed them, can that be used to allow them to break blocks?

**Comment by Tekstack** [comment]
I believe @desht is working on a fix that should solve this issue in a later build, but a temporary workaround I found for a similar issue on a ATM 6 server I was hosting was to disable land protection in the ftb-chunks config if possible. 
![Screenshot_20210108-143806_Edge](https://user-images.githubusercontent.com/14859369/104115050-07f7e700-52d9-11eb-9d5d-9de2f5ae480d.jpg)

**Comment by desht** [comment]
Yeah, this should be completely fixed in the 2.9.1 release, coming very soon. I just need to do some more testing with it, but drones have no problem with claimed chunks in my test world.

**Comment by desht** [comment]
If you'd like to beta test the fix, you can try build 112 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ - as always, make a backup of your world if you do that.  Also, you will need Forge 35.1.36 or later.

**Comment by desht** [comment]
Fixed in 2.9.1
