### ISSUE TITLE
Attempting to view info on Condition: Item Filter causes CTD (crash to desktop)

### ISSUE THREAD

**Issue by SaintElimine** [TeamPneumatic/pnc-repressurized#708]
Minecraft Version
1.16.4

Forge Version
35.1.13

Mod Version
1.16.4-2.8.1-96

Describe your problem, including steps to reproduce it
Playing a slightly modified version of Enigmatica 6 (added Wyrmroost server side and using Xaero World+Minimap client side). In the programming table interface, attempting to view the help info on the widget 'Condition: Item Filter' causes a crash to desktop (happens both when pressing I or middle clicking the widget). The error presents as 'mouseClicked event handler' or 'keyPressed event handler' depending on which triggers the crash. I've attached error logs for both.

[crash-2021-01-10_17.33.50-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5793697/crash-2021-01-10_17.33.50-client.txt)
[crash-2021-01-10_17.42.56-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5793698/crash-2021-01-10_17.42.56-client.txt)

**Comment by desht** [comment]
Fixed in 2.9.1
