### ISSUE TITLE
GPS area tool and global variables 

### ISSUE THREAD

**Issue by torndar** [TeamPneumatic/pnc-repressurized#709]
### Minecraft Version
1.16.4

### Forge Version
35.1.15

### Mod Version
2.8.2-101

### Describe your problem, including steps to reproduce it

I cannot set global variables using a GPS area tool (regular GPS tool appears to work correctly) on a single player or server hosted map. The chat message show the proper coordinates but a get_global_var command and reopening the tool both show it as 0,0,0. I can set it via the set_global_var command though and the GPS tool updates to match that. The regular GPS tool works and the values it sets for variables with the same name as area tool variables shows up in those like with the set command.

This seems similar to https://github.com/TeamPneumatic/pnc-repressurized/issues/217 but with global variables involved.

**Comment by desht** [comment]
Fixed in 2.9.1
