### ISSUE TITLE
Items in Pressure Chamber can be output infinitely by Thermal Dynamics

### ISSUE THREAD

**Issue by SihenZhang** [TeamPneumatic/pnc-repressurized#71]
Minecraft Version: 1.12.2
Forge Version: 14.23.0.2554
Mod Version: 0.1.0-71
Singleplayer/Multiplayer: Singleplayer
Thermal Dynamics Version: 2.3.6.13-universal

Additional Information:
* This bug ***only*** happen when using pipes of Thermal Dynamics to transport items. Transfer Node (Extra Utilities 2) and Wooden Pipe (Buildcraft) don't have this situation.
* When there are some(64) compressed iron in the Pressure Chamber Interface and then connect the output side of Interface with a container using pipes of Thermal Dynamics. The items in the Interface will be output infinitely while the Interface has no change,
![](https://i.imgur.com/UOkYdLo.png)
![](https://i.imgur.com/UeUZ4dA.png)
* When breaking the Pressure Chamber, it will stop outputing. However, when the Pressure Chamber formed again, the item will continue outputing.
* Though the Pressure Chamber is 0 bar, it still can output items infinitely.

**Comment by desht** [comment]
Well that's not good :)

Which type of Thermal Dynamics duct and servo did you test with? (and what servo settings? i.e. how many items at a time)

**Comment by SihenZhang** [comment]
Any kind of Itemducts and no servo or retriever can do this. The items will be automatically output. But once using servo or retriever, this bug will not happen.

**Comment by desht** [comment]
Yeah the interface was pretty buggy!  Fixed now.
