### ISSUE TITLE
Enderman chases 0,0 instead of drone on being attacked

### ISSUE THREAD

**Issue by xRebellion** [TeamPneumatic/pnc-repressurized#710]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.4
### Forge Version
35.1.36
### Mod Version
2.9.0-111

### Describe your problem, including steps to reproduce it
Whenever my drone attacks an enderman, the enderman tries to go to 0,0 (I think) instead of chasing the drone. This creates a problem where my drone keeps chasing them and goes too far away.

**Comment by desht** [comment]
Hmm, guessing the drone's fake player's position hasn't been initialised.  Should be easy enough to fix by just keeping it updated to the drone entity's position each tick, but I'll do some experimentation on it.

**Comment by desht** [comment]
Fixed in 2.9.2
