### ISSUE TITLE
Fluid Hopper pushed all the fluid out

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#711]
### Minecraft Version
1.16.4
### Forge Version
35.1.36
### Mod Version
pneumaticcraft-repressurized-1.16.4-2.9.0-111
### Describe your problem, including steps to reproduce it
When removing a tank connected over a fluid hopper that had a dispenser upgrade and the mode is set to leave 1000mb in tank to filter the last bucket was pushed out into the world.

![image](https://user-images.githubusercontent.com/4198031/104445668-aca84c00-5599-11eb-92d5-95b22d8fad3b.png)

### Any other comments?
Not sure how to reproduce this, when I test, before breaking the tank the fluid hopper has 1000mB, and after it has less 400-600mB so it doesn't always have the bucket in the tank.

**Comment by desht** [comment]
Fixed in 2.9.2
