### ISSUE TITLE
Item Life Upgrade Isn't Working on Armor

### ISSUE THREAD

**Issue by Naphrym** [TeamPneumatic/pnc-repressurized#713]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version 
1.16.4

### Forge Version 
35.1.13

### Mod Version 
1.16.4-2.8.1-96

### Describe your problem, including steps to reproduce it
The Item Life Upgrade is meant to repair armor using air pressure, but I haven't noticed it do that at all. I have maxed-out Volume Upgrades (x25) on all of my armor, maxed out Armor Upgrades (x4), and maxed out Item Life Upgrades (x5). All armor pieces are full.
### Any other comments?
Could be related to armor pieces not able to utilize stored air? Charging Upgrade and Range Upgrade don't seem to be working either.

**Comment by desht** [comment]
Known problem, upgrade to 2.9.2
