### ISSUE TITLE
Reinforced chest not keeping its renaming in anvil

### ISSUE THREAD

**Issue by Ironbeak021** [TeamPneumatic/pnc-repressurized#714]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.3
### Forge Version
1.16.3-forge-34.1.0
### Mod Version
pneumaticcraft-repressurized-1.16.3-2.4.5-62
### Describe your problem, including steps to reproduce it
Put a reinforced chest into an anvil and rename it. Then place the reinforced chest down, then dig it up and the name you named it will have disappeared.

**Comment by desht** [comment]
Fixed in 2.9.3
