### ISSUE TITLE
ComputerCraft calling getAllActions for drone not working

### ISSUE THREAD

**Issue by xRebellion** [TeamPneumatic/pnc-repressurized#716]
### Minecraft Version
1.16.4
### Forge Version
35.1.36

### Mod Version
pneumaticcraft-repressurized-1.16.4-2.9.0-111
cc-tweaked-1.16.4-1.95.1 (in case needed)

### Describe your problem, including steps to reproduce it
Trying to call the getAllActions() function to get all the things I can do with the drone using computercraft, but got a casting error instead:
![image](https://user-images.githubusercontent.com/32483348/104748871-c22d9980-5784-11eb-9a21-c706d5d63b7e.png)

### Any other comments?
More like a question, is there somewhere I can find the actions I can do with the drones? Since apparently the book doesn't provide them. Although it may no longer be an issue if this got fixed, but having them added on the book would be a nice addition. 😃

**Comment by desht** [comment]
Yeah, looks like a bug alright.

Regarding the actions; yes, it would be good to have them all documented in the book as well, I agree.

**Comment by desht** [comment]
Also, going to add the progwidget ID (which is exactly what the actions are) to the widget tooltip in the programmer GUI, displayed when extended tooltips are enabled with F3+H.  I'll also add some info to the manual pages on the Drone Interface / "getAllActions()", and the Programmer, about that.

**Comment by desht** [comment]
Fixed in 2.9.3
