### ISSUE TITLE
Minor graphical error - Pneumatic helmet pressure GUI

### ISSUE THREAD

**Issue by TheUNkilled123** [TeamPneumatic/pnc-repressurized#721]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.4
### Forge Version
1.16.4 - 35.1.37
### Mod Version
PneumaticCraft-Repressurized-1.16 Build #122
### Describe your problem, including steps to reproduce it
 The pneumatic helmet gui pressure can appear "tucked in" on first boot of helmet and stays that way until there's a pressure change or until you change the "show pressure numerically" bool.

**Comment by desht** [comment]
Fixed in 2.9.4 release
