### ISSUE TITLE
unable to make a recipe that used the drill and laser program

### ISSUE THREAD

**Issue by benbenlaw** [TeamPneumatic/pnc-repressurized#722]

**Comment by benbenlaw** [comment]
{
  "type": "pneumaticcraft:assembly_laser",
  "input": {
    "item": "refinedstorage:raw_advanced_processor"
  },
  "result": {
    "item": "refinedstorage:advanced_processor"
  },
  "program": "drill_laser"
}

**Comment by desht** [comment]
Not a bug.  The `drill_laser` category is not intended for direct use in recipe JSON's.  If you found some documentation suggesting to use it, please let me know so I can fix it.

It's for automatically chaining drill and laser recipes together so they can be done in one step.  E.g. if laser recipe makes B from A, and drill recipe makes C from B,  then laser/drill recipe to make C from A is automatically added by the mod.

The main example of this making Advanced Pressure Tubes:
* There is a drill recipe to make 20 Pressure Chamber Valves from 1 Compressed Iron Block
* There is a laser recipe to make 8 Advanced Pressure Tubes from 20 Pressure Chamber Valves
* Therefore, a drill/laser recipe is automatically added (by the mod, after JSON's are read) to make 8 Advanced Pressure Tubes from 1 Compressed Iron Block.

In your case above, you probably just want a `laser` program.
