### ISSUE TITLE
Pressure chamber applies all enchantments at once, deleting incompatible enchantments

### ISSUE THREAD

**Issue by ThizThizzyDizzy** [TeamPneumatic/pnc-repressurized#723]
### Minecraft Version
1.16.4 😃 

### Forge Version
35.1.36

### Mod Version
2.9.0-111.jar

### Describe your problem, including steps to reproduce it
The title says it all; The pressure chamber will move all enchantments from an enchanted book onto a tool/armor, and deletes any incompatible ones
Steps to reproduce:
1. Obtain a pressure chamber, Diamond chestplate, and an enchanted book with Protection I and Sharpness I
2. Place the chestplate and enchanted book in the pressure chamber and give it enough pressure
3. The outputs will be a Diamond chestplate with Protection I and a regular book

### Any other comments?
I just noticed that I'm using an already-outdated pnc version, but I didn't see any mention of this in the newer versions' changelogs

**Comment by desht** [comment]
Yeah that doesn't sound right, will take a look.

**Comment by desht** [comment]
Fixed in 2.9.4 release
