### ISSUE TITLE
Minor Graphical Bug - Pneumatic helmet causes the nether portal effect to cover vision.

### ISSUE THREAD

**Issue by TheUNkilled123** [TeamPneumatic/pnc-repressurized#724]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.4
### Forge Version
1.16.4 - 35.1.37
### Mod Version
PneumaticCraft-Repressurized-1.16 Build #122
### Describe your problem, including steps to reproduce it
Pneumatic helmet causes the nether portal effect to have a transparency of 0% instead of slowly fading in, making you blind until you exit the portal.

**Comment by desht** [comment]
Fixed by https://github.com/TeamPneumatic/pnc-repressurized/commit/dc155d18eba894a42dea023cbae29f82bb486f38

**Comment by desht** [comment]
Fixed in 2.9.4 release
