### ISSUE TITLE
Extremely large orders void emeralds completely

### ISSUE THREAD

**Issue by Sanguinely** [TeamPneumatic/pnc-repressurized#725]
### Minecraft Version
1.16.4
### Forge Version
35.1.36
### Mod Version
2.9.2 116
### Describe your problem, including steps to reproduce it
When ordering large amounts of crude oil to a quantum storage tank (in my case 2300 buckets of crude oil) The first drone came, grabbed the emeralds, then after it left. no drone came to deliver the oil. voiding my emeralds.

**Comment by desht** [comment]
Fixed in 2.9.4 release
