### ISSUE TITLE
Pneumatic Armor initialization bar not dissappearing upon 100% initialization

### ISSUE THREAD

**Issue by brandonjshaw** [TeamPneumatic/pnc-repressurized#726]
Minecraft Version: 1.16.4

Forge Version: Forge-35.1.36

Mod Version: v1.16.4-2.9.2-116

Modpack: All the Mods 6 v1.4.0

Upon equipping both a piece of charged pneumatic armor and an uncharged piece of pneumatic armor, the initialization bar display will no longer disappear once initialization has completed for any piece of armor. It will also reappear if initialization has already been completed. Upgrades seem to be irrelevant.

Reproduction steps: 
Tested on a creative, singleplayer, super flat world on normal difficulty using ATM 1.4.0 (PneumaticCraft: Repressurized v1.16.4-2.9.2-116)

1. Spawned in (1) Creative Compressor, (1) Charging Station, (1) full set of Pneumatic armor (uncharged), (2) Advanced Pressure Tubes
2. Placed down compressor and charging station, connected via the two cables.
3. Charge any one piece of pneumatic armor.
3. Equip any one piece (and only one) of Pneumatic armor with a charge. Initialization will occur normally, and the initialization bar will disappear upon reaching 100%.
4. Equip any piece of Pneumatic armor without a charge while also wearing the piece of pneumatic armor with a charge. Initialization bars will appear upon exiting the GUI you are in, regardless of whether the armor piece is fully initialized or not.

This issue, in essence, occurs when a player is wearing both a charged and an uncharged piece of pneumatic armor.

All pieces of pneumatic armor equipped, with each of them having a charge:
![image](https://user-images.githubusercontent.com/28740295/105635969-ded86a00-5e33-11eb-8871-853f3276a284.png)

All pieces of pneumatic armor equipped, with all of them having a charge except for the leggings:
![image](https://user-images.githubusercontent.com/28740295/105636006-07606400-5e34-11eb-811e-9066838bb475.png)

**Comment by desht** [comment]
Fixed in 2.9.4 release
