### ISSUE TITLE
Crash with Redstone Module GUI when clicking mode-change button in VR (Vivecraft)

### ISSUE THREAD

**Issue by Starfang42** [TeamPneumatic/pnc-repressurized#727]
### Describe your problem, including steps to reproduce it
In Redstone Module's GUI, clicking the mode-toggle button in the upper-right corner of the GUI causes a crash to desktop when playing with Vivecraft. 

### Any other comments?
Log
[latest.log](https://github.com/TeamPneumatic/pnc-repressurized/files/5867492/latest.log)

**Comment by desht** [comment]
Can't reproduce myself (I don't have Vivecraft or VR) but I think I can see how the problem could occur.  Next release (coming in the next few days) should fix this problem, hopefully.

As a short-term workaround, you can toggle Redstone Modules from outside the GUI by right-clicking with a Pneumatic Wrench.

**Comment by Starfang42** [comment]
Was already aware of the work-around, but thanks!

**Comment by desht** [comment]
Fixed in 2.9.4 release
