### ISSUE TITLE
GPS tool server crash

### ISSUE THREAD

**Issue by torndar** [TeamPneumatic/pnc-repressurized#730]
### Minecraft Version
1.16

### Forge Version
?

### Mod Version
1.16.5-2.9.4-126

### Describe your problem, including steps to reproduce it
Left or right click on a block with a GPS tool. 

### Any other comments?

[crash-2021-01-28_21.39.53-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/5891256/crash-2021-01-28_21.39.53-server.txt)

**Comment by desht** [comment]
Fixed in 2.9.5 release
