### ISSUE TITLE
Aerial Interface doesn't respect Curse of Binding

### ISSUE THREAD

**Issue by VorpalLemur** [TeamPneumatic/pnc-repressurized#733]
### Minecraft Version
Minecraft: 1.16.4
Pneumaticraft: 2.9.4-126

Playing in direwolf20 1.16 modpack v1.5.1

Pretty simple.  If you're wearing a bit of armor that has Curse of Binding on it, the Aerial Interface and a hopper can remove it for you.

Expectation is that it shouldn't be able to.  Nothing should be able to remove Curse of Binding gear short of death or breaking of the gear.

**Comment by desht** [comment]
Yeah, that's fair.

**Comment by desht** [comment]
Fixed in 2.10.0 release
