### ISSUE TITLE
Server Crash - Area Tool

### ISSUE THREAD

**Issue by Tekstack** [TeamPneumatic/pnc-repressurized#735]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.4
### Forge Version
forge-1.16.4-35.1.36
### Mod Version
1.16.5-2.9.4-126
### Describe your problem, including steps to reproduce it
Using the area tool in one dim, went back to overworld and used the same area tool. The cords were thousands of blocks apart when trying to set new cords . I was able to get the server to reboot, and deselect the area tool on load to prevent another crash. Ended up trashing that area tool and making a fresh one, but even then when trying to set a new area either via clicking or the GUI server crashes. Two examples plus crash logs below. I could not reproduce this issue on Single Player and I'm not able to use the Area Tool at all on the server anymore (GPS is fine).

### Any other comments?
Crash 1
Crash Log ---> https://pastebin.com/3pJyXcbQ
Video ---> https://youtu.be/te-C1uo1kQk

Crash 2
Crash Log---> https://pastebin.com/km1rDaHX
Video --->https://youtu.be/BrPk7Wwgt3M

**Comment by desht** [comment]
Ah, 2.9.4.  Yeah, upgrading to 2.9.5 will fix that.
