### ISSUE TITLE
Pneumatic Armor Step Assist not Functioning

### ISSUE THREAD

**Issue by Crazydude323** [TeamPneumatic/pnc-repressurized#737]
### Minecraft Version
1.16.4

### Forge Version
35.1.37

### Mod Version
Latest; 2.9.5-128

### Describe your problem, including steps to reproduce it
Step Assist on the Pneumatic Armor isn't functioning. Walking into blocks won't let you "step up" to the next block. Tested using a variety of Vanilla and Modded blocks.

### Any other comments?
As best I can tell from searching this repository, nobody else has reported this as an issue. If I had to throw out a guess, that means it's _probably_ a mod incompatibility? I've no idea what mod would screw up this feature, of all features, but that's all I can think of if nobody else has reported this yet.

**Comment by desht** [comment]
Just as a basic question: is the feature switched on in the armour GUI? The default is off if this client hasn't used pneumatic armour before.

**Comment by Crazydude323** [comment]
I did make sure to turn it on, yes. Both via the GUI, and I assigned a hotkey in case maybe it was just turning it on via the GUI that was broken. I can confirm that whichever method I used, neither managed to get Step Assist working.

**Comment by desht** [comment]
I honestly don't know then. Can you reproduce this with just PNC (and maybe JEI / waila / etc) present?

**Comment by Crazydude323** [comment]
I can give it a test later today (2 AM where I am, and I'd rather not do testing this late at night). If it does work with just Pneumaticcraft, I'll know that it's a mod incompatibility, and I can try and pinpoint which mod specifically is causing the issue.

**Comment by desht** [comment]
Any update on this?

**Comment by desht** [comment]
Closed due to lack of response.
