### ISSUE TITLE
tablet notifications

### ISSUE THREAD

**Issue by benbenlaw** [TeamPneumatic/pnc-repressurized#738]
i wonder if it would be possible to notify players when the amadron tablet has updated its items stock "recipes".

Like maybe if they have in in the hand it could glow when its been updated or just a chat message to people that have the tablet in there invenortry

**Comment by desht** [comment]
Do you mean when the random offers (villagers mainly but maybe others) have done their once-a-day reshuffle?

**Comment by benbenlaw** [comment]
yeah after the offers refresh once a day

**Comment by desht** [comment]
Yeah, I could do that.  Only for players with a tablet in their inventory, and probably also have a client-side setting in case players don't want to be notified.

**Comment by benbenlaw** [comment]
yeah that sounds perfect yeah, you dont want player to be notified if they havent got the tablet thanks :)

**Comment by desht** [comment]
Added in 2.10.1
