### ISSUE TITLE
Pneumatic Helmet Core Component Message Box Stuck Outside "Interactable" Screen

### ISSUE THREAD

**Issue by NonchalantNoob** [TeamPneumatic/pnc-repressurized#740]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
forge-1.16.5-36.0.14
### Mod Version
1.16.5-2.10.0-134
### Describe your problem, including steps to reproduce it
When customizing the message screen of core components, I was dragging around the message display for the pneumatic helmet. I middle-clicked it while the box was at the left edge of the screen. Now it is unreachable and I can only see the very far right of the status messages "poking" out from the left of my screen. I can't interact and drag the message display back to inside my screen anymore.
### Any other comments?
I hope there would at least be a "reset" button for those custom components.

**Comment by desht** [comment]
Replied on discord, but:

Edit `config/pneumaticcraft/PneumaticArmorHUDLayout.cfg` - find the `messages` section, and edit `x` to be some value between 0 and 1 (it's the proportion of the screen width)
You'll need to do this with minecraft not running

I'll keep this open as a reminder to add some in-game solution (protection from moving panels off screen, or a reset button of some kind)

**Comment by desht** [comment]
> I'll keep this open

**Comment by NonchalantNoob** [comment]
Okay thanks for the help.

**Comment by desht** [comment]
Fixed in 2.10.1
