### ISSUE TITLE
Security Station not securing the area

### ISSUE THREAD

**Issue by duncanwebb** [TeamPneumatic/pnc-repressurized#742]
### Minecraft Version
1.16.4

### Forge Version
35.1.37

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.10.0-134

### Describe your problem, including steps to reproduce it
The Security station does not secure an area, the "unauthorized" player can open chests and break blocks in the range of the station.

This is what I recorded for the episode https://youtu.be/w3Tdqsoq4Og.

### Any other comments?
Don't think that the version of Minecraft and the mod are significant. 
When changing the user the inventory is retained - probably a forge "feature".

**Comment by desht** [comment]
OK, dumb initial question (and I haven't watched your video yet, will do later today): does the unauthorized player have op status or creative mode?  If they do, the security station won't affect them in any way.

I did test all this on a dedicated server with two accounts.  My second account was prevented from doing anything, but I'll go back and test again.

**Comment by duncanwebb** [comment]
Maybe I can't do this on the same computer in a single player world with "Open to LAN" enabled, I'll create a separate server. If you still watch the video, you may have some tips. I watched the video mentioned in the manual and took most of the information from there.

**Comment by desht** [comment]
Yeah, I didn't test on an Open To LAN world... in practice it would always be used on a dedicated server.  I'll watch the video and let you know.  The video in the manual is pretty ancient, and I did significantly rework the security station in 1.16 (as in a near-total rewrite), so some stuff may have changed...

**Comment by duncanwebb** [comment]
I'd already set up a dedicated server, as a workaround for the lag that you fixed, so it was easy to do for 1.16.5. Feeling a bit stupid as it works just fine on a dedicated server. While I spotted that the inventory didn't change between users it didn't click that I should be using a dedicated server.

**Comment by desht** [comment]
Cool.  I've watched the video now - I did noticed some weirdness at one point when the station claimed a hack was already in progress.  That looks like a bug, though I'm not quite sure what you did to trigger it.  Any in-progress hack should be wiped if no player has the secstation GUI open, so I'll need to check that.

Also, the times where the station claimed you didn't have enough upgrades were (at least partly) because the helmet hadn't finished initialising when you clicked it. The helmet needs to be fully initialised to work, and you don't need any other armor pieces equipped.  The message could be more informative, I guess ("helmet still initialising!" or similar...)

**Comment by desht** [comment]
Oh - also, the secstation hack failure isn't a *guaranteed* death - if you're on full health it'll take you down to half a heart and apply blindness/slowness/nausea for a short time.  Anything under full health, though, and it'll kill you.

**Comment by duncanwebb** [comment]
I saw the "in-progress hack" too, since both players were on the same workstation, the first player needed to exit before starting the second player. It might be possible to have two Minecraft instances running at the same time but have not figured if it is possible with MultiMC.

I don't have the 10 speed upgrades in the second helmet, so it takes a while to initialize. Took a while to realize what was happening, you get used to the speed. Same with the legging, I walk so slowly, it's painful ;-)

**Comment by desht** [comment]
I think this is all OK?  Closing now, feel free to reopen if I missed something.
