### ISSUE TITLE
Interacting with block crashes server

### ISSUE THREAD

**Issue by 1nd1r4** [TeamPneumatic/pnc-repressurized#749]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.0.43
### Mod Version
2.10.1-140
### Describe your problem, including steps to reproduce it
Flew on a chassis block
### Any other comments?
Crash: https://pastebin.com/dD5uLtYp

**Comment by desht** [comment]
Looks like an easy fix, but for the record, please don't paste large stack traces directly into issues.  Sites like pastebin exist for a reason, please use them.

**Comment by 1nd1r4** [comment]
> 
> 
> Looks like an easy fix, but for the record, please don't paste large stack traces directly into issues. Sites like pastebin exist for a reason, please use them.

Edited it! :)

**Comment by desht** [comment]
Fixed in 2.10.2 release
