### ISSUE TITLE
[Feature Request] Item/mod blacklist for Enchantment Extraction

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#750]
Would be nice to have a way to blacklist certain items from the Pressure Chamber to prevent enchant extraction. 

Case in point, Quark's Ancient Tomes: https://github.com/NillerMedDild/Enigmatica6/issues/1514

Also, Tetra Tools which are not enchanted through traditional means: https://github.com/NillerMedDild/Enigmatica6/issues/1506

**Comment by desht** [comment]
Yeah, a blacklist is probably the simplest option here...

**Comment by desht** [comment]
This is in build ~~146~~ 147 if you'd like to test.  The config blacklists ancient tomes and all Tetra items by default since they're known to allow enchantment duping.

**Comment by desht** [comment]
Added in 2.10.2 release
