### ISSUE TITLE
Core Components re-activation problem.

### ISSUE THREAD

**Issue by ManiacRobertWasTaken** [TeamPneumatic/pnc-repressurized#753]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5

### Forge Version
Enigmatica 6 0.4.3. (forge 36.0.45)

### Mod Version

pneumaticcraft-repressurized-1.16.5-2.10.2-148

### Describe your problem, including steps to reproduce it.
Nobody from server can re-activate core components after disable them, we tried to restart client / relog but it's not working, we tried to keybind the core component, but still same problem.

https://user-images.githubusercontent.com/39351347/110176888-b10c1b00-7e0c-11eb-955a-0965783cd403.mp4

**Comment by desht** [comment]
Will investigate, but as discussed on Discord, a workaround in the short term is to edit `config/pneumaticcraft/ArmorFeatureStatus.cfg` (stop the client first) and ensure this line is in the active list:
```
"pneumaticcraft:core_components",
```
(trailing comma needed unless the last line of the list - it's a JSON file)

**Comment by desht** [comment]
Problem confirmed.

**Comment by desht** [comment]
Fixed in 2.10.3
