### ISSUE TITLE
[Feature Request] Support for Thermal's Holding Enchant

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#754]
Thought this might be a neat little bit of cross mod support to let Pneumatic tools/armor accept the Holding enchant to increase their air volume. 

I don't know what would be involved with enchanting blocks with it, but that could be nice too if it's not too involved. Otherwise just expanding the Jackhammer, Armor, and Memory stick with it would be lovely.

**Comment by desht** [comment]
I'll take a look into it, though I'm concerned it could be a very easy way to get a lot of extra air storage.  Then again, 1.12.2 allowed far more in the way of volume upgrades, so... *shrug*

If it's technically easy to do, then sure why not? :)

**Comment by MuteTiefling** [comment]
Oh, you even added it to canisters, very nice. This'll make for some excellent storage opportunities with a chest full of canisters!

**Comment by desht** [comment]
Added in 2.11.0 beta
