### ISSUE TITLE
[Feature Request] Radiation protection upgrade for Pneumaticraft Armor

### ISSUE THREAD

**Issue by Vashet** [TeamPneumatic/pnc-repressurized#755]
As part of integration with Mekanism and possibly other mods that introduce radiation exposure, it would be nice to have an upgrade for Pneumaticraft Armor that protects against radiation.
I'm currently in late game of a pack that has both Pneumaticraft and Mekanism. I've made both fully upgraded PNC and MekaSuite armors and find that I much prefer the PNC armor. Unfortunately I have to switch to the MekaSuite anytime I need to work with my nuclear setup.

**Comment by desht** [comment]
Yeah, worth looking into. I'll see how feasible it is.

**Comment by desht** [comment]
Added in 2.11.0 beta
