### ISSUE TITLE
Oil Mod Compatibilty

### ISSUE THREAD

**Issue by tyler489** [TeamPneumatic/pnc-repressurized#756]
I would like Silent Mekanism's and Thermal's Crude oil to be able to be substituted for pneumaticraft oil in the refinery.

**Comment by desht** [comment]
Silent's Crude Oil used to work in 1.15.  In that version, they added their crude oil to the `forge:crude_oil` fluid tag, which is what PNC:R uses for its oil and refinery recipes.  For some reason, they decided to change that to `forge:oil`.  Don't know why, but that's not on me.

As for Thermal, last I checked they don't use a fluid tag at all for their oil fluid.

This is really on the pack maker to handle this integration.  I can't be expected to chase the fluid tags or fluid names of other mods (which, as demonstrated, can change without my control).  Therefore, ask the modpack maker to add those mods' crude oil to the `forge:crude_oil` fluid tag, and everything will work fine.
