### ISSUE TITLE
[Feature Request] Flight Stabilizers - Anti Momentum upgrade to jet boots

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#757]
This seems to come up on a weekly basis in the E6 Discord, people wishing for the 'instant stop' of creative flight that was a feature of Draconic Evolution Armor.

I was thinking this might make a neat upgrade to the jet boots as a separate upgrade item. Call them Flight Stabilizers or something along those lines.

If the player is flying and takes their hand off the space bar or movement keys, the flight stabilizer will use a moderate amount of air as retro thrusters to stop movement immediately. No drifting. Both in build mod and in jet boot flight mode.

**Comment by theboo** [comment]
This would be amazing, and fits super well with that iron man feel you got going on with this armor

**Comment by desht** [comment]
Yeah, that could work. Probably requiring tier 4 or maybe 5 jetboots, and yes an air cost to come to a swift halt...

**Comment by MuteTiefling** [comment]
This works wonderfully, thanks!

**Comment by MuteTiefling** [comment]
Oh, hrm. Not working in build mode. Is that an intentional choice?

**Comment by desht** [comment]
Yeah... hadn't made a final decision on that, but my thought was that movement is pretty slow in build mode anyway.  Also, the auto-stop only applies when the thrust key is released (and in build mode the thrust key only moves you up, and you always immediately stopped anyway).

I presume you're referring to the drift when you move sideways in builder mode with WASD?  I could look at cancelling that too, although it could be a little trickier...

**Comment by MuteTiefling** [comment]
Yeah, you get pretty speedy in build mode with speed upgrades in your pants, so slowing/stopping that drift could be nice if not too much trouble

**Comment by MuteTiefling** [comment]
Testing these along with the heat block properties. It caught me a little off guard, actually. Wasn't expecting them to be in :D 

Seems like you may have bound the thrust to Forward, is that right? Noticed I can barely move laterally while these are enabled unless I'm also moving forward. 

https://streamable.com/4nfq8q

**Comment by MuteTiefling** [comment]
actually, this probably shows it a bit better

https://streamable.com/rvyq97

**Comment by desht** [comment]
Hmm, I might know what's going on there. Will take s look.

**Comment by desht** [comment]
Added in 2.11.0 beta
