### ISSUE TITLE
drone from amadron getting stuck in storage drawers

### ISSUE THREAD

**Issue by benbenlaw** [TeamPneumatic/pnc-repressurized#759]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.0.46
### Mod Version
2.10.3-149
### Describe your problem, including steps to reproduce it
drones seem to have trouble navigating to chests where storage drawers from the storage drawers mod are in the way. getting stuck ect

**Comment by desht** [comment]
Screenshots of your setup please.

**Comment by benbenlaw** [comment]
![image](https://user-images.githubusercontent.com/42780877/110772031-17e96400-8253-11eb-8bd7-2d5a05a5a7b3.png)
i dont have the exact setup yet but a few people have reported it now

**Comment by benbenlaw** [comment]
![](https://cdn.discordapp.com/attachments/790909542787579935/819555956236353576/2021-03-11_1.png)

![](https://cdn.discordapp.com/attachments/790909542787579935/819555980454264832/2021-03-11.png)

![](https://cdn.discordapp.com/attachments/790909542787579935/819556310701309973/2021-03-11_2.png)

**Comment by benbenlaw** [comment]
more pictures

**Comment by desht** [comment]
Difficult to tell, are those the normal or half-width drawers?

**Comment by benbenlaw** [comment]
normal

**Comment by desht** [comment]
As suspected, it's a problem with Storage Drawers, not PNC:R.  Storage Drawers blocks have a non-opaque collision shape, but don't override `allowsMovement()` to return false, which means entities will get stuck trying to path around them.

Please raise an issue with Storage Drawers, and feel free to direct the mod author to me if more explanation is needed.
