### ISSUE TITLE
[Feature Request] Altering Liquids Within Machines

### ISSUE THREAD

**Issue by Darkosto** [TeamPneumatic/pnc-repressurized#76]
Hello!

Would you consider adding a feature to alter the fuel lists? For example: I have two types of liquid gasoline and only the pneumaticraft shows on the list. I'd like to add the other and assign it a value within the liquid compressor. This would be very helpful for pack devs who are trying to make liquids consistent across the modpack.

Thank you and I appreciate your hard work!
Darkosto

**Comment by Jandakast** [comment]
Would be awesome to have CraftTweaker support for adding/removing/modifying the Fuel Registry as well! 

That way if we didn't want molten metals to work as fuels we don't have to remove their temperature and could just remove the fluid from the fuel registry.

**Comment by MineMaarten** [comment]
Added the following CraftTweaker methods:
mods.pneumaticcraft.liquidfuel.removeAllFuels();
mods.pneumaticcraft.liquidfuel.addFuel(ILiquidStack fuelLiquid, double mLPerBucket);
mods.pneumaticcraft.liquidfuel.removeFuel(ILiquidstack fuelLiquid);

Let us know if you're missing anything else!

**Comment by MineMaarten** [comment]
Btw, if you want to play around with this, you can find an official build at: http://jenkins.k-4u.nl/view/Desht/job/PneumaticCraft-Repressurized/88/
