### ISSUE TITLE
drone crashes game

### ISSUE THREAD

**Issue by MsAlPatina** [TeamPneumatic/pnc-repressurized#760]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### drone was linked to drone interface while on top of charging station and upon punching it it crashes the game 
[crash-2021-03-11_19.53.29-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/6130242/crash-2021-03-11_19.53.29-client.txt)

![image](https://user-images.githubusercontent.com/43314815/110945836-193f8d00-8336-11eb-8e55-cea93a0cfcb7.png)

**Comment by desht** [comment]
Fixed in 2.11.0
