### ISSUE TITLE
[Request] JEI support for heat blocks

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#763]
Would be nice to have these listed under a common tab in JEI. Maybe a secondary tab for each heat using machine that shows the blocks and some of their attributes? 

Temperature, a gauge to show how fast/slow they are, and their transformations would be fantastic.

**Comment by desht** [comment]
This is something that has occurred to me in the past, but it'll need a bit of a rework of the way heat definitions are done to work properly with JEI (specifically heat definitions need to become part of the vanilla recipe system so they're properly synced to clients when they connect, since JEI is course a client-side mod).

So it's probably possible and definitely desirable, but I need to figure if it's feasible, and how to best support it within the JEI framework (I think a custom "heat" ingredient type might be needed here).

**Comment by desht** [comment]
Build 153+ has JEI support for showing heat properties - 'U' or 'R' on a block which has heat properties, or is the result of a transition (respectively) will show the relevant heat info.

You can also do a 'U' on Heat Pipe to show all known heat properties (there's a new "Heat Properties" category with a little thermometer icon).

Testing appreciated - this code is pretty raw, be warned! :)

**Comment by MuteTiefling** [comment]
Looking pretty solid, honestly. Looks like you're auto registering fluids now too, or was that a thing already? May want to black list some of your own fluids there though, like oil and such. The ones from other mods would be easy enough to disable as part of a pack, however.

Tiny bit of feedback on the campfire and blaze burner. Campfire is probably good to leave the '[lit=true]' out of JEI entirely. The Blaze Burner I think could maybe have that left off too if you're able to render the various states. Otherwise, I think just a simple 'Smouldering', 'Fading', 'Kindled', and 'Seething' would work. 

And for the default heat values, I would drop the thermal resistance on the seething one a bit more to make it worthwhile. Getting to Kindled just means feeding it coal, and then it settles down to Fading and Smouldering from there. But Seething requires feeding it a Blaze Cake, which is a multi step recipe made from crushed netherrack, sugar, eggs, and lava. The state also doesn't last long, so getting a lot of heat out fast would be nice.

**Comment by desht** [comment]
Fluids have always been auto-registered - only now you can see what their values are. I'm not sure I want/need to blacklist anything, really.

Blaze burner needs a TER to render by the looks of it. Might be possible to render that in JEI, will have to investigate. Leaving the property display out entirely would be ideal, bit may be problematic... It's important to be sure it's clear for any future additions too, without any special-casing needed.

Agreed on buffing the seething version, yep.

**Comment by desht** [comment]
Added in 2.11.0 beta
