### ISSUE TITLE
Seemingly unable to add custom heat blocks

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#764]
### Minecraft Version
1.16.5

### Forge Version
36.0.46

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.10.3-149

### Describe your problem, including steps to reproduce it

I'm attempting to add in the attached heat block jsons as data packs and seem to be hitting a bit of a wall. 

These are being injected by KubeJS, though I couldn't get them working with a vanilla datapack either and I'm relatively certain that the custom ones I had added previously were working. However, at this point none of them do. 

On a side note, if you'd like to simply incorporate these into the mod, that'd be awesome. Just leave out the uraninite one, perhaps, as that's very much pack specific and wouldn't make sense otherwise. 

### Any other comments?

[block_heat_properties.zip](https://github.com/TeamPneumatic/pnc-repressurized/files/6135793/block_heat_properties.zip)

**Comment by MuteTiefling** [comment]
Oh, my god I'm dumb. >.< I had them in the wrong folder. Needed to be `data\pneumaticcraft\pneumaticcraft\block_heat_properties\` and I only had one pneumaticcraft folder.

Ugh, sorry. 

Still, there's something here that I could use your help with, and that's the Create Blaze Burner. As you can see in the screenshots below, it appears to use a block state similar to campfires to determine its temperature. So I set that as the `statePredicate` value but that doesn't seem to work. Is this something that you'd have to alter on your side?

Note on this block, it naturally burns out over time, so that's why there's no transformation listed.

![2021-03-13_20 33 50](https://user-images.githubusercontent.com/9543430/111054536-7bce8100-843b-11eb-97b4-fe46f734e695.png)

![2021-03-13_20 33 46](https://user-images.githubusercontent.com/9543430/111054537-7e30db00-843b-11eb-9529-7ffed60f9311.png)

![2021-03-13_20 33 52](https://user-images.githubusercontent.com/9543430/111054539-7ffa9e80-843b-11eb-9dee-6826bb0a5e1e.png)

**Comment by desht** [comment]
First off, I have no issues adding all these (except as you say the uraninite one) as default heat entries.  The more the merrier!

As for the blaze burner... yeah, my fault.  Right now the heat properties only support a single entry per block, so multiple definitions with the same block but different predicates get ignored.  Having said that, I think it will be pretty easy to support multiple definitions per block, so I'm going to have a play with that today...

**Comment by MuteTiefling** [comment]
Hah, sweet! Thanks!

**Comment by desht** [comment]
Added in 2.11.0 beta
