### ISSUE TITLE
When boots run out of pressure mid flight, once you land your bound button no longer disables them so you can't jump.

### ISSUE THREAD

**Issue by yropro** [TeamPneumatic/pnc-repressurized#765]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.0.46
### Mod Version
2.10.3-149
### Describe your problem, including steps to reproduce it
Fly, run out of pressure, land, tap bound button to disable it, can't disable it. Unable to jump because it tries to fly.
You have to repressurize them, wait for them to turn on, then tab the bound button to disable them.

**Comment by desht** [comment]
Fixed in 2.11.1
