### ISSUE TITLE
Killing drones can crash the player's client

### ISSUE THREAD

**Issue by TheDieselPunk** [TeamPneumatic/pnc-repressurized#766]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.0.46
### Mod Version
pneumaticcraft-repressurized-1.16.5-2.10.3-149
### Describe your problem, including steps to reproduce it
Myself and others have noticed that killing any type of drone on the server will crash their client. Here's my crash report:
https://pastebin.com/u5ChwWfT
To reproduce, kill a drone on the ATM6 modpack.

### Any other comments?
Sorry, not sure if this will happen with the mod installed by itself.

**Comment by desht** [comment]
Your stacktrace has got exactly nothing to do with PneumaticCraft

Also, the punching drones crash is fixed in 2.11.0.

**Comment by TheDieselPunk** [comment]
Hey sorry about that, I pasted the wrong crash report https://pastebin.com/JBHM6Yr8 but now that I'm looking I see that #760 seems to be the same issue, I'll be more careful in the future.
