### ISSUE TITLE
Drone mess up

### ISSUE THREAD

**Issue by thestormblazer** [TeamPneumatic/pnc-repressurized#767]
I set a drone radius to over 1 million just just mess about and it picked me up and then crashed the game and the server is fine when I log off but when I log on it crashes the chunk isn’t corrupted cause other people can go to the chunk and the drone logs of with me what can I do to fix it?

**Comment by desht** [comment]
I asked you for a stacktrace.  Where is it?

**Comment by thestormblazer** [comment]
I don't own the server nor do I know what that is xD sorry could you explain?

**Comment by desht** [comment]
You said it crashes. So I need the crash log. Without that I can't even guess what your problem might be.

**Comment by thestormblazer** [comment]
See I don't crash just when I try and join the server it doesn't let me and the server crashes

**Comment by thestormblazer** [comment]
Ok give me a bit

**Comment by desht** [comment]
Damn was afraid of that. Cofh core doesn't have an official API, and the calls I used have changed. Should be possible to work around this by disabling cofh integration in the config... See `config/pneumaticcraft/ThirdParty.cfg` which lists all the mods which can be integrated with.

**Comment by desht** [comment]
Closing this, since #775 covers it.
