### ISSUE TITLE
Suggestion: minecraft comparitor mode for redstone module

### ISSUE THREAD

**Issue by Rodg88** [TeamPneumatic/pnc-repressurized#769]
A mode for the redstone module which can read a block's 'comparitor output' would be great, so for example you could use one to read the power level in an energy cell, or how many items are in an inventory, and use that as an input directly without needing to use a vanilla comparitor as well.

**Comment by desht** [comment]
Yeah, possibly.  The main reason I didn't add one initially is because the Universal Sensor can actually do that already.

I'll consider it again.

**Comment by desht** [comment]
Added in 2.11.1.  Select "Compator Mode?" checkbox in the module GUI.  Module must be in input mode and have an Advanced PCB installed.
