### ISSUE TITLE
[Feature Request] Immersive Petroleum Integration

### ISSUE THREAD

**Issue by Darkosto** [TeamPneumatic/pnc-repressurized#77]
Hello!

Would it be possible to allow Immersive Petroleum mod integration specifically to allow the IP gasoline to work in Pneumaticraft machines. Thus eliminating two gasoline liquids in the game.

Thank you!
Darkosto

**Comment by MineMaarten** [comment]
If I'm not mistaken this is now covered by https://github.com/TeamPneumatic/pnc-repressurized/issues/76 ? You can now alter the fuel values and refinery recipes to use a different gasoline?:)

**Comment by justinrusso** [comment]
I *think* this should do. I'll grab the build and mess with it hopefully soon.

**Comment by justinrusso** [comment]
@MineMaarten Thanks for the help - This should be good!

**Comment by Darkosto** [comment]
Yes, definitely! Thank you for the assistance :)

**Comment by MineMaarten** [comment]
You are welcome!
