### ISSUE TITLE
Punching a drone causes NPE

### ISSUE THREAD

**Issue by ClockwiseGear** [TeamPneumatic/pnc-repressurized#773]
### Minecraft Version
1.16.4
### Forge Version
35.1.37
### Mod Version
2.10.3-149
### Describe your problem, including steps to reproduce it
In creative mode, after programming a drone and placing it, left-clicking it caused the game to crash
### Any other comments?
Crash report:
https://pastebin.com/hqeHZyW0

**Comment by desht** [comment]
Already fixed in 2.11.0
