### ISSUE TITLE
Crash after placing and breaking the Refinery output block

### ISSUE THREAD

**Issue by BirblinPastry** [TeamPneumatic/pnc-repressurized#777]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.1.2
### Mod Version
2.11.1-163
### Describe your problem, including steps to reproduce it
I place the refinery block, and then it causes a server crash when trying to break it (using a Supremium Paxel from the Mystical Agriditions mod), Tried again with an Iron Pickaxe from Vanilla, when breaking them while crouched it did not cause a crash, but if standing normally it will cause a crash
### Any other comments?
Currently in the modpack: All The Mods 6 (version 1.5.6)

![](https://cdn.discordapp.com/attachments/604075564969754660/825919209987899422/unknown.png)

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Fixed in build 169+ from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/

As a workaround in earlier versions, if you need to tear down a refinery setup, break the Refinery Controller before any of the Refinery Output blocks.

**Comment by desht** [comment]
Fixed in 2.11.4 release
