### ISSUE TITLE
[1.16.5] Potion Ammo in Minigun disconnects player from server

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamPneumatic/pnc-repressurized#779]
### Minecraft Version
1.16.5

### Forge Version
1.16.5-36.1.0

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.11.3-168

### Describe your problem, including steps to reproduce it

This issue only occurs on servers. 

Steps to reproduce:
- Make potion ammo (tested with Instant Damage II) 
- Place it in the Minigun GUI
- Close the GUI
- You're kicked from the server

Logged error: https://pastebin.com/Q2dUvDX1

### Any other comments?
Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/1871 and https://github.com/NillerMedDild/Enigmatica6/issues/1756

**Comment by desht** [comment]
Fixed in 2.11.4 release
