### ISSUE TITLE
Server Crash when breaking refinery output(middle of stack) by hand - Modversion 1.16.5-2.11.3-168 (On Enigmatica 6 0.4.8)

### ISSUE THREAD

**Issue by Trostmm** [TeamPneumatic/pnc-repressurized#780]
### Minecraft Version
1.16.5

### Forge Version
36.1.0

### Mod Version
1.16.5-2.11.3-168

### Describe your problem, including steps to reproduce it
Build a refinery controller, stack at least 3 outputs on top or next to it. Break one of the outputs in the middle of the stack. Enjoy a javalangstackoverflow.

[crash-2021-04-01_23.28.44-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/6246599/crash-2021-04-01_23.28.44-server.txt)

Obviously part of a modpack, so lots of other stuff going on.

**Comment by desht** [comment]
Already fixed in 2.11.4.  see #777
