### ISSUE TITLE
Allow Mending Enchant to Repair Tools held by Drones

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamPneumatic/pnc-repressurized#784]
I would like to suggest that picked up XP applies to mending enchanted items held by drones.

That's about it :D

**Comment by aqpoyo** [comment]
Yes, that would be awesome!

**Comment by desht** [comment]
I think this would be fairly easy to do, although it will be a requirement that the drone is instructed to collect XP via the Import Entity widget (and a `@orb` filter).
