### ISSUE TITLE
Sides not accurately represented in thermal compressor

### ISSUE THREAD

**Issue by Landstryder** [TeamPneumatic/pnc-repressurized#785]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
While having a fire or other heat source on the North and East face of the block the interface of the thermal compressor shows the heat value of the East and West faces rise. The machine still seems to function as expected but the interface is visually incorrect or mixed up

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Yep, a simple mixup in the GUI where the north & west temperature widgets were swapped.  The compressor itself is working correctly, just a GUI problem.  Will be fixed in next release.

**Comment by desht** [comment]
Fixed in 2.12.0
