### ISSUE TITLE
When running on external server elevator bases prevent logging in

### ISSUE THREAD

**Issue by Steve1150** [TeamPneumatic/pnc-repressurized#786]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12.2
### Forge Version
14.23.5.2847
### Mod Version
0.11.15-398
### Describe your problem, including steps to reproduce it
When running this mod on an external server: logging in where chunks containing elevator bases are present, crashes the client with the following crash report:
[crash-2021-04-06_19.16.19-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/6266803/crash-2021-04-06_19.16.19-client.txt)

**Comment by desht** [comment]
Sorry, 1.12.2 is long out of support.
