### ISSUE TITLE
[1.14.4] Omnidirectional hopper not outputting into or extracting from composters.

### ISSUE THREAD

**Issue by Rev31** [TeamPneumatic/pnc-repressurized#787]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.14.4
### Forge Version
28.2.23
### Mod Version
1.0.8
### Describe your problem, including steps to reproduce it
Omnidirectional Hopper not outputting into or extracting from composters. The composter does not get filled and the omnidirectional hopper does not put any items into it. A omnidirectional hopper also does not extract bonemeal from a full composter.

**Comment by desht** [comment]
Yep, the composter is a special-case, and the vanilla hopper also handles it specially.  It's not a tile entity and doesn't expose an item capability, so there won't be any support for it via the omnihopper, sorry.
