### ISSUE TITLE
Amadron not dispersing payments for custom trades

### ISSUE THREAD

**Issue by Landstryder** [TeamPneumatic/pnc-repressurized#788]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
Setting up custom trades with the Amadron Tablet on a multiplayer server, the seller is never receiving the payments. We have tried using the default locations, and setting custom locations with GPS, and still the payments never comes back. The buyer get their items just fine every time, and canceling the trade returns the original items, but every time a sale happens the payment get lost or absorbed by the Amadron network.

### Any other comments?
Is this meant to simulate how it works IRL? Amadron just keeps all the profit for itself :P

**Comment by desht** [comment]
Hmm, there have been problems with this in the past, but I thought I'd resolved everything.  I'll do some more testing on it.

**Comment by desht** [comment]
Fixed in 2.12.0
