### ISSUE TITLE
Harvest Drone is destroying my Farm

### ISSUE THREAD

**Issue by Killerdog200** [TeamPneumatic/pnc-repressurized#789]
So my Harvest drone is Harvesting my Wheed Carrots potatos etc and its replacing it. But when i use the seed from Pams Harvest its Harvesting my crops but not Repleacing it
Edit: and my harvest drone is destroying my wooden housexD

**Comment by desht** [comment]
Mod version? The template is there for a reason, please use it and not just overwrite it.

**Comment by Killerdog200** [comment]
sry
