### ISSUE TITLE
Harvest drone is destroying my Farm

### ISSUE THREAD

**Issue by Killerdog200** [TeamPneumatic/pnc-repressurized#790]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.1.2
### Mod Version
1.16.5-2.11.4-170
### Describe your problem, including steps to reproduce it
So my Harvest drone is Harvesting my Wheed Carrots potatos etc and its replacing it. But when i use the seed from Pams Harvest its Harvesting my crops but not Repleacing it
Edit: and my harvest drone is destroying my wooden housexD

**Comment by desht** [comment]
I'll do some testing with Pam's. Seems like maybe those crops don't work like vanilla crops.

As for your wooden house... not a bug, just don't build so close :p

**Comment by Killerdog200** [comment]
Ok thx for having a look^^

**Comment by desht** [comment]
So I've taken a look at PHC2 Crops (for 1.16), and it does indeed behave differently to vanilla: crops don't drop seeds, but need to be right-clicked to drop a crop item, which can then be crafted into seeds.

Harvesting Drones require that crops drop seeds when they're broken so they have seeds to replant.  I'm not going to change this behaviour, so PHC crops will remain unsupported by Harvesting Drones.  If you want to automate harvesting of these crops with drones, use a regular programmable Drone, and the Right Click widget (in Click Block mode).
