### ISSUE TITLE
Server refuses to boot-up

### ISSUE THREAD

**Issue by dangerousones** [TeamPneumatic/pnc-repressurized#791]
### Minecraft Version
1.14.4
### Forge Version
1.14.4-28.2.23
### Mod Version
pneumaticcraft-repressurized-1.14.4-1.0.8-22.jar
### Describe your problem, including steps to reproduce it
Server flatout refuses to complete the boot process, it fails in the setup phase.
### Any other comments?
[crash-2021-04-10_22.11.20-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/6290870/crash-2021-04-10_22.11.20-server.txt)
[latest_8.log](https://github.com/TeamPneumatic/pnc-repressurized/files/6290871/latest_8.log)

**Comment by desht** [comment]
No idea what that error means, and sorry but 1.14 is not supported. Only 1.16 is supported.
