### ISSUE TITLE
1.16.5 Oil dont have water physics

### ISSUE THREAD

**Issue by ghost** [TeamPneumatic/pnc-repressurized#792]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5

### Forge Version
1.16.5-36.1.0

### Mod Version
Pneumaticcraft-repressurized-1.16.5-2.11.4-170

### Describe your problem, including steps to reproduce it
The oil generated in the world does not have the physical properties of liquids in minecraft. For example, if you try to go down from a mountain on a waterfall made of oil, the player will immediately fall to the ground.

### Any other comments?
![Screenshot_3](https://user-images.githubusercontent.com/36424845/114460074-f977df00-9be9-11eb-8a81-688d53b5fc4c.png)

**Comment by desht** [comment]
Known issue, and nothing I can do about it.  Modded fluids simply don't behave like water, and won't until at least Minecraft 1.17.
