### ISSUE TITLE
[Bug]  Advanced Regulator not preventing air flow with redstone signal

### ISSUE THREAD

**Issue by Mayhemblast** [TeamPneumatic/pnc-repressurized#796]
1.16.5 Minecraft
Forge - 1.16.5-36.1.0
Tested on latest recommended and release, singleplayer
(pneumaticcraft-repressurized-1.16.5-2.12.0-177)
(pneumaticcraft-repressurized-1.16.5-2.11.4-170)

Using a small setup with a regulator and vortex tube connected to an air compressor
a redstone signal will prevent air flow through the regulator, but once an advanced PCB is added, the regulator stops working and will not prevent any air flow regardless of redstone signal, and so the vortex tube drains all the pressure, tested with redstone modules, levers and repeaters.

**Comment by desht** [comment]
One you add the Advanced PCB, what values are you setting in the module GUI?
