### ISSUE TITLE
[Feature request] drone filte block/item by nbt

### ISSUE THREAD

**Issue by Death-123** [TeamPneumatic/pnc-repressurized#797]
make a tool to get a block/item, contain its meta and nbt
and then use this to filte block/item in drone's action
for example i want drone only right click block which has energy over 100

i want feature like this to do some wonderful things

**Comment by Death-123** [comment]
i play in 1.12.2, i dont know is still under maintenance :-)

**Comment by desht** [comment]
I'm afraid 1.12.2 isn't supported anymore.  I'm actually considering something like this, but it will be 1.16 only.  See #771.

**Comment by Death-123** [comment]
understand, thanks
