### ISSUE TITLE
Crash when shift-clicking the Refinery Controller with the book to open its page

### ISSUE THREAD

**Issue by aaronhowser1** [TeamPneumatic/pnc-repressurized#798]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.1.4
### Mod Version
pneumaticcraft-repressurized-1.16.5-2.11.4-170
### Describe your problem, including steps to reproduce it
https://pastebin.com/QeEcwgkn

**Comment by desht** [comment]
Hard to see this as being anything other than a Patchouli bug...

I can reproduce this in my dev environment, although the relevant line in the stacktrace (GuiBookEntry.java:97) doesn't properly match the decompiled source for the class I have in my dev environment (using Patchouli 1.16.4-48).  Stepping through with a debugger shows the the `GuiBookEntry` object's `leftPage` and `rightPage` are both null at this point and Patchouli is assuming a non-null `leftPage` object.

So this is on Patchouli.
