### ISSUE TITLE
Assembly Table won't work with split stacks

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#799]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5

### Forge Version
36.1.4

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.12.0-177

### Describe your problem, including steps to reproduce it
Assembly table doesn't appear to want to work with a split stack of items.

Place 20 Pressure Chamber Valves in the input side, but split across two inventory slots. It won't pick them up.

Re-stack them and it works fine. 

### Any other comments?

This is perhaps compounded by the fact that it takes evenly from each stack. So if you take 60 valves and spread them across 3 slots, at first all slots have a valid 20. But as it picks up, it takes from each slot, leaving 13,13,14. Now it will stop processing any further.

**Comment by desht** [comment]
Yeah, the IO unit is expecting to see all the items in a single itemstack right now.  Shouldn't be too hard to fix, I think...

**Comment by desht** [comment]
Should be fixed in build 180.  Would appreciate some testing on that before a 2.12.1 release just to make sure I haven't broken anything :)  Needed to redo the item search logic for the IO Units a bit...

**Comment by MuteTiefling** [comment]
seems to be working just fine! does wonky stacks with ease, still works for single item stuff. Mixed inputs too

**Comment by desht** [comment]
Fixed in 2.12.1
