### ISSUE TITLE
Pneumatic Armor with Security Upgrade doesn't seem to function

### ISSUE THREAD

**Issue by belathus** [TeamPneumatic/pnc-repressurized#802]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5

### Forge Version
36.1.16

### Mod Version
2.12.0-177

### Describe your problem, including steps to reproduce it
I put a security upgrade in my pneumatic chest plate. The charging station says I will "gain protection from fire and lava at a significant air cost: air will be rapidly dumped from the chest plate to extinguish nearby flames and solidify nearby lava." I don't see an option to enable it on the "Pneumatic Armor General Options" screen for my armor, nor does it seem to extinguish any flames or solidify lava.

**Comment by desht** [comment]
There's no option to enable it since it's a passive upgrade (always on).

I just did some testing and I can confirm it's definitely extinguishing fire and solidifying lava for me.  Can you confirm that you're in survival mode (the upgrade doesn't do anything in creative or spectator) ?

I guess it's possible some other mod is interfering here, but I've not had any reports of this not working before...

**Comment by belathus** [comment]
I'm in survival mode playing on a server. The armor has 10 bar of pressure, kept pressurized via an aerial interface with a charger attached to it. I tried jumping in lava in both the nether and the overworld.

... Ring of Odin, from Botania and an Infernal Chalice from Reliquary. When I removed those, jumping into lava causes that lava to be turned into obsidian. Guessing it doesn't activate if I'm immune to fire.

**Comment by desht** [comment]
Yes, it requires incoming fire damage to trigger, which is intentional. I guess I should document that in the book & the upgrade text

**Comment by belathus** [comment]
Awesome. Well, documenting it is enough for me. I guess I thought it'd work like frost walker boots or something, but I appreciate that it works like it does.

**Comment by desht** [comment]
Manual updated in 2.12.2
