### ISSUE TITLE
Technical typos in the PNC:R handbook

### ISSUE THREAD

**Issue by Juicebox360** [TeamPneumatic/pnc-repressurized#807]
### Minecraft Version
1.16.5
### Forge Version
36.1.16
### Mod Version
184

Some entries have certain strings that haven't been parsed correctly as contextual links.
![uhoh](https://user-images.githubusercontent.com/1103834/118428388-32d9b980-b684-11eb-8e90-bfad4245a6a5.png)
So far I've seen this in: "Pneumatic Armor Overview", "Pneumatic Chestplate"

**Comment by desht** [comment]
Thanks for catching those.  I found a couple more in the Heat & Aerial Interface pages too; will all be fixed for the next release.

**Comment by desht** [comment]
Fixed in 2.12.3
