### ISSUE TITLE
Oil not acting like a fluid, in the sense that the player doesn't swim in it

### ISSUE THREAD

**Issue by lampshaded** [TeamPneumatic/pnc-repressurized#809]
### Enigmatica 6 0.4.11

When my character jumps into a pool of PneumaticCraft Crude Oil, the player just falls through, like it's empty air, rather than swimming like it's water. 

I'm playing PNC-R as a part of Enigmatica 6, and I haven't attempted to replicate it without the modpack, and I could do so if that would be helpful. 

This appears to be a similar issue as in this issue from original PneumaticCraft:

https://github.com/MineMaarten/PneumaticCraft/issues/663

This issue appears to have something to do with Material.water, which apparently might have unintended consequences. This is apparently a common issue with modded fluids. 

If this is intentional behaviour, then I apologize. Cheers.

**Comment by desht** [comment]
See #792
