### ISSUE TITLE
[2.12.3-187/8] Crash when reloading world with minecolonies.

### ISSUE THREAD

**Issue by radiomike** [TeamPneumatic/pnc-repressurized#811]
### Minecraft Version
1.16.5
### Forge Version
36.1.23
### Mod Version
2.12.3-187/8
### Describe your problem, including steps to reproduce it

Single player. 
1. Start modpack
2. Start world - all fine
3. Stop world, return to menu - all fine
4. reload world. 
5. Crash - see attached logs

### Any other comments?
Initially seen in All the mods 6 1.6.4.
Tested mod by itself, no issues
Introduced minecolonies and structurize. Crash!!

[crash-2021-05-24_23.05.41-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/6535233/crash-2021-05-24_23.05.41-client.txt)

**Comment by radiomike** [comment]
Have also tested with latest minecolonies, same crash occurs.
[crash-2021-05-24_23.33.52-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/6535295/crash-2021-05-24_23.33.52-client.txt)

**Comment by desht** [comment]
Looks like a timing issue between Minecolonies and PNC.  Minecolonies does clientside fuel discovery when tags are reloaded (on server reload), which triggers a search of PNC's fuel recipes, and a recipe manager search needs an available world, which appears to be null when a reload is in progress.

I've worked around this so there at least isn't a crash (although an error message will probably still be logged), but can you please test with build 189 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ ?

**Comment by desht** [comment]
By the way, the effect of this is that Minecolonies won't see PNC fuel sources (e.g. buckets of LPG/Kerosene etc.) on the client.  Probably not a game-breaker.  Not sure there's much else to be done here, although I might have a chat with the Minecolonies guys and see if there's an alternative approach.

**Comment by radiomike** [comment]
Just tested that build. Both with the minimal install and then dropped into the atm6 pack. Can confirm reloading worlds works now, though appreciate the current caveat.

**Comment by desht** [comment]
Fixed in 2.12.5 release
