### ISSUE TITLE
Crash with create schematics

### ISSUE THREAD

**Issue by TheOnlyMann** [TeamPneumatic/pnc-repressurized#812]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.1.18
### Mod Version
2.12.5-190
### Describe your problem, including steps to reproduce it
[crash-2021-05-28_16.57.13-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/6559256/crash-2021-05-28_16.57.13-client.txt)
Crashes when used inconjunction with create's schematicanon, it will try to display pressure chamber glass and then it crashes.
### Any other comments?
TESTED WITH CREATE 0.3.1C

**Comment by desht** [comment]
Fixed in 2.13.0
