### ISSUE TITLE
Removing fluids from heat_block_properties? Feature request

### ISSUE THREAD

**Issue by G-Stav** [TeamPneumatic/pnc-repressurized#813]
Did a bit of looking around and here https://github.com/TeamPneumatic/pnc-repressurized/issues/763#issuecomment-799766290 it was mentioned that a blacklist wouldn't be needed, but imo it would be nice to be able to remove some of the weirder ones, like oil turning into ice. Or molten metals turning into ice. Maybe this already is a feature but I've tried with datapacks and crafttweaker and I'm not really sure on how to do it!

**Comment by desht** [comment]
Right now, all fluids get auto-added with a temperature based on what the mod defines for the fluid.  But as you noticed, any hot fluids turn to obsidian and any cool fluids turn to ice (when heat is removed).

There isn't a way at the moment to disable this auto-adding, but that would be pretty easy to add, so sure why not.  Although I'd probably keep the behaviour for vanilla lava & water (they can always be overridden with datapack entries anyway).

**Comment by desht** [comment]
Added in 2.13.0
