### ISSUE TITLE
Unable to set target filter in turret

### ISSUE THREAD

**Issue by memesanddremes** [TeamPneumatic/pnc-repressurized#814]
### Minecraft Version
1.12.2

### Forge Version
14.23.5.2847

### Mod Version
1.12.2-0.11.15-398

### Describe your problem, including steps to reproduce it
As the title implies, I am unable to set the target filter in the turret, as in I cant type in the target filter.
To reproduce place down a turret and try to set the entity target.

### Any other comments?
Could this be caused by a mod incompatibility since it never happens on any other modpacks?

list of mods I was using:
https://pastebin.com/raw/w4ajuptz

keep up the good work

**Comment by desht** [comment]
Sorry, 1.12.2 is long out of support
