### ISSUE TITLE
Feature Request: Getting The Elevator Direction

### ISSUE THREAD

**Issue by YetiWiz** [TeamPneumatic/pnc-repressurized#815]
When using an elevator with the elevator caller, there is no way to tell whether the floor chosen is above or below the current one. In other words, the elevator moving direction cannot be retrieved.
This information would be useful when creating more elaborate elevator builds with CC: Tweaked.
The suggestion is to either have the elevator base output a redstone signal of different strengths depending on the direction, or just using Lua methods to retrieve the elevator velocity.

**Comment by desht** [comment]
As discussed on Discord, it's actually possible to use the existing `getTargetHeight()` and `getCurrentHeight()` Lua methods to determine which way the elevator is going.  However, getting its current velocity is easy enough to add and might be useful for something so why not?

**Comment by desht** [comment]
Added in 2.13.0
