### ISSUE TITLE
speed upgrades crafting issue

### ISSUE THREAD

**Issue by gameplays12303** [TeamPneumatic/pnc-repressurized#816]
### Minecraft Version
16.5
### Forge Version
36.1.25
### Mod Version
-1.16.5-2.12.5-190
### Describe your problem, including steps to reproduce it
try to craft speed up grades in survival  (you see the problem ) also jei says it doesn't require lubricant i have tried with lubricant both sugar and the other both with lapist and the upgrade units also it's i only tried in refined storage crafting terminal 
### Any other comments?
if you don't have a problem  then i don't know why i am

**Comment by desht** [comment]
Works absolutely fine here and JEI shows that lubricant is indeed required (either in a bucket or any suitable fluid tank)
![image](https://user-images.githubusercontent.com/736831/120887302-eed63680-c5e9-11eb-8ae1-34f82d4b28c0.png)

If the lubricant isn't showing up, then something has probably messed up fluid tags in your instance.  Not a PNC problem.

**Comment by gameplays12303** [comment]
how do i go in fixing that
