### ISSUE TITLE
pneumaticcraft:pneumaticcraft:refinery?

### ISSUE THREAD

**Issue by Alcates** [TeamPneumatic/pnc-repressurized#819]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
31.6.0
### Mod Version
1.16.5-2.12.5-190
### Describe your problem, including steps to reproduce it
Having both Pneumaticcraft and JEITweaker installed causes this error to appear upon reload, which I believe is the source of an issue I'm having with JEITweaker.
https://gist.github.com/n2galaxy/576c03e4757a91d1ad701d3ad30baac9#file-latest-log-L7622
(edited because that line was wrong)
### Any other comments?
Thanks in advance.

**Comment by desht** [comment]
Can I see your JEITweaker startup scripts please?

**Comment by Alcates** [comment]
Here you go.
https://pastebin.com/fbw3azpJ
https://pastebin.com/m0QQVCPS

**Comment by desht** [comment]
Yep. As I thought, you have an error in your script. Search for refinery and it will be very very obvious.
