### ISSUE TITLE
Air Grate is not moving Item Entities

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#820]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5

### Forge Version
36.1.31

### Mod Version
1.16.5-2.12.5-190

### Describe your problem, including steps to reproduce it

The Air Grate Tube Module is not affecting Item entities.

Steps to reproduce:

1. Attach a Pressure Tube to a Creative Compressor.
2. Attach an Air Grate Tube Module to the Pressure Tube.
3. Set the pressure in the Creative Compressor to 5 bar.
4. Throw an item in front of the Air Grate.
5. Change the pressure in the Creative Compressor to -1 bar.
6. Throw an item in front of the Air Grate.
7. Right click the Air Grate with an advanced PCB.
8. Right click the Air Grate to open the config GUI
9. Type "@item"
10. Throw an item in front of the Air Grate

Note that for all of these configurations, item entities are not being attracted/repelled. Mobs and players are still moved correctly, just not items. Haven't checked Xp orbs yet

**Comment by desht** [comment]
Fixed in 2.13.0
