### ISSUE TITLE
Crash after entering bad alt+character into Aphorism Tile

### ISSUE THREAD

**Issue by ghost** [TeamPneumatic/pnc-repressurized#822]
### Minecraft Version
1.16.5

### Forge Version
36.1.6

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.12.5-190

### Describe your problem, including steps to reproduce it
Minecraft crashes if I type `alt+g` into an Aphorism Tile followed by enter.
1. Create an Aphorism Tile.
2. Leave the flavor text, just press `alt+g`.
3. Press enter.

Crash log: https://gist.github.com/mc-ganduron/c9e4b300d90c977df25dbfe79c7e04f7

### Any other comments?
Let me know if there are any more details you need.

**Comment by desht** [comment]
Fixed in 2.13.0
