### ISSUE TITLE
Feature Suggestion: Slight QoL improvements for easier right-clicking

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#827]
1. Make the Crop Support proxy right clicks to the block it's placed on. At the moment, if I place a Crop Support on bare farmland, I have to align my cursor carefully on the edge of the block to get a successful crop placement, which is difficult to do when trying to plant things quickly. A simple solution to this would be to proxy the right click on the Crop Support directly to the block below it if the player is attempting to plant a crop.
2. An option in the Aphorism Tile that when enabled, makes the Aphorism Tile proxy right clicks through to the block behind it, except when holding another Aphorism Tile. This'll make it easier to access chests when using the Aphorism Tile in invisible mode as a chest icon.

**Comment by desht** [comment]
1. Yeah that would be a nice QoL feature.  If the block the support is on is air (i.e. not a crop), proxy to the solid block underneath, if any.  Otherwise proxy to the contained crop itself.
1. Would right clicking with a tile in hand open the editor, then?  Or maybe require sneak-right-click with empty hand to edit if click proxying is enabled?

**Comment by HipHopHuman** [comment]
> 1. Yeah that would be a nice QoL feature.  If the block the support is on is air (i.e. not a crop), proxy to the solid block underneath, if any.  Otherwise proxy to the contained crop itself.

Sounds perfect!

> 2. Would right clicking with a tile in hand open the editor, then?  Or maybe require sneak-right-click with empty hand to edit if click proxying is enabled?

Yes. So basically tiles will behave as they always do with this config off - with it on, the tile becomes inaccessible the normal way so there needs to be a way to bypass the click-through. The "with a tile" was just my idea for how a bypass could be done. It could be done other ways, like with a sneak right click of an empty hand - although that specifically does make me apprehensive, some part of my brain is telling me, "what if there's a bespoke arbitrary mod out there that adds tile entities with their own sneak-right click behavior?". Maybe I'm being too defensive here and there's no need to worry, but I do think clicking with an Aphorism Tile will reduce the potential for any conflict

**Comment by desht** [comment]
> but I do think clicking with an Aphorism Tile will reduce the potential for any conflict

Only downside I can see to that is if the player doesn't have any Aphorism Tiles to hand, edits a tile and then realises they can't edit it anymore without going to get (or possibly make) another tile.  Given that tiles can be found in-world before the technology to make them exists, this could be quite an annoyance.

**Comment by HipHopHuman** [comment]
> Only downside I can see to that is if the player doesn't have any Aphorism Tiles to hand, edits a tile and then realises they can't edit it anymore without going to get (or possibly make) another tile. Given that tiles can be found in-world before the technology to make them exists, this could be quite an annoyance.

Good point. Perhaps do a runtime validation that they have Aphorism Tiles in their inventory before they can turn the option on? The *intended* use case for this is for labelling chests, so I imagine the "target market" for this feature has a high likelihood they're carrying multiple Aphorism Tiles on them, that validation will catch the edge-cases.

**Comment by desht** [comment]
Both features are in build 197, please give them a go :)

I decided to go with "right-click with empty hand opens GUI" - sneak & right-click works in all cases, but you must be sneaking to open the editor if the tile is currently invisible.  Seems to work very well in my testing and feels nicely intuitive.

**Comment by HipHopHuman** [comment]
Sheesh you work fast. I mean, I knew it already from back when you did the Aphorism Tile overhaul but still, it impresses me. I've just given it a test and this is *so* much better than it was before. I can spam-plant the crops again! :D I did however do a little test to bonemeal some wheat seeds and it seems like the normal old behavior, though the edge hitbox on that is pretty forgiving so it isn't so bad. Great work :D

**Comment by desht** [comment]
:)

The bonemealing issue should be easy enough to fix, I believe.

**Comment by desht** [comment]
Added in 2.13.0
