### ISSUE TITLE
Key Binding for Pneumaticraft Helmet Overrides Vanilla Swap Items Key

### ISSUE THREAD

**Issue by Darkosto** [TeamPneumatic/pnc-repressurized#83]
### Describe your problem, including steps to reproduce it

Vanilla minecraft introduced using both hands and by default the key to swap items is "F". Is it possible to switch the keybinding for your helmet so the item swap still works?

**Comment by desht** [comment]
Yeah, that's a reasonable request.  Did you have any thoughts on an alternative default?

**Comment by Darkosto** [comment]
"U" works pretty well, especially to keep it clustered together.

**Comment by desht** [comment]
OK, U it is then! That's in the latest build.
