### ISSUE TITLE
Crash after pressing escape in "Change Area Type" inventory screen of GPS Area Tool GUI

### ISSUE THREAD

**Issue by ghost** [TeamPneumatic/pnc-repressurized#831]
### Minecraft Version
1.16.5

### Forge Version
36.1.6

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.12.5-190

### Describe your problem, including steps to reproduce it
1. Create a GPS Area Tool.
2. Set the positions.
3. Open the tool's GUI.
4. Click "Change Area Type".
5. Click the button under P1.
6. After the inventory screen appears, hit escape.

https://user-images.githubusercontent.com/83793683/123021554-e9bf0880-d399-11eb-84c8-f340db9f8498.mp4

stacktrace: https://gist.github.com/mc-ganduron/913d15c374b9fb427ae9a5fa1f63f2e1

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Fixed in 2.13.0
