### ISSUE TITLE
Stuck in crawl/swim pose after Jet Boots lose all pressure in mid-flight

### ISSUE THREAD

**Issue by ghost** [TeamPneumatic/pnc-repressurized#832]
### Minecraft Version
1.16.5

### Forge Version
36.1.6

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.12.5-190

### Describe your problem, including steps to reproduce it
Losing all boot pressure while in mid-flight leaves the player in the crawl/swim pose. Taking off the boots has no effect, and neither does putting them back on. The only thing I've found to fix it is to add pressure back to the boots.

1. Equip Pneumatic Boots with Jet Boots I.
2. Fly forward until the boots lose pressure and can't sustain flight.

![image](https://user-images.githubusercontent.com/83793683/123134748-bb334300-d416-11eb-9c04-092afbdbb59a.png)

### Any other comments?

This would make for a pretty cool effect in a mermaid mod.

**Comment by desht** [comment]
Fixed in 2.13.0
