### ISSUE TITLE
Request: Allow tracking "minecart with chest"

### ISSUE THREAD

**Issue by ghost** [TeamPneumatic/pnc-repressurized#833]
Currently the Entity Tracking and Block Tracking upgrades ignore minecarts with chests. I'd like to request that they be tracked. (Maybe there's an argument to track all minecarts, I'm not sure.) I assume it's only living entities that are tracked now: 

https://github.com/TeamPneumatic/pnc-repressurized/blob/8500828e612db62212483cd67677369dc0af9cfc/src/main/java/me/desht/pneumaticcraft/client/render/pneumatic_armor/upgrade_handler/EntityTrackerClientHandler.java#L94-L96

No tracking currently:

![image](https://user-images.githubusercontent.com/83793683/123167749-92be3f80-d43c-11eb-91a3-273a05f8168b.png)

Thanks.

**Comment by ghost** [comment]
> I assume it's only living entities that are tracked now...

My mistake, I see other entities are also tracked.

Here is a quick prototype of entity tracking on minecarts. Maybe hopper & chest inventories could be listed.

Non-container:
![image](https://user-images.githubusercontent.com/83793683/123177742-7675cf00-d44b-11eb-8c25-7a5559b9c873.png)

Container:
![image](https://user-images.githubusercontent.com/83793683/123177779-84c3eb00-d44b-11eb-9684-eb68599de1ed.png)

**Comment by desht** [comment]
Yeah probably no reason not to track these. Would be handy to find them in mineshafts...

Update: I'll include all minecart types as an option in the entity tracker (can use filter `@minecart` to select them, by the way). 

I will not be including chest & hopper minecart inventories, mainly for technical reasons; that would involve some significant changes to the protocol to request entity inventory sync.  That will likely happen in 1.17+, where a rewrite of the whole pneumatic helmet tracker protocol is planned anyway.

**Comment by desht** [comment]
Added in 2.13.0
