### ISSUE TITLE
$owner_look variable is missing documentation in Patchouli manual

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#835]
### Minecraft Version
1.16.5

### Forge Version
36.1.32

### Mod Version
PneumaticCraft: 1.16.5-2.13.0-197
Patchouli: 1.16.4-51

### Describe your problem, including steps to reproduce it

The special drone variable `$owner_look` is not documented in the PneumaticCraft manual.

**Comment by desht** [comment]
Doh!  and I just uploaded the 2.13.0 beta release.

Will fix this for 2.13.1.  Meantime see the changelog for 2.12.5:

* Added new $owner_look drone special variable
  * Returns a vector where X/Y/Z can be any of -1, 0 or 1 based on the direction the drone's owner is currently facing

**Comment by desht** [comment]
Fixed in 2.13.1
