### ISSUE TITLE
Yeast Culture spread voids waterlogged blocks in target water source block 

### ISSUE THREAD

**Issue by ChromaPIE** [TeamPneumatic/pnc-repressurized#836]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version 
1.16.5
### Forge Version 
36.1.32
### Mod Version 
2.13.0-199
### Describe your problem, including steps to reproduce it
As has been said in the title. Reproducing step:
- make a horizontally two-block space, one for yeast culture and the other for water, just as all would do
- Pour a bucket of yeast culture out, throw some piles of sugar in it, as normal
- No hurry, before filling the other space with water, first place any waterloggable blocks like iron bars, signs or even pressure tubes in that space, if everything goes right the yeast culture source block would be blocked from flowing
- Pour the water into that space
- Spread triggered, the water source block together with the waterloggable block are replaced by a new born yeast culture source block.
### Any other comments?
I do know that those blocks are waterloggable but not Yeast-Culture-loggable so I won't expect those blocks could live in harmony with yeast culture. However the behavior described above is pretty much like a bug, so it's seemingly fairly better to just block the spread if there exists a waterloggable block in the target water source block.

**Comment by desht** [comment]
Yeah, preventing the spread is probably the best policy here.

**Comment by desht** [comment]
Fixed in 2.13.1
