### ISSUE TITLE
Jet Boots Hover Thrust Control

### ISSUE THREAD

**Issue by underscorched** [TeamPneumatic/pnc-repressurized#837]
Hello! I would like to see a way to adjust the percentage of "hover thrust" (the jet boots preventing the player from falling). This could be implemented as a percentage slider on the Jet Boots configuration GUI or (especially ties into my use case) only have the player not fall (with the Tier 5 jet boots) when builder mode is enabled, and have the player fall at the same rate the Tier 4 hover boots do otherwise. Thank you so much!

**Comment by desht** [comment]
I'm confused. Why would you want to deliberately nerf the given functionality? What is the actual use case here?

**Comment by underscorched** [comment]
To use staircases without having the jetboots off. Its a nuisance to either have the jetboots off or consistently hold sneak while descending a staircase.

**Comment by desht** [comment]
I wonder if there's a smarter way to this, by checking if the block below the player are stairs (and the downward direction is the same as the player's facing), and if so allowing descent rather than hovering...

**Comment by desht** [comment]
I have a possibly better solution: see #838 and let me know if it meets your needs...

**Comment by desht** [comment]
Actually going to close this since 838 addresses roughly the same problem, and any solution to that will address this issue too.

If you can, please try out the dev build linked in 838 and let me know if the Smart Hover mode is useful to you.
