### ISSUE TITLE
Keybing for making the jetboots activation key be something other than jump

### ISSUE THREAD

**Issue by MaddoScientisto** [TeamPneumatic/pnc-repressurized#838]
Right now the jet boots, if enabled, activate as soon as jump is pressed, therefore negating the jump action.
There should be either a way to bind the activation to something else or to change the activation method (something like holding the jump button again after jumping

**Comment by desht** [comment]
This could actually be trickier than I originally thought when we spoke on Discord.

The fundamental issue is that as soon as the player is off the ground, if the jet boots are enabled, they go into hover mode.  Which is intended - you can step off a cliff and not plummet to the ground.

Now, it would be extremely easy just to add another keybind for "jetboots thrust", and default it to Space.  **Hoewever**, this doesn't help with jumping - as soon as the player jumps, and they're off the ground, the hover functionality of the jetboots kicks in again.  And then we're back to needing to toggle the jetboots off with the hotkey to get normal jump functionality.

So, not sure if there's a really good solution to this...

**Comment by MaddoScientisto** [comment]
There are many times where I just want to plummet without engaging the thrusters or going into hover, for instance very low drops or even stairs, which I notice become very annoying to navigate with the jet boots enabled, perhaps it's the auto engagement of hover mode that is the problem

**Comment by desht** [comment]
I suppose a straight hover-toggle could be an option here... so the boots can be switched on, and thrust is enabled, and on the understanding that you'll basically plummet from the sky if you take your finger off the thrust key.

**Comment by MaddoScientisto** [comment]
I feel like the best way (for me at least) would be:
ground -> ungrounded (both jumping and falling off a ledge) : don't engage hover
ungrounded + press thrust : engage hover and thrust
keep hover on as usual until grounded again

**Comment by desht** [comment]
I think I might have something workable.  Basically a "Smart Hover" mode, off by default, but can be bound to a key like the other jet boots modes (and also appears as a toggle button in the Jet Boots armor screen).

When off, the boots behave as they do now, with hover kicking in as soon as the player's feet are off the ground.
When on, hover *only* kicks in when the thrust key is pressed.  Stepping off an edge or jumping won't engage hover.

Also adding a separate keybind for the thrust key (default Space, like it is now).  So you can bind thrust to some other key, switch on Smart Hover, and run & jump around with the Jet Boots switched on, and they won't interfere until you deliberately start flying.  Sounds good?

**Comment by desht** [comment]
If you'd like to test out a dev build, you can try build 200 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ which has this functionality.  Note: it's a dev build, not recommended for use in a proper world.  A test world is suggested...

**Comment by TeamSpen210** [comment]
Another solution might be to engage the boots only once you fall more than 2 blocks (and would begin to take fall damage). Then you could walk down stairs and short drops, but it'd activate on cliffs.

**Comment by desht** [comment]
Unfortunately there's no one-size-fits-all solution here which will make everyone happy.  I think the Smart Hover added in build 200 is good compromise, but it needs people to test it and provide feedback :)

**Comment by MaddoScientisto** [comment]
> 
> 
> I think I might have something workable. Basically a "Smart Hover" mode, off by default, but can be bound to a key like the other jet boots modes (and also appears as a toggle button in the Jet Boots armor screen).
> 
> When off, the boots behave as they do now, with hover kicking in as soon as the player's feet are off the ground.
> When on, hover _only_ kicks in when the thrust key is pressed. Stepping off an edge or jumping won't engage hover.
> 
> Also adding a separate keybind for the thrust key (default Space, like it is now). So you can bind thrust to some other key, switch on Smart Hover, and run & jump around with the Jet Boots switched on, and they won't interfere until you deliberately start flying. Sounds good?

This one sounds really good to me

**Comment by underscorched** [comment]
> I think I might have something workable. Basically a "Smart Hover" mode, off by default, but can be bound to a key like the other jet boots modes (and also appears as a toggle button in the Jet Boots armor screen).
> 
> When off, the boots behave as they do now, with hover kicking in as soon as the player's feet are off the ground.
> When on, hover _only_ kicks in when the thrust key is pressed. Stepping off an edge or jumping won't engage hover.
> 
> Also adding a separate keybind for the thrust key (default Space, like it is now). So you can bind thrust to some other key, switch on Smart Hover, and run & jump around with the Jet Boots switched on, and they won't interfere until you deliberately start flying. Sounds good?

Im going to try the dev build out and see if this works.

**Comment by underscorched** [comment]
> > I think I might have something workable. Basically a "Smart Hover" mode, off by default, but can be bound to a key like the other jet boots modes (and also appears as a toggle button in the Jet Boots armor screen).
> > When off, the boots behave as they do now, with hover kicking in as soon as the player's feet are off the ground.
> > When on, hover _only_ kicks in when the thrust key is pressed. Stepping off an edge or jumping won't engage hover.
> > Also adding a separate keybind for the thrust key (default Space, like it is now). So you can bind thrust to some other key, switch on Smart Hover, and run & jump around with the Jet Boots switched on, and they won't interfere until you deliberately start flying. Sounds good?
> 
> Im going to try the dev build out and see if this works.

seems good enough for my purposes. I only really wanted the smart hover. (#837 explains my frustrations with that lol.)

**Comment by desht** [comment]
Added in 2.13.1
