### ISSUE TITLE
Suggestion/Cross-mod bug: Better support for Inventory Tweaks Renewed's Sort function

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#840]
### Minecraft Version

1.16.5

### Forge Version

36.1.32

### Mod Version

Inventory Tweaks Renewed: 1.16.4-1.0.1 (Beta)
PneumaticCraft: Repressurized: 1.16.5-2.13.1-200

### Describe your problem, including steps to reproduce it

The *Inventory Tweaks: Renewed* mod adds a GUI button/middle click function to almost every inventory that when clicked, will auto-sort that inventory (a bit like Quark's sort feature). The problem is that when this function is activated on any PneumaticCraft machine that can hold upgrades, the upgrades are ejected from their upgrade slots and inserted into the machine's main inventory.

The button looks like this:
![image](https://user-images.githubusercontent.com/70091260/124137491-063bfe80-da86-11eb-9b10-1a0da88f92f5.png)

Steps to reproduce:

Install PNC:R
Install InvTweaks
Make a creative test world
Place a Smart Chest
Insert any upgrades into the Smart Chest's upgrade slots
Insert any random items into the Smart Chest's main inventory
Click the "Sort" button

What should happen: The items in the main inventory are sorted, and the upgrades stay in the upgrade slots
What actually happens: The upgrades are transferred from the upgrade slots to the main inventory

### Any other comments?

Is it even possible to hide upgrade slots from other mods? Is this behavior intentional so that upgrades can be hoppered in/out? If so, should I place an issue report on the InvTweaks repo?

**Comment by desht** [comment]
I'll check the mod and see if there's some kind of API to make it ignore certain slots...

**Comment by HipHopHuman** [comment]
Ah, I should have looked a bit harder, it seems you and duncan have spoken about this issue before

https://github.com/TeamPneumatic/pnc-repressurized/issues/613
https://github.com/reo-ar/InvTweaksRenewed/issues/20

**Comment by desht** [comment]
Yeah, I'm gonna go with my previous answer and call this an Inventory Tweaks bug still.

**Comment by desht** [comment]
See https://github.com/reo-ar/InvTweaksRenewed/issues/20#issuecomment-872599122 for a more detailed explanation.  Nothing I can do here; this is on InvTweaks to sort out (pardon the pun).
