### ISSUE TITLE
[Not a bug, but...] 1st-Person off-hand Minigun looks slightly suggestive/NSFW

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#844]
### Minecraft Version

1.16.5

### Forge Version

36.1.32

### Mod Version

2.13.1-201

### Describe your problem, including steps to reproduce it

This looks a bit naughty, especially when I spam right-click a lot 😅 

![image](https://user-images.githubusercontent.com/70091260/124397303-6ee9dc00-dd0f-11eb-8fa0-5e891f5195d8.png)

### Any other comments?

- Bonk.
- Here is video for sake of better demonstration https://streamable.com/2t4zt2
- Assuming no other issues have been opened/closed since this issue was opened, look at the current issue count. kekw

**Comment by desht** [comment]
This is actually a bug, although cosmetic (and yeah slightly rude hehe)

Anyway, will be fixed in 2.13.1

**Comment by desht** [comment]
Fixed in 2.13.1
