### ISSUE TITLE
Refinery Controller GUI ignores Refinery Outputs until quitting/reloading game

### ISSUE THREAD

**Issue by ghost** [TeamPneumatic/pnc-repressurized#845]
### Minecraft Version
1.16.5

### Forge Version
36.1.6

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.13.0-199

### Describe your problem, including steps to reproduce it
The Refinery Controller block claims that I have an invalid number of Refinery Outputs and appears to be nonfunctional, despite 4 Outputs stacked on it. Quitting and loading the game fixes this problem.

1. Create a new game.
2. Place a Refinery Controller.
3. View the Refinery Controller's GUI. (This step matters!)
4. Place 4 Refinery Outputs on the Controller. Add lagging, heat, and crude oil.
5. View the Refinery Controller's GUI.
6. Quit the game, load the game.
7. View the Refinery Controller's GUI.

Refinery structure (back and top have lagging):

![2021-07-05_20 41 33](https://user-images.githubusercontent.com/83793683/124534536-15021880-ddda-11eb-82dd-e24bad10b685.png)

GUI after placing all parts:

![2021-07-05_20 41 47](https://user-images.githubusercontent.com/83793683/124534544-16cbdc00-ddda-11eb-9515-04361d8ff61a.png)

GUI after quitting and reloading (the "problems" tab is complaining about the temperature since there was an exposed surface):

![2021-07-05_20 42 12](https://user-images.githubusercontent.com/83793683/124534550-19c6cc80-ddda-11eb-8698-e8651a5d2ba3.png)

### Any other comments?

1. The crude oil is being consumed despite the GUI's complaints.
2. With JEI installed, the recipes tooltip on the GUI correctly lists the number of Controllers.

**Comment by desht** [comment]
Sounds like the client is wrongly caching the fact that the outputs are missing. The server is processing the oil correctly?

Update: I think I see the problem (it is a caching issue - I use the same code to find the controller's neighbours on client & server, and the cached results are properly cleaned on the server when outputs are placed, but not on the client).  Should be an easy fix.

**Comment by desht** [comment]
Fixed in 2.13.1
