### ISSUE TITLE
Regulator Tube Module with Advanced PCB (in simple mode) does not shut off when Redstone Signal applied

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#848]
### Minecraft Version
1.16.5

### Forge Version
36.1.32

### Mod Version
2.13.1-202

### Describe your problem, including steps to reproduce it

The Advanced Regulator Tube Module ignores redstone signals when it is in simple mode.

I'm assuming that this is a bug, because it seems counter-intuitive that the basic regulator's threshold can be set to 0 with a redstone signal, but not the Advanced Regulator Tube Module when it is in simple mode.

Steps to reproduce:

1. Place a pressure tube leading into a vortex tube, powered by a creative compressor set to any pressure above 0.
2. Place a Regulator tube module on any of the pressure tubes connecting the compressor to the vortex tube.
3. Place a lever next to the Regulator module, and turn it on. Notice the threshold is set to 0 (it's easy to notice if you have The One Probe).
4. Now, install an Advanced PCB in the Regulator module.
5. Turn the lever off and on again to update the redstone signal.
6. Notice that the threshold is not changed.

**Comment by desht** [comment]
It might be a bit counter-intuitive, but it's not wrong.

Once you install an advanced PCB in a regulator, you're basically taking full responsibility for how the module reacts to redstone.  The default upgraded behaviour (in simple mode) is to obey the specified threshold, regardless of redstone signal.  If you want it to respond to redstone, you need to toggle "Advanced config" on, and set the interpolated threshold using the sliders.
