### ISSUE TITLE
While in Flight, Running Out of Air Pressure Will Force the Player in a Prone Position

### ISSUE THREAD

**Issue by SwissxCore** [TeamPneumatic/pnc-repressurized#849]
### Minecraft Version
1.16.5

### Forge Version
36.1.0

### Mod Version
1.16.5-2.12.5-190

### Describe your problem, including steps to reproduce it
Running out of air pressure in the pneumatic boots while in flight will cause the player to fall (as intended) however, it will force the player into a prone position, nothing I tried was able to cancel this animation; jumping, disabling the jet boots, removing the pneumatic boots, and swimming.

Step 1: Don a pair of pneumatic boots, ideally with low pressure so you don't have to fly around too much.
Step 2: Toggle the jet boots and fly close to the ground.
Step 3: Out of the player's control, but run out of air pressure (Do not toggle the boots off before this) falling to the ground.

### Any other comments?
I was able to take a clip using Windows Game Bar, so I apologise for any loss of quality.
https://youtu.be/9Civt8KLZdA

Also, I was quite low to the ground when this happened, perhaps it will only happen while low to the ground... Just something to consider.

And finally, I was able to stand up once more after refilling the boots slightly, equipping them, and toggling the jet boots on again.

**Comment by desht** [comment]
Already fixed in 2.13.0.
