### ISSUE TITLE
Tamed Foxhounds are seen as hostile by drones

### ISSUE THREAD

**Issue by Awesomespore** [TeamPneumatic/pnc-repressurized#854]
Quark adds foxhounds (fire doggos), which guard drones seem to see as hostile even when tamed (I made one and deployed it with no weapons and it seemed quite keen on targeting one of my foxhounds, though they didn't seem to damage them). Perhaps there could be an option in the config file to blacklist certain mobs from being targeted, or possibly just make an exception for foxhounds?

(Foxhounds are naturally hostile, unlike wolves)
![2021-07-16_12 44 07](https://user-images.githubusercontent.com/59407684/125875076-06662774-c4fc-40e4-a0a0-0d6d37c5eede.png)

**Comment by desht** [comment]
Yeah, the default behaviour of guard drones is to target anything that's a hostile mob (code-wise, any entity which implements `IMob`).

However, it looks like foxhounds also extend `TameableEntity`, so it wouldn't be hard to ignore mobs that are tamed.  I can add this for the next release.

**Comment by Awesomespore** [comment]
> Yeah, the default behaviour of guard drones is to target anything that's a hostile mob (code-wise, any entity which implements `IMob`).
> 
> However, it looks like foxhounds also extend `TameableEntity`, so it wouldn't be hard to ignore mobs that are tamed. I can add this for the next release.

Cool!

**Comment by desht** [comment]
Fixed in 2.13.2 release
