### ISSUE TITLE
Vegetable oil block is untranslated

### ISSUE THREAD

**Issue by Ch1216** [TeamPneumatic/pnc-repressurized#855]
### Minecraft Version 
1.16.5

### Forge Version 
36.1.4

### Mod Version 
2.13.1-202

### Describe your problem, including steps to reproduce it
1. Have some kind of waila mod (I use Jade) 
2. Look at the vegetable oil liquid block
3. See its untranslated 

### Any other comments?
its translation key is block.pneumaticcraft.vegetable_oil

**Comment by desht** [comment]
Fixed in 2.13.2 release
