### ISSUE TITLE
Programing Multiple Network APIs Puzzle Cost Calculation Error

### ISSUE THREAD

**Issue by Tekstack** [TeamPneumatic/pnc-repressurized#857]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
forge-1.16.5-36.1.16
### Mod Version
pneumaticcraft-repressurized-1.16.5-2.13.0-199
### Describe your problem, including steps to reproduce it
When using the programmer, if you have multiple Network APIs, you can program them all at once the cost of a single API. This not only lowers the overall puzzle piece cost, but if those individual APIs 'deprogramed,' you can have an endless supply of Puzzle Pieces.
See link below for example.

https://streamable.com/k7uj4l

**Comment by desht** [comment]
Yep, fixed it in dev already, will be in next release.

**Comment by desht** [comment]
Fixed in 2.13.2 release
