### ISSUE TITLE
Vacuum Pressure Chamber with Volume Upgrades loses vacuum on server start

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#858]
### Minecraft Version
1.16.5
### Forge Version
36.1.31
### Mod Version
pneumaticcraft-repressurized-1.16.5-2.13.1-202
### Describe your problem, including steps to reproduce it
Upon loading a world, pressure chambers in vacuum mode appear to briefly lose the volume from volume upgrades. The volume returns quickly, but the vacuum doesn't come back. So a chamber at -1 bar and 25 volume upgrades will reset to almost nothing on load.

1) Build pressure chamber
2) Add Volume Upgrades
3) Suck out all the air to -1 bar
4) Reload the world (quit to title, reload is enough in SP)

Vacuum pump with volume upgrades appears to work normally. Seems to only be an issue with the Vacuum Chamber itself. 

### Any other comments?
Before:
![2021-07-19_09 19 06](https://user-images.githubusercontent.com/9543430/126167064-e4317e13-afb7-4710-a207-6220c0460058.png)

After:
![2021-07-19_09 21 59](https://user-images.githubusercontent.com/9543430/126167069-57070448-0b33-4363-919f-eb5601a06df6.png)

**Comment by MuteTiefling** [comment]
Hrm, addendum: Just ran the same test with 3x3x3 chamber and it's working fine. So far only seeing this with 5x5x5 chamber and 25 volume.

**Comment by desht** [comment]
Hmm, if it works with 3x3x3, that's a good clue about where to look, thanks...

**Comment by desht** [comment]
Think I've fixed it - can you give build 206 a go when it's done?

**Comment by MuteTiefling** [comment]
will do, thanks :D

**Comment by MuteTiefling** [comment]
Yep, you seem to have gotten it. :D Good stuff!

**Comment by desht** [comment]
Fixed in 2.13.3 release
