### ISSUE TITLE
[Feature Suggestion] Heating and Cooling Upgrades

### ISSUE THREAD

**Issue by SwissxCore** [TeamPneumatic/pnc-repressurized#859]
Heating and cooling upgrades will prevent the cooling or negate the heating (respectively) of the block it's placed into by 5% per upgrade, with a maximum of 5 upgrades per block, these upgrades will also allow the block to heat up or cool down faster by the same rate.
As an example, installing a cooling upgrade into the advanced air compressor will slow the rate at which it heats up during use, and allow it to cool faster while idle by 5%, more if multiple upgrades are installed.
Whereas placing a heating upgrade into a refinery controller will allow it to heat up faster while in use and will slow the rate at which it cools while idle.

Recipe:
To create a cooling upgrade place a vacuum tube in the centre, place two heat frames to the left and right of the vacuum tube, and lastly place blocks of ice in the remaining spaces.
To create a heating frame, use the same recipe but replace the blocks of ice with a magma blocks.

These upgrades won't provide the cooling or heating that vortex tubes or blocks with cooling/heating properties would provide, but it will allow a portion of said heating/cooling in a compact area where placing a vortex tube or a temperature enabled block would not otherwise be possible.

These upgrades will work with any block that produces or uses temperature in some way.

Thank you.

**Comment by desht** [comment]
Sorry, but I don't plan to include something like this.  This is just a "magic block" way of making temperature management simpler, which is not in the spirit of the mod.  There are already ways to manage temperature in the mod so this isn't really necessary.
