### ISSUE TITLE
Exposed PCBs stack with unexposed PCBs

### ISSUE THREAD

**Issue by WazWaz** [TeamPneumatic/pnc-repressurized#86]
### Describe your problem, including steps to reproduce it

Shift click on exposed PCB in UV Light box while unexposed stack is in inventory.
Observe that the exposed one joins the others, becoming unexposed.

### Any other comments?

Other than how awesome this mod is? None.

**Comment by desht** [comment]
That's actually fixed in dev already. There will be a new beta out soon, but you can try dev builds from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized if you're interested.

**Comment by MineMaarten** [comment]
And the official build: https://minecraft.curseforge.com/projects/pneumaticcraft-repressurized/files/2513548
