### ISSUE TITLE
A random PNCR item disappears every time my FTB Endeavour Server starts up.

### ISSUE THREAD

**Issue by ZapdosVz** [TeamPneumatic/pnc-repressurized#862]
### Minecraft Version
1.16.5
### Forge Version
36.1.16
### Mod Version
1.16.5-2.12.1-186
### Describe your problem, including steps to reproduce it
Every time I restart my FTB Endeavour server(to help with lag) a random piece of my PNCR setup disappears. the first time it was an air line, the second time it was a valve in the air tank, the third time it was a compressor (but still made hissing noises yet was completely gone) the last time, a little bit ago, it was a random piece or air line. It wouldn't be that big of a deal if it didn't release all my pressure ever single time it happens.
### Any other comments?
Nothing else is disappearing from any other mod packs, just PNCR

**Comment by desht** [comment]
2.12.1 is pretty old.  Please try with the latest version - 2.13.2 - of the mod (there have been many many fixes and improvements since then) and then let me know if you're still having problems.

**Comment by desht** [comment]
Closed due to lack of response.
