### ISSUE TITLE
Game crash after Air Compressor explodes (semi-reproducible)

### ISSUE THREAD

**Issue by ghost** [TeamPneumatic/pnc-repressurized#865]
### Minecraft Version
1.16.5

### Forge Version
36.1.6

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.13.2-205

### Describe your problem, including steps to reproduce it
I was in creative mode testing the Spawner Extractor using an Air Compressor for pressure, Blocks of Coal for fuel, and maxed Speed Upgrades on the compressor and vacuum. The goal was to extract the spawner core as fast as possible. The compressor exploded and the game crashed.

I can reproduce the crash but not consistently. I don't think my setup matters to the underlying problem, it's just the only arrangement that I've gotten to fail.

Crash Log: https://gist.github.com/mc-ganduron/e303baebd89fca59db8f75639629648d

**Comment by desht** [comment]
Yep, I can see what's happening here.  It'll crash if the compressor has just exploded and the on/off state has just flipped in the same tick.  Easily fixed, though.

**Comment by desht** [comment]
Fixed in 2.13.3 release
