### ISSUE TITLE
[Localization] Certain Formatting of texts is unfriendly for localization

### ISSUE THREAD

**Issue by dovisutu** [TeamPneumatic/pnc-repressurized#866]
*code based on `1.16.4` branch when I wrote this, namely, at 1e0fbf27c07d1235f7f3f0d8185ce13ad2b92824*
*(Somehow I managed to put the latest commit wrong...)*

### Problem
Some of the texts in-game are formatted just by joining 2 localized parts together, which may be difficult to localize into a language with **different word orders**.

For example, see here:

https://github.com/TeamPneumatic/pnc-repressurized/blob/97c60951f63c00c53aa3d8395a50548fb3e40b77/src/main/java/me/desht/pneumaticcraft/client/render/pneumatic_armor/upgrade_handler/BlockTrackerClientHandler.java#L269-L286

This part of code is used to generate statistics of tracked blocks in the armor HUD.
It generates sentences like `5 Hackables` by *joining* the number 5 with a *translated term*.  It works for langauges like English, where numerals are put **before** nouns, and measure words (at least in this circumstance) are**n't** necessary.

However, in case of a language like Chinese, where measure words are usually **needed** *after* numerals, the translation must be prefixed with a measure word, which is somewhat awkward, yet *not impossible*; to generate a sentence like `5 个可入侵方块`(with the measure word `个`), the translation term should be `个可入侵方块`, which tends to let one think it's wrong, while that's indeed right.

Even worse, in case of a language where numerals are put **after** nouns, or measure words are put **before** numerals, or other cases, this sentence can**not** be properly translated at all, for in the current code, there's no way of switching the 2 parts. I don't have much knowledge to such language, though. It's said that Japanese is one of those langauges sometimes, but I'm not entirely sure.
### Suggestion
Change the current formatting to containing parameters *in* the translation term itself, like `%d Hackables`.

**Comment by desht** [comment]
Yes, valid point.  I can change the above code to sort that out.  If you spot any other places that need fixing please let me know.

**Comment by dovisutu** [comment]
Well, upon a search I find a bit more, while not as important as the one mentioned above:

Here, the code used `"` to mark the valuable name, while in some languages different quotations may be used (e.g. Chinese `“` `”`). Not a big deal, but makes it a bit annoying (especially if a language has quotation marks that are really different).
https://github.com/TeamPneumatic/pnc-repressurized/blob/c01fd6e3abadc51c117bf6a8b4099bb5b88f2f17/src/main/java/me/desht/pneumaticcraft/common/progwidgets/ProgWidgetCoordinateOperator.java#L211

Here, the same thing but for parentheses:
https://github.com/TeamPneumatic/pnc-repressurized/blob/8500828e612db62212483cd67677369dc0af9cfc/src/main/java/me/desht/pneumaticcraft/client/gui/widget/WidgetFluidStack.java#L84

What's interesting is that while searching, I happened to find several instances of hard-coded texts, which I'd like to mention here in addition: 
https://github.com/TeamPneumatic/pnc-repressurized/blob/9e2d4c63b5673a9bbe21f8369ad111ac49d472ff/src/main/java/me/desht/pneumaticcraft/common/thirdparty/theoneprobe/TOPInfoProvider.java#L140
https://github.com/TeamPneumatic/pnc-repressurized/blob/9e2d4c63b5673a9bbe21f8369ad111ac49d472ff/src/main/java/me/desht/pneumaticcraft/common/thirdparty/theoneprobe/TOPInfoProvider.java#L148
https://github.com/TeamPneumatic/pnc-repressurized/blob/97c60951f63c00c53aa3d8395a50548fb3e40b77/src/main/java/me/desht/pneumaticcraft/client/gui/pneumatic_armor/option_screens/DroneDebuggerOptions.java#L208
https://github.com/TeamPneumatic/pnc-repressurized/blob/6822dc0c8cd9525fb0b471b23ba50ac84e62a4e2/src/main/java/me/desht/pneumaticcraft/common/block/tubes/ModuleAirGrate.java#L286-L293
https://github.com/TeamPneumatic/pnc-repressurized/blob/c01fd6e3abadc51c117bf6a8b4099bb5b88f2f17/src/main/java/me/desht/pneumaticcraft/common/progwidgets/ProgWidgetDigAndPlace.java#L32-L35
https://github.com/TeamPneumatic/pnc-repressurized/blob/c01fd6e3abadc51c117bf6a8b4099bb5b88f2f17/src/main/java/me/desht/pneumaticcraft/common/progwidgets/ProgWidgetLiquidImport.java#L77-L79
https://github.com/TeamPneumatic/pnc-repressurized/blob/97c60951f63c00c53aa3d8395a50548fb3e40b77/src/main/java/me/desht/pneumaticcraft/common/item/ItemPneumaticArmor.java#L152

If one of them isn't intended to be shown in-game, just ignore that one. (Since I was in a hurry when doing so...)

**Comment by desht** [comment]
Fixed in 2.13.3 release

**Comment by dovisutu** [comment]
After looking back, I find that during the fix, key `pneumaticcraft.gui.progWidget.blockCondition.debug.allBlocksMatch` had been rewritten as `pneumaticcraft.gui.progWidget.blockCondition..allBlocksMatch`, with `debug` dropped. Is that intentional or accidental?

(Yeah, I know I should've posted it in a separate issue and reference this one, but I think it's too minor for one issue.)

**Comment by desht** [comment]
Accidental, looks like a typo crept in there.  Thanks for spotting it!

**Comment by desht** [comment]
Should be all fixed in 2.14.5 release, feel free to reopen (or create new issue) if you spot anything else that needs fixing.
