### ISSUE TITLE
Crash when removing closing pneumo-door

### ISSUE THREAD

**Issue by miuirussia** [TeamPneumatic/pnc-repressurized#87]
### Minecraft Version
1.12.2

### Forge Version
14.23.1.2575

### Mod Version
0.2.1-101

### Describe your problem, including steps to reproduce it
Crash when removing closing pneumo-door

[crash-2017-12-25_22.01.37-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/1586077/crash-2017-12-25_22.01.37-client.txt)

**Comment by MineMaarten** [comment]
Reproduced and fixed, thanks! We mostly tested the mod in creative worlds, where this does not happen :). Fixed in the version that will be uploaded to Curse in a minute!
