### ISSUE TITLE
Amadrone Does Not Support Side Pumping

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [TeamPneumatic/pnc-repressurized#871]
### Minecraft Version
1.16.5
### Forge Version
36.1.65
### Mod Version
1.16.5-2.13.2-205
### Describe your problem, including steps to reproduce it
1. Make Fluid Trade With Amadron Tablet Connected To Smeltery/Foundry Drain
2. Amadron Delivery Drone Dies (natural occurrence)
### Affected Mods
Tinkers' Construct (https://github.com/SlimeKnights/TinkersConstruct)

**Comment by desht** [comment]
Haven't looked at TiC closely, but I imagine the drain blocks are sided access only, and the Amadrone doesn't know about sides when accessing inventories or fluid tanks (it just looks for an unsided fluid capability).  While adding some sidedness is a possibility for a future release, it's very easy to work around this in the short term by pointing a Liquid Hopper at the smeltery drain, and using the hopper as a target for the Amadrone.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
it only pulls Fluid on top, not side
also add tinker's construct compatibility

**Comment by desht** [comment]
> also add tinker's construct compatibility

Explain, please?

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
so smeltery and foundry can have multiple fluids in a single multiblock and amadrone or drone can pull based on filter via smeltery/foundry drain

**Comment by desht** [comment]
No, I won't be adding that, sorry.  TiC already has ducts which can filter extraction into tanks; use those tanks as your Amadron fluid source.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
*triggered*

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
https://pastebin.com/gL6tH8dw read this

**Comment by desht** [comment]
?
