### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CaptainPlasma101** [TeamPneumatic/pnc-repressurized#872]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.12
### Forge Version
14.23.5.2854
### Mod Version
0.11.15-398
### Describe your problem, including steps to reproduce it
Crash
1. use io assembly thing
2. put inventory with items in it for io arm thing
3. destroy inventory while arm is moving
### Any other comments?
Playing PO3 latest ver (3.3.61)

**Comment by desht** [comment]
1.12 is not supported anymore, sorry.
