### ISSUE TITLE
Pressure chamber base volume changes when blocks are replaced

### ISSUE THREAD

**Issue by s-l-lee** [TeamPneumatic/pnc-repressurized#874]
### Minecraft Version
1.16.5

### Forge Version
36.2.0

### Mod Version
2.13.3-211

### Describe your problem, including steps to reproduce it

1. Build a pressure chamber larger than 3x3x3. 
2. Bring up the pressure chamber GUI and note the base volume.
3. Break a pressure chamber block.
4. Replace the broken block to complete the pressure chamber again.
5. Bring up the pressure chamber GUI and note the change in the base volume.

### Any other comments?
The base volume is multiplied by 2^3 for 4x4x4 pressure chambers and 3^3 for 5x5x5 pressure chambers with each repetition of steps 3 and 4 until it eventually overflows and wraps back around into the negatives.

**Comment by desht** [comment]
This fix looks good, thanks. Will do some testing on it in the next few days.

**Comment by s-l-lee** [comment]
Sure, no rush. Let me know if/when I should open a pull request or some other action on my part. I'm not familiar with this code and might not understand its conventions.
In the meantime, the in-game workaround seems pretty straightforward - break all pressure chamber valves, then replace them to reset the pressure chamber base volume.
Lastly, I just wanted to say the mod is great fun. I'm just only getting into it and greatly appreciate the progression in the PNC:R Manual.

**Comment by desht** [comment]
OK, tested and looking good - thanks!  No need to do a PR, I'll commit this now (and credit you in the changelog :).  Will be in the next release (pretty soon).

**Comment by desht** [comment]
Fixed in 2.13.4 release
