### ISSUE TITLE
[Feature Suggestion] Gas Tanks & Advanced Gas Tanks

### ISSUE THREAD

**Issue by SwissxCore** [TeamPneumatic/pnc-repressurized#875]
The gas tank will provide a solution for storing large volumes of compressed air in a small space, as well as providing the ability to transport this compressed air over distances without the use of pipes; in essence, this is the Pneumaticcraft equivalent of a battery for a mod that adds energy.

The gas tanks will be filled the same way as all other pressure based blocks and items, requiring external pressure to be greater to fill the tank, and lesser to empty. Unlike many pressure based blocks, these tanks can be right clicked with the pneumatic wrench to seal them, preventing them from discharging even when nothing is connected to them, this allows them to be tightly packed for bulk storage; additionally, they can only be connected to from the top, this will force the user to space out the tanks to fit pipes, meaning they can be used as a bulk storage, or a buffer, but not both.

Lastly, these tanks can be broken with a pickaxe and will retain their current air level, not requiring a pneumatic wrench, however, the pneumatic wrench will work at picking up the block as an item as well as long as the user crouches, not crouching as mentioned will seal and unseal the gas tank.

For the basic gas tank, containing a maximum of 5 bars of pressure, it will appear as a single air canister standing upright in the centre of the block, the top of the tank should change colour depending on if it's sealed or not so the user is able to determine it's state just by looking.
The advanced canister, containing a maximum of 20 bars of pressure, will appear as four basic canisters taking up the same block space with a frame surrounding it, all four will appears to be connected to a centre valve to which the user will connect, the same colouration will occur depending on if it's sealed or not.

**Comment by desht** [comment]
Thanks for the idea, but I'm afraid I'm not going to implement it, sorry.

There are already ways of storing a lot of air in the mod, as well as transporting it "wirelessly".  Air Canisters (which include a high pressure variant) are the prime example; they can be stored in any inventory and accessed via a Charging Module for large-scale air storage.  They can also be transferred using a vanilla Ender Chest and Aerial Interfaces (or use some ender storage mod).
