### ISSUE TITLE
Items containing Air (e.g, Amadron tablet) can go over normal pressure limits via disenchanting

### ISSUE THREAD

**Issue by fayk** [TeamPneumatic/pnc-repressurized#879]
### Minecraft Version
1.16.5
### Forge Version
36.1.31
### Mod Version
pneumaticcraft-repressurized-1.16.5-2.13.1-202.jar

### Describe your problem, including steps to reproduce it
If you place an enchantment (Holding) on an item like an Amadron tablet, fill it to 10.0 bar, then disenchant it with a grindstone, it seems to retain all the air. For example, it ended up showing as '80.0' bar afterward. 

To attempt to confirm this isn't just a cliient display issue, I checked the amount of air stored within it by looking at the NBT data in Integrated Dynamicis, which showed 239872 at the time it was 79.9 bar. Also, when placed in a charging station, I was able to watch it tick down smoothly as it equalized with the rest of the system.

Steps to Reproduce:
1. Craft an Amadron Tablet
2. Enchant the Amadron Tablet with some level of the 'Holding' enchantment (COFH Core?)
3. Fill the Tablet to 10.0 bar
4. Disenchant the tablet in a Grindstone
5. Observe the tooltip on the Tablet stating its pressure level.

### Any other comments?
Was playing on a dedicated server. Enigmatica 6 modpack, v0.5.6

**Comment by desht** [comment]
This is fixed in the 2.14.0 alpha release.  (While alpha, it is because of build system changes rather than major mod changes - it should be safe to use though as always do world backups, try on test world first etc.)...
