### ISSUE TITLE
Crash on startup related to Reflections

### ISSUE THREAD

**Issue by MineMaarten** [TeamPneumatic/pnc-repressurized#88]
Accidentally posted at the old PneumaticCraft repo: https://github.com/MineMaarten/PneumaticCraft/issues/908

https://github.com/MineMaarten/PneumaticCraft/files/1586140/crash-2017-12-25_21.41.56-client.txt

**Comment by MineMaarten** [comment]
@matyklugDebbuged : First of all, I'm a bit disturbed by the amount of core mods, and the stacktrace does suggest some weird stuff going on in the MC codebase PneumaticCraft is hooking into. I will try to find what is going on though.

I did just shuffle something around, which hopefully either fixes your issue magically, or should give us more information about what is going on. Could you try using this build: http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/103/

**Comment by desht** [comment]
Going to close this, we've not had any further reports.
