### ISSUE TITLE
Crafttweaker support problem - remove() doesn't work

### ISSUE THREAD

**Issue by Yarden-zamir** [TeamPneumatic/pnc-repressurized#883]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16
### Forge Version
36.2.2
### Mod Version
2.13.4-215
### Describe your problem, including steps to reproduce it
The explosion crafting and pressure chamber both implement IRecipeManager so the have .remove(IItemStack) but the output of those is is an array so it doesn't throw an error it just doesn't remove anything. The only way to remove is with removeAll()

**Comment by desht** [comment]
Yeah, I see the problem there.  As a workaround for now, I think `removeByName()` should work?

**Comment by Yarden-zamir** [comment]
Yea, that's what I am using. Thank you!

**Comment by desht** [comment]
This is fixed in the 2.14.0 alpha release. (While alpha, it is because of build system changes rather than major mod changes - it should be safe to use though as always do world backups, try on test world first etc.)...
