### ISSUE TITLE
Pressurized Spawners not working without a player nearby

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamPneumatic/pnc-repressurized#884]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5

### Forge Version
1.16.5-36.2.2

### Mod Version
[pneumaticcraft-repressurized-1.16.5-2.13.3-211.jar](https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized/files/3411628)

### Describe your problem, including steps to reproduce it

> ### Describe your issue
> 
> My PNC Pressurized spawners are not working without a player nearby, despite the description saying that they shouldn't require one.
> 
>     * The chunk and every chunk with machinery related to it is force loaded
> 
>     * There is definitely no air shortage
> 
>     * I used the same mob farm setup with Apotheosis spawners previously, and it worked fine without players nearby (Using spawner agitators)
> 
> 
> I have done the following tests:
> 
>     * Other processes (Hopper>Chest) seem to work fine even with no one nearby, so the actual chunk loading seems to be fine.
> 
>     * If every player on the server is in the nether, the spawner starts working again.
> 
> 

### Any other comments?
Additional details in the source issue: https://github.com/NillerMedDild/Enigmatica6/issues/3081

**Comment by ghost** [comment]
Lurker observations...

> My PNC Pressurized spawners are not working without a player nearby, despite the description saying that they shouldn't require one.

The source issue didn't cite the description around which the issue revolves, so I'll assume it's this line from the Guide:

> A Pressurized Spawner is a powerful device which uses pressure to spawn mobs. It doesn't care about light levels or player proximity [...]

It sounds like the question is whether "doesn't care about [...] player proximity" means "keeps its chunk loaded" or "has no strict distance requirement [like a vanilla spawner](https://minecraft.fandom.com/wiki/Spawner#Mechanics)":

> A [vanilla] spawner activates when a player comes within a spherical radius of 16 blocks from the center point of the block...

**Comment by TeamSpen210** [comment]
Are you more than 128 blocks from the spawner? It looks like the Pressurised Spawner doesn't prevent despawning, so they might be spawning then immediately despawning.

**Comment by NielsPilgaard** [comment]
That might be the case, yeah. Not preventing despawning is a bit counterintuitive when the spawner supposedly doesn't need a player nearby, in my opinion :)

**Comment by desht** [comment]
Yeah the spawner shouldn't care about player proximity when spawning, but you're right that it doesn't do anything specific to prevent *despawning*, and this is probably what's happening here.  I'll take a look into this.

**Comment by desht** [comment]
f4f70dc89dfa49f9da850db2d372832312f04b67

**Comment by desht** [comment]
This is fixed in the 2.14.0 alpha release. (While alpha, it is because of build system changes rather than major mod changes - it should be safe to use though as always do world backups, try on test world first etc.)...

@NillerMedDild feedback would be appreciated; if this looks good, I'll get a 2.14.1 release out very soon for inclusion in the next E6...

**Comment by NielsPilgaard** [comment]
The original reporter has verified that the despawning issue is fixed in the latest alpha 👍
