### ISSUE TITLE
Server crashes 

### ISSUE THREAD

**Issue by Fanky7949** [TeamPneumatic/pnc-repressurized#887]
### I accidentally used a wrench of the Galacticraft (the server has a modpack named "Lapito's Galacticraft") on a thermoprocessing plant. The machine has rotated and after some seconds the servers has crashed and everytime I try to rejoin it gives me this error: 

[crash-2021-08-29_00.01.21-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/7071592/crash-2021-08-29_00.01.21-client.txt)

**Comment by Fanky7949** [comment]
I managed to join the server for some seconds (after some seconds it crashes) and break the bugged blocks ; now the server runs normally

**Comment by desht** [comment]
1.12.2 is no longer supported, sorry.
