### ISSUE TITLE
GPS Tool Coordinate Manipulation Buttons are not altering the coords as expected

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#894]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.2.2
### Mod Version
pneumaticcraft-repressurized-1.16.5-2.14.2-247
### Describe your problem, including steps to reproduce it
Plus and Minus buttons in GPS gui don't manipulate the number as expected.

https://streamable.com/s549py

Seems it's concatenating instead of mathing :D

**Comment by desht** [comment]
Urgh, I bet that was another mappings screwup... Will take a look at it tomorrow morning.

**Comment by desht** [comment]
Yep, as I thought, next build will fix it.

In the meantime, adjusting values via scroll wheel (hold shift for fast adjust) should still work correctly.

**Comment by MuteTiefling** [comment]
Awesome thanks!

**Comment by desht** [comment]
Fixed in 2.14.3
