### ISSUE TITLE
JEI Layout is broken when looking at an Obsidian block

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#897]
### Minecraft Version
1.16.5

### Forge Version
36.2.4

### Mod Version
1.16.5-2.14.3-251

### Describe your problem, including steps to reproduce it

The JEI Recipe layout for Obsidian block is broken. Here are some pictures:

Dungeon Loot tab
![image](https://user-images.githubusercontent.com/70091260/133944342-69b161a7-3dfe-44e1-97e6-c80644ccbb92.png)

Fluid Mixer tab
![image](https://user-images.githubusercontent.com/70091260/133944352-decc6446-6493-4b7a-88fa-019615f19959.png)

### Any other comments?
I originally thought this was me adding Babel and Just Enough Piglin Bartering but I disabled those to check and it doesn't seem to be the case. Only other mod I have the f/s with JEI is Just Enough Resources.

**Comment by desht** [comment]
Bit of a wtf, but this is defintely something which has appeared in the dev code since the last release (I tested the public 2.14.2 and it doesn't happen there).

**Comment by HipHopHuman** [comment]
All fixed 🎆 
![image](https://user-images.githubusercontent.com/70091260/134076984-3a13f74e-394c-4bb9-8c66-6b94b10d5e76.png)
