### ISSUE TITLE
[Feature Request] Entity Tag support for vacuum_trap_blacklist

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#898]
Would be lovely if `vacuum_trap_blacklist` supported entity tags. 

For instance, I've set up a `enigmatica:mob_spawner_blacklist` tag for use in blacklisting things in Ars Nouveau and Industrial Foregoing. Being able to use the same tag with PNC would managing this list.

**Comment by desht** [comment]
Added in 2.14.5 release
