### ISSUE TITLE
Charging Station emits redstone with no item

### ISSUE THREAD

**Issue by Venom31** [TeamPneumatic/pnc-repressurized#901]
### Minecraft Version
1.16.5
### Forge Version
36.2.2
### Mod Version
1.16.5-2.13.3-211
### Describe your problem, including steps to reproduce it
1. Place down Charging Station and provide it with pressure.
2. Set 'Emit Redstone When' to 'Item Inserted but Idle' without putting any items in it.
3. Put some redstone dust adjacent to it.
Expected result: redstone signal 0. Actual result: redstone signal 15.

### Any other comments?
If I place some chargeable item inside, it outputs 0 when successfully (dis)charging. But it would be much more convenient for automation purposes if it output 0 when no item/drone charging as well. I also had Security, Dispenser and 8xSpeed Upgrades installed. But taking them out changed nothing.

**Comment by desht** [comment]
I'm not seeing this behaviour:
![2021-09-29_09 32 39](https://user-images.githubusercontent.com/736831/135232893-60488620-a3c0-41be-a44a-94057e6212ca.png)
No item is inserted there, and there's no redstone signal.

**Comment by desht** [comment]
Update: I can reproduce the problem if I put an item in and then remove it.  Looking for a solution now.

**Comment by desht** [comment]
Fixed in 2.14.5 release
