### ISSUE TITLE
Aerial Interface not charging pneumatic armour

### ISSUE THREAD

**Issue by quasarea** [TeamPneumatic/pnc-repressurized#903]
### Minecraft Version
1.16.5

### Forge Version
36.2.4

### Mod Version
2.14.4-258

### Describe your problem, including steps to reproduce it
Pneumatic armour is no longer charged by aerial interface.

**Comment by desht** [comment]
Works just fine for me.  Screenshot of your setup?

**Comment by quasarea** [comment]
![image](https://user-images.githubusercontent.com/10334982/137130303-c56f9033-0168-40f0-978d-2022f4e8e78c.png)
![image](https://user-images.githubusercontent.com/10334982/137130370-0c7c8f34-8caa-4746-97d7-5fe17ecd85da.png)
![image](https://user-images.githubusercontent.com/10334982/137130410-40a27379-9cf1-4a1c-84fa-7d00baefe53e.png)
![image](https://user-images.githubusercontent.com/10334982/137130435-4c39aafc-d147-4ca1-ba3c-2238e8712d8d.png)

I disconnected rf as I'm using flux network, I reconnected it but it did not solve the issue so I don't think its required

**Comment by desht** [comment]
I can see from that you're using the bottom face of the block for armor charging, but you just have a pressure tube running into that face.  That won't work; you need to have a charging module pointing at the face you've configured for armor charging, and run your pressure in through another face.  This behaviour isn't new (been like this since partway through 1.12.2).

**Comment by quasarea** [comment]
wait, this is for charging? I thought the hopper tab is only to configure items in/out behaviour and set it to `armour slot` just to be safe, now I disabled it, there is no separate option to set it to charge armour as far as I see

![image](https://user-images.githubusercontent.com/10334982/137133730-a469bbeb-cdb5-45c8-8d0e-f202e8bcbe1e.png)
doesnt work too

**Comment by quasarea** [comment]
got you!, I'm stupid, took me few reads to understand that charging is done only by using charging module pointing into aerial interface... checking it now

**Comment by quasarea** [comment]
No, I still cant make it work
![image](https://user-images.githubusercontent.com/10334982/137138088-557bbfa6-b06b-4d5b-ac03-a777d9d8ffad.png)

**Comment by quasarea** [comment]
OK, now it works, needs hopper to be set as well
![image](https://user-images.githubusercontent.com/10334982/137138396-629fe086-82ac-4c0a-8443-84f20835b1ab.png)
