### ISSUE TITLE
Request: Allow blacklisting oil generation by dimension and/or dimension type

### ISSUE THREAD

**Issue by dashkal16** [TeamPneumatic/pnc-repressurized#904]
In 1.16.5, PneumaticCraft no longer allows blacklisting by dimension.  The related configuration is now used for biome blacklisting, which is also useful.

It'd be nice to have dimension level blacklisting as well, and also dimension type (so as to grab classes of dynamically generated dimensions like private TARDIS interiors or MystCraft ages).

**Comment by desht** [comment]
By "dimension type", you mean the dimension ID namespace (which is generally the mod ID) ?

That would be doable, probably best via some kind of wildcard system (e.g. `mystcraft:*` or similar)

**Comment by dashkal16** [comment]
When creating a dimension, there are two components.  A dimension and a dimension type.
https://minecraft.fandom.com/wiki/Custom_dimension

The dimension itself controls the seed and world generation parameters, and selects a type.
The dimension type controls the skybox, time, and Y size of the dimensions that use that type.

That said, wildcards would be useful as well to hit the use case of "Just don't generate in that mod's dimensions".

**Comment by desht** [comment]
Ah yeah, the dimension type.  I'll see if that can be worked in.

**Comment by dashkal16** [comment]
Much appreciated.
Of the two, it's certainly the less important part, but it does serve some use cases.
Probably the same ones as controlling by mod.
Assertions like "Stay out of RFTools dimensions" or the like.

**Comment by desht** [comment]
Unfortunately, `DimensionType` objects don't have any kind of name field that could be matched against, so I don't think this idea is viable - sorry!  But matching against dimension id's along with a wildcard feature should hopefully be sufficient.

**Comment by dashkal16** [comment]
Ahh, I follow.  If the id isn't exposed then this cannot work.
In that case yes, wildcards like `minecraft:*` would serve pretty closely anyway.

I don't actually have a case where I want to blacklist a dynamically generated dimension of a mod, but not all dims from that mod.

New TARDIS Mod comes closest (The TARDIS dimensions are dynamic, but space and the moon are singular.  I don't want oil pools on the moon anyway).

**Comment by desht** [comment]
This is available in build 264 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/, if you'd like to test.

**Comment by desht** [comment]
Fixed in 2.14.5 release
