### ISSUE TITLE
Crash when loading village

### ISSUE THREAD

**Issue by Altnoir** [TeamPneumatic/pnc-repressurized#905]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2855
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.11.15-398
### Describe your problem, including steps to reproduce it
Crash when loading village.
My guess is that the villager IDs are conflicting.
the crash report looks like this:
https://paste.ubuntu.com/p/2XcjVmGgkw/
### Any other comments?
I hope to add the option to disable villagers in the config file.

**Comment by desht** [comment]
Sorry, 1.12.2 is no longer supported.

**Comment by Altnoir** [comment]
I really like this mod, please!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TeamPneumatic/pnc-repressurized"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月21日(星期四) 下午5:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TeamPneumatic/pnc-repressurized] Crash when loading village (Issue #905)





 
Sorry, 1.12.2 is no longer supported.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by desht** [comment]
Sorry but unsupported means unsupported.  And I see no evidence at all in your stacktrace that PneumaticCraft is even involved in this.
