### ISSUE TITLE
[Feature Request] Amadron Tablet "Fuel" capacity

### ISSUE THREAD

**Issue by Freebi85** [TeamPneumatic/pnc-repressurized#907]
Hey there 😃 

I am planning to use the amadron tablet for a custom store with many items. However, the standard amount of air the amadron can hold is a bit low in case someone wants to browse the store a bit longer. This requires constant recharging.
Would it be possible to have a config that increases this? I apologize if this already exists and I have overlooked. But could not find anything in the regard.

**Comment by desht** [comment]
A couple of solutions already exist: 
* Stand on a charging station with dispenser upgrade while using it (available very early on)
* Use an aerial interface to keep your inventory charged (late game but works anywhere)

I might consider allowing the tablet to take volume upgrades at some point in the future...

**Comment by Freebi85** [comment]
Ah nice didn’t know that. Thank you for the fast answer. Cheers

**Comment by desht** [comment]
Fixed in 2.14.5 release
