### ISSUE TITLE
[Feature Request] Spawner Core conversions

### ISSUE THREAD

**Issue by nirakoji** [TeamPneumatic/pnc-repressurized#908]
In discussion on the #development channel on Discord, Motoko, K4Unl, and myself pondered about a new mechanic for PNCR. (conversation link: https://discordapp.com/channels/380076480241336323/807230294636757022/904732094872305704)

In short, the ability to transmute Spawner Cores that are 100% filled with one type of mob. The use-case in mind was Thermal Series' elementals: the Blizz (ice), Blitz (wind), and Basalz (earth) alongside Vanilla's Blaze (fire).

One potential way this could look:
```
Blaze Core --(chilled)--> Blizz Core
Blizz Core --(vacuum chambered)--> Blitz Core
Blitz Core --(pressure chambered)--> Basalz Core
Basalz Core --(heated)--> Blaze Core
```

A full cycle would nudge people into using a range of PNC machines. It was also mentioned that this kind of a mechanic could open up options for other types of core conversions, like Squid Cores being vacuumed into Ghast Cores, or Pig Cores being compressed by pressure into Creeper Cores. Perhaps even a Sheep Core in the TPP with water and pressure turned into a Turtle Core. A lot of potential options!

**Comment by desht** [comment]
This is in fact already possible with the existing recipe system.  You just need to be aware of how the spawner core uses NBT, and the `/dumpNBT` command (added by PNC) helps here:

```
# while holding a spawner core
/dumpNBT
{"pneumaticcraft:SpawnerCoreStats":{"minecraft:skeleton":100}}
```

This means you can add e.g. a TPP recipe that looks like this:

```json
{
  "type": "pneumaticcraft:thermo_plant",
  "item_input": {
    "type": "forge:nbt",
    "item": "pneumaticcraft:spawner_core",
    "nbt": "{\"pneumaticcraft:SpawnerCoreStats\":{\"minecraft:zombie\":100}}"
  },
  "item_output": {
    "item": "pneumaticcraft:spawner_core",
    "nbt": "{\"pneumaticcraft:SpawnerCoreStats\":{\"minecraft:skeleton\":100}}"
  },
  "temperature": {
    "min_temp": 423
  }
}
```

which will convert a 100% zombie core to a 100% skeleton core in the TPP given a temperature of >=150C.  Note the `"type": "forge:nbt"` line in the input item, which is vital for the item's NBT to be considered in the recipe.

**Comment by desht** [comment]
As discussed on discord, this all seems to work just fine, so going to close this issue.  Feel free to update & reopen if you find any issues with recipes like the above.
