### ISSUE TITLE
Refinery refuses to start after receiving enough fluid if it initially received a smaller amount.

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#910]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5
### Forge Version
36.2.4
### Mod Version
pneumaticcraft-repressurized-1.16.5-2.14.4-258
### Describe your problem, including steps to reproduce it
The refinery refuses to start after receiving enough fluid if it initially received a smaller amount.

For example, the recipe for processing oil requires 10mb. If you somehow give the refinery 1mb of oil and then add the rest, it will refuse to start. This can be replicated with something like Logistics Frames or xNet to insert at a very low rate, like 1mb per second.

This came about as a result of a recipe I added that produces 10mb of brine from 100mb of water, and 10 mb of lithium from 100 mb of brine. The first refinery would output 10mb of brine, the second would receive it, nope out, and sit there doing nothing even after receiving the other 90mb. 

### Any other comments?
I've tweaked the recipes to avoid this so no worries on a quick fix. Seems like a bit of an odd edge case, but might be worth investigation anyway. I could conceive of a situation where someone is producing less than 10mb per operation from some other machine and that results in their refinery hanging up when it runs out and then receives a little dribble.

**Comment by desht** [comment]
I think I can see the problem.  The recipe rescanning is only triggered when the fluid type changes, not simply an increase in the existing fluid amount.  I think the TPP has the same issue.

Build 270 should hopefully fix this problem, for the Refinery at least.  If it looks good, I'll do the same for the TPP.

**Comment by MuteTiefling** [comment]
Seems to be working! Thanks!

**Comment by desht** [comment]
Fixed in 2.14.5 release
