### ISSUE TITLE
Create public default constructor for SmartChestItemHandler

### ISSUE THREAD

**Issue by juh9870** [TeamPneumatic/pnc-repressurized#911]
Please create public constructor for SmartChestItemHandler, so it can be serialized/deserialized by other mods without usage of mixins/reflection. Specifically, I'm working on Create addon that adds support for modded storage, and I can't add SmartChestItemHandler deserialization without extensive usage of reflections

**Comment by desht** [comment]
What specifically do you need from `SmartChestItemHandler` that isn't available through normal capability querying?

**Comment by juh9870** [comment]
Create moving contraption can pull SmartChestItemHandler from chest normally and it will work untill you serialize and deserialize contraption, at which point SmartChestItemHandler is deserialized as default ItemStackHandler, breaking all custom logic, and since tile entity does not exist at that point we can't just pull another handler, the only option is to create new SmartChestItemHandler and deserialize it from previos SmartChestItemHandler NBT, which is my addon does with custom handlers from other mods, but I can't do that here because I can't instantiate SmartChestItemHandler outside of tile entity

**Comment by desht** [comment]
Added in 2.14.6 release
