### ISSUE TITLE
Inaccurate guide book entry 

### ISSUE THREAD

**Issue by NielsPilgaard** [TeamPneumatic/pnc-repressurized#913]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5

### Forge Version
1.16.5-36.2.4

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.14.4-258

### Describe your problem, including steps to reproduce it
> pnc book says you can put 6 item life upgrades in each piece of armor but the upgrades only stack to 5 when they are put in.

### Any other comments?
Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/3700

**Comment by desht** [comment]
Fixed in 2.14.6 release
