### ISSUE TITLE
Pressure chamber with volume upgrade explode on block replace

### ISSUE THREAD

**Issue by Naheulf** [TeamPneumatic/pnc-repressurized#914]
### Minecraft Version
MC 1.16.5
### Forge Version
Forge 36.2.4 (MCP 20210115.111550)
### Mod Version
1.16.5-2.14.4-258

### Description of the Issue

Transient (lower) volume in enlarger pressure chamber on rebuild may cause explosion.

### Steps to Reproduce the Issue

1. Build a pressure chamber
2. Add some volume upgrade (i used the max amount for my tests)
3. Fill the pressure chamber with air (at almost 5 bar)
4. Brake one pressure chamber bloc and replace it

### Expected Behavior

The pressure chamber should not explode
### Actual Behavior

The pressure chamber explode

### Any other comments?
First seen on a dedicated server with a large modpack. But able to reproduce in single player with only pneumaticraft.
This is NOT #874.

**Comment by desht** [comment]
Yep, there is a problem here.  The multiblock break/reform logic gets really messy once both volume upgrades and base volume calculations due to multiblock size come into play.  I'll take another look at this and see if there's a cleaner way to handle it.

**Comment by Naheulf** [comment]
In the video for #915 I also make a demo for this bug https://www.youtube.com/watch?v=_QjUQIeenKs&t=0s

**Comment by desht** [comment]
Can you try build 275 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ ?  Hopefully it fixes the problem you're seeing.

**Comment by Naheulf** [comment]
It works in singleplayer with the full modpack. For multiplayer test I need to wait the next server update.

So I think we can close this issue. (I'll re-open if the issue still happen on the server)
