### ISSUE TITLE
Visual glitchs in Pneumatic Armor upgrade gui

### ISSUE THREAD

**Issue by Naheulf** [TeamPneumatic/pnc-repressurized#915]
### Minecraft Version
MC 1.16.5
### Forge Version
Forge 36.2.4 (MCP 20210115.111550)
### Mod Version
1.16.5-2.14.4-258

### Description of the Issue

There some visual glitches in Pneumatic Armour upgrade GUI (in the charging station)

### Steps to Reproduce the Issue (Case 1)

1. Take a stack of volume upgrade with 26 to 50 items
2. Shift + Click to send it on the armour upgrade slots

### Expected Behaviour (Case 1)

Only one stack with 25 Volume upgrade should go in the upgrade gui.

### Actual Behaviour (Case 1)

An additional stack of Volume upgrade is showed near the good one.
~~Note : seem to only occur with fresh armour part (newly crafted or gived)~~

### Steps to Reproduce the Issue (Case 2)
1. Place at least two upgrade types in an pressurized armour (for example in slots 1 and 2)
2. close the the gui and open it again
3. try to swap two upgrades **without exit the GUI** (ie : take the one from slot 1 and place it in slot 2, and the one from slot 2 and place it on slot 1)

### Expected Behaviour (Case 2)
Should works like swapping two stacks in a dropper/dispenser

### Actual Behaviour (Case 2)
The some "gost" invisible itemstack in the slots and shift click transfers act strange.

### Any other comments?
First seen on a dedicated server with a large modpack. But able to reproduce in single player with only pneumaticraft.
Theses seem to be only visuals glitches.

Edit 18 November 2021:
- Fix Step to reproduce (Case 1)
- Add more details To Step to reproduce (Case 2) (for the swap part)

Edit 21 November 2021:
- Fix required conditions for case 1

**Comment by desht** [comment]
I can't reproduce either of these problems and I think you've mixed up some of the steps with the other issue you raised (this has nothing to do with pressure chambers)

What do you mean by "swap upgrades" ?  Screenshots or a video of you trying this might be helpful.

**Comment by Naheulf** [comment]
I fix the steps to reproduce. I also made a video as requested https://www.youtube.com/watch?v=_QjUQIeenKs&t=65s

**Comment by desht** [comment]
Ok, yeah:

1. There is a desync here, and I have seen that before.  Unfortunately, there isn't really a feasible fix without fundamentally altering vanilla container sync'ing mechanics, and I don't want to do that for what is basically just a cosmetic problem.
2. Yes, upgrades can't be swapped, but there's no way around this.  Upgrades can't be in multiple slots, and when you pick an item up in the GUI to move it, the actual slots don't get altered until you try to click the item into another slot.  So the upgrade you're moving is basically still in the original slot, thus you can't put it into a new slot.

I'm aware this a bit glitchy, but I don't plan to fix either issue, sorry.  There are limitations to how the whole Minecraft container system works, and while this isn't ideal, there's nothing game-breaking here either.  Trying to fix these minor problems would be more likely to introduce a serious problem (item loss or duplication). So this just something that needs to be lived with...
