### ISSUE TITLE
Server lag caused by drones

### ISSUE THREAD

**Issue by TheyCallMeAmi** [TeamPneumatic/pnc-repressurized#918]
### Minecraft Version
1.12.2
### Forge Version
14.23.5.2847
### Mod Version
pneumaticcraft-repressurized-1.12.2-0.11.15-398.jar
### Describe your problem, including steps to reproduce it
My drones (regular drones, not harvesting drones) that I use for farming cause massive server lag when I am not in the same dimension (they are chunk loaded), while they are in an AE2 Spatial Drive. When I leave the dimension, the drones cause the dimension to, according to the /forge tps command, use over 150ms, and as soon as I go back the lag stops after 2-3 seconds, which I thought was strange.

---

### Any other comments?
I saw that the 1.12.2 version isn't actively supported anymore, but I thought I'd ask if anyone has a solution anyway as it's difficult to do the farming the same way without using drones.

**Comment by desht** [comment]
1.12.2 is not supported, sorry.  This isn't the place for general questions; you can ask in the mod Discord, although an answer is not guaranteed there.
