### ISSUE TITLE
Rotating kinetic blocks from Create using Pneumatic Wrench leads to unpredictable results

### ISSUE THREAD

**Issue by Lgmrszd** [TeamPneumatic/pnc-repressurized#919]
When using Pneumatic Wrench on kinetic block, said block does not get notified properly, not causing it to update power network.

It appears that all Create blocks that implement `IWrenchable` rely on `onWrenched` call, which only happens when blocks are rotated using Create wrench.

Possible solutions:
- (Simple but not perfect) ignore modded machines, or ignore some mods when using Pneumatic Wrench on them.
- (Better but still not perfect) When Create is installed, check if the block being clicked is instance of `IWrenchable` and call `onWrenched` on it.
- (IMO the best solution) Have some common interface/way of communication between mods and use it to notify blocks on being rotated (if such interface exists in Forge), but this may require changes in both mods.

Issue in Create repo:

https://github.com/Creators-of-Create/Create/issues/2370

Demo:

https://user-images.githubusercontent.com/16291541/143512785-d99e022d-8500-42fa-a9b7-758e6fda8354.mp4

Mods versions:
Forge: 36.2.8
PNC:R: 1.16.5-2.14.6-277
Create: mc1.16.5_v0.3.2g

**Comment by desht** [comment]
Bit of cross-mod compat problem yeah.  Option 2 wouldn't be too hard to do, but it would only solve the problem for wrenching blocks with PNC, so not a general solution.

Option 3 would be ideal but this would really need to be a fully cross-mod solution probably with support within Forge itself.  Which is far from trivial...

**Comment by desht** [comment]
Compat added in 2.14.7 release
