### ISSUE TITLE
Add a 'full grown plants' option in the Dig/Item Filter puzzle piece in the Programmer

### ISSUE THREAD

**Issue by MineMaarten** [TeamPneumatic/pnc-repressurized#92]
Meta values are disappearing, so this needs a replacement soon.

Also, this allows to simplify creating farming programs for users, because they don't need to look up for different crops how they behave.

This would be exposed via an API to other modders who would wish to add their own plant behaviour.

**Comment by desht** [comment]
Closed by https://github.com/TeamPneumatic/pnc-repressurized/commit/a87d0aa52fe5baf8c8ce52ce4903980adece19b3

**Comment by MineMaarten** [comment]
Not released/finished though
