### ISSUE TITLE
[Discussion] How to force drones to repressurize themselves.

### ISSUE THREAD

**Issue by Koulis2000** [TeamPneumatic/pnc-repressurized#920]
### Mod Version: FTB Endeavour 1.5.0

Hi there, hello. I have a small base and have assigned drones to attack "@mobs" around it. Problem is that the drones attack until they run out of pressure and drop on the ground. Is there a way to force drones to break out of their current order and go to a charging station? Maybe a "while over 2 pressure do attack" which would cause them to immediately stop attacking when they drop under 2 bar for a charging break? I see no issues reported on the matter but I think it's a major thing that people would use drones so it probably is that I'm doing something wrong.

All drones have these upgrades: 5 Speed, 1 Minigun, 16 Range.

**Comment by desht** [comment]
Drones automatically go to any Charging Station (within 80 blocks) with a Dispenser Upgrade when their pressure drops below 1 bar.  No extra programming is needed - this is built-in functionality.
