### ISSUE TITLE
[Bug]: Pressure chamber glass not connecting properly on the 5x5x5.

### ISSUE THREAD

**Issue by NightOps007** [TeamPneumatic/pnc-repressurized#923]
A picture is worth a thousand words...
![2021-12-16_00 09 27](https://user-images.githubusercontent.com/5381709/146335129-4945aa6e-b4b0-42ae-aed8-e6dbc2a670e5.png)

### Minecraft Version
1.16.5
### Forge Version
36.2.0
### Mod Version
2.14.6-277
### Describe your problem, including steps to reproduce it
Build the largest pressure chamber to observe the not so connected textures for the glass.
### Any other comments?
optifine installed as well, but connected textures from it disabled. Would the Connected textures mod cause problems or is that a required dependency for this one?

**Comment by desht** [comment]
Try without optifine installed at all, please...

As far as Connected textures mod goes, it shouldn't have any effect - PNC handles connected textures for glass entirely itself.

**Comment by desht** [comment]
Closed due to lack of response

**Comment by changhe3** [comment]
This happened to me when I don't shift click onto other glass blocks. It's a non-issue as long as I shift click onto other glass blocks.

**Comment by desht** [comment]
No longer relevant, since latest version of the mod has completely redone texturing, including the pressure chamber glass.  The CTM mod is now a requirement for connected pressure glass textures.
