### ISSUE TITLE
Crash when clear the hotkey

### ISSUE THREAD

**Issue by DrSigma4164** [TeamPneumatic/pnc-repressurized#924]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
Hi! I wanted to clear the hotkey that was assigned to the block tracker. When I pressed Shift + RMB I crashed minecraft ...

[crash-2021-12-17_12.18.05-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/7734321/crash-2021-12-17_12.18.05-client.txt)

**Comment by desht** [comment]
Fixed in 2.14.7 release
