### ISSUE TITLE
crash while trying to create world

### ISSUE THREAD

**Issue by Blake0wl** [TeamPneumatic/pnc-repressurized#926]
minecraft 1.16.5

forge version 36.2.22

mod version 2.14.6.277

Hi here is the crash report, I tried different build for the same result 

[crash-2021-12-29_09.46.18-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/7788097/crash-2021-12-29_09.46.18-server.txt)

**Comment by desht** [comment]
Probably a mod-compat issue - looks like something is creating villager trades with either an empty cost or empty result.  Which is invalid behaviour, but I'll update PNC to ignore such invalid trades rather than crashing on them.

**Comment by Blake0wl** [comment]
ok, can I change a value in the config file to prevent such crash ?

**Comment by desht** [comment]
Sorry, without knowing which mod's doing it, no.

You can however try out build 282 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/changes, which should fix the problem. This will also be in the next release (2.14.7), which I hope to get out in the next few days.

**Comment by Blake0wl** [comment]
ok i will try the 282 build or wait the next release

**Comment by Blake0wl** [comment]
the 282 buil fixed my issue

**Comment by desht** [comment]
Fixed in 2.14.7 release
