### ISSUE TITLE
Game crashes when loading up, Logs seem to indicate heat sinks are the cause

### ISSUE THREAD

**Issue by internetyh** [TeamPneumatic/pnc-repressurized#927]
Minecraft Version:
1.12.2

Forge Version:
14.23.5.2860

Mod Version:
0.11.15-398

When loading up the world I get an immediate crash, started happening recently, ive seemingly traced it to heat sinks from pneumatic craft

Misc Comments:
Project Ozone 3 Modpack
Started happening very recently, no changes to my pneumatic craft setup
Removed an assembly controller which I thought was causing the crashes earlier, however they just started happening again

Crash Report related to the current crashes:
[crash-2022-01-02_20.37.24-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/7798784/crash-2022-01-02_20.37.24-server.txt)

Crash report related to assembly controller crashes:
[crash-2022-01-02_15.42.17-server.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/7798785/crash-2022-01-02_15.42.17-server.txt)

**Comment by desht** [comment]
Sorry, 1.12.2 is not supported anymore.
