### ISSUE TITLE
Add a 'Harvesting Drone' and 'Planting Drone'

### ISSUE THREAD

**Issue by MineMaarten** [TeamPneumatic/pnc-repressurized#93]
These would be Drones that are low level non-programmable drones (just like the Logistic Drone). These are lower level drones that perform harvesting and planting tasks only, in a certain range from their initial placement position (like Logistic Drones), and they would use the chest they get placed on as the chest to pull item from / put items in. This would be using #92

More low level pre-programmed drone types could be added, feel free to suggest some other options :).

**Comment by Darkosto** [comment]
I would use this! I'm actually setting up drones to farm for me right now and would love a bit more simplicity in the process :D

**Comment by desht** [comment]
Closed by https://github.com/TeamPneumatic/pnc-repressurized/commit/a87d0aa52fe5baf8c8ce52ce4903980adece19b3

**Comment by MineMaarten** [comment]
Not released/finished though
