### ISSUE TITLE
Radiation Shielding Unit not working

### ISSUE THREAD

**Issue by IEqualMcAwesome** [TeamPneumatic/pnc-repressurized#932]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
I've applied the radiation shielding units to all four pieces of my armor, and have made sure all four pieces are fully pressurized. However, I cannot go near my Mekanism-based fission reactor without dying to radiation damage.

**Comment by desht** [comment]
I presume you didn't already have radiation sickness before putting the armor on?  It won't cure radiation sickness...

**Comment by desht** [comment]
It's working fine here, btw.  Just broke a Pressurized Tube full of Nuclear Waste, which is killing all the local wildlife, but not affecting me at all:
![2022-01-11_09 03 11](https://user-images.githubusercontent.com/736831/148912739-aa4db3f4-ab63-400f-82d0-0ecbd4cff5d6.png)

**Comment by MuteTiefling** [comment]
I'm able to reproduce this, actually. 

Versions:
Mekanism-1.16.5-10.1.1.456
pneumaticcraft-repressurized-1.16.5-2.15.0-289

Will upload a video shortly.

**Comment by MuteTiefling** [comment]
https://streamable.com/zg483x

**Comment by MuteTiefling** [comment]
~~I notice in your screenshot, you don't have the new blue overlay showing the area is irradiated. Possibly have an oldver version of Mek in your testing instance?~~ nvm, that's only there when you get iradiated.

**Comment by desht** [comment]
Yeah I haven't updated Mekanism in dev workspace for a while.  Will test with the latest when I get a chance...

**Comment by desht** [comment]
Yep, that was it, I think.  I was still testing against Mekanism 10.0.x in my dev world, and the radiation API has moved in Mek 10.1. Rebuilt against that now (and the next PNC release will require Mek 10.1.x - it will crash if run with Mek 10.0.x)

Anyway, if you could test out build ~~298+~~ 299+ for radiation protection, that would be great.

**Comment by IEqualMcAwesome** [comment]
As soon as I have a chance to log on I'll try it out! Thank you so much!

**Comment by desht** [comment]
Make that build 299 - build 298 failed.

**Comment by MuteTiefling** [comment]
Working beautifully, thanks!

**Comment by desht** [comment]
Fixed in 2.15.2 release.
