### ISSUE TITLE
PCR Omnidirectional hopper with entity upgrade won't allow for villagers to breed with the food it pipes into them

### ISSUE THREAD

**Issue by Iris-xii** [TeamPneumatic/pnc-repressurized#933]
### Minecraft Version
1.16.5
### Forge Version
36.2.23
### Mod Version
1.16.5-2.14.7-283
### Describe your problem, including steps to reproduce it
Tested on an instance with just PCR, Patchouli and Forge, after encountering this issue on the E6 pack after trying to find a way to breed villagers with mob griefing turned off.
![image](https://user-images.githubusercontent.com/48930896/149214688-a8895e39-9483-499c-a1af-a675861aa8f3.png)

1. Put down an omni-hopper piping carrots (with an entity upgrade) into a villager below.
2. Do this for two villagers and let them roam around around their breeding area (which would work just fine using vanilla mechanics)
3. Notice that they don't breed

However, piping into their armor slot (wtf??) _and_ from above (both) does cause them to breed. Though it looks extremely janky
![image](https://user-images.githubusercontent.com/48930896/149215478-0b5fa955-0876-4477-9c46-f2fd7c821f9a.png)

I am not sure what is going on here.

**Comment by desht** [comment]
I'm not sure either, but I'm going to put it down to vanilla villager weirdness.

The omnihopper just grabs the item handler capability for the entity on whatever side it's pointing at, and lets the entity itself decide what it wants to do with the items that get inserted.  I verified with the debugger that villagers do indeed get food in their held item slot if inserted from above, and in their armor slot if inserted from the side (which is the Forge-defined behaviour for entity item handler capability handling).

What they do with the food at that point is down to vanilla logic, nothing I can do about that...

**Comment by desht** [comment]
Not sure there's anything I can really do here, gonna have to close this one...
