### ISSUE TITLE
Manage Upgrades button in charging station no longer working

### ISSUE THREAD

**Issue by Rodg88** [TeamPneumatic/pnc-repressurized#934]
### Minecraft Version
1.16.5

### Forge Version
36.2.22

### Mod Version
pneumaticcraft-repressurized-1.16.5-2.15.0-289

### Describe your problem, including steps to reproduce it
Pressing the button to Manage Upgrades for an item (eg amadron tablet) in the charging station does nothing, and posts this in the log:
`[12:32:12] [Render thread/WARN] [minecraft/ScreenManager]: Failed to create screen for menu type: pneumaticcraft:charging_amadron`

**Comment by desht** [comment]
It's specific to the Amadron tablet, other items are fine.  A line of code registering the GUI handler got dropped in the big retexture patch, will be fixed in 2.15.1 (coming soon).

**Comment by desht** [comment]
Fixed in 2.15.1
