### ISSUE TITLE
Invisible air grates

### ISSUE THREAD

**Issue by Rodg88** [TeamPneumatic/pnc-repressurized#935]
### Minecraft Version
1.16.5
### Forge Version
36.2.22
### Mod Version
In enigmatica 6 modpack, pneumaticcraft-repressurized-1.16.5-2.15.0-289, though I have had it happen in previous versions, at least 2.14.6-277, I think also 2.14.4-258 

### Describe your problem, including steps to reproduce it
I'm getting invisible air grates on world loading in my main world, in some cases. Them having high pressure seems to affect it. I have had trouble reproducing it in a test world however.

![image](https://user-images.githubusercontent.com/2611674/149296182-f5885ee3-c26e-4d2e-aa8b-4e4dfcf35394.png)
Exited world and re-entered
![image](https://user-images.githubusercontent.com/2611674/149296668-10d869e8-33e0-4b39-8b55-afbeb362e53d.png)

Disconnected air and replaced grates:
![image](https://user-images.githubusercontent.com/2611674/149296792-0efda04b-ab82-4f59-bc46-85d2610c2015.png)
Reloaded world, and it didn't happen this time:
![image](https://user-images.githubusercontent.com/2611674/149297330-ddf7552e-4b1e-4a8c-99a5-067f54f08971.png)

### Any other comments?
latest.log from the above testing https://gist.github.com/Rodg88/c951c078ff2f1fd9dc1bd9db65cd5823

**Comment by desht** [comment]
Confirmed on discord this is due to the Entity Culling mod.  Blacklisting pressure tubes on that mod fixed the problem.
