### ISSUE TITLE
Blocks placed on pressure chamber blocks do not play block place sounds

### ISSUE THREAD

**Issue by ChiefArug** [TeamPneumatic/pnc-repressurized#937]
### Minecraft Version
1.16.5
### Forge Version
36.2.22
### Mod Version
pneumaticcraft-repressurized-1.16.5-2.15.0-289
### Describe your problem, including steps to reproduce it
When placing blocks on any normal pressure chamber block (that doesn't normally have any right click action, like the interface does) no block place sound is made. Holding shift whilst placing it will cause the sound to play.
To reproduce:
 - Place any pressure chamber block down except the interface.
 - Place another block on top of that, there will be no sound.

**Comment by desht** [comment]
Yeah think I noticed this the other day. Probably a very simple fix but I'll take a look into it.

**Comment by desht** [comment]
Fixed in 2.15.1
