### ISSUE TITLE
Make Patchouli a required dependency

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#940]
I personally don't mind that it is an optional dependency. However, I have been keeping track of the number of times I've had a particular interaction online on Reddit and various Discords, and that interaction goes *sort-of* as follows:

SomeUser: Hey HipHopHuman can you help me with PNC?
HipHopHuman: Yeah sure
SomeUser: *proceeds to explain something clearly documented in the PNC:R Manual*
HipHopHuman: This is in the mod's manual
SomeUser: There's a manual?
HipHopHuman: Yes, search JEI for "PNC:R Manual"
SomeUser: I don't see it
HipHopHuman: Do you have Patchouli installed?
SomeUser: No
HipHopHuman: Ok, install Patchouli, then the manual should be available

I've had this interaction (or similar) **8** times now. I think it's time that the manual comes installed with the mod by default.

**Comment by desht** [comment]
Hmm.  I'm in two minds about this.  I get your point, but a hard dependency on *any* mod is something I'm quite uncomfortable with.  IMHO hard dependencies should only be used by mods which are intended as addons to other mods.

**Comment by HipHopHuman** [comment]
I totally get that, though I do think an exception should be made in the case where a mod's only source of concrete documentation requires another mod to be installed. AFAIK, Patchouli is a required dependency in almost all mods that have a Patchouli book - from a cursory glance, Botania, Thermal Foundation, Occultism and Ars Noveu all include Patchouli as a hard dependency so that their respective manuals come included with a single click of "Install".

I think this will benefit PneumaticCraft in the long run, as I've pointed out there are people who want to progress in this mod who not only do not have access to the manual, but aren't even aware that there even is a manual.

Think of it from a newcomer's perspective - they make their own modpack and install PNC, look for documentation,  cannot find it, get frustrated. Perhaps they upload that modpack to CurseForge and then other newcomers download it and share that same negative experience. Some might come over to the Discord to find answers to their questions, but only a handful of those that join the Discord find those answers, and only a handful of those actually ask questions/engage with the Discord community.

I'm not saying that this is staining PNC's reputation in any way, as the mod already has a proven track record. I'm just of the mind that this will positively benefit the mod by giving a small boost to the new player experience.

**Comment by desht** [comment]
Yeah, that's fair.  I'll consider it.

**Comment by MuteTiefling** [comment]
Probably reiterated above, but it makes a lot of sense to me to make it a hard dependency. The mod is very difficult to use without it.

And it's less of an issue now, but back in 1.12 the number of packs that never bothered to add IGW were far too high. Ensuring that the documentation is there goes a long ways towards improving player experience. Especially first time players.

**Comment by desht** [comment]
Given the fairly unanimous support for the idea so far, I'll give in, in this case :)

Patchouli will become a required dependency as of 2.15.1.

**Comment by desht** [comment]
Added in 2.15.1
