### ISSUE TITLE
[Feature Request] Tag Compressed Iron Gear with forge/gears & forge/gears/compressed_iron

### ISSUE THREAD

**Issue by Vapaman** [TeamPneumatic/pnc-repressurized#944]
This would make mod compatibility easier.

I could try to make a PR if everyone is too lazy to do it

**Comment by desht** [comment]
Gears always used to be oredicted back in 1.12, so yeah this is a good idea.  Easy to add in, no need for a PR thanks.

**Comment by desht** [comment]
Added in 2.15.2 release

**Comment by Vapaman** [comment]
This feature is missing in later versions on 1.18.2 and 1.19

Also the recipe for the gear should be changed to use a iron nugget to be more in line with Thermals gear recipes.

**Comment by desht** [comment]
Yep, the tags got overlooked in the port - will be in the next 1.18.2 and 1.19.1 releases.

Not changing the recipe - PNC isn't Thermal.  If you don't like it, feel free to datapack it yourself.
