### ISSUE TITLE
Move away from DieselHandler in IEIntegration

### ISSUE THREAD

**Issue by FrederikRasmussen** [TeamPneumatic/pnc-repressurized#945]
With Immersive Engineering moving over to datapack recipes, the old API integrations like the DieselHandler are deprecated.

Currently, this causes issues in modpacks, where the burntime for Biofuel and Diesel added by PNC:R is not modifiable, as the API integration is always used first.

Essentially, the two recipes in IEIntegration.java just need to be converted to datapack recipes 😃 

https://github.com/TeamPneumatic/pnc-repressurized/blob/872003157d152f48d542d92be0dffd12ddd9b6db/src/main/java/me/desht/pneumaticcraft/common/thirdparty/immersiveengineering/IEIntegration.java

**Comment by MuteTiefling** [comment]
Bit of history here: https://github.com/BluSunrize/ImmersiveEngineering/issues/5062

Long story short, I was looking to add some custom fuels to the IE Diesel Gen and Malte was kind enough to oblige. If PNC were to simply drop the API integration and instead let IE pick up biodiesel via the `forge:biodiesel` tag already used in there recipe, it will fix an issue we're having with overriding the default biodiesel values in the diesel gen.

**Comment by desht** [comment]
Yeah, I'd noticed datapack is now the only way to do it in 1.18.  Hadn't realised it was also a thing in the 1.16 version.  Dropping the explicit API registration is probably a smart idea at this point, will be gone in the 2.15.2 release.

**Comment by desht** [comment]
FIxed in 2.15.2 release
