### ISSUE TITLE
[Feature Suggestion] Three New Pneumatic Armor Upgrades

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#947]
- **Gilded** (any armor piece, only needed on one). Makes Pneumatic Armor behave like Gold Armor. (Piglins are no longer hostile)
- **Stomp** (boots upgrade). Makes landing from a sufficient height do a small amount of impact damage at the landing site. (for Iron Man landings).
- **Shock Absorption** (helmet upgrade). Makes crashing head-first into cliffs during pneumatic flight do less damage. Stackable up to 4, which protects from damage entirely.

EDIT: Just to add some context on where I got these ideas from:
 - Botania's Terrasteel Armor acts like Gold armor does in the Nether, so Piglins would not be hostile to players wearing it. There's a couple of niche lesser-known mods that let you add gold trim to regular armor for the same benefit. It makes sense to me for this to be an expensive-ish upgrade for Pneumatic Armor, because it kind of sucks having to trade a whole bunch of modules for less Piglin hostility. Trade your helmet, you lose the ability to track things. Trade your boots, you no longer have flight. Trade your chestplate, you no longer have remote charging. Trade your legs, you no longer have speed. 
 - The "Stomp" and "Shock" absorption ideas I stole from Mr Crayfish' Enchantable mod, which adds two enchants that do the same thing. It didn't quite occur to me until writing this issue that these seem more like they belong in PNC because of how well they synergize with the Pneumatic Jet Boots mechanics - almost like it just makes sense to have them available in the mod out of the box.

**Comment by desht** [comment]
Gilded would be nice, yeah. Possibly related would be "Pumpkin" to prevent enderman aggro.

Stomp: I presume this is some AoE damage to nearby entities?  Could be an option, I guess.

Shock: Not so convinced about this one. PNC Armor flight has so many pluses, it feels like it needs a tiny bit of balance... Armor upgrades could be used to mitigate this damage, I suppose, but I'm not keen on removing it entirely.

**Comment by TeamSpen210** [comment]
For endermen, perhaps something like a "tinted visor" would make sense.

**Comment by HipHopHuman** [comment]
> Gilded would be nice, yeah. Possibly related would be "Pumpkin" to prevent enderman aggro.

Ooh, that's a good one I hadn't thought of. 

> Stomp: I presume this is some AoE damage to nearby entities? Could be an option, I guess.

Pretty much exactly that, in Enchantable, it's only a 5 block radius and it's not enough to actually kill the mobs. It doesn't really add anything to combat, it just feels very thematic and it meshes *very* well with the Iron Man theme. Perhaps it could also have a very small knockback effect.

> Shock: Not so convinced about this one. PNC Armor flight has so many pluses, it feels like it needs a tiny bit of balance... Armor upgrades could be used to mitigate this damage, I suppose, but I'm not keen on removing it entirely.

That's fair, but I urge you to at least try it and see how it works by installing Enchantable ([here's the link](https://www.curseforge.com/minecraft/mc-mods/enchantable)) into your dev world and giving it a little spin. It works *really* well, and balance can be added in other ways (expensive recipes, mutual exclusiveness to modules due to limited upgrade slots, etc etc).

**Comment by desht** [comment]
Yeah I guess the helmet already has a ton of upgrades, so choices would need to be made here...

**Comment by desht** [comment]
Gilded upgrade should require Gilded Blackstone (that way the player needs to find a bastion first)

Pumpkin upgrade (Tinted Visor?) should require something from the End, chorus fruit perhaps.

**Comment by HipHopHuman** [comment]
Makes sense to me, though perhaps Chorus Flower would be better, because it's a block (like pumpkin is a block)

**Comment by desht** [comment]
Ender Visor and Stomp are now in the 1.18 dev builds.

I've decided against adding a Shock upgrade, since Armor Upgrades + Protection enchant pretty much protect against all collision damage anyway.  I might make it so max armor upgrades and Protection IV fully protect against *all* damage, but I don't see the need for a separate upgrade here.
