### ISSUE TITLE
Items in horizontal Pressure Chamber Interface render outside it

### ISSUE THREAD

**Issue by baysupercool** [TeamPneumatic/pnc-repressurized#948]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Minecraft Version
1.16.5

### Forge Version
36.2.23

### Mod Version
2.15.2-303

### Describe your problem, including steps to reproduce it
1. Build a Pressure Chamber with a Pressure Chamber Interface put at top or bottom (not at the walls)
2. Insert an item through the interface
![bug1](https://user-images.githubusercontent.com/46246461/152691801-481fa263-f842-4bda-a6d3-ba2fb4fd0ae0.png)
![bug2](https://user-images.githubusercontent.com/46246461/152692235-2e34de87-3c34-4cda-9a7e-ae19873356a6.png)

### Any other comments?
*it took 15 minutes for uploading 2 images*
*why is my internet so bad*

**Comment by desht** [comment]
Fixed in 2.15.3 release
