### ISSUE TITLE
[Feature Enhancement] Config option for modifying bandage cooldown time

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#950]
In my pack I want to reduce the cooldown timer of the bandage just ever so slightly (just by like half a second), had a look in the config options and noticed it wasn't there (unless I'm missing something). The cooldown for micromissiles is configurable, so it makes sense that this should be configurable too.

**Comment by desht** [comment]
Added in 1.18.1, will include this for the next 1.16.5 release though.

**Comment by desht** [comment]
Added in 2.15.3 release
