### ISSUE TITLE
Pneumaticcraft Drones not going back to charging station

### ISSUE THREAD

**Issue by JaKinen44** [TeamPneumatic/pnc-repressurized#952]
Minecraft Version: 1.12.2

 Forge Version: 14.23.5.2860

 Mod Version: Pneumaticcraft Represurized 1.12.2-0.11.15-398
 
Hello, Im playing Pneumaticcraft Represurized 1.12.2-0.11.15-398. Drones dont go to charging station when low pressure, i even tried to use a Go to piece to send them to the top of a charging station and it doesnt charge. Any help?

**Comment by desht** [comment]
1.12.2 is long out of support, sorry.
