### ISSUE TITLE
Investigate possible bug with Crafting Widget's "Use Count" option

### ISSUE THREAD

**Issue by HipHopHuman** [TeamPneumatic/pnc-repressurized#955]
This affects 1.16.5 but might affect 1.18 as well. I don't think Forge version matters, but I've seen talk on the Discord that the "Use Count" option on the crafting widget doesn't quite work as it should.

The "Use Count" option is *supposed* to limit the amount of crafting operations - that is, Use Count=2 will make the drone perform the same crafting recipe no more than *twice* (if it has sufficient ingredients).

However, if the drone doing the crafting has a surplus of ingredients in it's inventory, it will continue to craft. This can be replicated with a simple program telling it to craft crafting tables:
- by telling it to "Import All" from an input chest with multiple logs
- then craft 1 log into 4 planks with Use Count=1
- then craft the 4 planks into 1 crafting table with Use Count=1
- then export to an output inventory
- then suicide

I personally haven't run into this issue because I severely limit what is in my crafting drone's inventory when it does crafting, but I can definitely see the case for having a mobile drone craft a certain amount of things while on the move, and in that use case limiting items in the inventory doesn't make sense.

This is just what I've surmised from this issue being brought up twice on Discord. You can find the related correspondence [here](https://discord.com/channels/380076480241336323/380100722420613121/943630058180997150)  and [here](https://discord.com/channels/380076480241336323/380100722420613121/913658056364146738)

**Comment by Iris-xii** [comment]
Thank you for relaying the issue over here for me. For the record I'm running PCR 1.16.5-2.15.0-289 and Forge 36.2.28

**Comment by desht** [comment]
It looks like the crafting widget has never actually honoured the "use count" setting at all.  Easy enough to fix, fortunately, so that will be in the next release (2.15.3).

This is still the max number to craft before moving to the next widget in the program, of course - so a looping program which just crafts will still craft as much as it can. But with this change, you get some control via conditions etc.

**Comment by desht** [comment]
Fixed in 2.15.3 release
