### ISSUE TITLE
Pressure gauge module render issue with any shaderpack.

### ISSUE THREAD

**Issue by doomguy81** [TeamPneumatic/pnc-repressurized#956]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2860
Mod version: 0.11.15-398

Hi, I'm currently making a small custom modpack to play with my friends. As the title says my problem is when I use shaders (Like Sildur's Vibrant Shader or SEUS Renewed) the pressure gauge module doesn't render correctly and appears completely black.
- I've used two different versions of Optifine (HD_U_G6 & HD_U_G5) nothing has changed.
- When I use lower quality versions of Sildur's Vibrant Shaders like the lite version it begins to be barely visible.
![2022-02-18_00 50 25](https://user-images.githubusercontent.com/53040865/154572769-384ce555-5077-4d1a-a5f4-8db8d4feecbf.png)
![2022-02-18_00 50 04](https://user-images.githubusercontent.com/53040865/154572786-4ea5b5df-4bb5-49a3-a1e7-b0d48d806b9a.png)

**Comment by desht** [comment]
1.12.2 is long out of support, and any issues with shaders or Optifine weren't even supported back then.

**Comment by doomguy81** [comment]
@desht Completely understandable. But I believe 1.12.2 is one of the most used game versions for modding, if not the most used. Because the majority of the mods we like are not available in higher versions.

**Comment by desht** [comment]
Unsupported is unsupported...
