### ISSUE TITLE
[1.18.1] Crash when viewing Compressed Iron Block tooltip and holding shift

### ISSUE THREAD

**Issue by ChiefArug** [TeamPneumatic/pnc-repressurized#959]
### Minecraft Version
1.18
### Forge Version
39.0.79
### Mod Version
pneumaticcraft-repressurized-1.18.1-3.0.0-42 
### Describe your problem, including steps to reproduce it
When viewing the tooltip of a compressed iron block while holding shift the game crashes saying it cannot find an Immersive Engineering Heater api class (IE is not installed. It used to be but I removed it before adding PNCR)
### Any other comments?
The crash report:
[crash-2022-02-21_12.47.34-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/8105199/crash-2022-02-21_12.47.34-client.txt)

**Comment by ChiefArug** [comment]
The same problem happens with the refinery pieces, however it doesnt cause a crash, just a `Tooltip error, see logs`. In the logs is the same error: ```
java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/api/tool/ExternalHeaterHandler$IExternalHeatable
	at TRANSFORMER/pneumaticcraft@1.18.1-3.0.0-42/me.desht.pneumaticcraft.common.thirdparty.immersiveengineering.ImmersiveEngineering$ForgeListener.attachExternalHeatHandler(ImmersiveEngineering.java:66)```

**Comment by ChiefArug** [comment]
Nevermind that, it does cause a crash (the same one again). Just not when viewed in JEI it seems, only when in the inventory/crafting output/vanilla recipe book.

**Comment by ChiefArug** [comment]
Ahhh great. Placing the refinery causes a freeze (with a identical error in the log) for exactly the same reason, probably true for all the other heat-based blocks too.

**Comment by desht** [comment]
Yeah, IE external heatable is now capability-based and attached via capability event.  And I used `@EventBusSubscriber` which was a mistake since that always gets called.  Adjusting that to register via code instead so it only gets attached when IE is actually present.  Next build should fix the problem.

**Comment by desht** [comment]
5d682304c80da0a50b11b56e723a0ffffb28b4f2

**Comment by desht** [comment]
Fixed in latest build
