### ISSUE TITLE
Add item to Store Drone Programs

### ISSUE THREAD

**Issue by Tekstack** [TeamPneumatic/pnc-repressurized#96]
Currently, we have two options to store Drone programs. Either via Pastebin, or an actual drone. Sometimes after writing a program, you realize that you don't quite have the resources yet to make all the pieces you need, but you cannot store the program to clear the programmer without using either of the two options above, and without all the pieces, you cannot store the program to a drone.

Suggestion: to incorporate an item that will act like a drone in the programmer, without the check for puzzle pieces in the player's inventory. Basically, the player could name the program and store the program for later use. Also, just as the drone displays how many of each puzzle piece is currently occupying the drone/needed for the program, this item could show the user how many of each piece is needed for the program and make it much easier to retrieve the correct number of each piece.

Thanks

**Comment by desht** [comment]
That's already in game: the Network Data Storage.  You can put it in a Programmer like a drone and write your program to it without using the puzzle pieces.

Adding extra info to the item's tooltip is a good idea though!

**Comment by Tekstack** [comment]
Durp, so sorry I completely overlooked that item.
