### ISSUE TITLE
Block place sound gets played when opening a Pressure Chamber 

### ISSUE THREAD

**Issue by ChiefArug** [TeamPneumatic/pnc-repressurized#963]
### Describe the bug

It gets fake placed, appearing briefly for a moment before disappearing again.

### How to reproduce the bug

Hold any block in hand. Right click a formed pressure chamber. Hear the block place sound and see that the block appears briefly before dissapearing.

### Expected behavior

It just opens the UI and doesnt do anything with the block I am holding.

### Additional details

I beileve this is caused by the fix for  https://github.com/TeamPneumatic/pnc-repressurized/issues/937 (https://github.com/TeamPneumatic/pnc-repressurized/commit/89ca1213ca02e8970c2c6e81eb349101f03fef28)

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
Fixed in latest build
