### ISSUE TITLE
[1.16] Condition: Item Filter Widget is not comparing tags and variable item filters

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#968]
### Describe the bug

I have a for loop with a bunch of items. I want to detect if any of these are part of a tag and treat them separately.

So inside the For loop, I have a Condition: Item Filter comparing a Tag Filter to the variable item from the loop. This always returns false. 

### How to reproduce the bug

Test program: https://gist.github.com/MuteTiefling/16545c896216e03ff06a2996ffda8444

Just put this on a drone and run it. It should tell you that wool is wool and prismarine is not wool. But everything is coming up false. 

### Expected behavior

Expect the condition to return true if the item is in the tag

### Which Minecraft version are you using?

1.16

**Comment by desht** [comment]
The order is actually important here; when using a Tag Filter, it needs to be in the lower of the two filter slots.

Which isn't intuitive or well documented, I appreciate.  Two options:
* Make the code more flexible - if it detected a Tag Filter, always use it as the reference
* Document the behaviour more thoroughly

Downside to approach 1 is the change in behaviour, which has a small chance of breaking existing programs. But the chance is very small, and anyone comparing against a Tag Filter probably wants the new behaviour anyway...

**Comment by desht** [comment]
Fixed in 2.15.4
