### ISSUE TITLE
Server-side crash

### ISSUE THREAD

**Issue by emanuele246gi** [TeamPneumatic/pnc-repressurized#969]
### Describe the bug

I don't really know what caused it because I saw first a mention about Silent's Mechanisms but I found below that it was talking about the TPP too, so I don't know.

### How to reproduce the bug

I don't really know the precise steps because this happened because my friend crafted the thermopneumatic processing plant, at the moment I can't say if the crash happened because he crafted it or placed it down, but anyway after that the server closed.

### Expected behavior

To just not crash, lol

### Additional details

Are the informations above enough? If you need something else I will just wait for you to ask it 

### Which Minecraft version are you using?

1.16

### Crash log

https://pastebin.com/VMBhbwvH

**Comment by desht** [comment]
Not one I can reproduce, and does fall into "shouldn't ever happen" category, but I suspect a cached value isn't getting cleared somewhere.

Will add some extra defensive checks to make sure this definitely can't happen.

**Comment by emanuele246gi** [comment]
I don't know if this can help you, but you could try to create a server using the mods in the crash report, maybe it will be more easy to find a solution

**Comment by desht** [comment]
No, it's OK, next release should be immune to crashes like this.

**Comment by emanuele246gi** [comment]
Ok thank you!

**Comment by desht** [comment]
Fixed in 2.15.4
