### ISSUE TITLE
Crash - Don`t Setup Game =(

### ISSUE THREAD

**Issue by Rumaruka** [TeamPneumatic/pnc-repressurized#97]
*For feature requests, just erase this template and clearly describe the feature you'd like to see*

### Describe your problem, including steps to reproduce it
https://pastebin.com/zAtgjPUw

**Comment by desht** [comment]
Looks like a possible corruption of a JSON file in your config/pneumaticcraft folder. I'd need to see all the files to know which, though. 

I can add some better exception handling and error reporting here, although I don't want to completely mask the problem (it's easy to miss or ignore error messages in the log file).

**Comment by Rumaruka** [comment]
Im try delete config and resetup game

**Comment by Rumaruka** [comment]
Ok, game start, Im retard :D 
Close #97
