### ISSUE TITLE
would it be possible to added a whitelist toggle for biomes / dims?

### ISSUE THREAD

**Issue by zachsai** [TeamPneumatic/pnc-repressurized#971]
### Describe the feature

would it be possible to added a whitelist toggle for biomes / dims?

![image](https://user-images.githubusercontent.com/63996164/158326815-8d2721c1-2f41-446d-a8d2-4412c33d710f.png)

### Reasons why it should be considered

Helps modpack makers

**Comment by desht** [comment]
Added in 3.1.5 release
