### ISSUE TITLE
[1.18.2] Forge 40.0.18 breaks mod

### ISSUE THREAD

**Issue by Baggytrousers27** [TeamPneumatic/pnc-repressurized#972]
### Describe the bug

PneumaticCraft Repressurized (pneumaticcraft) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

### How to reproduce the bug

Install Patchouli-1.18.2-66 and pneumaticcraft-repressurized-1.18.2-3.1.0-57 onto 1.18.2 forge 40.0.18.
Above error shows.

### Expected behavior

Not that ^

### Which Minecraft version are you using?

1.18

### Crash log

https://pastebin.com/AMU5ZWKe

**Comment by ModernGamingWorld** [comment]
Yep can confirm, I had this issue as well

**Comment by desht** [comment]
I'm aware.  Forge 40.0.18 is a very breaking change.  Forge for 1.18.2 in general is still in early alpha and likely to change rapidly so these breaks are very likely.

For now, use 40.0.17.  A new version of PNC will address this eventually, but not until the various mods it depends on also have builds that work on 40.0.18.

**Comment by Baggytrousers27** [comment]
Fair enough.
