### ISSUE TITLE
Redstone tube module crashes game 1.18.x

### ISSUE THREAD

**Issue by bbgott** [TeamPneumatic/pnc-repressurized#973]
### Describe the bug

When attempting to place a redstone tube module on a pipe it causes the game to crash with `java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3`

This crash also happened in 1.18.1

MC: 1.18.2
Forge: 40.0.12
Pneumaticcraft R: 1.18.2-3.1.1-61
Patchouli: 1.18.2-66
theoneprobe: 1.18-5.1.0
jei: 1.18.2-9.5.2.141

### How to reproduce the bug

Create a fresh world, place a pressure tube and then try to place a redstone tube module on the pipe and the game will crash

### Expected behavior

Not to crash

### Which Minecraft version are you using?

1.18

### Crash log

https://gist.github.com/bbgott/c41ad5e6b05217335e6570689ea190b5

**Comment by desht** [comment]
Confirmed.

**Comment by desht** [comment]
Fixed in 3.1.2 release
