### ISSUE TITLE
modules gets copied when replacing item in charging station

### ISSUE THREAD

**Issue by jona23E** [TeamPneumatic/pnc-repressurized#974]
### Describe the bug

i was wondering why dosent my jet boots work, then i realised that theres a charging upgrade on my boots. what happened is i replaced my pneumatic chestplate in the charging station with the boots, just dragged it over it and left clicked. all the modules from my boots vanished and got replaced with the chestplate's modules. now waiting for the server owner to load backup.

### How to reproduce the bug

1. get a pneumatic chestplate
2. get a pneumatic boots
3. install different modules in them
4. put the chestplate in the charging station, then drag the boots over the chestplate thats in the charging station and left click.

### Expected behavior

the modules in the boots vanish and gets replaced with the chestplate's modules

### Additional details

modpack is TNP LIMITLESS 3   PACK VERSION: 1.11.10

mod name: pneumaticcraft-repressurized-1.16.5-2.15.3-308

its on a server.

### Which Minecraft version are you using?

1.16

**Comment by desht** [comment]
Confirmed.  Should be an easy fix, though.

**Comment by desht** [comment]
Fixed in 2.15.5 & 3.1.3
