### ISSUE TITLE
Game crashes when interacting with the thermopneumatic processing plant

### ISSUE THREAD

**Issue by dantistruct** [TeamPneumatic/pnc-repressurized#975]
### Describe the bug

Interacting with the object crashes client (Does not crash server side).
[crash-2022-03-18_23.30.38-client.txt](https://github.com/TeamPneumatic/pnc-repressurized/files/8308528/crash-2022-03-18_23.30.38-client.txt)

### How to reproduce the bug

Place Thermoneumatic block on any surface, right click to interact, crashes client. 

### Expected behavior

Client crashes error - 0

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
I believe this was confirmed resolved in Discord?  Can I close this now?

**Comment by dantistruct** [comment]
Yes it was sorry I forgot to update it on github
