### ISSUE TITLE
Instant Crash on Forge 1.18.2 40.0.18

### ISSUE THREAD

**Issue by zachsai** [TeamPneumatic/pnc-repressurized#976]
### Describe the bug

https://pastebin.com/kNrdiBMg

### How to reproduce the bug

add mod, be on same version, launch

### Expected behavior

not crash

### Which Minecraft version are you using?

1.18

### Crash log

https://pastebin.com/kNrdiBMg

**Comment by desht** [comment]
Duplicate of #972
