### ISSUE TITLE
1.16.5 Patchouli flag warning (fixed in 1.18.2 version) (non-critical)

### ISSUE THREAD

**Issue by Digitoris** [TeamPneumatic/pnc-repressurized#977]
### Describe the bug

I am currently composing a 1.16.5 modpack and was browsing the debug log for potential problems and encoutered one (non-ciritical) issue with the pneumaticcraft book.
Upon starting the instance, patchouli throws the following warning:
`[Render thread/WARN] [patchouli/]: Queried for unknown config flag: pneumaticcraft:plasticinworldsolidification`
A quick peek through the source code of various versions shows that patchouli expects the flag as above
https://github.com/TeamPneumatic/pnc-repressurized/blob/1.16.5/src/main/resources/data/pneumaticcraft/patchouli_books/book/en_us/entries/components/plastic.json
Lines 23, 30 and 36

The flag is provided to patchouli as `pneumaticcraft:inWorldPlasticSolidification`
https://github.com/TeamPneumatic/pnc-repressurized/blob/1.16.5/src/main/java/me/desht/pneumaticcraft/common/thirdparty/patchouli/Patchouli.java
Line 110

Note that this is already fixed in 1.18.2
https://github.com/TeamPneumatic/pnc-repressurized/blob/1.18.2/src/main/resources/assets/pneumaticcraft/patchouli_books/book/en_us/entries/components/plastic.json
https://github.com/TeamPneumatic/pnc-repressurized/blob/1.18.2/src/main/java/me/desht/pneumaticcraft/common/thirdparty/patchouli/Patchouli.java

Therefore this is not necesarily an issue, but more a notice of a small lack of parity between versions.
I tried to see if a similar issue had been raised before, but couldn't find one. I apologize if I missed anything

### How to reproduce the bug

The warning presents itself upon client startup

### Expected behavior

The expected behaviour is apparent: the flag in the datapack matches the flag provided to the api

### Additional details

Launcher: MultiMC 5
Forge 36.2.29
Pneumaticraft 1.16.5-2.15.4-312
Patchouli 1.16.4-53.2

### Which Minecraft version are you using?

1.16

**Comment by desht** [comment]
Thanks for reminding me about that one - I spotted & fixed the mistake when porting and intended to backport to 1.16.5.  It'll be in the next 1.16.5 release.

**Comment by desht** [comment]
Fixed in 2.15.5
