### ISSUE TITLE
Logistics module renderer client crash on 1.18

### ISSUE THREAD

**Issue by bbgott** [TeamPneumatic/pnc-repressurized#978]
### Describe the bug

Same bug as #973 but with the logistics tube module this time

### How to reproduce the bug

Create a new world and attempt to place a logistics module on a tube and the client with crash

### Expected behavior

Not to crash

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
Yep, same problem, sorry.

**Comment by bbgott** [comment]
No worries, thanks for addressing it so quickly. This is definitely one of my favorite mods and I'm glad to see it under active development

**Comment by desht** [comment]
Fix will be in next release, but you can use a dev build from https://github.com/TeamPneumatic/pnc-repressurized/actions if you want to get the fix sooner.

**Comment by bbgott** [comment]
I'm unfortunately stuck on 1.18.1-3.0.0-53 due to other mods in my pack not updated to 1.18.2 yet.

**Comment by desht** [comment]
Yeah unfortunately 1.18 is a fast moving target right now...

**Comment by desht** [comment]
Fixed in 3.1.3
