### ISSUE TITLE
Drop down menus seem to be populated with the first item

### ISSUE THREAD

**Issue by bbgott** [TeamPneumatic/pnc-repressurized#979]
### Describe the bug

When you open a drop down menu, say in the redstone module configuration screen, all of the menu items are overwritten with the first item string.  When you select an item is does change to that new item.

![Redstone_module_bug](https://user-images.githubusercontent.com/314107/159547945-070926ad-e28a-4b8c-b7c0-c0bdafaf68f6.jpg)

MC: 1.18.2
Forge: 40.0.18
PNC:R: 1.18.2-3.1.2-64

### How to reproduce the bug

Open any GUI with a drop down menu, like the redstone tube module configuration screen or the drone place blocks programming piece

### Expected behavior

Menu to be populated with all the values

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
Confirmed

**Comment by desht** [comment]
Fixed in 3.1.3
