### ISSUE TITLE
Omnidirectional Hopper doesn't face right direction

### ISSUE THREAD

**Issue by Kevun1** [TeamPneumatic/pnc-repressurized#98]
Minecraft 1.12.2
Forge 2571
Mod version 0.2.2-102

It's impossible to get the omnidirectional hopper to point in a direction different than where it's opening is facing. 

Example:

1. Face North, and hover over the top side of a block
2. Place omnidirectional hopper

What you would expect is the opening to be facing you (South), and the hopper to point downwards on the part of the block you clicked. Instead, the hopper faces you, but points ahead (North).

It seems to be impossible to get a 90 degree angle on the hopper.

**Comment by desht** [comment]
It's not impossible, although I agree the default rotation when placed should probably behave more as you suggest.

Rotation of the hopper is done via:
* Right-click rotates the input
* Sneak-right-click rotates the output
* With the obvious constraint that the input and output cannot face the same way

As far as default orientation (when placed) goes, it should probably behave like:
* Output should face the block clicked
* Input should face the player

Sound reasonable?

**Comment by MineMaarten** [comment]
I'm sure it used to work like that in the past, but I think it got lost in the port

**Comment by desht** [comment]
Yeah, that's entirely possible :)
