### ISSUE TITLE
Dungeon loot still spawning when disabled

### ISSUE THREAD

**Issue by zachsai** [TeamPneumatic/pnc-repressurized#980]
### Describe the bug

Dungeon loot still spawning when disabled in config

### How to reproduce the bug

set to false, find desert temple, find loot

### Expected behavior

not be loot

### Additional details

![image](https://user-images.githubusercontent.com/63996164/159622626-86bf0e0c-e2a7-4917-84e6-54da0042b243.png)
![image](https://user-images.githubusercontent.com/63996164/159622638-695f9098-610b-452c-99fb-ba502f5d7dda.png)

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
Yeah that config value is pretty much obsolete and I need to remove it.  The right way to control PNC dungeon loot now is via datapack: `data/pneumaticcraft/loot_modifiers/dungeon_loot.json`.

As discussed on Discord, right now you can modify which dungeon types PNC loot appears in and how common/rare it is, but the actual items are currently hardcoded in PNC.  But allowing items to be listed in JSON is planned.

**Comment by desht** [comment]
Fixed in 3.1.3, fully data-driven dungeon loot tables.
