### ISSUE TITLE
Crash on air grate placement

### ISSUE THREAD

**Issue by Vane79** [TeamPneumatic/pnc-repressurized#981]
### Describe the bug

If I try to place an air grate onto a tube, the game crashes.

### How to reproduce the bug

Create a world, place/fuel an air compressor, attach a couple of tubes, attach an air duct to a tube. 

### Expected behavior

For grate to be placed and a game to not crash.

### Additional details

forge-1.18.2-40.0.19, pneumaticcraft dist-1.18.2-3.1.2-66

### Which Minecraft version are you using?

1.18

### Crash log

https://pastebin.com/BPVZWW2g

**Comment by desht** [comment]
Ah, null entity filters were OK 1.16, but apparently not in 1.18.  Easy fix...

**Comment by desht** [comment]
Fixed in 3.1.3

**Comment by Guardian9978** [comment]
This same crash happens on 1.18.1.
Forge Version: 39.1.2
Mod Version: 3.0.0-53

Also the server crashes if the chunk with the grate is loaded.
I had to use MCEdit to delete the block in order to keep my server functional.

Any chance for a fix on 1.18.1 as well?

**Comment by desht** [comment]
Sorry, no.  1.18.1 is a dead-end version and mods need to be getting off it.
