### ISSUE TITLE
Drill and Laser crafttweaker recipes 1.16

### ISSUE THREAD

**Issue by blockgoblin31** [TeamPneumatic/pnc-repressurized#983]
### Describe the feature

a crafttweaker script for adding drill and laser assembly recipes. something like `<recipetype:pneumaticcraft:assembly_drill_laser>.addRecipe(name as string, IIngredientWithAmount input, IItemStack output)`

### Reasons why it should be considered

because it doesn't make sense to not exist

### Additional details

1.16

**Comment by HipHopHuman** [comment]
Drill & Laser isn't a special recipe type. It's just the separate Drill crafting step and Laser crafting step combined. If you setup a recipe that includes separate steps for both the drill and laser, it will appear as a combined "Drill & Laser" recipe.

**Comment by desht** [comment]
@HipHopHuman is correct, Drill/Laser is a synthetic recipe type used for sequential drilling & lasering.  Drill/Laser recipes are auto-created when a drill recipe for A to B and a laser recipe for B to C exists (like the standard Compressed Iron Block -> 20 Valves, and 20 Valves -> 8 Advanced Pressure Tubes give a Drill/Laser recipe of Compressed Iron Block -> 8 Advanced Pressure Tubes).
