### ISSUE TITLE
Problem with CC & Drone Interfache

### ISSUE THREAD

**Issue by pxsleep** [TeamPneumatic/pnc-repressurized#984]
### Describe the bug

I want to use CC to control drone.  setAction() “goto” and “standby” have no problem. But when I use setAction("pneumaticcraft:condition_redstone") ,  drone.evaluateCondition() can’t return currently. That’s always “false”
Or when running setAction("pneumaticcraft:condition_redstone") ,this client would crash.

### How to reproduce the bug

local drone = peripheral.wrap("left")
drone.addArea(-197, 64, -151) 
drone.setSides(true,true,true,true,true,true)
drone.setCount(0)
drone.setOperator(">=")
drone.setIsAndFunction(true)
drone.setAction("pneumaticcraft:condition_redstone")
repeat
	sleep(0.5)
until drone.isActionDone()
print(drone.evaluateCondition())
drone.clearArea()
drone.addArea(202, 64, -153,202, 64, -150,"filled") 
drone.setBlockOrder("highToLow")
drone.setSides(false,true,false,false,false,false)
drone.setRightClickType("click_block")
drone.setSneaking(false)
drone.setUseMaxActions(false)
drone.setAction("pneumaticcraft:block_right_click")

### Expected behavior

It  print true and, and the drone should automatically right click the block in Area.

### Which Minecraft version are you using?

1.16

### Crash log

https://pastebin.com/BsVX2t0p

**Comment by desht** [comment]
Yep, two genuine bugs there.  Should be fixed in build 314 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ if you would like to test that version.  Otherwise will be in next release (2.15.6, no release date yet).

**Comment by desht** [comment]
Fixed in 3.1.4 & 2.15.6 releases
