### ISSUE TITLE
Disabling Pneumatic Boots fall damage protection

### ISSUE THREAD

**Issue by Awesomespore** [TeamPneumatic/pnc-repressurized#987]
### Describe the feature

Pneumatic boots should have an option to enable/disable the fall damage protection and/or not try to prevent fall damage that would be prevented by another method (such as the feather feet potion effect from Botania or bunny hoppers from Artifacts.)

### Reasons why it should be considered

It doesn't feel right for pneumatic boots to waste air in order to prevent fall damage that would've already been prevented by other means. Sure, it doesn't use a lot of air to do so, but it's still wasting air for no reason, which is rather unsatisfying.

**Comment by desht** [comment]
Added in 1.19.2
