### ISSUE TITLE
Programmable Controller crashes from "Drone Condition: Pressure"

### ISSUE THREAD

**Issue by Awesomespore** [TeamPneumatic/pnc-repressurized#988]
### Describe the bug

Apologies for the lack of a crash report, but I think this is fairly straightforward anyway.

The Programmable Controller will crash the game if it is using a program that uses the "Drone Condition: Pressure" widget.

### How to reproduce the bug

Create a drone program that checks the drone's pressure via Drone Condition: Pressure
Insert this program into a programmable controller (with enough pressure to run the program), and hey presto, the game crashes.

### Expected behavior

I would expect the program to work as normal, checking the pressure of the drone (so by extension, checking the pressure of the programmable controller). Instead, the game crashes, quite possibly due to it attempting to check the minidrone's pressure rather than the programmable controller's pressure?

### Additional details

Mod version being used is 313, however I believe the same thing would happen in 315 as well.

(Only reason I'm not using 315 is because me and my friend haven't gotten around to updating the mod yet)

### Which Minecraft version are you using?

1.16

**Comment by desht** [comment]
Build 316 from https://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized-1.16/ should fix this if you're in a position to test that. Otherwise will be fixed in next release.

**Comment by desht** [comment]
Fixed in 2.15.7 & 3.2.0
