### ISSUE TITLE
Omnidirectional hopper doesn't drop it's inventory when broken in creative

### ISSUE THREAD

**Issue by Kevun1** [TeamPneumatic/pnc-repressurized#99]
Minecraft 1.12.2
Forge 2571
Mod version 0.2.2-102

1. Place omnidirectional hopper, and fill its inventory
2. Destroy it in creative mode
3. The items inside are voided, rather than dropped

**Comment by desht** [comment]
Confirmed.  This is actually the case for *all* PNC:R tile entities, not just the hopper.
