### ISSUE TITLE
Cannot create plastic sheet

### ISSUE THREAD

**Issue by Bonzay0** [TeamPneumatic/pnc-repressurized#991]
### Describe the bug

When trying to cool a "Bucket of Molten Plastic" in any shape or form, it will not cool and stay in molten form.

### How to reproduce the bug

Create molten plastic by using LPG and Coal in the "Thermopneumatic Processing Plant", transfer molten plastic into a bucket by right-clicking the plant with a bucket, try to "pour into the world" or cool with cooled framed inventory (chest).

### Expected behavior

the Molten Plastic will become a plastic sheet and the bucket will become empty.

### Additional details

The server is using the mod pack: "Valhelsia: Volatile - 1.18". 
The server also includes the following mods:
https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge
https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge
https://www.curseforge.com/minecraft/mc-mods/architectury-forge
https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator/
https://mrcrayfish.com/download?id=1e7a416f6388f7769e48eda25b963513727ddade

### Which Minecraft version are you using?

1.18

**Comment by desht** [comment]
What "performance" mods does this pack include?  Sounds like something has broken fluid block tick behaviour.

**Comment by Bonzay0** [comment]
The mod pack Valhelsia: Volatile was updated, ever since that update plastic can be created again.
"Version 1.0.4" works well.
