### ISSUE TITLE
Tag Filters don't get exported properly from Drone Programs

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#993]
### Describe the bug

When exporting a drone program to JSON, the tag filter settings are lost

### How to reproduce the bug

Create a tag filter
Make a small program using the filter as an Item Filter
Export

It'll come out looking like this: 

`
      {
        "name": { "type": 8, "value": "item_filter" },
        "x": { "type": 3, "value": 502.0 },
        "y": { "type": 3, "value": 42.0 },
        "id": { "type": 8, "value": "pneumaticcraft:tag_filter" },
        "Count": { "type": 1, "value": 1.0 },
        "tag": {
          "type": 10,
          "value": { "TagList": { "type": 9, "value": [{}] } }
        }
      },
`

### Expected behavior

Tag list to be preserved on export

### Which Minecraft version are you using?

1.16

**Comment by desht** [comment]
Mmm yeah, the current JSON<->NBT conversion code doesn't handle lists of string values (like the tags in a tag filter). I can fix that, though.

**Comment by desht** [comment]
Can you try out build 317 and see if it works for you?

**Comment by MuteTiefling** [comment]
Yep! Looks great, thanks :D

**Comment by desht** [comment]
Fixed in 2.15.7
