### ISSUE TITLE
Drone Programming: Import from JEI

### ISSUE THREAD

**Issue by MuteTiefling** [TeamPneumatic/pnc-repressurized#995]
### Describe the feature

Would be nice to have a way to pick a craft out of JEI and have it automatically place the ingredient filters. Perhaps you shift click the item in the programming area (much like clicking with a GPS tool to set a coordinate) and it opens the JEI menu. Click the plus next to a recipe and all items from that recipe get set as individual Item Filter pieces.

### Reasons why it should be considered

Currently doing a lot of recipe programming and it would just be nice to have a shortcut to setting the filters.

**Comment by desht** [comment]
Are you referring specifically to the Crafting progwidget here?  i.e. as a means to automatically create the item filter widgets it needs for the recipe?  I can see the value in that...

**Comment by desht** [comment]
How's this?

![output](https://user-images.githubusercontent.com/736831/165070833-28a6b6c7-99fd-4607-916c-d8659d545612.gif)

**Comment by MuteTiefling** [comment]
Not specifically, but it would be useful for that too. But right now I'm dealing with non standard crafts and I'm trying to get the drone to be smart about what it picks up so it can lay things out intelligently. Unfortunately that means making myself a list and searching for each item individually in the filter search. 

Like with the double GPS tool, if you (I think) shift click it in the programming area, you get one piece for each of the coordinates it stores.

So imagine I shift click a PNC capacitor there instead. The jei interface would come up, I'd see the pressure chamber recipe, and upon selecting it, I'd get one filter piece for each ingredient in the recipe. Three nuggets, a plastic, and a redstone (or whatever the default is. I've forgotten now).

**Comment by desht** [comment]
I think rather than shift-clicking the item into the programmer area, it would be better to just click the item in JEI itself (which automatically brings up the JEI recipe window).  At that point, clicking the "+" would create item filters for each input ingredient that JEI is currently displaying.

Which is very similar to what I've already implemented, except it wouldn't care about trying to fit them to an existing crafting widget.

**Comment by MuteTiefling** [comment]
Hrm. JEI isn't really accessible from the programming station though. Not sure how that would work

**Comment by desht** [comment]
Hmm?  Yes it is (assuming your screen resolution is OK) - look at the video I posted above, for example.

**Comment by MuteTiefling** [comment]
Huh. Missed the video. That's neat. And yeah, my programming window is either full screen (when I full screen minecraft) or so small I can't really use it since it only shows a couple widgets at once.

**Comment by MuteTiefling** [comment]
Ok, I retract my previous early morning grogginess induced comments. It's all good. >.< I do still have to fullscreen MC to make it this big, but I guess I forgot I was seeing JEI this whole time. 

![2022-04-25_10 16 27](https://user-images.githubusercontent.com/9543430/165107789-cd736757-737f-4c19-94e4-802aee6a9a8b.png)

**Comment by desht** [comment]
Added in 3.2.0 (for 1.18.2) and 2.15.7 (for 1.16.5)
