### ISSUE TITLE
New blocks that should be added

### ISSUE THREAD

**Issue by ilovehorrorcats** [TeamPneumatic/pnc-repressurized#996]
### Describe the feature

Air lamp: a lamp that has a high light radius (32+ blocks) that uses compressed air
Brewer: brews potions using compressed air and heat instead of blaze powder
Fluid and item ducts: two new blocks, item pipe and fluid pipe that transfers fluids or items and all pipes can be camoflauged (kind of similar to the hoppers)
Valve that can be activated by redstone that can shut off all pipes (heat, pressure, fluid, and item]
a pressure chamber that can support 20 psi

### Reasons why it should be considered

It will improve this mod and it is easy additions too

**Comment by desht** [comment]
* Air lamp: Kerosene Lamp already does this
* Brewer: maybe? but I'm not sure of the utility
* Fluid/item ducts: logistics tube modules already handle this
* Valve: Regulator Valve already shuts off pressure when given redstone. I don't see the need for shutting off item/fluid transfer.
* Pressure chamber @ 20 psi: what is the use case?

**Comment by ilovehorrorcats** [comment]
The thing for the air lamp is that it does not use kerosene it uses air pressure only. thx for the quick response :)
The use for a 20psi pressure tank is to store air at 20psi. It is like the 5psi pressure tank but upgraded so it can handel 20 psi
For the valve It took a bit to stop and I didnt wait for it to stop.

**Comment by ilovehorrorcats** [comment]
I am really liking this mod. It is unqique since it uses air pressure instead of something like rf or fe. Thx for pointing out stuff too.

**Comment by desht** [comment]
Glad you're enjoying the mod!

The Kerosene lamp is the mod's large-scale lighting solution, I don't plan to add an air lamp, sorry.

Just storing air at 20psi isn't enough justification for a tier 2 pressure chamber.

Potion brewing is something potentially more interesting, but it needs to be a lot more than just a pressure-powered brewing stand. It would to have some interesting and unique game mechanics - I'm open to ideas there.

**Comment by HipHopHuman** [comment]
I don't see the need for a potion brewing mechanic.

- The brewing stand can already be semi-automated in vanilla
- With drones and logistics, the vanilla method can be fully automated
- A maxed out Pressurized Spawner + a method of auto killing (Drones, Turrets) will give an unlimited supply of blaze rods that can be autocrafted into blaze powder.

**Comment by desht** [comment]
Going to close this one. I don't really see the need for any of these.

Note that if you want large-scale air storage at 20 bar, a chest full of Reinforced Air Canisters with a Charging Module pointing at it will provide that.  Even more so if you have CoFH Core in your pack and can enchant the canisters with Holding.
